### ISSUE TITLE
Links to hello world examples broken

### ISSUE THREAD

**Issue by kordek** [uber/deck.gl#1008]
In example's readme webpack/browserify hello world examples are described. Clicking on links results in 404, e.g.:
https://github.com/uber/deck.gl/blob/master/examples/hello-world-webpack2/README.md

Can't find these examples anywhere in the repo.

**Comment by ibgreen** [comment]
Links fixed. Moved to `examples/react` folder. If things don't work on master, try 4.1-release branch.
