### ISSUE TITLE
Crash if `shouldUpdateState` returns true on viewport active

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1015]
## Issue
If `Layer.shouldUpdateState` returns `true` with `changeFlags.viewportChanged`, the app will crash.

## Repro steps
Modify `Layer.shouldUpdateState` to
```
    return changeFlags.propsOrDataChanged || changeFlags.viewportChanged;
```
Run any example app.

## Cause

This issue is Introduced by the multi-viewport feature. At every render call, `LayerManager._activateViewport` calls `updateLayer` with the following `updateParams`:
```
{changeFlags: {viewportChanged: true}}
```
If `Layer.shouldUpdateState` returns `true`, it will invoke `Layer.updateState` and `Layer.updateAttributes` which expect `updateParams` to have non-empty `oldProps` and `props` fields, crashing the app.

The default `shouldUpdateState` looks for `changeFlags.somethingChanged` or `changeFlags.propsOrDataChanged`, both undefined in this case, therefore suppressing the issue.

@ibgreen

**Comment by jianhuang01** [comment]
Ib is working on this and have a PR. Forward to him.
