### ISSUE TITLE
queryVisibleObjects from arbitrary shape

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1022]
We have an application that needs to do `queryVisibleObjects` on a polygon.

* One idea is to add a final polygon layer as a `multi polygon` with a hole of the desired shape. 
* This way, they can mask out all the area they don't want to pick.
* They can manually filter out any objects belonging to the polygon.

It is a nice idea that would reuse our existing polygon rendering layer. The problem with this approach is that they would only want this masking polygon to be visible during picking.

**Comment by ibgreen** [comment]
@Pessimistress @1chandu

**Comment by ibgreen** [comment]
@georgios-uber

**Comment by 1chandu** [comment]
> It is a nice idea that would reuse our existing polygon rendering layer. The problem with this approach is that they would only want this masking polygon to be visible during picking.

Couple other alternatives to explore

1. We render this polygon as fully transparent so it is not visible during normal rendering but updates picking buffer. 

2.  This option may be complicated but something to think about, render this polygon layer to a FB and (this happens once when user decides the area), then use this texture as a mask when rendering to picking buffer (do not render if the sample from this texture is not a specific color), we have to make changes to `picking` shader module.

**Comment by ibgreen** [comment]
@1chandu - Yes, I believe there is a short term and long term solution here. I would say 1) is a candidate for the short term and 2) is a candidate for the long term.

For 1) a concern is that some layers check if color is (0, 0, 0, 0) and discard the fragment, to avoid touching the depthBuffer. But if the polygon layer is not doing that, and we have not plans to do it, then this might be an option.

For 2) We could consider stencil buffers, or an extension to picking that makes layers render in nullPickingColor. We could have a prop `pickingMask` or `pickable: 'mask'` that rendered a layer in null picking color, with a small extension to the picking module.

**Comment by ibgreen** [comment]
Possible with the new `layerFilter` prop
