### ISSUE TITLE
how to handle the event of right-click

### ISSUE THREAD

**Issue by asling** [uber/deck.gl#1042]
I have a new facility of right-click based on PathLayer of deck.gl in my project.  So how to do it?
Thanks all.

**Comment by 1chandu** [comment]
@ibgreen @Pessimistress 

We are working on a new module 'mjolnir' (https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/break-out-event-manager-rfc.md) to handle all mouse events. If you are working on master branch you can give this a try.

**Comment by Pessimistress** [comment]
@asling If you disable context menu on your app:
```
onContextMenu={event => event.preventDefault()}
```
`onClick` or `onClickLayer` callback should be fired on right click as well.

**Comment by 1chandu** [comment]
@asling , closing, please re-open if the issue is still not resolved.
