### ISSUE TITLE
Viewport does not update without changing `props.layers`

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1043]
`LayerManager.updateLayers` does not update layer context if `layers` array remains the same:
https://github.com/uber/deck.gl/blob/master/src/core/lib/layer-manager.js#L206

Then in `drawLayersInViewport`, instead of the provided viewport, the viewport from layer context is used:
https://github.com/uber/deck.gl/blob/master/src/core/lib/draw-layers.js#L183

This issue does not surface in our React examples, as we reconstruct the layers whenever the viewport updates. You may reproduce the problem by opening this document in the browser, and then commenting out this line:
https://github.com/Pessimistress/deck.gl-runkit/blob/382b5ded83d2b493ecb96dcde9f74d66cc1bdadc/src/template.html#L38

@ibgreen @1chandu

**Comment by 1chandu** [comment]
Need to be verified.

**Comment by Pessimistress** [comment]
Confirmed: fixed in alpha.22
