### ISSUE TITLE
ViewportTransitions for Multi-viewports

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#1052]
* Multi-viewport support is added through `viewports` ( immutable viewport objects array) prop on `DeckGL` component, for transitions to work these array needs to support viewport descriptors.
* Need to come up with minimum set of parameters that can be transitioned and all `ViewState` (FirstPerson, MapState etc) types should be able to derive from it.

**Comment by gnavvy** [comment]
Not sure if it is related to this issue but the layer-browser example is broken in mater. @1chandu 
<img width="648" alt="screen shot 2017-10-18 at 3 54 13 pm" src="https://user-images.githubusercontent.com/144743/31746485-9e1b206c-b41c-11e7-8da8-695dddc13e14.png">
^ in viewport-transition-utils.js:41

**Comment by 1chandu** [comment]
@gnavvy , no this isn't related, layer-browser should work without it, I will take a look.

**Comment by 1chandu** [comment]
Multi viewports are experimental in 4.2, we have a working `viewState` now (with all mapbox parameters and `position`) that is working for all type of viewport transitions (WebMercatorViewport,  FirstPersonViewport and ThirdPersonViewport). Moving out of 4.2

**Comment by 1chandu** [comment]
Multi-viewport transitions are working, added in #1099
