### ISSUE TITLE
viewport/controller - related issues for v4.2

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#1056]
- [x] 1. Temp fix for OrthographicViewport and PerspectiveViewport (https://github.com/uber/deck.gl/pull/1055)
- [x] 2. Move OrthographicViewport and PerspectiveViewport from being deprecated, update docs (https://github.com/uber/deck.gl/pull/1057)
- [x] 3. Remove the [default y-flip](https://github.com/uber/deck.gl/blob/master/src/core/viewports/viewport.js#L152) from the viewport, make it optional.
(https://github.com/uber/deck.gl/pull/1125)
- [x] 4. Fix the y-flipping issue in the graph, point-cloud-ply, and point-cloud-laz examples
~~- [ ] 5. Replace `OrbitViewport` with `ThirdPersonViewport`~~
~~- [ ] 6. Finish the ThirdPersonViewport implementation, having OrthographicViewport and PerspectiveViewport extend ThirdPersonViewport instead of the base viewport (ref: https://github.com/uber/deck.gl/pull/1030)~~
~~- [ ] 7. Create a new example as the test for the Perspective viewport 
(could use one of the point-cloud-ply/laz examples and remove the orbit-controller)~~
~~- [ ] 8. Add a document explaining the hierarchies and recommended practices of using the viewports~~

**Comment by gnavvy** [comment]
> Fix the y-flipping issue in the graph, point-cloud-ply, and point-cloud-laz examples

Regarding this issue, there is a seemingly redundant [y-flipping](https://github.com/uber-common/viewport-mercator-project/blob/master/src/web-mercator-utils.js#L237) operation in the viewport-mercator-project util, and in the base viewport class we are [y-flipping](https://github.com/uber/deck.gl/blob/master/src/core/viewports/viewport.js#L152) again regardless of whether the descendant viewport classes are cartographic or not. 
=> causing the f-flipping issue in non-mercator viewports. 

Plan:
1. Fix the makeViewMatricesFromMercatorParams function, remove the y-flip operation;
2. Bump viewport-mercator-project version, remove the y-flip operation in the base viewport in deck.gl

Not sure how many apps are directly depending on the viewport-mercator-project library that we might have to add a flag for backward compatibility. @ibgreen

**Comment by 1chandu** [comment]
CC: @jianhuang01 
@gnavvy can you please update this with whats remaining. Does the OrbitController/viewport changes (#1145) resolve any of the issues.

**Comment by gnavvy** [comment]
@1chandu confirmed on point-cloud-laz, point-cloud-ply, and plot examples, all worked as expected. will close this issue as 4.2 docs are tracked in https://github.com/uber/deck.gl/issues/1053
