### ISSUE TITLE
fail  to add grid-layer to the map.

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1064]
my deck.gl version is 4.1.5.  
when I add  grid-layer .
deck.gl deck.gl error during initialization of <GridLayer:'grid-layer'> TypeError: Cannot read property '1' of undefined TypeError: Cannot read property '1' of undefined
    at _pointsToGridHashing (1908:62)
    at pointToDensityGridData (1908:31)
    at GridLayer.getLayerData (1904:285)
    at GridLayer.updateState (1904:124)
    at GridLayer.initializeLayer (425:512)
    at LayerManager._initializeNewLayer (1878:654)
    at _loop (1878:509)
    at LayerManager._matchSublayers (1878:553)
    at LayerManager._updateLayers (1878:456)
    at LayerManager.updateLayers (1878:249).
const layer = new GridLayer({
      id: 'gridlayer',
      data,
      cellSize:cellSize
    });

**Comment by 1chandu** [comment]
@Wwangchen 

I am assuming it is crashing here : https://github.com/uber/deck.gl/blob/c70823742852cce767ab403844b3966afafc258c/src/layers/core/grid-layer/grid-aggregator.js#L55 , if not can you give reference to the code where it is throwing the error.

If you are not setting `getPosition` prop, it is going to use default prop `getPosition: x => x.position`, you need to make sure data you are passing has `position` field, if it is different you need to provide custom `getPosition` prop, hope that helps.

**Comment by Wwangchen** [comment]
Thank you. When I first clicked the map to generate the screengrid .The position is wrong. I  clicked the map again ,the position is right . I don't know why the first generate is wrong.

**Comment by Wwangchen** [comment]
@1chandu  Thank you. When I first clicked the map to generate the screengrid .The position is wrong. I clicked the map again ,the position is right . I don't know why the first generate is wrong.
I use mapbox and deck.gl to generate  screengrid  and so on.
