### ISSUE TITLE
updateTrigger: getElevation not being called on prop update

### ISSUE THREAD

**Issue by rorysedgwick** [uber/deck.gl#1065]
**Deck.gl v4.1.3**
**React v15.6.2**
**React-dom v15.6.2**
**Node v6.11.4**
Replicated issue in **Chrome v61**, Safari **10.1.2** and Brave **v0.19.53**

I am rendering a geoJson layer to show road traffic conditions, with extruded polygons that are intended to display one of two values (vehicle count, or miles per hour). Each polygon has both of these properties, along with the polygon geometry, e.g.:

```
"type": "Feature",
"properties" {
     {
        "timeIntervalId": "0",
        "timePeriodEnding": "00:14:00",
        "averageMPH": 40.25,
         "totalVolume": 47.75
    }
},
"geometry": {
    "type": "Polygon",
    "coordinates": [[]]
}
```

The user can select which value they want to be displayed, therefore changing the height of the extruded polygon. The updateTrigger for getElevation is not being triggered when props are updating. The getFillColor data accessor is using exactly the same syntax, and is updating colour based on the same property. See code below:

``` js
// this value correctly updating based on user input
const currentTrafficMetric = this.props.currentTrafficMetric;

<MapGL id='mapUI'
    <DeckGL {...viewport} layers={[
        new GeoJsonLayer({
        id: 'traffic-layer',
        data: this.props.currentTrafficCountData,
        filled: true,
        stroked: false,
        extruded: true,
        lightSettings,
       // my intended syntax was the following, as the updating currentTrafficMetric would return different values from the data object:
       // getElevation: d => d.properties[currentTrafficMetric]
       // even the following syntax does not call the getElevation updateTrigger, even though the prop is updating
       getElevation: d => currentTrafficMetric === 'averageMPH' ? 100 : 500,
       // this correctly updates the polygon color when props change
       getFillColor: d => currentTrafficMetric === 'averageMPH' ? [255, 225, 0] : [0, 0, 255],
       opacity: 1,
       updateTriggers: {
          // not triggered
          getElevation: currentTrafficMetric,
          // triggered
          getFillColor: currentTrafficMetric
        }
      })
    ]} />
</MapGL>
```

I started to wonder if elevation was not a property that could be re-drawn based on updateTriggers, but your documentation explicitly says so here: https://github.com/uber/deck.gl/blob/master/docs/advanced/updates.md

Any help much appreciated

**Comment by 1chandu** [comment]
@Pessimistress could this be related to https://github.com/uber/deck.gl/pull/971 ?

**Comment by Pessimistress** [comment]
Yes. We should cherry pick the PR to be in the next patch release.

**Comment by 1chandu** [comment]
Thanks, I marked #971 to be picked for next patch, @rorysedgwick will update here once a patch released with the fix.

**Comment by 1chandu** [comment]
@rorysedgwick , actually we have already released this fix in deck.gl 4.1.4 (https://github.com/uber/deck.gl/releases), I see you are using 4.1.3, please upgrade and re-open if it still exists.

**Comment by rorysedgwick** [comment]
@1chandu: I have upgraded to 4.1.5 and this is still an issue

**Comment by rorysedgwick** [comment]
@1chandu @Pessimistress in the meantime, can you offer any advice on the best way to force-trigger a re-render of the layer? I'm using Redux so the state is managed externally from the component. 

Essentially the layer needs to conditionally re-render based on a singe state property changing, and I looked into using `shouldComponentUpdate` to watch this but ended up writing loads of checks to ensure the rest of the rendering process happened correctly and I think would end up causing lots of wasted renders

**Comment by ibgreen** [comment]
@rorysedgwick 

* Submitting a new `props.data` array should do it (for instance by copying just the top level array, it should not be that expensive). That will trigger all vertex attributes to update and will thus be less performant, but should work until the fix is published.

* There is also a `props.dataComparator` (see docs on the base `Layer`) that you might be able to use to trigger full regeneration.

**Comment by rorysedgwick** [comment]
thanks @ibgreen, forcing the re-render using a dataComparator that always returns false has proved to be a workaround that isn't too much of a performance issue.

Just FYI, the first approach did not appear to work either - copying the data array using `newData = [...data]` and assigning to state did not trigger a re-render.

Thanks for the assistance

**Comment by ericsvendsen** [comment]
Ran into this bug as well with 4.1.5. I'm getting around it for now by changing the layer ID if the elevation value has changed.

**Comment by 1chandu** [comment]
Re-opening the issue.

@Pessimistress  #971 seem not fixing this issue, are there any other PRs we need to cherry-pick?  Can you take a look?

**Comment by 1chandu** [comment]
@heshan0131 does your PR (https://github.com/uber/deck.gl/pull/1092) fix this, any plans on re-open/merge this PR.

**Comment by heshan0131** [comment]
I have the fix in #1046, it is landed in master @rorysedgwick you can give it a try.

**Comment by heshan0131** [comment]
`4.2.0-alpha.18` and above should include the fix

**Comment by 1chandu** [comment]
Please test with latest alpha and re-open if still an issue.
