### ISSUE TITLE
DeckGL GeoJSON layer jumps around and is jagged

### ISSUE THREAD

**Issue by vicapow** [uber/deck.gl#1071]
I'm noticing some odd effects with the GeoJSON layer flickering and being jagged at higher zoom levels.

I put together [this codepen](https://codepen.io/anon/pen/mBZxOd?editors=0110) that demonstrates the issue.

Here's also a gif

![deckgl-rendering-bug](https://user-images.githubusercontent.com/583385/31971501-ffac1ae4-b8d0-11e7-84fc-ca67a6a71b1e.gif)

The layer, for quick reference:

````js
  layers: [
    new DeckGL.GeoJsonLayer({
      data,
      filled: false,
      stroked: true,
      extruded: false,
      fp64: true,
      lineMiterLimit: 10,
      lineWidthScale: false,
      lineWidthMinPixels: 10,
      lineWidthMaxPixels: 10
    })
  ]
````

And the GeoJSON I was using: https://gist.github.com/vicapow/ddab6493316253195ce779a153fb1e02

All the best,

**Comment by shaojingli** [comment]
So the fp64 fails again... not on my computer, probably on nvidia gpus
can you send over your "about this mac" window?

**Comment by shaojingli** [comment]
also, do you see any issues in your console or anywhere?

**Comment by 1chandu** [comment]
Yeah, just verified on my machine (AMD GPU), doesn't happen, @vicapow what is the GPU on your machine and any errors on console?

**Comment by contra** [comment]
Just curious - how do webgl game engines handle things like this? Never seem to see many problems with their rendering on these GPUs - or is it a fundamental issue with the cartographic projections on the GPU?

**Comment by ibgreen** [comment]
@contra If WebGL games wanted to show the entire earth and enable seamless zoom down to centimeter level they would have the same issue, that zooming in >1 million times exhausts the precision of 32 bit floats, which what the GPU offers (or more precisely, that's all that WebGL exposes).

Games are notorious for making short cuts and do clever optimizations to their world, for instance to fit coordinates in 16 bit shorts etc. And even other geospatial apps, like mapbox, serves every map tile with such a relative coordinate system adapted to that zoom level. Efficient in the GPU but more work when serving data.

The focus during deck.gl's design was on simple data analysis, we didn't want the user to have to change his data to make it work, so adding 64 bit support very was appealing.

Ironically, the most persistent problem with the 64 bit approach has actually not been bugs in the implementation itself but a surprisingly small thing: The basic math trick necessary to do 64 bit computation is something that triggers aggressive code removal optimizations in GPU drivers and shader compilers, and it sometimes feels like every new GPU requires a new trick to defeat the optimization.

**Comment by contra** [comment]
@ibgreen Thanks for the explanation, really helpful in understanding the root issue as somebody who doesn't work on the GPU usually

**Comment by vicapow** [comment]
Any update on this? Was hoping to start using DeckGL in a new project but this is a blocker.

**Comment by jianhuang01** [comment]
start to investigate this issue.

**Comment by jianhuang01** [comment]
Tested with Intel HD Graphics 630 1536 MB, can reproduce the problem. Will dig into the 64bits shader.

**Comment by jianhuang01** [comment]
Figured out a solution, will check in and release new version.
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/15093546/35171559-148d9136-fd19-11e7-840a-4ab120cb94dd.gif)

**Comment by ibgreen** [comment]
I believe this is fixed in 5.0.2. 

@jianhuang01 we need to update the github release log for patches https://github.com/uber/deck.gl/releases

**Comment by jianhuang01** [comment]
@ibgreen deck.gl 5.0.2 is not released yet, only released luma.gl, I am preparing deck.gl.

**Comment by vicapow** [comment]
Nice! Thanks, everyone
