### ISSUE TITLE
My first addlayer to the map ,the location is wrong.

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1076]
When I add the grid or trips to the map,the location is wrong.But When click the map,the location is right. I don't konw the reason.

**Comment by 1chandu** [comment]
@Wwangchen ,  is it wrong on app launch and correct when you interact with the map (resize, rotate, pan etc?).

Can you share some screen shots and more details about how you are adding gird/trip ?

**Comment by Wwangchen** [comment]
@1chandu Yes,it is wrong on app  launch.When I click the map ,the location is right.

**Comment by 1chandu** [comment]
@Wwangchen, its possible you are setting wrong initial value, you should compare your code with our example, are if you can share your code that sets up the layers I can take a look.

**Comment by Wwangchen** [comment]
@1chandu，Thank you for your reply. Do you know how to modify the tripsLayer width of the trajectory, by modifying the source code. I tried a lot but failed.  I konw the strokeWidth  has been abandoned.
