### ISSUE TITLE
Cleanup 'oldContext' usage in Layer class (updateState() and shouldUpdateState())

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#1077]
Based on discussions from  : https://github.com/uber/deck.gl/pull/1072

Layermanger passes, 'oldContext' to Layers method so layers can check for what changed in context and act accordingly. But this may not been properly implemented or being used by any layer, if so we should remove this code.

CC: @ibgreen

**Comment by ibgreen** [comment]
`oldContext` was removed in 5.2
