### ISSUE TITLE
How can I know map is dragging?

### ISSUE THREAD

**Issue by jacklam718** [uber/deck.gl#1079]

**Comment by kershnerd** [comment]
Did you figure this out?  I am trying to figure out that same thing...

**Comment by jacklam718** [comment]
@kershnerd 
Yeah. MapGL component has getCursor props, you can pass a function and get cursor event.
For example:
<MapGL>

**Comment by kershnerd** [comment]
@jacklam718 Any chance you know how to tell when a zoom ended?  The cursor.isDragging is working well for panning and rotation, but it isn't set for when I am doing a pinch zoom.

**Comment by jacklam718** [comment]
you can try `onViewportChange`

**Comment by jacklam718** [comment]
@kershnerd I'm not sure, you can try to workaround with `onViewportChange`
