### ISSUE TITLE
3D Pan/Tilt Not Working In Demo On Linux Chrome

### ISSUE THREAD

**Issue by rmackinnon** [uber/deck.gl#108]
Greetings,

Checked out the new demo page, and looks awesome. Found that pan/tilt though is broken in the demo for my client. Pressing CTLR, ALT, Shift, and combinations there in do not result in a change. Having seen "Trip Routing" and "ArcLayer" elsewhere I know that CTRL should work and allow for a change of view. All the layers display fine along with scroll/zoom.

OS: Linux 4.4.x
Client: Chrome Version 53.0.2785.143 (64-bit)

Let me know what debug info you need to squash this.

**Comment by ibgreen** [comment]
> Found that pan/tilt though is broken in the demo for my client. Pressing CTLR, ALT, Shift, and combinations there in do not result in a change

@rmackinnon 
This is due to event handling in `react-map-gl`, so better reported there. I think there might already be an open issue, you could add your comments to it. Adding a fix to support the keys you mention should be a small PR.

**Comment by rmackinnon** [comment]
Cool, I'll check out the upstream and report there if not already.  Didn't know if that was a control on your end or not.  Thanks for the reply man, I'll close this out. :)
