### ISSUE TITLE
how to add some custom icon?

### ISSUE THREAD

**Issue by jasonhe99** [uber/deck.gl#1108]
I want to add some custom icons to your trips example code,How do I add custom icon for mapbox ?
For example, on mapbox.com  add icons the following ,
var map = L.mapbox.map('map', 'mapbox.light');

var marker = L.marker([23, 40], {
    icon: L.mapbox.marker.icon({
      'marker-color': '#f86767'
    })
});

marker.addTo(map); 

please tell me, how to add to your this trips project?
which modify that js file ?

**Comment by 1chandu** [comment]
@jasonhe99  To show icons, you can use iconLayer, this can be in addition to other layers you have, so icons will be rendered and visible along with content from other layers.

**Comment by jasonhe99** [comment]
Thank you very much
Can you help me write a simple example, please?
Can you send me an iconLayer detail documentation of website?  tutorial ...

**Comment by ibgreen** [comment]
@jasonhe99 Sounds like you want to check out our website and `examples` folder
* https://uber.github.io/deck.gl/#/examples/core-layers/icon-layer
* https://github.com/uber/deck.gl/tree/4.1-release/examples/icon
