### ISSUE TITLE
Can't undestand how to change the layer of deck by zoom.

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1114]
I don't know if this is the right place to ask, but we are facing an issue in our project. When I change the map zoom by   button.  (map.zoomIn() )  The map'zoom  changed,but the layer of deck   did not.
I don't konw why and how to let them change at the same time when I click the button on the map.
I'm looking forward to your answer.

**Comment by 1chandu** [comment]
@Wwangchen you need to update viewport props on 'MapGL' and 'DeckGL' components.

https://github.com/uber/deck.gl/blob/8d3cd788c30879f6830302424a224f25867cfc11/examples/3d-heatmap/app.js#L48

In above example, if you call _onViewportChange({zoom: newZoomValue}) , zoom of the map and deckgl layers will be updated in sync.
