### ISSUE TITLE
Problems with Hexagon lightsettings when extruded: true

### ISSUE THREAD

**Issue by mf222** [uber/deck.gl#1116]
Hi, I've been trying to implement Hexagon layer with another dataset, and when I try the extruded: true, the visibility the hexagons overlap (the 3d effect is messed). I'm not sure if is because the lightsettings, I've tried different configurations, but the kind of look I'm trying to get is the one in the layer catalog (solid and no overlaped hexagons). If it's not the light settings, what else could be my mistake?

[Overlaped screenshot](https://imgur.com/a/pZSC0 "Overlap image") 

And the settings:
```
const LIGHT_SETTINGS = {
  lightsPosition: [-122.45, 37.75, 8000, -122.0, 38.00, 5000],
  ambientRatio:  0.3,
  diffuseRatio: 0.5,
  specularRatio: 0.9,
  lightsStrength: [2.0, 0, 0, 0],
  numberOfLights: 3
};
```

```
const hex = new HexagonLayer({
      id: 'hexagon-layer',
      data,
      radius: 800,
      visible: true, 
      pickable: true,
      opacity: 0.5,
      colorRange: [[255,255,178,255],[254,217,118,255],[254,178,76,255],[253,141,60,255],[240,59,32,255],[189,0,38,255]],
      extruded: true,
      elevationRange: [0,1000],
      elevationScale: 30,
      lightSettings: LIGHT_SETTINGS
});
```

Thanks in advance.

**Comment by ibgreen** [comment]
@mf222 You need to enable WebGL `depthTesting` to make sure that you don't render the hidden parts of the geometry. Can be done like this:
* https://github.com/uber/deck.gl/blob/4.1-release/examples/3d-heatmap/deckgl-overlay.js#L100
* https://github.com/uber/deck.gl/blob/4.1-release/examples/3d-heatmap/deckgl-overlay.js#L131
