### ISSUE TITLE
3.0.0-beta21 - q is not defined

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#112]
Publisher accidentally introduced an artifact into `dist/react/deckgl.js`

<img width="470" alt="screen shot 2016-10-18 at 5 21 23 pm" src="https://cloud.githubusercontent.com/assets/425716/19496861/8248e070-9557-11e6-9517-0952c2d219ac.png">

**Comment by ibgreen** [comment]
@contra - That's weird, I just installed and don't see this. Can you try npm cache clean on your side and see if it persists?

**Comment by contra** [comment]
I think npm might have served a corrupted zip on my last install or something. Fresh wipe and it works fine, sorry about the mis-issue.
