### ISSUE TITLE
If I want to change the line width of the tripslayer, I should modify where in the source code.

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1120]
First of all thank you for seeing my question. I find for a long time, but I do not know where in the source code to be modified, so as to ensure that  tripsLayer  line  width can be modified.

**Comment by 1chandu** [comment]
CC: @Pessimistress 
AFAIK trips layer doesn't support line width, it is an example we added but not yet part of the core layers. Instead, you can use PathLayer in your application and its `widthScale`prop to set path width. (https://uber.github.io/deck.gl/#/documentation/layer-catalog/path-layer)
