### ISSUE TITLE
Google Maps API sample

### ISSUE THREAD

**Issue by jaakla** [uber/deck.gl#1122]
Can you add a sample how to add deck.gl layers to Google Maps API? I would not be probably the only one interested on this.

**Comment by thatVaddiguy** [comment]
Hey did you figure out a way to integrate deck and google maps by any chance?

**Comment by MeTaNoV** [comment]
I would also be VERY interested since we plan to use https://github.com/apache/incubator-superset which is integrating deck.gl in their dashboards!

**Comment by Pessimistress** [comment]
For Google Maps users: if you check this file: 
https://github.com/uber/deck.gl/blob/master/examples/get-started/pure-js/app.js
The interface with Mapbox is fairly minimal. I imagine it wouldn't be that difficult to modify this example  to replace mapbox-gl with Google Maps API. We'd be happy to add it to the get-started templates if you open a PR.

**Comment by MeTaNoV** [comment]
@Pessimistress , thanks for the pointer, I did a quick experiment and of course there are issues...
Mainly:
- zoom levels are not strictly equivalent, and the one you use is the one of Mapbox
- it is currently impossible to rotate a Map with Google Maps
- tilt value range are also a bit different, and the one you use is the one of Mapbox
The result is sadly pretty unusable with G maps...

**Comment by Pessimistress** [comment]
@MeTaNoV 
You can disable rotation in deck.gl by setting:
```js
controller: {dragRotate: false}
```
See [documentation](http://deck.gl/#/documentation/deckgl-api-reference/controllers/controller).

Mapbox uses OpenStreetMap's [tile index system](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames). Google Maps is not open-sourced, and I have not researched its documentation. I do believe Google Maps also uses Web Mercator projection, so if there is a offset between the two zoom levels, it should be constant.

**Comment by ibgreen** [comment]
> is a offset between the two zoom levels, it should be constant.

Yes.

FWIW, I did a test integration a long time ago (don't have the code). I seem to remember that there is a 2x difference in zoom so adding or removing one to the zoom level fixed the (non-tilted) alignment.

I did not try changing pitch.

I recall there was an issue with one of Google Map's overlay types, there was tearing when panning the map, that I didn't have time to dig in to.

**Comment by MeTaNoV** [comment]
@Pessimistress and @ibgreen , thanks for the additional information, I will tinker a bit more with it and eventually raise a PR with the result.

**Comment by vnugent** [comment]
I'd also be VERY interested in this.  I'm using Mapbox geocoding service but their data is really lacking.  Per Google API ToS if I use their Geocoding API I have to switch to their maps as well.

**Comment by Pessimistress** [comment]
We are adding official support for Google Maps in v7.0 (currently in beta). See [example](https://github.com/uber/deck.gl/tree/master/examples/get-started/pure-js/google-maps).

**Comment by benderlidze** [comment]
any example on how to update layer visibility on google maps?
for example I want to update this layer id: 'airports'
How should it be with overlay.setProps({layers: []}) ?
Thanks
