### ISSUE TITLE
updateTriggers does not work for PolygonLayer->getPolygon

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1129]

**Comment by 1chandu** [comment]
@ibgreen @Pessimistress 
Is this same as : https://github.com/uber/deck.gl/issues/1065

**Comment by ibgreen** [comment]
In this case we need to invalidate all attributes when the getPolygon trigger fires as in general it means that the entire geometry needs to be rebuilt.

**Comment by 1chandu** [comment]
@ibgreen @Pessimistress is there any work needed or is this expected behavior?

If this is expected behavior should we clarify this in the docs? Also is #1065 same issue?

**Comment by 1chandu** [comment]
We need to check, if composite layer updating its sublayers when invalidate all triggered.

**Comment by georgios-uber** [comment]
I can verify that in the latest (alpha-19) updateTriggers still does not work as expected.

**Comment by 1chandu** [comment]
@heshan0131 does your PR (#1092) fix this, any plans on re-open/merge this PR.

**Comment by heshan0131** [comment]
#1046

**Comment by 1chandu** [comment]
@heshan0131 
#1046 is included in `4.2.0-alpha.18`, given @georgios-uber tested on alpha-19, this is still not fixed.

**Comment by heshan0131** [comment]
Sorry This is a different issue, #1046 fixes `getElevation` trigger. @georgios-uber you are talking about `getPolygon`. Yes this is still a issue. 

1. `PolygonLayer` currently does not pass `updateTriggers.getPolygon` to `SolidPolygonLayer`
2.  `SolidPolygonLayer` doesnt not check whether `updateTriggers.getPolygon` has changed to re calculate polygon geometry.

Before we have a fix out @georgios-uber you will need to always pass in a new data to `PolygonLayer` to trigger geometry recalculation

**Comment by 1chandu** [comment]
@georgios-uber is this resolved by #1162 ? Should we close it.

**Comment by georgios-uber** [comment]
Yes, it is fixed now.
