### ISSUE TITLE
how to get mapbox object? 

### ISSUE THREAD

**Issue by jasonhe99** [uber/deck.gl#1132]
mapbox fly example :https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/

how to get mapbox object? 

in mapbox example. I want to get map object.

var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-0.15591514, 51.51830379],
    zoom: 15.5,
    bearing: 27,
    pitch: 45
});

**Comment by jasonhe99** [comment]
at your souce code 
deck.gl/website/src/utils/map-utils.js

// fly to new viewport
const fly = (fromViewport, toViewport, duration, onUpdate) => {

how to use this fly function?

**Comment by 1chandu** [comment]
We are working on providing Mapbox flyTo style viewport animations. This features exists in master as experimental and you can check this example : https://github.com/uber/deck.gl/tree/master/examples/wip/viewport-animation

We will be adding more docs, but meanwhile all information to get started is here : https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/viewport-transition-rfc.md

**Comment by ibgreen** [comment]
See answer to #1137. Unfortunately, using flyTo on the mapbox map will not integrate well with deck.gl. As 1chandu says flyTo animations are being worked on for the upcoming deck.gl 4.2 release.
