### ISSUE TITLE
When I drag the map, the layer  color also changes

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1133]
![image](https://user-images.githubusercontent.com/23378127/32655213-aa753194-c647-11e7-9d80-533ef68d4491.png)
This is HexagonLayer .When I drag my map, The Layer's color will change.  I want to konw the reason.

**Comment by 1chandu** [comment]
@Wwangchen 
- Is this happening in your own application? Can you provide more details on how you set data for the layer.
- Can you reproduce this on any of the provided examples? (https://github.com/uber/deck.gl/tree/master/examples/3d-heatmap or https://github.com/uber/deck.gl/tree/master/examples/layer-browser)

**Comment by Wwangchen** [comment]
@1chandu 
const layers = [
      new HexagonLayer({
        id: 'hexagon-layer',      //  Canvas ID允许CSS中的样式定制。
        colorRange,
        coverage,
        data: this.getHistogramData(data),
        elevationRange: [0, 80],
        elevationScale: this.state.elevationScale,
        extruded: true,
        getPosition: d => d,
        lightSettings: LIGHT_SETTINGS,
        onHover: this.props.onHover,
        opacity: 0.8,
        pickable: Boolean(this.props.onHover),
        radius,
        upperPercentile,
      hexagonAggregator: pointToHexbin
      }),
    ];
    return <DeckGL {...viewport} layers={layers} onWebGLInitialized={this._initialize} />;

**Comment by 1chandu** [comment]
@Wwangchen , hard to say anything from the code you pasted. I would suggest check hexagon layer docs (https://uber.github.io/deck.gl/#/documentation/layer-catalog/hexagon-layer), check the provided examples, and start debugging the props that affect color, like `getColorValue`.

**Comment by ibgreen** [comment]
> data: this.getHistogramData(data),

If you change data, the ranges will be recalculated. As a start, verify that this function returns the **same** array on each call. @heshan0131
