### ISSUE TITLE
Graph visualisation example

### ISSUE THREAD

**Issue by QuantumInformation** [uber/deck.gl#1135]
I am wanting to visualise a graph in 3D starting on a x-y plane. Has anyone made one?
Use case has over 10k nodes and there are about 10-20k line connections between nodes. 

I also want certain heavily connect nodes to be higher on the z axis to help visualisation

**Comment by ibgreen** [comment]
@gnavvy might be able to give some pointers. 

@QuantumInformation I believe this was the [example](http://jerome.bousquie.fr/) you showed me.

**Comment by shaojingli** [comment]
@QuantumInformation Is the [graph example](https://github.com/uber/deck.gl/tree/master/examples/graph) in the example folder giving you some hints?

**Comment by QuantumInformation** [comment]
@shaojingli sorry haven't had a chance to play yet, ultra busy. But will have a client soon for this vis project so I hope to play soon.

**Comment by gnavvy** [comment]
@QuantumInformation the example @shaojingli pointed to is an example for rendering graph in 2D, it uses an OrthographicViewport and should be performant enough. Depending on how you'd like to visualize your graph in 3D (free 3D, or 2.5D with Z as depth that does not participate in the layout process), you might want to change the switch from OrthographicViewport to PerspectiveViewport.

**Comment by QuantumInformation** [comment]
Cool demo, I see its real-time movement and d3. Atm I don't need real-time interactions (I need to show 4000+ data points and force will crash I think). I just need an initial render than for the user to move about in 3d.

![image](https://user-images.githubusercontent.com/216566/32846632-9e4ccd10-ca1f-11e7-939b-c6b178e45eb2.png)
