### ISSUE TITLE
createElement was not found in 'react'

### ISSUE THREAD

**Issue by howardya** [uber/deck.gl#1136]
I have these errors when I added deck.gl to my existing project. Seems like deckgl.js is not using my react package. 

ERROR in ./node_modules/deck.gl/src/react/deckgl.js
102:16-29 "export 'createElement' was not found in 'react'

How should I overcome this error? Thanks.

**Comment by ibgreen** [comment]
Haven't seen this. We have plenty of examples that use react, do those work for you?

https://github.com/uber/deck.gl/tree/4.1-release/examples/hello-world-webpack2

**Comment by mrcodemonkey** [comment]
@howardya did you ever figure this out ?

**Comment by ibgreen** [comment]
@mrcodemonkey Sorry for closing this but there is very little info to go on here. 

I can only ask the seemingly obvious: Are you guys actually installing React in your apps?  React is a "peer dependency", it needs to be installed by the app. Use `npm ls` to debug what has been installed.

If that's not it, are you able to install and run the deck.gl examples? Compare with your app setup and see what is different.
