### ISSUE TITLE
How to get map object from plugin

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1137]
When I  import MapGL  from  " import MapGL, { SVGOverlay }  from 'react-map-gl';"
I don't know how to get the map from  <MapGL/>.
I need to get the map object to do other operations.
Looking forward to your answer

**Comment by ibgreen** [comment]
> I don't know how to get the map

This is described in the [docs](https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=methods)
