### ISSUE TITLE
Use deck.gl in combination with WebGL Globe

### ISSUE THREAD

**Issue by dleitner100** [uber/deck.gl#1141]
I'm wondering if it is possible to map the visualization from my deck.gl application to a basic WebGL Globe (https://experiments.withgoogle.com/chrome/globe). How would I do that?

**Comment by ibgreen** [comment]
It's a fun idea! 

A possible starting point would be the fact that all layers use a common `project` "shader module" to transform their coordinates, so in theory it should be possible to extend or replace this module with code that does spherical projections. 

It would be a fun project, but would require a fair bit of effort, and the required 3D math should provide for some fun mental gymnastics. 

If you really want to try, the shader module gets uniforms from the `Viewports` classes so you'd want to get up to speed on those as well.
