### ISSUE TITLE
why glsl not fwidth function?  i'm use chrome62. webgl version is 2.0

### ISSUE THREAD

**Issue by dytmh** [uber/deck.gl#1142]
why glsl not fwidth function? i'm use chrome62. webgl version is 2.0

**Comment by ibgreen** [comment]
> why glsl not fwidth function? i'm use chrome62. webgl version is 2.0

Could it simply be that `fwidth` is part of GLSL 3.00 and you need to define `#version 300 es` as the very first characters of your shader?
See https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html

**Comment by ibgreen** [comment]
GLSL related follow up questions might be better to post in luma.gl
