### ISSUE TITLE
Why the map is undefined; When I use getMap();

### ISSUE THREAD

**Issue by Wwangchen** [uber/deck.gl#1144]
Firstly,   import   MapGL   from  'react-map-gl';
<MapGL
          {...viewport}
            mapStyle='mapbox://styles/mapbox/dark-v9'
			    //mapStyle= {beijingMerge}
          onViewportChange={this._onViewportChange.bind(this)}
          mapboxApiAccessToken={MAPBOX_TOKEN}
          onLoad={this.onLoadMapSource.bind(this)}
          removeMissingdivCss={this._removeMissingdivCss()}
          getMap={this._getMap}
        >
        </MapGL>
_getMap=(e) => {
     console.log(e)  //undefined？ 
}
I can't get the map object from  getMap(); And how to get the map object.
Looking forward to your answer ，Thank you.

**Comment by ibgreen** [comment]
@wwangchen  Looking at the [source code](https://github.com/uber/react-map-gl/blob/master/src/components/interactive-map.js#L205), I don't see `getMap` being a callback prop (the way your code is using it) but rather a function to be called on a react "ref".

Recommend moving this question to the react-map-gl repo. 

It sounds like the docs on `getMap()` function might need improving @abmai
* docs are missing on InteractiveMap
* StaticMap docs don't make it very clear that this needs to be called on a ref.
