### ISSUE TITLE
onHover/onClick `index` property missing from choropleths on 3.0.0-beta21

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#116]
<img width="388" alt="screen shot 2016-10-19 at 11 14 41 am" src="https://cloud.githubusercontent.com/assets/425716/19524899/4303097c-95ed-11e6-8fed-0803b4b8c801.png">

Works fine on beta17, beta21 is missing the `index` + `feature` attributes.

Other layers have the index attr but no object, this one is missing both so I figured I would open a different ticket since it probably stems from something else.

You can reproduce this on the example demo using any of the choropleth layers.

**Comment by ibgreen** [comment]
Fixed in beta22

**Comment by contra** [comment]
Just tested on beta22 - doesn't seem to be fixed. Same with #115
