### ISSUE TITLE
changing dot radius scaling? (3.x)

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#117]
Going to take a pass at doing some documentation for all of the layers + examples.

The logic for scaling the dots in scatterplots changed in the latest 3.x beta. Is there any info about how this works/is configured?

I know before the radius was a flat pixel size, I think now it works as meters width. Is this configurable? I can't seem to figure out how to override the scaling to do my own logic (min width/max width in pixels)

**Comment by ibgreen** [comment]
@contra - Correct. The `projection` shaderlib now enables all layers to work in both meters and lng/lat, and this also enabled us to specify extents in meters, so we tried that.

As you say it is of course also sometimes desirable to specify extents in pixels, but there is no prebuilt mechanism for doing this yet - it will require a touch of hand coding in the vertex shader.

I've not quite made up my mind what I think is the best approach. I was leaning towards preferring to have radius specified in meters, while allowing the app to specify a minimum pixel size for the point using a prop... that should be pretty easy to add to the current layer. What do you think?

**Comment by contra** [comment]
@ibgreen Size in meters with min/max pixel size solves all of my use cases. Biggest issue right now is being zoomed way out and having the dots be non-existent, and zooming way in and having them consume 50% of the viewport.

**Comment by contra** [comment]
How does all of this play in with strokeWidth for choropleth/arc/line? Is the plan to move those to the same system as well?

**Comment by ibgreen** [comment]
`strokeWidth` is a little harder to change, since it currently uses `gl.lineWidth` which is specified in screen pixels. 

We do have an `enhanced-choropleth-layer` that extrudes lines to thin triangle strips and yes this gives us that level of control (an also allows us to get clean "mitering"), so it is probably the way to go (i.e. eventually replace choropleth-layer with enhanced-choropleth-layer)

**Comment by contra** [comment]
@ibgreen Would that work for arcs too?

**Comment by ibgreen** [comment]
> Would that work for arcs too?

Arcs require 3D extrusion (think a thin "tube" rather than just a flat strip), so we need to create more triangles, and mitering (joining) tubes requires a bit more care than joining flat strips. But yes, we could absolutely have a layer that "tessellates" arcs.

**Comment by contra** [comment]
Couple of examples with 3.x:

There's 25K dots on this map, but none of them are visible due to the scaling.

![image](https://cloud.githubusercontent.com/assets/425716/19693668/5e8d8bc4-9aaa-11e6-967a-99fbeb5b0bf2.png)

Zooming in more makes them kind of visible, but still way too small.

![image](https://cloud.githubusercontent.com/assets/425716/19693714/7a3dbc9a-9aaa-11e6-8755-89dccb94a6b4.png)

Zoom in a little bit more and they become huge.

![image](https://cloud.githubusercontent.com/assets/425716/19693746/905934f0-9aaa-11e6-84dc-00960049004f.png)

**Comment by ibgreen** [comment]
@contra There are two ways to set the radius - `getRadius` accessor returns radius in meters of that particular point (default 1) and `radius` is a multiplier (default 30).

You can make them visible in the zoomed out mode by making the radius bigger, but they will of course become even bigger as you zoom in.

We could change the layer to work differently, or have more options - we just need to agree on how we want it to work.
- Do you want the points to always occupy a certain number of screen pixels, regardless of zoom?
- Would you like to be able to specify min and max sizes for them?
- etc...

**Comment by contra** [comment]
@ibgreen How do you feel about this? Feels a little funny mixing units but can't think of any other way.

```js
new ScatterPlot({
  radius: 3, // meters
  minRadiusPixels: 10 // pixels
  maxRadiusPixels: 10 // pixels
})
```

**Comment by ibgreen** [comment]
@contra - Yes this looks reasonable.
- Maybe `radiusMinPixels` etc in case we need to specify screen size limits on multiple props.
- These props could default to 0 and say 10000 (something big enough to cover today's screens).

**Comment by contra** [comment]
Will work on a PR, hopefully I can do this without having to mess with the shaders - no idea how to work on that stuff.

**Comment by ibgreen** [comment]
@contra Looking forward to the PR, but I do suspect it needs to be done in the shaders.

You need to make sure the props get set as uniforms when they change, declare the new uniforms in the vertex shader, then [clamp](http://www.shaderific.com/glsl-functions/) the intermediate scaled radius value in the shader.

You can always give it a try - it should be easy to just extend the existing code - and I have seen several people here getting hooked on shader programming after having their first ever go at modifying an existing deck.gl layer.

If not - maybe you can put together some of those layer docs we talked about, and I could give this a whirl :)

**Comment by mcnuttandrew** [comment]
I wanna plus one @ibgreen suggestion to modify the radius. I've have reasonably good success with correlating the zoom level the radius multiplier level
