### ISSUE TITLE
Update default blend function.

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#1176]
This issue to track and re-merge #1171 as it is reverted in #1175. We should merge this change once 4.2 is branched from master.

**Comment by ibgreen** [comment]
> We should merge this change once 4.2 is branched from master.

There is a way to merge it now. There is a new `DeckGL` prop [`initWebGLParameters` ](https://github.com/uber/deck.gl/blob/master/docs/api-reference/react/deckgl.md#initwebglparameters-boolean-optional) that defaults to `false`. 

Currently setting this prop to true automatically sets depth testing, better blending etc. The intention has been that we'd collect all the default GL prop setting changes under this prop. Then we can just change its default in 5.0.

 The changes in the reverted PR could have been applied to the settings in this new prop.

Note that most examples have been updated to use this prop, to avoid complicated GL initialization callbacks in the examples.
