### ISSUE TITLE
Fail to npm start

### ISSUE THREAD

**Issue by DataVisPurdue-JZ** [uber/deck.gl#1177]
After adding access token without <>, I proceed "npm start". However, it came out with this error. 
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
> @ start /Applications/MAMP/htdocs/deck.gl-4.1-release/examples/3d-heatmap
> webpack-dev-server --progress --hot --port 3030 --open

Configuration file found but no entry configured.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! @ start: `webpack-dev-server --progress --hot --port 3030 --open`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MYNAME/.npm/_logs/2017-11-21T03_04_21_298Z-debug.log

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

hope someone can teach me how to install properly.

**Comment by 1chandu** [comment]
I am assuming you already did either `yarn` or `npm install` ?

**Comment by DataVisPurdue-JZ** [comment]
@1chandu Thank you for replying me. I have solved it by ignoring the README second instruction regarding deleting the last line. 

The reason behind I am not sure yet but it works now lol.
