### ISSUE TITLE
4.2 missing uniform `selectedPickingColor`

### ISSUE THREAD

**Issue by heshan0131** [uber/deck.gl#1179]
in 4.1 there was a uniform `selectedPickingColor`, people have been using it in customized shader, comparing it to instancePickingColors to determine whether a vertex has been picked:

```
uniform vec3 selectedPickingColor;

float isPicked(vec3 instancePickingColors) {
 return float(instancePickingColors.x == selectedPickingColor.x
 && instancePickingColors.y == selectedPickingColor.y
 && instancePickingColors.z == selectedPickingColor.z);
}
```

**Comment by ibgreen** [comment]
I believe it is now handled by the picking shader module and called [`picking_uSelectedPickingColor`](https://github.com/uber/luma.gl/blob/master/src/shadertools/modules/picking/picking.js#L32)? 

* Maybe add a `#define selectedPickingColor picking_uSelectedPickingColor` to the picking module for backwards compat?
* Also handle the pickingColorValid?

I must say that `picking_uSelectedPickingColor` is pretty long, maybe `picking_uSelectedColor` would suffice? Should add a note to the API audit.

**Comment by 1chandu** [comment]
>Maybe add a #define selectedPickingColor picking_uSelectedPickingColor to the picking module for backwards compat?

Should this `#define` be in `picking` module, if so this still requires model to be created with `picking` module. We can just set this uniform as it was set in 4.1.

**Comment by ibgreen** [comment]
>  if so this still requires model to be created with picking module

OK I think you are right, maybe this is to support older shaders that don't use picking. Where was this uniform usually set before? In the layers? Could it still be set there? I think that before it was just a few layers that supported this.

**Comment by 1chandu** [comment]
> Where was this uniform usually set before? In the layers?
It was done in base Layer class, added it back in #1191
