### ISSUE TITLE
3d heatmap elevationheight data?

### ISSUE THREAD

**Issue by DataVisPurdue-JZ** [uber/deck.gl#1184]
Dear, 

Just stuck on the confusion of the 3d heatmap example. Where are the dataset controlling Hex's heights? 

Hope can be interpreted.

**Comment by 1chandu** [comment]
CC: @heshan0131 
Number of points that belong to the hexagon decide the height.

**Comment by DataVisPurdue-JZ** [comment]
Thanks Shan.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
