### ISSUE TITLE
Sharp line ends in path layer

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1194]
Pull down NVIDIA_PROBLEM_DEMO  branch, and run layer-browser example on computer which has discrete video card. Disable default ScatterplotLayer and enable PathMarkerLayer (Meter) under Experimental Layers, the red line has a sharp end.

<img width="856" alt="sharp_end" src="https://user-images.githubusercontent.com/15093546/33405894-092fd762-d51f-11e7-8706-727e82390587.png">

**Comment by 1chandu** [comment]
Here are my findings so far:
When used different color for each triangle:

**Good (Intel Iris Pro)**
![screen shot 2017-11-29 at 6 01 02 pm](https://user-images.githubusercontent.com/9502731/33410000-0acfb5d8-d533-11e7-9853-aca8b4520e1d.png)

**Bad (AMD AMD Radeon R9 M370X)**
![screen shot 2017-11-29 at 5 59 09 pm](https://user-images.githubusercontent.com/9502731/33410025-3073e8a4-d533-11e7-870d-edaa55df3706.png)

Offset calculation for bottom triangle is wrong, causing it move the vertex by some offset. Based on zoom level this affects one of the two vertices of bottom triangle. 

Also this offset in vertex is proportional to the width of the segment, here is the rendering after setting the `widthScale` to max:
![screen shot 2017-11-29 at 6 34 54 pm](https://user-images.githubusercontent.com/9502731/33410259-45f537a4-d534-11e7-927f-f4371c1789da.png)

So we need to focus on vertex shader instructions that use `widthScale`

**Comment by jianhuang01** [comment]
The spike on the end is caused by precision issue on mix function. but there is also precision issue when calculating the joint, which can make some other cases fail to render on any video card. For example:
with path:       
      [8584.484798702775, 6742.5945553739575],
      [2908.5139320879325, 429.453672569738],
      [8000.484798702775, 6742.5945553739575],
      [8000.485798702775, 6742.5945553739575],
      [5100.486798702775, 7742.5945553739575]

Bad result:
      
<img width="451" alt="spike" src="https://user-images.githubusercontent.com/15093546/33455762-e95259e8-d5d1-11e7-8394-26edf584d05d.png">

with Fix #1200 
<img width="367" alt="spike2" src="https://user-images.githubusercontent.com/15093546/33455952-8f3ee9fc-d5d2-11e7-9b08-1260d50952a0.png">

#1200 still didn't fix all the cases, for example:
with path
      [8584.484798702775, 6742.5945553739575],
      [2908.5139320879325, 429.453672569738],
      [8000.484798702775, 6742.5945553739575],
      [8000.484798702775, 6742.5945553739575],
      [8000.484798702775, 6742.5945553739575],
      [5100.486798702775, 7742.5945553739575]

<img width="604" alt="gap" src="https://user-images.githubusercontent.com/15093546/33456371-11205f9a-d5d4-11e7-84eb-9d94623e7cd5.png">
There is a gap on the top joint.
