### ISSUE TITLE
help me. i`m calculate screen coord in vertex shader but y is wrong.

### ISSUE THREAD

**Issue by dytmh** [uber/deck.gl#1203]
vec4 pos = normalize(gl_Position);
vec2 screenpos = vec2(pos.x * 0.5 + 0.5, pos.y * 0.5 + 0.5) * viewportSize; 
vec2 uv = screenpos / viewportSize;
vec4 color = texture2D(textureAlpha, uv);

textureAlpha size === viewportSize

i`m use gl_FragCoord.x/viewportSize.x in fragment shader is ok.
but in vertex shader myself calculate coord is wrong,   x is ok, y is wrong.
I'm going to use y as the color output.

framebuffer show image  (gl_FragCoord.y/viewportSize.y)
![_20171201085840](https://user-images.githubusercontent.com/4333197/33462997-db972960-d675-11e7-8574-fd09ae23b352.png)

other vertex shader (uv.y)
![_20171201085827](https://user-images.githubusercontent.com/4333197/33462998-dcdb689a-d675-11e7-99a3-14ec5363d569.png)

**Comment by 1chandu** [comment]
Why don't you pass texture co-oridnates to the shader?  It looks like you are doing viewport transformations in your shader, try to check deck.gl project shader module https://github.com/uber/deck.gl/blob/master/docs/shader-modules/project.md

**Comment by 1chandu** [comment]
@dytmh , doesn't look like deck.gl issue, please re-open with more details if you think so.

**Comment by balthazar** [comment]
[StackOverflow](https://stackoverflow.com/questions/tagged/deck.gl?mixed=1) is the place to ask this sort of question
