### ISSUE TITLE
Zooming and dragging viewport issue

### ISSUE THREAD

**Issue by balthazar** [uber/deck.gl#1246]
As soon as you try zooming and dragging, the viewport starts acting incorrectly.

Can be reproduced on the `3d-heatmap` example using the master and `start-local`command.

**Comment by shaojingli** [comment]
confirmed that I can reproduce it. Is it due to some version mismatch? @1chandu

**Comment by 1chandu** [comment]
Yes, this is a known issue in our examples, @jianhuang01 investigated this before. Once beta versions are release we can fix these issues.

**Comment by jianhuang01** [comment]
Root cause is that react-map-gl has version conflict with viewport-mercator-project under deck.gl/node_modules.

**Comment by 1chandu** [comment]
Update react-map-gl to 3.2.beta and viewport-mercator-project to 5.0. (Verify both versions with `npm ls`)
