### ISSUE TITLE
Turn off scatterplot radius scaling based on zoom

### ISSUE THREAD

**Issue by rimig** [uber/deck.gl#1259]
Is there a way to turn off the scatterplot radius scaling as the map is zoomed in/out?

Here's my data and props:

Point 1, radius=~3
Point 2, radius=100
minRadius=2
maxRadius=100
radiusScale=1

![image](https://user-images.githubusercontent.com/1369884/34185274-1ee9c33a-e4ea-11e7-8dea-5c44d7e4b70c.png)

Zoomed in (zoomLevel ~16), things look as expected:

![image](https://user-images.githubusercontent.com/1369884/34185336-68d856c8-e4ea-11e7-8d17-374d879822fa.png)

When zoomed out (zoomLevel ~10), my points are massively shrinking. 

![image](https://user-images.githubusercontent.com/1369884/34185436-e16cdd70-e4ea-11e7-921c-bc3bc8024ec2.png)

Is there a way to always have the points be the size I specify? What's the suggested way to handle this?

**Comment by ibgreen** [comment]
@rimig radius is specified in meters which scales with zoom, however there should be `minPixelRadius` and `maxPixelRadius` props, if you set them to same value you can control the point sizes in pixels. 

That affects the size of all the points in your layer. If you want different points to be different radius, you may need to do more work and calculate a zoom dependent `radiusScale` prop. Scale is `2**zoom` so it should be relatively easy to calculate a compensation factor.

**Comment by rimig** [comment]
Thanks! I'll close this out. 

It seems I get the behavior I want with something like `scale = 2 ** (15 - viewport.zoom);`

**Comment by do-me** [comment]
## Pydeck variant for zoom-based point radius

I was trying to get this working in pydeck but without success. As there aren't any error messages yet it's pure trial and error and hard to debug. 

How to do this for a simple `ScatterplotLayer`? I tried many different combinations with below parameters.

```python
import pydeck as pdk
import pandas as pd
import numpy as np

data = {
    'lat': np.random.uniform(-90, 90, size=10000),  # Generating random latitudes between -90 and 90
    'lon': np.random.uniform(-180, 180, size=10000),  # Generating random longitudes between -180 and 180
    'value': np.random.rand(10000)  # Generating random values between 0 and 1
}

df = pd.DataFrame(data)

view = pdk.data_utils.compute_view(df[["lon", "lat"]])

all_points = pdk.Layer(
    'ScatterplotLayer', 
    df, # df holds lat lon columns
    get_position=['lon', 'lat'],
    auto_highlight=True,
    get_radius="value*10000",        # static radius based on value column, should somehow respect zoom, how to pass param?
    #get_radius= pdk.ViewState().zoom*1000, # doesn't work
    #radius_scale = 5, # scales but expression with zoom level is missing
    #min_radius=2, # doesn't have any effect
    #max_radius=100, # doesn't have any effect
    opacity=0.9,
    pickable=True)

map = pdk.Deck([all_points],
          map_style= "light",
          initial_view_state=view)

# for jupyter
map.to_html("deleteme.html", notebook_display=True,iframe_height=800) 
```
