### ISSUE TITLE
4.2-alpha.30: deck.gl intercepting move events?

### ISSUE THREAD

**Issue by kvsivaraman** [uber/deck.gl#1264]
Using a custom mapbox react wrapper, my mapbox `this._map.on('move', function () {` callback gets called when I don't use `DeckGL`. 

When I render `DeckGL` as a child of the mapbox wrapper, this function only gets called very infrequently if at all. 

It is as if DeckGL is interfering with some move event that mapbox needs.

**Comment by kvsivaraman** [comment]
@Pessimistress - I talked to @ibgreen he suggested I check with you, in case you have any hunch...

**Comment by Pessimistress** [comment]
@kvsivaraman Without knowing how your custom mapbox wrapper works, I assume it's using Mapbox's native event handling. The DeckGL component listens to `pointermove` and `click` events for its hover and click functionalities. DeckGL renders a canvas the same size as the base map so it completely blocks any mouse interaction with the map below.
