### ISSUE TITLE
JSPrettier slows down on a few files

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1282]
One downside of including JSPrettier is that running tests take more time.  Since JSPrettier logs a lot it is possible to get a sense for what is happening: most files seem to lint quite fast but it gets stuck in a few places. 

* `examples/point-cloud-laz/worker/laz-perf.js`
* `examples/test/tree-shaking/dist/bundle.js`

As a first step, maybe those files could be excluded? Maybe excluding dist folders in general would handle the second case?

**Comment by balthazar** [comment]
Cleaning before linting could also be a solution, what is this `laz-perf` file exactly? It's generated right?

**Comment by ibgreen** [comment]
> Cleaning before linting could also be a solution

Wouldn't it feel bad to have to rebuild everything just because one needed to lint?

> what is this laz-perf file exactly? It's generated right?

Not sure about the laz-perf file maybe it is a big data file. Need to check with @gnavvy, but doesn't really matter I think, it should be ignored.

Isn't there a `jsprettierignore` file?

**Comment by balthazar** [comment]
Yes can do that too.
