### ISSUE TITLE
layers not rendering after updating to v5

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#1293]
happens sporadically, a refresh usually fixes it. digging deeper into the layers it seems like they get stuck at "awaiting state" in the lifecycle. everything is rendered, data is there. this happens on all layers i've tested, not just the geojson layer.

here are the props for the deckgl component, with the layer expanded:

![screen shot 2018-01-05 at 11 31 47 am](https://user-images.githubusercontent.com/425716/34618309-5542e09a-f20c-11e7-8018-438fb66530cc.png)

**Comment by ibgreen** [comment]
@contra - nothing else in the console? 

The most convenient explanation is that some kind of error during the lifecycle is preventing the layer from either being matched with a previous layer (in which case they would "share" state), or be freshly initialized (with a newly allocated state).

Your screenshot cuts just a little short so I can't verify that `state` is still `null`. Just to make sure that the `lifecycle` string is correct.

**Comment by contra** [comment]
@ibgreen Ah yeah, here is the rest:

![image](https://user-images.githubusercontent.com/425716/34618730-ab65d22e-f20d-11e7-9aa2-61224a229429.png)

Nothing in the console, no layers in seer either.

**Comment by contra** [comment]
Code, if it helps:

![image](https://user-images.githubusercontent.com/425716/34618819-fe06e70c-f20d-11e7-8bbd-6063bb9d6626.png)

**Comment by contra** [comment]
Further digging: `_onRendererInitialized` is never called, so `gl` stays `null` and no layer manager is ever created. `setProps` is being executed but calls noop when no layer manager exists.

**Comment by contra** [comment]
Even further digging, now into `luma.gl`: `start` is called on the animation loop, so it tries to create the gl context. To create the gl context it waits for the page to load then creates a canvas, which never resolves https://github.com/uber/luma.gl/blob/master/src/webgl-utils/create-canvas.js#L10-L17

This seems to be an easy fix - it should check if the page is already loaded and resolve true, otherwise wait for load. We load JS dynamically using webpack code splitting, so by the time luma.gl/deck.gl is loaded the onload event has already fired. I would also recommend not using `window.onload` since other crummy libraries will write over that attribute.

I'll send a PR to luma.gl in a moment.

**Comment by 1chandu** [comment]
`_onRenderInitialized` is called by luma.gl's `AnimationLoop`, is it possible the window is never loaded, in which case, this method is not called.
