### ISSUE TITLE
Valid data updates cause attribute invalidation

### ISSUE THREAD

**Issue by cmtoomey** [uber/deck.gl#1308]
Data being passed via state to HexagonLayer is not being rendered, and throws the an `invalidated all attributes` error, along with

`deck.gl: error during update of HexagonCellLayer({id: 'heatmap-hexagon-cell'}) TypeError: Cannot read property '3' of undefined
    at HexagonLayer._onGetSublayerColor (hexagon-layer.js:417)`

For valid data, what could be causing this?

**Comment by ibgreen** [comment]
@cmtoomey 

Looking at the [code](https://github.com/uber/deck.gl/blob/master/src/core-layers/hexagon-layer/hexagon-layer.js#L349), it seems that color lookup has failed. Did you provide a custom color scale?

@heshan0131

**Comment by cmtoomey** [comment]
@ibgreen Yes. This issue persists even with a custom color scale. It's the same one as in the [UK Road Safety Example](https://uber.github.io/deck.gl/#/examples/core-layers/hexagon-layer). 

My hex layer is nearly identical to that source.

**Comment by ibgreen** [comment]
As you can see in the code I linked, it seems pretty clear that the `colorScaleFunc` is failing and returning `undefined` or `null` instead of a color RGBA array. Make sure it is a valid function, that it can handle the range of values you are sending in etc. Can't really suggest much beyond that.

**Comment by cmtoomey** [comment]
@ibgreen @heshan0131 I've looked at the referenced code. The most obvious fix based on what the color lookup function is doing is to require an [r,g,b,a] for all custom colors. The problem is that this still fails. 

This also appears to cause some sort of intermittent hang in rendering of cells. Passing in valid data causes the app to hang with the same data being rendered for multiple state updates, AND then it proceeds to render.

**Comment by cmtoomey** [comment]
This rendering hang is present in both my code and the source pulled from the Uber Hex example (when using my data)

**Comment by heshan0131** [comment]
@cmtooney what props dod you pass in to the hex layer. Sometimes when the data passed in has empty field or nulls, this could cause the color domain calculation return undefined or null

**Comment by cmtoomey** [comment]
The props are the standard one found in the Uber overlay examples. 

I've tried a plan `<Heatmap viewport={viewport} data={data}/>`

I've also tried a `<Heatmap viewport={viewport} data={data.length > 0 ? data : [[0,0],[0,0],[0,0]]} />`

There are situations where the data prop is [], but setting a default doesn't seem to fix it.

**Comment by cmtoomey** [comment]
The source is published in my repo cmtoomey/vanish if you want to see it live.

**Comment by jianhuang01** [comment]
@cmtoomey Where is the example code? I didn't see repo cmtoomey/vanish

**Comment by cmtoomey** [comment]
https://github.com/cmtoomey/vanish

**Comment by jianhuang01** [comment]
Tested with Chrome 65, the hexagon layer is rendered correctly, didn't see any problem.
![image](https://user-images.githubusercontent.com/15093546/37362730-3e09872c-26b3-11e8-9b55-9ecc1b721ca2.png)
