### ISSUE TITLE
Missing reference to layerManager.queryLayer

### ISSUE THREAD

**Issue by LINKIWI** [uber/deck.gl#1310]
I'm seeing an error reported by Sentry:

```
TypeError: this.layerManager is null
  at value(/orion-web/:1:429152)
  at value(/orion-web/:1:428404)
  at x.prototype._updateComponent(/orion-web/:1:550905)
  at ct(/orion-web/:1:533523)
  at at(/orion-web/:1:531806)
  .... (remaining stack frames irrelevant)
```

Minified source context:

```
{snip} u=void 0===s?null:s;return this.layerManager.queryLayer({x:e,y:n,width:i,height:a,layerIds:u})}},{key:"_updateLayers",value:function(t){var  {snip}
```

Based on the breadcrumbs, it seems like this exception is thrown before `react-map-gl` is even able to render a map. This was produced on Firefox 52 on Windows 7. I'm trying to trace the source of the problem, which I believe is in deck.gl, and I'm more than happy to submit a patch.

This offending call is `this.layerManager.queryLayer`. The only reference I was able to find is in the [docs for `layer-manager`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/layer-manager.md#pickobjects) for `layerManager.queryLayer`, but this doesn't seem to appear [anywhere in the source](https://github.com/uber/deck.gl/blob/5.0-release/src/core/lib/layer-manager.js).

Has the relevant logic since been moved somewhere else? Alternatively, any assistance tracing the source of the exception would be greatly appreciated.

**Comment by 1chandu** [comment]
@LINKIWI `queryLayer` has been renamed to `pickObjects` in 5.0-release. The docs are referring to old names, will fix them, but you can see renamed method here https://github.com/uber/deck.gl/blob/1d4280285abf126290ce428cdc4bec2a0c52deec/src/core/pure-js/deck-js.js#L173

If your application is using deck.gl 4.1 you can checkout 4.1-release branch to debug.
To see whats changed in 5.0 you can see these docs :
upgrade-guid: https://uber.github.io/deck.gl/#/documentation/overview/upgrade-guide
whats-new: https://uber.github.io/deck.gl/#/documentation/overview/whats-new
