### ISSUE TITLE
Outlines not drawn for polygon layer

### ISSUE THREAD

**Issue by IGlautier** [uber/deck.gl#1315]
## description
Polygon layer does not appear to draw outlines around polygons even when stroked is true.

## versions
"deck.gl": "^5.0.2",
"luma.gl": "^5.0.1",
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-map-gl": "^3.2.0",

## reproduction
https://github.com/IGlautier/deck-gl-line-repro

**Comment by Pessimistress** [comment]
@IGlautier try change `getColor` to `getLineColor`.

**Comment by IGlautier** [comment]
@Pessimistress No luck with that either.

**Comment by IGlautier** [comment]
Fixed thanks @Pessimistress
