### ISSUE TITLE
Changing line width in the trips example: not working

### ISSUE THREAD

**Issue by nauhc** [uber/deck.gl#1331]
There is a line `strokeWidth: 2` in the deckgl-overlay.js implementation.
But changing the setting does nothing. 
The trips-layer.js renders with `drawMode: 'LINES'`. 

How to draw with functional width settings?
Or is there any examples of drawing lines with triangles using luma.gl?

**Comment by jingsam** [comment]
I encountered the same issue.

**Comment by jianhuang01** [comment]
The line width is limited by hardware, usually is 1 because we are using 'LINES' drawMode for rendering. Our path layer can support width settings.

**Comment by shaojingli** [comment]
@nauhc @jingsam have you tried to use the path layer? they are width settings

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)

**Comment by Kyngo** [comment]
This shows as checked in #2523 but doesn't work yet on 6.4.9.

**Comment by ibgreen** [comment]
This was implemented in deck.gl 7.0
