### ISSUE TITLE
Need help on trips layer data

### ISSUE THREAD

**Issue by anggakhrsma** [uber/deck.gl#1332]
In example folder the trips layer data is using json file as data with [lng, lat, timestamp] format for the paths. But in deck.gl website the data is using encoded polyline format.

I downloaded trips layer in the example folder. I tried using [lng, lat, timestamp] format and it works fine. The problem is, with 10k trips the json file is around 40MB.

So i created a json file like in the example but the segments are encoded polyline instead of [lng, lat, timestamp] format. And then decode the polyline in the `requestJson()` method and add timestamp in each coordinate.
In the console and react state I can see the format is the same with json file from the example, but it doesn't render the paths.

Can you guys help me on this?
I noticed that you guys using worker to decode the polylines on the background, could you share the code that used in the website?

Thanks.

**Comment by jianhuang01** [comment]
demo code:
deck.gl/website/src/components/demos/trips-demo.js

Decoder code:
deck.gl/website/src/static/workers/trips-data-decoder.js
