### ISSUE TITLE
Infinite layer redraw when using GeoJSON with stroked: true

### ISSUE THREAD

**Issue by ex3ndr** [uber/deck.gl#1333]
I have found that deck.gl became to redraw layers on every frame and found that LayerManager's `needsRedraw` always return name of the polygon outline layer. Just disabling stroke in the layer solves a problem.

This issue cause huge performance impact in almost all of our visualisations. We have only ~50k vertexes in our polygons and it became dead slow at MBP 15 with external video with stroke enabled.

**Comment by Pessimistress** [comment]
@ex3ndr I can't reproduce this issue. Are you able to share the props used for your GeoJson layer?

**Comment by ibgreen** [comment]
>  found that LayerManager's needsRedraw always return name of the polygon outline layer.

@ex3ndr 

Sounds like you have already been able to debug and pinpoint this to a significant extent. 

FWIW, you can experiment with opening the console and setting the `deck.log.priority` variable to e.g. 1, 2, or 3 for increasingly more logging, to help you detect what is causing unnecessary redraws. It should for instance be able to tell which "prop" is changing each render.

**Comment by ex3ndr** [comment]
I tried to dig deeper. It seems that problem is only when i use GeoJSON with MultiPoligons and stroke enabled and i can't see stroke at all. Changing to Poligons will show strokes.

Setting priority to 3 log growing until i switch the tab with messages:
```
deck.gl RENDER #271 2 (of 3 layers) to screen because maps-polygon-outline (0 hidden, 1 composite 3 unpickable)
log.js?3527bb0:45 deck.gl viewportChanged: Viewport changed in maps
log.js?3527bb0:45 deck.gl Composite layer reused subLayers GeoJsonLayer({id: 'maps'}) (2) [SolidPolygonLayer, PathLayer]
log.js?3527bb0:45 deck.gl viewportChanged: Viewport changed in maps-polygon-fill
log.js?3527bb0:45 deck.gl invalidated all attributes for maps-polygon-outline
log.js?3527bb0:45 deck.gl invalidated all attributes for maps-polygon-outline
```

Also i have checked if any of props are changed - nothing is changed and render of my components are method is not invoked at all.

My props for the layer:
```
id: 'maps',
stroked: true,
filled: true,
extruded: false,
wireframe: false,
pickable: true,
opacity: 0.8,
fp64: false,
getFillColor: this.getFillColor,
getLineColor: this.getLineColor,
onHover: this.onHover,
onClick: this.onClick,
data: this.state.data,
updateTriggers: {
     getFillColor: this.state.selected
}
```

**Comment by ibgreen** [comment]
Just checked. It looks like `examples/layer-browser` has a [`MultiPolygon`](https://github.com/uber/deck.gl/blob/master/examples/layer-browser/data/sample.geo.json?short_path=6ca5829#L122) in its data set for the geojson layer. Just a thought: if you could reproduce the issue there, it would give us a great start on fixing this.

**Comment by ex3ndr** [comment]
Ok, i found a problem. That was on my side, but behaviour still very strange. I was missed one level of arrays when changing from Poligons to MultiPoligon. But no error was raised and it still render all polygons well....
