### ISSUE TITLE
Server Side Rendering creates global "window" object during import

### ISSUE THREAD

**Issue by ex3ndr** [uber/deck.gl#1335]
Right after importing react-map-gl object "window"object "window" in the global scope appears and this breaks a lot of stuff on the server side.

```
console.warn(typeof window);
import 'deck.gl';
console.warn(typeof window);
```

Will output
```
undefined
deck.gl 5.0.2 - set deck.log.priority=1 (or higher) to trace attribute updates
object
```

Workaround is to use dynamic imports and do not import `deck.gl` directly.

**Comment by ex3ndr** [comment]
Workaround (canUseDom is my helper variable):
```
let w = typeof window === 'undefined' ? undefined : window;
import * as Deck from 'deck.gl';
if (w && !canUseDOM) {
    window = w!!;
}
```

**Comment by ex3ndr** [comment]
Seems to be fixed at webgl-debug!

**Comment by 1chandu** [comment]
CC: @ex3ndr 
Closing this , opened this issue on luma.gl : https://github.com/uber/luma.gl/issues/394
