### ISSUE TITLE
`pickObjects` throws assertion error due to NaNs for ScatterplotLayer

### ISSUE THREAD

**Issue by rsolomon** [uber/deck.gl#1344]
Within `pickVisibleObjects`, `getUniquesFromPickingBuffer` is creating an Array of `pickInfos`. None of these have an `x` or `y` value (they only have `pickedColor`, `pickedLayer`, and `pickedObjectIndex`). Because of this, the first Array arg passed to `createInfo` has `NaN`s, which throws inside of `pixelsToWorld` when it asserts that the Array values are finite numbers.

Note that `pickObject` (singular) works fine with the exact same arguments.

**Comment by rsolomon** [comment]
I believe the bug is in `getUniquesFromPickingBuffer`, which states that it "Returns array of unique objects in shape `{x, y, pickedColor, pickedLayer, pickedObjectIndex}`".

It sets each point using the following code:

```
uniqueColors.set(colorKey, {
  pickedColor,
  pickedLayer,
  pickedObjectIndex: pickedLayer.decodePickingColor(pickedColor)
  });
```

So I don't see how `x` or `y` would possibly have been set. It's strange because the whole premise around its use is based on the existence of those coordinates, and the function hasn't been modified for months.

**Comment by ibgreen** [comment]
Confirmed, this is reproducible in layer-browser example on both master and 5.0-release. 

Crashes in `pixelsToWorld`.

@1chandu @Pessimistress

**Comment by rsolomon** [comment]
Created https://github.com/uber/deck.gl/pull/1345 , with the caveat that I'm not 100% sure that it's the correct approach. It does seem to fix the problem.

**Comment by ex3ndr** [comment]
Same here in other layers too
