### ISSUE TITLE
detect non-hovering state change? (3.x)

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#136]
In previous versions, you could detect hover/non-hovering over a data item because onHover was called for every mouse movement, so `hovering = event.index === -1` was enough to keep the cursor in sync.

With the latest 3.x (beta28), the onHover seems to only be called when the item is actually being hovered over, which is great for performance but doesn't let you know when the state changes from hovering -> not hovering. What's the recommended way to keep the cursor in sync with this new change?

**Comment by ibgreen** [comment]
@contra - This is an unintended side effect of the picking refactor - previously we were always doing a picking check on every layer - in the new version we only check picking until we find a match. Agree that we need to send a -1 index on deselection, will have to consider how to handle this, maybe we need to add picking state to the layer manager.

**Comment by ibgreen** [comment]
@contra Just published rc1 which should fix this. Also has new hover/click callbacks on the react component: https://github.com/uber/deck.gl/blob/dev/docs/using-with-react.md in addition to the layer callbacks.

**Comment by spiderdab** [comment]
sorry if I'm not understanding.
At the moment (deck.gl version 8.8.15) what is the way to check when not hovering an item?
