### ISSUE TITLE
Error while initializing GridLayer with large data set and small cell size.

### ISSUE THREAD

**Issue by Warkst** [uber/deck.gl#1360]
I'm trying to display a `GridLayer` with 176665 data points that _should_ be spaced 200m apart. The data points are generated from a project I'm working on as a 200x200 grid, so the positions should be solid. If I specify the GridLayer's cell size property with a value of 200 , I get an error when adding it to the layers of a `DeckGL` instance:

```
 RangeError: Maximum call stack size exceeded
    at BinSorter.getMaxCount (bin-sorter.js:113)
    at new BinSorter (bin-sorter.js:47)
    at GridLayer.getSortedColorBins (grid-layer.js:302)
...
```

If I change the cell size to a larger number (e.g. 300 or higher), there is no problem. I haven't done extensive testing to determine the exact cell size when the problems start but I can guarantee it happens at 200.

I would like to have the cell size at 200. My ideal GridLayer just renders a fixed-size 200x200 grid with 1 data point per cell and a custom `getColorValue` implementation to colorize the raster. Right now I have to use a larger cell size, meaning I lose information (at a cell size of 400 e.g., I'm losing 3/4th data points as 4 points fall into the same cell). Is this possible or am I using too much data?

I've attached a zip of a fresh, minimal react project that shows the behavior, so you can play around with the cell size value yourself, mapbox access token included. Should be as simple as unzip, `npm install` and `npm start`. Click the button "Add grid" to add the gridlayer and have the console open to inspect the error.

[minimal-test.zip](https://github.com/uber/deck.gl/files/1673653/minimal-test.zip)

**Comment by ibgreen** [comment]
@heshan0131 Looks like another case where calling `Math.max(...data)` breaks on long arrays.

**Comment by jianhuang01** [comment]
@Warkst Thanks for reporting the bug and the test example, I can reproduce the issue, will fix it and publish patch release at the end of this week.

**Comment by Warkst** [comment]
You're very welcome and thanks!
