### ISSUE TITLE
Error in docs: default value for extruded key in HexagonLayer

### ISSUE THREAD

**Issue by LINKIWI** [uber/deck.gl#1369]
Source defaults `extruded` to false here: https://github.com/uber/deck.gl/blob/94b20952de18bbf8cea28ce4acebd32224fd1321/src/core-layers/hexagon-layer/hexagon-layer.js#L50

The docs for `HexagonLayer` state it should default to `true` here: https://uber.github.io/deck.gl/#/documentation/layer-catalog/hexagon-layer?section=render-options

I'm happy to submit a PR to patch this. Should the default actually be `true`, or is this just a typo in the docs?

**Comment by ibgreen** [comment]
@1chandu @heshan0131 My assumption is that extrusions/2.5D are an "optional" feature and should be "off" by default for our layers. We usually favor consistency. 

Maybe check & if needed make a note in our dev-docs/API Guidelines
