### ISSUE TITLE
Async Props (data-url RFC)

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1372]
Implement [data-url RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.3/async-props-rfc.md) to support async props.

Summary: ability to provide a URL to certain props like `data`, deck.gl automatically loads, layer only sees loaded data not URL string.

- [x] LayerState introduction #1382
- [x] Prop rewriting, async props
- [x] Tests
- [x] Update examples
- [x] Docs, What's New

**Comment by ibgreen** [comment]
This could probably go into 5.2 but until we have assess risk of breaking backwards compatibility, keeping it in 6.0 milestone

**Comment by ericsoco** [comment]
Have you all made any decisions about type analysis yet? We (@heshan0131, @btford, and I) have had some issues with @uber/type-analyzer, and @btford has started on some improvements, but nothing has yet been finalized or solved.

**Comment by ibgreen** [comment]
> Have you all made any decisions about type analysis yet? 

@ericsoco You make an excellent point. The new loading system in v5.3 primarily focuses on JSON formatted data. It needs to be improved/expanded, and it would be really nice to have an easy way to integrate with `type-analyzer`. 

Sounds like a perfect topic for a micro-RFC. I will open a separate task where we can bounce ideas!
