### ISSUE TITLE
Extrude point/circle

### ISSUE THREAD

**Issue by RodionChachura** [uber/deck.gl#1375]
Is there a way to extrude circle/point without representing a circle as a polygon? When I am tried to extrude circle represented as a polygon in large zoom I have this result(the more zoom the worse result)
![1](https://user-images.githubusercontent.com/17750556/35736451-258e06de-0839-11e8-8647-b0c3f5a78351.PNG)

**Comment by MaksimMarkevich** [comment]
Same problem

**Comment by gnavvy** [comment]
Hi @RodionChachura, it seems like the precision issue for high dynamic range data, could you try to enable the fp64 feature as mentioned in the doc and see if it helps?
https://uber.github.io/deck.gl/#/documentation/layer-catalog/scatterplot-layer

**Comment by RodionChachura** [comment]
Hi @gnavvy, I tried fp64 and it makes a circle look a little bit better, but, when I have a circle with the radius less than 60 meters it still looks quite bad.

**Comment by jianhuang01** [comment]
@RodionChachura Can you make an small example and put it here? I will investigate that. Thanks!

**Comment by RodionChachura** [comment]
Hello @jianhuang01.
Steps:
1. Draw circle using [SVGOverlay ](https://uber.github.io/react-map-gl/#/Documentation/api-reference/overlay)and d3.js(number in tooltip - radius in meters)
2. Convert circle to polygon and draw it on SVGOverlay
3. Switch to Deck.gl [PolygonLayer](https://uber.github.io/deck.gl/#/documentation/layer-catalog/polygon-layer)

```
const layer = new PolygonLayer({
      id: 'polygon-layer',
      data: shapes.map_('deckPolygon'),
      filled: true,
      extruded: true,
      fp64: true,
      getElevation: f => buildingHeight,
      getFillColor: f => [33, 33, 33],
      lightSettings: LIGHT_SETTINGS
    })
```

I removed frames of waiting until deck.gl render circle.
![7 886](https://user-images.githubusercontent.com/17750556/35766264-e5348f1a-08e5-11e8-8b53-b9e699ff38ee.gif)
![21 958](https://user-images.githubusercontent.com/17750556/35766266-0faa02e8-08e6-11e8-8f99-bc32a81c375f.gif)
![39 269](https://user-images.githubusercontent.com/17750556/35766292-8a5886b8-08e6-11e8-8e56-ed330a71587c.gif)

![61 302](https://user-images.githubusercontent.com/17750556/35766271-2a9c031c-08e6-11e8-9fa0-da7cd9992e90.gif)

**Comment by Pessimistress** [comment]
You can try extending the `HexagonCellLayer`:
```js
import {HexagonCellLayer} from 'deck.gl';
import {Cylinder} from 'luma.gl';

class ExtrudedCircleLayer extends HexagonCellLayer {
  _getModel(gl) {
    return new Cylinder(gl, {
      id: this.props.id,
      bottomCap: true,
      nradial: 36,  // radial resolution - 6 in HexagonCellLayer
      nvertical: 1,
      isInstanced: true,
      ...this.getShaders()
    });
  }
}
```

[CodePen demo](https://codepen.io/Pessimistress/pen/ddMGyy)

**Comment by jianhuang01** [comment]
@odionChachura could be your converted data is bad rather than a bug in deck.gl, better to print out the points and verify first.

**Comment by RodionChachura** [comment]
I am decided to use mapbox layers and everything works fine now. You can also see this problem in Your NY trip examples.

**Comment by Pessimistress** [comment]
@RodionChachura Glad that you resolved the issue. Sounds like fp64 has a bug on your box. Would you provide your video card information so we can investigate?

**Comment by RodionChachura** [comment]
@Pessimistress, yes.
NVIDIA GeForce GTX 960M

**Comment by jianhuang01** [comment]
@RodionChachura Would you please paste your polygon point data here? so I can do a quick test.

**Comment by jianhuang01** [comment]
Need sample data to proceed, close for now.
