### ISSUE TITLE
DeckGL render fails if children contains `null`

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1377]
At this line: https://github.com/uber/deck.gl/blob/master/src/react/deckgl.js#L104

See [React.Children](https://reactjs.org/docs/react-api.html#reactchildren): child can be `null` or `undefined`.

**Comment by ibgreen** [comment]
> See React.Children: child can be null or undefined.

How about that... while the original `children` can of course contain `nulls`, I could never have imagined that React's hierarchical array iteration function would fail to filter out `null`s. 

Easy enough to work around though.
