### ISSUE TITLE
deck.gl demos crashes chrome on linux

### ISSUE THREAD

**Issue by krosaen** [uber/deck.gl#1397]
simply visiting [the deck.gl](https://uber.github.io/deck.gl/#/) homepage or any of the examples triggers an 'oh snap' in chrome.

https://bugs.chromium.org/p/chromium/issues/detail?id=809707 

Version 64.0.3282.119 (Official Build) (64-bit)

This might be a chrome issue (see issue filed above), but just in case this is of interest. FWIW no issues in Firefox.

**Comment by ibgreen** [comment]
@krosaen Thanks for reporting.

We don't have easy access to Linux platforms (mostly use Macs). Do you know if this worked before on your machine (i.e. on an older version of Chrome?). Another data point would be to check if it is also (still) broken on Chrome Canary? 

PS - I don't seem to be able to open the Chrome bug link right now, does it require special access?

**Comment by contra** [comment]
@ibgreen This might help you out with that - https://www.browserling.com/#pricing

Basically a VNC to any OS (mobile included) + browser you want, most are free - linux you have to pay though. Would be easy to test linux + chrome with this.

**Comment by ibgreen** [comment]
@contra Yes that is a great concept. The problem I have always encountered in the past with virtual machine testing rigs is that WebGL support is either non-existent or very poor, which makes it ill suited for our needs.  Do you have any indications that browserling or any other setup might have solved this?

**Comment by krosaen** [comment]
Hi, I just checked back and right now this is working on my Linux laptop with chrome. I'll re-open if this problem persists on my linux desktop next time I check.
