### ISSUE TITLE
Safari 11.0.3 WebGL1 onHover error: INVALID_ENUM

### ISSUE THREAD

**Issue by Warkst** [uber/deck.gl#1403]
I am using deck.gl in a react application. I use Safari to view the webpage during development. Despite all functionality working properly, I am getting an error in the console each time the `onHover` callback is triggered on a `GridLayer`:

> WebGL: INVALID_ENUM: bindFramebuffer: invalid target (track-context-state.js : 249)

This does not seem to be affecting performance or functionality, but it is probably still worth looking into.

On load, luma.gl states it's using a WebGL 1 context (not WebGL 2 like in chrome, where the errors do NOT occur, btw):

> luma.gl: WebGL1 context (Intel Inc.,Intel Iris Pro OpenGL Engine)

**Comment by ibgreen** [comment]
Confirmed, I was able to reduce this by opening the [GridLayer's documentation page](https://github.com/uber/deck.gl/issues/1403) in Safari.

We can take it from here, but if you want to poke around a little, try turning on the debug parameter `<DeckGL ... debug />`. If everything works it should put luma.gl in "synchronous" mode where it waits for return status for each WebGL call and throws an exception where it happens. By breaking on exceptions this could give you more precise information to report.

**Comment by Warkst** [comment]
I think I've managed what you asked. See attached screenshots of the debugger.
<img width="1241" alt="screen shot 2018-02-07 at 16 17 47" src="https://user-images.githubusercontent.com/1039594/35924130-79fc5256-0c22-11e8-863a-f0cf1dd7f7aa.png">

<img width="1243" alt="screen shot 2018-02-07 at 16 15 57" src="https://user-images.githubusercontent.com/1039594/35924059-4709eb74-0c22-11e8-975f-b3d6fcabb175.png">

**Comment by 1chandu** [comment]
This is a luma.gl bug, opened a new issue : https://github.com/uber/luma.gl/issues/435
Closing this.
