### ISSUE TITLE
OnHover 

### ISSUE THREAD

**Issue by orangebacked** [uber/deck.gl#1404]
Dear Uber Team,

First of all, I would like to congratulate you for this lovely framework you have developed, it is gorgeous! Nevertheless,  I've run into an impasse and would hope you can help me out guys.  I haven´t been able to understand how you display the properties of the bars in the hexagonLayer example you have displayed in your official webpage (the accidents in the UK visualization). The example that is available in GitHub doesn't have this functionality and the browser layer is a too intricate to for me.  I tried incorporating the layer-info component, but I don´t understand what is (info), and I keep getting this error : 

"Module parse failed: 
You may need an appropriate loader to handle this file type.
|
|      return (
|        <div id="layer-info">
|        </div>
|      );

Thank you very much for your time! I'm a newbie in react! I'm sorry if it's trivial.

**Comment by jianhuang01** [comment]
@orangebacked Welcome to deck.gl, from the error message you provided, it is hard to know what's going on. You can launch our website with github code, there you will find the bar control.

Go go deck.gl/website folder, do "yarn" or "npm install" to grab dependencies, type "npm run start" to launch our website.

Good luck!
