### ISSUE TITLE
Voyager

### ISSUE THREAD

**Issue by anggakhrsma** [uber/deck.gl#1410]
Hi guys,

https://www.youtube.com/watch?v=pjzCMQBqjFw&t=1343s
I saw this video about Voyager that was built on deck.gl. Do you guys have a plan to open-source the tool?
If not, can I make a tool that mimics Voyager and then open-source it?

Thanks.

**Comment by heshan0131** [comment]
Hi @anggakhrsma 

We are working on open sourcing Voyager. It's going to come out in the next 2 months. Cheers!

**Comment by heshan0131** [comment]
[![image](https://user-images.githubusercontent.com/3605556/36046833-27b46b50-0d8f-11e8-8e41-7af2268e773a.png)](https://twitter.com/DesigningUber/status/959446574559526913)

**Comment by heshan0131** [comment]
The estimated launch date of kepler.gl is end April early May. If you are interested you can sign up for early beta testing!

**Comment by akansal1** [comment]
@heshan0131  any update on kepler.gl release ?

**Comment by Rhishab** [comment]
How can I download this right now?
