### ISSUE TITLE
GPGPU: New layer to render contours.

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#1415]
- This will require : #1414 

#### To Do List 
  - [X] Add label and assign to milestone 
  - [x] Coding
  - [x] Test
  - [x] Docs

**Comment by 1chandu** [comment]
Planning: Moving to later milestone.

**Comment by chrisgervang** [comment]
This would be very handy for rendering ground textures (e.g. terrain mapbox api) :)

**Comment by 1chandu** [comment]
Need docs.
