### ISSUE TITLE
Controller Official API

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1422]
This PR involves aligning on a single set of controller classes, doing all necessary changes and getting the resulting code in a good state with official documentation, test cases etc that will make future maintenance and work on this part of the code easy.

This task does not include, but should represent a strong foundation for [RFC: per view controllers](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/per-view-controllers-rfc.md)

# v6.0
PART I:
- [x] Decide on Controller class hierarchy (merge States into Controller subclasses)
- [x] The current PureJS wrappers (`MapController` and `OrbitController`) are not needed and should be deleted.
- [x] Handle `TransitionManager` issues related to above.
- [x] Ensure Controller size matches first viewport size (rather than full screen).
- [x] Remove React `ViewportController`- The `ViewportController` React component is no longer needed and should be deleted.
- [x] Merge `State` callbacks into `Controller` sublasses
- [x] Update any remaining test apps.

FINAL STEPS:
- [x] Doc update
- [x] What's New Update

# v6.x
- [x] Document Controller Base class.
- [ ] Move Controller Base Class to mjolnir.js?

**Comment by Pessimistress** [comment]
Deprecation proposal for v6:
- `ViewportController` React component
- Deck: `onViewportChange` prop
- Deck: `viewport` prop
- Deck: `viewports` prop

@ibgreen

**Comment by ibgreen** [comment]
Agreed.

* `viewport` and `viewports` were already isolated to the React DeckGL component and are now calling `log.removed()`. 
* Removing support for `onViewportChange` but calling `log.removed()` if prop is detected to give user a hint about what he needs to do.
* Just removed `ViewportController` 

Upgrade Guide updated.
