### ISSUE TITLE
Coding help needed

### ISSUE THREAD

**Issue by Warkst** [uber/deck.gl#1441]
I'm not sure this is the right place to ask for help, so please feel free to close this "issue" and redirect me to the correct place, but I didn't know where to go so that's how I ended up here.

I'm using deck.gl in combination with react-map-gl. For my application, I would like to add a draw control so the user can draw lines/polygons. I've noticed there are some pretty nice plugins written for this purpose already so rather than reinventing the wheel I wanted to try to include it in my current setup. It didn't take much effort to add an instance of [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw/blob/master/docs/API.md) to the controls of the mapbox underlying react-map-gl, but the `.overlays` div introduced by react-map-gl is preventing the controls from working. I've found that if I hide that div manually using the development tools of the browser to set `visibility: hidden`, everything works. Obviously, hiding that div hides the layers added by deck.gl, which is not what I want. My guess is that the click events that the draw controls needs to function are being intercepted, but I'm not sure that's the real reason why it's not working.

I know the uber team is not responsible for the draw control nor for how it works, and I'm not asking that you "fix" this - I just want to check if either deck or react-map-gl (or both) intercept click events (maybe it's mapcontrollerjs?) and if so, how I can modify this behavior. For my purpose, it would be acceptable to disable the controls of deck/react-map-gl when the application goes into some "user-drawing" state and to re-enable them when the user finishes. Is this possible at all? It would help me a lot if someone would point me in the right direction here because I can't seem to figure it out.

Thanks!

**Comment by Warkst** [comment]
To follow up: I got things to work but the solution isn't pretty... So here's what I have currently:

```
<ReactMapGL>
    <DeckGL>
        <ReactMapGL ref={m => this.innerMap = m} className={'inner-map'}/>
    </DeckGL>
</ReactMapGL>
```

Then, in `componentDidMount`, I use the `ref` to add an instance of `MapboxDraw` to the map and register to the `load` event (which is fired when the styles are loaded) so I can access the layers, removing all of them except the ones that have an id starting with `gl-draw` (these are the layers that the draw component adds and needs to function).

```
        const innerMapRef = this.innerMap.getMap();
        innerMapRef.addControl(new MapboxDraw());
        innerMap.on('load' , e => {
                innerMap.getStyle().layers.forEach(l => {
                    if (!l.id.startsWith('gl-draw')) {
                        innerMap.setLayoutProperty(l.id, 'visibility', 'none')
                    }
                });
            }
        );
```

In the css file associated to the component, I add a css rule to ensure the inner map's canvas is rendered on top of the deck.gl layers and the underlying (outer) ReactMapGL's canvas.

```
.inner-map .mapboxgl-canvas {
    z-index: 1;
}
```

This setup basically creates a mapbox instance with no layers except the ones needed for the draw component at z-index 1. This breaks pointer-events for deck.gl, but to work around this, it makes sense to have the entire component switch states between "drawing" and "regular". In "regular" mode, `pointer-events: none` can be added to the same css selector as above to ensure pointer-events reach deck.

I'm glad it works, but I'm not really satisfied with how this works. I can't imagine this doesn't cause issues somewhere in the internals of these libraries... If anyone is interested, I could work towards uploading a working code example...

**Comment by jianhuang01** [comment]
@Warkst These rendering canvases and libraries are independent, only the events input is shared, that's why there is no internal conflict, ideally deck.gl should support a drawing layer. For now we have no better solution.

**Comment by stef-iula** [comment]
Hi @jianhuang01, is there any news on supporting drawing on a deck?
