### ISSUE TITLE
How to manage Tiles with Deck ?

### ISSUE THREAD

**Issue by twisig** [uber/deck.gl#1453]
Hi,
I would like to use the WMTS with Lidar files in Deck. Do you know if it’s possible or not ?

The goal is that when the user pans on the maps , the interface is updated depending the level, the column and the row.

Thank you

**Comment by jianhuang01** [comment]
@twisig Deck.gl doesn't support tiles for now.

**Comment by twisig** [comment]
Okay but can you add this enhancement to the new release ?

**Comment by jianhuang01** [comment]
@twisig we are planning to add a similar feature, but not sure when we can finish it.

**Comment by carlostxm** [comment]
Hi,
I'm trying to fetch data splitted by tiles or something related to the viewport. While is not supported by Deck, could you give any advice about how to manage this case?

In a Leaflet map I was using to load raster tiles L.TileLayer('http://mydataservice.com/endpoint/{z}/{x}/{y}.png'). But for MapBox/DeckGL I don't know how to do it. 

Any help is appreciated.

Thanks,
Carlos.
