### ISSUE TITLE
website documentation side bar improvement

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1470]
#### Background 
As feedback from @Pessimistress , we could improve our documentation side by doing
- React reference and api reference should be merged into api reference, and mark related pages as  (react) or  (experimental)
- Test utils reference (experimental) should be renamed test utils

The point of API reference is that you can find everything in one place, and the sidebar is very narrow and there's no point if a title is clipped.
![image](https://user-images.githubusercontent.com/15093546/36621584-933a515e-18ad-11e8-946f-230963dd58b3.png)

#### To Do List
  - [x] Add label and assign to milestone 
  - [ ] Doc update
  - [ ] Testing

**Comment by ibgreen** [comment]
Looks like we have different preferences in the team on this topic. I added this as discussion point to our next meeting.
