### ISSUE TITLE
Picking looks broken using chrome + nvidia

### ISSUE THREAD

**Issue by kouak** [uber/deck.gl#1473]
#### Actual Result
Picking does not work.

#### Expected Result
Picking does work.

#### Reproduce Steps
* Linux x86_64
* NVIDIA driver 390.25
* Chrome 64.0.3282.186
* Navigate to https://uber.github.io/deck.gl/#/documentation/layer-catalog/arc-layer
* Picking events are not propagated to the react app.

#### Comments
This works as expected using firefox 58 on the same system.

Output of `chrome://gpu` : https://jsfiddle.net/cd2ptggL/

Unfortunately I don't know much about WebGL, about how browsers interact with the graphic card to provide further guidance about how this problem could be solved :(.

**Comment by jianhuang01** [comment]
What do you mean "Picking does not work"? Is hover or auto-highlight not working in that example? I tested the example on OSX with chrome64, both hover and highlight work as expected, based on the fact that firefox 58 works for you, and chrome64 works for me on OSX, I think linux version of chrome has bugs which we can't do anything.

**Comment by kouak** [comment]
(warning large images)

* Chrome
![demo-deck gl-chrome](https://user-images.githubusercontent.com/48335/36724528-bfdec484-1bb3-11e8-88ae-b92cde73fcad.gif)
* FF
![demo-deck gl-ff](https://user-images.githubusercontent.com/48335/36724529-bff742f2-1bb3-11e8-9014-f7186b8c5b34.gif)
