### ISSUE TITLE
End to end rendering performance profiling

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1495]
#### Background 
Our performance profiling only focuses on a few functions or modules, need have a solution to profile and benchmark on the system level with end to end rendering.
#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Unit test

**Comment by tgorkin** [comment]
Closing this based on work done in deck.gl and luma.gl 8.0 milestone for performance profiling with probe.gl, initial benchmarking using scatterplot stress test, and optimization.  See:
#3801 
https://github.com/uber/luma.gl/issues/1275
https://github.com/uber/luma.gl/pull/1271
