### ISSUE TITLE
Use Buffer instance as external attribute buffer

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1519]
#### Background
Since v4, applications are allowed calculate attributes outside of a layer and pass in the attribute value as a layer prop. `AttributeManager` skips the default updating procedure if an external buffer is found for an attribute.

Currently, `AttributeManager` requires the external buffer to be a typed array. The typed array is later used to construct a luma.gl `Buffer` object when calling `model.setAttribute`. However, if the app is using transform feedback to calculate an attribute, the attribute value is not accessible to the CPU as a typed array. In fact, it is the most efficient to just use the target Buffer of the transform feedback for the attribute, and avoiding the GPU-CPU-GPU roundtrip entirely .

#### Proposal
- Do not throw error in `AttributeManager._setExternalBuffers` if external buffer is a `Buffer` object
- `AttributeManager.getAttributes` and `AttributeManager.getChangedAttributes` return `Buffer` objects instead of attribute descriptor, if applicable.

#### To Do List
  - [ ] Assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update
  - [ ] Test

**Comment by ibgreen** [comment]
Hear hear! This improvement is long overdue, and fits nicely with our overall GPGPU focus.

More generally, I have been thinking that the attribute manager should go all the way and generate `Buffer`s from its arrays, and not leave that final step to luma.gl. When we add support for partial buffer updates this will presumably be necessary anyway. 

Perhaps these two changes together could make the code more aligned?
