### ISSUE TITLE
Error: GeoJsonLayer: GeometryCollection not supported

### ISSUE THREAD

**Issue by akiori** [uber/deck.gl#1532]
#### Actual Result
Chrome console:
```
deck.gl: error while initializing GeoJsonLayer({id: 'geojson'})
 Error: GeoJsonLayer: GeometryCollection not supported.
```

#### Expected Result
several polygons on the map

#### Reproduce Steps

the original file of my geojson is something like (GeometryCollection inside a FeatureCollection)
![origin](https://user-images.githubusercontent.com/8252543/37306964-a88dd0c0-25f6-11e8-867f-ab363a826166.png)

I have tried to simplified it, here are the snippets:
![geocollection](https://user-images.githubusercontent.com/8252543/37306649-938bc246-25f5-11e8-9bd0-1d7e2bec6bb7.png)
and
![geocollectioninfeature](https://user-images.githubusercontent.com/8252543/37306662-9d3e9372-25f5-11e8-9660-fe5350c87c0d.png)

both of them don't work. I saw in your source code **geojson.js**, in `function getGeojsonFeatures(geojson){}` deals with GeometryCollection, while in `function separateGeojsonFeatures(features) {}` it comments as "// Not yet supported" abouve `case 'GeometryCollection'`.

Previously, I use leaflet API to render polygons in the geojson (also includes geometry collection), it works well.

Now my solution is use [geojson-flatten](https://github.com/node-geojson/geojson-flatten) first, then use deckgl to render.

Besides I saw in this issue(https://github.com/uber/deck.gl/issues/936), mentioned some stuff like nested GeometryCollection in FeatureCollection.

**Comment by akiori** [comment]
since my geojson file is converted from a KML file, the conversion results may dependes on the converting tool?

I used a python lib named kml2geojson, and got the result which includes a "GeometryCollection". My peer uses GDAL ogr2ogr, and get a result with "MultiPolygon". His result works well in deckgl.

The following image is a comparison between them, actually not much difference
![difference between GeometryCollection and Multipolygon ](https://user-images.githubusercontent.com/8252543/37313187-523e08ce-260b-11e8-8cd0-96e5614ac211.png)

**Comment by Pessimistress** [comment]
GeometryCollection support should be fixed by https://github.com/uber/deck.gl/pull/1442
@jianhuang01 do we want to publish a patch release for 5.1?

**Comment by ibgreen** [comment]
I believe `GeometryCollections` can be nested, but in a quick read of the PR it didn't seem to handle that case?

**Comment by Pessimistress** [comment]
@ibgreen From the GeoJSON spec:
> To maximize interoperability, implementations SHOULD avoid nested GeometryCollections.

We could leave nested GeometryCollections an open issue, but just adding single-level support would be covering majority of the use cases.

**Comment by ibgreen** [comment]
OK sounds good. If that is a loosely defined part of the spec it might have been nice to issue a warning if we see nested collections (stating that we ignore them per recommendation), but fine as is.

**Comment by jianhuang01** [comment]
@akiori Looks like the output depends on the tool, cause both output are valid and have the same rendering result from the spec's perspective. I will publish a patch release this week to resolve the non-nested GeometryCollection issue.

**Comment by akiori** [comment]
@jianhuang01 thanks a lot!
