### ISSUE TITLE
WebSockets and deck.gl

### ISSUE THREAD

**Issue by flolas** [uber/deck.gl#1542]
#### Background 
I'm testing deck.gl with static data for layers and its working really good. Now I want to try using real time data(for example, twitter). It would be great to have real time examples on the deck.gl docs, or give some orientation.

Thanks!

**Comment by freddieb** [comment]
Hi @flolas, I've recently done a deck.gl app with real-time websocket data.

The data received from the socket can be added to your DeckGL layer's `data` prop. DeckGL will do a shallow compare of the new props (which is a common cause for it not updating with the new data), so it can be useful to use the `dataComparator` prop to check if a specific part of your new data prop has changed, and to then return whether the DeckGL component needs to be updated.

**Comment by flolas** [comment]
Hi @freddieb 
Great!! 
Do you have a simple code example??

Thank you!!
