### ISSUE TITLE
Unable to run the JS only examples

### ISSUE THREAD

**Issue by Whiskerc** [uber/deck.gl#1543]
#### Actual Result
When attempting to run the /examples/experimenta/js/with-mapbox-map example, npm outputs the following errors: 
```
ERROR in ./~/deck.gl/dist-es6/react/map-controller.js
Module not found: Error: Can't resolve 'react' in '/Users/chris/Downloads/deck.gl-master/examples/experimental/js/with-mapbox-map/node_modules/deck.gl/dist-es6/react'
 @ ./~/deck.gl/dist-es6/react/map-controller.js 9:0-53
 @ ./~/deck.gl/dist-es6/react/index.js
 @ ./~/deck.gl/dist-es6/index.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app.js

ERROR in ./~/deck.gl/dist-es6/react/deckgl.js
Module not found: Error: Can't resolve 'react' in '/Users/chris/Downloads/deck.gl-master/examples/experimental/js/with-mapbox-map/node_modules/deck.gl/dist-es6/react'
 @ ./~/deck.gl/dist-es6/react/deckgl.js 31:0-59
 @ ./~/deck.gl/dist-es6/react/index.js
 @ ./~/deck.gl/dist-es6/index.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app.js

ERROR in ./~/deck.gl/dist-es6/react/viewport-controller.js
Module not found: Error: Can't resolve 'react' in '/Users/chris/Downloads/deck.gl-master/examples/experimental/js/with-mapbox-map/node_modules/deck.gl/dist-es6/react'
 @ ./~/deck.gl/dist-es6/react/viewport-controller.js 9:0-49
 @ ./~/deck.gl/dist-es6/react/index.js
 @ ./~/deck.gl/dist-es6/index.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app.js

ERROR in ./~/deck.gl/dist-es6/react/experimental/orbit-controller.js
Module not found: Error: Can't resolve 'react' in '/Users/chris/Downloads/deck.gl-master/examples/experimental/js/with-mapbox-map/node_modules/deck.gl/dist-es6/react/experimental'
 @ ./~/deck.gl/dist-es6/react/experimental/orbit-controller.js 9:0-53
 @ ./~/deck.gl/dist-es6/react/index.js
 @ ./~/deck.gl/dist-es6/index.js
 @ ./app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./app.js
```
#### Expected Result
My understanding was that the JS examples would not need react to run (I am looking to port the js into an angular project eventually)
#### Reproduce Steps
Download from github
npm install
npm start
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by jianhuang01** [comment]
Examples on master can't only work with native master code, its own dependencies are not in good condition yet. Use "npm run start-local" instead of "npm run start"

**Comment by ibgreen** [comment]
@Whiskerc See #1502

**Comment by Whiskerc** [comment]
Cheers!! That worked

I also had only run npm install in the sample folder and not the root of the examples which gave me some problems :)

If I get a good Angular example working I'll let you know as it seems something a number of people are looking for

Chris

**Comment by ibgreen** [comment]
> If I get a good Angular example working I'll let you know as it seems something a number of people are looking for

That would be awesome. Angular port has been attempted before, when the JS API support was much weaker see #576. It should be easier now.
