### ISSUE TITLE
TextLayer text has artifacts

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1550]
Render '**AAAAAAA**' text using TextLayer, default parameters, _COORDINATE_SYSTEM.LNGLAT_OFFSETS_.

#### Actual Result
Text has artifacts.

#### Expected Result
Text is clear.

#### Reproduce Steps
Use layer browser.

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  
- [ ] Test

**Comment by georgios-uber** [comment]
<img width="847" alt="screen shot 2018-03-19 at 4 04 48 pm" src="https://user-images.githubusercontent.com/25012840/37627083-035acc76-2b90-11e8-9db6-7f4dac1a84e3.png">

**Comment by ibgreen** [comment]
Too little space between the icons in the icon atlas?

**Comment by 1chandu** [comment]
is `useDevicePixels` prop set to true ?

**Comment by georgios-uber** [comment]
@1chandu not setting it, shouldn't it be true by default?

**Comment by 1chandu** [comment]
@georgios-uber , yes default should be true.

**Comment by georgios-uber** [comment]
@1chandu Can you try to reproduce on MacBook Pro Retina display?

**Comment by georgios-uber** [comment]
I think the problem is in experimental-layers/src/text-layer/font-atlas.js
The atlas generates is too "tight".

I managed to get a screenshot:
<img width="1110" alt="screen shot 2018-03-19 at 5 00 42 pm" src="https://user-images.githubusercontent.com/25012840/37628579-3fe9738e-2b97-11e8-80a0-1e17a7ba9740.png">

**Comment by georgios-uber** [comment]
I had:
```
depthTest: false
blend: false
```

When I took the screenshot above, but the problem still happens to much less degree when you don't set depthTest & blend.

**Comment by 1chandu** [comment]
I am not able to reproduce this issue, I am using `LNGLAT_OFFSETS` , tried various sizes, zoom levels and different characters for text. Looks good on my screen.

<img width="127" alt="textlayer" src="https://user-images.githubusercontent.com/9502731/37629708-8f7c4be6-2b9d-11e8-92e3-5956afe251df.png">

The vertical lines between the characters could be related to padding and/or text-coords setup, but the blurring looks like a different issue, that I couldn't reproduce.  @georgios-uber can you share the props you are setting for `TextLayer`.

**Comment by georgios-uber** [comment]
@1chandu The issue does reproduce on your screen. Circled the issue on screenshot.

<img width="803" alt="screen shot 2018-03-19 at 6 00 12 pm" src="https://user-images.githubusercontent.com/25012840/37630139-051099a0-2ba0-11e8-8510-4a3243e64817.png">

**Comment by georgios-uber** [comment]
@1chandu changed the title to make it more clear "TextLayer text has artifacts"

**Comment by daumann** [comment]
@georgios-uber @1chandu 
This issue does not seem to be fixed completely.

I am using a` "deck.gl": "^6.3.2"` Textlayer with the Google **Cinzel** font.

https://i.imgur.com/nwATZ9h.png (live version at https://chronas.org)

Unfortunately the line of the Q affects the R character.

**Comment by georgios-uber** [comment]
@daumann Windows/Linux/Max? What browser?

**Comment by daumann** [comment]
@georgios-uber I would be surprised if the system spec matter here. Anyway my specs are Linux/ Windows (tested on both) and Chrome.
If you like to test it yourself, go to https://chronas.org and zoom in until you see city labels.

**Comment by georgios-uber** [comment]
@1chandu any ideas?

**Comment by xintongxia** [comment]
@daumann 

Thanks for reporting this bug.

After investigating, I figured out this is because when `TextLayer` generates the font atlas with all the required `characterSet`, it adds some buffer surrounding each character, but the current buffer size is not sufficient for `Cinzel` font. For the short term to unblock you, I put up a [PR](https://github.com/uber/deck.gl/pull/2609) to increase the buffer.

**Comment by Pessimistress** [comment]
@daumann 6.4.0 is published with a new `TextLayer` prop `fontSettings`. You can increase `fontSettings.buffer` to avoid overlapping of characters (in the Cinzel font the uppercase `Q` extends far beyond its character box)
