### ISSUE TITLE
TextLayer updateTriggers.all do not work as expected

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1551]
TextLayer updateTriggers.all do not work as expected.

#### Actual Result
getText is not called when updateTriggers.all changes.

#### Expected Result
getText is called when updateTriggers.all changes.

**Comment by 1chandu** [comment]
@georgios-uber , I don't have reproducible case, does #1555 fix this issue.
Are you setting `updateTriggers` prop? , if so what is it set to?

**Comment by georgios-uber** [comment]
#1555 Seems good.

**Comment by georgios-uber** [comment]
Thanks for the fix.
