### ISSUE TITLE
All 64-bit layers now wobbling...

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#156]
All 64-bit layers are wobbling as of beta31. I need to do some regression tests tomorrow.
It's highly likely due to recent viewport changes.
Assigning to myself.

**Comment by contra** [comment]
Still getting some pretty major wobbling on FP64 layers even on the latest dev branch

**Comment by shaojingli** [comment]
@contra Saddly, the 64-bit layers are not supported on 2013 MBP with NVIDIA GPUs from the beginning...because the machine is not available to buy and we could secure one to test... there are some unique peculiarity in mac version of nvidia driver. 

I tested MBP with AMD and Intel GPUs, Linux and Windows with NVIDIA GPUs, the wobbling is not there as of today.

**Comment by contra** [comment]
@shaojingli Any way I can help out with that? You can use my machine remotely to debug if you want.
