### ISSUE TITLE
Plot multiples points on a map but in order of time

### ISSUE THREAD

**Issue by mary83** [uber/deck.gl#1568]
Hello, I am not sure if this is the correct place where I should ask info for my issue.
I am trying to use the example Scatterplot because my goal is to plot multiple points on a map. 
Using this example I am able to load all the points on the map but I would like to plot them in order of time (for example, at time 1 I have to display just 10 points, at time 2 display another 20 points, etc.).
Is there some way to do this?
Thanks in advance for the info.

**Comment by jianhuang01** [comment]
@mary83  Welcome to deck.gl, in order to have effects you mentioned, you need control the timeline on your own, for example, at time 1 update the data prop with 10 points, at time 2 update data prop with 20 points, etc.
