### ISSUE TITLE
IconLayer not rendering 

### ISSUE THREAD

**Issue by alexbavinton** [uber/deck.gl#1571]
I am trying to render png icons over a map, but the IconLayer isn't rendering. 

I have tried rendering other types of layers, and they render fine. 

My code is as follows: 

`const ICON_MAPPING = {
        marker: {x: 0, y: 0, width: 32, height: 32, mask: false}
    };
 

    const layer = new IconLayer({
        id: 'icon-layer', 
        data: this.props.data, 
        iconAtlas: planeImg, 
        iconMapping: ICON_MAPPING, 
        getPosition: d => d.position, 
        getAngle: d => d.angle, 
        getIcon: d => d.icon, 
        getColor: d => d.color || [0, 0, 0, 255], 
        getSize: d => d.size || 24, 
        sizeScale: 1,
        opacity: 1,
        pickable: true,
        radiusMinPixels: 2,
        radiusMaxPixels: 30,
        visible: true,
    })`

Any help people could give would be greatly appreciated!

**Comment by 1chandu** [comment]
For icon layer you don't need `radiusMinPixels` and `radiusMaxPixels`, but other props look ok to me, unless the data you are providing has some issue. Can you enable logging as below and see if any errors/warning are logged ?

`"luma.log.priority=2" and "deck.log.priority=2" in browser console`

**Comment by ibgreen** [comment]
How big is the iconAtlas texture `planeImg`? You are basically showing a 32x32 pixel section, maybe that part is transparent? 

How are you specifying/loading the texture? 

Any warnings in the console?

**Comment by alexbavinton** [comment]
Thanks for your help. You were right, I was showing a transparent section of the image
