### ISSUE TITLE
Callbacks for onHover and onClick events are not being called in Google Chrome

### ISSUE THREAD

**Issue by mhsekhavat** [uber/deck.gl#1574]
#### Actual Result
It seems there is a bug with `hover` and `click` features *on chrome*. When I open [Icon Layer Example](https://uber.github.io/deck.gl/#/examples/core-layers/icon-layer)
no popups are shown in Google Chrome. 
I have also set logging priorities to 2 and checked browser console, no exceptions or logs are printed about the issue. Only lots of `luma.gl: >>> RENDERING MODEL icon`.
I also created a small DeckGL component with a `ScatterplotLayer` like below:
```jsx
            <ScatterplotLayer
              id="layer1"
              data={this.records}
              getPosition={this.getPosition}
              getRadius={this.getRadius}
              getColor={this.getColor}
              fp64={true}
              pickable={true}
              onHover={(e)=>console.log(e)}
              onClick={(e)=>console.log(e)}
            />
```
Nothing is logged in the console. I also tried setting `onLayerClick` prop on `DeckGL` component. This time the callback was being called but with `null` argument.
#### Expected Result
But when I open up the same url in Firefox, popups are shown.
#### Reproduce Steps
Go to https://uber.github.io/deck.gl/#/examples/core-layers/icon-layer 
Use Google Chrome Version: 64.0.3282.140 (Official Build) (64-bit) 
(My OS is ArchLinux)

**Comment by jianhuang01** [comment]
@mhalverson Thanks for reporting the issue, usually this is caused by bugs in chrome on linux, can you try the latest chrome 65 to see if it is OK?

**Comment by mhsekhavat** [comment]
@jianhuang01 I just tried it with Chrome 65.0.3325.181 and the problem still exists.

**Comment by mhsekhavat** [comment]
Now I tried it with Version 66.0.3359.117 and the bug is fixed in this version.

**Comment by ibgreen** [comment]
@toddmedema
