### ISSUE TITLE
TripsLayer flickers severely when viewport bearing changes

### ISSUE THREAD

**Issue by alanzchen** [uber/deck.gl#1586]
Hi developers,

Basically, I am trying to replicate the `TripsLayer` demo on the deck.gl homepage. So I tried to incorporate the `_rotateCamera` feature into the `TripsLayer` example. However, the `TripsLayer` seems to flicker a lot.
#### Actual Result
![flicker](https://user-images.githubusercontent.com/2144783/37967251-653e8144-31fd-11e8-8280-5bdadd9fb579.gif)
The `TripsLayer` flicker severely.
#### Expected Result
The demo running on deck.gl homepage.
#### Reproduce Steps
Try to replicate TripsLayer and `deck.gl/examples/experimental/viewport-transitions`.

**Comment by 1chandu** [comment]
@alanzchen this could be due to 32 bit precession not enough at that zoom level. Trip layer is not part of the core layers, can you use path layer with `fp64` on ?

**Comment by Pessimistress** [comment]
Unfortunately the good old trips layer does not have a `fp64` mode. It shouldn't be hard to add one with the unified projection feature in 5.2 though.

@alanzchen just to verify that it is indeed a precision issue - you can try switching to `LNGLAT_OFFSETS` mode, i.e.
From
```
new TripsLayer({
  data: [{position: [-74.123, 41.012], time: 1234567}, ...],
  ...
})
```

To
```
new TripsLayer({
  coordinateSystem: COORDINATE_SYSTEM.LNGLAT_OFFSETS,
  coordinateOrigin: [-74, 41],
  data: [{position: [-0.123, 0.012], time: 1234567}, ...],
  ...
})
```

**Comment by alanzchen** [comment]
@Pessimistress Thanks, your solution works perfectly!
