### ISSUE TITLE
Layer drawing positions differs between browsers

### ISSUE THREAD

**Issue by sga-suzuki-kenji** [uber/deck.gl#1599]
Hi, thank you for the great work.

I am using GeoJsonLayer for drawing points, lines, and polygons. 
The drawing positions are different between MS Edge and Chrome.

I have this problem in my application,
But also occurs on layer-browser example.

##### MS Edge
![image](https://user-images.githubusercontent.com/15903124/38078239-9b6bbd70-3376-11e8-945b-9e3c368e2808.png)

##### Chrome
![image](https://user-images.githubusercontent.com/15903124/38078177-63e290ae-3376-11e8-9a66-e2413fd1c5be.png)

#### Expected Result
I want to draw in the same position.

#### Reproduce Steps
- layer-brower example v5.1.4
- Microsoft Edge 40.15063.674.0
- Google Chrome 65.0.3325.181

**Comment by jianhuang01** [comment]
@sga-suzuki-kenji Thanks for reporting the issue, cross platform support is not in our scope yet because of limited resources, for now I will keep the issue in backlog.

**Comment by ibgreen** [comment]
This is most likely due to precision issues. Either flip on `fp64: true` or try the new `COORDINATE_MODE.LNGLAT_EXPERIMENTAL`.
