### ISSUE TITLE
add radius to scatterplot attributes breaks when render with other type of layer

### ISSUE THREAD

**Issue by heshan0131** [uber/deck.gl#16]
Hi @wwwtyro

I try to edit the scatterplot layer to have radius as an attribute instead of uniform.

My edit works when ONLY scatterplot layers is rendered. But breaks when any other type of layer is rendered together.

Here is to my branch. I edit the example code to include radius in scatterplot. https://github.com/heshan0131/deck.gl/tree/point-size

**Comment by wwwtyro** [comment]
Thanks, @heshan0131, I'll take a look at this one, too. :+1:

**Comment by ibgreen** [comment]
@heshan0131 @wwwtyro Could this be related to the issue with having multiple programs with different numbers of uniforms? On the performance branch we are now removing the attributes after each render so please retest.
