### ISSUE TITLE
Graph example and test-browser are broken

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1601]
#### Bad commit
#1594 

Tried to update the version of webpack, webpack-dev-server etc. in example/graph, but other errors came out.
#### Actual Result
"TypeError: Cannot read property 'thisCompilation' of undefined" while running graph example, test-browser can't be launched either.

#### Expected Result
No errors
#### Reproduce Steps
"npm run start-local" for example/graph
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by 1chandu** [comment]
`test-browser` failure is seen only when you remove `node_modules` folder and rebuild. This effectively blocks all commits commits to master.
