### ISSUE TITLE
Enable stroke width setting for trips-layer

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1624]
#### Background 
We use gl lines to render trips layer which can't have more than 1 pixel width, need generate triangle strips to render them properly.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by elbertwang3** [comment]
Any idea on when this might be released? Really hoping to use this feature

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)

**Comment by ibgreen** [comment]
This was implemented in deck.gl 7.0
