### ISSUE TITLE
Choropleth64 layer broken

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#168]
Choropleth64 layers are broken as of c6b27ce55e365906327fb013c1e2a0747e2fa790

However, removing the type property when adding colors attribute resolves the issue.

     --- a/src/layers/fp64/choropleth-layer/choropleth-layer.js
     +++ b/src/layers/fp64/choropleth-layer/choropleth-layer.js
     @@ -61,7 +61,6 @@ export default class ChoroplethLayer64 extends Layer {
            heightsFP64: {size: 2, update: this.calculateHeightsFP64},
            colors: {
              size: 4,
     -        type: GL.UNSIGNED_BYTE,
              update: this.calculateColors
            },
            // Instanced attributes

I'm a bit confused...
@ibgreen do you know how this is happening?

**Comment by Apercu** [comment]
Introduced in https://github.com/uber/deck.gl/pull/161.

**Comment by shaojingli** [comment]
Resolved by #172. Closing
