### ISSUE TITLE
Is it possible to select multiple objects within a dragging box?

### ISSUE THREAD

**Issue by tonny2v** [uber/deck.gl#1683]
I coundn't find any example about this, I wonder if it is possible in provided API? Or shall I dig into luma.gl?

**Comment by jianhuang01** [comment]
not supported yet, need new design.

**Comment by Pessimistress** [comment]
@tonny2v You may want to check the [pickObjects](https://uber.github.io/deck.gl/#/documentation/api-reference/react/deck?section=methods) method of DeckGL. It will return all objects in a rectangular bounding box.

**Comment by saravanabalagi** [comment]
pickObjects got moved [here](https://deck.gl/docs/api-reference/core/deck#pickobjects) if anyone's interested

**Comment by yxia-zoox** [comment]
Hi @saravanabalagi , would you please give me some examples of this `pickObjects` function? I managed to run the `layer-browser` example, but couldn't figure out how points or mesh objects are selected, and whether I could use a bounding box for selection. 

Ideally, I'd like to see a similar workflow like this mapbox selection [demo](https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/), i.e. holding the shift and dragging the cursor to select a region.
