### ISSUE TITLE
Infinite resizing loop if Deck's `width` and `height` props are not specified

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1687]
#### Actual Result
If Deck's `width` and `height` props are not specified, `_checkForCanvasSizeChange()` doubles the canvas size on every animation frame.

#### Expected Result
Should either apply default sizing or throw error.

#### Reproduce Steps
- Go to layer-browser's `app.js`, remove `width="100%" height="100%"` from `<DeckGL>`
- Run the app

This is introduced by auto resizing: https://github.com/uber/deck.gl/pull/1389
If no css style is specified for the canvas, its rendered dimensions are the same as `canvas.width` and `canvas.height`, which are the the last rendered dimensions multiplied with `devicePixelRatio`.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by kaligrafy** [comment]
I still get this bug on current version (9.0.29).

I set the div containing the map to 100% of parent both in width and height. Most of the time it works well, but if the console is opened or when resizing, I get an infinite loop resizing (a change of 1 or 2 pixels, forever) and the map just goes blank.

https://github.com/user-attachments/assets/430504e2-1ed4-40dd-bcda-ab10dd7ff14e

Here is the css:
.admin__interview-map {
    background: rgba(0,0,0,1.0);
    position: relative;
    padding: 0;
    margin: 0;
    width: 100%;
    height: 100%;
}

parent is a flex element

**Comment by ibgreen** [comment]
A possible cause that I have seen is that setting the drawing buffer size on the canvas to account for device pixel ratio can sometimes trigger this. I have never been able to fully understand why this happens and how to avoid it and we haven't seen the issue for quite a while now.

We have changed this logic in luma.gl v9.1 so it may solve the issue, and we are moving into final beta so deck.gl v9.1 should be out in a few weeks.

For now you could try to set `useDevicePixels: false` on deck.gl and see if that fixes it, it would at least confirm my hypothesis.

**Comment by kaligrafy** [comment]
same bug with useDevicePixels: false

Thanks for the help though!
