### ISSUE TITLE
5.2.0-beta.2 broken on missing dependency

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1696]
#### Actual Result
When importing `deck.gl@5.2.0-beta.2` in an independent application, webpack throws error:
```
ERROR in ./~/@deck.gl/core/dist/esm/core-layers/text-layer/font-atlas.js
Module not found: Error: Can't resolve 'global' in '/Users/missx/Desktop/3d-heatmap/node_modules/@deck.gl/core/dist/esm/core-layers/text-layer'
```

This is not visible in /examples because `global` is a dev dependency at root.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by awdng** [comment]
i just tried to run the trips example from the 5.2 release and master branch but i am still getting this error and i won't compile.
Then tried to change the dependency in the trips example to the current master, but that gives me a different error.
How to run this example ?

**Comment by Pessimistress** [comment]
@awdng 5.2 is still under beta, please run the examples on the 5.1-release branch.
