### ISSUE TITLE
Deck.gl keeps sending rendering commands after all layers are off

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#170]
Deck.gl keeps rendering stuff after all layers are turned off. 

When deck.gl example app is started with no layers turned on, everything is as expected with GPU utilization being 0. However, if layers are turned on and back off, deck.gl continuous to send WebGL commands and the GPU utilization are constantly above 50%.

**Comment by ibgreen** [comment]
@shaojingli  Can this be closes as a dup of #300 ?

**Comment by shaojingli** [comment]
@ibgreen yes. let's dup it to #300
