### ISSUE TITLE
Picking of multiple occluded objects

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1733]
#### Background 
Some applications need all objects below mouse, not just top object.

See
* [RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.3/picking-overlapping-objects-rfc.md)
* luma.gl Issue https://github.com/uber/luma.gl/issues/432
* luma.gl PR https://github.com/uber/luma.gl/pull/509
* deck.gl PR #1730

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update
  - [ ] Update layer docs about ```clearPickingColor()```
  - [ ] Unit Tests

**Comment by georgios-uber** [comment]
#1730

**Comment by ibgreen** [comment]
* My suggestion is to keep `clearPickingColor` as experimental (i.e. undocumented) for this release.
* The default implementation should work with most layers
* And I think we are due of a couple of overhauls of the `AttributeManager` that could change the way we do this.
* The test cases are tracked in a separate task #1756
