### ISSUE TITLE
right mouse button can't change viewState

### ISSUE THREAD

**Issue by zhuweileo** [uber/deck.gl#1743]
I use deckgl by this way([Using deck.gl without React](http://uber.github.io/deck.gl/#/documentation/getting-started/using-standalone)).
My problem is  that I can't change deckgl layer's bearing, pitch, by dragging right mouse button.
And when I click right mouse ,the context menu appears.
Beg your Help!

**Comment by Pessimistress** [comment]
At the moment you have to manually disable the context menu:
```
document.getElementById('container').addEventListener('contextmenu', evt => evt.preventDefault());
```

@ibgreen Ideally we should offer a prop for disabling the context menu?

**Comment by Pessimistress** [comment]
Hmm I tried this and right mouse button drags instead of pan. It seems to be a bug.
https://github.com/uber/deck.gl/blob/master/modules/core/src/core/controllers/viewport-controls.js#L236
is overridden by
https://github.com/uber/deck.gl/blob/master/modules/core/src/core/controllers/map-controls.js#L35

**Comment by zhuweileo** [comment]
Thanks a lot!
I tried deck.gl/core  version 5.2.0(the latest) from npm  to handle my problem, but failed.
I can pan with the right mouse , but still can't rotate 
Which version should  I pick to handle my problem.
@Pessimistress

**Comment by jianhuang01** [comment]
Fxied in 5.2.1

**Comment by zhuweileo** [comment]
Thanks a lot! @jianhuang01

**Comment by RELNO** [comment]
As @hijiangtao mentioned, right click map rotate does not natively work. This method worked for me (` "deck.gl": "^7.3.3"`)
```
  componentDidMount() {
    document
      .getElementById("deckgl-wrapper")
      .addEventListener("contextmenu", evt => evt.preventDefault());
  }

```

**Comment by hijiangtao** [comment]
@jianhuang01 , as @RELNO mentioned, there's more than one developer who faced the problem (with version 7.3.3+ and 6.3.1), I think we may double check whether `right-click-rotate` problem is solved indeed?
