### ISSUE TITLE
Add link to source code of examples in API documentation

### ISSUE THREAD

**Issue by pbeshai** [uber/deck.gl#1749]
#### Background 
Would be nice if when visiting the API docs there was an easy way to see the source code of the example on the page. For example, look at the [ScatterplotLayer](http://uber.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer) documentation. The vis at the top of the screen is pretty nice and interactive, but it's not obvious how to see the source code behind it as an example. 

I was curious to see how the hover behavior and autohighlight worked in this case and was unable to find the source to the example to see.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ianshan0915** [comment]
Hey @jianhuang01, I'm trying to work on this. but not sure about the link to source code. is [this link](https://github.com/uber/deck.gl/blob/master/website/src/components/demos/layer-demos.js) the right one? thanks

**Comment by jianhuang01** [comment]
@ianshan0915 Yes, that's the source code for layer demos.
