### ISSUE TITLE
No default lighting without specifying `lightSettings` prop

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#1751]
#### Actual Result
Default lighting is not applied if the user does not specify the `lightSettings` prop on primitive layers.

#### Expected Result
Default lighting should be applied if the user does not specify the `lightSettings` prop.

#### Reproduce Steps
- Open this [codepen](https://codepen.io/vis-gl/pen/qYrmZp)
- Comment out L23: `lightSettings: {}`, and all points turn black

#### Cause
- `Object.assign({}, layer.props)` only grabs the `props` object's own properties in https://github.com/uber/deck.gl/blob/master/modules/core/src/core/lib/draw-layers.js#L240
- This affects the PointCloudLayer, SolidPolygonLayer, GridCellLayer and HexagonCellLayer. Usually only PointCloudLayer is used standalone, so this problem has slipped our attention.

@ibgreen 

#### To Do List 
  - [ ] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by ibgreen** [comment]
My idea has been that we would let "shader modules" organize common prop bundles (like `lightSettings`) as `Effects`. 

One would specify 

```
<DeckGL
  layers={...} 
  effects={new LightingEffect({...})}
  />` 

and layers would pick the settings from there unless (rarely) overridden.
