### ISSUE TITLE
Consume less GPU memory on inactive tabs

### ISSUE THREAD

**Issue by toddmedema** [uber/deck.gl#1775]
Deck.gl applications can easily use 100's of MB of GPU RAM; if users have multiple tabs of deck.gl applications open, it can easily overwhelm a lightweight laptop's available GPU memory, causing system-wide issues. (OS X seems to manage it better, but I've seen it lock up an Ubuntu computer)

Suggest adding some default (but disable-able) intelligence around rendering a dummy grey scene on inactive tabs. As it happens, I have example code for good tab activity detection from another project:

https://github.com/ExpeditionRPG/expedition-app/blob/master/app/Main.tsx#L162-L168
plus
https://github.com/ExpeditionRPG/expedition-app/blob/master/app/Main.tsx#L298-L304

To be nice to users and make it less aggressive, we might consider only marking tabs as inactive if they've been inactive for 5+ minutes. There might also be a way to page the scene to host memory instead of dropping it entirely? (although that would just shift the GPU memory shortage problem to RAM)

**Comment by ibgreen** [comment]
@toddmedema 

Agreed, the time has come to look into this. Quick comments:

- deck.gl rendering is already driven by `requestAnimationFrame` which is not called on hidden tabs.
- The memory consumption is mostly unrelated to the rendering, it is related to data updates. Depending on how those are triggered the may still be happening.
- The best initial approach might simply be to increase reuse of GPU buffers. The code is not very optimized in this regard and this is already on our near-term roadmap.
