### ISSUE TITLE
PolygonLayer using too many vertexes?

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#1784]
#### Actual Result

![image](https://user-images.githubusercontent.com/425716/39773253-73e5638c-52c5-11e8-8f50-6854a61de9c5.png)

On version 5.2.3

#### Expected Result

The boundary would render with no errors. This GeoJSON used to render in previous versions of deck.gl (even very recent 5.x iterations).

#### Reproduce Steps

Render the maritime boundary of the USA as a simple outline.

```js
    const boundaryLayer = new GeoJsonLayer({
      id: 'boundary-outline',
      data: geojson,
      lineWidthScale: 1,
      lineWidthMinPixels: 2,
      lineWidthMaxPixels: 3,
      lineJointRounded: true,
      drawContour: true,
      fp64: true,
      stroked: true,
      filled: false,
      pickable: false
    })

    const layers = [ boundaryLayer ]
    return <DeckGLOverlay
      id="boundary-outline-gl"
      height={this.props.height}
      width={this.props.width}
      {...viewport}
      style={style}
      layers={layers} />
```

Maritime boundaries available here if you need to grab the data: https://unpkg.com/@geo-maps/countries-maritime-1m/map.geo.json

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by GeoIntelSolution** [comment]
I have draw 18400 building,It aslo report vertexes is too much ,I cut it down to 3900 ，It shows up;It seem it has a capacity

**Comment by Pessimistress** [comment]
This is a bug. We check if Uint32 indices are supported [here](https://github.com/uber/deck.gl/blob/master/modules/core/src/core-layers/solid-polygon-layer/solid-polygon-layer.js#L127) but fail to account for WebGL2 contexts:

https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint

I'll put up a fix today.

**Comment by kamillejohnson** [comment]
+1 on this. Currently experiencing the same error as above, including the `could not read property 'forEach' of undefined`. Is this undefined error linked to the Vertex error?
![screen shot 2018-05-10 at 4 06 47 pm](https://user-images.githubusercontent.com/6621056/39891743-6755776c-546c-11e8-9b56-ee32102aaa80.png)

**Comment by Pessimistress** [comment]
@contra @GeoIntelSolution @kamillejohnson fix is published as v5.2.4:
https://codepen.io/Pessimistress/pen/MGVdOm

**Comment by kamillejohnson** [comment]
@Pessimistress thank you so much! it works great!

**Comment by contra** [comment]
closing, will reopen if not fixed - thanks!
