### ISSUE TITLE
Error trying to use externar image (SVG) to create IconLayer 

### ISSUE THREAD

**Issue by tonicastillo** [uber/deck.gl#1788]
Hi.
Sorry, I don't know If this is a bug, a not implemented feature, or it's my fault.

When I use an image from another server:

```javascript
layers.push(new IconLayer(
  iconAtlas: 'http://example.com/example.svg',
  ...
));
```
I get a cross-origin error. Server configuration allows to serve cross-origin data.

Thanks.

**Comment by ibgreen** [comment]
Sorry for not givinb a timely response. We do set the `crossOrigin='anonymous'` flag when we load images.

That said, WebGL has tighter CORS limitations than standard images, see https://webgl2fundamentals.org/webgl/lessons/webgl-cors-permission.html
