### ISSUE TITLE
Fighting pac-men effect in scatterplot example.

### ISSUE THREAD

**Issue by thunderkid** [uber/deck.gl#1793]
On the scatterplot example ([here](http://uber.github.io/deck.gl/#/examples/core-layers/scatterplot-layer)), zooming in far enough shows random occlusions occuring between the blue and red circles:

![image](https://user-images.githubusercontent.com/6183356/39897844-f9d24fec-5468-11e8-8d9e-3598e0c8ce93.png)

As you zoom or change the tilt slightly, these occlusions change randomly. It looks like blue and red pac-men trying to eat each other. If you're zoomed out this appears as a shimmering effect as you change the tilt slightly. I'm seeing the same effect on Chrome 66 and MS Edge.

**Comment by thunderkid** [comment]
To see the effect much more vividly, if you change to `radiusScale: 500`, then any slight tilt change makes the circles look as though they're boiling:
![image](https://user-images.githubusercontent.com/6183356/39934770-bedbcff6-54fb-11e8-9ee0-61dd1d12a30c.png)

**Comment by ibgreen** [comment]
There is an FAQ entry in the upcoming release about z-fighting.
