### ISSUE TITLE
react-webpack example is down

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1823]
#### Actual Result
Didn't render anything
#### Expected Result
Should render the map
![image](https://user-images.githubusercontent.com/15093546/40259497-28ebccca-5aab-11e8-852d-1cb6533ed6bf.png)

#### Reproduce Steps
do "yarn" and "npm run start-local" under folder "examples/get-started/react-webpack"
#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
This seems to be related to the example using JSX layers. React freezes the props object so the following assignment fails:
```
      log.deprecated('LineLayer: `strokeWidth`', '`getStrokeWidth`');
      props.getStrokeWidth = props.strokeWidth;
```
Maybe
```
Object.assign({}, props, {getStrokeWidth: props.strokeWidth}); 
```
would work for now?

**Comment by jianhuang01** [comment]
<img width="492" alt="line_layer" src="https://user-images.githubusercontent.com/15093546/40259248-3ee66fa4-5aaa-11e8-888c-b9afffb5e85a.png">
Not work, the line width is not correct.
