### ISSUE TITLE
pure-js

### ISSUE THREAD

**Issue by localdevjs** [uber/deck.gl#1849]
I've seen links to a "pure-js" implementation but those links have expired. The correct link seems to be this:

https://github.com/uber/deck.gl/tree/master/examples/get-started/pure-js

But I need to get deck.gl going with raw html and javascript. No "npm" stuff, no react, no angular, no frameworks... just plain old html + javascript directly. 

The problem with all the current deck.gl examples is that they use react and npm and other stuff that conflict with other frameworks and tools that might be already in use by a project. It would be better to have a bunch of examples that work with vanilla js and html and css so that we can later tweak it to fit within other tools and frameworks.

As it is right now... I have no idea what I'm doing here. I have no idea what js scripts to import into my project, how to wire this into my already existing mapbox maps etc. 

Are there such examples running around somewhere? The "pure-js" seems like a decent start but it doesn't run without "npm". And I can't change my entire project setup/structure to use npm just because of deck.gl

Any ideas? Specifically this stuff here looks like it will be a problem:

import {Deck, MapController} from '@deck.gl/core';
import {GeoJsonLayer} from '@deck.gl/core-layers';
import Map from './mapbox';

in the app.js

**Comment by ibgreen** [comment]
@localdevjs Sounds like you want to [start scripting with deck.gl](https://medium.com/vis-gl/start-scripting-with-deck-gl-c9036d7a6011)

**Comment by localdevjs** [comment]
Indeed! That looks pretty good, thanks for the link!
