### ISSUE TITLE
Capture layer output

### ISSUE THREAD

**Issue by edwinwebb** [uber/deck.gl#1853]
I want to capture the output of my custom layer along with the mapbox output as an image. I can capture the ReactMapGL output with `toDataUrl()` after enabling `preserveDrawingBuffer` but not the layer output from DeckGL.

**Comment by DLCJianyf** [comment]
I have the same problem

**Comment by DLCJianyf** [comment]
I have the same problem

**Comment by RichardWithnell** [comment]
Have you tried setting it in the DeckGL components glOptions prop? 

`glOptions={{ preserveDrawingBuffer: true }}`
