### ISSUE TITLE
Popup is not interactive in combination with trips example

### ISSUE THREAD

**Issue by norraell** [uber/deck.gl#1855]
#### Actual Result
Popup is not interactive, as it seems that the trips layer is rendered on top of it.

#### Expected Result
Popup should be interactive

#### Reproduce Steps

1.  Create an iconLayer that opens a popup when being clicked on (see here https://github.com/uber/react-map-gl/tree/master/examples/controls)
2. Check popup being interactive.
3. Add trips layer from deck.gl example.
4. Popup is not interactive anymore and trip layer seems to be rendered on top of popup.

#### Code snippet

Will add code whenever I have time for it, unfortunately I currently can't.

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)
