### ISSUE TITLE
[Coding] [Doc update]Tooltip code not found

### ISSUE THREAD

**Issue by MicalKarl** [uber/deck.gl#1861]
In the page 'http://uber.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/hexagon-layer', the 'setTooltip' function is not found in the code, it is undefined. Could the code definition be displayed, I searched the whole project code but not found!

**Comment by ianshan0915** [comment]
I managed to create [a scatterplot example](https://github.com/ianshan0915/deck-examples/tree/master/example-scatterplot) with the setTooltip function. I'm not sure if it's the code definition, but it works the same [the example](http://uber.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer).

**Comment by matthewjwhitney** [comment]
I am also having this issue with the Polygon Layer. In the documentation http://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer 'setTooltip' is not defined. I have searched far and wide for the definition of this function and have found nothing that works. Please give us a clearer definition of this function.

**Comment by Pessimistress** [comment]
We do not include specific code for tooltips because it can be wildly different depending on if you are using React or not. You can find sample code in the examples folder, e.g.

React:
https://github.com/uber/deck.gl/blob/master/examples/website/geojson/app.js#L89

Pure JS:
https://github.com/uber/deck.gl/blob/master/examples/gallery/src/geojson-layer.html#L107

**Comment by layik** [comment]
Strangely enough, the html version works!

**Comment by layik** [comment]
If you land here hours into searching for the `settooltip`, make sure you try with a different class name in React/other npm package, in case `tooltip` is already used by another css definition. That cost me hours of frustration.
