### ISSUE TITLE
how can i interactive with mapboxgl 

### ISSUE THREAD

**Issue by dfy167** [uber/deck.gl#1863]
i flowed the example in get-started/pure-js
but the interactive of mapboxgl is disabled.
i changed it to true.
but it still can not interactive. 
i think is because the div of deck  covered the div of mapboxgl.
are there any way to interactive both with mapboxgl and deck

```
 this._map = new mapboxgl.Map({
      ...props,
      attributionControl: false,
      interactive: true,
      center: [viewState.longitude, viewState.latitude],
      zoom: viewState.zoom,
      bearing: viewState.bearing,
      pitch: viewState.pitch
    })
```

**Comment by Pessimistress** [comment]
By interactive you mean user interaction with the map? The example is supposed to be fully interactive.
If are you trying to access a particular API of the mapboxgl Map instance, use `deck.getMapboxMap()`.
