### ISSUE TITLE
Interactivity documentation needs an update

### ISSUE THREAD

**Issue by karussell** [uber/deck.gl#1886]
Thanks for deck.gl! ([having fun with it](https://github.com/graphhopper/isochrone-experiments/tree/deckgl) and nothing what I tried was faster :+1: )

Now to the interactivity documentation:

1. Two links are not properly set here: https://github.com/uber/deck.gl/blob/master/docs/get-started/interactivity.md#calling-the-picking-engine-directly

2. when I tried the code there it seems that instead of `onClickHandler = (event) => {` one should use `onClickHandler(event){` in MyComponent to make it compiling?

3. This compiles but now I got `this is undefined` within onClickHandler. But it looks like it should work, so I had a look into [this](https://github.com/uber/deck.gl/blob/master/examples/layer-browser/src/app.js) example and when adding autobind(this) in the constructor it finally works (plus `import autobind from 'react-autobind';` and adapting package.json). Not sure if this is obvious in react world (new to this).

**Comment by tgorkin** [comment]
1. links have been fixed.  For 2. and 3., you'll need to use https://www.npmjs.com/package/@babel/plugin-proposal-class-properties or an equivalent plugin for you bundler to fix those issues.
