### ISSUE TITLE
bitmap layer

### ISSUE THREAD

**Issue by xintongxia** [uber/deck.gl#1893]
#### Background 
Bitmap layer is used to place single or multiple images in given positions. It could be used with other deck.gl layers.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by dhdemerson** [comment]
We're needing this in AV Maps for Map Maker to overlay ground truth imagery collected by the AV

**Comment by coenvalk** [comment]
Looks like there's already some work on a bitmap layer. See [here](https://github.com/uber/deck.gl/tree/d559daa95bdd7882e8acfff773734abad1ff2aec/test/apps/sample-layers/bitmap-layer).

**Comment by ibgreen** [comment]
> Looks like there's already some work on a bitmap layer. See here.

Yes indeed, that is a very old incarnation of this layer - not sure if it is even working with the latest deck release. 

Basically, we have an improved version of that layer that we want to clean up and add to the deck.gl repo as an official documented and supported layer, removing/replacing the code you pointed to.

**Comment by tgorkin** [comment]
Closing, duplicated by #2548
