### ISSUE TITLE
`npm run bench` issues

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1914]
#### Actual Result
- npm run bench fails
#### Expected Result
- npm run bench works
#### Reproduce Steps
- npm run bench
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by ibgreen** [comment]
@1chandu Opening a PR with some fixes, but some remaining issue with GPU aggregation depending on WebGL2.

**Comment by 1chandu** [comment]
@ibgreen I just pushed a change to  #1915 to disable GPUAggregator tests for WebGL1 context , it is applicable for WebGL2 only.
