### ISSUE TITLE
why ScatterPlotLayer can not draw point both with fill and border??? 

### ISSUE THREAD

**Issue by DLCJianyf** [uber/deck.gl#1919]
is it possible to realize? how should i do?

**Comment by ibgreen** [comment]
A common technique is to use two scatterplot layers, one for the fill and one for the outline. It may require an extra step to make sure you don't get [Z fighting](http://uber.github.io/deck.gl/#/documentation/developer-guide/tips-and-tricks?section=z-fighting-and-depth-testing) between the layers.

**Comment by DLCJianyf** [comment]
It' s really a solution. But if i did so, it will draw twice the amount of data. And every point has its's own style. it will be twice amount of cacultation again .It's performance will be greatly affected

**Comment by DLCJianyf** [comment]
is there any other solution?

**Comment by DLCJianyf** [comment]
can anyone help me about this??
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546708-f5e7c8b0-7350-11e8-9c24-4a564ec27c15.png)
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546641-c91ec5fe-7350-11e8-9dd7-46bc79ea57c9.png)
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546667-dd1dde32-7350-11e8-8a69-974fa66496bc.png)
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546731-00171caa-7351-11e8-984a-fa9918eea139.png)
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546740-04627e3a-7351-11e8-8ed4-aeac5ba8d4d8.png)
![tim 20180618233645](https://user-images.githubusercontent.com/18675306/41546747-083cd564-7351-11e8-93c9-35883feced13.png)

**Comment by ibgreen** [comment]
@DLCJianyf Have you actually tried and seen performance suffer? How many points are you drawing? We have internal applications that use this technique, with big data sets with great performance.

If it truly is an issue, you could always subclass the ScatterplotLayer and modify the shader.

**Comment by DLCJianyf** [comment]
surely,i have saw it. very thankful  for your tip

**Comment by DLCJianyf** [comment]
got it.
![image](https://user-images.githubusercontent.com/18675306/41704904-133a5372-756a-11e8-85f1-eff426be7e8e.png)

**Comment by ibgreen** [comment]
@DLCJianyf You did it, congratulations! It looks really nice with the color gradient.

Although resolution seems a bit low, it looks a little pixelized? Maybe some `smoothstep`-ing of transparency in the fragment shader could help? Just a tip in case you want to keep improving your custom shaders...

**Comment by DLCJianyf** [comment]
yes, i think it will very useful for me. I will try it

**Comment by DLCJianyf** [comment]
It seems that the code did not support webgl fWidth function..............

**Comment by ibgreen** [comment]
`fwidth` (note the lowercase `w`) either requires writing your shader in GLSL 3.00 ES and using WebGL2 (Chrome or Firefox only) or using a WebGL1 extension (`OES_standard_derivatives`).

I believe that luma.gl automatically tries to install that extension, so maybe it is not available on your browser?

**Comment by DLCJianyf** [comment]
It looks better
![image](https://user-images.githubusercontent.com/18675306/41819976-ad3c1f8e-77fc-11e8-97f9-f7a38e79a96c.png)

**Comment by ibgreen** [comment]
@DLCJianyf That looks great, delighted to see that you got it all to work! 

Would you be interested in contributing your improvements back to deck.gl? You could open a PR on the original `ScatterplotLayer` (or add a new `EnhancedScatterplotLayer` in `experimental-layers`) and we could take a look...

**Comment by matthrice** [comment]
Sorry to reopen this issue, but can I ask how this is achieved? I'm having an issue where two overlapping layers using the same data only renders one instance. For example, the following code will only render the last `ScatterplotLayer` in the array:

```
render() {
    const coords = [
      { position: [-79.92974571588147, 40.459702877261044, 0] },
      { position: [-79.92892772595097, 40.459069877880204, 0] },
      { position: [-79.92859965826088, 40.458421518470075, 0] },
      { position: [-79.92753871886694, 40.45849420710192, 0] }
    ];

    const outline = new ScatterplotLayer({
      id: 'outline',
      data: coords,
      getRadius: 30,
      getColor: [0xff, 0xff, 0xff, 0xff],
    });

    const fill = new ScatterplotLayer({
      id: 'fill',
      data: coords,
      getRadius: 15,
      getColor: [0x00, 0x00, 0x00, 0xff],
    });

    // order matters
    const layers = [outline, fill];

    return (
      <DeckGL
        {...this.props.viewport}
        layers={layers}
      />
    );
  }
```

**Comment by ibgreen** [comment]
As a first step, try adding `parameters: {depthTest: false}` to the second layer:

```js
   const fill = new ScatterplotLayer({
      id: 'fill',
      data: coords,
      getRadius: 15,
      getColor: [0x00, 0x00, 0x00, 0xff],
      parameters: {
        depthTest: false
      }
    });
```

**Comment by matthrice** [comment]
Looks like just updating to 6.0.1 solved the issue. But thanks regardless!
