### ISSUE TITLE
not ok 741 cpu and gpu results should match (with Intel GPU)

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#1940]
```
not ok 741 cpu and gpu results should match
index.js:13   ---
index.js:13     operator: deepEqual
index.js:13     expected: |-
index.js:13       { counts: { 0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 48: 0, 49: 0, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 58: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 0, 73: 0, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 91: 0, 92: 0, 93: 0, 94: 0, 95: 0, 96: 0, 97: 0, 98: 0, 99: 0 }, maxCount: { 0: 0, 1: 0, 2: 0, 3: 0 } }
index.js:13     actual: |-
index.js:13       { counts: { 0: 2, 1: 10.100000381469727, 2: 0, 3: 0, 4: 1, 5: 1, 6: 0, 7: 0, 8: 2, 9: 9, 10: 0, 11: 0, 12: 0, 13: 0, 14: 0, 15: 0, 16: 0, 17: 0, 18: 0, 19: 0, 20: 0, 21: 0, 22: 0, 23: 0, 24: 0, 25: 0, 26: 0, 27: 0, 28: 0, 29: 0, 30: 0, 31: 0, 32: 0, 33: 0, 34: 0, 35: 0, 36: 0, 37: 0, 38: 0, 39: 0, 40: 0, 41: 0, 42: 0, 43: 0, 44: 0, 45: 0, 46: 0, 47: 0, 48: 3, 49: 11, 50: 0, 51: 0, 52: 0, 53: 0, 54: 0, 55: 0, 56: 0, 57: 0, 58: 0, 59: 0, 60: 0, 61: 0, 62: 0, 63: 0, 64: 0, 65: 0, 66: 0, 67: 0, 68: 0, 69: 0, 70: 0, 71: 0, 72: 3, 73: 278, 74: 0, 75: 0, 76: 0, 77: 0, 78: 0, 79: 0, 80: 0, 81: 0, 82: 0, 83: 0, 84: 0, 85: 0, 86: 0, 87: 0, 88: 0, 89: 0, 90: 0, 91: 0, 92: 0, 93: 0, 94: 0, 95: 0, 96: 0, 97: 0, 98: 0, 99: 0 }, maxCount: { 0: 11, 1: 309.1000061035156, 2: 0, 3: 278 } }
index.js:13     stack: |-
index.js:13       Error: cpu and gpu results should match
index.js:13           at Test.assert [as _assert] (http://localhost:8080/bundle.js:107373:54)
index.js:13           at Test.bound [as _assert] (http://localhost:8080/bundle.js:107225:32)
index.js:13           at Test.tapeDeepEqual (http://localhost:8080/bundle.js:107570:10)
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
@georgios-uber , there are two tests that compare cpu, gpu results,  `cpu and gpu results should match`.
`test('GPUGridAggregator#CompareCPUandGPU', t => {` and `test('GPUGridAggregator worldspace aggregation #CompareCPUandGPU', t => {` 
Can you tell me which one is failing, couldn't figure out based on text you copied above. By the way this could be specific to your browser as theses tests are enabled in master already. But I will take a look into it and disable them if needed.

**Comment by georgios-uber** [comment]
> ok 728 total count should match
> index.js:13 ok 729 total weight should match
> index.js:13 ok 730 max weight should match
> index.js:13 # GPUGridAggregator#CPU
> index.js:13 ok 731 total count should match
> index.js:13 ok 732 total weight should match
> index.js:13 ok 733 max weight should match
> index.js:13 # GPUGridAggregator#CompareCPUandGPU
> program.js:77 luma: Program unnamed-program-4: Attribute -1:gl_InstanceID not supplied
> checkAttributeBindings @ program.js:77
> index.js:13 ok 734 cpu and gpu results should match
> index.js:13 # GPUGridAggregator worldspace aggregation #CompareCPUandGPU
> program.js:77 luma: Program unnamed-program-6: Attribute -1:gl_InstanceID not supplied
> checkAttributeBindings @ program.js:77
> index.js:13 not ok 735 cpu and gpu results should match
