### ISSUE TITLE
Polygon starting at certain height

### ISSUE THREAD

**Issue by carlos12silva94** [uber/deck.gl#1956]
Hi. Is there any way to set a height to start drawing a polygon in polygon layer so it doesn't start from the ground? For example, having a bridge polygon

**Comment by ibgreen** [comment]
@carlos12silva94  You should be able to use the `Layer.modelMatrix` prop. If I get some time I'll see if we can provide you with a working example.

**Comment by ibgreen** [comment]
It would raise all polygons in the same layer to the same height, so it may not work if you have many different heights, but perhaps as a temporary workaround?

**Comment by danmarshall** [comment]
I may have [asked the same question](https://github.com/uber/deck.gl/issues/1525#issuecomment-388156301) on another issue. If your question is the same, @Pessimistress [provided me the answer](https://github.com/uber/deck.gl/issues/1525#issuecomment-388419281):

> you can set the "floor" by adding a z component to your polygon coordinates:
https://codepen.io/Pessimistress/pen/MGGEYK
