### ISSUE TITLE
Where to post questions?

### ISSUE THREAD

**Issue by karussell** [uber/deck.gl#1980]
I've seen no information where to ask questions. Should it be done here or is there a forum? [I've posted one](https://stackoverflow.com/q/50662130/194609) at stackoverflow but not even a bounty raised attention.

**Comment by ibgreen** [comment]
Sorry we don't look much at stackoverflow, we probably should. We do try to be responsive to issues here however. 

> It is probably very easy but I couldn't find how to add a new layer below the labels for deck.gl which uses Mapbox GL JS under the hood. For mapbox gl it is explained here.

> I searched their docs also for z-index or picking the label layer from the vector tiles source but without success so far.

About your issue:

- If your question related to relative rendering order of deck.gl layers then maybe this [section in the docs](http://uber.github.io/deck.gl/#/documentation/developer-guide/tips-and-tricks) helps?
- Looking at your question in another way: we don't currently support interleaving deck.gl layer with mapbox style layers. deck.gl layers are always on top of the base map (and its labels). We are working with mapbox to see if we can change that in the longer term, but for now that is the situation.
- An extreme approach to get around the mapbox/deck limitation is to wrap deck.gl in two mapbox instances, but that has its own complications and limitations so it really depends on your app.

**Comment by karussell** [comment]
> We do try to be responsive to issues here however.

Great thanks - maybe write this into "help section"?

> About your issue

Thanks - understood. I think point 2 answer my question as I would need 

 1. vector tiles without labels
 2. custom layer
 3. only labels of vector tiles

Is there already an issue for this feature request that we can reference here or at SO?
