### ISSUE TITLE
Module not found: Error: Can't resolve 'global/window' in ./node_modules/@deck.gl/experimental-layers/dist-es6/advanced-text-layer/advanced-text-layer.js

### ISSUE THREAD

**Issue by oller** [uber/deck.gl#1989]
- Clone latest release, 5.3.2.  
- cd to `examples/layer-browser` directory
- `yarn install`, then `yarn start`.
- This error occurs.

This also happens on master branch too.  

Using node v6.12.0

Any ideas?

**Comment by Pessimistress** [comment]
layer-browser is for testing purpose. You can run it via the following steps:
```bash
npm run bootstrap # install root dependencies
cd examples/layer-browser
npm run start-local # run against source
```

@ibgreen @jianhuang01 is layer-browser intended to work standalone? Shall we move it under the `test` directory?

**Comment by ibgreen** [comment]
@georgios-uber 

Let's remove reference to global/window from AdvancedTextLayer. deck.gl does not include the `global` module.

**Comment by ibgreen** [comment]
> @ibgreen @jianhuang01 is layer-browser intended to work standalone? 

Valid question... we might want to define a "roadmap" for the layer-browser.

My off-the-cuff preference would be to keep `layer-browser` in the examples folder, try to fix any minor issues related to making it work standalone (we have to fix the `website` apps as well).

It is a really useful app. The main problem is that the source code has gotten messy. I think we should gradually clean it up. 

Of course, the advent of JSON layers is bound to have some impact on the scope or usefulness of layer browser, we should consider what the desired long-term state is.


> Shall we move it under the test directory?

The `test/apps` directory has become a staging place for unfinished examples. Doesn't feel like the right home for something as complete and useful as the layer-browser...

**Comment by georgios-uber** [comment]
So what is the problem? Importing window?
Why is it a problem?

**Comment by ibgreen** [comment]
> So what is the problem? Importing window?
Why is it a problem?

`AdvancedTextLayer` is importing window from the module `global` which is not a dependency of `deck.gl`.
