### ISSUE TITLE
Polygon layer doesn't close strokes, but documentation implies it does

### ISSUE THREAD

**Issue by pbeshai** [uber/deck.gl#1992]
#### Actual Result
![image](https://user-images.githubusercontent.com/793847/42221597-8d4e9d46-7ea0-11e8-914f-4547a37e84c3.png)

#### Expected Result
![image](https://user-images.githubusercontent.com/793847/42221604-96cbc132-7ea0-11e8-81e3-3594bc330859.png)

#### Reproduce Steps
Add a polygon where the first coordinate is not the same as the last and the stroke is not closed. While it's no problem to just modify my polygon coordinates to repeat the last one, [the documentation reads](http://uber.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer?section=remarks) (Remarks section):

> Polygons are always closed, i.e. there is an implicit line segment between the first and last vertices, when those vertices are not equal.

#### Code Example 
```js
new PolygonLayer({
  id: 'polygon-layer',
  data: [
    [
      [-114.07, 35.516844],
      [-115.07, 35.516844],
      [-115.07, 36.516844],
      [-114.07, 36.516844],
      // [-114.07, 35.516844], // uncomment this to get it to close (first point reproduced)
    ],
  ],
  stroked: true,
  filled: true,
  wireframe: false,
  extruded: false,
  lineWidthMinPixels: 1,
  getPolygon: d => d,
  getFillColor: [255, 0, 0, 20],
  getLineColor: [255, 0, 0],
  getLineWidth: 1,
})
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by SymbolixAU** [comment]
I'm seeing a different result to this, where there is a 'closed' polygon, but the `stroke` doesn't appear to work

![screen shot 2018-08-27 at 12 28 31 pm](https://user-images.githubusercontent.com/18344164/44637495-bf378000-a9f4-11e8-905c-8851ac037fcf.png)

using the same code, and `deck.min.js 6.0.3`

```js
  const polygonLayer = new PolygonLayer({
  id: 'polygon-layer',
  data: [
    [
      [-114.07, 35.516844],
      [-115.07, 35.516844],
      [-115.07, 36.516844],
      [-114.07, 36.516844],
      // [-114.07, 35.516844], // uncomment this to get it to close (first point reproduced)
    ],
  ],
  stroked: true,
  filled: true,
  wireframe: false,
  extruded: false,
  lineWidthMinPixels: 1,
  getPolygon: d => d,
  getFillColor: [255, 0, 0, 20],
  getLineColor: [255, 0, 0],
  getLineWidth: 1,
})
```

**Comment by ibgreen** [comment]
@SymbolixAU Thanks for reporting!

While we triage this, should you have time to help us poke around a little, perhaps set a break point [here](https://github.com/uber/deck.gl/blob/502abecfff39950393e52578f35bbbaee7f6f654/modules/layers/src/solid-polygon-layer/polygon.js#L44) and see if this function gets hit, or the one the calls it etc?

**Comment by SymbolixAU** [comment]
I would love to help more but at the moment I'm still learning how to use/build/debug JS, so don't expect a quick turn-around from me. Should I make progress I'll certainly help out where I can. 

---

However, while I've been experimenting with all the layers I've noticed another anomaly (let me know if you want this turned into its own issue):

Both these screenshots are plotting the same data. The first uses a `Polygon` layer, the second uses `Geojson` layer. 

![screen shot 2018-08-29 at 2 16 53 pm](https://user-images.githubusercontent.com/18344164/44765051-42dca280-ab96-11e8-96d0-8dfcff3480a2.png)

![screen shot 2018-08-29 at 2 17 06 pm](https://user-images.githubusercontent.com/18344164/44765058-4a03b080-ab96-11e8-87a8-944718e6702d.png)

I've logged the coordinates which get returned to the `getPolygon` accessor in the console. The polygon layer appears to only plot one of the 3 polygon arrays

---

If it's helpful the raw data (WKT) of the layer is

```
MULTIPOLYGON (((-75.78317 36.22519, -75.77316 36.22926, -75.54497 35.78836, -75.70274 36.04986, -75.74087 36.05032, -75.78317 36.22519)), ((-75.89149 35.63127, -75.90803 35.66564, -76.02121 35.66909, -75.98785 35.89271, -75.81805 35.92352, -75.74896 35.86934, -75.72937 35.66517, -75.77905 35.57869, -75.89149 35.63127)), ((-75.49122 35.6705, -75.53362 35.76886, -75.45698 35.6174, -75.5263 35.22792, -75.74929 35.18983, -75.69157 35.23499, -75.52148 35.28136, -75.47542 35.5645, -75.49122 35.6705)))
```

**Comment by ibgreen** [comment]
> The polygon layer appears to only plot one of the 3 polygon arrays from the MULTIPOLYGON, but all of the individual POLYGONs

"multi polygons" are a GeoJsonLayer concept. The `PolygonLayer` was designed to show a list of "single" polygons (more precisely each polygon be a lists of polygons where the first polygon is the outer outline and the remaining polygons are "holes"). 

> A bit of digging suggests this could be related to the orientation of the polygons (clockwise vs anti-clcokwise). When using 'complex' polygons, Is the Polygon layer affected by the winding?

Winding order should not have an effect on flat polygons, if it does a minimal reproducible case would be great.

If I recall correctly polygon winding order only affects the direction of "normals" on extruded polygons (important mainly for correctly applying lighting), and I believe we have code to handle that.

**Comment by SymbolixAU** [comment]
Ok that makes sense - the applications will need to handle `MULTIPOLYGON` objects when plotted in the `PolygonLayer`. 
Thanks.
