### ISSUE TITLE
Learning Deck.gl

### ISSUE THREAD

**Issue by phemmmie** [uber/deck.gl#1997]
Good Day All. 
please can anyone help me with links to learn deck.gl 
And also recommend books.

**Comment by shreym03** [comment]
I think these links might help you out:

[Vis Academy](http://vis.academy/#/): This is the tutorial site made by the developer (I think) to learn how to use deck.gl

[Deck.gl Documentation](http://deck.gl/#/documentation/overview/introduction): Lot of information over here

I would also recommend looking at the code from the examples on Github to understand how each layer works

**Comment by 1chandu** [comment]
Yes [Vis-academy](http://vis.academy/#/) and then dig into example code by downloading deck.gl repo.

**Comment by phemmmie** [comment]
Thanks so much team i will need a link for videos if available
