### ISSUE TITLE
Add heatmap layer

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#2]
A finer-grained heat map layer as compares to the grid layer.

- [x] Add custom FS support to Transform for running KDE on offline rendering.
- [x] Add Heatmap Layer.
- [x] Docs
- [x] Render tests
- [x] Unit tests
- [x] Whats-new
- [x] API Audit

**Comment by contra** [comment]
Anyone working on this? Might make time to look into it this weekend if not - the one bundled w/ map-gl has some really major perf issues

**Comment by gnavvy** [comment]
Hi @contra, we are currently working on some other features and can definitely use some help here :)

**Comment by vicapow** [comment]
Hey @contra! If you're talking about https://github.com/vicapow/react-map-gl-heatmap-overlay would love to hear more info on the perf issues you're experiencing.

**Comment by contra** [comment]
@vicapow The issue with `react-map-gl-heatmap-overlay` is:

- location accessor map over dataset not being cached - immutablejs `.get()` and `.getIn()` are super costly!
- iterating every data point on every draw for mercator projection

Even with only ~10K items in immutable the framerate is incredibly low and the main thread is locked up consistently.

Doing the projections on the gpu (with this module) solves all of these problems.

Caching the output of mapping locationAccessor over the data set alleviates the major bottleneck and allows you to render ~20K items with a decent framerate, but I still think doing the projections in JS at all is going to be a bottleneck for our case (10M+ data points, trying to render as many as possible @ 60fps).

**Comment by jianhuang01** [comment]
Will be resolved by #1414

**Comment by 1chandu** [comment]
We will be working on this layer for next major deck.gl release (6.0 or 6.1, currently building GPU aggregation pieces).

**Comment by jay-manday** [comment]
is this still coming in 7.0.0? a port of @vicapow 's webgl heatmap for both geospatial and identity based systems would be amazing and super relevant to the use case im working through in #2673

**Comment by tgorkin** [comment]
This will likely not make it in for 7.0 release.  I expect this will release in 7.1 or 7.2.

**Comment by SymbolixAU** [comment]
Can I add a request that the elevation of a point be considered, and therefore render the heatmap in 3D?

**Comment by 1chandu** [comment]
@SymbolixAU , it is possible, but can you give more details of your use case?

**Comment by SymbolixAU** [comment]
I don't have a specific use-case in mind yet, but a lot of the data I work with has elevation, so I thought it might be an interesting component of a heatmap.

**Comment by 1chandu** [comment]
This can be closed once #3384 is merged, remaining issues are tracked here: #3385

**Comment by SymbolixAU** [comment]
nice work!
