### ISSUE TITLE
OnHover doesn't work with IconLayer Example

### ISSUE THREAD

**Issue by shreym03** [uber/deck.gl#2000]
What do I do to get a Tool-tip while hovering over Icons in the meteorite example. It isn't clearly explained anywhere I look. So I'm unsure how to get the same results displayed on their website
#### Actual Result
I don't see the Tool-tip while Hovering over the Icons with the example I downloaded
#### Expected Result
I wanted the example to work like how it works over [here](http://deck.gl/#/examples/core-layers/icon-layer)

**Comment by 1chandu** [comment]
@shreym03 , the website version uses extra logic to display too-tips which isn't present in example. You can check :  https://github.com/uber/deck.gl/blob/c6e8ac1a97505df995cef68277cc77978751bb46/website/src/components/demos/icon-demo.js#L75
