### ISSUE TITLE
64bit layers (choropleth and building) not rendering on a Linux box. 

### ISSUE THREAD

**Issue by philogb** [uber/deck.gl#201]
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

Gpu Summary:
Operating system	Linux 4.7.6-sabayon
Software rendering list version	0
Driver bug list version	8.93
ANGLE commit id	c9e893119842
2D graphics backend	Skia

**Comment by shaojingli** [comment]
is this on virtual machine?
Will need to reproduce the environment and take a look at it tomorrow.

**Comment by philogb** [comment]
@Pessimistress

**Comment by Pessimistress** [comment]
I think we should at least attempt to detect that 64bit is not supported... then I can fallback to use the 32bit version.

**Comment by shaojingli** [comment]
We need to formulate a strategy on cross-platform support of deck.gl.

**Comment by rmackinnon** [comment]
Greetings, bug reporter here...

This is running on bare metal with an AMD/Radeon HD6400M

lspci:
...
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series]
...

relevant glxinfo snippets:
name of display: :1
display: :1  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
...
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD CAICOS (DRM 2.45.0 / 4.7.0-sabayon, LLVM 3.8.1) (0x6760)
    Version: 12.0.2
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD CAICOS (DRM 2.45.0 / 4.7.0-sabayon, LLVM 3.8.1)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.2
OpenGL core profile shading language version string: 3.30
...
OpenGL version string: 3.0 Mesa 12.0.2
OpenGL shading language version string: 1.30
...
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 12.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00

Journal error messages logged:
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_shader.c:3662 r600_shader_from_tgsi - GPR limit exceeded - shader requires 225 registers
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_shader.c:182 r600_pipe_shader_create - translation from TGSI failed !
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_state_common.c:798 r600_shader_select - Failed to build shader variant (type=0) -12
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_shader.c:3662 r600_shader_from_tgsi - GPR limit exceeded - shader requires 225 registers
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_shader.c:182 r600_pipe_shader_create - translation from TGSI failed !
Nov 09 21:01:16 hostname google-chrome.desktop[3492]: EE /var/tmp/portage/media-libs/mesa-12.0.2/work/mesa-12.0.2/src/gallium/drivers/r600/r600_state_common.c:798 r600_shader_select - Failed to build shader variant (type=0) -12

I have a kernel bump available for 4.8.x ... but don't think it will make things better there.  Might have a Mesa bump too.  Will check and get back.

**Comment by shaojingli** [comment]
@rmackinnon thanks for reporting...

**Comment by rmackinnon** [comment]
There is a bump on Mesa to 13.0.0, installing and seeing if it resolves the GPU issue.  Meanwhile...

Complete environment info:
Machine: HP Elitebook 8560p
CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
Cores: 4
Memory: 16GB
OS: Linux 4.7.6 AMD64
Xorg Server Version: 1.17.4
Mesa Version: 12.0.2
Window Manager: Gnome 3.18
Chrome Version: 53.0.2785.143

**Comment by rmackinnon** [comment]
Bumped my Mesa version to 13.0.0, but same reportable error on shader usage. Let me know if you need anything else.

Cheers

**Comment by shaojingli** [comment]
From the error message, it seems that it's specific to AMD r600 GPU using MESA driver...

**Comment by contra** [comment]
@shaojingli Is the goal to make the 64 bit work everywhere, or to have the 64 bit only work on some GPUs and fall back to the 32 bit? Curious what the cross-platform strategy is

**Comment by shaojingli** [comment]
@rmackinnon I tested MESA driver's software renderer using a Ubuntu box, deck.gl works as expected. The issue here is more of the MESA driver problem regarding this AMD's r600 GPU chipset. The front-end compiler seems to generate codes that the GPU can't handle. My recommendation is to upgrade to AMD's proprietary driver or using software renderer.

**Comment by shaojingli** [comment]
@contra The goal is to make 64-bit layer on all WebGL compliant platforms. There is really no technical reasons they are not working since it's just a bunch of GLSL shaders. We will elaborate our cross platform support strategy in upcoming versions
