### ISSUE TITLE
Elevations of Hexagon Layer get shorter after using "transitions" in hexagon layer

### ISSUE THREAD

**Issue by ricardoCyy** [uber/deck.gl#2010]
#### Actual Result
I updated version from 5.2 to 5.3 for "transitions" property of Hexagon layer. The elevations of hexagons get shorter and not matching with the number of points in the hexagon (some hex have more points but shorter than the other) after adding "transitions" in properties and, besides, every time when data gets updated no transition shows up.
[before](https://github.com/ricardoCyy/imgs/raw/master/comments/before.png)
[after](https://github.com/ricardoCyy/imgs/raw/master/comments/after.png)
[properties](https://github.com/ricardoCyy/imgs/raw/master/comments/issue.png)

Two errors showed in the console after I added "transitions" in my code.
[error1](https://github.com/ricardoCyy/imgs/raw/master/comments/error1.png)
[error2](https://github.com/ricardoCyy/imgs/raw/master/comments/error2.png)
#### Expected Result
Attribute transition when data update.

Any hints appreciated. :)

**Comment by ricardoCyy** [comment]
@Pessimistress Sorry for my late reply. Yes, I'm using the latest release of Chrome(67.0.3396.99). And I also tried on Firefox and it shows the same problem.

**Comment by ibgreen** [comment]
@Pessimistress My understanding is that this is fixed in v6 and too costly to fix in 5.3. Should we close as WONT FIX?

**Comment by jianhuang01** [comment]
won't fix per team decision
