### ISSUE TITLE
Orthographic view issues on 6.0

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2019]
1. Zoom is broken
2. ScreenGridLayer rendering is bad on first instance, re-rendering fixes it, could be related to above point.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by 1chandu** [comment]
CC: @javidhsueh

**Comment by 1chandu** [comment]
Need to re-test with #2024 for item#2

**Comment by javidhsueh** [comment]
I've confirmed that zoom works again
