### ISSUE TITLE
v6 onHover doesn't fire when mouse moves over to absolutely positioned element in front of canvas

### ISSUE THREAD

**Issue by oller** [uber/deck.gl#2027]
I've an absolutely positioned toolbar on top of my deck.gl visualisation, with a greater z-index and previously worked fine.

**v.5.3.2**
With build 5.3.2 when I mouse over to the toolbar, any tooltips disappear as the `object` returned by `onHover()` is undefined, and the tooltip disappears.  So the `onHover` event is firing, but it knows its obfuscated by the toolbar so returns undefined.

**v6**
The`onHover()` does not fire at all, so the ghost tooltip stays there.  Unsure what event I can use to hide any tooltips.

It seems the onHover detection has changed?  Is this a regression, or should we be looking for a different method to clear tooltips now? I couldn't find it documented in the upgrade guide.

Fantastic library, really enjoying the transitions in v6, this is the only issue i've encountered upgrading

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
@oller thanks for reporting. Are you using React? Can you share a sample of your render tree?

**Comment by oller** [comment]
No problem @Pessimistress.  I'm actually using the pure js implementation.

I could create a codepen to recreate the issue, but it looks like you may have made some further progress already.  Let me know if this would be helpful.

**Comment by shreym03** [comment]
Follow Isuue #1128. I implemented that code to my app.js, It seemed to work. Although I'm not getting the list like it is given in the Icon Layer Example on their website. 
Not sure what to change

**Comment by oller** [comment]
This appears to be fixed with the latest Release Candidate (6.0.0-r.c.1).  Closing and thank you!
