### ISSUE TITLE
GeoJson points in GeoJsonLayer over the 180th meridian doesn't show

### ISSUE THREAD

**Issue by JBoudMS** [uber/deck.gl#2051]
In a GeoJson Feature collection of points, if you have points that cross the 180th meridian from the current viewport, they aren't shown.
#### Actual Result
For example, if you have a GeoJSON feature collection with two points, `[170, -35]` and `[-170, -35]`, then you can only see one of them based on which side of the 180th meridian your viewport is on. In the example repo, this is the two maps on the left.

This can be mitigated by for each point adding another point that is +/- 360 (based on what side you need it on), so you end up with points: `[170, -35]`, `[-190, -35]`, `[-170, -35]`, `[190, -35]`. Unfortunately with a real-time dataset of my size, this adds a lot of strain to the processing and memory of the app and is not feasible. In the example repo, this is the two maps on the right.

#### Expected Result
That all feature collection points are visible when inside the viewport, whether they are across the 180th meridian or not.

#### Reproduce Steps
Create a DeckGL GeoJsonLayer with a feature collection like so:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          -170.5078125,
          -42.81152174509788
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          175.78125,
          -41.244772343082076
        ]
      }
    }
  ]
}
```
Pan the map from -35, 170 to -35, -170 and one of the points will disappear and one will appear. Pan back and they will swap.

#### Code Example
[**Running example:** The Actual Result are the left two maps, the desired result _(achieved via a means I can't use in production)_ are the right two](https://jboudms.github.io/deck-gl-geojson-over-180th-meridian-issue/)

[The GitHub repo for the code](https://github.com/JBoudMS/deck-gl-geojson-over-180th-meridian-issue/tree/master)

**Comment by SinZ163** [comment]
+1, This is annoying when working with data around Australia / New Zealand
