### ISSUE TITLE
v6.0 Website issues

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2070]
## Firefox

- [x] IconLayer does not work in Firefox: `Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.`
- [x] AsciiLayer demo is broken

## Chrome

- [ ] GeoJson (Paths) - Changing year not visible (faster transitions?)
- [ ] ScreenGridLayer - Just aesthetics, too little contrast, can we use a more distinctive color scale?
- [x] PlotDemo - crashes on resolution change
## Safari

- [ ] All Examples - Zoom (Macbook pinch) is broken
- [X] All Examples - Tons of NPOT disabling mipmapping warnings from luma.gl - probably from picking - wonder if these textures were intended to have mipmaps in the first place. see https://github.com/uber/luma.gl/issues/610
- [x] Home (Trips) - Lighting seems broken, buildings don't have tops
- [x] GeoJson (Polygons) - Lighting seems broken, polygons don't have tops
- [x] ScreenGrid -  Unusably slow (completely dead), we need a smaller data set on non-WebGL2 systems!
- [x] ScreenGrid -  Also GPU checkbox is checked even though not supported.
- [x] Arc Layer - Picking broken
- [x] ScatterplotLayer - Color picker Broken (expected - Safari 11 does not support color input https://caniuse.com/#feat=input-color)

- [x] PointCloudLayer - Loads but shows nothing
- [x] TextLayer - font not rendered correctly

## Edge (version 41.16299)
- [ ] All demos
     - [ ] Overall everything is slow, interaction and data-loads. 
     - [x] NPOT Warnings => see : https://github.com/uber/luma.gl/issues/610
     - [ ] Some number sliders don't show the indicator, instead shows a constant number on left
- [x] LineLayer - scatterplot instances are not circles, they are heart shaped. (Note: ScatterplotLayer demo renders fine) => fixed in 6.1.0-beta.1

<img width="1253" alt="linelayercircles" src="https://user-images.githubusercontent.com/9502731/42839048-4f4126dc-89b7-11e8-883a-06be4c43d050.png">

- [x] LineLayer regression with latest build, geometry and color is wrong.
<img width="1252" alt="linelayerregression" src="https://user-images.githubusercontent.com/9502731/42852544-0280f3fc-89e6-11e8-9cb4-baed0d72a002.png">

- [ ] ArcLayer : regression with latest build , renders nothing with error `WEBGL11037: INVALID_OPERATION: drawArraysInstanceANGLE: Insufficient buffer size`

- [x] IconLayer - no icons are rendered (could be same as Firefox issue)
- [ ] ScreenGridLayer
     - [ ] renders fine but shows WebGL Error in consoe: `WEBGL11112: INVALID_OPERATION: bindBuffer: Object cannot be used because it has been deleted
    - [ ] `GPU Acceleration` option is a slider instead of check box
 - [ ] ArcLayer : Width slider works but doesn't move the indicator (always shows 1)
<img width="356" alt="sliders" src="https://user-images.githubusercontent.com/9502731/42839062-6047a38e-89b7-11e8-90f8-dd4be5d35987.png">

- [x] TextLayer : 
    - [ ] Bottom portion of text is missing, trailing pixels on top portions.
<img width="535" alt="textlayerskipping" src="https://user-images.githubusercontent.com/9502731/42839073-681a18d0-89b7-11e8-970a-6e60a4121deb.png">

     - [ ] Warnings: `deck: Missing Character: x` for several characters. (o, a, etc)
- [ ] Trip Routes :
     - [ ] Invalid lighting on buldings
     - [ ] Incorrect geometry for buildings
<img width="1251" alt="tripsinvalidgeometry" src="https://user-images.githubusercontent.com/9502731/42839078-6e2bf932-89b7-11e8-8032-c2c803ee57d4.png">

- [x] 3D Surface Explorer: Graph labels missing -> fixed in 6.1.0-beta.1
- [x] Minecraft Chunk Viewer : Missing geometry (no walls) -> fixed in 6.1.0-beta.1
<img width="1244" alt="minecraft" src="https://user-images.githubusercontent.com/9502731/42839091-734a9842-89b7-11e8-8462-df06ada8dec6.png">

**Comment by ibgreen** [comment]
## Chrome Examples

GeoJson (Paths)
- Changing year not working under Chrome, seems to work in Safari (w/o transitions of course)?

Scatterplot 
- Chrome, too little contrast, can we use a more distinctive color scale?

TextLayer
- Loads but does not animate

**Comment by ibgreen** [comment]
## Safari Examples

General Examples Issues
- Zoom (Macbook pinch) is broken
- Tons of NPOT disabling mipmapping warnings from luma.gl - probably from picking - wonder if these textures were intended to have mipmaps in the first place.


Home (Trips)
- Lighting seems broken on home page, but not in individual example... 

Icon Layer
- Zoom (Macbook pinch) is broken

GeoJson (Polygons)
- Lighting seems broken
- Some top level polygons invisible.


GeoJson (Paths)
- Not working under Chrome, seems to work in Safari?


Scatterplot 
- Unusably slow (completely dead), we need a smaller data set on non-WebGL2 systems!
- Also GPU checkbox is checked even though not supported.


Arc Layer
- Picking broken


ScatterplotLayer
- Color picker Broken
<img width="273" alt="screen shot 2018-07-16 at 12 57 12 pm" src="https://user-images.githubusercontent.com/7025232/42780351-d16fe258-88f7-11e8-9154-8d22ea3b915a.png">


PointCloudLayer
- Loads but shows nothing


TextLayer
- Loads but does not animate (same as Chrome)

Brushing/3D Surface
- OK

**Comment by Pessimistress** [comment]
https://github.com/uber/deck.gl/pull/2064

**Comment by 1chandu** [comment]
> IconLayer does not work in Firefox: Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

CC: @Pessimistress 
The error may not be the real issue, it is warning we should fix, but there seem to be another problem:
1. I am seeing same errors when running the `website/example/icon` standalone demo and it renders fine.
2. I updated the shaders to not use any texture data just render rectangle, still nothing rendered for website demo on Firefox.

The real problem seem to be the `data` itself, if you print result of `getIcon` in `calculateInstanceIconFrames` it is `undefined` for every data sample, but in Chrome it has valid values for `88` samples. Could there be anything that can fail in Firefox in recent website demo changes?

**Comment by 1chandu** [comment]
@ibgreen @Pessimistress @jianhuang01 
Tested on Edge with updated builds, notable issues, update the list in description:
TripsLayer geometry is not fixed.
LineLayer: regression, updated pic above.
ArcLayer: regression, nothing is rendered.

**Comment by darionco** [comment]
Just wanted to add that in Edge the ArcLayer throws:
`WEBGL11037: INVALID_OPERATION drawArraysInstancedANGLE: Insufficient buffer size`

Google has very few hits on the specific issue (most of the, related to IE11), things I tried:
- Disable instanced rendering and drawing one arc (didn't work)
- Stubbed `bufferData` and `bufferSubData` to verify arguments (see: https://stackoverflow.com/questions/47021179/ie-11-bufferdata-does-not-allocate-transfer-data-to-vbo)
- Patched luma.js to not load the `ANGLE_instanced_arrays` extension (didn't work)

**Comment by ibgreen** [comment]
@darionco Thanks for reporting. Before release v6 we did a quick test pass on Edge and we discovered that

* Edge 17 was able to pass our smoke tests.
* Edge 16 had some issues with luma.gl 6.0, we have a patch in the works.

However, I am not sure the patch addresses your issue, so we will treat your comment as a bug report for now.
