### ISSUE TITLE
Setting strokeWidth in one line layer affects all other line layers

### ISSUE THREAD

**Issue by kenns29** [uber/deck.gl#2075]
#### Actual Result
Using deck.gl 6.0.0-rc
both lines have strokeWidth 60
https://codepen.io/kenns29/pen/MByvOj?editors=0001
#### Expected Result
Only 'line-2' should have strokeWidth of 1,
#### Reproduce Steps
https://codepen.io/kenns29/pen/MByvOj?editors=0001
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by tgorkin** [comment]
Fixed in 6.3.0
