### ISSUE TITLE
Docs: API reference links to source are 404

### ISSUE THREAD

**Issue by danmarshall** [uber/deck.gl#2080]
In the documentation API reference, the Source link at the bottom of each page results in a 404. Example from http://deck.gl/#/documentation/deckgl-api-reference/deck

Actual:
text: `modules/core/src/core/lib/deck.js`
url: `https://github.com/uber/deck.gl/blob/5.3-release/modules/core/src/core/lib/deck.js`

Expected:
text: `modules/core/src/lib/deck.js`
url: `https://github.com/uber/deck.gl/blob/5.3-release/modules/core/src/lib/deck.js`

**Comment by jianhuang01** [comment]
Fixed in 5.3-release branch
