### ISSUE TITLE
Contour layers: official release

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2086]
#### Background 
Contour Layer added as an experimental layer in 6.0, some of the remaining issues before we can officially release it.
- [x] Make it work for Info viz use cases (GPU Aggregator needs to support Orthographic viewport)
- [X] API-Audit
- [x] Add support for per threshold stroke width.
- [x] Move layer from `experimental-layers` to `layer`
- [x] Website: Add demo to the layer doc page.
    - [x] Verify build after landing the changes to master.
#### To Do List 
  - [X] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update 
  - [X] Test

**Comment by loganpowell** [comment]
I'm from the Census Bureau and am super stoked about the work you guys are doing. I found this issue by searching for "contour map" in your repo. I was hoping someone could easily help me out by letting me know if it would be possible to take Census boundaries and interpolate them into a contour map like this:

![contour map](https://i0.wp.com/flowingdata.com/wp-content/uploads/2016/10/frame00013.png?fit=1200%2C675&ssl=1)

here's a [link](https://flowingdata.com/2016/10/17/animated-map-of-unemployment/) to an article that shows an animation with similar characteristics to what we're trying to accomplish.

**Comment by 1chandu** [comment]
@loganpowell , thanks for the article and the link.

Our current version of Contour layer supports rendering boundaries only, but we are looking into expand this to [iso-bands](https://github.com/uber/deck.gl/issues/2180) and [gpu-acceleration](https://github.com/uber/deck.gl/issues/2182) next release, stay tuned.

**Comment by loganpowell** [comment]
Woot!
