### ISSUE TITLE
Question: declaratively setting GL parameters?

### ISSUE THREAD

**Issue by LINKIWI** [uber/deck.gl#2101]
The [documentation](http://deck.gl/#/documentation/deckgl-api-reference/deck?section=configuration-properties) is not particularly clear on how to set GL properties via the `parameters` Deck prop. I understand that this is now the preferred way to set GL properties (as opposed to using `onWebGLInitialized`).

Using this interface, how do we obtain a `gl` instance so we can set parameters? For example, I want to pass

```
parameters: {blendEquation: gl.FUNC_ADD}
```

but this requires me to get a WebGLRenderingContext instance from the initialization callback.

I wonder if the API can be asynchronous instead and supply a context as a callback parameter, e.g.

```
<Deck
  parameters={(gl) => ({ blendEquation: gl.FUNC_ADD })}
/>
```

**Comment by ibgreen** [comment]
Yes good question.

luma.gl exports static constants that enable you to use gl constants without access to a gl context.

```js
import GL from 'luma.gl/constants'; // deck/luma v6
import {GL} from 'luma.gl'; // deck/luma v5

  parameters: {
    blendEquation: GL.FUNC_ADD
```

This should be clarified in the docs, tagging this for tracking.

**Comment by LINKIWI** [comment]
I see, is `GL` re-exported from deck.gl at all? It feels awkward to import from luma.gl since it is a dependency of deck.gl rather than a peer dependency of the root project.
