### ISSUE TITLE
Hexagons rendered at (0, 0)

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2111]
#### Issue

I'm trying to recreate the [hexagon example](https://beta.observablehq.com/@pessimistress/deck-gl-hexagonlayer-example), but the hexagons aren't being rendered at the correct locations.  

The data is the road accidents in the UK as per
```
data = {
  return d3.csv('https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv', row => {
    return {lng: +row.lng, lat: +row.lat};
  })
```

#### Actual Result

In this screenshot I'm showing two layers - a **scatterplot** and a **hexagon**

![screen shot 2018-07-23 at 12 40 30 pm](https://user-images.githubusercontent.com/18344164/43054585-9f138f7a-8e75-11e8-9863-40e0debc8d14.png)

The scatterplot has rendered as expected - the blue dots over the UK

The hexagons have rendered at coordinates (0, 0) (you can see a small blue dot at location (0, 0) off the central-east coast of Africa at the bottom of the image), and I don't know why.

If it helps, this is the log of the hexagon and scatterplot layers

![screen shot 2018-07-23 at 12 50 11 pm](https://user-images.githubusercontent.com/18344164/43054873-fc73a7bc-8e76-11e8-82fd-d42a1841173c.png)

#### Code Example 

The two functions I'm using to create the hexagon and scatterplots are:

```
const hexagonLayer = new deck.HexagonLayer({
  id: 'hexagon'
  data,
  pickable: true,
  extruded: true,
  elevationRange: [0, 1000],
  elevationScale: 250,
  opacity: 1,
  getPosition: d => [d.lng, d.lat]
});
```

```
const scatterLayer = new deck.ScatterplotLayer({
  id: 'scatterplot',
  data,
  radiusScale: 1,
  radiusMinPixels: 1,
  getRadius: d => d.radius,
  getPosition: d => [d.lng, d.lat],
  getColor: d => hexToRgb( d.fill_colour )
});
```

Both functions are using the same `getPosition: d => [d.lng, d.lat]` function, and receive the same data object.  

#### Background / extra detail

I'm an R programmer, not a javascript programmer, so I may have missed something obvious. 

I'm making an `R` package [(github repo here)](https://github.com/SymbolixAU/mapdeck) which wraps `deck.gl`. Therefore my js functions are slightly different to the examples, as I have to receive the data from R.

The [hexagon.js is here](https://github.com/SymbolixAU/mapdeck/blob/hexagon/inst/htmlwidgets/lib/hexagon/hexagon.js)

The [scatterplot.js is here](https://github.com/SymbolixAU/mapdeck/blob/hexagon/inst/htmlwidgets/lib/scatterplot/scatterplot.js)

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
@SymbolixAU 
You are not providing getColor prop for hexagon layers, so the blue-dot you are seeing could be part of ScatterplotLayaer.
Couple of suggestions, 1. Can you increase `elevationScale` to see if it gets rendered. 2. Do not render scatterplot and see if anything rendered for hexagon. But otherwise your props seems to be fine and anything you are not set should use default values. 
Also keep an eye on console to see if there are any errors.

**Comment by SymbolixAU** [comment]
@1chandu 
is there a [`getColor`](https://github.com/uber/deck.gl/blob/master/docs/layers/hexagon-layer.md) prop? the`getColorValue` says it's optional too. 

Looking closer, the 'blue dot' is actually a 'scatter' dot on top of a yellow hexagon.

If I remove the scatter layer you can see the hexagon at (0, 0)

The small yellow 'dot' in the center
![screen shot 2018-07-26 at 9 06 11 am](https://user-images.githubusercontent.com/18344164/43232251-53b46640-90b3-11e8-8921-d468328fa913.png)

zooming in:
![screen shot 2018-07-26 at 9 06 21 am](https://user-images.githubusercontent.com/18344164/43232256-55aafaae-90b3-11e8-9435-1a449c797932.png)

The console is not showing any warnings or errors
![screen shot 2018-07-26 at 9 06 37 am](https://user-images.githubusercontent.com/18344164/43232262-5c8fff90-90b3-11e8-9c81-b571be46fa64.png)

**Comment by SymbolixAU** [comment]
Not an error per-se, but of interest is the `centroid` is set to [0,0]

![screen shot 2018-07-27 at 12 02 02 pm](https://user-images.githubusercontent.com/18344164/43297494-0500b480-9195-11e8-85b2-fe4a767bea20.png)

**Comment by SymbolixAU** [comment]
And for what it's worth, I can get all the [other layers](https://github.com/SymbolixAU/mapdeck/tree/master/inst/htmlwidgets/lib) rendered without issue

**Comment by SymbolixAU** [comment]
How are the centroids calculated, does this perhaps require a d3 library installed?

**Comment by oller** [comment]
I'm encountering the same issue with the hexagon layer, a `hexagons` array of length 1 at `[0,0]` with all the items nested in the points array (as shown in the bottom screenshot of the console)

For me it seems an issue with the initial load state, once I manipulate the data and call my render method again, it seems to work, with the correct colors / elevations etc. so none of that is a problem, it seem an issue with the initial load.

There are no reported errors from deck.gl in the console

I'm using this in a Pure JS context.

Did you find a workaround @SymbolixAU ?

**Comment by SymbolixAU** [comment]
@oller no I haven't found a solution yet.

**Comment by 1chandu** [comment]
@SymbolixAU @oller , I was able to reproduce this on my end. The problem is , when the first time hexbins are generated the viewport is not properly set yet, resulting in wrong projections. As a temporary work around if you update `radius`, which re-triggers the hex-bin aggregation, everything renders fine, I am looking into this.

**Comment by 1chandu** [comment]
Ok, found it, unlike other aggregation layers (Grid and ScreenGrid), HexagonLayer, aggregation depends on `viewport`, so when `viewport` is changed, we need to re-trigger the aggregation. PR coming up ...

**Comment by SymbolixAU** [comment]
An update from my tests

versions: v6.1.0 and v6.1.1 of deckgl.min.js

- Hexagons are still not rendered on the map
- The console is showing hexagon data (and a hexagon-layer object) with centroids

![screen shot 2018-09-26 at 3 50 29 pm](https://user-images.githubusercontent.com/18344164/46059744-f2ac2c80-c1a3-11e8-8fab-ee15f2f55590.png)

**Comment by oller** [comment]
Likewise, having followed this issue's progress and noted it was added into the `6.1.1` milestone, I can confirm this still isn't resolved in `6.1.1` version in my scenario either.

**Comment by oller** [comment]
Any update on this @1chandu? It'd be a shame to see all that work you put in not make a release.  Thanks again!

**Comment by SymbolixAU** [comment]
Same issue in v6.2.0 of deckgl.min.js

**Comment by Pessimistress** [comment]
@1chandu is this related to https://github.com/uber/deck.gl/issues/2215?

**Comment by 1chandu** [comment]
Closing this, remaining work is tracked in #2215

**Comment by oller** [comment]
Wahey! Works for me in `6.2.1`! 

Thanks again for all your efforts with this lib!

**Comment by SymbolixAU** [comment]
Awesome! 6.2.1 is now my new favourite number.

![hexagons](https://user-images.githubusercontent.com/18344164/47460281-d0044680-d829-11e8-8381-7d0c43514bcb.gif)

Thanks @Pessimistress @1chandu and the rest of the Deck.gl team
