### ISSUE TITLE
Question: Ability to update viewState to a bounding box?

### ISSUE THREAD

**Issue by oller** [uber/deck.gl#2114]
I've seen your examples to update a viewState to center on a certain lat/long.  I was wondering if there was a way to have the map and accompanying datalayers zoom to a bounding box of 2 lat/long values, as this would account for the zoom too.

I can see a `fitBounds()` method in the code, but no real documentation regarding it.

Many thanks!

**Comment by ibgreen** [comment]
In the past we have typically used the `fitBounds()` function directly from the [viewport-mercator-project](http://uber-common.github.io/viewport-mercator-project/#/documentation/api-reference/web-mercator-utils) module.

As a first step, take a look and see if it does what you need.

(That said, I do agree that it could be nice to have this functionality more tightly integrated into deck.gl.)

**Comment by oller** [comment]
Sorry, I never updated this thread.  The `fitbounds()` method did the trick, thank you for pointing me in the direction of it.
