### ISSUE TITLE
Upgrade Guide Improvements

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2119]
#### Background 
- Deck.gl upgrade guide should mention luma.gl as a major breaking change there affects many deck.gl applications.
#### To Do List 
  - [x] Doc update
  - [x] Whats new update

**Comment by ibgreen** [comment]
@jianhuang01 @1chandu  Needs to be cherry picked into 6.0.x and website needs to be updated.

**Comment by 1chandu** [comment]
Cherry-picked into 6.0.-release, website also updated.
