### ISSUE TITLE
GridLayer: Centroid of grid cells

### ISSUE THREAD

**Issue by wireman27** [uber/deck.gl#2150]
Could someone please help out with how grid cells are created for points in a GridLayer?

#### Actual Result

![screen shot 2018-08-02 at 10 09 20 am](https://user-images.githubusercontent.com/20759715/43562998-93a1d5a0-963d-11e8-93be-e82f5e0e9a2d.png)

#### Expected Result

The centroid of the point represented by the ScatterplotLayer to be at the center of the GridLayer

#### Reproduce Steps

This is a data sample:

```javascript
[{"s": 29, "g": 139680240.1, "c": [74.9632, 15.5026]}, 
{"s": 29, "g": 89340141.67, "c": [74.9832, 15.5026]}, 
{"s": 29, "g": 141077543.9, "c": [75.0732, 15.502]}]
```

#### Code Example 

```javascript
layers: [
        new GridLayer({
          id: 'grid-layer',
          data: gdpData,
          pickable: true,
          extruded: false,
          autoHighlight: true,
          cellSize: 500,
          getPosition: d => d.c,
          getColorValue: function(points) {
            return(points[points.length-1]["g"])
          },
          colorRange: [[255,255,178],[254,217,118],[254,178,76],[253,141,60],[240,59,32],[189,0,38]]
        }),
        new ScatterplotLayer({
          id: 'scatter-layer',
          data: gdpData,
          getPosition: d => d.c,
          getRadius: 25
        })
        ]
```

**Comment by 1chandu** [comment]
@wireman27 , in GridLayer, cell boundaries are always aligned to cellSize. provided cellSize is first converted from meters to lng/lat offset, this calculation varies based on whether your data is close to equator or away from equator.

In the above example, you are rendering 3 instances of scatter plot, but the image shows only one. Few thing you can try, reduce the cellSize in GridLayer, so only the cell with data sample is colored and other not.

**Comment by wireman27** [comment]
@1chandu  , I'm using the scatterplot layer here to only demonstrate what the coordinates of the point are. Assuming I only have one point in my dataset, shouldn't it lie at the center of the grid cell?

Ultimately, I am trying to produce something like the extrusions in wireman27.github.io/india_gdp_new using a GridLayer. Each point would be at the center of 1km sq GridLayer cell and I can then extrude instead of using a much bulkier GeoJsonLayer for the same purpose.

**Comment by ibgreen** [comment]
@wireman27 As @1chandu says, the `GridLayer` aggregates points into an "invisible grid" that is overlaid on the points. The alignment of the grid is defined by cell size, not by the points.

The `GridLayer` is an aggregating layer built on top of the `GridCellLayer` - the latter does not aggregate data and instead allows applications precise control over each grid cell (they can even overlap).

Maybe that is an option for you?

**Comment by wireman27** [comment]
@ibgreen That absolutely sounds like what I need. Thanks so much!
