### ISSUE TITLE
RFC: Property Animation

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2152]
[RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/property-animation-rfc.md)

#### Background 

luma.gl can now accept function valued props that get reevaluated agains a set of `animationProps` before every frame. 

- Streamline deck.gl so that layers (and shadermodules) can accept function valued props.
- Forward the right set of `animationProps` into the layers.
- Add a system that enables animation to happen every frame even if layers haven't changed.
- P2 - enable the user to set FPS update frequency, to prevent fans from running hot.

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [ ] Whats new update 
  - [ ] Test

> GIF framerate is lower than actual rendering

![animated-hexagon](https://user-images.githubusercontent.com/7025232/43688207-998165ea-9899-11e8-9a5d-f22f8dca0d53.gif)

![animated-scatterplot](https://user-images.githubusercontent.com/7025232/43688208-9c0d817c-9899-11e8-8e1e-9f489aa3c868.gif)

**Comment by 1chandu** [comment]
Implemented in 6.2
