### ISSUE TITLE
Bitmap layer Size and Rasters

### ISSUE THREAD

**Issue by coenvalk** [uber/deck.gl#2165]
#### Background
Right now, it seems like there is no intuitive way to set the size of each individual image in the bitmap layer. Furthermore, this limits the aspect ratio of all images to be square. Would like to see a way to change size and aspect ratio of individual bitmaps.

Ideally, I would also like to see the support for geotagged rasters to be automatically visualized over a StaticMap layer.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by 1chandu** [comment]
CC: @xintongxia 

Please note `BitMapLayer` is still in experimental state.

Where did you see the size restriction for individual images? In [loadMapImagesToTextures](https://github.com/uber/deck.gl/blob/c30ba5b3ad200e667bb51a2a6f8e4f710ec6775d/modules/experimental-layers/src/bitmap-layer/bitmap-layer.js#L126), the size of texture is set to what ever the size of the provided image.
