### ISSUE TITLE
Polygons without walls, or paths with elevation

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2178]
### Request

Can the `PathLayer` get an elevation property, or can the `PolygonLayer` get a `remove_walls` (or similar) property?

### Example

Both these screenshots are showing the same data in a `PolygonLayer`, but one is in a WebGL-2 enabled browser and one is not. 

![webgl2_enabled](https://user-images.githubusercontent.com/18344164/43874459-5ce3c91e-9bcf-11e8-9c6f-5e1e293be9f6.png)

![webgl2_not_enabled](https://user-images.githubusercontent.com/18344164/43874471-66912c36-9bcf-11e8-889a-70ca1475db3d.png)

I like the second plot without the 'walls' which comes from a side-effect of not having WebGL2 support in the browser. This effectively looks like an elevated 'path'. 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
> Both these screenshots are showing the same data in a PolygonLayer, but one is in a WebGL-2 enabled browser and one is not.

Well, this should work on both browsers. It is likely related to a bug in luma.gl v6.0 that we are currently working on. But that bug fix will remove the effect you are after, not enable it.

> Can the PathLayer get an elevation property, or can the PolygonLayer get a remove_walls (or similar) property?

The `PathLayer` is quite complex and I seem to recall that it doesn't naturally extend to 3D, however removing the walls on a `PolygonLayer` seems like a simple and reasonable ask. 

Right now we I believe the polygon shader only uses `getElevation` value if the `PolygonLayer` is marked as `extruded`. We could instead always use `getElevation`, but only show the walls if `extruded: true`. (And to get the old behavior, there is already the `elevationScale` prop that the user could set to `0` to defeat elevations.)

But these changes would of course risk breaking existing apps. Maybe add a prop `useElevation: false` and make the new behavior conditional on that, until next major release?

@Pessimistress @1chandu

**Comment by SymbolixAU** [comment]
@ibgreen thanks for looking into it. Would you also consider something like a SurfaceLayer?

I realise I've been requesting a few things lately; if there's anything you'd like me to do to help just shout. My [r library](https://github.com/SymbolixAU/mapdeck) has had a lot of positive feedback so I'll be getting more and more involved in this area.

**Comment by ibgreen** [comment]
@SymbolixAU 

> Would you also consider something like a SurfaceLayer?

Maybe you can write up an issue with more clear definition? 

I assume the surface layer in the [Plot example](http://deck.gl/#/examples/custom-layers/3d-surface-explorer) is not what you are looking for

If you want to take a stab at it, we have an `experimental-layers` module where we can accept contributions, while we polish them for inclusion in the main catalog.

Our current [layer roadmap](https://github.com/uber/deck.gl/blob/master/dev-docs/roadmaps/layers-roadmap.md) is here. (Still being updated, but can give you a sense.)

> My r library has had a lot of positive feedback

Looks great! Will think about how we could feature it on the deck.gl website.

**Comment by 1chandu** [comment]
@SymbolixAU

>> Can the PathLayer get an elevation property, or can the PolygonLayer get a remove_walls (or similar) property?


> The PathLayer is quite complex and I seem to recall that it doesn't naturally extend to 3D, however removing the walls on a PolygonLayer seems like a simple and reasonable ask.


The side rendering of the polygon (when `extruded` is set) is controlled by [sideModel](https://github.com/uber/deck.gl/blob/9528109aa3e971b8b48d15c41242480d01825210/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js#L288) in `SolidPolygonLayer`, it should be easy to control this with an layer prop, happy to look at a PR if you can make this change.

**Comment by SymbolixAU** [comment]
@1chandu If you're happy to wait a few weeks I could have a go at it. But I'm not yet a javascript developer, and am spending most of my time getting the R library production ready.

**Comment by SymbolixAU** [comment]
Given [this PR (Polygon Documentation)](https://github.com/uber/deck.gl/pull/2462), I think this issue can also be closed as I can achieve my aim by supplying the `Z` component of the coordinates. 

![elevated_roads](https://user-images.githubusercontent.com/18344164/49323336-c29b5400-f56d-11e8-9a9e-cb1d045df446.gif)
