### ISSUE TITLE
IconLayer - showing markers on the map

### ISSUE THREAD

**Issue by israelidanny** [uber/deck.gl#218]
Is there any way to display markers in any way or form?

**Comment by gnavvy** [comment]
Hi @israelidanny, we do have an icon/symbol layer but it is not ready for graduation yet.

**Comment by ibgreen** [comment]
In the mean time it is possible to use SVG Overlays from react-map-gl.

**Comment by ibgreen** [comment]
Merged to dev, will be part of next release

**Comment by wupinlang** [comment]
@ibgreen Haven't seen it from docs,Can i use this feature now?

**Comment by ibgreen** [comment]
> Haven't seen it from docs,Can i use this feature now?

@wupinlang Yes, please check out the "layer catalog" in the docs, it includes the [IconLayer docs](https://uber.github.io/deck.gl/#/documentation/layer-catalog/icon-layer).

**Comment by wupinlang** [comment]
@ibgreen thx!
