### ISSUE TITLE
Trip Routes Performance Issues

### ISSUE THREAD

**Issue by JamesSingleton** [uber/deck.gl#2186]
I have a question after working with the Trip Routes example. I took a look at the sample data and this is what it looks like

```
{
  "vendor": 0,
  "segments": [
    [-74.20986, 40.81773, 1191],
    [-74.20987, 40.81765, 1193.803],
    [-74.20998, 40.81746, 1205.321],
    [-74.21062, 40.81682, 1249.883],
    [-74.21002, 40.81644, 1277.923],
    [-74.21084, 40.81536, 1333.850],
    [-74.21142, 40.8146, 1373.257],
    [-74.20965, 40.81354, 1451.769],
    [-74.21166, 40.81158, 1527.939],
    [-74.21247, 40.81073, 1560.114],
    [-74.21294, 40.81019, 1579.966],
    [-74.21302, 40.81009, 1583.555],
    [-74.21055, 40.80768, 1660.904],
    [-74.20995, 40.80714, 1678.797],
    [-74.20674, 40.80398, 1779.882],
    [-74.20659, 40.80382, 1784.858],
    [-74.20634, 40.80352, 1793.853],
    [-74.20466, 40.80157, 1868.948]
  ]
}
```

However, my data set is much bigger than that for the segments. Here is an example:
https://gist.github.com/JamesSingleton/dc856db646535fa1ce9c5be6ab3a2fc7

The code base I am working on is here https://github.com/JamesSingleton/route-visualization

With the Gist above, I can have above 500+ of these. However, it seems like the Trip Routes code takes a significant performance hit with my data vs the data in the example. Is there a reason for that? Its seems as if the example is running the routes immediately, but mine take about a minute or so to show up and they are all drawn at once instead of like they are driving like the example.

**Comment by Pessimistress** [comment]
Looking at your data sample, your timestamps do not seem to be in ascending order. They are also super close together (within a few seconds range) while your `trailLength` is set to `180`, which means everything is always drawn at all times - and causing the perf issue.

**Comment by JamesSingleton** [comment]
So originally I didn't want to use time stamps, I wanted to use speed instead but the README states that it should be a timestamp. In an ideal scenario I was going to change the color of the line depending on the distribution of speed. The reason why the timestamps seem to not be in ascending order as well as super close is because I was adding the value of the speed to the start time since I only have a start and end time as well as a lat long coordinate coupled with a speed taken at once a second for the duration of the trip.

It looks like I might not be able to use this as a speed distribution? So the slower the speed the closer to red the line gets.

**Comment by JamesSingleton** [comment]
Could I potentially use a number that is between say 0-120 instead of a number in the 4 digits?

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)
