### ISSUE TITLE
onHover callback does not give back x&y

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/deck.gl#219]
<img width="488" alt="screen shot 2016-11-14 at 3 31 17 pm" src="https://cloud.githubusercontent.com/assets/6854312/20287155/b6a82dde-aa7f-11e6-936e-3e4dd00a2cea.png">

In the call onHover callback from scatterplot and arc layer, it used to be that x & y would return not undefined values. However in v3 it looks like the come back undefined pretty homogenously

**Comment by gnavvy** [comment]
fixed in v3.0.6
