### ISSUE TITLE
[Bug] hexagonLayer Render 

### ISSUE THREAD

**Issue by Franches** [uber/deck.gl#2198]
I am trying to render a HexagonLayer with:

      const {upperPercentile = 100, coverage = 1} = this.props;

      var {data = HEXDATA} = this.props;

      return new HexagonLayer({
            id: 'hexagon-layer',
            pickable: false,
            extruded: true,
            radius: 5,
            elevationScale: 0.2,
            getPosition: d => d,
            onHover: null,
            ightSettings: LIGHT_SETTINGS,
            colorRange,
            coverage,
            data: data,
            opacity: 1,
            upperPercentile
          })
       // ...
      <DeckGL
          layers={layers}
          viewState={viewState}
          controller={MapController} onViewStateChange={this._onViewStateChange}
      >
          <StaticMap
              reuseMaps
              preventStyleDiffing={true}
              mapboxApiAccessToken={MAPBOX_TOKEN}
              mapStyle="mapbox://styles/mapbox/dark-v9"
          />
      </DeckGL>

However, this would not render anything. I found that adding this line would make a layer rendered:

      var {data = HEXDATA} = this.props;
      data = data.slice()
      return new HexagonLayer({

However, the appearance of hexagonLayer (i.e. the height, color, distribution of all bars) would dramatically change on onViewStateChange events. I am pretty sure that the data passed to new HexagonLayer() func never change.

Any ideas are much appreciated!

**Comment by oller** [comment]
This looks like a duplicate of https://github.com/uber/deck.gl/issues/2111, to do with a bug related to the initial drawing of the hexagon layer.  I believe this is being addressed in https://github.com/uber/deck.gl/pull/2196 so keep an eye on that!

**Comment by Franches** [comment]
thanks very much. it is indeed the same issue :)
Also i think it is also very useful for NOT re-aggregating and updating hexbins when viewport is changed, otherwise the hex layers will look "shaking".

**Comment by 1chandu** [comment]
@Franches , yep aggregation only happens once, no re-aggregation on viewport change.
