### ISSUE TITLE
preserveDrawingBuffer is not passed through when creating context

### ISSUE THREAD

**Issue by alee8** [uber/deck.gl#2200]
#### Actual Result

`preserveDrawingBuffer` is not passed through as an option, preventing screen shots of the canvas.

#### Expected Result

Passed in options should be passed through.

This should also be back-ported to version 5 because that's what I'm using.

#### Reproduce Steps

Call `Deck._createAnimationLoop`. Have something call `onCreateContext` on the returned object (of class `AnimationLoop`). The parameter `opts` is dropped on the floor.

https://github.com/uber/deck.gl/blob/b40a9ed36b9e9b06b95375c2c72041a954ddc6b4/modules/core/src/lib/deck.js#L373
```
      onCreateContext: opts =>
        gl || createGLContext(Object.assign({}, glOptions, {canvas: this.canvas, debug})),
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Thanks for the PR, looks good. Are you setting like this?

```
<DeckGL glOptions={{preserveDrawingBuffer: true}}/>
```
