### ISSUE TITLE
attributes are being re-calculated when prop changes instead of only when data changes

### ISSUE THREAD

**Issue by abmai** [uber/deck.gl#221]

**Comment by abmai** [comment]
seems like `dataChanged` is set to `true` on `initializeState()` and then never gets set back to `false` after

**Comment by abmai** [comment]
problem seems to be here: https://github.com/uber/deck.gl/blob/master/src/lib/layer.js#L391

`setState` is only called if `willReceiveProps` is defined

**Comment by shaojingli** [comment]
#222

**Comment by gnavvy** [comment]
fixed in v3.0.5
