### ISSUE TITLE
Probe.gl adds a high number of transitive dependencies

### ISSUE THREAD

**Issue by carlostxm** [uber/deck.gl#2241]
Resolution Summary

- [ ] Update probe.gl dependency to >= 2.0.0-beta.1

--- 

Hi,

I don't know if I should open this issue in deck.gl or in probe.gl. Please let me know if I should move it.

I am using deck.gl in one project and I have detected that one of the dependencies of @deck.gl/core and luma.gl, [probe.gl](https://github.com/uber-web/probe.gl), is adding +90 transitive dependencies. These dependendencies are added by its only direct dependency [asciify-image](https://github.com/ajay-gandhi/asciify-image) which allows to convert an image to ascii. 

That means that most deck.gl dependencies are added to give support a feature of the logger that actually is not being used, I think this could be improved.

Please, let discuss about how this problem could be improved.

Thank you,

Carlos.

**Comment by ibgreen** [comment]
@carlostxm 

Thanks for reporting! 

If it helps, the dependencies are only loaded at runtime when running deck.gl under node.js. `asciify-image` is not bundled into your application, e.g if you are bundling using webpack.

But I agree, 90 dependencies sounds excessive. If you open an issue on probe.gl (can be minimal, just link to this issue) I can look into making the `asciify-image` dependency conditional (i.e. not depend on it and only load it at runtime if the user has manually installed it himself).

Also would be great if you opened a PR directly on `asciify-image`. The maintainers have been responsive in the past.

**Comment by ibgreen** [comment]
New probe.gl version published, we should bump in next deck.gl beta release.

**Comment by carlostxm** [comment]
Thanks @ibgreen!
