### ISSUE TITLE
layer control

### ISSUE THREAD

**Issue by 3dgiser** [uber/deck.gl#2245]
I did not use react in my project。Just javaScript code.
Now，I want to hide or show one layer in one canvas in page，
It seem that map.addLayer(layer)、map.removeLayer in arcgis or leaflet

**Comment by ibgreen** [comment]
You should use `deck.setProps({layers: ...})` with your new list of layers. You can either omit the layer in the new layer list, or set its `visible` property to `false` (can be more efficient if the layer is showing a lot of data and you are frequently turning it on and off).

Here is an article in the new [FAQ]( https://github.com/uber/deck.gl/blob/master/docs/faq.md#should-i-really-regenerate-all-layers-everything-something-changes) that may be helpful.

The FAQ will be part of the deck.gl website once we publish 6.1.

**Comment by 3dgiser** [comment]
Ok,I found the that method yesterday.but how do I change the value of visible ?

**Comment by ibgreen** [comment]
You can't change a layer. You create a new Layer with the same id, but with the prop changed.

```
deck.setProps({layers: [
  new ScatterplotLayer({
    id: 'same-id-as-last-time',
    ...
  }),
  ...
]});

Layer instances are only "descriptors" describing what deck.gl should render, not actual objects you manipulate.
