### ISSUE TITLE
render-test script not reporting failures

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2246]
#### Actual Result
rend-test script reports all test cases passed even though a sub test is failed.
#### Expected Result
render-test scritpt should fail.
#### Reproduce Steps
Run render-test on master

<img width="1381" alt="screen shot 2018-08-29 at 1 09 54 pm" src="https://user-images.githubusercontent.com/9502731/44813018-93033700-ab8d-11e8-9127-0f7efebf02c3.png">

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by jianhuang01** [comment]
fixed in master after double check
