### ISSUE TITLE
React examples don't seem to work properly

### ISSUE THREAD

**Issue by kennetpostigo** [uber/deck.gl#2249]
I was trying out some of the deck.gl React examples and they seem to throw errors from the `controller` prop. Here is a codesandbox reproducing this:

[![Edit o4j0jlnz2y](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o4j0jlnz2y)

**Comment by kennetpostigo** [comment]
Hey yall, I also noticed that the `render callback` section doesn't seem to work either on this page
- http://deck.gl/#/documentation/deckgl-api-reference/react/deckgl?section=children

**Comment by XiaokaiUber** [comment]
You are using an old version of deck.gl. Please update it to 6.1.0 and try again.

**Comment by ibgreen** [comment]
@kennethpostigo 

I went to your sandbox, upgraded to deck.gl 6.1.0 and made some changes to your JS:

```
import React from "react";
import ReactDOM from "react-dom";
import DeckGL, { ScatterplotLayer } from "deck.gl";
import { StaticMap } from "react-map-gl";

const App = data => (
  <DeckGL
    initialViewState={{ longitude: -122.45, latitude: 37.78, zoom: 12 }}
    controller={true}
    layers={[
      new ScatterplotLayer({
        data: [{ position: [-122.45, 37.78] }],
        radiusScale: 100,
        getColor: [255, 0, 0, 255]
      })
    ]}
  >
    <StaticMap
      mapStyle="mapbox://styles/mapbox/dark-v9"
      mapboxApiAccessToken="__YOUR_TOKEN__"
    />
  </DeckGL>
);
```

Now it works for me (scatterplot layer is showing one red dot in middle of screen).

**Comment by layik** [comment]
Hope someone can have a look at this, the controller is NOT appearing in this slightly modified version of @ibgreen's code
```{js}
import React from "react";
import DeckGL, { ScatterplotLayer } from "deck.gl";
import { StaticMap } from "react-map-gl";

export default class App extends React.Component{
    render() {
        return(
            <DeckGL
            initialViewState={{ longitude: -122.45, latitude: 37.78, zoom: 12 }}
            controller={true}
            layers={[
              new ScatterplotLayer({
                data: [{ position: [-122.45, 37.78] }],
                radiusScale: 100,
                getColor: [255, 0, 0, 255]
              })
            ]}
          >
            <StaticMap
              mapStyle="mapbox://styles/mapbox/dark-v9"
              mapboxApiAccessToken="__YOUR_TOKEN__" //added my own key for screenshot below
            />
          </DeckGL>
        )
    }
}
```
![image](https://user-images.githubusercontent.com/408568/47565461-6b77e300-d920-11e8-8e52-51a494cfa995.png)

**Comment by layik** [comment]
Forgot to say https://stackoverflow.com/q/53008068/2332101

**Comment by XiaokaiUber** [comment]
@layik Could you please clarify "the controller is NOT appearing"? Are you able to see the layers and perform mouse/keyboard interaction?

Controller allows you to handle events such as panning, rotating, zooming with your keyboard, mouse and trackpad. If you set controller = {false}, those events will be disabled.

**Comment by 1chandu** [comment]
`controller` prop doc here: http://deck.gl/#/documentation/deckgl-api-reference/react/deckgl?section=view-state-properties

**Comment by layik** [comment]
@XiaokaiUber seems I have confused at least two of you. My apologies. As stated above, I thought setting that prop to "true" would show the zoom/rotate control buttons on the DeckGL component view.

![image](https://user-images.githubusercontent.com/408568/47644329-bd5d7a80-db65-11e8-9fe7-45f4f4579caa.png)
