### ISSUE TITLE
Layers not rendering when navigating back to page with Map

### ISSUE THREAD

**Issue by dekkofilms** [uber/deck.gl#2250]
We have a page with a map that is displaying a polygon as a GeoJSONLayer. When I click on a link to another page and then click back, the polygon is no longer rendering.

Looking in the React tools of the DeckGL wrapper it shows that the layer is there, but it's just not rendering on the map itself. The lifecycle message is what I'm curious about, it seems to have successfully resolved to something stating: `lifecycle:
"Matched. State transferred from previous layer"`

Here is the full image below:

<img width="1173" alt="screen shot 2018-08-30 at 3 56 53 pm" src="https://user-images.githubusercontent.com/14862852/44879101-53f8e280-ac6e-11e8-8ccb-6391db2fca9d.png">

I have found one weird use case where everything slightly works as expected. If I navigate to a new page (from the map) and refresh before navigating back to the map page ... it renders the polygon. A little stuck on what is actually causing the problem here though. Any advice/suggestions would be much appreciated. 

Here is the error showing up in the console:

```
deck: error while initializing GeoJsonLayer({id: 'geojson'})
 Error: deck.gl: assertion failed.
    at assert (assert.js:6)
    at GeoJsonLayer._initState (layer.js:1012)
    at GeoJsonLayer._initialize (layer.js:651)
    at LayerManager._initializeLayer (layer-manager.js:640)
    at LayerManager._updateSublayersRecursively (layer-manager.js:571)
    at LayerManager._updateLayers (layer-manager.js:525)
    at LayerManager.setLayers (layer-manager.js:257)
    at LayerManager.setProps (layer-manager.js:191)
    at Deck.setProps (deck.js:219)
    at Deck._setGLContext (deck.js:591)
```

We are using NextJS for SSR, and could this possibly be happening due to deck.gl not mounting in the order we assume.

**Comment by ibgreen** [comment]
@dekkofilms 

Looking into the deck.gl source code, the only assert in Layer._initState is

```
    assert(!this.internalState && !this.state);
```

This means that deck.gl is trying to initialize an already initialized layer. That indicates that something is going quite wrong, but hard to speculate what. 

I would have assumed some other error would have happened before this, to make things get this badly out of whack...

Have not seen this before, and yes could possibly be related to the SSR framework.

**Comment by dekkofilms** [comment]
@ibgreen yeah, that's correct. I threw a `Math.random()` as a part of the key to see the layer. I mean I feel it should be the same since it hasn't changed, which seems appropriate and the reason I'm seeing `"Matched. State transferred from previous layer"`

Initial Mount:

<img width="342" alt="screen shot 2018-08-30 at 6 30 19 pm" src="https://user-images.githubusercontent.com/14862852/44884769-f58a2f00-ac82-11e8-83be-ad58f6df5801.png">

Then returning to the page:

<img width="343" alt="screen shot 2018-08-30 at 6 30 31 pm" src="https://user-images.githubusercontent.com/14862852/44884783-fde26a00-ac82-11e8-9db6-6f59dc3e232b.png">

It is weird that I'm seeing more layers for navigating back than the initial mount of the page.

**Comment by dekkofilms** [comment]
@ibgreen Sorry to keep pinging you ... after being able to dive deeper into this issue, I have some more helpful information on the related problem.

So this happens mainly on route changes and navigating back to our map. In our map container, we are memoizing the lastResult found, which is a GeoJsonLayer:

```
  return new GeoJsonLayer({
    id: `geojson-${type}-${ID}`,
    data,
    opacity: 1,
    stroked: true,
    filled: true,
    wireframe: false,
    lineWidthScale: 5,
    lineWidthMaxPixels: 10,
    lineWidthMinPixels: 1.5,
    getFillColor: [183, 49, 44, 40],
    getLineColor: [183, 49, 44, 255],
    getLineWidth: 1.5,
  });
```

It seems to collide with the previous GeoJsonLayer when coming back to the map since those `id`s haven't changed, would that be correct?

I tested this more, by taking out some logic in our memoize handler, and instead of creating an id with `geojson-type-id`, I'm creating an id with `geojson-timestamp`, and it seems to be working well again.

Ultimately, I still like we should be able to use the last stored GeoJsonLayer, and not be forced to generate new ones each time.

**Comment by ibgreen** [comment]
If you clone the deck.gl repo there is a benchmark suite. `npm run bench-browser`

Gives me the following values:


<img width="384" alt="screen shot 2018-09-12 at 3 00 33 pm" src="https://user-images.githubusercontent.com/7025232/45455764-0aac8800-b69d-11e8-8e84-804a5cc2c71d.png">

I.e. my Macbook can create approximately 500K layer instances per second. So it is unlikely to be a bottleneck in your app, and one could argue that you are complicating your code quite a bit to save performance where it likely doesn't matter.

That said, you should be able to again submit an existing layer instance in a new layers array (as long as it hasn't been modified), it should match the layer with the same id, and if those are the same layer instance, no change should be made.

**Comment by dekkofilms** [comment]
Sure, I totally understand where you are coming from, and I really appreciate your response ... this has been helpful! Memoization in this use case was not used as an optimization for DeckGL layers ... it just (at the time) made the most sense to go ahead and store that computation with everything else being memoized already.
