### ISSUE TITLE
Add messages for Transform Feedback examples when running under WebGL1

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2252]
# For #2235 

#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding

**Comment by 1chandu** [comment]
We update the title to have WebGL2, but we should update demos so message is displayed so it is less confusing.

**Comment by 1chandu** [comment]
This should be luma.gl issue, opened https://github.com/uber/luma.gl/issues/743 
closing this one.
