### ISSUE TITLE
DeckGL controller prop does not accept boolean

### ISSUE THREAD

**Issue by FranciscoGileno** [uber/deck.gl#2259]
Hi, I installed the v6.0.3, and I tried to follow the docs with this example:
```jsx
<DeckGL
  initialViewState={initialViewState}
  controller={true}
  layers={layers}
>

```

And it throws an warning:
```
index.js:2178 Warning: Failed prop type: Invalid prop `controller` of type `boolean` supplied to `DeckGL`, expected `function`.
    in DeckGL (at App.js:32)
    in App (at index.js:7)
```

```
Uncaught (in promise) TypeError: this.props.onResize is not a function
    at DeckGL._onResize (deckgl.js:159)
    at Deck._updateCanvasSize (deck.js:347)
    at Deck._onRendererInitialized (deck.js:527)
    at animation-loop.js:149
```

Can anyone help me?
Thanks.

**Comment by ibgreen** [comment]
> it throws an warning:

@FranciscoGileno Thanks for reporting! Looking on the `6.0-release` branch the prop type for that prop should be defined [here](https://github.com/uber/deck.gl/blob/6.0-release/modules/core/src/lib/deck.js#L62) and it looks like it should support bool.

Will require some investigation so marking this as a bug. 

In the mean time, it may be worthwhile for you to copy a working example to make sure you don't get blocked.

Also relevant is taht we are actually moving away from the top level `controller` prop, and instead it is possible to specify a controller on each view. That newer syntax could be an alternative.

See the documentation of the `View` `controller` prop [here](http://deck.gl/#/documentation/deckgl-api-reference/views/view?section=constructor)

**Comment by ibgreen** [comment]
@FranciscoGileno  Thanks for confirming!
