### ISSUE TITLE
Control the opacity of each instance in IconLayer

### ISSUE THREAD

**Issue by javidhsueh** [uber/deck.gl#2260]
#### Background

Right now the opacity of IconLayer is to control the uniform opacity of the layer. I'd like to have different opacity for each instance. This is for implementing some highlight interaction. Ex: hover over the icon and change the opacity to 1, and set the opacity of rest of instances to 0.1.

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update

**Comment by ibgreen** [comment]
Have you looked at the `autoHighlight` properties on the layer, they allow you to set a highlight color?

**Comment by javidhsueh** [comment]
That only can set the highlight color for the hovered instance. In my case, the graph visualization, I need to highlight the hovered node and its adjacent nodes. I might need to set the hovered node with opacity=1, adjacent nodes with opacity=0.8, and rest of nodes with opacity=0.1

**Comment by javidhsueh** [comment]
The other way to change the opacity is through getColor with mask=true. Although this method can change the opacity, it will apply the color  defined by the users instead of the pixel color from the image.

**Comment by javidhsueh** [comment]
<img width="905" alt="screen shot 2018-09-13 at 3 25 38 pm" src="https://user-images.githubusercontent.com/3599601/45519342-8542d980-b769-11e8-92df-e1e85d660d8f.png">
<img width="916" alt="screen shot 2018-09-13 at 3 25 34 pm" src="https://user-images.githubusercontent.com/3599601/45519343-8542d980-b769-11e8-88bc-a5d6aff6a281.png">
<img width="742" alt="screen shot 2018-09-13 at 3 25 29 pm" src="https://user-images.githubusercontent.com/3599601/45519344-8542d980-b769-11e8-97a6-4f83585c9467.png">
