### ISSUE TITLE
deck.gl 6.1.0 warnings

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2263]
When testing with kepler.gl with deck.gl `6.1.0-rc.1` on Safari seeing following.

<img width="789" alt="screen shot 2018-09-06 at 4 25 59 pm" src="https://user-images.githubusercontent.com/9502731/45190221-acd9f500-b1f1-11e8-8497-7165088ade9c.png">

  - [X] Add label and assign to milestone
  - [x] SphericalCoordinates import warning
  - [x] On safari we should report WebGL1 , not WebGL2 (NPOT warnings could be related to this)
  - [x] Test

**Comment by ibgreen** [comment]
* Check installed version of math.gl.
* Ensure math.gl@2.1.0 is installed.

**Comment by 1chandu** [comment]
@heshan0131 , please re-open if you see any of these issues in 6.1.0 version.

**Comment by FranciscoGileno** [comment]
Hi. Sorry to open this again.

my `yarn.lock`:

```
"@deck.gl/core@^6.1.0":
  version "6.1.0"
  resolved "https://registry.yarnpkg.com/@deck.gl/core/-/core-6.1.0.tgz#4880254c7beed91a498a7b21f80b8ef98927c732"
  dependencies:
    luma.gl "^6.1.0"
    math.gl "^2.1.0"
    mjolnir.js "^1.0.0"
    probe.gl "^2.0.0-beta"
    seer "^0.2.4"
    viewport-mercator-project "^5.2.0"
```

I am getting warnings on every test I run:

```
    console.log node_modules/@deck.gl/core/dist/es5/lib/init.js:43
      deck: deck.gl 6.1.0 - set deck.log.priority=1 (or higher) to trace attribute updates
    console.info node_modules/luma.gl/dist/es5/webgl-utils/webgl-types.js:32
      luma.gl: loaded under Node.js without headless gl installed, meaning that WebGL contexts can not be created. This may not be an error. For example, this is a typical configuration for isorender applications running on the server.
```

Is there any way to get rid of it?
Thanks.
