### ISSUE TITLE
How To: composite icon in IconLayer

### ISSUE THREAD

**Issue by pr1ntr** [uber/deck.gl#2269]
Is it possible to make an IconLayer that has a dynamic aspect to it. Like I want a marker that is a graphic pin and then a picture from a url to fill some part of it? Does this require a special shader?

**Comment by pr1ntr** [comment]
@ibgreen that was the only thing I was thinking. Is that preferable?

**Comment by pr1ntr** [comment]
I think my only concern is fitting the image (square) into a round container (the mask)

**Comment by ibgreen** [comment]
>  think my only concern is fitting the image (square) into a round container (the mask)

@pr1ntr I imagine that you'd want the second layer (with the round frames) to render over the first layer. You could turn e.g. off depth testing to make sure the second layer renders on top of the first:

```
new IconLayer({
  id: 'pictures'
}),
new IconLayer({
  id: 'frames',
  ...
  parameters: {
    depthTest: false
  }
});
```

**Comment by pr1ntr** [comment]
This all may be moot since the project is about to get killed 🙄
