### ISSUE TITLE
unproject function not returning correct LatLng coordinates

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#228]
to reproduce, add a breakpoint to the pick function for the choropleth layer, switch on the choropleth layer, hover any choropleth and check the LatLng value from the console. 

<img width="424" alt="screen shot 2016-11-21 at 6 41 37 pm" src="https://cloud.githubusercontent.com/assets/144743/20508973/2f09cfb8-b01a-11e6-9e68-dde6424d9226.png">

**Comment by shaojingli** [comment]
This is known for a while. I'll investigate tomorrow

**Comment by gnavvy** [comment]
This has been [fixed](https://github.com/uber-common/viewport-mercator-project/pull/17) in viewport-mercator-project by @heshan0131.
