### ISSUE TITLE
How to render the info.object information while hovering over hexagon layer

### ISSUE THREAD

**Issue by weiluo0001** [uber/deck.gl#2281]
I really like deck.gl. I am following your tutorial: http://vis.academy/#/building-a-geospatial-app/3-more-data-overlays-hexagons. Instead of the default rendering implemented in your example, I would like to render the information from info.object hovering on hexagon layer. I set onHover prop in the hexagon layer: onHover: info => calSum_hover(info) and also implemented calSum_hover(info) function as
function calSum_hover(info){
  var sum = 0;
  // undefined error will NOT be thrown as we check for existence before access
  if(info && info.object && 
    info.object.points &&
    info.object.points.length)
  {
    var infe_info = info.object.points;
    var size = info.object.points.length;

    for(var i=0; i<size; i+=1){
    sum += infe_info[i].infection[0];
  }
  }
  console.log(sum);
  return sum;
}

I also added 
<DeckGL
    ...
    onLayerHover={this._onHover}
/>

When I hovered on the hexagon layer, the new render value of sum can be printed, but did not pop up over map. Which part of codes I need to modify? I guess some code here:

  render() {
    return (
      <div>
        {this.state.hoveredObject &&
          <div style={{
            ...tooltipStyle,
            transform: `translate(${this.state.x}px, ${this.state.y}px)`
          }}>
            <div>{JSON.stringify(this.state.hoveredObject)}</div>
          </div>}
        <LayerControls
          settings={this.state.settings}
          propTypes={HEXAGON_CONTROLS}
          onChange={settings => this._updateLayerSettings(settings)}/>
        <MapGL
          {...this.state.viewport}
          mapStyle={MAPBOX_STYLE}
          onViewportChange={viewport => this._onViewportChange(viewport)}
          mapboxApiAccessToken={MAPBOX_TOKEN}>
          <DeckGLOverlay
            viewport={this.state.viewport}
            data={this.state.points}
            onHover={hover => this._onHover(hover)}
            //onLayerHover={this._onHover}
            {...this.state.settings}
          />
        </MapGL>
      </div>
    );
  }

**Comment by weiluo0001** [comment]
Thanks. I saved the information in the HexaonLayer

this.props.showHexagon ? new HexagonLayer({
        id: 'heatmap',
        colorRange: HEATMAP_COLORS,
        getColorValue: points => calSum(points),
        elevationRange,
        elevationScale: 5,
        extruded: true,
        getPosition: d => d.position,
        lightSettings: LIGHT_SETTINGS,
        getElevationValue: points => calSum(points),
        onHover: info => calSum_hover(info),
        opacity: 1,
        pickable: true,
        ...this.props
      }) : null 

 I am new to this area. Can you provide me an example how to save it and use in the app?

**Comment by 1chandu** [comment]
You can check ArcLayer example for reference : https://github.com/uber/deck.gl/blob/master/examples/website/arc/app.js

Prop set here : https://github.com/uber/deck.gl/blob/5d48b2d053833aae1db5e54874994d54fd9ca3e8/examples/website/arc/app.js#L129

Data saved here : https://github.com/uber/deck.gl/blob/5d48b2d053833aae1db5e54874994d54fd9ca3e8/examples/website/arc/app.js#L67

Data used here :
https://github.com/uber/deck.gl/blob/5d48b2d053833aae1db5e54874994d54fd9ca3e8/examples/website/arc/app.js#L79
