### ISSUE TITLE
ArcLayer getStrokeWidth

### ISSUE THREAD

**Issue by rconjaerts** [uber/deck.gl#2282]
#### Actual Result
When creating a new ArcLayer the getStrokeWidth function doesn't get executed OR the value isn't assigned properly. If I use strokeWidth parameter I can assign a value and the lines are getting thicker, but not based on a function.
#### Expected Result
getStrokeWidth should be able to accept a function and then assign the variable strokeWidth for that case.
#### Reproduce Steps
Very basic ArcLayer as you can see in the code example. Nothing extra is happening, and when I assign the strokeWidth value manually the lines are getting thicker. Try to use a function in the  getStrokeWidth and notice that it doesn't function as it should.
#### Code Example 
As an example just create an array with objects that have to, from coordinates and a variable **amount** that is an integer.
ArcLayer code:

```
new ArcLayer({
        id: 'arc-layer',
        data: this.props.migrationData,
        pickable: true,
        //strokeWidth: test[count],// d => d.amount,
        getStrokeWidth: d =>d.amount,
        getSourcePosition: d => d.from,
        getTargetPosition: d => d.to,
        getSourceColor: d => [128,0,0],
        getTargetColor: d => [195,151,151]
      })
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
@rconjaerts , I am not able to reproduce this issue, by using function for `getStrokeWidth` you should be able to set different stroke width for each arc. I tried both on master and latest release branch, 6.1.0. What version are you using? If you are using older versions can you upgrade to 6.1.0 and try again?

**Comment by rconjaerts** [comment]
Hi @1chandu, apparently when I installed deck.gl through yarn I got version 4.1 (which I did 5 days ago). Now that I forced an upgrade to version 6.1.0 everything seems to work. Thank you for pointing out something as simple as the versioning.
