### ISSUE TITLE
GPUGridAggregator: Add support for min/max/mean operations and multiple weights

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2291]
#### Background 
[RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.x/gpu-aggregation-enhancements.md)
#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] RFC
  - [x] Coding
    - [x] Support for multiple weights
    - [x] Support for Min and Max
    - [x] Support for Mean.
  - [x] Doc update
  - Whats new update => experimental
  - [x] Test (ScreenGridLayer, ContourLayer, GPUGridLayer, and other tests)

**Comment by richardowright** [comment]
Glad to see these changes!

I was looking into adding an index to prior option to grid-cell-layer (i.e. say compare today's taxi pickupsto yesterday's or a year ago). With that, it feels like part of the solution would be to add an index operation to the GPU grid aggregator. First, would there be interest in the index approach. If so, does that feel right approach, and, if so, what's the best way to coordinate work on that?

**Comment by 1chandu** [comment]
Thank you for your interest on this work.

Regarding `index` option to grid-cell-layer : are you planning to show both time-lines at the same time? Or will you be switching using an option.  This layer is designed to be render just the grid-cells, I will suggest to have a new composite layer (similar to GridLayer) if you want more customizations.

And for aggregation part, the proposed API in above RFC already supports this kind of operations, i.e. defining more than one weight and aggregating. When you pass in `weights` data to GPUGridAggregator, one weight will be current time line and another one will be previous. Building these weights should happen outside of the aggregator, could be in above mentioned custom layer and just pass them to the aggregator.

**Comment by richardowright** [comment]
The plan would be to only show a single value, the `index`. To extend the example a bit, I'd want to show the user the areas where taxi pickups are growing vs declining. The `cells` that have the highest growth/index value would be the `maxColor` , and the declining/lowest growth areas would be the `minColor`. 

Now, onto the implementation side, I'm happy to add an option to GridLayer or create a new layer that just extends GridLayer. If I'm looking at just the API side of the component, it would be extending it to accept two data properties (i.e probably adding a dataBase property) and perhaps a property to specify index or % difference (i.e. [a-b]/b vs. a/b). 

When looking at GPUGridAggregator, I can easily see how to get the sum of a and b with this work. I was also thinking of calculating a/b or [a-b]/b with it which I don't see how I'd support. (This is similar to the mean operator which takes a sum and count first and then performs the division.) Is it overkill to do this in GPUGridAggregator and better just in standard cpu operations?

**Comment by 1chandu** [comment]
I see.

The operations you are referring above `index or % difference (i.e. [a-b]/b vs. a/b).` are performed after aggregation, where as `OPERATION` supported by `GPUGridAggregator` refer to how all the weights that fall into same grid-cell are processed. Based on you above input I recommend following approach : 

1. Feed you data to aggregator, where you will have two weights, 1. baseWeight, 2. currentWeight (or any other appropriate name)
2. Use luma.gl's `Transform` [API](https://luma.gl/#/documentation/api-reference/transform-webgl-2) , that takes two textures, 1. baseWeight.aggregationTexture (refers to `a`) and 2. currentWeight.aggregationTexture (refers to b) and using a custom vertex shader (which does either `[a-b]/b` or `a/b` and generates a new texture. This can also be done on CPU doing `getData` on (buffer objects of above weights), this gives you a texture or Array with one value (specifying the growth) for each cell and just generate a new array on CPU then upload data to new Buffer object.
3. Feed this new texture or Buffer to the existing ScreenGridLayer.
