### ISSUE TITLE
Setting touchRotate to true with the Scripting API

### ISSUE THREAD

**Issue by c-p-d** [uber/deck.gl#2295]
I'm using the deck.gl [Scripting API](http://deck.gl/#/documentation/getting-started/using-standalone?section=using-the-scripting-api) to create a scatterplot map. I'd like to change the controller property touchRotate from its default of false to true. I tried the below, but it does seem to work.

```
var map = new deck.DeckGL({
    container: map,
    ...
    controller: {touchRotate: true},
    ...
    mapboxApiAccessToken: '...',
    mapStyle: 'mapbox://styles/mapbox/light-v9',
    layers: [
      new deck.ScatterplotLayer({
        id: 'scans',
        ...
```
I don't find the documentation very clear, how can I set touchRotate to true?

**Comment by ibgreen** [comment]
@c-p-d 

I am not sure this syntax works for the top level controller prop. The alternative syntax is to specify the controller on the view in the DeckGL `views` prop:

```js
  views: [new MapView({controller: {touchRotate: true}))]
```

Worth a try...

**Comment by c-p-d** [comment]
Thanks @ibgreen for the suggestion.

Unfortunately, it didn't do the trick though :(

**Comment by Pessimistress** [comment]
@c-p-d The way you were passing the prop is fine. I tried it with `controller: {dragPan: false}` and it works. Haven't got around to test touch though.

**Comment by Pessimistress** [comment]
Which version of deck.gl are you using?

**Comment by c-p-d** [comment]
@Pessimistress I'm using 6.1.0.

I've tried passing `controller: {touchZoom: false}` and `controller: {dragRotate: false}` and they both work as expected. Just not `touchRotate`..

Will use the `dragRotate` function instead for now.

**Comment by Pessimistress** [comment]
@c-p-d 	I just tried in iOS and `touchRotate` works. Maybe you're expecting a different interaction (this option allows you to rotate bearing using two fingers)?
