### ISSUE TITLE
Overlapping GeoJSON features flickering zIndex conflict

### ISSUE THREAD

**Issue by trevorwhealy** [uber/deck.gl#2298]
#### Actual Result
![overlapping-geojson](https://user-images.githubusercontent.com/14946478/45904256-5fd55180-bda1-11e8-86d3-05f436dfb0a8.gif)

#### Expected Result
Non flickering overlap of filled GeoJSON features in 3D Map.
![nonflickeringoverlap](https://user-images.githubusercontent.com/14946478/45904943-78466b80-bda3-11e8-8152-0b87beb6dea6.gif)

#### Reproduce Steps
Basic DeckGL setup with GeoJsonLayer.

#### Code Example 
```
const layer = new GeoJsonLayer({
    id: 'geojson-layer',
    data,
    pickable: true,
    stroked: true,
    filled: true,
    fp64: true,
    extruded: false,
  });
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@trevorwhealy Looks like you are dealing with z-fighting. There is some information on this in the [deck.gl FAQ](http://deck.gl/#/documentation/overview/frequently-asked-questions?section=layer-pixels-render-randomly-on-top-of-each-other).

Unless you have multiple layers in play, most likely you have multiple features in your GeoJSON data, rendering at the same elevation, which causes the Z-fighting.

**Comment by trevorwhealy** [comment]
@ibgreen yep, you were exactly right - the FAQ had the perfect solution.

The below solved my issue:
```
new GeoJsonLayer({
    id: 'loaded-geojson-layer',
    data,
    ****************
    parameters: {
      depthTest: false,
    },
   ****************
    ...
```

Thank you!
