### ISSUE TITLE
PathLayer cannot draw vertical lines

### ISSUE THREAD

**Issue by fanwashere** [uber/deck.gl#2302]
#### Actual Result
When drawing a path using PathLayer between (0, 0, 0) and (0, 0, 1000), no line appears.
#### Expected Result
When drawing a path using PathLayer between (0, 0, 0) and (0, 0, 1000), there should be a 1000 meters long vertical line.
#### Reproduce Steps
Create a PathLayer and add a path between two points which have the same longitude and latitude, but different altitude. However, adding a very small offset (e.g. 0.000001) to longitude and/or latitude of either points in the path will cause the path to be rendered.
#### Code Example
```
const pathLayer = new PathLayer({
  data: [
    {
      path: [[0, 0, 0], [0, 0, 1000]],
      width: 10,
      color: [255, 255, 255],
    },
  ],
  getColor: d => d.color,
  rounded: true,
  widthScale: 1,
  widthMinPixels: 2,
})
```
#### Suspected Cause
In the shader for PathLayer, there is a check for scalar distance between the two points which make up the path. However, [this calculation only takes 2 dimensions into account (x and y)](https://github.com/uber/deck.gl/blob/master/modules/layers/src/path-layer/path-layer-vertex.glsl.js#L64). This causes the path to fail the `PIXEL_EPSILON` check [here](https://github.com/uber/deck.gl/blob/master/modules/layers/src/path-layer/path-layer-vertex.glsl.js#L70). Although the two points which make up the path may be thousands of meters away from each other in altitude, the shader considers them the same point and does not draw a line between them. This was tested by adding a small offset to the longitude or latitude of one of the two points, which does indeed produce a line. A sufficiently small offset must be used or else a line will not be rendered.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
The PathLayer was not originally designed to show full-3D paths -- each leg is rendered as a flat surface and as you rotate the viewport it can become invisible. I'm interested in your use case here. If your source data is in discrete line segments the LineLayer is probably a better choice -- the output always faces the camera.

**Comment by fanwashere** [comment]
@Pessimistress thanks for getting back on this. LineLayer (at least from reading the source code) is 2D only, correct? Also, I did notice that PathLayer does look invisible from certain perspectives since it is a flat line. Is there is a good way to visualize discrete straight-line segments in 3D which has neither the problem described above nor the flat problem with PathLayer? The use case is to visualize aircraft trajectories.

**Comment by Pessimistress** [comment]
All layers accept 3d positions. Check out our [LineLayer example](http://deck.gl/#/examples/core-layers/line-layer).

**Comment by Pessimistress** [comment]
@bianzbenny Use the `billboard: true` prop.
