### ISSUE TITLE
Project screen coordinates (x, y) to layer coordinates (x, y, z)

### ISSUE THREAD

**Issue by ZohaibAhmed** [uber/deck.gl#2303]
#### Background 
DeckGL provides no way of mapping clicks on the client/screen (x, y) to (x, y, z) coordinates in `COORDINATE_SYSTEM.IDENTITY`.

This PR looks like a good start: https://github.com/uber/deck.gl/pull/2286

Can we create an API, perhaps an extension of the `pickable` functionality on the layer level?

**Comment by Pessimistress** [comment]
Technically it is not possible to unproject 2d back to 3d as there are infinite number of points along the ray. What is your specific use case?

**Comment by ZohaibAhmed** [comment]
Ideally, I just want to find the appropriate x and y in the 3d view. The `z` can be fixed to 0. The use case here is a point cloud that I'm rendering, and I want the ability to add another point on click.

**Comment by Pessimistress** [comment]
The `onHover` and `onClick` gives you a `lngLat` object which should be the unprojected coordinates: https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/pick-layers.js#L334

The naming is of course confusing and should be changed if you are not using a geospatial viewport, but the result should be correct?

**Comment by ZohaibAhmed** [comment]
Thanks @Pessimistress, I was on an older version of deck.gl. I can work from here.
