### ISSUE TITLE
Add webpack example

### ISSUE THREAD

**Issue by jefffriesen** [uber/deck.gl#231]
I know uber doesn't officially support webpack, but someone watching this repo probably has solved this problem. Enough React developers use webpack that I think it would be nice to get a PR together to fix this for everyone else (I'm willing to help if we can nail it down).

The errors I get are:
```
Uncaught ReferenceError: regeneratorRuntime is not defined

./~/glslify/index.js
Critical dependencies:
148:22-37 the request of a dependency is an expression
 @ ./~/glslify/index.js 148:22-37

[HMR] ./~/glslify/LICENSE.md
Module parse failed: /Users/jeffers/git/jefffriesen/electron-analytics/node_modules/glslify/LICENSE.md Unexpected token (1:4)
You may need an appropriate loader to handle this file type.

lots more glslify errors....
```

My take is that glslify isn't being loaded through webpack properly. I have the latest release, so glslify is loaded via dependencies (https://github.com/uber/deck.gl/issues/48). 

I have react-map-gl loaded and working properly as well by adding alias in the webpack config:
```
alias: {
  'mapbox-gl/js/geo/transform': path.join(__dirname, "/node_modules/mapbox-gl/js/geo/transform"),
  'mapbox-gl': path.join(__dirname, "/node_modules/mapbox-gl/dist/mapbox-gl.js")
}
```

It's when I try to add deck.gl as a child component to MapGL that it fails and I get the errors above:

```jsx
import React, {Component, PropTypes} from 'react'
import MapGL from 'react-map-gl'
import DeckGL from 'deck.gl/react'
import {ScatterplotLayer, Viewport} from 'deck.gl'
const MAPBOX_TOKEN = 'pk....'
const viewport = new Viewport()
const data = []


export default class Map extends Component {

  static propTypes = {
    onChangeViewport: PropTypes.func,
  }

  state = {
    viewport: {
      latitude: 37.7749,
      longitude: -122.4194,
      zoom: 11,
      startDragLngLat: null,
      isDragging: false
    }
  }
  
  onChangeViewport = (viewport) => {
    if (this.props.onChangeViewport) {
      return this.props.onChangeViewport(viewport)
    }
    this.setState({viewport})
  }

  render() {
    const {viewport} = this.state
    const common = {
      width: 1000,
      height: 1000,
      style: {float: 'left'},
      mapboxApiAccessToken: MAPBOX_TOKEN,
      onChangeViewport: this.onChangeViewport
    }
    const mapProps = {...common, ...viewport} 
    return (
      <MapGL {...mapProps}>
        <DeckGL
          debug
          viewport={viewport}
          layers={[new ScatterplotLayer({data})]}
        />
      </MapGL>
    )
  }
}
```

Does someone know how to fix this?

**Comment by philogb** [comment]
Thanks for asking this @jefffriesen - we're planning on phasing out glslify in deck.gl which should solve this problem. @Apercu can you have a look at it when you have some time?

**Comment by Apercu** [comment]
I've managed to get webpack working with the current deck.gl last week and was planning to release a small config example in a separate repo

**Comment by philogb** [comment]
That's awesome! Why a separate repo though?

**Comment by Apercu** [comment]
I thought it would be a bit out-of-scope of the project, since people mostly use browserify when it comes to deck.gl and mapbox stuff, but I you think it's fine to have it there that works too ;)

**Comment by jefffriesen** [comment]
I would love to see the webpack example when you get a chance. Thanks

**Comment by tehwalris** [comment]
@jefffriesen Meanwhile [here's a gist](https://gist.github.com/tehwalris/606dcc8d8974e4e48740ed204e166bac) with the relevant parts of my working config. Hopefully that will help.

**Comment by ibgreen** [comment]
glslify is no longer a dependency so at least that should no longer be an issue. Still it would be nice to have a small working webpack example as a starting point for non-browserify users, so will leave this issue open for discussion/contribution.

**Comment by Apercu** [comment]
@jefffriesen You should try again using the latest `3.1.0`release, since as @ibgreen said, we removed `glslify` completely.

You can also follow the ongoing progress at #247 for the webpack example if this still doesn't resolve your issue.

**Comment by jefffriesen** [comment]
Thanks for working on this. That [config](https://gist.github.com/tehwalris/606dcc8d8974e4e48740ed204e166bac) did not work - I keep getting `regeneratorRuntime is not defined` errors at the call `var _webglRenderer = require('./webgl-renderer');`. I'll post more in ticket #247
