### ISSUE TITLE
Can't start the standalone version of the TripsLayer example

### ISSUE THREAD

**Issue by ricardoCyy** [uber/deck.gl#2316]
#### Actual Result
3 errors appeared in turn when I was trying to start the TripsLayer example following the [guideline.](https://github.com/uber/deck.gl/tree/master/examples/website/trips#usage)

1. Module 'webpack-cli' is outdated. [can't read property 'properties' of undefined at module.export 'webpack-cli'](https://github.com/ricardoCyy/imgs/blob/master/comments/trips_error1.png) occurred after I ran
`npm install`
`npm start`
(solved by updating 'webpack-cli' to the latest version 3.1.1);

2. Module 'html-webpack-plugin' not found. [can't find module 'html-webpack-plugin'](https://github.com/ricardoCyy/imgs/blob/master/comments/trips_error2.png)
(solved by installing 'html-webpack-plugin');

3. After I solved last two errors, the project can be compiled, but nothing happened. And this error occured
[App is not defined](https://github.com/ricardoCyy/imgs/blob/master/comments/trips_error3.png)
#### Expected Result
Run TripLayer example.
#### Reproduce Steps
1. update 'webpack-cli' to 3.1.1;
2. install 'html-webpack-plugin';
3. install '@deck.gl/experimental-layers' (version 6.1.1);

**Comment by ricardoCyy** [comment]
I download the "trip" file and 'npm install'&'npm start' same error happened. But I implement a TripLayer by import './trip-layer', so it's no longer an issue for me. I'll close this issue. Thanks for your effort! XD

**Comment by ricardoCyy** [comment]
By the way, I'm desperately curious about any news on the "strokeWidth" prop? I can't find its definition in 'trip-layer.js', and I know it used to be unchangeable because of the use of gl.LINE. But I saw you manipulate it in [multi-viewport example](https://github.com/uber/deck.gl/blob/6048cdf179500d4e84f19020e3c279e9ad3740ea/test/apps/multi-viewport/app.js). So is it now accessible? If it is not, is there any trick I could use to change the line width while keeping the other props (i.e., trailLength, animation) of TripsLayer?
Any tip will be appreciated.

**Comment by lucycousins** [comment]
@ricardoCyy how did you fix the 'App is not defined' error? Can you share a code snippet?

**Comment by ricardoCyy** [comment]
> @ricardoCyy how did you fix the 'App is not defined' error? Can you share a code snippet?

sorry for my late reply. I think this error occurred because of the late updating of "trip-layer.js" file in 'deck.gl'.
Solution: download the latest "trip-layer.js" file in your project and just import it from your project but not from 'deck.gl'.
