### ISSUE TITLE
deck.gl - multiple versions detected: 6.1.1 vs 5.3.3

### ISSUE THREAD

**Issue by GloriaCHL** [uber/deck.gl#2319]
I am using both kepler.gl and deck.gl now. There's a error here 'Error: deck.gl - multiple versions detected: 6.1.1 vs 5.3.3'. I checked node_modules and found that kepler.gl use deck.gl v5.x, and I installed another v6.x. And I can't install older version because I need the orthographic view controller which in the least deck.gl version. Can anybody give some advance ？

**Comment by Pessimistress** [comment]
kepler.gl is in the process of upgrading to v6. You may need to get their beta release for this to work.
@heshan0131

**Comment by GloriaCHL** [comment]
@Pessimistress Thank you for your help!
