### ISSUE TITLE
publish demo layers / add to core?

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#232]
Any plans to publish the demo layers (or add them to core) so people don't have to copy/paste the code if they want to use it?

**Comment by Apercu** [comment]
Are you referring to the trip layer?

**Comment by contra** [comment]
@Apercu yep

**Comment by Apercu** [comment]
We are working on publishing more layers indeed, I believe the trip layer would also be one of those, although it might come in a more generic form to be easily reusable and customizable :)

**Comment by contra** [comment]
Closing, other issues opened per-layer already
