### ISSUE TITLE
Best practice to share maps between components

### ISSUE THREAD

**Issue by schlesingermatthias** [uber/deck.gl#2321]
Hi, 
I'm working on a map-centered application. I have different fairly complex layers that change depending on how the user interacts with the map. Right now I have multiple components that contain a DeckGL component with a static map. 

So for instance there's a Component with multiple markers (OverviewComponent.js): 
```
export default const OverviewComponent {
...
  render() {
    <DeckGL
      layers={this.renderMarkers()}
      initialViewState={initialViewState}
      onViewStateChange={this.viewStateChange}
      controller 
      pickingRadius={5}>
      <StaticMap reuseMaps mapStyle={mapstyle} preventStyleDiffing />
   </DeckGL>
  }
}
```

When I click on a marker, the application routes to a different component (MarkerComponent.js) where complex visualizations for the selected marker are rendered. It looks like the one above but with different layers passed to the DeckGL component.
```
export default const MarkerComponent {
...
  render() {
  <DeckGL
      layers={this.renderConnections()}
      ...>
      <StaticMap reuseMaps mapStyle={mapstyle} preventStyleDiffing />
   </DeckGL>
  }
}
```
I'm looking for best practices to provide smooth transitions between those components when the user interacts with the map. Ideally with viewport transitions (flying to the selected marker) and without a noticeable lag. If I put everything in one component it would work but the component would get huge. So what's the best approach to keep a clean app structure but still achieve a smooth UI? Thanks in advance

**Comment by 1chandu** [comment]
@schlesingermatthias ,  when using `DeckGL`,  transitions are tied to that component.
How about you use [react-map-gl,](https://github.com/uber/react-map-gl) which also offers same set of viewport transitions, and you can keep InteractiveMap at the root component, [example](https://github.com/uber/react-map-gl/blob/master/examples/deckgl-overlay/src/app.js).

**Comment by Pessimistress** [comment]
@schlesingermatthias If you want continuous transition, then you cannot unmount the <DeckGL> component. When dealing with complex visualizations, we usually use [custom composite layers](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/composite-layers) to organize code:

```js
// overview-layer.js
import {CompositeLayer, IconsLayer, ScatterplotLayer} from 'deck.gl';

export default class OverviewLayer extends CompositeLayer {
  renderLayers() {
    return [
      new IconsLayer(...),
      new ScatterplotLayer(...)
    ];
  }
}
```

```js
// markers-layer.js
import {CompositeLayer, LineLayer} from 'deck.gl';

export default class OverviewLayer extends CompositeLayer {
  renderLayers() {
    const {customProp1, customProp2} = this.props;
    return [
      new LineLayer(...),
      new LineLayer(...)
    ];
  }
}
```

```jsx
// map-component.js
import DeckGL from 'deck.gl';
import OverviewLayer from './overview-layer';
import MarkersLayer from './markers-layer';

export default const MapComponent {

  _renderLayers() {
    const {customProp1, customProp2} = this.props;
    switch (this.state.visType) {
      case 'overview':
        return new OverviewLayer({
          customProp1: this.props.some_prop,
          customProp2: this.state.some_state
        });

      case 'markers':
        return new MarkersLayer({
          customProp1: this.props.some_prop,
          customProp2: this.state.some_state
        });
    }
  }

  render() {
    <DeckGL
      ...
      layers={this._renderLayers()} >
      <StaticMap reuseMaps mapStyle={mapstyle} preventStyleDiffing />
   </DeckGL>
  }
}
```
