### ISSUE TITLE
Picking Info Object returns null in Safari/iOS

### ISSUE THREAD

**Issue by jarekpelczynski** [uber/deck.gl#2329]
Every time when I try to call [Picking Engine directly](http://deck.gl/#/documentation/developer-guide/adding-interactivity?section=calling-the-picking-engine-directly) (using example code) or trigger built-in event I got `null` (instead of an event) in Safari/iOS. It's fine in Desktop browsers.

My deck.gl version is 6.1.1

**Comment by Pessimistress** [comment]
Is this still an issue in 6.2.0?

**Comment by Pessimistress** [comment]
Can you post a code snippet here that reproduce this issue?

Picking on the deck.gl website in iOS Safari is working on my device.

**Comment by jarekpelczynski** [comment]
The same as in this guide: [Using the Built-in Event-Handling
](http://deck.gl/#/documentation/developer-guide/adding-interactivity?section=calling-the-picking-engine-directly)

This example do not work for me: http://deck.gl/#/examples/core-layers/icon-layer

**Comment by jarekpelczynski** [comment]
@1chandu I've made test again with version 6.2 and it works, probably old versions was cached on iOS Simulator. Sorry for the confusion.

**Comment by jarekpelczynski** [comment]
I found that picking info in 6.3.0 version doesn't work again on iOS – for instance: http://deck.gl/#/examples/core-layers/icon-layer

**Comment by 1chandu** [comment]
Closing .., please re open if this still happens with latest release.
