### ISSUE TITLE
Shaky Icons onMove

### ISSUE THREAD

**Issue by Pagnito** [uber/deck.gl#2330]
#### Code Example 
http://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer
if you zoom in on the icon and move the map around, youll see the icon is jumping around. 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Turn on `fp64`.

**Comment by Pagnito** [comment]
Thank you
