### ISSUE TITLE
Make example testing back to work

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#2331]
#### Actual Result
Example testing is broken
#### Expected Result
should work well
#### Reproduce Steps
npm run test examples
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test

**Comment by Pessimistress** [comment]
One more thing: we should move the json examples (data + app) to examples/experimental. The APIs are not yet audited for stability & design.
