### ISSUE TITLE
IconLayer problem

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#2341]
In my project ,a event to make dots. so I want use IconLayer to achieve the effect.
I refer to the example [IconLayer](http://deck.gl/#/examples/core-layers/icon-layer).
in the code ,I copy 'icon-cluster-layer.js' file in my project
in layer 
```
      new IconClusterLayer({
        data: RankListData,
        wrapLongitude: true,
        getPosition: d => d.location,
        iconAtlas: require('../../images/rank_icon.png'),
        iconMapping: require('../../data/rank-icon-mapping.json'),
        sizeScale: 30,
         id: 'icon-cluster'
        }),
```
but the result is not quiet right,:
![image](https://user-images.githubusercontent.com/42837853/46601573-0d758e00-cb20-11e8-8ed2-c755bcd449ce.png)
the yellow point maybe is the icon ,in console.
![image](https://user-images.githubusercontent.com/42837853/46601595-2120f480-cb20-11e8-9309-6d7ac5454c99.png)
and in the line 97 
![image](https://user-images.githubusercontent.com/42837853/46601616-385fe200-cb20-11e8-9dab-536244df0656.png)
how can I resolve this warn to show the right effect.
thank you .

**Comment by HeiYanjing** [comment]
> @HeiYanjing
> 
> `icon-cluster-layer.js` is an example that uses standard core layer `IconLayer`. It basically projects icon position in screen space to group them into clusters. You may have to apply any changes to the `icon-cluster-layer` based on you data format and please compare all other required props.
> 
> The crash seem to be due to invalid data format, make sure data in your props is an array where each element contains `coord` array.

yes，I resolved it ,thank you

**Comment by hijiangtao** [comment]
This is always because that the input data doesn't include property of `coordinates`. In `icon-cluster-layer.js`, the location of one point is fixed to be get from this key. See https://github.com/uber/deck.gl/blob/6.3-release/examples/website/icon/icon-cluster-layer.js#L97

```javascript
const screenCoords = transform.project(p.coordinates);
```

Other developers may face the same problem when they need to modify the codes of this demo, I think abstract it to a user customized input property will be better, such as:

```javascript
const User_Customized_Key_Name = props.User_Customized_Key_Name || 'coordinates';
const screenCoords = transform.project(p[User_Customized_Key_Name]);
```

:-)

**Comment by 1chandu** [comment]
@hijiangtao , please update to latest deck.gl version, and let us know if it is still relevant, if so please re open the bug, closed bugs are usually not monitored.

**Comment by hijiangtao** [comment]
@1chandu Well, I can customize `getPosition` function right now, but it doesn't work in deck.gl@6.3.1 or older versions. Thanks.
