### ISSUE TITLE
IconLayer obscured by buildings

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#2343]
firstly
I refer to the example iconlayer in my project. and I achieve effect like this
![image](https://user-images.githubusercontent.com/42837853/46667640-d4f7b200-cbfc-11e8-974b-4e59867dda82.png)
the icon show correctly.
the building show 3D effect, so , there is a problem in the web page, in larger scale.
![image](https://user-images.githubusercontent.com/42837853/46667742-243de280-cbfd-11e8-944d-c77e2d5bf835.png)
Icons blend with buildings .
so ,can icons suspended in the air or buildings ?

**Comment by Pessimistress** [comment]
You may either:
- Add an altitude (`[long, lat, z]`) to the position of each icon
- Disable depth testing by passing `parameters: {depthTest: false}` to the IconLayer

**Comment by HeiYanjing** [comment]
> You may either:
> 
> * Add an altitude (`[long, lat, z]`) to the position of each icon
> * Disable depth testing by passing `parameters: {depthTest: false}` to the IconLayer

thank you for your reply .
I add altitude when I handle the coordinate. , I set altitude 80,and it works,
![image](https://user-images.githubusercontent.com/42837853/46717219-a8de3e80-cc99-11e8-9d26-c570d92ceafd.png)
icons like ballon suspend above the buildings .but there is another question
the buildings  PolygonLayer still overlaps with the IconClusterLayer。Because buildings datas and icon coordinate datas are independent of each other。so ,Is it possible to set up active avoidance buildings？

**Comment by Pessimistress** [comment]
If you mean making the icons automatically avoid the buildings... that would be very difficult. You can try setting a larger `z` value, then draw a vertical line from the bottom of each icon to the ground to provide some visual reference:

![image](https://user-images.githubusercontent.com/2059298/47059682-47c5d780-d17f-11e8-83c2-9039c298b6fe.png)


If you are using the IconClusterLayer from our [example](https://github.com/uber/deck.gl/blob/master/examples/website/icon/icon-cluster-layer.js), you can do this by modifying the `renderLayers` method:

```js
return [
  // the same IconLayer
  new IconLayer(...),

  // new
  new LineLayer(
      this.getSubLayerProps({
        id: 'icon',
        data,
        getSourcePosition: getPosition,
        getTargetPosition: d => {
          const p = getPosition(d);
          return [p[0], p[1], 0];
        },
        getColor: [255, 255, 255],
        getStrokeWidth: d => d.zoomLevels[z] ? 1: 0,
        updateTriggers: {
          getStrokeWidth: {version, z}
        }
      })
    );
];
```

**Comment by HeiYanjing** [comment]
@Pessimistress Thank you for you  reply. and you can understand what I said
