### ISSUE TITLE
Failed to run example in deck.gl 6.0 release

### ISSUE THREAD

**Issue by levitomer** [uber/deck.gl#2344]
Hi,

I Tried to get some hands-on practice with an example in deck.gl repository. However, I find it difficult to start it using npm. 

I followed the instructions in http://deck.gl/#/documentation/getting-started/installation guide. And both npm start or npm run start-local doesn't launch the example (so far I have tried 3d-heatmap, tagmap, and arc).

The log shows the following output:

tomerlevi@macintosh > ~/GitHub/React/deck.gl/examples/website/tagmap > 6.0-release > npm start

> tagmap@0.0.0 start /Users/tomerlevi/GitHub/React/deck.gl/examples/website/tagmap
> webpack-dev-server --progress --hot --open

/Users/tomerlevi/GitHub/React/deck.gl/examples/website/tagmap/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^
**TypeError: Cannot read property 'properties' of undefined**
    at module.exports (/Users/tomerlevi/GitHub/React/deck.gl/examples/website/tagmap/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/Users/tomerlevi/GitHub/React/deck.gl/examples/website/tagmap/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tagmap@0.0.0 start: `webpack-dev-server --progress --hot --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tagmap@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tomerlevi/.npm/_logs/2018-10-09T13_15_37_404Z-debug.log

Pasting the package.json for reference:

{
  "name": "arc",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start-local": "webpack-dev-server --env.local --progress --hot --open",
    "start": "webpack-dev-server --progress --hot --open"
  },
  "dependencies": {
    "d3-scale": "^2.0.0",
    "deck.gl": "^6.0.0",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-map-gl": "^3.3.0"
  },
  "devDependencies": {
    "buble": "^0.19.3",
    "buble-loader": "^0.5.0",
    "html-webpack-plugin": "^3.0.7",
    "webpack": "^4.3.0",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "^3.1.1"
  }
}

Thanks in advance for all the helpers, and sorry if I missed out anything.

**Comment by Pessimistress** [comment]
This is a problem caused by a recent webpack update. Try the 6.2-release branch.

**Comment by Pessimistress** [comment]
I've updated the readme.

**Comment by levitomer** [comment]
Working now, thanks!

I needed also to run _npm install_ again before running _npm start_

**Comment by donmccurdy** [comment]
@Pessimistress is there a workaround for contributors without using the 6.2 branch? Trying to submit a PR, not sure how else to test against the `master` branch.
