### ISSUE TITLE
Correct Ways to Update TripsLayer When Data Changes

### ISSUE THREAD

**Issue by zicodeng** [uber/deck.gl#2349]
I guess this not a bug nor feature enhancement. I am fairly new to data visualization. I just want to get some suggestions from you experts about how to solve the problem below :)

I am creating a project with TripsLayer to animate trips. The data is fetched from server every N seconds. Whenever polling (refetching) occurs, the data fed to the TripsLayer changes, this causes the layer to render new data. However, the problem is that there is milliseconds frozen on the map because of the data suddenly changes. The animation also disappears (half finished) and appears again. This is very noticeable when the data is large.

So what is the best way to create a live map with TripsLayer when data is constantly fetched from server every N seconds?

Thanks in advance. Really appreciate your help!

**Comment by Pessimistress** [comment]
Try always loading the new data fetched into a new TripsLayer. Theoretically every fetch you get updates of what happened in the last N seconds. Say your trail fades in m seconds. After (N + m) seconds you can be confident that nothing is rendered any more and remove the layer created for that chunk. Over time you will not end up with unlimited number of layers, and each one of them only receive data once.

**Comment by zicodeng** [comment]
Ok I have found a less than ideal solution. When data update arrives, I hide the animation layer. When update completes, I show the layer again. At least from UX perspective, this feels better than seeing frozen animation on the map :)
