### ISSUE TITLE
The documentation is terrible

### ISSUE THREAD

**Issue by RanQiwu** [uber/deck.gl#2356]
http://deck.gl/#/documentation/deckgl-api-reference/layers/point-cloud-layer
I want to see the full content of this demo, and one of the pieces isn't enough for me to run it.
I'm using pure js+mapbox-gl.js .

**Comment by SymbolixAU** [comment]
@RanQiwu The documentation may not be to your liking, but it's definitely not 'terrible'. 

The `point-cloud-layer` example you link to tells you how to construct the point cloud layer. And the [getting started](http://deck.gl/#/documentation/getting-started/using-standalone) section tells you how to add deck.gl to your page. 

Calling the work of the authors "terrible", and demanding to "see the full content of this demo" isn't a good way to file an issue.

**Comment by RanQiwu** [comment]
@SymbolixAU  
https://developers.google.com/maps/documentation/javascript/examples/polyline-simple
https://ant.design/components/button/
Similar to the above document, it is easy to understand.
A bad document can waste a lot of time trying to figure out how to use the tool.

**Comment by SymbolixAU** [comment]
I find Deck.gl's documentation easy to understand.

**Comment by RanQiwu** [comment]
@Pessimistress Thank you for your answer. Yesterday I did take a long time to solve the missing part of the code. I have a headache why it always runs unsuccessfully.
Today I switched to React to run successfully.
Finally, I want to emphasize that the current documentation is still missing a lot of things, but it can be found in the source code.
