### ISSUE TITLE
MapboxLayer unwanted brush effect bug

### ISSUE THREAD

**Issue by hugo-fonseca** [uber/deck.gl#2359]
Loved the new integration with mapbox-gl layers, the standalone seems to work just fine but in the react version there is a brush effect happening dragging the map.

Live example: (tested on chrome)
https://codesandbox.io/s/187260q354

![screenshot 2018-10-18 at 16 17 50](https://user-images.githubusercontent.com/6686394/47165217-75329280-d2f1-11e8-98fe-dbeea730bc40.png)

**Comment by Pessimistress** [comment]
You need to use react-map-gl@4.0.0-beta

**Comment by Harrisandwich** [comment]
@1chandu @Pessimistress @hugo-fonseca 

I'm still getting this with react-map-gl@^4.0.0-beta. Scatterplot layer duplicates on map pan.

**Comment by Pessimistress** [comment]
@Harrisandwich please open a new issue with code samples. It's impossible to debug from your description.
