### ISSUE TITLE
3d lines rendering

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#2361]
![image](https://user-images.githubusercontent.com/42837853/47193645-a1e4b980-d386-11e8-8feb-5d1ac20d72e0.png)
recently , I saw this effect render  lines for 3D effects ,when roads are rendered by corrdinate datas, red will exist constantly.
If this kind of  animation effects can achieved. I think it will use deck.gl and luma.gl。
so ,if it can be come true.Any ideas about this question？need help！

online watting....

**Comment by HeiYanjing** [comment]
@ricardoCyy ,thank you for your reply.I'm still concerned about this issue.

**Comment by HeiYanjing** [comment]
@ricardoCyy thank you for your reply.I'm still concerned about this issue.

**Comment by 1chandu** [comment]
Duplicate of https://github.com/uber/luma.gl/issues/759.

**Comment by HeiYanjing** [comment]
@1chandu Thank you for your reply.
