### ISSUE TITLE
TripsLayer not working?

### ISSUE THREAD

**Issue by convelming** [uber/deck.gl#2366]
I try to use Tripslayer by going to deck.gl-6.2-release/examples/website/trips with: npm install, and export MapboxAccessToken=xxx&& npm start, first there is an error saying lack of 'html-webpack-plugin' I googled and tried use this: npm i --save-dev html-webpack-plugin,
It seems it works, but there are further errors in the console:
"Module not found: Error: Can't resolve '@deck.gl/experimental-layers' in 'deck.gl-6.2-release/examples/website/trips'
errors @ webpack://App/(webpack)-dev-server/client?:162"
So I copied deck.gl-6.2-release/modules/experimental-layers into 'deck.gl-6.2-release/examples/website/trips/node_modules/@deck.gl'
still got:
Module not found: Error: Can't resolve '@deck.gl/experimental-layers'
So what should I do now? I have been trying this for a couple of days now.... Any help would be appreciated...

**Comment by zicodeng** [comment]
@convelming Hi, have you tried to install `@deck.gl/experimental-layers` dependency? TripsLayer is still in experimentation stage, so it is not found in `@deck.gl/layers`.

**Comment by XiaokaiUber** [comment]
@convelming Please try to add the following two lines in the package.json file in the trips folder:
1. to resolve the experimental-layers error, add the following line to "dependencies" 
"@deck.gl/experimental-layers": "^6.2.0" 
2. to resolve the html-webpack-plugin error, add the following line to "devDependencies"
"html-webpack-plugin": "^3.0.7"

**Comment by Pessimistress** [comment]
Fixed on 6.2-release branch
