### ISSUE TITLE
Accessing queryRenderedFeatures?

### ISSUE THREAD

**Issue by lapidus** [uber/deck.gl#2377]
I would like to count the number of scatterplot (or other layer) items in the viewport as the user pans & zooms. (I assume via map.queryRenderedFeatures)

Does Deck.gl facilitate this or would I have to interact with the underlying mapbox-gl?

Thank you!

**Comment by Pessimistress** [comment]
Are you querying features in an mapbox layer or a deck.gl layer? For react-map-gl questions please go to the react-map-gl repo.
