### ISSUE TITLE
Scatterplot layer: Radius updates

### ISSUE THREAD

**Issue by MoritzStefaner** [uber/deck.gl#238]
Hi,

I am observing the following problems when trying to update the radius of elements in the Scatterplot layer:

```
    updateCount++;
    let getScatterplot = ()=>{
      return new ScatterplotLayer({
        id: 'scatter-plot',
        data: scatterPlotData || [],
        getPosition: d => [d.lon, d.lat, d.elevation],
        getColor: d => [Math.floor(Math.random()*255), Math.floor(Math.random()*255), Math.floor(Math.random()*255)],
        getRadius: d => Math.random() * 10,
        updateTriggers: {
          instanceColors: {updateCount},
          instanceRadius: {updateCount}
        }
      });
    }
```

throws:

```
"AssertionError: undefined == true
    at AttributeManager.invalidate (http://localhost:8080/js/app.js:189025:29)
    at ScatterplotLayer._diffUpdateTriggers (http://localhost:8080/js/app.js:188791:31)
    at ScatterplotLayer.diffProps (http://localhost:8080/js/app.js:188695:15)
    at LayerManager._updateLayer (http://localhost:8080/js/app.js:190290:33)
    at LayerManager._matchSublayers (http://localhost:8080/js/app.js:190137:21)
    at LayerManager._updateLayers (http://localhost:8080/js/app.js:190089:25)
    at LayerManager.updateLayers (http://localhost:8080/js/app.js:189910:34)
    at DeckGL._updateLayers (http://localhost:8080/js/app.js:149339:13)
    at DeckGL.componentWillReceiveProps (http://localhost:8080/js/app.js:149321:13)
    at http://localhost:8080/js/app.js:31672:24"

```

(Visually, the example changes the colors of the dots, on each draw, but not the radii.) 

Any ideas?

**Comment by ibgreen** [comment]
@MoritzStefaner You were getting this error because the 32 bit ScatterplotLayer did not have an `instanceRadius` attribute (radius was encoded inside `instancePositions`).

The referenced PR updates the code to generate better errors when referencing undefined attributes in `updateTriggers`, and updates ScatterplotLayer(32) to have same attributes as ScatterplotLayer64, including `instanceRadius`. This should fix the issue.

**Comment by MoritzStefaner** [comment]
Ah, that makes sense! Thanks for the swift reply!

**Comment by MoritzStefaner** [comment]
Thanks! Might be another issue, but I updated to 3.1.0 now, and get the following warnings / errors:

```
warning.js:36Warning: Failed prop type: Cannot call a class as a function
    in DeckGL (created by Motion)
    in Motion (created by MapView)
    in MapView (created by App)
    in div (created by App)
    in App

log.js:54Program scatter-plot-program: Attribute 2:instancePositions not supplied
```
(layer definition is same as above) - any ideas? Has the API changed?

**Comment by ibgreen** [comment]
https://github.com/uber/deck.gl/pull/244 landed last night, fixes the `instancePositions` issue. Will be published today.

**Comment by ibgreen** [comment]
The warning looks like a React PropTypes mixup. Will take a look.

**Comment by ibgreen** [comment]
@MoritzStefaner 3.1.1 published, give it a try.

**Comment by jefffriesen** [comment]
I ran into the same problem and this fixed it. Thanks.

**Comment by MoritzStefaner** [comment]
@ibgreen Works fine now, thanks!
