### ISSUE TITLE
OrbitController not working with Deck.gl 6.2.0

### ISSUE THREAD

**Issue by ZohaibAhmed** [uber/deck.gl#2381]
#### Actual Result

OrbitController doesn't work (this includes all movements - panning, zooming, rotating).

#### Expected Result

I expect `onViewportChange` to be called, but it never is from the controller. This was working on the last deck.gl version I was on (5.2).

#### Code Example 

```
<DeckGL
                    ref={"deckgl"}
                    width={width}
                    height={height}
                    views={new OrbitView()}
                    zoom={100}
                    viewState={viewState}
                    controller={OrbitController}
                    onViewportChange={this._onViewportChange}
                    layers={layers}
                />
```

**Comment by jianhuang01** [comment]
onViewportChange is not supported anymore, use onViewStateChange per [upgrade-guide](https://github.com/uber/deck.gl/blob/master/docs/upgrade-guide.md)
