### ISSUE TITLE
Conditional development/debug mode

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2386]
#### Background

Deck's `debug` prop is overloaded:

- Enable [WebGL debugging](http://deck.gl/#/documentation/deckgl-api-reference/deck?section=configuration-properties). Also requires to import `luma.gl/debug`.
- Enable layer prop validation, see [comment](https://github.com/uber/deck.gl/pull/2378#discussion_r227938732)

The proposal is to toggle these features based on `process.env.NODE_ENV === 'production'` instead, similar to React's [build mechanism](https://reactjs.org/docs/optimizing-performance.html).

**Alternative proposal** use probe.gl's global flag?

#### To Do List
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update
  - [ ] Test

**Comment by tgorkin** [comment]
The spirit of this feature was completed during 8.0 milestone as part of #3957
