### ISSUE TITLE
Trips won't show up when the timestamp value is large

### ISSUE THREAD

**Issue by Bill-Q** [uber/deck.gl#2397]
Hi,
I am using deck.gl/experimental-layers @6.2.3 and encounted a bug in the TripsLayer. When the timestamp in `[longitude, latitute, timestamp]` set to a large number, e.g. 15000, and each step is large, e.g. 1000, the trip animation stop working properly. The trip would fade out before reach the next vertex in the path or fade in in the middle of a segment. Anyway to make it work with large number in the timestamp? Our goal is to use the UNIX time as timestamp.

Many thanks.

Bill

#### Reproduce Steps
Sample data:
`[{
  "vendor": 0,
  "segments": [
    [-73.98973, 40.71409, 1000],
    [-73.98933, 40.71412, 6000],
    [-73.99024, 40.7144, 9000],
    [-73.99188, 40.71489, 15000],
    [-73.99237, 40.71505, 17000],
    [-73.99179, 40.71616, 20000],
    [-73.99117, 40.71734, 23000],
    [-73.99331, 40.71798, 30000],
    [-73.99382, 40.71814, 31000],
    [-73.99335, 40.71906, 35000]
  ]
}]`
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
Are you referring to `currentTIme` prop? And what are you setting for `trailLength`? 

Here is the example on how these props can be used : https://github.com/uber/deck.gl/blob/60e99cce91f9fee385543d4a38cb9eb4d4c9f6c5/examples/website/trips/app.js#L55

**Comment by BertCh** [comment]
I ran into a this issue and transforming the number used to represent time using d3-scale made it work
```
const timeScale = scaleLinear() //scaleLinear from d3-scale
    .domain([minDate, maxDate])
    .range([0, 120]);
```
The insights in this post lead me to my solution to the issue.
https://github.com/uber/deck.gl/issues/1854#issuecomment-412650008

**Comment by Bill-Q** [comment]
> I ran into a this issue and transforming the number used to represent time using d3-scale made it work
> 
> ```
> const timeScale = scaleLinear() //scaleLinear from d3-scale
>     .domain([minDate, maxDate])
>     .range([0, 120]);
> ```
> The insights in this post lead me to my solution to the issue.
> [#1854 (comment)](https://github.com/uber/deck.gl/issues/1854#issuecomment-412650008)

@BertCh Thanks for reading my question and posting the solution! I ended up with writing a scaling function myself. The solution you quoted seems to be much cleaner. 

I still feel this is a bug and it still exists. It would be nice to have the dev team fixed it.

**Comment by 1chandu** [comment]
@Bill-Q , can you give us more context on other props, and answer my above questions. Please compare your implementation with above example I pointed.

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)
