### ISSUE TITLE
3D rotated text or image

### ISSUE THREAD

**Issue by MarcinPiekarniak** [uber/deck.gl#2408]
Is there any plan to add rotation to TextLayer or Iconlayer so it rotates along with camera like other layers instead of staying 2D?

There's some bitmapLayer in sample layers but I haven't  checked it out and I'm not sure if it works or if it allows rotations. 

Is there any easy way to achieve 3D rotated text with current tools? 

If no what's the best approach to implement my own layer or override existing one that would allow me to render either 3d image or 3d text?

I'm a bit familiar at this point with 3d basics like , z-buffers and matrix operations: rotations, scaling, translations, camera matrix, clipspace, projections, model-world. I went through luma.gl examples and ran some code from https://webglfundamentals.org/  - compiling shaders, passing buffers and defining attributes. I used deck.gl to make an application and at least in theory I know how it works because I read some source code and most of the documentation - but my knowledge is still vague.

I guess reading "Writing Custom Layers", rendering 3d textures like here https://webglfundamentals.org/webgl/lessons/webgl-3d-textures.html and going through code of existing layers would be good starting point but anything specific/useful I should know before I start doing it?

**Comment by jianhuang01** [comment]
We have no plan to support icon/text 3D rotation for now, the reason is that with 3D rotation the labels are usually hard to read. You need understand 3D matrix operation and basic webgl knowledge to implement a custom layer for it.

**Comment by MarcinPiekarniak** [comment]
Thank you for response. I'll be implementing it and post code some code here once I'm done for someone who might stumble here accidently.

**Comment by ayeganov** [comment]
@MarcinPiekarniak Hi Marcin, is your code open source? Can I have a look at your implementation?

**Comment by ibgreen** [comment]
You may want to check out the billboard option in the soon-to-be-released deck.gl v7:

https://github.com/uber/deck.gl/pull/2846/files

**Comment by MarcinPiekarniak** [comment]
@ayeganov

Hey. Just read your comment. Maintainers added that billboard option in PR but I'll make public opensource that anyone can use repository with runnable deck.gl example on my github profile with my code. The code I wrote is usable but it's not completely clearly written. I'll add it within few days as I'm busy right now.

I have two versions:
-render texture using quadrilateral with 4 coordinates (lat, longitude)
-render rectangle with center (lat, long) initial rotation and diagonal size

And over it version with generating multiple texts I called it SignLayer (using 4 coordinates):

![Screenshot-13](https://user-images.githubusercontent.com/24396676/56206603-0f7b5500-604d-11e9-945f-e9fba075e07a.png)

**Comment by MarcinPiekarniak** [comment]
@ayeganov I deleted previous comment from april. Sorrry that I give it so late and you probably don't need it here's some code:

https://github.com/MarcinPiekarniak/SignLayer

BitMapLayer takes 4points and displays it as a rectangle, SignLayer uses it(I modified SignLayer deleting some code - I didn't rerun it). There's legacy position parameter sent when I was doing it based on one position and rotation (the code is commented out so you see two solutions there)
