### ISSUE TITLE
Experimental Tile Layer: getFillColor accessor and visibility property do not update correctly 

### ISSUE THREAD

**Issue by Harrisandwich** [uber/deck.gl#2411]
#### Actual Result
- When the visible property is set to false, the layer remains visible
- When the fill color is changed, the fill color updates inconsistently and only on map zoom

#### Expected Result
- When the visible property is set to false, the layer is no longer visible
- When the fill color is changed, the fill color updates for all features immediately

#### Reproduce Steps
**For visible property:**
1. have a tile layer in the renderLayers loop
2. toggle the visibility with a toggle control

**For getFillColor accessor:**
1. have a tile layer in the renderLayers loop
2. Get fill color with a function
3. change fill color using a color picker/slider control

#### Code Example 
**Below is the data being passed to the layer**
**getFillData not included. Matches example in TileLayer readme**
```
// gets the color for the feature based on the data of that feature
const getFillColor = (feature, data) => {
  const property = 'total' 
  let color = [255, 255, 255, 255]
  let colorSet = false
  data.style.forEach((s) => {
    if (!colorSet && feature.properties[property] <= s.data) {
      const c = hexToRgb(s.color)
      color = [c.r, c.g, c.b, 255]
      colorSet = true
    }
  })
  const last = data.style.length - 1
  if (feature.properties[property] > data.style[last].data) {
    const c = hexToRgb(data.style[last].color)
    color = [c.r, c.g, c.b, 255]
  }
  return color
}

export default (data, options) => ({
  layers: [{
    type: 'TileLayer',
    id_key: 'slug',
    layer_name: 'fill',
    properties: {
      stroked: false,
      visible: data.enabled,
    },
    actions: {
      getLineColor: [192, 192, 192],
      getFillColor: d => getFillColor(d, data),
      getTileData,
      },
    },
    events: {
      onClick: () => { console.log('clicked') },
      onHover: () => { console.log('hovered') },
    },
  }],
})
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
This is by design. deck.gl does not recalculate colors on every render pass because it will kill performance. You need to use the `updateTriggers` prop to manually trigger an update. See [updateTriggers on the Layer class documentation](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=data-properties)

**Comment by Harrisandwich** [comment]
@Pessimistress The update triggers work great for the color change, but the `visible` prop still doesn't seem to properly toggle the layer. `updateTriggers` is only for accessors, so that doesn't look like the right option here. Is there a similar process for updating the `visible` prop?

**Comment by Pessimistress** [comment]
You don't need update trigger for `visible`. That should be a bug. @starry97

**Comment by XiaokaiUber** [comment]
@Harrisandwich It seems there is an extra `{` in the `export default` part of your code. Can you share more code with me so that I can do further investigation?

**Comment by Pessimistress** [comment]
The fix is published in 6.4.0.

**Comment by alitarraf** [comment]
I am still facing issue with implementing a checkbox to turn on or off a layer in pure js using updatetriggers.
I have this layer, 
```     
    const myIconlayer = new IconLayer({
        id: 'icon-layer',
        data:educationData.features,
        pickable: true,
        iconAtlas: './schooltr.png',
        iconMapping: ICON_MAPPING,
        getIcon: d => 'marker',
        
        visible: enabled,
        updateTriggers: {
          visible: [true, false],
        },

        sizeScale: 6,
        getPosition: d => d.geometry.coordinates,
        getSize: d => 5,
        getColor: d => [Math.sqrt(1000), 140, 0],
      });

      deckgl.setProps({
        layers: [hexagonLayer,myIconlayer],
        viewState: Object.assign({}, currentViewState)
      });
```
and I am updating the visibility with this function
```
    function enabled() {
      // Get the checkbox
      var checkBox = document.getElementById("Education");

      // If the checkbox is checked, display return true
      if (checkBox.checked == true){
        console.log("checkbox true")
        return true    
      } else {
        console.log("checkbox false")
        return false
      }
    }
```

However nothing happens on the map, it doesnt seem to change the visibility of the layer. However when i do it manually (replacing with false and true the visible prop) it works.

Anything I am missing?

**Comment by Pessimistress** [comment]
@alitarraf Your use case is not related to this issue, which is about the TileLayer. We do not monitor closed issues. Please open a new issue if you need help.

**Comment by alitarraf** [comment]
Here is the link to the new issue, thanks!
https://github.com/visgl/deck.gl/issues/4571
