### ISSUE TITLE
Experimental TileLayer: onClick event is non-functional

### ISSUE THREAD

**Issue by Harrisandwich** [uber/deck.gl#2413]
#### Actual Result

onClick event handler prop for TileLayer doesn't handle clicks

#### Expected Result

onClick event handler prop for TileLayer should handle clicks

#### Reproduce Steps

- Add an onClick handler to the experimental TileLayer. 
- Click features on the layer

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
Make sure you set the `pickable` prop to `true`. See [layer interaction properties](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=interaction-properties).

**Comment by Harrisandwich** [comment]
@Pessimistress oh my god. I totally flaked on that. Thanks for putting up with all my issues today! I appreciate it a lot!
