### ISSUE TITLE
userData is not present in context on initial render

### ISSUE THREAD

**Issue by goszczynskip** [uber/deck.gl#2414]
When supplying `userData` attribute to deck.gl component isn't present in `context` passed to `initializeState` method.
Version: 6.2.3

#### Code Example
```
class CustomLayer extends CompositeLayer {
  initializeState(context) {
   console.log(context.userData.foo)
  }
}

// in react component
<DeckGL 
  userData={{ foo: "bar" }} 
  layers={[new CustomLayer({ data:[] })]} 
  {...otherProps}>
  {children}
</DeckGL>
```
#### Actual Result
`console.log` prints `undefined`

#### Expected Result
`console.log` should print `"bar"`

#### Potential culprit
`setLayers` are called before setting userData. 
https://github.com/uber/deck.gl/blob/7cde1e1e01acbecef5e6634fc88510be5576ce87/modules/core/src/lib/layer-manager.js#L165
https://github.com/uber/deck.gl/blob/7cde1e1e01acbecef5e6634fc88510be5576ce87/modules/core/src/lib/layer-manager.js#L184
Changing their order should fix this bug.

**Comment by Pessimistress** [comment]
Published 6.2.4.
