### ISSUE TITLE
Best way to set per-view visibility of layers

### ISSUE THREAD

**Issue by MGraefe** [uber/deck.gl#2431]
I have a Visualization with two views and I would like a layer to be visible in one of them but not the other. What would be the best way to achieve this?

So far I subclass the Layer which I want to use and override the draw() function so it just returns in case this.context.viewport.id isn't matching the view in which I want the layer to be visible. This seems cumbersome and in fact it doesn't work for composite layers.

**Comment by 1chandu** [comment]
@MGraefe you can use deck's `layerFilter` props : https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md

**Comment by MGraefe** [comment]
How did I not see this!? Thank you very much.
