### ISSUE TITLE
Polygon Layer documentation - coordinate specification

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2435]
#### Background 

**Polygon layer coordinate specification**

The documentation for polygon layer specifies the following data format

```
/**
   * Data format:
   * [
   *   {
   *     // Simple polygon (array of coords)
   *     contour: [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
   *     zipcode: 94107,
   *     population: 26599,
   *     area: 6.11
   *   },
   *   {
   *     // Complex polygon with holes (array of coords)
   *     contour: [
   *       [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
   *       [[-122.45, 37.73], [-122.47, 37.76], [-122.47, 37.71], [-122.45, 37.73]]
   *     ],
   *     zipcode: 94107,
   *     population: 26599,
   *     area: 6.11
   *   },
   *   ...
   * ]
   */
```

I've just generated an example which has coordinates in the form of

```
{
  "geometry":{
    "type":"Polygon",
    "coordinates":[
      [
        [-162.96333331843185, 23.963333318432139,-94860.0,1.0],
        [-162.89693422519478, 23.963333318432139,-95135.0,1.0]
        ... etc
     ]
   ]
}
}
```

Where the elevation is specified as the 3rd value in each coordinate array (as per GeoJSON). 

Which gives 

![quadmesh](https://user-images.githubusercontent.com/18344164/48512983-cca32e80-e8ae-11e8-9107-c380925cf861.gif)

Should the documentation reflect that you can specify the elevation in the coordinate array, as well as in the **getElevation** prop?

And is this a valid way to supply the elevation? 

---

[Related issue from my mapdeck library](https://github.com/SymbolixAU/mapdeck/issues/40)

### Update

The same works for `pathLayer` too, where you can specify the elevation in the `coordinates [ ]` array

---

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by SymbolixAU** [comment]
Excellent. 

> Think of z values in the polygon array the "base" elevation and getElevation the amount of extrusion.

This is a key point of clarification and would be useful in the docs.

**Comment by SymbolixAU** [comment]
@mdsumner I had the same question - hopefully this helps

Setting up some data (in R)

```r
poly1<- matrix(c(0,0,0,0,1,1000,1,1,50000,1,0,25000,0,0,0), ncol = 3, byrow = T)
poly2<- matrix(c(0,0,0,0,-1,1000,-1,-1,50000,-1,0,25000,0,0,0), ncol = 3, byrow = T)

poly1 <- sf::st_sfc( sf::st_polygon( x = list( poly1 ) ) )
poly2 <- sf::st_sfc( sf::st_polygon( x = list( poly2 ) ) )

poly1 <- sf::st_sf( geometry = poly1 )
poly2 <- sf::st_sf( geometry = poly2 )

sf <- rbind( poly1, poly2 )
sf$id <- 1:2
```

The polygons have a Z attribute. I'm making two plots, one using the `extrusion`, and one without

### Non-extruded

Just using the `Z` attribute on the data

```r
mapdeck() %>%
	add_polygon(
		data = sf
		, fill_colour = "id"
	)
```

![polygon_non_extruded](https://user-images.githubusercontent.com/18344164/49047015-4251b780-f22a-11e8-8a94-a41860209254.gif)

### Extruded

uses `getElevation` to extrude the polygon from the map

```r
mapdeck() %>%
	add_polygon(
		data = sf
		, elevation = 100000
		, fill_colour = "id"
	)
```
![polygon_extruded](https://user-images.githubusercontent.com/18344164/49047032-4e3d7980-f22a-11e8-9053-4c242dee986c.gif)

**Comment by mdsumner** [comment]
Thanks!  (nice!!!)

Those top-faces do look like implicitly triangulated quads to me, see how it's kind of saddle-looking? I bet there's an earcut triangulation going on, I'll try with more complex polys

**Comment by Pessimistress** [comment]
> This is a key point of clarification and would be useful in the docs.

@SymbolixAU May the documentation use the lovely example image in your original issue?

**Comment by SymbolixAU** [comment]
@Pessimistress of course it can. Would you like me to send a higher-res version, or are you happy grabbing the gif directly from the original post?

(@mdsumner - assuming this is OK with you as it's your example originally)

**Comment by mdsumner** [comment]
No problem!

**Comment by Pessimistress** [comment]
Docs updated http://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer
