### ISSUE TITLE
H3 layer support?

### ISSUE THREAD

**Issue by dcj** [uber/deck.gl#2443]
Learned a lot more about [H3](https://uber.github.io/h3/) yesterday at the [Uber Open Summit](https://uberopen2018.splashthat.com), it would "sure be nice" :-) if there was H3 layer/support in deck.gl

Some background on my application is described in issue #2428,  two near-term applications of an H3 layer for me include:

- Compute/measure aircraft noise on an H3 grid, and visualize/present these results via deck.gl.  These  predictions/simulations, and/or aggregated measurements, are computationally intensive, and would most likely be pre-computed in the back end, per H3 index. 
- Compute maximum frequency and/or total count of aircraft over an H3 grid, again, per H3 index.

In both use-cases above, my dataset for these layers would (conceptually) be a list of objects, each object containing the H3 index, and various key/values to display.

**Comment by thomasgwatson** [comment]
At the moment, seems like the easiest way to achieve this is using geosjon2h3 to port H3 keys into polygons

Live/editable demo here:
https://beta.observablehq.com/@nrabinowitz/h3-tutorial-heatmap-rendering

**Comment by ericsoco** [comment]
@ibgreen, @nrabinowitz, and I [talked about the possibility](https://github.com/uber/kepler.gl/pull/198#issuecomment-414449753) of bringing the Kepler H3 layer into a deck.gl experimental layer. Not sure if this is currently on the roadmap, but I imagine a PR would be welcome :)

**Comment by ibgreen** [comment]
@ericsoco Just last week I started working on a PR for adding an experimental `h3-layers` layer catalog module to deck.gl

My work is based on our internal H3 layers (3 layers), and perhaps that PR can be aligned with the kepler.gl H3 layer.

I'll try to clean up and push my PR so that we can discuss/collaborate on the branch.

**Comment by ibgreen** [comment]
h3-layers PR is up: #2620

**Comment by bbss** [comment]
We (@dcj and me) are very interested to start using h3 in our deck.gl project and have tried to build/use the h3-layers feature branch locally. We're running into a couple of issues with JS dependencies (h3-js).

It seems this is to be expected as the step
`> * Update H3 and geojson2hex to open source version` is still in progress.

Is there some way to figure out which parts are missing from the layers (internal h3-transitional has equivalents on h3-js?) so we can start testing out this layer?

**Comment by dcj** [comment]
Just "FYI", since @bbss and I have been stymied in trying to use the (in-progress) h3-layer stuff with deck.gl, I finally broke down and tried loading some of my data into Kepler.gl, the good news is that I eventually succeeded, and was able to confirm/visualize that my H3 processing is on the right track...

**Comment by ibgreen** [comment]
@bbss @dcj 

> It seems this is to be expected as the step
> * Update H3 and geojson2hex to open source version is still in progress.

> Is there some way to figure out which parts are missing from the layers (internal h3-transitional has equivalents on h3-js?) so we can start testing out this layer?

Hi, yes I did an initial push on getting our internal H3 layers into open source. The next step is indeed to replace the use of the internal `h3-transitional` lib to the open source `h3-js` lib.

The APIs are supposed to be almost identical, so it is probably a very easy task to get it working. 

Unfortunately I ran out of time on this, but if you were to try to put up a PR, I would make sure we support you if you run into issues with the port.

As you say, you may even be able to peek into the kepler.gl code base to see how the open source H3 lib is used there.

CC:ing H3 folks @nrabinowitz @isaacbrodsky and deck.gl @xintongxia
