### ISSUE TITLE
OrthographicView zoom is reversed

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2447]
#### Actual Result
When zooming in, `zoom` value decreases

#### Expected Result
When zooming in, `zoom` value increases

#### Reproduce Steps

https://codepen.io/Pessimistress/pen/RqZJEg

zoom in/out and watch the zoom value.

#### To Do List
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
@javidhsueh @gnavvy Is this something by design?

**Comment by javidhsueh** [comment]
> The issue is here: https://github.com/uber/deck.gl/blob/master/modules/core/src/views/orthographic-view.js#L33
> 
> When zoom level is higher, the camera should be looking at a smaller bounding box, not larger.

Does it mean we should do:
```
      left = (-width / 2 + offset[0]) / zoom, // Left bound of the frustum
      top = (-height / 2 + offset[1]) / zoom, // Top bound of the frustum
      right = (width / 2 + offset[0]) / zoom, // Right bound of the frustum
      bottom = (height / 2 + offset[1]) / zoom, // Bottom bound of the frustum
```

**Comment by Pessimistress** [comment]
Essentially yes.
A separate alignment issue is that if we follow the naming convention of the MapController, `zoom` is logarithmic and `scale = Math.pow(2, zoom)`.
