### ISSUE TITLE
@deck.gl/experimental-layers can't be loaded in Observable

### ISSUE THREAD

**Issue by mojodna** [uber/deck.gl#2456]
#### Actual Result

```javascript
require('@deck.gl/experimental-layers@6.3.0') // => undefined
// Error: invalid module
// index.js:3 Uncaught ReferenceError: exports is not defined
//     at index.js:3
```

(`index.js` is `dist/es5/index.js`)

Recommended strategy (given current packaging), per https://beta.observablehq.com/@tmcw/module-require-debugger:

```javascript
// window._outline, etc.
require('@deck.gl/experimental-layers@6.3.0/dist/es5/index.js').catch(() => window._outline) // => undefined
```

It seems to be a weird interaction with globals (specifically `exports`) + https://github.com/d3/d3-require

#### Expected Result

Object containing experimental layers.

#### Code Example

https://beta.observablehq.com/@mojodna/deck-gl-experimental-layers

**Comment by ericsoco** [comment]
👋 Seth!
@Pessimistress may be able to help you with this one.

**Comment by Pessimistress** [comment]
To support d3-require, essentially we'll have to bundle all dependencies of experimental-layers with the distribution. This is not something in our current plan. May I ask which layer you are trying to use?

**Comment by mojodna** [comment]
The bundle.run approach has worked pretty well in the past, as that handles bundling dependencies. There's something about the current packaging that it doesn't like, though. 

My primary interest is in the TileLayer, since I produce a lot of tiled datasets that would otherwise be too large as individual GeoJSON.

**Comment by Pessimistress** [comment]
We're planning to graduate TileLayer in v7.0

Observable's error message doesn't tell me what needs to be done with the current distribution to make bundle.run work. The way we bundle deck.gl for standalone usage is somewhat hacky, and I'm hesitant to apply it to experimental APIs that we don't have enough bandwidth to support. On the other hand, if it's a simple change in packaging and will consistently work in the future, then I don't see why we won't do it.

I will keep poking - Please send documentations my way if you come cross any.

**Comment by mojodna** [comment]
Awesome, I'll look forward to that. Any idea on the ETA of 7.0 yet?

Meanwhile, I need to migrate this out of a notebook anyway, so all's good. If I do run across something useful, I'll follow up here, since it could help with the other experimental layers.

**Comment by Pessimistress** [comment]
> Any idea on the ETA of 7.0 yet?

We're targeting January right now.
