### ISSUE TITLE
ScatterplotLayer lags during FlyToInterpolator transition

### ISSUE THREAD

**Issue by dnass** [uber/deck.gl#2458]
#### Actual Result

![flyto](https://user-images.githubusercontent.com/12872474/48985487-04dc1580-f0d6-11e8-8259-296074a0dc45.gif)

#### Expected Result

`ScatterplotLayer` should remain in sync with map during `FlyToInterpolator` transition.

#### Reproduce Steps

deck.gl 6.3.0
react-map-gl 4.0.2
`ScatterplotLayer` with ~130k points

The transition sometimes works smoothly, but the lag can be consistently reproduced by turning on CPU throttling in Chrome dev tools. The map and scatterplot always stay synced when zooming/panning by hand, so the issue seems related to the transition.

#### Code Example 
https://codesandbox.io/s/91jzk2yy7y

**Comment by Pessimistress** [comment]
This seems to be React-specific. We set the props in both `Deck` and mapbox in the render method. Mapbox rerenders right away but deck's next rerender lives on its own animation cycle.

**Comment by Pessimistress** [comment]
Fixed in v7+
