### ISSUE TITLE
Bug: TextLayer rendered behind other layers

### ISSUE THREAD

**Issue by schlesingermatthias** [uber/deck.gl#2460]
I have multiple layers that I pass to my DeckGL component. The last of which is a TextLayer.
#### Actual Result
The Scatterplot and GeoJsonLayers that preceed the TextLayer in the layers array overlay the TextLayer. The IconLayer which is also passed in after the ScatterplotLayer and GeoJsonLayer is rendered correctly.
<img width="150" alt="grafik" src="https://user-images.githubusercontent.com/20062071/49021906-f6ecca00-f193-11e8-9ce3-a6989c411aea.png">
#### Expected Result
As the TextLayer is the last item in the Array, it should be rendered on top of all other layers. So the white text should appear in front of the grey dot and the grey lines. 
#### Code Example 
Here's the generation of the layer array passed to the DeckGL component
```
return [
      new ScatterplotLayer({
      id: 'grey-dots',
      data: greyDots,
      getPosition: d => d.geometry.coordinates,
      getRadius: 20,
    }),
    new GeoJsonLayer({
      id: 'lines',
      data: lines
      getLineColor: [129, 134, 145],
    }),
      new IconLayer({
        id: 'icon',
        data: markerPoints,
        wrapLongitude: true,
        getIcon: d => 'marker',
        getPosition: d => d.geometry.coordinates,
        getColor: d => getColor(d),
        getSize: d => 5,
        iconAtlas: '/icon-atlas.png',
        iconMapping: {
          marker: {
            x: 0,
            y: 0,
            width: 128,
            height: 128,
            anchorY: 128,
            mask: true,
          },
        },
      }),
      new TextLayer({
        id: 'icon-texts',
        data: texts,
        getText: d => `My Text`,
        getPosition: d => d.geometry.coordinates,
        getColor: d => [256, 256, 256], 
        getSize: d => 20,
        sizeScale: 1,
        getPixelOffset: [0, 15],
      }),
    ];
```

Is there a bug or am I doing something wrong?

**Comment by 1chandu** [comment]
@schlesingermatthias , layers are rendered using `Array.forEach` or `lyaers` array prop : https://github.com/uber/deck.gl/blob/fb5e72485669ac745f41fa4987ddfae656094394/modules/core/src/lib/draw-layers.js#L210

1. Can you verify the order of layers in above line with your example.
2. Are you changing blend state
3. Are you changing opacity prop on any layers or using any custom shader?

**Comment by schlesingermatthias** [comment]
@1chandu , thanks for your response. Yes I can confirm the correct order. I'm not changing the blend state or opacity prop and am also not using any custom shaders. 

Interestingly, if I change the TextLayers pixelOffset to [0,0] so that parts of the text are directly in front of the IconLayer than it works (for those parts, the bottom half of the text is still overlayed by the Scatterplot and GeoJSON Layer)

**Comment by 1chandu** [comment]
Ok, I tried locally with Scatterplot and TextLayer, layers are correctly rendered, i.e. in the order they have provide in `layers` array. (I swapped the order and can see the order changes in final rendering)

Can you provide an image for you above observation with changes to `pixelOffset`.   What ever offset you are providing, will be added to text's screen space position, i.e. by adding an offset you can move your text position in X and/or Y direction, but it shouldn't change the depth order. I am also assuming you are on latest version, 6.3.0 or using `master` ?

**Comment by 1chandu** [comment]
Also I would recommend, isolate the problem to just two layers, TextLayer + another layer, that would provide details if this due to interaction with any other layer.

**Comment by ibgreen** [comment]
Maybe [disable depth testing](https://deck.gl/#/documentation/overview/frequently-asked-questions?section=layer-pixels-render-randomly-on-top-of-each-other) for the text layer, or add a small Z offset?

**Comment by tgorkin** [comment]
Closing issue, please re-open if necessary and provide more details to help isolate the issue.
