### ISSUE TITLE
@deck.gl/mapbox depends on mapbox css

### ISSUE THREAD

**Issue by darionco** [uber/deck.gl#2461]
#### Explanation
I am building an app that needs to be injected in an arbitrary page, meaning I have no control over how the page is constructed and can't guarantee that I'll be able to inject mapbox-gl's CSS code. When the CSS in not in the page inserting a deck gl layer sets the wrong size for the canvas and causes visual artifacts.

#### Actual Result
deck.gl resizes the canvas and gl contexts causing visual bugs:
- the rendered map ends up outside the div assigned to it (it should be rendered where the red rectangle is)
- the data on the deck.gl layer is not rendered at the correct location
- a scroll bar is added
<img width="722" alt="screen shot 2018-11-26 at 10 07 13 am" src="https://user-images.githubusercontent.com/2651846/49022531-15869d00-f163-11e8-9f35-1f415f6809d5.png">

#### Expected Result
deck.gl respects the boundaries and size set by mapbox-gl and renders data at the correct location:
<img width="721" alt="screen shot 2018-11-26 at 10 01 32 am" src="https://user-images.githubusercontent.com/2651846/49022596-3a7b1000-f163-11e8-9aa5-edd7a52aab7e.png">

#### Reproduce Steps
1. Create HTML that has a div where the map should be rendered that is NOT the full size of the viewport
2. Import mapbox-gl and deck.gl but NOT mapbox's CSS
3. Create and insert a deck.gl `MapboxLayer`

The issue can be fixed by either importing `getDeckInstance` and passing a custom deck instance to the layer:
```
const deck = getDeckInstance({
    map,
    gl: map.painter.context.gl,
});
deck.setProps({
    autoResizeDrawingBuffer: false,
    width: false,
    height: false,
});
const myDeckLayer = new MapboxLayer({
    id: 'my-scatterplot',
    type: ScatterplotLayer,
    data: [
        {position: [-95.712891, 37.090240], size: 100000}
    ],
    getPosition: d => d.position,
    getRadius: d => d.size,
    getColor: [255, 0, 0],
    deck,
});
```
or setting the deck instance properties right after the layer has been added to the map:
```
map.addLayer(myDeckLayer);
myDeckLayer.deck.setProps({
    autoResizeDrawingBuffer: false,
    width: false,
    height: false,
});
```
either way seems hacky though.

#### Code Example 
https://codepen.io/anon/pen/oQMXQe

**Comment by Pessimistress** [comment]
A fix is published in 6.3.1
