### ISSUE TITLE
TripsLayer: Adding interactivity or pickable functionality

### ISSUE THREAD

**Issue by arthurakay** [uber/deck.gl#2467]
I realize that `TripsLayer` is currently in the experimental-layers module, but there's not much public discussion that I can find about why, or what the roadmap will be to "gradually collect a suite of strong layers to support trips" (per #2175).

On a whim I tried to add `pickable` functionality to my layer as follows:

            new TripsLayer({
                id: 'trips',
                data: tripData,
                getPath: d => d.segments,
                getColor: d => COLORS[d.category],
                opacity: 0.5,
                strokeWidth: 25,
                trailLength: 1000,
                currentTime,

                pickable: true,
                onHover: info => console.log('Hovered:', info),
                onClick: info => console.log('Clicked:', info)
            })

#### Actual Result

My map and the TripsLayer render fine.

When mousing-over a trip line, I get an error stating `deck: Picked non-existent layer. Is picking buffer corrupt?`

#### Expected Result
My map and the TripsLayer render fine.

When mousing-over a trip line, I was hoping to see some `console.log()` output in my DevTools console.

-----

Clearly the current answer is that "TripsLayer doesn't support pickable functionality". But I'm hoping for two things here:

1. to get an answer on the roadmap for TripsLayer (as mentioned above), and
2. to get some direction on how I might try tackling this problem myself. I'm fairly new to deck.gl and I gather that maybe I could extend TripsLayer to support this somehow? I'm not really sure where to start.

**Comment by 1chandu** [comment]
> When mousing-over a trip line, I get an error stating deck: Picked non-existent layer. Is picking buffer corrupt?

yes, as you mentioned it is due to Trips layer not written to support picking.

> I'm fairly new to deck.gl and I gather that maybe I could extend TripsLayer to support this somehow? I'm not really sure where to start.

You probably need to add , picking filter funciton at the end of the trips layers fragment shader : 
```
gl_FragColor = picking_filterHighlightColor(gl_FragColor);
```

**Comment by arthurakay** [comment]
The deeper I dive into the Deck.gl and Luma.gl internals, it seems like the TripsLayer creates a single Line geometry, then shows/hides portions of that line based on the shader calculations. In that sense I don't know exactly "picking" a visible portion of the line will give me the data I'm after (i.e. it's all _one_ line, not separate "pickable" segments). I'm clearly still learning, but I'll give your suggestion a go! Thanks!

**Comment by ibgreen** [comment]
@arthurakay 

> The deeper I dive into the Deck.gl and Luma.gl internals, it seems like the TripsLayer creates a single Line geometry, then shows/hides portions of that line based on the shader calculation

picking uses the same shader as rendering, so it will only pick the currently visible portion (pixels) of the line.

>  In that sense I don't know exactly "picking" a visible portion of the line will give me the data I'm after 

What data are you after, other than the index of the trip in the data array?

**Comment by arthurakay** [comment]
> picking uses the same shader as rendering, so it will only pick the currently visible portion (pixels) of the line. What data are you after, other than the index of the trip in the data array?

If that's the case, that's really all I would need. Thanks for pointing that out! 

For all of the experience I have building web apps, visualizations (and the shaders/math/etc involved) are still very new to me so I'm slowly making sense of it all, but I'm learning a ton!

**Comment by ibgreen** [comment]
Tracked in #2523 (Trip Layer)
