### ISSUE TITLE
Add basic webpack and browserify example

### ISSUE THREAD

**Issue by Apercu** [uber/deck.gl#247]
We need to have a common place to demonstrate basic usage of deck.gl using browserify and webpack, and be able to point directly at the code.

**Comment by ibgreen** [comment]
> From #231 Thanks for working on this. That config did not work - I keep getting regeneratorRuntime is not defined errors at the call var _webglRenderer = require('./webgl-renderer');. I'll post more in ticket #247

@jefffriesen 
FWIW, these are missing babel polyfills. Sounds like you need to add babel-polyfill or babel-runtime to your app.

Also there is a [babel plugin](https://babeljs.io/docs/plugins/transform-runtime/) that includes necessary polyfills in the transpiled code. If deck.gl added that it could make consuming deck.gl a little easier (apps wouldn't have to deal with it), but last time I tried it had issues with wildcard exports.

I opened a separate issue on this #249

**Comment by jefffriesen** [comment]
If we're using https://gist.github.com/tehwalris/606dcc8d8974e4e48740ed204e166bac as a starting point for the webpack example, I think there are some problems with it.

This is from the `worker-loaded` [docs]( https://github.com/webpack/worker-loader/blob/master/README.md#usage):

```js
var MyWorker = require("worker-loader!./file.js");
var worker = new MyWorker();
```

Here is the webpack config:
```js
{
    test: /\.js$/,
    include: path.resolve(__dirname, 'node_modules/webworkify/index.js'),
    loader: 'worker-loader'
},
```
I *think* that webpack is setting up a web worker for every js file in the app?


Regardless, I'm running into other problems with this config. I keep getting this error: 
`Uncaught ReferenceError: regeneratorRuntime is not defined` at 
`var _webglRenderer = require('./webgl-renderer');`


Here is a working webpack config that works with react-map-gl (this is an electron app).
https://gist.github.com/jefffriesen/76e370bd5031c982f8aae7606fa21788

Here is one attempt at getting deck.gl working base on that other gist. They all give `regeneratorRuntime` errors.
https://gist.github.com/jefffriesen/187418ac5b5fd34e34728e22ac98db64

**Comment by Apercu** [comment]
Like @ibgreen said, you just need to import babel-polyfill to get rid of
the regenerator error

**Comment by tehwalris** [comment]
I was already using babel-polyfill for my own modules, so I wasn't aware that deck.gl requires it too. Hopefully that change will be all that's needed.

**Comment by Apercu** [comment]
As long as the `babel-polyfill` import comes before the import of `deck.gl`, you shouldn't have an issue though.

**Comment by jefffriesen** [comment]
@ibgreen @Apercu yup - `babel-polyfill` was it. I should have caught that. I've run into it before and I thought I had set that up with this repo. #249 would be a great addition though. 

Now I have this error: 
```js
Uncaught Error: Cannot create headless WebGL context, headlessGL not available
```

I can't tell if this is deck.gl misconfigured or webpack. I'm just trying to get the most basic layer rendered:
```js
import React, {Component, PropTypes} from 'react'
import MapGL from 'react-map-gl'
import DeckGL from 'deck.gl/react'
import {ScatterplotLayer, Viewport} from 'deck.gl'
const viewport = new Viewport()
const data = []

render() {
  const {viewport} = this.state
  const common = {
    width: 1000,
    height: 1000,
    mapboxApiAccessToken: MAPBOX_TOKEN,
    onChangeViewport: this.onChangeViewport
  }
  const mapProps = {...common, ...viewport}
  return (
    <div style={mapViewportStyles}>
      <MapGL {...mapProps}>
        <DeckGL
          debug
          height={1000}
          width={1600}
          viewport={viewport}
          layers={[new ScatterplotLayer({data})]} />
        {/* ScatterplotOverlay from react-map-gl works */}
        {/* <ScatterplotOverlay
          {...mapProps}
          locations={locations}
          dotRadius={2}
          globalOpacity={1}
          compositeOperation="screen"/> */}
      </MapGL>
    </div>
  )
}
```

**Comment by tehwalris** [comment]
@jefffriesen You should not be using `new Viewport()` directly. Let me quickly create a full working webpack demo.

**Comment by Apercu** [comment]
Please try to limit the noise of this issue with unrelated problems.

@tehwalris I'm currently in the process of doing so, dunno if it's necessary for you to do so in the same time.
