### ISSUE TITLE
fix pickMultipleObjects

### ISSUE THREAD

**Issue by XiaokaiUber** [uber/deck.gl#2478]
#### Actual Result
when pickMultipleObjects is called, it returns an array of same objects. The number of the returned objects is equal to the picking depth
#### Expected Result
it should return the objects at the picking point
#### Reproduce Steps
the bug is only observed in the pathLayer which can be tested in the layer browser exampel
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by lxe** [comment]
Is this backported into @deck.js/layers@6.4.1+ ?

**Comment by XiaokaiUber** [comment]
Please see $2701
