### ISSUE TITLE
Inconsistent types of controller prop

### ISSUE THREAD

**Issue by vnugent** [uber/deck.gl#2482]
Release 6.3 branch
In geojson example [1] `controller` prop is a boolean but according to API docs [2] prop is a MapController

[1] https://github.com/uber/deck.gl/blob/6.3-release/examples/website/geojson/app.js#L113
```
    const {viewState, controller = true, baseMap = true} = this.props;
    return (
      <DeckGL
        layers={this._renderLayers()}
        initialViewState={INITIAL_VIEW_STATE}
        viewState={viewState}
        controller={controller}
      >
     ...
```

[2] https://github.com/uber/deck.gl/blob/6.3-release/docs/api-reference/map-controller.md
```
import DeckGL, {MapController} from 'deck.gl';

<DeckGL
controller={{type: MapController, dragRotate: false}}   // <---
viewState={viewState}
onViewportChange={v => this.setState({viewport: v})}
/>
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
This prop is currently documented in
https://github.com/uber/deck.gl/blob/6.3-release/docs/api-reference/view.md#controller-function--boolean--object, but not in the Deck class doc.

**Comment by vnugent** [comment]
Thanks.  Coming from OOP this will take a bit to get used to `controller (Function | Boolean | Object)` :)
