### ISSUE TITLE
Need guideline / examples to move Camera View along the map street

### ISSUE THREAD

**Issue by tkt028** [uber/deck.gl#2485]
#### Background 
In my application, I want to move the Camera View along the map street as the car is driving. Is there any guideline / hint / example to do this? Thanks!

**Comment by Pessimistress** [comment]
You can try using [FirstPersonView](http://deck.gl/#/documentation/deckgl-api-reference/views/first-person-view) with Deck's `views` prop.

**Comment by hajimezhao** [comment]
Hi @Pessimistress ,
Thank you very much for the hint. I will give it a try.  :)

**Comment by tkt028** [comment]
Hi @Pessimistress,
I am trying to make the FirstPersonView (as you suggested) to move from point A to B (with hard-coded value coordinate) for below example [1].
I tried to replace the OrbitView (used in the example) with FirstPersonView with different parameters. I also tried to find out how the FirstPersonView is used in the existing code base (both from tests and examples). However, due to my limited knowledge of DeckGL and 3D know-how, it doesn't work.
 
I am really grateful if you can provide sample code that works for [1] with above requirement. Thank you very much!

Have a nice day,
Cheers,
Khon

[1] http://deck.gl/#/examples/core-layers/point-cloud-layer

**Comment by tkt028** [comment]
I close this issue. Because I moved to threejs and found solution there. Thank you!
