### ISSUE TITLE
Use transform-runtime - so that apps don't need babel-polyfill

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#249]
There is a [babel plugin](https://babeljs.io/docs/plugins/transform-runtime/) that includes necessary polyfills in the transpiled code. If deck.gl added that it could make consuming deck.gl a little easier (apps wouldn't have to deal with it), but last time I tried it had issues with wildcard exports.

**Comment by Apercu** [comment]
Tried it, but as long as https://github.com/babel/babel/issues/2877 is not fixed, we can't do much more than tell people they need to include their own polyfill.

**Comment by ibgreen** [comment]
Next release (dev branch) is moving to buble compiler which doesn't require the polyfill.

Note that luma also needs to migrate to completely remove the need for babel-polyfill.
