### ISSUE TITLE
firefox rendering issues with lines

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#2497]
#### Actual Result

Flickering as you zoom in.

![kapture 2018-12-11 at 15 52 05](https://user-images.githubusercontent.com/425716/49829702-11f73680-fd5d-11e8-8591-67689f621465.gif)
![kapture 2018-12-11 at 15 46 10](https://user-images.githubusercontent.com/425716/49829345-36064800-fd5c-11e8-9279-0af37a2f6115.gif)

```
deck: deck.gl 6.3.1 - set deck.log.priority=1 (or higher) to trace attribute updates init.js:39:2
luma: luma.gl 6.3.1 - set luma.log.priority=1 (or higher) to trace rendering init.js:23:4
luma.gl: WebGL debug support imported debug.js:9
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. index.js:152:12
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. supported.js:22:15
deck: t.componentName not specified create-props.js:213:4
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. create-browser-context.js:20:15
luma: WebGL2 context (ATI Technologies Inc.,AMD Radeon Pro 560 OpenGL Engine) context.js:191:2
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. index.js:152:12
react-map-gl: 4.0.4 using mapbox-gl v0.51.0 mapbox.js:181:6
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. map.js:1501:19
luma: Found instanced attributes on non-instanced model transform-model model.js:335:6
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:71:16
Error: WebGL warning: checkFramebufferStatus: This operation requires zeroing texture data. This is slow. framebuffer.js:232:19
Error: WebGL warning: clear: This operation requires zeroing texture data. This is slow. draw-layers.js:59:4
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
```

#### Expected Result

No flickering.

#### Reproduce Steps

- Open http://deck.gl/#/examples/core-layers/geojson-layer-paths in Firefox latest (64.0)

#### To Do List
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by contra** [comment]
![screen shot 2018-12-11 at 3 57 48 pm](https://user-images.githubusercontent.com/425716/49829851-87fb9d80-fd5d-11e8-87b0-ccd4b9185562.png)

Can also reproduce this using the hex layer w/ a small radius.

**Comment by 1chandu** [comment]
Tested on my machine , works fine with Firefox 61.0.2 (64-bit) + AMD Radeon Pro 560X, upgraded my Firefox to 64.0 still works fine.

Is this a regression , was this working for you with previous versions of Firefox, how about Chrome, does it work fine.

**Comment by contra** [comment]
@1chandu Chrome works fine.

For reference:

<img width="234" alt="screen shot 2018-12-12 at 1 34 12 pm" src="https://user-images.githubusercontent.com/425716/49890663-a2dc1980-fe12-11e8-8ce7-5315b82d3344.png">

I just did a side by side and it is slightly better (but not really) if tested on a retina screen.

**Comment by Pessimistress** [comment]
The visual artifact is due to antialiasing being disabled. In your log:

```
getContext: Disallowing antialiased backbuffers due to blacklisting
```

Not sure if this is caused by the latest release of FF or your machine.

**Comment by contra** [comment]
@Pessimistress Is anti-aliasing requested? That message is always printed, if asked for or not (reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1285937)

**Comment by Pessimistress** [comment]
It is not required, but if it's disabled you get the above visual quality.
