### ISSUE TITLE
Plot Great Circle on Deck.Gl?

### ISSUE THREAD

**Issue by gpism** [uber/deck.gl#2499]
How to Plot great circle on deck.gl between two points on map?

**Comment by gpism** [comment]
why its closed ? Can please give some pointers how to draw great circle will do it my self

**Comment by Pessimistress** [comment]
This one is not closed. You opened two issues with the same content.

The arc calculation is done in this function: https://github.com/uber/deck.gl/blob/master/modules/layers/src/arc-layer/arc-layer-vertex.glsl.js#L66

Right now it just interpolate between source and target positions linearly. You can replace it with any custom calculation. You can find out how to subclass the ArcLayer by overriding its shaders [here](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/subclassed-layers?section=overriding-shaders).

**Comment by dcooley** [comment]
I've made a `GreatCircleLayer` using v7.0.0-beta` using these coordinates

```js
[{"from_lon":140.0,"from_lat":50.0,"to_lon":-140.0,"to_lat":50.0}] 
```

and the result is 

![Screen Shot 2019-03-31 at 1 27 27 pm](https://user-images.githubusercontent.com/8093396/55283958-cc688300-53b8-11e9-8b30-41ba0a6ff81b.png)

Do you plan on handling cases where the circles crosses the international date line?

Thanks,

**Comment by ibgreen** [comment]
> Do you plan on handling cases where the circles crosses the international date line?

@dcooley See [`Layer.wrapLongitude`](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=wraplongitude-boolean-optional-)
