### ISSUE TITLE
Render Tests: test script should pause on failed test

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2504]
#### Actual Result
Test script doesn't stop on failed test case.
#### Expected Result
should stop on failed test case to allow view/save failed image.
#### Reproduce Steps
Run render tests (inroduce a failure in one of the unit tests)

CC: @javidhsueh 

<img width="1312" alt="screen shot 2018-12-14 at 10 09 16 am" src="https://user-images.githubusercontent.com/9502731/50019799-d6d94b00-ff88-11e8-96ec-7b80abc641c8.png">

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
This is no longer valid since we replaced the old render test harness.
