### ISSUE TITLE
Is there any way to use static base layers like OpenStreetMap tiles with Deck.GL?

### ISSUE THREAD

**Issue by hyzhak** [uber/deck.gl#2507]
Open Street Map provides tiles on that api:

```https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png```

How could I use static base layers of Open Street Map in Deck.gl?

**Comment by Pessimistress** [comment]
Yes, by using the experimental [TileLayer](https://github.com/uber/deck.gl/tree/master/modules/experimental-layers/src/tile-layer) with the [BitmapLayer](https://github.com/uber/deck.gl/tree/master/modules/experimental-layers/src/bitmap-layer). Unfortunately the latter is a little outdated and lacks documentation. We're planning to refresh it for v7.0, and then I can put together an example for your use case. Is this blocking you right now?

**Comment by hyzhak** [comment]
Big thanks for reply! Yes, I'm working on open source project, and I can't use deck.gl, because it requires MapBox. It would be great to have examples, as starting point. But thanks for mentioned experimental layers, I haven't seen them.

**Comment by Pessimistress** [comment]
Well, technically, deck.gl does require mapbox. There are [examples without map](https://github.com/uber/deck.gl/tree/master/examples/get-started) and also [prototypes](https://github.com/uber/deck.gl/pull/2179) working with Google Maps. 

Also, a paid service is not required to use mapbox-gl. You can use OSM raster layers with mapbox ([info](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources)) or use alternative vector tile service providers ([info](https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens)).

**Comment by jalMogo** [comment]
First, I want to say thanks for sharing this project!

I came across this PR, which seems to document how to load a raster source like `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png`:

https://github.com/uber/deck.gl/pull/2821/files#diff-4f90d4e6ab9c03e5819086ec5ac1848a

and that PR adds an `openstreet-map` directory to the `examples/website` directory here:
https://github.com/uber/deck.gl/tree/master/examples/website

but I see that it's no longer there. And there is no mention of loading raster tile sources in the [TileLayer docs](https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer) or the [BitmapLayer docs](https://deck.gl/#/documentation/deckgl-api-reference/layers/bitmap-layer).

Is this use case supported? If so, is there any documentation or example of it?

**Comment by xintongxia** [comment]
@jalMogo 
The example is renamed and moved to [here](https://github.com/uber/deck.gl/tree/master/examples/website/map-tile)

Also it is under the `examples` category on the [website](https://deck.gl/#/examples/core-layers/tile-layer)

**Comment by HeiYanjing** [comment]
@hyzhak Have you ever been load tile layer published by youself.
I tried load a building layer published by geoserver. #3329, could you help me have a look.

**Comment by RaedsLab** [comment]
@XiaokaiUber thank you very much for this example it is a life saver 🙏 ! 

On an unrelated question, do you know if there is a way to style the openstreetmap example?

Maybe with something like `maptiler` ? 

The following MAP doesn't look too pretty :D 

![Screenshot 2020-11-01 at 12 20 12](https://user-images.githubusercontent.com/1442690/97801384-9ea28a80-1c3c-11eb-9554-c617279404ec.png)
