### ISSUE TITLE
Demo bugs. /examples/core-layers/screen-grid-layer

### ISSUE THREAD

**Issue by caffeine-potent** [uber/deck.gl#2511]
#### Actual Result
Blank map shows up when I visit:   
http://deck.gl/#/examples/core-layers/screen-grid-layer

#### Expected Result

Map is populated with markers.   
#### Reproduce Steps
Visit http://deck.gl/#/examples/core-layers/screen-grid-layer with chrome.

**Comment by 1chandu** [comment]
@caffeine-potent , this demo works fine on our end, can you share the log from your browser console window. Do you see any crash? Does other demos work fine?
