### ISSUE TITLE
Addlayer's second parameter(before) lead to error when use MapboxLayer

### ISSUE THREAD

**Issue by Leesson** [uber/deck.gl#2525]
#### Actual Result
deckgl MapboxLayer always display on top of map and covers all layers even thouth I set it before other layer

#### Expected Result
mapbox layer display in the right index on map
#### Code Example 
```js
const deck = new Deck({
    gl: map.painter.context.gl,
    layers: [
        new ScatterplotLayer({
            id: 'my-scatterplot',
            data: [
                {position: [-74.5, 40], size: 100}
            ],
            getPosition: d => d.position,
            getRadius: d => d.size,
            getColor: [255, 0, 0]
        })
    ]
});

// add to mapbox
map.addLayer(new MapboxLayer({id: 'my-scatterplot', deck}), 'otherLayerId');

// update the layer
deck.setProps({
    layers: [
        new ScatterplotLayer({
            id: 'my-scatterplot',
            data: [
                {position: [-74.5, 40], size: 100}
            ],
            getPosition: d => d.position,
            getRadius: d => d.size,
            getColor: [0, 0, 255]
        })
    ]
});
```
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by Pessimistress** [comment]
Are you sure that `otherLayerId` exist in your mapbox style? Mapbox seems to silently fail if the id is not found.

**Comment by Leesson** [comment]
Yes, and I checked out [this example](https://github.com/uber/deck.gl/blob/6.3-release/test/apps/mapbox-layers/app.js), the only difference I found is the `otherLayer` is not symbol layer in my case.

**Comment by Leesson** [comment]
Resolved this problem use the example referred upstairs.

> Yes, and I checked out [this example](https://github.com/uber/deck.gl/blob/6.3-release/test/apps/mapbox-layers/app.js), a difference I found is the `otherLayer` is not symbol layer in my case.

The code in [documentation](http://deck.gl/#/documentation/mapbox-api-reference-experimental/mapbox-layer?section=use-a-layer-from-an-existing-deck-s-layer-stack) is out date. follow this: 

```js
const deckPoiLayer = {
  id: 'deckgl-scatter',
  type: ScatterplotLayer,
  data,
  pickable: true,
  autoHighlight: true,
  radiusMinPixels: 0.25,
  getPosition: d => d.coordinates,
  getColor: [255, 180],
  getRadius: 10
}
map.addLayer(new MapboxLayer(deckPoiLayer), otherLayerId);
```
And update layer: 
```js
map.getLayer('deckgl-scatter').implementation.setProps({
   data,
});
```
But thrown an error when I called `map.getLayer('deckgl-scatter').implementation.deck.finalize()`

![image](https://user-images.githubusercontent.com/10245840/50396072-6f01dc00-07a2-11e9-8f53-5c43e7746c12.png)
![image](https://user-images.githubusercontent.com/10245840/50396112-b38d7780-07a2-11e9-88a1-9816db61db87.png)

**Comment by Leesson** [comment]
@Pessimistress Sorry, my code works now and I cannot reproduce it, maybe I was wrong. Sorry for wasting your time again and happy new year.

> I'm confused. Why are you calling finalize?

I am not sure should I call `finalize` to free resources before destroy my map when using MapboxLayer.
