### ISSUE TITLE
Enhancement about hexagonLayer or just basic 3D density layer

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2527]
#### Background 

Currently, deck.gl works well in HexagonLayer to provide an auto-calculation and clustering hexagon form in displaying data in 3D way, however, we may just want to display our data on the map with our defined height, without re-calculation based on our origin dataset, such as density or population which is gathered through some specific units like provinces or countries, etc.

It's a feature simpler than any current provided layer, and many issues had mentioned about this, like #829 #1184 #1852 , etc.

Demo Picture (by mapbox.gl)

![image](https://user-images.githubusercontent.com/4990015/50475284-25fa9380-09ff-11e9-9e03-61dc4b706097.png)

Suppose my raw data consists of points like this:

```
[
	{
		COORDINATES: [lng, lat],
		SPACES: Math.random()*100,
	}, 
	...
]
```

And `HexagonLayer` currently did provide an approach for us to get the result described above. The approach consists of following steps:

* Define `getPosition` method:

```
getPosition: d => d.COORDINATES
```

* Define `getElevationValue` method:

```
getElevationValue: d => d.reduce(
	(accumulator, currentValue) => currentValue ? 
		accumulator + currentValue.SPACES : accumulator, 
	0
),
```

* Define `getColorValue` method (if you need to map color with corresponding height you defined in `getElevationValue`):

```
getColorValue: d => d.reduce(
	(accumulator, currentValue) => currentValue ? 
		accumulator + currentValue.SPACES : accumulator, 
	0
),
```

However, we may need less running memory if deck.gl provides a simple layer for this kind of rendering situation, since there is no more need to keep the cluster structure of the points or re-calculate it when we change `radius` or something properties provided in API docs.

Last, we can use some other geometry in representing our data, or make this an option for developers, such as cylinder.

:-)

**Comment by Pessimistress** [comment]
You may be looking for the HexagonCellLayer https://github.com/uber/deck.gl/blob/master/docs/layers/hexagon-cell-layer.md ?

Under the hood the Hexagonal yet just renders a HexagonCellLayer after aggregation.

**Comment by hijiangtao** [comment]
@Pessimistress Thanks for providing this Layer, and I think put it and other base Layers into documents can be better! I couldn't found this Layer before in http://deck.gl/#/documentation/deckgl-api-reference/layers/hexagon-layer?section=data-accessors so I thought hexagonLayer may directly based on `Layer`.

And for another topic, is there any approach for developers to make a simple cell layer with different rendering shapes rather than only hexagon, like cylinder?

Thanks.

**Comment by Pessimistress** [comment]
You need to extend the HexagonCellLayer for that.

This example:
https://codepen.io/Pessimistress/pen/PXJOKY
Overrides the HexagonCellLayer's [getCylinderGeometry](https://github.com/uber/deck.gl/blob/master/modules/layers/src/hexagon-cell-layer/hexagon-cell-layer.js#L164) method. Specifically [nradial](https://luma.gl/#/documentation/api-reference/model-cylinder) sets the resolution along the disk perimeter. Setting it to `6` was how we make a hexagon.

**Comment by Pessimistress** [comment]
- [ ] Add HexagonCellLayer and GridCellLayer docs to layer catalog

**Comment by hijiangtao** [comment]
@Pessimistress 
Thanks very much, I think it's the result that I want in the beginning! 
I think I also need to learn more about how to combine extending CellLayer with DeckGL, but it's already clear on how to do that.
I'll try it later, thanks for your example code!

**Comment by hijiangtao** [comment]
@Pessimistress As mentioned in PR #2536 HexagonCellLayer is introduced in documents, however I couldn't find it in latest API documents. Does that mean this API is deprecated now? However, I also couldn't find that it's abandoned from CHANGELOG.

**Comment by Pessimistress** [comment]
It is replaced by a more generic `ColumnLayer` in v7.0:

https://deck.gl/#/documentation/overview/upgrade-guide

**Comment by hijiangtao** [comment]
Thanks.
