### ISSUE TITLE
Calculating mean in ScreenGridLayer

### ISSUE THREAD

**Issue by mkrkelj1** [uber/deck.gl#2541]
Are we able to calculate mean/min/max w/ the public API via passing in props or some other method? This features appears to have been added and tested: [Issue: 2291](https://github.com/uber/deck.gl/issues/2291) , but I am having trouble locating documentation.

**Comment by tgorkin** [comment]
It looks like the GPUAggregator class has been improved in v6.3 to support mean/min/max, but the system is still experimental and the new functionality has not yet been exposed all the way up to the ScreenGridLayer API.  Hopefully we'll get to those changes soon.  If you wanted to start tinkering with the new functionality directly at the GPUAggregator level, or even helping to flush out the implementation at the ScreenGridLayer level, there are some docs here: https://github.com/uber/deck.gl/blob/master/modules/core/src/experimental/utils/gpu-grid-aggregation/gpu-grid-aggregator.md.

**Comment by 1chandu** [comment]
Thanks @tgorkin 

Yes, we will be exposing these with Grid and ScreenGrid aggregation layers soon, but happy to look into any PRs as well.

**Comment by 1chandu** [comment]
This will be supported as **Experimental** feature in 7.0, #2560

**Comment by tgorkin** [comment]
Fixed in master and release-6.4 branch.  Will be published to npm with 6.4 release.
