### ISSUE TITLE
autoHighlight not working properly in safari

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#2550]
#### Actual Result

![kapture 2019-01-07 at 16 08 51](https://user-images.githubusercontent.com/425716/50793566-a1c5cd00-1296-11e9-967b-e0867b20505d.gif)

Issue persists across all layer types tested so far (GeoJSON, Hexagon). Hover events are working fine (powering the tooltip visible in the GIF).

#### Expected Result

Color change when hovered.

#### Reproduce Steps

- deck.gl 6.3.3 (latest)
- Safari 12.0.1 (latest)

Use `autoHighlight: true` on any layer, then open in Safari.

#### Code Example

Should be able to easily reproduce here -

https://share.staging.municipal.systems/z7SVwNuGkl

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
I was able to reproduce this issue on Safari after several attempts, and it only happens when I move my  mouse faster and it happens **only** on Safari,  no issue on chrome.
It seems like some of the mouse move events are ignored, need to be debugged.

**Comment by tsherif** [comment]
@contra Could you check if offsetting the tooltip from the mouse by a few pixels helps? I'm wondering if it's picking up the mouse events.

**Comment by contra** [comment]
@tsherif The tooltip has `pointer-events: none` so should't pick up any events (unless safari is horribly bugged)
