### ISSUE TITLE
Is there a more efficient way to implement animation for point/circle(ScatterplotLayer)?

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2555]
Hi, there. I am looking for an approach to implement the animation for points/circles in ScatterplotLayer.

What I want the map shows is circles can spread(animate) in ScatterplotLayer with time and disappear at some specific time, just like the waves raised by throwing a stone into rivers.

![image](https://user-images.githubusercontent.com/4990015/50837096-c359ae00-1395-11e9-8f62-9debd54ff416.png)

At each moment, the map is just like a ScatterplotLayer as usual, but the ScatterplotLayer will change by the time. Currently, I can implement it by passing different radius property to `ScatterplotLayer`, but I don't think it is a ideal way to do that.

Any advice on that? Thanks very  much!

**Comment by Pessimistress** [comment]
You can animate the `radiusScale` prop from `0` to `1` - it has virtually zero cost.

If you need to control animation per-object, you can do one of the following:

- Use the [transitions](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer) prop. Note this is WebGL2 only/.
- [Extend](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/subclassed-layers) the ScatterplotLayer. This is a little more work but will give you the most cross-platform compatible result. The general idea is to
  + add an attribute, say `instanceEntryTime`, set by a new accessor `getEntryTime`
  + add a `currentTime` uniform, set by a new prop `currentTime`
  + in the vertex shader, replace `radiusScale` in this line: https://github.com/uber/deck.gl/blob/6.3-release/modules/layers/src/scatterplot-layer/scatterplot-layer-vertex.glsl.js#L46 to `step(currentTime, instanceEntryTime)`
  + in your app, animate the `currentTime` prop of your layer

**Comment by hijiangtao** [comment]
The third method seems complex for me right now, so I tried the first two methods.

### Point size didn't change when I set `radiusMinPixels` to a no-zero value
I have some problems in doing that, for the first method of animate `radiusScale` directly, I change radiusScale dynamic from the state of react component with `requestAnimationFrame` API, and when I print it out I can saw the changes of its value, but sometimes the radius of points didn't get changed as expected. Once I set `radiusMinPixels` to a no-zero value, the `radiusScale` won't work any more (and the point will stay the same size all the time, but the color will change normally as time goes by), should I set `radiusMinPixels` to 0 all the time? (I may want to let the point change from a no-zero radius)

```
// codes in `_renderLayers` function
const {radiusScale} = this.state;
console.log(radiusScale);

    return [
      new ScatterplotLayer({
        id: 'scatterplot-fade',
        data: accData,
        pickable: true,
        opacity: 0.8,
        radiusScale,
        radiusMinPixels: 0,
        radiusMaxPixels: 160,
        getPosition: d => d.COORDINATES,
        getRadius: () => 14000,
        getColor: () => [255, 140, 0, 255],
        updateTriggers: {
          getColor: [radiusScale],
        },
      }),
    ];
```

#### How to change point size and specify its color with the help of `transitions`?
And for the second method, which is using `transitions` prop, I found the document is pretty hard for me to understand. I couldn't set initialized color and animate the radius of points with it:

```
// codes in `_renderLayers` function
return [
      new ScatterplotLayer({
        id: 'scatterplot-fade',
        data: accData,
        pickable: true,
        opacity: 0.8,
        // radiusScale,
        radiusMinPixels: 0,
        radiusMaxPixels: 160,
        getPosition: d => d.COORDINATES,
        getRadius: () => 14000,

        transitions: {
          radiusScale: {
            duration: 5000,
            easing: t => t*t*t,
            enter: () => 0,
          },
          getColors: {
            duration: 5000,
            easing: t => t*t*t,
            enter: () => [255, 140, 0, 0], // fade in
          },
        },
      }),
    ];
```

I can just get some black points without any animation (color or radius) in the map:

![image](https://user-images.githubusercontent.com/4990015/50902428-cfa54000-1455-11e9-9938-db5ad22dc895.png)

Is there some concrete examples? I am still confused about how to set `transitions`.

And I will try to get some external articles to help me understand those concepts such as `shaders` you mentioned in the third method, and I will try them later.

Thanks.

**Comment by Pessimistress** [comment]
**Using `requestAnimationFrame`**

You could definitely animate `radiusMaxPixels`. The downside of it is just that you don't know how big the largest circle is, so it might be difficult to control timing.

If your points are mostly smaller than `radiusMinPixels`, you may try animating `radiusMinPixels` too.

**Using `transitions`**

- Your code sample did not have a `getColor` prop, so everything falls back to black. You never told the layer what color you want to transition *to*. "Transition" means going from the current value to some new value, so you need to actually specify the new value. If you are familiar with [CSS transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition) it's a similar idea.
- `radiusScale` does not support transition. Look for "transition enabled" in the [layer documentation](http://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer?section=render-options).
- The key used in transitions should be `getColor` not `getColors`.

**Comment by hijiangtao** [comment]
Thanks for replying, I may wonder what does 「how big the largest circle is」 means, is it the size I returned at `getRadius` property, or something else? 

And can I directly change property value like `radiusMinPixels` to make it animate? It seems when I change `radiusMinPixels` to a no-zero value (the code I only modified, compared with previous normal animation of changing `radiusScale` dynamicly), the animation on `radiusScale` would disappear, which is said the point size will always be the same when I change `radiusScale`.

**Comment by hijiangtao** [comment]
Also, is it possible to `trainsitions` properties like `radiusScale`, which is not a method but a pure variable? I thought it should work since the docs says:

> Animation parameters are defined per attribute by using attribute names or accessor names as keys:

**Comment by hijiangtao** [comment]
@Pessimistress I tried the third approach you mentioned above, but got confused about how to manage Layer's data and state.

It seems you suggest me to use attribute to manage some new properties and methods, however, I found codes using attributes manager is often used for shader, I want to add some other properties to `MyLayer` (the class which extends from ScatterplotLayer), I would got following errors:

> TypeError: can't define property "x": "obj" is not extensible.

It seems deck.gl do have freeze some properties and `Layer`'s internal structure. I look through deck.gl documents and found some concepts like [Attribute Management
](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/attribute-management), [Lifecycle](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/layer-lifecycle) and [Subclassed Layers](http://deck.gl/#/documentation/developer-guide/writing-custom-layers/subclassed-layers), but still not clearly about how to combine them into my code, when I need to subclass an existed Layer with some customized state and props. Maybe some concrete example can help me understand them.

Which way do deck.gl prefer for developers in managing `MyLayer`'s data and state, especially when I want to communicate between parent layer's class with child class (For example, get parent layer's state in child layer & change parent layer's state and trigger child layer update, etc.)?

**Comment by Pessimistress** [comment]
> is it possible to `trainsitions` properties like `radiusScale`

No. In each layer's documentation all transition-enabled props are marked as such.

Regarding subclassing layer: if you need debugging help you need to include your code sample. The error message does not tell us much about what went wrong.

**Comment by claudewg** [comment]
@hijiangtao were you able to resolve your issue with the radius and color enter transitions?

I have a similar set up and can't seem to get any enter transitions to work.

**Comment by hijiangtao** [comment]
@claudewg Yep, I got things work with the help of `CompositeLayer` class (actually update radius dynamically with the help of state manager) and `transitions` props (enable `getColor` change over time with the help of `updateTriggers`).

You may modify the internal shader to get more flexibility on it.

Which approach did you choose to realize the transition effect?

**Comment by hijiangtao** [comment]
Thanks for the help!

**Comment by claudewg** [comment]
@hijiangtao I couldn't get the enter functionality to work so ended up using the component's state to transition to a larger radius on load.

**Comment by hijiangtao** [comment]
As @Pessimistress said, `radiusScale` doesn't support transition, you may check if you used the wrong accessors.

According to documents, I suppose you may get things work by combine `getRadius` and `transitions`.

More information should be given such as your code sample, so that we may locate where is the problem more specifically.

More at

http://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer?section=linewidthminpixels-number-optional-

http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=getpolygonoffset-function-optional-
