### ISSUE TITLE
ScreenGridLayer: picking under WebGL1 not working (Safari)

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2556]
#### Actual Result
Picking not working
#### Expected Result
Picking should work
#### Reproduce Steps
Run ScreenGridLayer in Safari
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by tgorkin** [comment]
Released a fix for this in deck.gl patch release 6.3.4.
