### ISSUE TITLE
Fix pickMultipleObjects for MeshLayer

### ISSUE THREAD

**Issue by jcready** [uber/deck.gl#2563]
#### Actual Result
when pickMultipleObjects is called, it returns an array of same objects. The number of the returned objects is equal to the picking depth
#### Expected Result
it should return the objects at the picking point
#### Reproduce Steps
the bug is observed in the MeshLayer which can be tested in the layer browser example

Related https://github.com/uber/deck.gl/issues/2478

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by XiaokaiUber** [comment]
@jcready I tested pickMultipleObjects for the MeshLayer in the layer browser and it works fine on my end. Can you tell me how you get the error so that I can further investigate the issue? A list of steps of reproducing it and some screenshots will be very helpful.

**Comment by jcready** [comment]
It looks like it doesn't have to do with the MeshLayer, but rather anything sitting on top of a Line layer. This is the layer browser using the master branch checked out today. I have Multi Depth picking on and the picking radius turned up a bit with Scatterplot and Line layers turned on.

![](https://i.imgur.com/QDngH8h.gif)

**Comment by XiaokaiUber** [comment]
@jcready it seems picking does not work properly when the line width is too small. One workaround is to increase the line width.

**Comment by jcready** [comment]
So is the bug due to incorrectly calculating intersections? Because I would assume that by setting the picking radius to a non-zero value then the line width wouldn't matter.

**Comment by XiaokaiUber** [comment]
@jcready If the line is not horizonal or vertical, some pixels on the edge maybe interpolated as you can see in the image which magnifies the line segment. The interpolated color is not the original color which picking is based on. I need to do more tests to verify it.
<img width="76" alt="linelayer" src="https://user-images.githubusercontent.com/42359372/51134030-4bebaa80-17eb-11e9-8b74-a3e281ce0e1e.png">
