### ISSUE TITLE
ScreenGridLayer examples not working on Windows browsers with GPU accelerated aggregation enabled

### ISSUE THREAD

**Issue by danmarshall** [uber/deck.gl#2566]
#### Actual Result
Map is visible without any data visualization.

#### Expected Result
ScreenGridLayer data visualization.

#### Reproduce Steps
http://deck.gl/#/documentation/deckgl-api-reference/layers/screen-grid-layer
http://deck.gl/#/examples/core-layers/screen-grid-layer

Toggle the 'GPU Acceleration' checkbox on to see the issue.  You may need to zoom in/out to get the example to re-render after toggling the checkbox.

**Comment by danmarshall** [comment]
I'm using Windows. And, it *does* work in Edge 🤯😊:
![image](https://user-images.githubusercontent.com/11507384/51052790-9d4a2e80-158c-11e9-905e-40ed9dea34d2.png)

But not in Chrome:
![image](https://user-images.githubusercontent.com/11507384/51052815-b226c200-158c-11e9-90f5-40ea627d445c.png)

I do see 2 warnings in the Chrome console:
```
[.WebGL-000001784325A5F0]RENDER WARNING: Render count or primcount is 0.   /#/examples/core-layers/screen-grid-layer:1
```

**Comment by hijiangtao** [comment]
@danmarshall I do have the warnings you mentioned about, but it didn't interrupt the displaying of demo. I got another warning which is:

> bundle.js:35 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.

But I think it's not the reason, either. I think you may check it out with chrome private mode, maybe some of your chrome extensions prevent assets loading from deck.gl.

**Comment by danmarshall** [comment]
I've tried disabling extensions, still see the issue. 🤔
Also had a coworker try and they can reproduce the issue, in Chrome on windows only.

**Comment by hijiangtao** [comment]
Well then, maybe you can try some other websites which also contains running codes of WebGL2, to see if it's the problem of browser's compatibility on specific platform? 
Currently, I've no idea why could that happen. :-(

**Comment by tgorkin** [comment]
I'm able to reproduce this on Windows and narrow it down to the GPU accelerated aggregation.  The example doesn't render on Windows Chrome and Firefox when the GPU Acceleration option is enabled.  I don't see any errors in the console.  I think the "missing CSS declarations for Mapbox GL JS" warning is unrelated as I see that running other examples that work fine.  Will raise this with the author of the GPU aggregation system, but in the meantime I would suggest disabled GPU accelerated aggregation if you need your app to run on Windows.
