### ISSUE TITLE
Error: shader module fp32 already registered

### ISSUE THREAD

**Issue by MAGilleeney** [uber/deck.gl#2569]
#### Actual Result

Application fails to run. Error: 

Error: shader module fp32 already registered
▼ 5 stack frames were expanded.
ShaderModuleRegistry._registerShaderModule
node_modules/luma.gl/dist/esm/shadertools/src/lib/shader-module-registry.js:105
ShaderModuleRegistry.registerShaderModules
node_modules/luma.gl/dist/esm/shadertools/src/lib/shader-module-registry.js:36
registerShaderModules
node_modules/luma.gl/dist/esm/shadertools/src/lib/resolve-modules.js:23
initializeShaderModules
node_modules/@deck.gl/experimental-layers/node_modules/@deck.gl/core/dist/esm/shaderlib/index.js:27
Module../node_modules/@deck.gl/experimental-layers/node_modules/@deck.gl/core/dist/esm/shaderlib/index.js
node_modules/@deck.gl/experimental-layers/node_modules/@deck.gl/core/dist/esm/shaderlib/index.js:30

#### Expected Result

Application should run

#### Reproduce Steps

I recently upgraded from deck.gl 6.3.0 to deck.gl 6.3.3 and this issue appears as the application runs.

**Comment by MAGilleeney** [comment]
I can confirm that there is only one copy of deck.gl installed. I've narrowed down the issue to the experimental layers 6.3.3. Running these versions appear to work fine: 

"@deck.gl/experimental-layers": "^6.3.0",
"@deck.gl/mapbox": "^6.3.3",
"deck.gl": "^6.3.3"

**Comment by hijiangtao** [comment]
I thought it may be an incompatible bug of specific version of 'deck.gl' with '@deck.gl/experimental-layers'.

I met the same error info when I import `TripLayer` after I upgrade these two packages to the latest version today.

```
import { TripsLayer } from '@deck.gl/experimental-layers';
```

My dependencies' version lists below:

```
deck.gl@6.3.4
@deck.gl/experimental-layers@6.3.4
```

Versions before 6.3.3 runs well (can't confirm the exact version number).

**Comment by Pessimistress** [comment]
Looking closer to your tracestack:

`node_modules/@deck.gl/experimental-layers/node_modules/@deck.gl/core/dist/esm/shaderlib/index.js:27`

This means that your `experimental-layers` module installed its own copy of `@deck.gl/core`.

`npm ls @deck.gl/core` should give you two copies.

This is a known issue in the dependency structure and we have a plan to address this in the next major release (because it will be a breaking change): #2519 . Meanwhile a quick way to fix this is to add this to your package.json:

```json
"resolutions": {
  "@deck.gl/core": "6.3.4"
}
```

@ibgreen

**Comment by rocos-david** [comment]
I got this error when I just updated deck.gl/layers to 6.3.9 as it duplicated /core in layers dependencies.  Resolution was to npm remove deck.gl/layers, update /core and then npm install deck.gl/layers again which then installed /layers without the extra dependency install of /core, it used existing install. Works fine now.

**Comment by ayeganov** [comment]
I've run into the same issue when trying to upgrade to `deck.gl 7.0.0`. `npm ls @deck.gl/core`:
```
├── @deck.gl/core@7.0.0 
└─┬ deck.gl@7.0.0
  └── @deck.gl/core@7.0.0 
```

If I remove `@deck.gl/core` then it does not get installed anywhere, but as soon as I add it then I always get 2 installations. What would be a good way to resolve this?

**Comment by ibgreen** [comment]
You'd get the most control over dependencies by no longer importing the `deck.gl` module and migrate your code to only use the scoped modules (such as `@deck.gl/core`, `@deck.gl/react` etc).

**Comment by ayeganov** [comment]
@ibgreen thank you, after breaking up the dependencies the issue was resolved.

**Comment by robert-claypool** [comment]
I spent an hour trying various combos of top-level dependencies before realizing `npm dedupe` exists.
