### ISSUE TITLE
No matching version found for deck.gl@^6.4.0

### ISSUE THREAD

**Issue by Ash-sc** [uber/deck.gl#2579]
Hi,

I got an error when running 'npm install' at folder 'examples/website/3d-heatmap/' in branch '6.4-release'.

#### Repro Steps
git checkout 6.4-release   
cd examples/website/3d-heatmap/   
npm install   

The log shows the following output:   

npm ERR! code ETARGET   
npm ERR! notarget No matching version found for deck.gl@^6.4.0   
npm ERR! notarget In most cases you or one of your dependencies are requesting   
npm ERR! notarget a package version that doesn't exist.   
npm ERR! notarget   
npm ERR! notarget It was specified as a dependency of '3d-heatmap'   
npm ERR! notarget   

and here are the latest-version message from npmjs.com:   

beta: "6.4.0-alpha.1"   
latest: "6.3.4"   
rc: "4.0.0-rc.4"

**Comment by Pessimistress** [comment]
6.4.0 has not been published. Please use 6.3-release branch to run examples.

**Comment by Ash-sc** [comment]
@Pessimistress :grin: thx.
