### ISSUE TITLE
64 bit wobble is back

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#258]
The precision issues are back for all layers I've tested so far.

Tested on:
- Line
- Scatter
- Arc
- Choropleth

**Comment by shaojingli** [comment]
@contra do you know the last working version?

**Comment by contra** [comment]
@shaojingli It was working fine on 3.0.10, broke when updating to 3.1.1 - I'll test to confirm right now.

**Comment by shaojingli** [comment]
@contra thanks a lot!

**Comment by contra** [comment]
@shaojingli Still present on 3.0.10 - maybe a subdep update to blame?

**Comment by shaojingli** [comment]
@contra I think it's due to some regression in luma.gl. It should  have been fixed in the latest version

**Comment by contra** [comment]
@shaojingli I'll try it out and update in a bit

**Comment by contra** [comment]
@shaojingli Fixed after latest updates, so probably that luma.gl regression - closing.
