### ISSUE TITLE
On BitmapLayer, perhaps default tintColor should be 300?

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2585]
#### Description
On the experimental BitmapLayer, setting the tintColor to `[300, 300, 300]` preserves the colors of the original, while accepting the default `[255, 255, 255]` results in something too dark. Greater than 300 washes out the colors. I'm not sure whether the default should be different, or it should be re-centered on 255 instead of 300.

#### Repro Steps
snippet:
```
    const imgUrl = 'https://docs.higlass.io/_images/higlass-heatmap-screenshot.png';

    const bitmapParams = {
      coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
      images: [imgUrl],
      modelMatrix: new Matrix4().scale([400,200,200])
    };

    return [
      new BitmapLayer({
        id: 'bitmap-layer0',
        data: [{
          imageUrl: imgUrl,
          center: [0, 0, 0],
          rotation: 0
        }],
        ...bitmapParams
      }),
      new BitmapLayer({
        id: 'bitmap-layer1',
        data: [{
          imageUrl: imgUrl,
          center: [0, 1, 0],
          rotation: 0
        }],
        tintColor: [300, 300, 300],
        ...bitmapParams
      }),
      new BitmapLayer({
        id: 'bitmap-layer2',
        data: [{
          imageUrl: imgUrl,
          center: [0, 2, 0],
          rotation: 0
        }],
        tintColor: [350, 350, 350],
        ...bitmapParams
      }),
```
(Had a little trouble getting math.gl to work in codepen; Sorry.)
<img width="407" alt="screen shot 2019-01-17 at 3 42 55 pm" src="https://user-images.githubusercontent.com/730388/51347612-9cbf0580-1a6e-11e9-8d49-6e14f0ad0120.png">

#### Environment (please complete the following information):
- Library
    "@deck.gl/experimental-layers": "^6.3.4",
    "deck.gl": "^6.3.4",
 - Browser Version: 
Google Chrome 71.0.3578.98
and FF 63.0.3
 - OS: OSX 10.11.6 (15G22010)

#### Logs
```
RENDER WARNING: there is no texture bound to the unit 0
```
but I don't think that's the problem.

**Comment by Pessimistress** [comment]
The default layer `opacity` is `0.8` - that might be causing your issue?

**Comment by mccalluc** [comment]
Thanks! yep, that fixes it:
```
const bitmapParams = {
  coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
  images: [imgUrl],
  modelMatrix: new Matrix4().scale([400,200,200]),
  opacity: 1
};
```
produces:
![screen shot 2019-01-17 at 6 52 31 pm](https://user-images.githubusercontent.com/730388/51356632-48754f00-1a89-11e9-8767-5dd535af9de8.png)

... but it feels a little odd, still: Is there something else that's putting a black background implicitly behind the image? because the background I see around these images is white, so I would expect them to fade out to white rather than black as opacity goes to 0.

Anyway, this fixes the problem I had, so feel free to close, or not. Thanks!

**Comment by gnavvy** [comment]
(shamelessly hijacking this thread)

Hi @mccalluc, I noticed in your screenshot there're fairly comprehensive visualizaitons of bioinformatic data with density matrix and sequence, etc. Are you using some other tools to pre-generated those images and then display them via the bitmap-layer? 

Would you be interested in using some `matrix-layer` or `sequence-layer` for such use case with full interactivity support in the browser?

**Comment by mccalluc** [comment]
@gnavvy : Sorry for the confusion: that's a screenshot from a separate project (higlass.io) and it doesn't use deck.gl (mostly PIXI.js): I just needed some image to work with and I had it in another browser tab.

`matrix-layer` would interesting if it existed... but I need to take a look at `TileLayer` and that might do what we need.

Glad to describe more about what we're doing, but maybe start a new issue or use email instead of confusing this one? Thanks for asking!

**Comment by Pessimistress** [comment]
@mccalluc re: background color - you may be looking for this https://github.com/uber/deck.gl/blob/master/modules/experimental-layers/src/bitmap-layer/bitmap-layer.js#L39

**Comment by mccalluc** [comment]
`opacity: 1` works for me. Thanks for your help! Closing.

(FWIW: alpha transparency in my image does seem to be working... The link above suggests there is a problem, but that might be talking about something different.)
