### ISSUE TITLE
min/max for 64 bit scatterplot

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#259]
Opening to make sure it doesn't get lost in the void.

I could use a little help with the PR for the 64 bit layer. The 32 bit was easy with `clamp()`, the 64 bit layer seems much more complex and I'm not sure where to dive in.

Might be easier if @shaojingli tackles this instead of waiting for me to fumble a PR out.

**Comment by shaojingli** [comment]
Issue addressed in #283
