### ISSUE TITLE
Most gallery examples do not work with Firefox 64.0

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2597]
#### Description
Of the 9 examples on https://deck.gl/showcases/gallery/, only ScreenGrid and Scatterplot work on Firefox.

#### Repro Steps
Visit https://deck.gl/showcases/gallery/boiler-plate (for example): Nothing is rendered

#### Environment (please complete the following information):
 - Framework Version: 6.0.0 on your site, but I've downloaded a couple, upped the version (`https://unpkg.com/deck.gl@6.3.4/deckgl.min.js`), and the behavior does not change.
 - Browser Version: Firefox 64.0
 - OS: MacOS 10.11.6

#### Logs
```
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:70:12
Error in parsing value for ‘cursor’.  Declaration dropped. data:%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3Ctitle%3EGet%20Started%20with%20deck.gl%3C/title%
Error in parsing value for ‘cursor’.  Declaration dropped. data:%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3Ctitle%3EGet%20Started%20with%20deck.gl%3C/title%
Unknown descriptor ‘"normal"’ in @font-face rule.  Skipped to next declaration. refresh.css:1:42967
Unknown descriptor ‘"normal"’ in @font-face rule.  Skipped to next declaration. refresh.css:1:86438
Unknown descriptor ‘"normal"’ in @font-face rule.  Skipped to next declaration. refresh.css:1:129781
Unknown descriptor ‘"normal"’ in @font-face rule.  Skipped to next declaration. refresh.css:1:172668
Unknown descriptor ‘"normal"’ in @font-face rule.  Skipped to next declaration. refresh.css:1:214746
Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes.
Error in parsing value for ‘cursor’.  Declaration dropped.
data:%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%20%20%3Ctitle%3EGet%20Started%20with%20deck.gl%3C/title%
```
(It doesn't show up in the copy, but the last `Error in parsing value` is being hit in an infinite loop, but only the first time after browser start.)

I am also filing a bug against Firefox, and will reference it here.

**Comment by mccalluc** [comment]
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1521245

**Comment by Pessimistress** [comment]
Ok this has nothing to do with the standalone bundle. The way we set up iframe for these pages is not working in FF. I'll put up a fix.
