### ISSUE TITLE
deprecation warning for geojson-normalize

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#260]
Changed it to `@mapbox/geojson-normalize`, should be a quick update.

**Comment by ibgreen** [comment]
@apercu @Pessimistress @gnavvy - Let's get this one done as part of our new GeoJson layer.

**Comment by Apercu** [comment]
@ibgreen What about proposing a PR for them to support immutable? I don't feel like implementing all of our dependencies (even if small) in our code is a good idea, it's a very slippery slope.

**Comment by ibgreen** [comment]
> What about proposing a PR for them to support immutable?

@apercu I'd be surprised if mapbox had an interest in supporting Immutable. It is something that becomes interesting mainly when one works with react, which is something we have been adding on top of their stuff. 

>  I don't feel like implementing all of our dependencies (even if small) in our code is a good idea, it's a very slippery slope.

It's a good discussion, but in this particular case I'm decided. We are already building in deep knowledge of the geojson format into our layers, why should we suddenly use an external module for a small part of the necessary code. Especially if writing our own could enable us to e.g. support Immutable data structures.

I already wrote an implementation of this, as you can see it is very simple. I will put up a PR later that shows how it can support Immutable (without importing Immutable.js, of course).

```
export default function normalizeGeojson(geojson) {
  const type = geojson.type;
  switch (type) {
  case 'Point':
  case 'MultiPoint':
  case 'LineString':
  case 'MultiLineString':
  case 'Polygon':
  case 'MultiPolygon':
  case 'GeometryCollection':
    // Wrap the geometry object in a "Feature" and add the feature to a "FeatureCollection"
    return {
      type: 'FeatureCollection',
      features: [
        {type: 'Feature', properties: {}, geometry: geojson}
      ]
    };
  case 'Feature':
    // Add the feature to a "FeatureCollection"
    return {
      type: 'FeatureCollection',
      features: [geojson]
    };
  case 'FeatureCollection':
    // Just return the feature collection
    return geojson;
  default:
    throw new Error('Unknown geojson type');
  }
}
```

**Comment by Pessimistress** [comment]
One benefit I'd like to have from this migration is the ability to handle an array of features. Such an array is not a valid GeoJSON object, therefore does not fit in the geojson-normalize context.

In our use case, though, consider the GeoJSONLayer: it takes a featureCollection and sort it into three arrays of features by type to pass into the ScatterplotLayer, PolygonLayer and PathLayer. It doesn't make sense if we have to cast them into new featureCollections just for the PolygonLayer and PathLayer to understand.

**Comment by ibgreen** [comment]
Removed on dev
