### ISSUE TITLE
MapboxLayer: Hexagon not pickable if any layer above not visible

### ISSUE THREAD

**Issue by jasonsoden** [uber/deck.gl#2602]
#### Description
With MapboxLayer + HexagonLayer, at least one layer above the inserted HexagonLayer needs to be on screen for the hexagon to be pickable.

#### Repro Steps
Using the experimental MapboxLayer, insert a HexagonLayer into the map at the 'country-label-lg' position.

`map.addLayer(new MapboxLayer({ id, deck }), 'country-label-lg');`

Layer Order:

country-label-lg
hexagon-layer
country-label-md
country-label-sm
etc..

If no country-label-lg instances are on screen, you can't pick anything. For example, none of these are pickable. The onHover event does not fire.

![image](https://user-images.githubusercontent.com/8482503/51451929-9938b200-1cec-11e9-8191-0aa769206f87.png)

But if you zoom out to show the country-label-lg, you can pick any hexagon:

![image](https://user-images.githubusercontent.com/8482503/51452330-90e17680-1cee-11e9-93d6-6d0d2b3e9c15.png)

You can reproduce this by inserting the HexagonLayer underneath any layer and zoom to a position so no layers above are visible. Nothing is pickable. For example, if you insert HexagonLayer at 'waterway-label' and zoom in so no roads or any layers above are visible, you can't pick anything at all.

#### Environment:
 - Framework Version: 6.3.6
 - Browser Version: Chrome 71.0.3578.98
 - OS: Windows 10

#### Logs
N/A

**Comment by Pessimistress** [comment]
@jasonsoden Thanks for reporting. Are you using the feature with React (http://deck.gl/#/documentation/mapbox-api-reference-experimental/overview?section=using-with-react)?

**Comment by jasonsoden** [comment]
@Pessimistress My implementation is very similar to the example code you posted, only I'm using HexagonLayer instead of ScatterplotLayer. I can try to get you a codepen soon. In short, I capture the map and gl refs when the Deck component initializes and loads, then listen to the StaticMap onLoad event and insert the HexagonLayer accordingly.

**Comment by Pessimistress** [comment]
@jasonsoden I was able to reproduce this. It has to do with Mapbox messing with the GL parameters. I'll put up a work around.

**Comment by Pessimistress** [comment]
Fix published in 6.3.8
