### ISSUE TITLE
"Multiple new layers with same id" error

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2603]
I tried to change `radius` passed to ScatterplotLayer dynamically, to generate a scatterplot with animation, and get Layers to be empty when the animation was done.

However, I got several errors at one time (they will appear when my layer is going to disappear, which is the end of animation) when I tried to do these, which includes:

* deck: Multiple new layers with same id ScatterplotLayer({id: 'scatterplot-fade'})
* deck: Multiple old layers with same id ScatterplotLayer({id: 'scatterplot-fade'})
* deck: error while initializing ScatterplotLayer({id: 'scatterplot-fade'}) Error: deck.gl: assertion failed.

A more detailed log info of the third error shows below:

```
deck: error while initializing ScatterplotLayer({id: 'scatterplot-fade'})
 Error: deck.gl: assertion failed.
    at assert (assert.js:6)
    at ScatterplotLayer._initState (layer.js:1096)
    at ScatterplotLayer._initialize (layer.js:726)
    at LayerManager._initializeLayer (layer-manager.js:700)
    at LayerManager._updateSublayersRecursively (layer-manager.js:631)
    at LayerManager._updateSublayersRecursively (layer-manager.js:651)
    at LayerManager._updateLayers (layer-manager.js:581)
    at LayerManager.setLayers (layer-manager.js:269)
    at LayerManager.setProps (layer-manager.js:212)
    at Deck.setProps (deck.js:217)
```

The way I realize the `renderLayers` method follow these two steps:

```javascript
renderLayers() {
    let {updateTriggers = {}, showWaveAnimation, data, colorRange, ...otherProps} = this.props;
    const {radiusScale,} = this.state;
    
	// I will return [] when reach the end of animation (I defined with `radiusScale` variable)
    if (radiusScale === OVERFLOW_FLAG) return [];
    
	// other codes

    const layerProps = {
      ...otherProps,
      data,
      getColor: SOME_FUNCTION(radiusScale),
      updateTriggers: {
        ...updateTriggers,
        getColor: [radiusScale],
      },
    };

    return [
      new ScatterplotLayer(layerProps)
    ]
  }
```

After searching in deck.gl documents, I found I can solve these problems by:

1. How to destroy instance safely when I don't need to display them anymore?
2. How to forbid useless rendering when I return `[]`?

Thanks!

**Comment by Pessimistress** [comment]
- Layer instances are finalized when an id is no longer present in the layers list. See http://deck.gl/#/documentation/developer-guide/writing-custom-layers/layer-lifecycle.
- Can you define "useless rendering?" `renderLayers()` is only called when layer props/state change, and no rerender is performed unless some layers/viewport changed.

**Comment by hijiangtao** [comment]
**For the first point**, I am also confused about this sentence, which is also the problem I mentioned above:

> When a new layer instance is matched to an existing layer instance by id, the state object of the old layer becomes accessible to the new layer...

It seems that layer will be identified by its unique ID, and will reuse some resource when new layer's ID matched existing ID. The question is I never changed layer ID, but why would I got warnings like these:

```
deck: Multiple new layers with same id ScatterplotLayer({id: 'scatterplot-fade'})
deck: Multiple old layers with same id ScatterplotLayer({id: 'scatterplot-fade'})
```

Is it because I will reach `return [];` logic when I think there's no need to return layers in `renderLayers` method? 

And that's the useless rendering I defined in my project, let me explain it in detail, for **the second topic** you mentioned above:

The purpose of my animation is to draw a scatterplot layer with fade out animation, so the radius will grow and the opacity of circles will go down as time goes by, when the opacity reaches 0, I think that's the end of my animation, so there's no need to render layers anymore.

PS: Why I render `[]` in `renderLayers`? Reason: I don't want the circles that are already transparent still exist in the map, which will hide my other layers, as mentioned in https://github.com/uber/deck.gl/issues/633#issuecomment-299723320 : 

> Even though the arcs are transparent they are still being rendered which affects the Z buffer and hides arcs behind.

Again, I found there's no recommend `destroy` way in the documents, so how to destroy instance safely when I don't need to display them anymore? or, deck.gl had already do something like cleaning for us?

Thanks.

**Comment by Pessimistress** [comment]
As the warning message suggests, you are passing multiple layer instancess with the same id (`scatterplot-fade`) to DeckGL's `layers` prop. Without seeing your code I can only suggest you inspect the list of layers.

You do not need to finalize a layer yourself, deck.gl does it when a layer id is no longer in the list of layers.

**Comment by hijiangtao** [comment]
Here is codes https://gist.github.com/hijiangtao/994ddb910228f47292782ed53cc4e2ba of custom layer I extends from `CompositeLayer`, I checked my usage and found there's no duplicate layer with same id passed to this component, but the above three problem still exists, I use it in this way:

```
import DeckGL from 'deck.gl';

...

// things I passed to DeckGL
<DeckGL layers={[
	new Layer({
        data: this.data,
		id: 'scatterplot-fade',
        ...LAYER_CONFIGS,
      })
]} >

...
```

The problem is that my customized layer can run well, but with that three warnings. I want to get the warnings out, since it means potential wrong usage of deck.gl.

![image](https://user-images.githubusercontent.com/4990015/51673969-53405e80-200a-11e9-9a33-8bcdad6a1ced.png)

**Comment by Pessimistress** [comment]
You are passing the id of `FadeScatterplotLayer` directly to the `ScatterplotLayer` inside `renderLayers`. So the parent composite layer and the sublayer are the two layers with the same id. An easy fix is to add `id: this.id + '-child'` to your sublayer props.

The documentation pages of CompositeLayer and "writing custom layers" do not make this clear. It is something we are working to address in the 6.4 release.

**Comment by hijiangtao** [comment]
@Pessimistress It works, I also tried removing my customized id and let deck.gl generate default id for layers. Thanks very much!

**Comment by chriszrc** [comment]
@Pessimistress In my case, I was returning two GeoJsonLayers to renderSubLayers for an MVTLayer (so they could share the point data for both circles and labels for cluster markers), and just removing `id` wasn't enough, because the two layers ended up with the same ids, so I can to do `id: props.id + "first_sub_layer"` and `id: props.id + "second_sub_layer"` -
