### ISSUE TITLE
Uncaught (in promise) Error: Could not load image when loading the icon atlas in IconLayer

### ISSUE THREAD

**Issue by FabianHertwig** [uber/deck.gl#2610]
#### Description

I followed the docs for the icon layer here: https://github.com/uber/deck.gl/blob/master/docs/layers/icon-layer.md

When I try to load the icon atlas with the relative path as described in the docs I get the following error:

    Uncaught (in promise) Error: Could not load image ./img/icon_atlas.png.
    at Image.image.onerror (browser-load.js:54)

Method to load the icon atlas:

    iconAtlas: 'images/icon_atlas.png',

I found the following solutions:
Either use the require function:

    iconAtlas: require('img/icon_atlas.png'),

Or import the icon atlas
  
    import iconAtlas from 'img/icon_atlas.png'

and then

    iconAtlas: iconAtlas,

#### Environment:
 - Framework Version: deck.gl 6.3.3
 - Browser Version: Chrome 71.0
 - OS: Mac OS X 10.14

Should the docs be updated?

**Comment by Pessimistress** [comment]
`./img/icon_atlas.png` is the path to the image at runtime, not from the source code. If you are using webpack dev server the `img` directory need to be at root.

You can see this by inspecting the "networks" tab in the developer console.
