### ISSUE TITLE
Interaction between zoom and offset is unclear to me

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2638]
I think I have a conceptual problem with `offset`:
- I would expect that if the offset matched the position of an object, the object should be in the center of the view for any zoom level: It is centered in the lower right example, but the position and offset do not match.
- I would expect that if an object is in the center of the view, just changing the zoom level should not move it from the center of the view: It is centered in the lower right example with zoom=3... but changing the zoom to 10 moves it off center

https://codepen.io/mccalluc/pen/MLjXLJ
![screen shot 2019-01-29 at 1 53 15 pm](https://user-images.githubusercontent.com/730388/51932488-44bcc300-23cd-11e9-9783-f886ce10f202.png)

JS:
<details>

```javascript
function render(zoom, offset, position) {
  new deck.DeckGL({
    container: `zoom-${zoom}-offset-${offset}-position-${position}`,
    views: [new deck.OrthographicView()],
    initialViewState: {
      zoom: zoom,
      offset: [offset, offset]
    },
    layers: [
      new TextLayer({
        coordinateSystem: deck.COORDINATE_SYSTEM.IDENTITY,
        data: [[0,0]],
        getPosition: d => d,
        getText: d => 'fixed'
      }),
      new ScatterplotLayer({
        coordinateSystem: deck.COORDINATE_SYSTEM.IDENTITY,
        data: [[position,position]],
        getPosition: d => d,
        getRadius: d => 100,
        opacity: d => 0.25
      }),
    ]
  });
}

render(10, 0, 0);
render(10, 100, 0);
render(10, 100, 300);
render(10, 0, 300);

render(3, 0, 0);
render(3, 100, 0);
render(3, 100, 300);
render(3, 0, 300);

```
</details>

html:
<details>

```html
<table>
  <tr>
    <td>

<table>
  <tr>
    <td>zoom: 10</td>
    <td>position: [0,0]</td>
    <td>position: [300,300]</td>
  </tr>
  <tr>
    <td>offset: [0,0]</td>
    <td><div id="zoom-10-offset-0-position-0"></div></td>
    <td><div id="zoom-10-offset-0-position-300"></div></td>
  </tr>
  <tr>
    <td>offset: [100,100]</td>
    <td><div id="zoom-10-offset-100-position-0"></div></td>
    <td><div id="zoom-10-offset-100-position-300"></div></td>
  </tr>
</table>

    </td><td>  
      
<table>
  <tr>
    <td>zoom: 3</td>
    <td>position: [0,0]</td>
    <td>position: [300,300]</td>
  </tr>
  <tr>
    <td>offset: [0,0]</td>
    <td><div id="zoom-3-offset-0-position-0"></div></td>
    <td><div id="zoom-3-offset-0-position-300"></div></td>
  </tr>
  <tr>
    <td>offset: [100,100]</td>
    <td><div id="zoom-3-offset-100-position-0"></div></td>
    <td><div id="zoom-3-offset-100-position-300"></div></td>
  </tr>
</table>

    </td>
  </tr>
</table>
```

**Comment by Pessimistress** [comment]
@mccalluc we just published 6.4.0 which includes a bug fix for the OrthographicView. Can you give it a try? (you may need to check the [upgrade guide](http://deck.gl/#/documentation/overview/upgrade-guide)).

**Comment by jianhuang01** [comment]
@mccalluc according to [this doc](http://deck.gl/#/documentation/deckgl-api-reference/views/orthographic-view), this offset is for viewport in screen space pixels, it won't meet your expectation. Basically it acts like this, first the world is scale up/down based on current zoom and [0, 0, 0] origin, then the full screen moves by this offset.

**Comment by mccalluc** [comment]
This is what it looks like now: https://codepen.io/mccalluc/pen/dapBKB
![screen shot 2019-01-29 at 5 53 07 pm](https://user-images.githubusercontent.com/730388/51946267-09cb8700-23ef-11e9-9d36-fdb98518b741.png)

I think I've just had the wrong model in my head:
- The origin remains fixed as `zoom` changes.
- `offset` moves the viewport by pixels (I think?) *after* zoom.
- To zoom at a given coordinate, I'll need to do the math myself for `offset`, which will depend on `zoom`.

It feels like it could be a common usecase for a view to be centered on given coordinate at a given zoom level, but I should be able to figure out the math, if that's not built-in. Thanks!

**Comment by mccalluc** [comment]
(But `eye` and `lookAt` may help. Thanks again!)
