### ISSUE TITLE
how to update geojson layer data

### ISSUE THREAD

**Issue by qly612525** [uber/deck.gl#2641]
Hi, I have a List. The list elements are a bunch of polygons(get polygon by ajax). When I click a element, map shound draw the polygon and  fit the bound of polygon. After 10 second，remove the polygon.

the question is when I click the element less than 10 second, how to remove the polygon and add a new polygon to the geojson layer.

---

I use redux store **DeckGL** layers，I cannot dispatch updateLayer action twice immediately！

**Comment by jianhuang01** [comment]
you can create a new geojson layer with updated polygon data, and set new layers to Deck/DeckGL object

**Comment by qly612525** [comment]
@jianhuang01 i have solve this problem. I use the `SVGOverlay` as my Layer , expose `props` for updating data and handling the UI interaction.

Maybe my application required, I need custom layer.
