### ISSUE TITLE
Loading custom images for layers.

### ISSUE THREAD

**Issue by bdparrish** [uber/deck.gl#2649]
Utilizing the same layer preparation as mapbox-gl can you add an image for reference for an `IconLayer` other than an icon atlas  or a URL reference in each object?

i.e. ---
```
map.addImage(id, "http://some.com/image.png");

map.addLayer({
                            id: id,
                            interactive: true,
                            type: 'symbol',
                            source: {
                                ---brevity---
                            },
                            layout: {
                                'icon-image': id
                            }
                        });
```

I can't have an icon atlas for the dynamic images that i am using and the url reference will fetch for every object in the layer it seems like.  Is there a different way to do what I am trying to do where I can preload an image for reference and map handles it?

**Comment by bdparrish** [comment]
My understanding is that icon atlas is a known set of glyphs/sprites like sprite sheets used in games.  I do not know the icons before hand, so I am unable to create an icon atlas.

The out of the box API for mapbox-gl allows me to create an in memory mapped lookup on the fly for any images I want to use in a layer.  

I understand Icon Layer can do this with icon urls, but it seems like it is making a url request for every feature in the layer.  

Is there something I am missing

**Comment by xintongxia** [comment]
> My understanding is that icon atlas is a known set of glyphs/sprites like sprite sheets used in games. I do not know the icons before hand, so I am unable to create an icon atlas.

Your understanding about icon atlas is correct. 
If you do not know image urls beforehand, `IconLayer` allows you pass in the url for each feature/data point. check [`Example: auto packing iconAtlas`](http://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer?section=example-auto-packing-iconatlas)

> The out of the box API for mapbox-gl allows me to create an in memory mapped lookup on the fly for any images I want to use in a layer.

`IconLayer` provides 2 options now,

1. If you know the shared IconAtlas beforehand, pass in `IconAtlas` (image url or texture) and `IconMapping` (like a icon look up table)

2. If you do not know the icons you are going to use, then your `getIcon` property need provide instructions about how to get these icons. Then the `IconLayer` will do the work of fetching icons and creating shared `IconAtlas` and `IconMapping`.

```
IconLayer({
  data,
  getIcon: d => ({
    url: d.some_url,
    width: 128,
    height: 128,
    anchorY: 128,
    mask: true
  }),
  ...
})
```

> I understand Icon Layer can do this with icon urls, but it seems like it is making a url request for every feature in the layer.

If your data and `getIcon` provided icon urls, `IconLayer` will extract all the unique urls from your data and fetch them, but `IconLayer` will not make duplicate calls for the same url.

Let me know if I misunderstood your questions.

**Comment by bdparrish** [comment]
Looks like that answered my concerns.  Maybe I am coding up the `getIcon` function wrong.  I’ll take another look.
