### ISSUE TITLE
Utilizing mapbox-gl layer functionality

### ISSUE THREAD

**Issue by bdparrish** [uber/deck.gl#2653]
Is a deck.gl layer acting as a mapbox layer utilizing `MapboxLayer` able to respond as if it were a mapbox layer?  For example I converted a mapbox-gl symbol layer over to being an `IconLayer` type defined as a `MapboxLayer`.  I have now lost the ability to `queryRenderedFeautures()` and act on  `oncontextmenu` events.  Is there another way to access these utilizing the `IconLayer`?  I am not using react for this.

**Comment by Pessimistress** [comment]
For the time being you have to use `onHover` and `onClick` props of the IconLayer. As far as I know Mapbox does not have an API for 3rd-party layers to participate in query.
