### ISSUE TITLE
Wireframe is connecting outer polygon to inner polygon

### ISSUE THREAD

**Issue by Snaptags** [uber/deck.gl#2657]
#### Description
The handling of polygon wire frames seems to have been changed with the 6.4.0 release. It is now connecting the outer polygon to the inner polygon:

**Actual (6.4.0)**
![actual](https://user-images.githubusercontent.com/1249745/52412777-09627880-2ae0-11e9-8a4f-4007e1394f2d.png)
https://codepen.io/anon/pen/WPXBMQ

**Expected (6.3.6)**
![expected](https://user-images.githubusercontent.com/1249745/52412776-09627880-2ae0-11e9-96d2-9db8adee2217.png)
https://codepen.io/anon/pen/xMPoGy

Any workarounds to get the old behavior?

#### Repro Steps
Use any polygon with hole(s), e.g. https://codepen.io/anon/pen/WPXBMQ

#### Environment (please complete the following information):
 - Framework Version: deck.gl 6.3.6 vs. 6.4.0
 - Browser Version: Firefox 65, Chrome 74
 - OS: Windows 10

#### Logs
No relevant logs.

**Comment by Pessimistress** [comment]
Thanks for reporting. I'll put up a patch asap.

**Comment by Pessimistress** [comment]
Fixed in 6.4.1

**Comment by Snaptags** [comment]
@Pessimistress I can happily confirm that the bug is gone in 6.4.1. Thank you for fixing this quickly and for adding tests.
