### ISSUE TITLE
Cannot run exhibits.

### ISSUE THREAD

**Issue by davidkell** [uber/deck.gl#266]
**Problem**

Cannot run the webpack exhibits example.

**Steps to reproduce**

`git clone https://github.com/uber/deck.gl`
`cd deck.gl`
`cd exhibits`
`npm run webpack`

I am using yarn.
Machine: MacBook Pro 11" Retina with macOS Sierra

**Error**

```
ERROR in Cannot find module 'babel-core'
 @ multi main
```

I have tried to add babel-core as a dependency.
However I then run into a bunch of other errors.

Thanks

**Comment by rajshah4** [comment]
I was able to run the app.js in exhibits by doing the following: (with maybe unnecessary step)
```
git clone https://github.com/uber/deck.gl
cd deck.gl
npm install
cd exhibits
npm run webpack
```

**Comment by davidkell** [comment]
OK- followed these steps- get a new error.

Fails when it runs `webpack-dev-server --config config.js --progress --hot --port 3000`

Also- if we need to install deck.gl in the upper directory, how do we extract this exhibit into a new standalone project with webpack as the builder?

Thanks

**Comment by rajshah4** [comment]
I don't know the answer for making this is standalone.  Here is what I am using as my app.js  . . . updated it with your mapbox key and hopefully you should see a map and the drawing layer: 
https://gist.github.com/rajshah4/e703768b3dd65060387ab168a8d7c000

**Comment by davidkell** [comment]
That's interesting - that code you've linked is different to mine. Are you on a different branch?

**Comment by rajshah4** [comment]
Hmm, I wrote this App.js about two weeks ago.  I haven't been closely following all the developments, but I know its enough for me to show others how deck.gl works.  Does this work for you?

**Comment by davidkell** [comment]
Afraid not :( Do you have any idea what that web console log means? WOuld love to get this working!

**Comment by rajshah4** [comment]
I don't know about the error, but feel free to contact me and I can try to help you troubleshoot this.

**Comment by Apercu** [comment]
Could you please post your node, yarn and osx versions?

@rajshah4 Thanks for your help but it would be best if we could stick with the original example rather than introduce new overhead. Trimming the conversation.

**Comment by davidkell** [comment]
node: v7.2.1
osx: v10.12.1
yarn: v0.17.10

This is the log--

```
bundle.js:81620 deck.gl 3.1.1 - set deck.log.priority=2 to trace attribute updates
bundle.js:34125 luma.gl 2.10.3: WebGL1 debug context using driver: unknown unknown Object
bundle.js:34125 Assign luma.log.priority in console to control logging: 0: none, 1: minimal, 2: verbose, 3: attribute/uniforms, 4: gl logs
luma.log.break[], set to gl funcs, luma.log.profile[] set to model names
bundle.js:133057 [HMR] Waiting for update signal from WDS...
bundle.js:98361 Uncaught TypeError: Cannot read property 'default' of undefined
    at Light.set (bundle.js:98361)
    at Light (bundle.js:98345)
    at Style._resolve (bundle.js:91775)
    at Style.<anonymous> (bundle.js:91682)
    at XMLHttpRequest.xhr.onload (bundle.js:96674)
bundle.js:133134 [WDS] Hot Module Replacement enabled.
bundle.js:91833 Uncaught TypeError: Cannot read property 'updateLightTransitions' of undefined
    at Style._applyClasses (bundle.js:91833)
    at Style.update (bundle.js:91923)
    at module.exports._render (bundle.js:90075)
log.js:32 Resizing framebuffer id-1 to 1x1
```

Is this fine, or what do you mean by pastebin?

Thanks

**Comment by davidkell** [comment]
Update: it works on our ubuntu machine 14.04 with the instructions from @rajshah4 

Tried on another mac, no success.

**Comment by Apercu** [comment]
Got it: you need to also install the deck.gl dependencies before running the exhibits, didn't catched that until I did a fresh clone.

Will look at if we can remove this step, since the install is taking a bit of time.

PS: [Pastebin](http://pastebin.com) is a service allowing to paste text easily and prevent to pollute the thread, it's useful for big stacktraces, but since yours is relatively small, it's fine like you did.

**Comment by Apercu** [comment]
@davidkell You should now be able to `npm run webpack` without having to install deck.gl dependencies using the latest master state.

**Comment by davidkell** [comment]
@Apercu Thank you for doing this, really appreciate it.

 

We dug into the issue further at our end- here is what we’ve found---

 

Does the deck.gl webpack exhibit work?

yarn v0.21 on Ubuntu 14.04: YES

yarn v0.19 or v0.21 on macOS 10.12: NO (tested on 2 separate laptops)

npm v3.10.9 on macOS 10.12: YES (tested on 1 laptop)

 

The error for yarn on macOS is what we listed above. Now we’ve dug in deeper.

It seems like the `light.js` file in `mapbox-gl` is expecting a certain json structure. It is referencing another package `mapbox-gl-style-spec`, a file called `v8.json`

 

Seems like there is a mismatch happening here. The `v8.json` has been through multiple structures and this needs to match the corresponding mapbox-gl light.js

 

My only guess is that when you look at the `package.json` in the `mapbox-gl` is referencing a specific commit in a github repo (rather than npm repository) and sometimes yarn gets it wrong. Will look deeper tomorrow, but thought it would be of interest.

 

Thanks for the help.

**Comment by Apercu** [comment]
Are you sure you've pulled/cloned the latest `master`? Starting on a clean base without any previous errors might help.

**Comment by davidkell** [comment]
@Apercu we have now re-run from scratch with the new master branch
Issue persisted on macOS with yarn v0.21

We can now confirm that the issue is that yarn v0.21 is failing to correctly parse the dependency for the correct commit hash of `mapbox-gl-style-spec`, instead it's just grabbing the latest version which is inconsistent with `mapbox-gl` ( we have verified this manually on github )

The dependency for `mapbox-gl` v0.26 is `mapbox/mapbox-gl-style-spec#7d330d2abf1775abc95ab8b889089cf5ff579357`

Our current solution is to use the nightly build of yarnpkg.
https://yarnpkg.com/en/docs/nightly
As of today (21 Dec 2016) they have fixed this issue.
I will also file a bug on yarnpkg in case they are not aware of this issue

Thanks for your help!

**Comment by Apercu** [comment]
Thanks for the insights ;)
