### ISSUE TITLE
Refactor rendering & picking workflow

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#2662]
#### Target Use case

Clean integration of all rendering modules, like picking buffer, layers, effects.

#### Proposed feature

Refactor rendering & picking workflow to have clear responsibilities in each class, break draw-layers.js into different layer pass classes, wrap pick-layers.js in new class, improve Effect and EffectManager classes

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Test

**Comment by Pessimistress** [comment]
- [ ] Benchmark tests are down due to broken imports
