### ISSUE TITLE
Brushing Layer without react

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2672]
### Question

Should `arcLayer.setState({ mousePosition: [evt.offsetX, evt.offsetY] })` work in a non-react environment. Or is it ok to create a new instance of `ArcBrushingLayer` and use DeckGLs shallow comparison of the layers to update the `mousePosition`? 

---

### Explanation

I can create an `ArcBrushingLayer` without react and it works, but to get the brushing effect I'm having to create a `new ArcBrushingLayer` inside the `mousemove` Event Listener and rely on DeckGL's data comparison to compare the old and new layer, rather than using `setState({ })` as recommended by the documentation.

For example, I can implement the [shaders and default layer, as per the example](https://github.com/uber/deck.gl/tree/master/examples/website/brushing/arc-brushing-layer)

And I can create a layer

```js
var arcLayer = new ArcBrushingLayer({
    map_id: map_id,
    id: 'arc-'+layer_id,
    data: arc_data,
    pickable: true,
    getStrokeWidth: d => d.properties.stroke_width,
    getSourcePosition: d =>  d.destination.coordinates,
    getTargetPosition: d => d.origin.coordinates,
    getSourceColor: d =>  d.properties.stroke_from,
    getTargetColor: d => d.properties.stroke_to,
    enableBrushing: false,
    brushRadius: 100000,
    mousePosition
  });

// add layer to map
// I have this function to add the layer to my array of layers , as per https://github.com/uber/deck.gl/issues/2131#issuecomment-408736301
update_layer( arcLayer )
```

(related: https://github.com/uber/deck.gl/issues/2131#issuecomment-408736301)

But then I have to define a listener and create a `new` instance of the layer in order to get the `mousePosition` to be used. 

```js
var myListener = function(evt) {
  var arcLayer = new ArcBrushingLayer({
    map_id: map_id,
    id: 'arc-'+layer_id,
    data: arc_data,
    pickable: true,
    getStrokeWidth: d => d.properties.stroke_width,
    getSourcePosition: d =>  d.destination.coordinates,
    getTargetPosition: d => d.origin.coordinates,
    getSourceColor: d =>  d.properties.stroke_from,
    getTargetColor: d => d.properties.stroke_to,
    enableBrushing: false,
    brushRadius: 100000,
    mousePosition: [evt.offsetX, evt.offsetY]
  });

  update_layer( map_id, 'arc-'+layer_id, arcLayer );
  }

document.addEventListener('mousemove', myListener, false);
```
This new layer will be compared against the original layer, the only difference is the `mousePosition` property. 

using `arcLayer.setState({ mousePosition: [ evt.offsetX, evt.offsetY ] })` on the original `arcLayer` doesn't work. 

---

My working code is [here in my R package](https://github.com/SymbolixAU/mapdeck/blob/brush/inst/htmlwidgets/lib/arc/arc.js#L149) if it helps to see the whole thing.

**Comment by Pessimistress** [comment]
I quickly modified our brushing example to test this:

```js
// app.js
  _onMouseMove(evt) {
    if (evt.nativeEvent) {
      if (arcLayer) {
        arcLayer.setState({mousePosition: [evt.nativeEvent.offsetX, evt.nativeEvent.offsetY]});
      }
    }
  }
```

```js
// arc-brushing-layer.js

  draw(opts) {
    // add uniforms
    const uniforms = Object.assign({}, opts.uniforms, {
      ...
	  mousePos: this.state.mousePosition
        ? new Float32Array(this.unproject(this.state.mousePosition))
        : defaultProps.mousePosition,
```

And it does work. Can you verify that:
- `ArcBrushingLayer.draw` is called after a mouse move
- `arcLayer.state.mousePosition` value is valid

**Comment by SymbolixAU** [comment]
@Pessimistress 

I modified the `draw(opts)`  to reference `this.state.mousePosition`

```js
    draw(opts) {
	    // add uniforms
	    const uniforms = Object.assign({}, opts.uniforms, {
	      brushSource: this.props.brushSource,
	      brushTarget: this.props.brushTarget,
	      brushRadius: this.props.brushRadius,
	      mousePos: this.state.mousePosition
	        ? new Float32Array(this.unproject(this.state.mousePosition))
	        : defaultProps.mousePosition,
	      enableBrushing: this.props.enableBrushing
	    });
	    const newOpts = Object.assign({}, opts, {uniforms});
	    super.draw(newOpts);
	  }
  }
```

And my listener is now

```js
var myListener = function(evt) {
    console.log("arcLayer.state.mousePosition");
    console.log( arcLayer.state.mousePosition );
    arcLayer.setState({mousePosition: [evt.offsetX, evt.offsetY] });
}
```
This is the console.log showing the `arcLayer.state.mousePosition` changing, but brushing doesn't work. 

![screen shot 2019-02-13 at 10 31 06 am](https://user-images.githubusercontent.com/18344164/52675376-c76f8180-2f7a-11e9-82e9-20471d657ba7.png)

How would I check if `ArcBrushingLayer.draw` is called?

**Comment by Pessimistress** [comment]
> How would I check if `ArcBrushingLayer.draw` is called?

Just move the `console.log` statements into the draw() method?

What deck.gl version are you using?

**Comment by SymbolixAU** [comment]
using **deckgl.min.js 6.4.1**

Here's a screenshot showing the `console.log()` statements inside the `draw()` method, and the console output. It looks as though `draw()` is being called. 

![screen shot 2019-02-13 at 3 24 12 pm](https://user-images.githubusercontent.com/18344164/52686807-745df480-2fa3-11e9-81e0-34d2ca4b63a4.png)

**Comment by SymbolixAU** [comment]
@Pessimistress I've just tried something else and I think I may have a solution. 

I'll do more tests and report back.

**Comment by SymbolixAU** [comment]
@Pessimistress The solution seems to be changing the `draw(opts)` to use `this.state` as opposed to `this.props` as per the documentation

```r
    draw(opts) {
	    // add uniforms
	    const uniforms = Object.assign({}, opts.uniforms, {
	      brushSource: this.props.brushSource,
	      brushTarget: this.props.brushTarget,
	      brushRadius: this.props.brushRadius,
	      mousePos: this.state.mousePosition
	        ? new Float32Array(this.unproject(this.state.mousePosition))
	        : defaultProps.mousePosition,
	      enableBrushing: this.state.enableBrushing
	    });
	    const newOpts = Object.assign({}, opts, {uniforms});
	    super.draw(newOpts);
	  }
```
