### ISSUE TITLE
updating screen grid layer with orthographic view

### ISSUE THREAD

**Issue by jay-manday** [uber/deck.gl#2673]
# Issue Summary

Hi there! I've been working on some visualizations with deck.gl, and i've had some trouble in particular with updating the screenGridLayer when used in a non geospatial context.

I'm rendering a sparse matrix of fixed points, that follow this pattern: `[ [x, y, value], ... ]`

Im performing a simple scaling calculation to scale the original 640 x 480 matrix against the dimensions of the DOM element that is housing the layer. However every time the screen is resized, orthographic view seems to go out of phase, and appears to have not updated even though new data has passed to the layer.

I can verify that the scaling function is appropriately resizing the data according the proper scale but doesn't update the view.

# Expected Behavior

The ortho view and screen grid layer are appropriately rendering to correct scale across resizes.

![screen shot 2019-02-11 at 5 45 17 pm](https://user-images.githubusercontent.com/13109165/52633387-358c4980-2e92-11e9-97a1-b63caeeac27f.png)

# Actual Behavior

It appears that the `bottom` and right `parameters` aren't bound to the frame, and shift as the screen resizes.

<img width="680" alt="screen shot 2019-02-12 at 6 52 51 am" src="https://user-images.githubusercontent.com/13109165/52633625-02968580-2e93-11e9-93fc-48d4cf524a73.png">

# Notes

Here is a gist with the components in question. Any help would be greatly appreciated! I've had a lot of fun working with deck.gl but this weird edge case has been tricky to handle.

I'm sure i'm just missing something really silly though and not hooking into the layer lifecycles correctly. Any guidance would be super appreciated though!!

https://gist.github.com/jay-manday/421161a156f1f70ce90709641a746714

**Comment by tsherif** [comment]
@jay-manday We'll investigate further, but I notice that the `bottom` state you're setting is different when the component mounts and when the window resizes:
https://gist.github.com/jay-manday/421161a156f1f70ce90709641a746714#file-deck-js-L36
https://gist.github.com/jay-manday/421161a156f1f70ce90709641a746714#file-deck-js-L65

Is that intentional?

**Comment by jay-manday** [comment]
Hey @tsherif thanks for taking a look, I super appreciate it. 

Ahhhh that was an artifact of a prior test to double check that it's displaying the layer in a 4:3 aspect ratio. 😅 

I removed that artifact from my project and it's still exhibiting the same I updated the gist to reflect the appropriate value.

https://gist.github.com/jay-manday/421161a156f1f70ce90709641a746714#file-deck-js-L36

Thanks again for taking the time to investigate!

**Comment by jay-manday** [comment]
It might not totally relevant but logging the layer presented these results. It seems that the `viewProjectionMatrix`  & `viewportMatrix` have shifted significantly after the resize

# Before Resize

### ScreenGridLayer.context.viewport

```
cameraDirection: (3) [0, 0, 1]
cameraPosition: (3) [0, 0, 1]
cameraUp: (3) [0, 1, 0]
center: null
distanceScales: {pixelsPerMeter: Array(3), metersPerPixel: Array(3), pixelsPerDegree: Array(3), degreesPerPixel: Array(3)}
equals: ƒ ()
focalDistance: 1
getMatrices: ƒ ()
height: 673
id: "OrthographicView"
isGeospatial: false
meterOffset: (3) [0, 0, 0]
pixelProjectionMatrix: (16) [2, 0, 0, 0, 0, 2, 0, 0, 0, 0, -0.002000200020002, 0, 0, 0, -0.9981998199819982, 1]
pixelUnprojectionMatrix: (16) [0.5, -0, -0, 0, -0, 0.5, 0, -0, -0, -0, -499.95, -0, -0, -0, -499.05, 1]
position: (3) [0, 0, 0]
project: ƒ ()
projectFlat: ƒ ()
projectPosition: ƒ ()
projectionMatrix: (16) [0.004459308807134894, 0, 0, 0, 0, -0.005943536404160475, 0, 0, 0, 0, -0.002000200020002, 0, -1, 1, -1.0002000200020003, 1]
scale: 1
unproject: ƒ ()
unprojectFlat: ƒ ()
unprojectPosition: ƒ ()
viewMatrix: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -0, -0, -1, 1]
viewMatrixInverse: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1]
viewMatrixUncentered: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -0, -0, -1, 1]
viewProjectionMatrix: (16) [0.004459308807134894, 0, 0, 0, 0, -0.005943536404160475, 0, 0, 0, 0, -0.002000200020002, 0, -1, 1, -0.9981998199819982, 1]
viewportMatrix: (16) [448.5, 0, 0, 0, -0, -336.5, -0, -0, 0, 0, 1, 0, 448.5, 336.5, 0, 1]
width: 897
x: 0
y: 0
zoom: 0
```

# After Resize

### ScreenGridLayer.context.viewport

```
cameraDirection: (3) [0, 0, 1]
cameraPosition: (3) [0, 0, 1]
cameraUp: (3) [0, 1, 0]
center: null
distanceScales: {pixelsPerMeter: Array(3), metersPerPixel: Array(3), pixelsPerDegree: Array(3), degreesPerPixel: Array(3)}
equals: ƒ ()
focalDistance: 1
getMatrices: ƒ ()
height: 558
id: "OrthographicView"
isGeospatial: false
meterOffset: (3) [0, 0, 0]
pixelProjectionMatrix: (16) [2, 0, 0, 0, 0, 2, 0, 0, 0, 0, -0.002000200020002, 0, 0, 0, -0.9981998199819982, 1]
pixelUnprojectionMatrix: (16) [0.5, -0, -0, 0, -0, 0.5, 0, -0, -0, -0, -499.95, -0, -0, -0, -499.05, 1]
position: (3) [0, 0, 0]
project: ƒ ()
projectFlat: ƒ ()
projectPosition: ƒ ()
projectionMatrix: (16) [0.005376344086021506, 0, 0, 0, 0, -0.007168458781362007, 0, 0, 0, 0, -0.002000200020002, 0, -1, 1, -1.0002000200020003, 1]
scale: 1
unproject: ƒ ()
unprojectFlat: ƒ ()
unprojectPosition: ƒ ()
viewMatrix: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -0, -0, -1, 1]
viewMatrixInverse: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1]
viewMatrixUncentered: (16) [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, -0, -0, -1, 1]
viewProjectionMatrix: (16) [0.005376344086021506, 0, 0, 0, 0, -0.007168458781362007, 0, 0, 0, 0, -0.002000200020002, 0, -1, 1, -0.9981998199819982, 1]
viewportMatrix: (16) [372, 0, 0, 0, -0, -279, -0, -0, 0, 0, 1, 0, 372, 279, 0, 1]
width: 744
x: 0
y: 0
zoom: 0
```

**Comment by jay-manday** [comment]
I managed to solve it! I was doing a few things wrong here, but needed to assert the state of the viewport for each time the component updates.

Thanks!
