### ISSUE TITLE
Plot example code shows "Cannot find module '@luma.gl/constants' "

### ISSUE THREAD

**Issue by mk48** [uber/deck.gl#2698]
#### Description
I just downloaded the code as ZIP file and opened the "deck.gl-master\examples\website\plot" folder in a command prompt then tried the following

npm install
npm start

that plot example didn't run and gave the below error

![image](https://user-images.githubusercontent.com/3082469/53001484-b9c16c80-3450-11e9-98c8-fe330b471ef1.png)

#### Repro Steps
just try to run the plot example code

#### Environment (please complete the following information):
    "d3-scale": "^1.0.6",
    "deck.gl": "^6.2.0",
    "luma.gl": "^6.4.2",
    "react": "^16.3.0",
    "react-dom": "^16.3.0"
 - Browser Version: Chrome 66
 - OS: Win7 64bit

**Comment by Pessimistress** [comment]
Are you running the example from 6.4-release? Master is the dev branch.

**Comment by mk48** [comment]
I downloaded from Master branch only.
Could you please suggest me which branch should I use?

**Comment by IgorWilbert** [comment]
@mk48 I think @Pessimistress suggested using the branch called `6.4-release`

**Comment by Pessimistress** [comment]
@mk48 See http://deck.gl/#/documentation/getting-started/installation for how to run examples.

**Comment by mk48** [comment]
Thanks @IgorWilbert , 6.4-release examples working fine
