### ISSUE TITLE
Calling function in vertex shader

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2705]
In the Scatterplot Brushing example you define functions inside the vertex shader to calculate if the point is [within the radius of the mouse](https://github.com/uber/deck.gl/blob/master/examples/website/brushing/scatterplot-brushing-layer/scatterplot-brushing-layer-vertex.glsl.js#L72)

```
// range is km
float isPointInRange(vec2 ptLatLng, vec2 mouseLatLng, float range, bool enabled) {
  return float(!enabled || distanceBetweenLatLng(ptLatLng, mouseLatLng) <= range);
}
```

**Is it possible to return the result of this function to javascript/ the app?**

A work-around is to write a similar function in the app (in javascript) to iterate over the data and find those within range, but I'm wondering if we can make use of the shader function which has already calculated it?

**Comment by tsherif** [comment]
@SymbolixAU unfortunately, no. The shader code is running on the GPU and so is in a completely separate execution context from your JavaScript running in the browser. If you need a similar function, it will have to be implemented in your app.

**Comment by SymbolixAU** [comment]
Thanks @tsherif , I suspected as much, but it's good to have it confirmed.
