### ISSUE TITLE
JSX codepen examples? (Trying to reproduce problem with pickObject)

### ISSUE THREAD

**Issue by mccalluc** [uber/deck.gl#2712]
Are there any codepen (or similar) examples using JSX? I have found the https://codepen.io/vis-gl/# examples, but the behavior of pure-js vs the react component seems to be different around `pickObject`.

https://codepen.io/mccalluc/pen/wNbbOm
<details>

```jsx
function triangle(color) {
  return {
    initialViewState: { zoom: 0.5 },
    layers: [
      new PolygonLayer({
        coordinateSystem: deck.COORDINATE_SYSTEM.IDENTITY,
        data: [{
            contour: [[0, 0], [0, -50], [-50, -50]],
            color: color
        }],
        getPolygon: d => d.contour,
        getFillColor: d => d.color
      }),
    ]
  }
} 
    
const plainDeck = new deck.DeckGL({
  views: [new deck.OrthographicView()],
  container: 'plain',
  ...triangle([255, 0, 0])
});

console.log('pickObject', plainDeck.pickObject);
// Function is defined, but...

// console.log('pickObject()', plainDeck.pickObject({x: 0, y: 0}));
// --> TypeError: this.layerManager is null

// Trying to do it without JSX... not the right syntax?
// ReactDOM.render(
//   React.createElement(deck.DeckGL, triangle([0, 255, 0]), null),
//   document.getElementById('js')
// );
// --> ReferenceError: require is not defined
//

// ReactDOM.render(
//   <DeckGL {...triangle([0, 0, 255])}/>,
//   document.getElementById('jsx')
// )
// TypeError: class constructors must be invoked with |new|
```

</details>

I would be happy either 
- being able to use `pickObject` in plain js in codepen (Currently, gives this error: `TypeError: this.layerManager is null`.)
- or being able to use deck.gl + JSX in codepen (In my local environment using JSX, I have been able to call `pickObject`, but haven't gotten my example to work in codepen.)

(FWIW: I am using `COORDINATE_SYSTEM.IDENTITY` and locally `pickObject` works for objects with positive coordinates, but not if the coordinates are negative; `pickObjects` seems to have the same problem, with something else in addition: I'll look into these further and give you a better report if I can get a reproducer up.)

**Comment by jianhuang01** [comment]
```javascript
function triangle(color) {
  return {
    initialViewState: { zoom: 0.5 },
    layers: [
      new PolygonLayer({
        pickable: true,
        coordinateSystem: deck.COORDINATE_SYSTEM.IDENTITY,
        data: [{
            contour: [[0, 0], [0, -50], [-50, -50]],
            color: color
        }],
        getPolygon: d => d.contour,
        getFillColor: d => d.color
      }),
    ]
  }
} 
    
const plainDeck = new deck.DeckGL({
  views: [new deck.OrthographicView()],
  container: 'plain',
  ...triangle([255, 0, 0])
});

console.log('pickObject', plainDeck.pickObject);

setTimeout(() => {
  console.log(plainDeck.pickObject({x: 1, y: 1, radius:1000}));
}, 1000);
```
You need delay the query action cause deck uses a callback to update gl context and create layerManager, etc.

**Comment by mccalluc** [comment]
Cool. I'm still having trouble picking objects with negative coordinates, but I haven't been able to make a small reproducer: The problem may be on my end. Closing this, but if I can understand my problem better, I'll reopen this, or reference it. Thanks!

**Comment by ibgreen** [comment]
> picking objects with negative coordinates,

We use color based picking, which means that only objects that are rendered into the "picking frame buffer" will be picked.

If by "negative coordinates" you mean objects that are outside of the screen (after projection) they won't be picked.

You'd have to make a new Viewport with bounds that encompasses all your target objects. It is certainly doable but we don't have any convenience functions to handle this case.
