### ISSUE TITLE
Layer Transition on ScatterPlot Layer

### ISSUE THREAD

**Issue by flolas** [uber/deck.gl#2720]
Hi!

I'm testing the layer transitions props for animating the radius of an scatterplot layer.

When adding transition props, the browser reports the following error:

> [.WebGL-0x7fa76681ec00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0

Someone has an example of this type of animation?

My ScatterplotLayer React Component:

> 
>         <ScatterplotLayer
>           data={this.state.data}
>           radiusScale={200}
>           pickable={true}
>           opacity={1}
>           stroked={true}
>           filled={true}
>           radiusScale={6}
>           radiusMinPixels={1}
>           radiusMaxPixels={100}
>           transitions={
>             {
>             getRadius: {
>               duration: 1000,
>               enter: t => t*1.1
>               }
>             }
>           }
>           getPosition={d => d.coordinates}
>           getRadius={d => Math.sqrt(d.monto)}
>           getColor={x => [0, 0, 255]}
>           />
> 
> 

Thanks!

**Comment by jianhuang01** [comment]
according to [doc](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=transitions-object-optional-)
use
```js
enter: t => [t[0] * 1.1]
```

**Comment by flolas** [comment]
Thanks! Im gonna test

**Comment by flolas** [comment]
@jianhuang01 The browser is reporting the same error, tested with:

```javascript
        getRadius: {
          duration: 1000,
          enter: t => [t[0]*1.1]
          }
```
,
```javascript
        getRadius: {
          duration: 1000,
          enter: t => [t[0]*1.1, 0]
          }
```
and

```javascript
        getRadius: {
          duration: 1000
          }
```

> [.WebGL-0x7fa88711be00]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 0

If I delete transitions on getRadius, it works as expected(no animations and no errors).

**Comment by jianhuang01** [comment]
@flolas check this code pen [code](https://codepen.io/jianhuang01/pen/JzjBxj), which uses deck.gl@6.4.5, and works as expected.

**Comment by flolas** [comment]
@jianhuang01 Thanks! Everything is working as expected now after updating to 6.4.5,
