### ISSUE TITLE
Mesh Layer example

### ISSUE THREAD

**Issue by galleon** [uber/deck.gl#2724]
Hello, thanks for the amazing tool.

I have been using the experimental trips layer successfully. I am now at a point where I would like to add a moving object (lat, lon, altitude) (à la threebox). I got the feeling that the mesh-layer is designed for this but I am missing documentation / example.

Am I correct ?

**Comment by Pessimistress** [comment]
Experimental layer documentation are with each layer source: https://github.com/uber/deck.gl/tree/6.4-release/modules/experimental-layers/src

**Comment by mccalluc** [comment]
I had thought I had seen a demo of this layer, but now I can't find it again... There were a few hundred small triangles randomly positioned on the screen, each doing a random walk. If this doesn't ring a bell, maybe I was looking at a different library and am confused now?

**Comment by ibgreen** [comment]
Sounds like the luma.gl [transform example](https://luma.gl/#/examples/core-examples/transform-webgl-2). That is not using meshes unfortunately. 

To whet your appetite a little: we are also adding a `ScenegraphLayer` in v7 which can show glTF models.

**Comment by mccalluc** [comment]
Yep, that's it. Thanks! / oh well. (The use case I'm trying to satisfy is to get a raster based on a matrix efficiently rendered in the background... The BitmapLayer seems to draw a square for each pixel individually, and only takes image files as input. My plan right now is to use a MeshLayer with just a single data point, rendered as a texture.)

**Comment by ibgreen** [comment]
Ideally, the `BitmapLayer` should be able to accept a luma.gl `Texture2D` instance. @xintongxia that should not be hard to support if not already implemented.

@mccalluc If you have an array of data, e.g. a typed byte array with length `width * height * 4` (rgba values for each pixels) you should be able to supply that array to the `Texture2D` constructors `data` prop and create a texture directly from data without dealing with images.
