### ISSUE TITLE
[7.0] New Module Structure

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2736]
### To Do
  - [x] Add label and assign to milestone
  - [x] Create new modules, refactor and update exports
  - [x] Update dependencies and build scripts
  - [ ] Doc update
  - [ ] What’s new update
  - [ ] Tests (node, browser, render)
  - [ ] Update examples
  - [ ] Add documentation for module structure

#### deck.gl

The deck.gl module will have ALL submodules as dependency.
All submodule exports are re-exported. The default export is `DeckGL` from `@deck.gl/react`.
The following submodules are bundled into a standalone `deck.gl.min.js`:
- @deck.gl/core
- @deck.gl/*-layers
- @deck.gl/mapbox

#### Submodule Changess

- `@deck.gl/core` has `luma.gl` as dependency.
- All other submodules `@deck.gl/*` specify `@deck.gl/core` and other peer submodules as `peerDependency`.
- Each of the following submodules will contain their own standalone bundle:
  + @deck.gl/core
  + @deck.gl/*-layers (requires the core bundle)
  + @deck.gl/mapbox (requires the core bundle)

#### @deck.gl/layers

Primitive layers that are the basic building blocks of more advanced layers.

- ScatterplotLayer
- IconLayer
- ArcLayer
- LineLayer
- PointCloudLayer
- SolidPolygonLayer
- PolygonLayer
- PathLayer
- TextLayer
- BitmapLayer
- CylinderLayer (replaces GridCellLayer and HexagonCellLayer)
- GeoJsonLayer (This is not a primitive layer, however this is so widely used that we want to keep it in the core. We will NOT add new adapter layers to this module in the future.)

#### @deck.gl/aggregation-layers

Layers that aggregate the input data into alternative representations.

- ContourLayer
- GridLayer
- _GPUGridLayer
- HexagonLayer
- ScreenGridLayer

#### @deck.gl/mesh-layers

Layers for loading and displaying 3D models.

- SimpleMeshLayer (current MeshLayer)
- SceneGraphLayer (glTF)

#### @deck.gl/geo-layers

Specialized layers supporting geospatial-only use cases and common GIS formats.

- GreatCircleLayer
- TileLayer
- KMLLayer
- TripsLayer
- S2Layer
- H3Layer
- H3Hexagon
- H3Outline
- H3Ring

**Comment by IgorWilbert** [comment]
Hey @Pessimistress ! This one seems pretty big. Would you like to team up? Perhaps I could help you updating the examples or the documentation for module structure, but if that might slow you down I'll look for some other issue :)
