### ISSUE TITLE
Migrate Minecraft Chunk Viewer Project into deck.gl

### ISSUE THREAD

**Issue by IgorWilbert** [uber/deck.gl#2743]
Hello! Seeing the showcases on deck.gl website I noticed Ascii Video Player and Wind Map are part of this code base, but Minecraft Chunk Viewer is not. I think Chunck Viewer is a very interesting and creative project, making it a valuable addition to showcases. It would also be a great opportunity to make some updates to it. @Pessimistress , the project is basically yours, what do you think of this idea? I completely understand if you would like to keep it (since I also have my own private projects) but I think it would be pretty cool to have it on deck.gl. Thanks!

**Comment by ibgreen** [comment]
@IgorWilbert It takes a lot of effort to continuously update examples to the latest API for every release. We do that for examples but not for show cases. 

Also showcases is an area where we can present external work done by others that we can't control the source code of. The MineCraft things is an example of how that works.

That said, a good PR updating the APIs for a specific showcase would probably be accepted.

**Comment by Pessimistress** [comment]
@IgorWilbert The project is using very old deck API (I believe pre-4.0). As Ib said, part of the reason we keep it apart from the main repo was because we don't have the bandwidth to continuously maintain it. I can speak more to the path to upgrade if you feel up to it :)

**Comment by IgorWilbert** [comment]
@Pessimistress yes it would be nice if you could tell me more about how to update it. I'm trying to figure out how to run it by downloading the textures only (since I don't have Minecraft on this PC). Also, could you tell me where are the textures you used to make your example [here](http://pessimistress.github.io/minecraft/) ? Thanks!

**Comment by Pessimistress** [comment]
I'll sync with you offline.

**Comment by aberenyi** [comment]
@IgorWilbert have you had the chance to work on this? I'd also be interested in an updated version of this awesome app. Cheers!
