### ISSUE TITLE
IconLayer (Autopacking) Icons losing definition when Zooming out 

### ISSUE THREAD

**Issue by Lowhearth** [uber/deck.gl#2745]
First of all  I'd like to say thanks for this amazing library.

Using IconLayer with autopacking, the icon correctly diminishes in size when Zooming out but loses significant definition  (Feels like its not using the MIPMAP filtering for minification).
This behavior is not shown when I previously pack the exact same image on a sprite, and use the prepacked atlas IconLayer configuration.
For diminishing the size of the icon I'm using a linear function that reduces the iconSize prop when zoom changes (working fine with prepacked atlas)

I've tried to follow the SourceCode of the IconLayerManager to find the root cause but had no luck.

Thanks in advance!

**Comment by xintongxia** [comment]
@Lowhearth 

1. What prop you are using to control the size of icon?
In `IconLayer`, there is a prop `sizeScale` and accessor `getSize`, which can manipulate the size of icon. Is this what you are using?

As I tried to correlate the size and zoom level, I couldn't reproduce your issue.

2. What `height` and `width` you are used in `getIcon` callback? The `height` and `width` are the size we used to pack the iconAtlas in `IconManager`.

3. Could you provide a small .gif to demonstrate the issue?

**Comment by Lowhearth** [comment]
@xintongxia 

Sorry for the delayed response, I've got all you need :

![grab-landing-page](https://media.giphy.com/media/1wPWLjUOWY6TkdA7OJ/giphy.gif)

For better resolution: https://i.ibb.co/DfMbB3n/issuedem.gif

``` import React, { Component } from "react";
import { render } from "react-dom";
import { StaticMap } from "react-map-gl";
import DeckGL, { IconLayer } from "deck.gl";

import IconClusterLayer from "./icon-cluster-layer";

const MAPBOX_TOKEN =""
const iconImage =
  "https://cors-anywhere.herokuapp.com/http://www.naturephotographysimplified.com/wp-content/uploads/2014/12/Nature-Photography-Simplified-Elements-of-Design-Diagonal-Line-On-Ground.jpg?x92028";
const DATA = [
  {
    coordinates: [28.96, 13.66033],
    name: "Al Zarnkh",
    class: "LL5",
    mass: "700",
    year: 2001
  }
];

export const INITIAL_VIEW_STATE = {
  longitude: -35,
  latitude: 36.7,
  zoom: 1.8,
  maxZoom: 20,
  pitch: 0,
  bearing: 0
};


export class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      x: 0,
      y: 0,
      hoveredItems: null,
      expanded: false,
      zoom: INITIAL_VIEW_STATE.zoom
    };
  }
  _renderLayers() {
    const { data = DATA, viewState } = this.props;
    const { zoom } = this.state;
    const layerProps = {
      data,
      pickable: true,
      wrapLongitude: true,
      getPosition: d => d.coordinates,
      getIcon: d => ({
        url: iconImage,
        width: 300,
        height: 200,
        anchorY: 0,
        mask: false
      }),
      sizeScale: 60,
      getSize: d => zoom,
      onClick: this._onClick
    };

    const layer = new IconLayer({
      ...layerProps,
      id: "icon",
      updateTriggers: {
        getSize: zoom
      }
    });

    return [layer];
  }
  onViewStateChange({ viewState }) {
    this.setState({ zoom: viewState.zoom });
  }
  render() {
    const { viewState, controller = true, baseMap = true } = this.props;

    return (
      <DeckGL
        layers={this._renderLayers()}
        initialViewState={INITIAL_VIEW_STATE}
        viewState={viewState}
        controller={controller}
        onViewStateChange={this.onViewStateChange.bind(this)}
      >
        {baseMap && (
          <StaticMap
            reuseMaps
            mapStyle="mapbox://styles/mapbox/dark-v9"
            preventStyleDiffing={true}
            mapboxApiAccessToken={MAPBOX_TOKEN}
          />
        )}

        {this._renderhoveredItems}
      </DeckGL>
    );
  }
}

export function renderToDOM(container) {
  render(<App />, container);
}
 ```

```  "dependencies": {
    "deck.gl": "^6.4.6",
    "rbush": "^2.0.1",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-map-gl": "^3.3.0"
 ```


This behaviour is not shown when I display the same image with a prepacked Atlas (using same dimensions). 
I've also tried with different images with the same result.

Thanks for your time.

**Comment by Lowhearth** [comment]
@xintongxia Thanks.
