### ISSUE TITLE
Can I only see outgoing arcs when hovering over a location rather than both the incoming and outgoing? If so, how to do it?

### ISSUE THREAD

**Issue by kngoyal** [uber/deck.gl#2751]
I tried something like in the Arcs layer

updateTriggers: {
          getStrokeWidth: d => this.state.mousePosition===d.sourcePosition ? WIDTH_SCALE(d.value) : 0,
        }

**Comment by SymbolixAU** [comment]
Have you tried the [`ArcBrushingLayer`](https://github.com/uber/deck.gl/tree/master/examples/website/brushing) examples on the website? 

From memory you would need to set the [`brushTarget: false`](https://github.com/uber/deck.gl/blob/master/examples/website/brushing/arc-brushing-layer/arc-brushing-layer.js#L31), although I may be wrong about that.
