### ISSUE TITLE
npm error when Install deck.gl

### ISSUE THREAD

**Issue by jhx646018057** [uber/deck.gl#2768]
#### Description

I downloaded the deck.gl.zip and unzipped it in my computer as folder"d:\deck.gl". When I installed it by
commond "npm install" by cmd commond , I got the following error:
d:\deck.gl>npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, fl
atted is its successor.
npm ERR! code EINTEGRITY
npm ERR! sha1-FWUb1VOme4WB+zmIEMmK2Go0Uk4= integrity checksum failed when using
sha1: wanted sha1-FWUb1VOme4WB+zmIEMmK2Go0Uk4= but got sha512-6HO1hquvSlypWhC8Vt
d56r1NiicqdOsuPNJPB8yKdqTq827sjoRbN7gYCWdQ4rIkr97Fda7be9+KBuj05fG8pA== sha1-M79/
XXKExTUL/Fx/dw+6dUnFSl4=. (2244 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j00494350\AppData\Roaming\npm-cache\_logs\2019-03-08T07_49
_25_593Z-debug.log
#### Repro Steps
I have attempted by" npm cache clean" of"npm cache clean --force" but it did't work

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.4.6]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. window 7 64bit] I also tried in Ubuntu 16.04 
Nodejs V10.15.2

**Comment by ibgreen** [comment]
@jhx646018057  Thanks for reporting. We haven't seen this, so it can be a little tricky to fix. It would first be a question of being able to reproduce this on our side. 

On your side, you could try upgrading `npm` and also try installing with `yarn` and see how that works. 

@tsherif You may have the most experience with Windows installs...

**Comment by tsherif** [comment]
I'm not familiar with this error. Looks like a package is failing an integrity check with the server?

This post suggests running `npm cache verify` and they have a few other suggested solutions: https://stackoverflow.com/questions/47545940/when-i-run-npm-install-it-returns-with-err-code-eintegrity-npm-5-3-0

Let us know if that works for you.
