### ISSUE TITLE
about deck.gl data type

### ISSUE THREAD

**Issue by pzy2253999075** [uber/deck.gl#2781]
I am studying how to use deck.gl. But I have a confusion  that what  data type can deck.gl receives. I want to show the same wifi's signal-strength in different GPS points. However，deck.gl seem to only receive the data type like [latitude，longitude，counts] ，could someone tell me is  it possible to  design our  data type  or  to  Implement my project in another way with deck.gl.Thank you very much

**Comment by Pessimistress** [comment]
deck.gl does not make any assumptions about data format. See [documentation](http://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer) of the layers you want to use.

**Comment by pzy2253999075** [comment]
could you tell me  which kind of layer should I use in project ? I think  GridCellLayer can, right? Thank for your  answer once again.@Pessimistress
