### ISSUE TITLE
how to choose  layer  in different situation

### ISSUE THREAD

**Issue by pzy2253999075** [uber/deck.gl#2782]
I am learning deck.gl. And  I have scanned the tutorial in deck.gl website. Now I have a question about that how to choose proper  layer in different  situation.  In my case,I want to show the same wifi's signal-strength in different gps points ,  so I should  feed this three data [lat, lnt, wifi_signal_strength] to my layer. I want someone to tell me which layer should I choose or the details that how to implement my project in another way with deck.gl in my case .   I will appreciate all you guys.

**Comment by mayteio** [comment]
In this case, you would want to recreate the layers array based on state.

```
const layers = [...]
const renderLayers = strength => layers.filter(l => l.strength === strength);
```

**Comment by pzy2253999075** [comment]
Thank for your answer  @mayteio ，I am new to deck.gl, can I ask you one more question ,the red Frame In the picture below  is the place to set my data format。
![image](https://user-images.githubusercontent.com/15712923/54406117-d8471a80-4713-11e9-96ee-878b3a5cb675.png)

**Comment by mayteio** [comment]
Yep! Create a function to return the array as above instead of passing an array directly into DeckGL component.

**Comment by pzy2253999075** [comment]
ok, thank you @mayteio
