### ISSUE TITLE
H3_angle

### ISSUE THREAD

**Issue by Slawlight** [uber/deck.gl#2797]
I have used h3 to visualize  the heatmap in deck.gl, but how can I get the angle? I have used the prop hexagonVertices of HexagonCellLayer, it is no use.

**Comment by tgorkin** [comment]
Hi @Slawlight, can you elaborate a bit on what angle you are referring to and what you are trying to do?  We have an official H3HexagonLayer and H3ClusterLayer coming very soon in the deck.gl 7.0 release.  You can view their docs here:
https://github.com/uber/deck.gl/blob/master/docs/layers/h3-hexagon-layer.md
https://github.com/uber/deck.gl/blob/master/docs/layers/h3-cluster-layer.md
