### ISSUE TITLE
export GLTFInstantiator was not found in luma.gl where I npm run dev

### ISSUE THREAD

**Issue by Zhangliquan94** [uber/deck.gl#2800]
![image](https://user-images.githubusercontent.com/43436613/54415239-a6937b00-4736-11e9-83fe-e3efb4533271.png)

**Comment by Zhangliquan94** [comment]
[project address](https://github.com/sakitam-gis/ycyfans-map)

**Comment by tgorkin** [comment]
I believe this is fixed, but please reopen if not.
