### ISSUE TITLE
How to enable antialiasing for deck.gl custom layers?

### ISSUE THREAD

**Issue by jasonsoden** [uber/deck.gl#2809]
In February, mapbox-gl-js [added support](https://github.com/mapbox/mapbox-gl-js/issues/7543) for the [antialias flag](https://github.com/mapbox/mapbox-gl-js/commit/ed3d0e10ad36050e4ea63deb4c1b0733ac6a0e32) but I'm not sure how to use it.

![image](https://user-images.githubusercontent.com/8482503/54480858-fc295f80-47ea-11e9-94ae-8aebbee1bea5.png)

![image](https://user-images.githubusercontent.com/8482503/54480999-67bffc80-47ec-11e9-987c-64b391d7c65c.png)

Any suggestions? I'm experiencing jagged edges everywhere I've tested the custom layer. 

- Windows 10 (4k tv, 1440p monitor, Surface Book)
- iOS (iPad 12.9" Pro, iPhone 6 Plus)
- Android (OnePlus 3)
- Chrome, Firefox, Edge, Opera, Safari

The issue is less extreme with Retina Display but still happens. I'm using @deck.gl/react 6.4.7.

**Comment by jasonsoden** [comment]
I tried to tell luma.gl to enable [browser antialias](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) but this didn't work either.
```
<Deck glOptions={{ antialias: true }}>
```

**Comment by Pessimistress** [comment]
The antialias flag was not applied to custom layers, as fixed by https://github.com/mapbox/mapbox-gl-js/pull/7821. This commit has not been released by mapbox. We are actively tracking its progress.

**Comment by sibbl** [comment]
The PR from mapbox's side is closed now and the fix was released with mapbox a few months back already. However, I still run into this issue using the latest version of all involved npm modules.

**Comment by Pessimistress** [comment]
@sibbl The `antialias` option is default to `false` on Mapbox's side. You must manually enable it by supplying `mapOptions: {antialias: true}` to the `MapGL` component.

**Comment by sibbl** [comment]
@Pessimistress that's exactly what I did, but it didn't change anything. Is there a reason why mapbox-gl@0.54.0 is skipped by react-map-gl as the fix mentioned above is only in this and newer versions? Manually installing this specific version also didn't help unfortunately.

**Comment by Pessimistress** [comment]
@sibbl you can try react-map-gl 5.0.0 which uses mapbox-gl 1.0.0. I will also publish a patch of react-map-gl if you want to stay on the 0.xx track.
