### ISSUE TITLE
Icons on Icon Layer jump between global maps (repeating earth map) at incorrect time / location for far out zoom

### ISSUE THREAD

**Issue by rocos-david** [uber/deck.gl#2817]
Icons on Icon Layer jump between repeating maps at incorrect location at far out zoom.

#### Repro
Add icon layer over somewhere like New Zealand (likely edge of the repeating map).  Zoom out to 0 to 3 level.  Move map left and right.

See this video: https://www.useloom.com/share/3d760d4b3e284ee4a20d58ada44fa70b

#### Environment 
Framework Version: deck.gl 6.4.7 (previous 6.3 also did this)
Browser Version: Latest Chrome
OS: Windows 10

**Comment by Pessimistress** [comment]
You can set the [wrapLongitude](http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=wraplongitude-boolean-optional-) prop to `true` in this case.

**Comment by rocos-david** [comment]
Thanks @Pessimistress that has solved it.
