### ISSUE TITLE
3d-heatmap bug

### ISSUE THREAD

**Issue by Slawlight** [uber/deck.gl#2827]
#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

#### Logs

I did npm install and npm start, then:

<img width="1412" alt="屏幕快照 2019-03-22 下午4 30 53" src="https://user-images.githubusercontent.com/18410535/54810108-2fbf2a80-4cc0-11e9-9973-827413b49283.png">

**Comment by jianhuang01** [comment]
check out [6.4-release](https://github.com/uber/deck.gl/tree/6.4-release) branch, use yarn and npm run start, should work.
