### ISSUE TITLE
render lag between mapbox and deckGL

### ISSUE THREAD

**Issue by kyehuelin** [uber/deck.gl#2831]
#### Description
https://github.com/kyehuelin/dgl-lag (created a demo repo as example)
expected - perfect sync between map and deck GL (is ok in older demos available online)

actual - weird lag between mapbox and deckGL

Seems to be a bug but I maybe doing something wrong.

#### instructions::

Safari.(severe)
  - shake the viewport around and rotate and the map and 3d become un synced.
  - happens when resizing window.
  - Happens when camera in transit.

Chrome / firefox (not so bad but still a problem)
(is ok when shaking viewport around (unlike safari))
  - lags in camera transit.
  - Lags when resizing window

#### Repro Steps
Usual npm install process

#### Environment (please complete the following information):
 - Framework Version:     "deck.gl": "^6.4.7",
 - Browser Version: safari Version 12.0.3  /  chrome Version 73.0.3683.86
 - OS: mac OSX.  10.12.6 sierra

**Comment by kyehuelin** [comment]
@ibgreen  : sorry to single you out. any thoughts on this?

**Comment by jianhuang01** [comment]
Can you check [line example](https://github.com/uber/deck.gl/tree/6.4-release/examples/website/line), didn't find any lag issue there.

**Comment by kyehuelin** [comment]
Thank you.

I did some tests with the line demo, 

I can confirm that the issue is react-map-gl . 

all versions of 4.x.x have this render lag perfermance issue. and all versions of 3.x.x are fine.

if you want to see the bug for yourself, just switch out react-map-gl to v4 in the line demo and youll see what I mean. 

I have rolled back to 3..9.0 in my main project and things are running perfect now.

**Comment by kyehuelin** [comment]
@jianhuang01 ive got another bug where if i put multiple layers in in deckGL (one geoJson, one hexBin) the onHover flickers on and off, even though I set one the layers to 'pickable: false' shall i create a new bug report?

**Comment by jianhuang01** [comment]
@kyehuelin yeah, create a new bug with the gif and reproduce steps, please. Thanks!

**Comment by ibgreen** [comment]
>  ibgreen : sorry to single you out. any thoughts on this?

@kyehuelin 

Thanks for reporting as always and apologies for the slow response, we have been heads down doing final integration for the v7 releases.

Now that we are going into the v7 stabilization cycle we will be working through these bugs, so we should have more to say soon. I believe we have already been making progress, at least on the hover issue.

**Comment by kyehuelin** [comment]
@ibgreen Great to hear that progress is being made. Thank you for the hard work and contribution.

**Comment by Pessimistress** [comment]
@kyehuelin This is a complex issue that spans two libraries.

We have rolled out a patch of react-map-gl 4.1 that added an option to mimic 3.x behavior. Set the [asyncRender](https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map?section=render-options) prop of your `<StaticMap>` to `true` should solve your problem.

react-map-gl v4's default behavior will work with deck.gl 7.0.

**Comment by Oussema-Dallel** [comment]
This shouldn't be closed as setting the asycnRender to true makes the map flash when resizing...

**Comment by Pessimistress** [comment]
@Oussema-Dallel this issue is 3 years old. The versions of react-map-gl and deck.gl that were discussed here are no longer maintained. If you have issues with the latest release, please open a new conversation.

**Comment by DeepUpRosenthal** [comment]
This still happens to me with 

    "react-map-gl": "^7.1.6",
    "deck.gl": "^8.9.31",

https://github.com/visgl/deck.gl/assets/112082731/6a68af93-4aed-4040-876e-f362d31258e5

I have managed initialViewState via Valtio.

```typescript
<DeckGL
        controller
        width="100%"
        height="100%"
        initialViewState={{ ...viewport }}
        onViewStateChange={(vs) => setViewport(vs.viewState as Viewport)}
        layers={allLayers
          .filter((l) => visibleLayerNames.includes(l.name))
          .map(renderLayer)}
      >
        <Map
          mapboxAccessToken={MAPBOX_ACCESS_TOKEN}
          mapStyle={"mapbox://styles/mapbox/dark-v10"}
        />
      </DeckGL>
```

Can anybody point me in the direction to fix this?
