### ISSUE TITLE
[7.0] Light Effect Punch List

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2833]
#### To Do List
  - [x] Update all examples to match previous visual
  - [x] Integrate lighting with mesh layer
  - [x] Documentation
	- [x] All mentioning of `PhongMaterial` should link to luma docs
    - [x] Create one page for each `Light` class
    - [x] "Using Lighting" page in developer guide
  - [x] Investigate lighting+picking performance
  - [x] CameraLight class
  - [ ] LightEffect example
    - [ ] Example shadow effect
    - [x] SunLight class

**Comment by Pessimistress** [comment]
`LightingEffect` does not work in production. After running through uglifyJS, `lightSource.constructor.name` will be lost:

https://github.com/uber/deck.gl/blob/master/modules/core/src/effects/lighting-effect.js#L31

**Comment by ibgreen** [comment]
For unrelated reasons (relating to glTF light extension support and a more robust shader module API), I added a `type` field to the luma.gl light classes, looks like it could be used to fix this issue.

https://github.com/uber/luma.gl/blob/master/modules/core/src/lighting/light-source.js#L29

**Comment by Pessimistress** [comment]
> I added a type field to the luma.gl light classes

I think that would be the safe way to go forward, as we will have multiple implementations of the same light type (e.g. sun is directional, and camera light is point).
