### ISSUE TITLE
ScreenGridLayer not rendering

### ISSUE THREAD

**Issue by mendozaline** [uber/deck.gl#2841]
#### Description
The ScreenGridLayer is not getting displayed on my map. I'm able to render the ScatterplotLayer on the same map using the same data. 

I also noticed that the ScreenGridLayer examples in the deck.gl documentation are also not displaying [here](https://deck.gl/#/documentation/deckgl-api-reference/layers/screen-grid-layer) and [here](https://deck.gl/#/examples/core-layers/screen-grid-layer).

#### Repro Steps
Here's a CodeSandbox example: [https://codesandbox.io/s/539vl35404](https://codesandbox.io/s/539vl35404)

#### Environment (please complete the following information):
deck.gl 6.4.7 
react-map-gl 4.1.1
react 16.8.3

**Comment by jianhuang01** [comment]
actually all the examples work well on my computer, check this thread #2566 for more details.

**Comment by mendozaline** [comment]
Yup, that was the problem. I set `gpuAggregation` to `false` and it solved the issue. Thank you!
