### ISSUE TITLE
Trips layer with elevation

### ISSUE THREAD

**Issue by dcooley** [uber/deck.gl#2857]
#### Target Use case & feature

GPS tracking data from apps such as strava & garmin contain elevation and time for each lon/lat coordinate. Can the `TripsLayer` example be extended to to include elevation? This would allow trips to be animated over terrain too

The `PathLayer` allows elevation, but it's defined as a `vec3` (I think, to allow elevation data). Can this be made a `vec4`, where the 4th element represents time?

Then the [trips layer](https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/trips-layer/trips-layer.js#L38) can retain the `.z` element, and the `trail` applied to the `.w` element.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
This is supported in 7.1.1 by adding a `getTimestamps` prop.
