### ISSUE TITLE
Trips example without timestamps

### ISSUE THREAD

**Issue by melvinraju** [uber/deck.gl#2858]
I have a data set which only has lat, long coordinates but no time stamp. There are start and end times as separate features, but no timestamp for each coordinate. How do I make the animation run without anytime stamps, assuming each route will have the same speed? 
Thanks

**Comment by ctriley** [comment]
If you have the lat/lon coordinates, and the start and end time, I would get the distance between each point as a fraction of the total distance and multiply this by the total time to get an approximation for the amount of time spent on each line segment. This way you can create times for the intermediate points.

**Comment by melvinraju** [comment]
Is there no way to simply disable the timestamp function?

**Comment by dcooley** [comment]
The animation has to know where to go from and to, and how long to take to get there. How do you intend to animate trips without a timestamp?

**Comment by melvinraju** [comment]
I was wondering if it would be possible to use the frame rate to call a number of coordinates. This will obviously mean all the tracks will start at the same time as there is no timed trigger.

**Comment by mayteio** [comment]
I have to do the same for some GeoJSON LineStrings. I've put together this function but it's not quite right. It correctly generates the trips (usage: `getPath: d => d`), however, they seem to stutter when animated against time. 

Relies on `@turf/helpers`, `@turf/length` and `@turf/distance` to calculate sizes between coordinates.

```
function getTripsFromGeoJson(geojson) {
  const trips = [];
  const TOTAL_TIME = 1800;

  for (let i = 0; i < geojson.features.length; i++) {
    const route = geojson.features[i];
    const totalLength = length(route);
    const segments: any = [];
    let time = 0;

    // loop through coordinate points
    const { coordinates } = route.geometry;
    for (let index = 0; index < coordinates.length; index++) {
      // if there's no next coordinate, we're at the last coordinate.
      if (!coordinates[index + 1]) continue;

      // get points for turf to calculate distances
      // >> If you have the lat/lon coordinates
      const current = coordinates[index];
      const currentCoordinate = point(current);
      const nextCoordinate = point(coordinates[index + 1]);

      // get distance between
      // >> I would get the distance between each point
      const distanceBetween = distance(currentCoordinate, nextCoordinate);

      // get fraction of the total length
      // >> as a fraction of the total distance
      const fraction = distanceBetween / totalLength;

      // get time spent in particular
      // >> and multiply this by the total time
      // >> to get an approximation for the amount of time spent on each line segment.
      const timeInSegment = fraction * TOTAL_TIME;

      // add the time for the next iteration
      // >> This way you can create times for the intermediate points.
      time = time + timeInSegment;

      // push the coordinates and time onto the stack
      segments.push([current[0], current[1], time]);
    }
    trips.push(segments);
  }

  return trips;
}
```

Has anyone created an algorithm that takes an array of coordinates and spits out correct data for the Trips Layer to animate smoothly? @ctriley 

@melvinraju if performance is a problem maybe consider a Web Worker?
