### ISSUE TITLE
createGLTFObjects in 7.0.0.0-beta.1

### ISSUE THREAD

**Issue by galleon** [uber/deck.gl#2859]
It seems that there is a problem in dependencies using latest beta. 

./node_modules/@deck.gl/mesh-layers/dist/esm/scenegraph-layer/scenegraph-layer.js
Attempted import error: 'createGLTFObjects' is not exported from '@luma.gl/core'.

**Comment by bbss** [comment]
I'm having similar issues, luma.gl version is too new for deck.gl. Deck.gl/luma.gl are in heavy flux now as uber team seems to be wrapping up the v7.0.0 release. I regret deleting my yarn.lock file, as for some reason yarn nor npm let me install specific versions correctly, my guess is it's to do with nested module dependency structure in these projects.

@galleon assuming you have the same problems as I do: if the need is high for you you might be able to figure things out from lock file info: 
https://github.com/uber/deck.gl/pull/2855

**Comment by ibgreen** [comment]
@galleon @bbss Apologies for the churn, the 7.0.0 release has indeed required a lot of integration work as it spans a number of frameworks. 

The good news is that we expect the deck.gl beta release to be stable Monday next week, and at that time we will be very interested in getting early testing feedback and should be able to help with specific issues you might be facing.
