### ISSUE TITLE
Altering elevation of columns over time

### ISSUE THREAD

**Issue by ctriley** [uber/deck.gl#2860]
I am simulating a transportation system which has multiple stops. At each stop, I want to put a column, which displays the number of people waiting at said stop for that particular time. Therefore, I'd like to be able to dynamically change the height of my columns over time. I understand how to generate a column layer with static column heights, but I'm unsure how to make these heights dynamic. Any help would be appreciated -- I'm very new to this.

Thanks!

**Comment by xintongxia** [comment]
Are you using [`ColumnLayer`](https://github.com/uber/deck.gl/blob/master/docs/layers/column-layer.md)?

There is an accessor [`getElevation`](https://github.com/uber/deck.gl/blob/master/docs/layers/column-layer.md#getelevation-functionnumber-optional-) you can use to dynamically change the elevation of your data points.

**Comment by ctriley** [comment]
I know I can pass a function to get elevation, but how do I trigger updates to the elevation using that function? I'm trying to update the elevation at the same rate as the trip layer updates, so that I can keep the trip data and the columns (people waiting at stops) synchronized.

**Comment by ctriley** [comment]
If anyone wants to know how to do this, you have to use an updateTrigger. This is a field which you can find in the documentation here: https://github.com/uber/deck.gl/blob/master/docs/api-reference/layer.md

**Comment by tgorkin** [comment]
Closing issue, let us know if its not resolved or documentation needs improvement.
