### ISSUE TITLE
Will IconLayer do some throttle operation to improve the performances?

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#2868]
I follow the APIs in `IconLayer`, and return it from a customized `CompositeLayer`. In order to make the icon animating with time, I update icon's coordinates of icons inside `updateState` lifecycle, and use `window.requestAnimationFrame` API to loop it.

However, when I print the coordinates inside `window.requestAnimationFrame` and `renderLayers` method, I found the former one will update more frequently than the later one. So the animation may not be frequent as 60fps, so I want to know if IconLayer itself did some improvements to prevent frequent updates from outside, like throttle function in vanilla JavaScript function?

Thanks.

**Comment by hijiangtao** [comment]
Besides, I will not face this problem if I manually update the data passed into IconLayer (as props).

The way I update icons' coordinates is some way like this (keep `steps` increase by time):

*Tips: The outer class is a customized layer extends from `CompositeLayer`*

```javascript
initializeState() {
    this.state = {
      steps: 0,
      raf: null,
      MAX_STEPS: 1,
      animationLoop: false,
    };
}

updateState({ props, oldProps, changeFlags }) {
      super.updateState({ props, oldProps, changeFlags });
      const { propsChanged, stateChanged, dataChanged } = changeFlags;
      const { data = {} } = props;
      const { configs = {} } = data;
      if (configs.showIconFly) {
        /**
         * Animaiton trigger judgement
         */
        if (props.data.icons && props.data.icons.length) {
          const { raf } = this.state;
          // eslint-disable-next-line no-unused-expressions
          raf && cancelAnimationFrame(raf);
  
          /**
           * Point Spread Animation Method
           */
          const startAnimation = () => {
            const { speed = 0.0004 } = props;
            // eslint-disable-next-line prefer-const
            let { steps } = this.state;
            steps += speed;
  
            if (steps >= 1) {
              steps = 1;
              cancelAnimationFrame(raf);
            }
  
            this.setState({ 
              steps,
            });

			// HERE: This line will print steps' value in each frame
            console.log(steps); 
  
            if (steps < 1) {
              const newRaf = window.requestAnimationFrame(startAnimation);
              this.setState({
                raf: newRaf,
              });
            }
          };
  
          startAnimation();
        }
      }
}

renderLayers() {
	const {steps} = this.state;
	
	// HERE: This line will skip steps' value by some frame
	console.log(steps);
}
```

Keep look at the two `HERE` line in above codes, they will reproduce my above description about the *not so frequent* situation.

Thanks.

**Comment by ibgreen** [comment]
To avoid rerendering when not necessary (and keep the computer's fans silent) deck.gl does a dirty check every time the animation loop fires.

There is no throttling in the layers. 

If you want to draw every frame, you can use the experimental `_animate` prop: https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/deck.js#L80
