### ISSUE TITLE
Legend values when using manual colors

### ISSUE THREAD

**Issue by victorhdc** [uber/deck.gl#2870]
Is there a way to specify a character column for legend values, when using manual hex string colours?
Using the manual colours example:
https://symbolixau.github.io/mapdeck/articles/colours.html#manual-colours
sf$my_colour <- ifelse( substr(sf$SA2_NAME, 1, 1) == "A", "#00FF00FF", "#FF0000FF")
mapdeck( ) %>%
  add_polygon(
    data = sf
    , fill_colour = "my_colour"
  )
When a legend is included, the legend values are the hex color strings. How can I use a different column for legend values?

**Comment by SymbolixAU** [comment]
I think you've posted this to the wrong issue tracker, I think you mean to put it on the [mapdeck](https://github.com/SymbolixAU/mapdeck/issues) page

**Comment by victorhdc** [comment]
Thank you, my bad
