### ISSUE TITLE
Get pixels in First?Third Person view

### ISSUE THREAD

**Issue by galleon** [uber/deck.gl#2874]
Hello

I am looking at capturing the buffer of pixels displayed in a FirstPersonView - so that I can apply some machine learning algorithm onto them.
Is there a way do to that?

**Comment by ibgreen** [comment]
Yes, you'd use normal DOM APIs, e.g. if you have access to the canvas or gl context, then you can do [`canvas.toDataURL()` or `gl.canvas.toDataURL()`]( https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).

Unless you are passing those in, you can get those in different ways e.g. by defining the `onWebGLInitialized` callback.
