### ISSUE TITLE
help,cant run examples,webpack question

### ISSUE THREAD

**Issue by houxieyu** [uber/deck.gl#2882]
example 3d-heatmap cant running.
npm install is ok,mapboxaccesstoken is ok,but npm start cant work,below is report!

ERROR in ./app.js
Module build failed (from ./node_modules/buble-loader/index.js):
BubleLoaderError: 
125 :     const {viewState, controller = true, baseMap = true} = this.props;
126 : 
127 :     return (
128 :       <DeckGL
129 :         layers={this._renderLayers()}
                    ^
Unexpected token (129:14)
    at Object.module.exports (D:\我的桌面\decksrc\deck-gl\examples\website\3d-heatmap\node_modules\buble-loader\index.js:24:69)
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./app.js app[2]

**Comment by jianhuang01** [comment]
use "yarn" instead of "npm install" for now
