### ISSUE TITLE
async/await does not work inside modules/mesh-layers/src

### ISSUE THREAD

**Issue by georgios-uber** [uber/deck.gl#2885]
#### Description
async/await does not work inside modules/mesh-layers/src

#### Repro Steps
Convert modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js fetch function to use async/await

**Comment by tsherif** [comment]
Maybe the JS version used by the transpiler?

**Comment by ibgreen** [comment]
Do we all want deck.gl to use ES2018 syntax in the deck.gl code base? I am getting different signals.

I made changes to loaders.gl and luma.gl that updated lint settings and other things to make it work, I could try to do the same in deck.gl.

**Comment by georgios-uber** [comment]
Deck.gl currently does not use async/await and using it actually breaks the code.
We need to decide if we want to use it and setup our code base to work with it.
