### ISSUE TITLE
Walls of extruded polygons are transparent

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#2894]
#### Description

Walls of extruded polygons are transparent when specifying a transition duration greater than zero, but without actually using the transition. 

A live version showing this issue is [hosted here](https://symbolix.shinyapps.io/debuggingdeckgl/) where you can access the console logs. 

Here is a screenshot of what's happening. 

![Screen Shot 2019-04-03 at 1 25 47 pm](https://user-images.githubusercontent.com/18344164/55448604-0da89f00-5614-11e9-947f-af82794adc63.png)

In the console, for each map I am logging

- `Object` : the transition object
- `l` : the `PolygonLayer` object

The map on the left has `transitions: { getElevation: 0 }` 
The map on the right has `transitions: { getElevation: 600 }`

Therefore I am setting the `transition` prop, but not actually using it in either of the maps.

This has only been happening since v7.0.0-beta. Previous versions have worked as intended

The data is the same in both maps - [widget_melbourne.json](https://github.com/SymbolixAU/debugging/widget_melbourne.json) - a geojson file of polygons in Melbourne

#### Environment

 - Framework: deck.gl 7.0.0-beta.1 (https://unpkg.com/deck.gl@7.0.0-beta.1/dist.min.js)
 - Browser:  Chrome version 73.0.3683.86 (Official Build) (64-bit)
 - Mac OS X 10.14.1 (Mojave)

**Comment by 1chandu** [comment]
@SymbolixAU , what layers are you using, is this specific to one layer?  Can you reproduce this with any of the standalone [examples](https://github.com/uber/deck.gl/tree/master/examples/website) provided in the repo, if so it will be easy for us to reproduce and debug.

**Comment by dcooley** [comment]
@1chandu (I'm on my other github account) 

Here's a [codepen](https://codepen.io/dcooley/pen/vMJxpe) which demonstrates the issue. 

The code i'm using is

```js

/** Data **/
const data = [
  {
	  // Simple polygon (array of coords)
	  contour: [[-122.4, 37.75], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.75], [-122.4, 37.75]],
	  elevation: 3000
  }
];

/** DeckGL **/
new deck.DeckGL({
  container: 'container',
  mapboxApiAccessToken: 'pk.eyJ1IjoidWJlcmRhdGEiLCJhIjoidGllX1gxUSJ9.gElUooDF7u51guCQREmAhg',
  mapStyle: 'mapbox://styles/mapbox/dark-v9',

  // mapbox: false, /* disable map */
  longitude: -122.45,
  latitude: 37.8,
  zoom: 11,
  pitch: 30,
  layers: [
    new deck.PolygonLayer({
    id: 'polygon-layer',
    data,
    pickable: true,
    stroked: true,
    filled: true,
    wireframe: true,
    extruded: true,
    lineWidthMinPixels: 1,
    getPolygon: d => d.contour,
    getElevation: d => d.elevation,
    getFillColor: [255,0,0],
    getLineColor: [80, 80, 80],
    getLineWidth: 1,
    transitions: { getElevation: 600 }
  })
  ]
});

```

And a screenshot

![Screenshot from 2019-04-13 13-27-32](https://user-images.githubusercontent.com/8093396/56074088-ed38cb80-5def-11e9-92eb-167b26634193.png)

using https://unpkg.com/deck.gl@7.0.0-beta.3/dist.min.js

**Comment by Pessimistress** [comment]
An attribute transition bug was fixed in beta.4 - give it a try?

**Comment by Pessimistress** [comment]
@SymbolixAU This is fixed in 7.0.3.

**Comment by dcooley** [comment]
@Pessimistress yes it appears so; I'll be testing this on other layers too and will let you know if there are any other issues

**Comment by Pessimistress** [comment]
Closing for now, reopen if there're further issues with this
