### ISSUE TITLE
Width in TripsLayer

### ISSUE THREAD

**Issue by ctriley** [uber/deck.gl#2895]
I cannot figure out how to increase the width of the path lines in the trip layer. This features seems to have been merged into master 13 days ago (based on Issue [#2708](https://github.com/uber/deck.gl/pull/2708)). However, I'm on the newest version (6.4.9) which seems to be based on code from 5 days ago, and adding a `width` field to trip layer doesn't seem to have any effect.

I've pasted the code snippet below.

```
new TripsLayer({                                                          
          id: 'trips',                                                            
          data: trips,                                                            
          getPath: d => d.segments,                                               
          getColor: d => d.color,                                                 
          opacity: 0.3,                                                           
          width: 5,                                                             
          trailLength,                                                            
          currentTime: this.state.time                                            
        }), 
```

I've also tried using fields ```getWidth``` and ```strokeWidth```

**Comment by SymbolixAU** [comment]
perhaps try the beta release of v7.0.0 - https://unpkg.com/deck.gl@7.0.0-beta.1/dist.min.js

**Comment by jianhuang01** [comment]
@ctriley we don't port new features to 6.4.9 release branch, the TipsLayer width feature is only for v7.0.0 release.
