### ISSUE TITLE
WebMercatorViewport.unproject() produces incorrect results

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#291]
Test case:
https://github.com/uber/deck.gl/blob/viewport-fix/test/lib/viewports/web-mercator-viewport.spec.js
(uncomment line 44 - 49)

```
not ok 41 unproject (center)
  ---
operator: deepEqual
expected: |-
  [ -122.43, 37.75 ]
actual: |-
  [ -122.43, 37.675038961 ]
```

I expect the result of `unproject` reverses that of `project`.

**Comment by shaojingli** [comment]
@ibgreen can we close this based on #519 ?
