### ISSUE TITLE
How to run a independent layer?

### ISSUE THREAD

**Issue by chengyanyan0625** [uber/deck.gl#2916]
Excuse me, I am learning deck.gl. I want to run a GridCellLayer (https://deck.gl/#/documentation/deckgl-api-reference/layers/grid-cell-layer). But I don't how to run it. I will appreciate it if you can answer my question.

**Comment by 1chandu** [comment]
@chengyanyan0625 , you can build and run the examples as described here in this [doc](http://deck.gl/#/documentation/getting-started/installation?section=installation)

Regarding `GridCellLayer`, we don't have a standalone example but you can look at [3d-heatmap](https://github.com/uber/deck.gl/tree/master/examples/website/3d-heatmap) example, it uses `GridLayer` which internally uses `GridCellLayer`. You can always clone the repo, and modify any of these example to use a different layer and data.

**Comment by chengyanyan0625** [comment]
> @chengyanyan0625 , you can build and run the examples as described here in this [doc](http://deck.gl/#/documentation/getting-started/installation?section=installation)
> 
> Regarding `GridCellLayer`, we don't have a standalone example but you can look at [3d-heatmap](https://github.com/uber/deck.gl/tree/master/examples/website/3d-heatmap) example, it uses `GridLayer` which internally uses `GridCellLayer`. You can always clone the repo, and modify any of these example to use a different layer and data.

Thank you for your answer, I have run it. One more question, I want to show it dynamically in real time. I know that I need use 'react', But What I should refer to?

**Comment by 1chandu** [comment]
>  I want to show it dynamically in real time. I know that I need use 'react', But What I should refer to?

I don't quite get it, if you are asking about building using React API, yes you can, above and several other examples use the React API.
