### ISSUE TITLE
Beta release of pydeck, Python bindings and Jupyter notebook widget for deck.gl

### ISSUE THREAD

**Issue by ajduberstein** [uber/deck.gl#2929]
#### Target use case
Enable Python developers to use deck.gl

#### Proposed feature

A Python wrapper around deck.gl and Jupyter notebook integration, see https://github.com/uber/deck.gl/pull/2747

See #3013 and #3035 and for the associated pull requests.

#### v7.3 end of Aug
- [x] Publish NPM module for Jupyter widget P0
- [x] Modify notebook demos to include 2 way interaction and a tooltip
- [x] Verify installation on 2.7
- [X] Python-only (one-way API outside notebook) P2
- [X] Make pydeck notebooks work on github P2

#### v7.2 end of June
- [x] Publish pydeck to official PyPI P0
- [x] Markdown Documentation (awaiting API review) P1
- [x] Solve versioning issue (kernel)
- [X] Create example notebook, interactive P0
- [X] Create example notebook non-interactive P0 
- [x] IframeWidget - P1
- [x] Persist state for a visualization through a restart of the kernel P1 (sort of a no-op, a user has to specify "Save Widget State" through the browser UI)
- [x] In a notebook, change the visualization on pydeck configuration change
- [x] Publish pydeck to test.PyPI P0 
- [x] Travis CI for Python P0
- [x] Remove the Typescript
- [x] Replace karma with tape in JS tests
- [x] Make into a scoped module, `@deck.gl/jupter-widget`
- [X] Python tests as pre-commit hooks

#### TBD
- [ ] Use NPM module in hosted notebook build
- [ ] Sphinx Documentation P2
- [ ] Binary arrow data transfer P1
- [ ] Save a canvas out to an image
- [ ] Add screen diff tests
- [ ] Add more explicit error handling

**Comment by ajduberstein** [comment]
Breaking #2750 into two pull requests–one for Python objects that wrap the deck.gl JSON API and one for a Jupyter widget. JSON bindings are at #3013.

**Comment by ajduberstein** [comment]
Interactive updates available in https://github.com/uber/deck.gl/pull/3174, addresses ` In a notebook, change the visualization on pydeck configuration change`

**Comment by ajduberstein** [comment]
**Known Issues**

### .show() renders one immovable widget per chart and kernel

A Deck object can only run r.show() once in a notebook and can’t be moved without clearing out the notebook.

Code snippet to reproduce:
```
Import pydeck as 

layer = pdk.Layer(
    'HexagonLayer',
    UK_ACCIDENTS_DATA,
    elevation_scale=50,
    elevation_range=[0, 3000],
    extruded=True,                 
    coverage=1)

# Set the viewport location
view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=6,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.396)

# Combined all of it and render a viewport
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.show() ```

Run `r.show()` in a different cell and it won’t render.

**Comment by ibgreen** [comment]
> For example, below the notebook cell renders and then produces an error not seen outside the console:

A very rough mechanism (not deck.gl specific) is to bind `window.onerror` which gets called on uncaught exceptions.

**Comment by ajduberstein** [comment]
pydeck beta is released. Improvements will be tracked in #3640

**Comment by ajduberstein** [comment]
Quick gallery:

![beijing](https://user-images.githubusercontent.com/2204757/65288557-19254f00-dafc-11e9-924e-1dd228c5abdb.gif)
![Conway](https://user-images.githubusercontent.com/2204757/65289355-242dae80-daff-11e9-9e9b-717b1918d0ee.gif)
