### ISSUE TITLE
calling pickObjects on ref to DeckGL component results in error: "Cannot read property 'pickObjects' of null".  Is there something I'm missing here?

### ISSUE THREAD

**Issue by ToddJacobus** [uber/deck.gl#2956]
First, thanks for developing this amazing library.  I hope I can contribute in some way.  My question:

I'm simply trying to "pick" all rendered features within the current viewport and return information on each, using the pickObjects method on the DeckGL class.  Here is my component structure using React:

NOTE: this component is a child of a ReactMapGL component used to render the map.  Everything has been rendering just fine with no issue.
```
class Overviews extends Component {
  constructor(props) {
    super(props);
    // I'm using this ref to access methods on the DeckGL class
    this.deckRef = React.createRef();
  }

  componentDidMount() {
    this.props.fetchArticles() // Redux action that fetches data from external API

    // This line causes the error, of course.
    // Uncaught TypeError: Cannot read property 'pickObjects' of null
    console.log(this.deckRef.pickObjects({x:0, y:0}));
  }

  render() {
    const layer = new GeoJsonLayer({
      id: 'articles-layer',
      data: this.props.articles.features,
      pickable: true,
      opacity: 0.8,
      pointRadiusScale: 30,
      radiusMinPixels: 50,
      radiusMaxPixels: 100,
      getPosition: d => [d.coordinates[0], d.coordinates[1]],
      getFillColor:[245, 230, 83],
      getRadius: 1000,
      getLineWidth: 3,
    })
   
    return (
      <div>
        <DeckGL
          view={this.props.viewport}
          layers={layer}
          viewState={this.props.viewport}
          ref={ deck => this.deckRef = deck}
        />

      </div>
    )
  }
};

```

My initial thought, is that DeckGL is trying to pick features that aren't there yet, but I feel like the error is saying that my React ref (deckRef) is null.  However, when I add `console.log(this.deckRef.pickObjects)` it clearly returns the function:

```
ƒ pickObjects(_ref3) {
      var x = _ref3.x,
          y = _ref3.y,
          _ref3$width = _ref3.width,
          width = _ref3$width === void 0 ? 1 : _ref3$width,
          _ref3$height = _ref3.heig…
```

I'm confused why the function would be there, on my ref, but not callable.  Is there a better way to access this method on the DeckGL component nested in my custom, Overviews component?

**Comment by Pessimistress** [comment]
You call call `pickObjects` upon DeckGL's `onLoad` event, which happens after `componentDidMount`.

**Comment by ToddJacobus** [comment]
Thank you for the quick reply!  Using the built in callback methods, like you suggested, seems to do the trick.
