### ISSUE TITLE
Returning true in layer's OnDrag() doesn't stop drag propagation

### ISSUE THREAD

**Issue by DominusVilicus** [uber/deck.gl#2974]
#### Description
```
new ScatterplotLayer({
                    data: [{
                        position: [-122.45, 37.8],
                        color: [20, 100, 150],
                        radius: 15
                    }],
                    opacity: 1,
                    getFillColor: d => d.color,
                    getRadius: d => d.radius,
                    pickable: true,
                    onDragStart(info, event){
                        return true
                    },
                    onDrag(info, event){
                        return true
                    },
                    onDragEnd(info, event){
                        console.log(info.coordinate)
                        return true
                    }
                })
```

Returning true on any of the onDrag doesn't prevent the event from propagating/bubbling to the deck gl canvas. I'm not sure what to do, or whether i've read the docs properly.

The function is being called at the correct times (tested with `console.log`), but returning true doesn't prevent the bubbling as the docs state (layer.onDrag)

http://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=ondragstart-function-optional-

**Comment by jcready** [comment]
AFAIK this issue applies to all the event handlers.

Returning a truthy value from a layer's event handler seems to simply change the arguments deck's event handlers get called with from the info object to `null`. It doesn't actually prevent deck's event handler from getting called. I would argue that with v7 no longer providing the `pickedInfos` array as an argument, there is no reason deck's event handers should be called when a layer's event handler returns a truthy value.

**Comment by Pessimistress** [comment]
I cannot reproduce - The `onDrag*` callbacks on Deck do not get called with your layer. If you are in fact expecting this to block the default event handling (panning the map), then no it is not expected to do that.

**Comment by DominusVilicus** [comment]
So how do you prevent the panning of the map?

**Comment by Pessimistress** [comment]
The viewport interaction is controlled by the [Controller](http://deck.gl/#/documentation/deckgl-api-reference/controllers/controller) class.
You can toggle the `dragPan` option of the controller, e.g.

```jsx
render() {
  return (
	<DeckGL
	  layers={[
        new ScatterplotLayer({
		  ...
          onDragStart={() => this.setState({isDragging: true})}
          onDragEnd={() => this.setState({isDragging: false})}
        }
      ]}
      controller={{dragPan: !this.state.isDragging}}
    />
  );
}
```

**Comment by DominusVilicus** [comment]
Will reopen if it doesn't work with nativejs

**Comment by DominusVilicus** [comment]
@Pessimistress 

Hey, not sure how I did it earlier, but I'm trying to prevent the controller from panning when onDragStart is called on plain JS (using Vue)

```js
const deck = new Deck({
            canvas: 'deck-canvas',
            width: '100%',
            height: '100%',
            initialViewState: INITIAL_VIEW_STATE,
            controller: true,
            layers: [
                new GeoJsonLayer({
                    id: 'airports',
                    data: AIR_PORTS,
                    // Styles
                    filled: true,
                    pointRadiusMinPixels: 2,
                    opacity: 1,
                    pointRadiusScale: 2000,
                    getRadius: f => 11 - f.properties.scalerank,
                    getFillColor: [200, 0, 80, 180],
                    // Interactive props
                    pickable: true,
                    autoHighlight: true,
                    onDragStart(info, event){
                         //disable controller
                    },
                    onDragEnd(info, event){
                        //renable controller
                    }
                })
```

**Comment by Pessimistress** [comment]
You'll need to update Deck's `controller` prop when `onDragStart` and `onDragEnd` are called:

```js
onDragStart(info, event){
  deck.setProps({controller: {dragPan: false});
},
onDragEnd(info, event){
  deck.setProps({controller: true);
}
```
