### ISSUE TITLE
v7.0.0-rc.1 IconLayer loadimage missing.

### ISSUE THREAD

**Issue by bbss** [uber/deck.gl#2976]
#### Description
It seems going from deck.gl v7.0.0-beta.3 to rc1 introduced a bug for us when loading the IconLayer. I suspect this is due to deck.gl doing something different wrt transpiling as the error seems related to loaders.gl not being available, my error stems from es5 version of this:
https://github.com/uber/deck.gl/blob/master/modules/layers/src/icon-layer/icon-manager.js#L4

#### Repro Steps
We haven been using ClojureScript with a tool named [shadow-cljs](http://shadow-cljs.org/) deck.gl for a while and have usually been able to require from the deck and luma without issues. 

If this issue doesn't immediately give a hint to what the issue might be then I can supply a minimal-repro-repo or steps. I realize these JS dependency/module systems are ridiculously complicated and maybe this is a broader issue with JS dependency loading that is not in deck.gl/loaders.gl scope.

#### Environment
 - Framework Version: deck.gl v7.0.0-rc.1
 - Browser Version: Chrome 72.0
 - OS: OSX latest

#### Logs
```
react-dom.development.js:17963 Uncaught TypeError: (0 , _core2.loadImage) is not a function
    at IconManager.value (icon-manager.js:268)
    at IconManager.value (icon-manager.js:249)
    at IconLayer.value (icon-layer.js:186)
    at IconLayer.value (layer.js:703)
    at IconLayer.value (layer.js:694)
```

**Comment by ibgreen** [comment]
@xintongxia This function moved to `@loaders.gl/images` in loaders.gl@1.0.0.

This was to:
- keep `@loaders.gl/core` small
- enable `deck.gl` to avoid importing `@loaders.gl/core` in the modules (ok to import in examples of course)

**Comment by bbss** [comment]
Great, 7.0.0 solved this for us, thanks!
