### ISSUE TITLE
onClick event on GeoJsonLayer does not fire every time

### ISSUE THREAD

**Issue by rajikaimal** [uber/deck.gl#2986]
#### Description
GeoJsonLayer onClick event fires randomly.

#### Repro Steps
- Add GeoJsonLayer and onClick event handler to GeoJsonLayer.

```js
import React from "react";
import { render } from "react-dom";
import DeckGL from "@deck.gl/react";
import { GeoJsonLayer } from "@deck.gl/layers";
import { StaticMap } from "react-map-gl";

import data from "./geodata.json";

// Set your mapbox access token here
const MAPBOX_TOKEN = process.env.MAPBOX_TOKEN;

// Initial viewport settings
const initialViewState = {
  longitude: -122.41669,
  latitude: 37.7853,
  zoom: 2,
  pitch: 0,
  bearing: 0
};

class App extends React.Component {
  render() {
    const layers = [
      new GeoJsonLayer({
        id: "geojson-layer",
        data,
        pickable: true,
        stroked: false,
        filled: true,
        extruded: false,
        lineWidthScale: 20,
        lineWidthMinPixels: 2,
        getFillColor: [160, 160, 180, 200],
        
        getRadius: 100,
        getLineWidth: 1,
        getElevation: 30,
        onClick: (event) => { console.log(event); return true; }
      })
    ];

    return (
      <DeckGL
        layers={layers}
        initialViewState={initialViewState}
        controller={true}
        pickable={true}
        onClick={() => { console.log("DeckGL");  }}
      >
        <StaticMap
          mapboxApiAccessToken={MAPBOX_TOKEN}
        />
      </DeckGL>
    );
  }
}

export function renderToDom(container) {
  render(<App />, container);
}
```
onClick handler for DeckGL gets fired when GeoJsonLayer handler doesn't get called.

#### Environment
 - Framework Version: v7.0.0-rc.1
 - Browser Version: 73.0.3683.103
 - OS: MacOS Mojave

#### Logs
![image](https://user-images.githubusercontent.com/8940086/56235055-35801400-60a4-11e9-9f4d-45402f855ec8.png)

**Comment by xintongxia** [comment]
> onClick handler for DeckGL gets fired when GeoJsonLayer handler doesn't get called.

This is expected behavior, if the layers don't handle the click event, it will bubble up to the top DeckGL canvas

**Comment by rajikaimal** [comment]
> This is expected behavior, if the layers don't handle the click event, it will bubble up to the top DeckGL canvas

Since I have the onClick handler for GeoJsonLayer, shouldn't it handle that? 

![Deckgl](https://user-images.githubusercontent.com/8940086/56306054-3a55ce00-615f-11e9-9c0d-f4e9a87557df.gif)

**Comment by rajikaimal** [comment]
@xintongxia In the GIF `DeckGL` is the log is from DeckGL layer onClick handler other logs are from GeoJsonLayer.

**Comment by rajikaimal** [comment]
I could replicate the issue on `Safari Version 12.1 (14607.1.40.1.4)`, but it's not showing the same pattern as chrome.

**Comment by xintongxia** [comment]
@rajikaimal

I am not able to reproduce this either in safari or chrome. Could you try using the latest deck.gl and also try playing with our [geojson](https://github.com/uber/deck.gl/tree/master/examples/website/geojson) example?

**Comment by rajikaimal** [comment]
GeoJson example is working. 

In my example I have 'extruded: false' in the GeoJson layer, can there be a connection to this problem?

Below is my GeoJson,

{
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      properties: {
        name: "40"
      },
      geometry: {
        type: "Polygon",
        coordinates: [
          [[-109, 50], [-102, 50], [-102, 37], [-109, 37], [-109, 50]]
        ]
      }
    },
    {
      type: "Feature",
      properties: {
        name: "50"
      },
      geometry: {
        type: "Polygon",
        coordinates: [
          [[-130, 41], [-102, 41], [-102, 37], [-130, 37], [-130, 41]]
        ]
      }
    },
    {
      type: "Feature",
      properties: {
        name: "100"
      },
      geometry: {
        type: "Polygon",
        coordinates: [
          [[-120, 60], [-102, 60], [-102, 65], [-120, 65], [-120, 60]]
        ]
      }
    }
  ]
}

**Comment by rajikaimal** [comment]
@xintongxia 

This repo contains the project with the issue

https://github.com/rajikaimal/deckgl-onclick

**Comment by Pessimistress** [comment]
I was able to reproduce this. It's caused by the event recognizer being overly sensitive - if you dragged even 1px it is recognized as a "pan" instead of "click".

**Comment by rajikaimal** [comment]
Still having the same issue with the codepen as well.

**Comment by Pessimistress** [comment]
I definitely do not see anything like you described. Maybe it's caused by a Chrome extension?

**Comment by rajikaimal** [comment]
I tested with Safari as well.

**Comment by Pessimistress** [comment]
I am unable to reproduce this issue. I'd appreciate if anyone else seeing this can provide more clue.

**Comment by Pessimistress** [comment]
@rajikaimal ok, I can confirm the following bug: if you click and quickly move your mouse away, the picking does not return the clicked object. If you click and keep your pointer at the same location then it works as expected.

Let me know if this observation is consistent with your issue.

**Comment by rajikaimal** [comment]
Yes, that's the accurate description of what I have observed.

**Comment by Pessimistress** [comment]
Try 7.0.4
