### ISSUE TITLE
Point Cloud is not rendered in FirstPersonView

### ISSUE THREAD

**Issue by tkt028** [uber/deck.gl#2995]
#### Description
My project is based on Streetscape.gl [1] (DeckGL-based). For performance reasons, I don't re-use the Point Cloud layer provided by Streetscapes.gl, but I made changes to the code of Streetscape at [2] (by adding layers to DeckGL) in order to render below data:
- point cloud data: rendered by DeckGL#PointCloudLayer

```
      new GeoJsonLayer({
          id: 'id',
          data: semanticUrl,
          pickable: true,
          stroked: true,
          filled: true,
          lineWidthScale: 2,
          lineWidthMinPixels: 1,
          lineWidthMaxPixels: 2,
          getRadius: 100,
          getLineWidth: 1,
          getElevation: 30,
        })
```

- street signs, lanemarks: rendered by DeckGL#GeoJsonLayer

```
new PointCloudLayer({
      id: 'point-cloud-id',
      data: points,
      pickable: false,
      coordinateSystem: COORDINATE_SYSTEM.LNGLAT_EXPERIMENTAL,
      radiusPixels: 1,
      getPosition: d => d.position,
      getColor: colorFunc,
      lightSettings: lightSettings,
    });
```

[1] https://avs.auto/#/
[2] https://github.com/uber/streetscape.gl/blob/master/modules/core/src/components/log-viewer/core-3d-viewer.js#L216 (function _getLayers())

#### Problems
In the Perspective view, I can see both point cloud data and GeoJsonLayer. But in the First Person View, only the GeoJsonLayer is visible. See the screenshots below for details.
**Expectation**: I can see point cloud data in First Person View.

#### Environment (please complete the following information):
 - Framework Version: ^6.4.5 (used by Streetscapes.gl)
 - Browser Version: 75.0.3759.4 (Official Build) dev (64-bit)
 - OS: Mac OS X 10.14.3

#### Screenshots
Screenshot 1: in First Person View (which is Driver mode in the language of Uber AVS), only GeoJsonLayer is visible, not point cloud layer.
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/1096511/56276812-68221f00-612d-11e9-927a-fa814e4fccf9.png">

Screenshot 2: In Perspective View, GeoJsonLayer and point cloud layer are both visible.
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/1096511/56282100-7de91180-6138-11e9-8399-a5b47af4864c.png">

**Comment by xintongxia** [comment]
In screenshot 2, it looks like your point cloud is below the greed trajectory and the blue cuboid? What is the z of the point cloud data?

**Comment by tkt028** [comment]
Hi @xintongxia ,
Thank you for asking. The z of point cloud data should be around 13.47 (I guess the unit is in meter).

```
$ pdal info point-cloud-data.laz -p 1
{
"filename": "point-cloud-data.laz",
"pdal_version": "1.8.0 (git-version: Release)",
"points":
{
"point":
{
"Blue": 9472,
"Classification": 0,
"EdgeOfFlightLine": 0,
"GpsTime": 0,
"Green": 9472,
"Intensity": 0,
"NumberOfReturns": 0,
"PointId": 1,
"PointSourceId": 0,
"Red": 9472,
"ReturnNumber": 0,
"ScanAngleRank": 0,
"ScanDirectionFlag": 0,
"UserData": 0,
"X": -121.9327896,
"Y": 37.3140889,
"Z": 13.47
}
}
}
```

One more input: in the Perspective View, I can move down the Camera to be very close to the point cloud and the point cloud is still visible.

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1096511/56303896-1d24fd80-6167-11e9-9989-f545ef1d97e9.png">

**Comment by ibgreen** [comment]
Just a hunch, based on working on this a long time ago...

This could be related to [focal distance](http://deck.gl/#/documentation/deckgl-api-reference/views/view?section=focaldistance-1-number-)

The documentation states this is only for orthographic views but that does not match with my recollection.

Basically the point cloud layer tries to determine at what distance a "pixel" corresponds to one "screen pixel", so that it can make pixels bigger and smaller depending on view. In the map views, the distance is naturally set to the map ground plane, but in the first person view, one needs to supply this information.

To test if this could be the case, just try increasing your pixel size (x10, x100, x1000) to see if points show up in first person.

The code could have changed so my comments may not apply, but worth a try.

**Comment by tkt028** [comment]
Hi @ibgreen ,
Thank you very much for your suggestion. Your are right about the connection between Point Cloud pixel size and the visibility of Point Cloud data.
- **Observation 1**: by increasing only the Point Cloud Pixel size to 5 pixel, the point cloud is somehow visible  (very small size) in the Driver Mode. However, point cloud with new pixel size looks very ugly in Perspective View (see screenshots).

```
new PointCloudLayer({
      id: 'point-cloud-id',
      data: points,
      pickable: false,
      coordinateSystem: COORDINATE_SYSTEM.LNGLAT_EXPERIMENTAL,
      radiusPixels: 5,      //.   ########## adjust this param. Original size: 1
      getPosition: d => d.position,
      getColor: colorFunc,
      lightSettings: lightSettings,
    });
```

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/1096511/56334066-0d3a0780-61c1-11e9-9f4f-6454d0180833.png">

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/1096511/56334722-b97ced80-61c3-11e9-9d1e-8ea3faafa94b.png">

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/1096511/56334833-27c1b000-61c4-11e9-9ac9-08529d2814f9.png">



- **Observation 2**: another experiment: change the value of Focal Distance, the Point Cloud is not visible, but the shapes of other objects (landmark) is distorted.

```
new FirstPersonView({
      id: name,
      fovy: 75,
      near: 1,
      far: 10000,
      focalDistance: 0.1,       // adjust this value. Original value: 6
      controller: controllerProps
    });
```

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/1096511/56334368-3909bd00-61c2-11e9-909c-ba6d000d09db.png">


**QUESTION**
Do you have any suggestion to have a nice rendering of Point Cloud both in Perspective and First Person View?

**Comment by tkt028** [comment]
Since I could not find a single parameter to have a nice rendering of Point Cloud in both Perspective and First Person View, I adopt a workaround solution that pass the right value of PointCloudLayer#radiusPixels according to each view mode.
