### ISSUE TITLE
Add Voronoi layer

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#3]
A (hierachical) voronoi layer to visualize density distribution

**Comment by ibgreen** [comment]
Available in deck.gl v3 - although has some constraints on usage.

**Comment by andybak** [comment]
This is one of the top results for "deck.gl voronoi" and seems to imply the functionality exists. However - there's no mention of voronoi in the deck.gl docs.

**Comment by ibgreen** [comment]
In one of the early releases, we did write a voronoi layer that used a clever depth buffer technique to calculate cell boundary intersections on the GPU. However it had visual artifacts and we never included it in the release. 

IIRC, it worked pretty well in non-perspective mode, but not when tilted. 

It should not be too hard to find the layer, but it would require some work to get it up to latest API, and then the issues would need to be evaluated again.

An alternative option is to calculate the cell divisions on CPU, I believe d3 and other libraries support that.

I don't think there is any current work on this, but happy to support a contribution.
