### ISSUE TITLE
How can I get tile data to render some other layers?

### ISSUE THREAD

**Issue by ajiko** [uber/deck.gl#3025]
Deck.gl is faster enought to render large data set, but speed of HttpRequest is limit.
So I need to get data like vector tiles to render.
except tileLayers, is there any thing I can use?

**Comment by xintongxia** [comment]
@ajiko 

I am not sure I am following your question, but what `TileLayer` mainly does is fetching tiles by given current viewport (lat lng, zoom), and you can decide how to render the tiles by using the prop `renderSubLayers`.

Check [Map Tiles](https://github.com/uber/deck.gl/blob/master/examples/website/map-tile/app.js#L56) example, might help.
