### ISSUE TITLE
Point Cloud  data are separate on PointCloudLayer

### ISSUE THREAD

**Issue by ouxiang** [uber/deck.gl#3026]
I have two  .las files data originally connected together.I put both position of two .las files data in an array.But they are shown to be separate.I don't know why.

**Comment by Pessimistress** [comment]
Please use the issue template if you need help. Include a code snippet, describe the expected vs. actual behavior, the version of the framework you are using, etc.

**Comment by ouxiang** [comment]
> Please use the issue template if you need help. Include a code snippet, describe the expected vs. actual behavior, the version of the framework you are using, etc.

Thanks,this problem has been solved, because of the data position.I have a  new question. Why it needs do normalize when adding new data on PointCloudLayer.I do not see the pointcloud data if not do normalize.
