### ISSUE TITLE
TileLayer example on website in the API Reference is becomming white screen when interacting

### ISSUE THREAD

**Issue by TrantorM** [uber/deck.gl#3031]
In the API Reference Documentation on your website the TileLayer example is not working properly with Firefox (66.0.3). The entire browser window becoms white screen as soon as one interact with the map (zoom, move, ...).

I also would like to ask, if you could add this very example to the example collection? At the moment there is just the open-street-map as a TileLayer example.

**Comment by xintongxia** [comment]
This is because of `@babel/polyfill` see [this](https://github.com/uber/deck.gl/issues/2988) thread for details.

You can remove `@babel/polyfill` from [code](https://github.com/uber/deck.gl/blob/master/website/src/main.js#L2) and running the website on your local.

**Comment by athomann** [comment]
Is this a firefox only issue?  Possibly a different issue, but TileLayer docs are crashing on all browsers currently with error.

```
TypeError: "o is undefined
```

**Comment by Pessimistress** [comment]
@xintongxia this seems to be a different issue in the website itself. I'll put up a fix.
