### ISSUE TITLE
GPU memory not freed after unmounting Deck component.

### ISSUE THREAD

**Issue by Lowhearth** [uber/deck.gl#3039]
#### Description
GPU memory not freed after unmounting Deck component.

#### Repro Steps

- Go to https://deck.gl/#/examples/core-layers/

- Open Google Chrome task manager and enable the GPU Memory column.

- Switch between the demos and see how the GPU Memory permanently increases every time a new one is displayed

#### Environment (please complete the following information):
 - Framework Version: 7.0.3
 - Browser Version: Chrome 73.0
 - OS Ubuntu 18.04.2 LTS

#### Logs

![memory](https://user-images.githubusercontent.com/40487685/56888313-f377aa80-6a73-11e9-9f1c-5976718b1037.jpg)
![memory2](https://user-images.githubusercontent.com/40487685/56888314-f377aa80-6a73-11e9-8826-c6be98b1c956.jpg)
![memory3](https://user-images.githubusercontent.com/40487685/56888316-f4104100-6a73-11e9-8665-34fedcf0b52f.jpg)
![memory5](https://user-images.githubusercontent.com/40487685/56888317-f4104100-6a73-11e9-912d-83cdb49bddac.jpg)
![memory6](https://user-images.githubusercontent.com/40487685/56888318-f4104100-6a73-11e9-9d31-f48ac4be6783.jpg)
![memory7](https://user-images.githubusercontent.com/40487685/56888319-f4104100-6a73-11e9-886b-a1c15342974b.jpg)

**Comment by Pessimistress** [comment]
@tsherif @ibgreen There are several layers to this issue:

- Buffers are not properly deleted, addressed in https://github.com/uber/deck.gl/pull/3044
- We can not tell WebGLContext to immediately free all GPU resources, according to https://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use. With the above PR I do see GPU memory stack up but it eventually comes back down.
- We do not properly free cached shaders and programs upon finalization, https://github.com/uber/luma.gl/blob/master/modules/core/src/lib/shader-cache.js#L25 I don't have hard numbers on exactly how much impact this has.

**Comment by tsherif** [comment]
I don't think we should worry too much about the shaders. If buffers and textures are now properly released, that should address this issue.

**Comment by ibgreen** [comment]
That would be my sense as well. 

But maybe they hold on to the context, preventing it from being garbage collected?

**Comment by tsherif** [comment]
Oh, interesting point. Is unmounting a deck.gl component meant to completely release the gl context?

**Comment by ibgreen** [comment]
> Is unmounting a deck.gl component meant to completely release the gl context?

Hmm, I would have to check the code to answer that. The ideal resource management design is typically that release is "symmetric" with creation, so if we create during `mount` then yes.

Regardless, when we are done with the context it makes sense to make sure we don't prevent garbage collection by e.g. having objects in e.g. a global map like a shader cache referencing it.

**Comment by Pessimistress** [comment]
Partial fix published in 7.0.4
