### ISSUE TITLE
Usage with React Hooks

### ISSUE THREAD

**Issue by felixerdy** [uber/deck.gl#3046]
#### Description
I am using deck.gl with React Hooks. Data and layers are stored in different Hooks. I'd like to update a GeoJsonLayer after the data Hook changes.

#### Repro Steps
This is my map component. The map gets rendered but the layer will not show up. It seems like updating the `data` Hook does not update the `scatterLayer` Hook.
```js
import React, { useState, useEffect } from "react";
import DeckGL from '@deck.gl/react';
import { GeoJsonLayer } from '@deck.gl/layers';
import { StaticMap } from 'react-map-gl';

const Map = (props) => {
    // fetching API data
    useEffect(() => {
        fetch('https://api.opensensemap.org/boxes?format=geojson')
            .then(res => res.json())
            .then(data => {
                setData(data)
            })
    }, [])

    // Viewport settings
    const [viewport, setViewport] = useState({
        width: "100%",
        height: "100%",
        latitude: 45,
        longitude: 9,
        zoom: 4,
    })

    const [data, setData] = useState()

    const [scatterLayer, setScatterLayer] = useState(new GeoJsonLayer({
        id: 'geojson',
        data,
        pickable: true,
        stroked: false,
        pointRadiusMinPixels: 4,
        getRadius: 10,
        visible: props.layersVisible.scatter,
    }))

    return (
        <DeckGL
            viewState={viewport}
            controller
            onViewStateChange={({ viewState }) => setViewport(viewState)}
            layers={[scatterLayer]}>
            <StaticMap />
        </DeckGL>
    )
}

export default Map
```

#### Environment (please complete the following information):
 - Framework Version: "deck.gl": "^7.0.3", "react": "^16.8.6",
 - Browser Version: Chrome 74.0.3729.108
 - OS: macOS 10.14.4

#### Logs
No relevant logs.

**Comment by Pessimistress** [comment]
The layer you passed to `useState` is the [initial value](https://reactjs.org/docs/hooks-reference.html#usestate). You never updated it with `setScatterLayer`.

**Comment by felixerdy** [comment]
I also want to set the opacity of the layer depending on the zoom level. So I need to create a new instance of `GeoJsonLayer` on each data change and zoom level change?

**Comment by Pessimistress** [comment]
That is correct. There is no performance penalty to creating new layer instances, see http://deck.gl/#/documentation/developer-guide/using-layers?section=should-i-be-creating-new-layers-on-every-render-

**Comment by albertpak** [comment]
I've followed your steps and my layer get stuck in `Awaiting state` lifecycle...any idea what it could be...I'm using `React 16.8 and `deck.gl 7.2.3`

![image](https://user-images.githubusercontent.com/1485687/64764345-796a2e80-d507-11e9-8225-5a13c29b40af.png)
