### ISSUE TITLE
How does the trip-routes in the examples load data ?

### ISSUE THREAD

**Issue by jjdblast** [uber/deck.gl#305]
Dig into this [demo](http://uber.github.io/deck.gl/#/examples/trip-routes?tab=demo) and also read the code for a long time, still can't figure out where the taxi route data is and how does this demo load data. Could anyone explain? Thanks!

**Comment by ibgreen** [comment]
@Pessimistress @apercu who have worked most on the demo

**Comment by Apercu** [comment]
All credit goes to @Pessimistress, but I think I can tell you the data comes from [this file](https://github.com/uber/deck.gl/blob/master/demo/src/static/data/hero-data.txt), is requested in [this component](https://github.com/uber/deck.gl/blob/master/demo/src/javascripts/components/demos/hero.js#L12) and the data decoded in [the loadData action](https://github.com/uber/deck.gl/blob/master/demo/src/javascripts/actions/app-actions.js#L52). Correct me if I'm wrong ;)

**Comment by contra** [comment]
@Apercu Is the script for creating that file anywhere in the repo?

**Comment by Apercu** [comment]
Don't think so

**Comment by Pessimistress** [comment]
@jjdblast the trips data is loaded from [this txt](https://github.com/uber/deck.gl/blob/master/demo/src/static/data/hero-data.txt) and processed with [this worker](https://github.com/uber/deck.gl/blob/master/demo/src/static/workers/hero-data-decoder.js). The extra effort is mostly for optimizing loading speed (compression), and visual flare (create a seamless loop), but has nothing to do with the data format that the `TripsLayer` consumes. Eventually the data is an array of *trips*, each *trip* containing an array of turn points in the form of `[longitude, latitude, timestamp]`.
It's easier to see if you inspect the `vis` store state on the demo page.

@contra The raw data went through a pipeline of several scripts that perform routing, aggregation, sampling, and then compress with the [encoded polyline format](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). Some of them use private APIs and are tuned for this specific dataset, so I figure there's little reuse value.

**Comment by contra** [comment]
@Pessimistress If the scripts have private APIs in them it would still be really helpful to see them - if the routing portion is a private uber thing I can swap in something that uses the mapbox routing API.

**Comment by jjdblast** [comment]
Cool method and thanks for explanations !
