### ISSUE TITLE
Scatterplot layer should support clustering

### ISSUE THREAD

**Issue by zicodeng** [uber/deck.gl#3055]
#### Target Use case

Currently, scatterplot layer is able to handle a large number data points without any problem. Good job team. However, when we have many data points, we will get trypophobia :(

![image](https://user-images.githubusercontent.com/24593509/57031603-f356e680-6bfc-11e9-9767-348c66d1ef78.png)

#### Proposed feature

In Mapbox GL JS, you can accomplish this by using [supercluster](https://github.com/mapbox/supercluster). I wonder if there is a way to do this with Deck.gl?

![image](https://user-images.githubusercontent.com/24593509/57031886-b8a17e00-6bfd-11e9-84f5-31433a83ed94.png)

Thanks!

**Comment by ibgreen** [comment]
Does zooming in and out in the [icon layer example](http://deck.gl/#/examples/core-layers/icon-layer) look like what had in mind?

**Comment by zicodeng** [comment]
@ibgreen haha, thanks. I think this is what I need!

**Comment by mcchong** [comment]
Hi, sorry if I'm raising a dead mink here, but I have the same question, and don't seem to be able to access the referenced example.  Thanks!
