### ISSUE TITLE
H3 layer not rendering

### ISSUE THREAD

**Issue by thomasgwatson** [uber/deck.gl#3070]
Hey folks,

A little puzzled why hexagons aren't showing up in my project.

The react-map-gl map is showing up fine. Not getting any errors in the console.

The layer appears to be forming correctly, and in the correct resolution (level 8)
<img width="960" alt="Screen Shot 2019-05-06 at 21 01 58" src="https://user-images.githubusercontent.com/5193218/57270979-64a1f980-7042-11e9-8175-aac605827bf0.png">

I have clipped the data to a smaller sample but I've scanned several cities where the hexs should be and seen nothing...

The relevant code:
https://gist.github.com/thomasgwatson/392dad23b8d56a00e78445d14de30714
My debug checklist:
- [x] Check react-map component/viewport
- [x] Check h3Layer component
- [x] Check MapPage component

Hoping there is something obvious I've missed!

**Comment by Pessimistress** [comment]
This is an example of your data working: https://codepen.io/Pessimistress/pen/vwLMdv

Not sure if it's relevant, but your default viewport is no where near where your data is.

**Comment by thomasgwatson** [comment]
Thanks for checking that out and confirming the data renders!

It's a little obscure but I pass the bay area coords in via the Map Props, so the default viewport isn't coming to play. The data is street art/graffiti, so was expected a decent chunk in the bay.

I'll try rendering the deck.gl view without the map and see if I can at least get that working
