### ISSUE TITLE
Should ES5 bundle be UMD?

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3076]
The current [ES5 build](https://unpkg.com/deck.gl@7.0.5/dist/es5/index.js) is valid ES5 syntax, but it's not a UMD bundle, making it unusable in a vanilla JS environment.

Is the current format intended or was there a build issue? If intended, what environment is it meant to run in?

**Comment by ibgreen** [comment]
> Is the current format intended?

The ES5 build was mainly intended to avoid using `import`/`export` syntax for toolchains that does not support those. It is supposed to be [commonjs](https://github.com/uber-web/ocular/blob/master/modules/dev-tools/config/babel.config.js#L19).

> making it unusable in a vanilla JS environment.

How would you like to use it? What is a vanilla JS environment to you? 

We do publish pre-bundled scripts for non-npm usage, that can either be accessed from the installe module or directly via `unpkg.com`:

- https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js
- https://unpkg.com/@deck.gl/core@7.0.0/dist/dist.dev.js

**Comment by bclinkinbeard** [comment]
Gotcha. By vanilla environment I just meant a browser. I have been using the unpkg.com build, but today discovered I cannot subclass things like ScatterplotLayer using that build because my code is compiled to ES5 and so I can't subclass an ES6 class. I had wrongly assumed that all published builds were meant for browser consumption.

**Comment by ibgreen** [comment]
> today discovered I cannot subclass things like ScatterplotLayer using that build because my code is compiled to ES5 and so I can't subclass an ES6 class.

Is that a problem with the debug script only? The `dist.min.js` should also be compiled to ES5...

**Comment by bclinkinbeard** [comment]
No, the minified build has several class definitions in it, which makes it ES6.

**Comment by ibgreen** [comment]
> the minified build has several class definitions

OK, that sounds like a fixable bug, some issue with the babel settings for the script bundler @Pessimistress

**Comment by bclinkinbeard** [comment]
Awesome, thanks. I _think_ adding `options: { presets: ['@babel/preset-env'] }` [here](https://github.com/uber/deck.gl/blob/master/scripts/bundle.config.js#L71) would do the trick, but I'm far from a Webpack expert.

**Comment by ibgreen** [comment]
Yes, I thought it would have picked up the repo's global babel settings, but maybe it doesn't. 

Also preset-env doesn't compile everything by default. It needs the `forceAllTransforms` flag.

**Comment by Pessimistress** [comment]
Published deck.gl@7.0.6

**Comment by bclinkinbeard** [comment]
Thanks so much!
