### ISSUE TITLE
GeoJSON Polygon normals are inverting, causing caps to render in front of bodies when depthMask = false.

### ISSUE THREAD

**Issue by mayteio** [uber/deck.gl#3081]
#### Description
3D polygon normals are inverting, causing a depth issue. Happens to all extruded polygon layers I have.

[GIF of issue](https://media.giphy.com/media/h5XhAjPgQgUt8Ek5pT/giphy.gif)

Example of GeoJsonLayer arguments causing this:

![Screen Shot 2019-05-09 at 11 31 28 am](https://user-images.githubusercontent.com/43975092/57423232-7825ae00-7256-11e9-838a-c62393373021.png)

It's worth noting that I am hiding/showing a subset of the full dataset by setting the hidden polygons' color to `[0,0,0,0]` as described in [This issue](https://github.com/uber/deck.gl/issues/3063).

When I turn depthMask back to true, the issue goes away but obviously, the invisible polygons mask the visible ones:

![Screenshot 2019-05-09 18 12 21](https://user-images.githubusercontent.com/43975092/57437967-3a407e00-7286-11e9-99ba-1ff6f16627e8.png)

So I'm in a rock and a hard place - masks or inverted polygons. Is there a middle ground I can use?

#### Environment (please complete the following information):
 - Framework Version: 7.0.5
 - Browser Version: Chrome 74
 - OS: MacOS 10.14.2

#### Logs
No logs

**Comment by jianhuang01** [comment]
the normals are fine, you need change the elevation to 0 for buildings with [0, 0, 0, 0] colors

**Comment by mayteio** [comment]
That was the correct solution. [Got these great visuals running](https://www.dropbox.com/s/fimg0m8id2y2z36/Screen%20Recording%202019-05-28%20at%208.11.19%20am.mov?dl=0) - appreciate the support.
