### ISSUE TITLE
Color polygons according to it's  features

### ISSUE THREAD

**Issue by gcoimbra** [uber/deck.gl#3082]
How can I color polygons according to a attribute that is present in GeoJSON?

**Comment by jianhuang01** [comment]
you can define getFillColor to be something like this.
```js
getFillColor: d => {
  // check attribute here
  if (d.height == 100) return [255, 0, 0, 255];
  return [0, 255, 0, 255];
}
```

**Comment by Pessimistress** [comment]
@gcoimbra  Please read the [documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer) and use the template to raise questions.
