### ISSUE TITLE
Polygon layer: How to get attribute popup even if Fill setting is disabled?

### ISSUE THREAD

**Issue by guidorice** [uber/deck.gl#3087]
I have noticed that with the Polygon layer, e.g. the demos at:

https://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer
and at
https://kepler.gl/demo/movement_pittsburgh

If I turn off the Fill color setting, then the attribute popup is only visible when one mouse hovers over the shape's stroke. If the stroke width is set to a small value, this can be quite difficult to hit and get to see the attribute popup (or user might not even know they can get the attribute popup).

I tried enabling Fill color, and experimenting with the opacity, setting close to zero, which enables the attribute popup display again. But it also makes the lines close to transparent, so that's not going to work.

Are there any secret settings or plans for the hit-testing algorithm that could improve this?

**Comment by jianhuang01** [comment]
you can redefine fill color accessor with low alpha like this:
```js
getFillColor: d => return [128, 0, 0, 0];;
```
so stroke color won't be impacted.

**Comment by guidorice** [comment]
Nice workaround! thanks
