### ISSUE TITLE
Not able to properly synchronize layers

### ISSUE THREAD

**Issue by ctriley** [uber/deck.gl#3088]
I am working on a Trip Layer and a GridCellLayer. I want to simulate people waiting at stops using the cells, and those people being picked up with the trip layer. Therefore, I want to ensure that when a vehicle leaves a stop, the Column in the GridCellLayer goes down. However, I seem to have timing issues where the GridCellLayer goes down before the TripLayer draws a line for the vehicle.

I've attached code which should compile (`yarn` then `yarn start`) provided that there is a `token.json` file with your mapbox token in the root directory of the project.

If anyone can take a look and help me I'd really appreciate it.
[example.zip](https://github.com/uber/deck.gl/files/3168278/example.zip)

**Comment by BertCh** [comment]
You have to make the units you are using to represent time for the GridCell layer match up with the units being used in the trips layer. The length the elevation array that is used to animate the cell over time should correspond with the loopLength variable. The third number in the test route segments represents the timestamp for that segment. You can see the trip starts at 70 and ends at 309 so you would want your elevation array to have 1 from 0-70 and 0 thereafter.
```
        "segments": [
            [
                -73.98928,
                40.77357,
                70
            ],
            [
                -73.9891,
                40.77349,
                71.20999908447266
            ],
            [
                -73.99371,
                40.76713,
                126.6434223651886
            ],
            ...
            [
                -73.99519,
                40.74983,
                309.0000002384186
            ]
```
[example.zip](https://github.com/uber/deck.gl/files/3170164/example.zip)
