### ISSUE TITLE
When I share the same canvas in the mapbox and the deck, loaded the extruded Polygon of the deckgl will appear perspective.

### ISSUE THREAD

**Issue by F1ng3rs** [uber/deck.gl#3104]
When I share the same canvas in the mapbox and the deck, loaded the extruded Polygon of the deckgl will appear perspective. What happened ?

This is the rendering：
![eg](https://user-images.githubusercontent.com/37007832/57847479-1f7f8380-7809-11e9-886b-66019e272a2a.gif)

**Comment by ibgreen** [comment]
Looks like `depthTest` is `false`. Either you are turning it off yourself or it is due to some interaction between the two libraries?

**Comment by F1ng3rs** [comment]
@ibgreen Thank  you.I think i know the reason for this problem.
