### ISSUE TITLE
Module version numbers in package.json are incorrect

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3118]
All of the modules appear to list `7.0.0-rc.1` as their version, and non-core modules depend on `"@deck.gl/core": "^7.0.0-beta.1"`, while 7.0.8 appears to be the latest published version.

**Comment by Pessimistress** [comment]
@bclinkinbeard The latest production versions are published from the 7.0-release branch. Master is only used to publish beta releases. This is documented in https://github.com/uber/deck.gl/blob/master/dev-docs/directory-structure.md#branching-and-releasing-model.

**Comment by bclinkinbeard** [comment]
Ah, the package versions are correct when installed but the peer deps are not. Installing `@deck.gl/layers` results in a package.json with the definition below. Same for /geo-layers, /google-maps, etc.

```
"peerDependencies": {
    "@deck.gl/core": "^7.0.0-beta.1"
  },
```

**Comment by bclinkinbeard** [comment]
Thanks for fixing that. I also noticed that the LICENSE file is not included in the published assets. I'm happy to create a PR if it's just a matter of adding it to `files` in all of the `package.json` files but I wanted to ask if there's a better way.

**Comment by bclinkinbeard** [comment]
Closing in favor of #3151
