### ISSUE TITLE
tripsLayer: Segments do not get drawn when trailLength is large

### ISSUE THREAD

**Issue by harisbal** [uber/deck.gl#3120]
Hello,
I'm trying to use the `tripsLayer` in order to visualize the movement of some vehicles throughout the day. My issue is that I need the the `trailLength `of of trips to remain for the whole duration of the trip (which can be quite a long duration). When trying to set the `trailLength `to a large enough value some of the segments do not get drawn.
I noticed that when I comment out the 2 following lines, the issue gets resolved. Is that because the module of `mod(instanceEndPositions.z, trailLength) `returns 0 when the trail is too large therefore no `shiftZ `is applied?

https://github.com/uber/deck.gl/blob/8e382c65aefaeefec240f30d36b20215cd3af5c9/modules/geo-layers/src/trips-layer/trips-layer.js#L41-L42
 
I'm sorry but I did not manage to set a codepen that could update time (It would be useful if you could upload the trips example as a codepen) 

My very simple single trip is presented below
```
[{"Tripid": 1, "Segments": [[-2.358666776, 51.35911178, 3500.0],
                            [-2.35958041, 51.38328426, 8000.9],
                            [-2.4175237, 51.4007863, 11000.0],
                            [-2.426716202, 51.3474509, 12000.8],
                            [-2.358666776, 51.35911178, 16000.1]]}]

```
Setting the trailLength to something more than 5000 results in the first segment not being drawn. I suppose it has to do with the duration of the first segment which is below 5000.

Cheers

 - Framework Version: [e.g. deck.gl 7.0.0]
 - Browser Version: [e.g. Chrome 74.0.3729.157]
 - OS: [e.g. Windows 10 ]

**Comment by Pessimistress** [comment]
Maybe we're hitting a precision issue in the shader?

@tsherif `shiftZ` is an arbitrary small number applied to reduce z-fighting. Any suggestion of alternatives? Maybe we should just use a constant instead of `trailLength`?

**Comment by tsherif** [comment]
I don't think you'd get a precision issue with those numbers. It looks like it's just `shiftZ` gets too large with these values and pushes segments outside the clipping volume. I'd suggest basing `shiftZ` on a function with a known range. This worked for me (though I didn't test it that much): 
```c
float shiftZ = sin(instanceEndPositions.z) * 1e-4;
```

**Comment by Pessimistress** [comment]
The problematic z shift has been dropped as of v8.
