### ISSUE TITLE
Clear selection / Catch onClick event on Basemap

### ISSUE THREAD

**Issue by harisbal** [uber/deck.gl#3123]
Hello,
Although documentation is very clear on selecting elements, I cannot seem to find how I clear a selection. 
My approach is to catch a `onClick` event anywhere on the map and not just over a specific layer but I do not know how to register a callback on the map layer itself.

Cheers!

**Comment by Pessimistress** [comment]
Can you explain what you mean by "selection?" Are you trying to check if the user clicked on nothing? Are you trying to query a feature in the Mapbox component?

**Comment by harisbal** [comment]
I'm working on a pickable geojson (polygon) layer and I'm filtering some data based on the selected polygon. (as explained in the [arcs example](https://deck.gl/#/examples/core-layers/arc-layer)).
What I want to achieve is to show the full dataset (all arcs) if the user clicks on anywhere but a US state (a rightMouseClick could also be an option).

I suppose capturing a click on nothing could work to clear the filter but if there is another better way please suggest so.

**Comment by Pessimistress** [comment]
Have you tried supplying an `onClick` prop to Deck/DeckGL?

**Comment by harisbal** [comment]
Thank you @Pessimistress . I hadn't realised that I can register onClick events to Deck/DeckGL
Modifying the following worked.

https://github.com/rajikaimal/deckgl-onclick/blob/d6fd46f3ad1d365df8aa5861629c24a274bfa376/src/app.js#L159-L166

Thanks
