### ISSUE TITLE
Layers is undefined in deck.gl@6.4.10

### ISSUE THREAD

**Issue by hijiangtao** [uber/deck.gl#3124]
According to documents, I can customize a CompositeLayer with following codes:

```
import {CompositeLayer, IconLayer, TextLayer} from 'deck.gl';

class LabeledIconLayer extends CompositeLayer {
  // TODO
}
LabeledIconLayer.layerName = 'LabeledIconLayer';
```

However, I got this error message when I use it (with deck.gl@6.4.10):

> Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null.

The `null` refers to `CompositeLayer`.

On the other hand, if I want to use any properties (such as 'defaultProps') inside `IconLayer` or other layers, I got error message like this:

> Uncaught (in promise) TypeError: Cannot read property 'defaultProps' of undefined

Docs： https://deck.gl/#/documentation/developer-guide/writing-custom-layers/composite-layers?section=collection-layers

**Comment by hijiangtao** [comment]
However, I didn't get related upgrade tips from **Upgrade Guide** https://deck.gl/#/documentation/overview/upgrade-guide

**Comment by Pessimistress** [comment]
They are defined: https://unpkg.com/deck.gl@6.4.10/dist/esm/index.js

Can you double check your dependency and bundling configs.

**Comment by hijiangtao** [comment]
@Pessimistress I checked the package I used in my project again, and restricted it to ~6.3.1 version (which is v6.3.9 installed actually), but following usage would still got errors like:

```
import {ArcLayer} from 'deck.gl';
```

> index.js:10 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null

I also print the package itself out and got following result (most of layers are undefined inside deck.gl, however, `CompositeLayer` is valid inside it, is there ant ideas why it could happen?):

```
import * as testDeckGl from "deck.gl";
console.log(testDeckGl);
```

Result:

![image](https://user-images.githubusercontent.com/4990015/58105083-7d9cd400-7c18-11e9-9014-fdc341054305.png)

I noticed there are some usages different from previous version, such as I should import '@deck.gl/layers' rather than 'deck.gl' if I want to use ScatterplotLayer? Would it be the reason?

Thanks.

**Comment by Pessimistress** [comment]
deck.gl re-exports all the classes from submodules. Looks like your submodules (e.g. `@deck.gl/layers`) are not properly installed. You can try clear your node_modules and reinstall all dependencies.

**Comment by hijiangtao** [comment]
I removed my node_modules folder and reinstalled, but it seems doesn't work if I only declare deck.gl in package.json.

The strange thing is that `ArcLayer` is exported but remains `undefined`, which means corresponding package '@deck.gl/layers' isn't installed rightly. However, when I open the deck.gl's node_modules folder inside node_modules folder, `@deck.gl/layers` is there with version 6.3.9.

I need to separately install these submodules and import from them rather than 'deck.gl' to solve my problem currently. Got no idea what's wrong with my environment that causes the wrong settings of deck.gl. :-(

**Comment by hijiangtao** [comment]
It seems submodules not included in '@deck.gl/core' will be exported as undefined with specific Babel environment. I suspect it's caused by deck.gl's `export` or `module.export` coding style.

I will reopen it if I locate a more specific reason.

**Comment by kfragkedaki** [comment]
I have the same issue as described above (same deck.gl version as well). 
This error occurred when I added CompositeLayer so as to compose two of the layers. 
I have no idea on how to solve this issue. If you have any suggestions,  let me know

**Comment by kfragkedaki** [comment]
I have the same issue as described above (same deck.gl version as well).
This error occurred when I added CompositeLayer so as to compose two of the layers.
I have no idea on how to solve this issue. If you have any suggestions, let me know

**Comment by hijiangtao** [comment]
@kfragkedaki Hi, there. Currently, I have no idea why it would happen either, but I solved it temporarily by importing sub modules like "@deck.gl/layers and "@deck.gl/react" separately.

I used them in my project with:

```
import DeckGL from '@deck.gl/react';
import { ScreenGridLayer } from "@deck.gl/layers";
```

Maybe you can try it the same way. I still suspect it's caused by deck.gl's `export` or `module.export` coding style.

**Comment by kfragkedaki** [comment]
Hi again, I solved this problem by using the following piece of code. It seems that I had to create aN object of LayerText class and include its properties when using it on deckgl's layers.

```
import { TextLayer, ScatterplotLayer, CompositeLayer } from "deck.gl";

export const layerText = data => {
  class LayerText extends CompositeLayer {
    renderLayers() {
      const scatterplot = new ScatterplotLayer(
        this.getSubLayerProps({
          id: "icon-eta",
          data: this.props.data,
          radiusScale: 6,
          opacity: 1,
          getPosition: d => d.coordinates,
          getFillColor: [4, 171, 193]
        })
      );

      const text = new TextLayer(
        this.getSubLayerProps({
          id: "text-distance",
          data: this.props.data,
          getPosition: d => d.coordinates,
          getText: d => d.distance,
          getColor: [255, 255, 255]
        })
      );
      return [scatterplot, text];
    }
  }
  LayerTexT.layerName = "LayerText";

  return new LayerText({
        id: `icontext-eta`,
        data
   });
}
```

```
<DeckGL
  layers= {[
     layerText
  ]};>
   // TODO
</DeckGL>
}
```

**Comment by hijiangtao** [comment]
@kfragkedaki I suspect we met different problems. I think the problem you faced is how to use Layers correctly, but I just couldn't import them from deck.gl directly?

And one more thing, is it typos that you pass an array contains function into `layers` property rather than an array contains layers (since `layerText` in your code is a function, which should be executed to return the exact layer instance)?
