### ISSUE TITLE
How do I change viewState with pure-js?

### ISSUE THREAD

**Issue by dinglei92** [uber/deck.gl#3125]
I use setProps method to change the value of viewstate,but there are some problems.

```
deckgl.setProps({
       viewState: {
               longitude: 118.76218,
               latitude: 32.04358,
               zoom: 14
       }
})
```
But this method does not execute immediately, just only works if I'm manipulating the map。

**Comment by Pessimistress** [comment]
Can you provide more context?

There is a [pure JS set viewState example](https://deck.gl/showcases/gallery/viewport-transition)

**Comment by dinglei92** [comment]
@Pessimistress  
I want to implement a method like mapbox jumpTo. No fly animation, just change viewState immediately.
This is my code:
```
jumpTo(option) {
        const viewStateDefault =  {
            transitionDuration: 0,
            transitionInterpolator: new FlyToInterpolator(),
        }
        this.setViewState({...viewStateDefault, ...option});
        this.deckgl.setProps({ viewState: this.viewState });
 }
```
It doesn't work  well, but when I set transitionDuration to a very small value, like 10, It works well.

**Comment by Pessimistress** [comment]
In the example I linked, if I comment out the transition settings, the camera jumps immediately. Can you share the rest of your code?
