### ISSUE TITLE
Time-slider

### ISSUE THREAD

**Issue by harisbal** [uber/deck.gl#3148]
Hello,
I'm trying to include a slider in order to control time during my animation. Would it be possible to use something similar to the time-slider used by [kepler](https://kepler.gl/demo/nyctrips) for the NYC trips, or is there a better/easier to implement alternative that I cannot see in the documentation?
Cheers

**Comment by 1chandu** [comment]
deck.gl doesn't support it natively yet, so for now you would have implement your own, but we are working on [data filtering ](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/data-filter-rfc.md) support for future releases.

**Comment by bclinkinbeard** [comment]
@harisbal You should be able to wire up your slider to the currentTime prop in the trips layer example on the site.

**Comment by harisbal** [comment]
@bclinkinbeard @1chandu  thank you for your replies. I'm still new to this realm and I wanted to make sure that I am not missing something obvious. Cheers!

**Comment by AdriSolid** [comment]
@harisbal take a look [here](https://github.com/AdriSolid/DECK.GL-Time-Slider) (if you are looking for a from scratch DECK.GL time-slider implementation), maybe this will help others as well. 

Cheers! :baby_chick:

**Comment by AdriSolid** [comment]
@1chandu pretty excited with the [data filtering support](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v6.0/data-filter-rfc.md)!

**Comment by harisbal** [comment]
> @harisbal take a look [here](https://github.com/AdriSolid/DECK.GL-Time-Slider) (if you are looking for a from scratch DECK.GL time-slider implementation), maybe this will help others as well.
> 
> Cheers! 🐤

Hi @AdriSolid 
I have seen your time-slider but my novice level in JS didn't allow me to make it work. I'll give it a second try now that I'm slightly more experienced. Cheers!
