### ISSUE TITLE
Update Lerna to facilitate LICENSE publishing

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3151]
#### Description
As described in [this Lerna PR](https://github.com/lerna/lerna/pull/1465), specifically [this comment](https://github.com/lerna/lerna/pull/1465#issuecomment-405184876), older versions of Lerna do not include LICENSE files when publishing packages. In addition to appeasing some corporate lawyers, some licenses require that the full text be distributed with the source. From the above linked PR:

"Without full license text, the sub packages are not properly licensed, even though the license field contains a valid SPDX identifier. Some licenses, such as MIT, even explicitly require packing the text together with the distribution..."

MIT is of course the license under which deck.gl is published.

#### Repro Steps
Install any deck.gl module using `yarn` or `npm`. Note that paths like `node_modules/@deck.gl/layers` do not contain a LICENSE file.

**Comment by bclinkinbeard** [comment]
I am happy to submit a PR bumping the Lerna version in lerna.json if that would help, but Lerna isn't listed as a devDependency so I'm guessing it's installed globally by whoever publishes the modules. Same goes for luma.gl and loaders.gl so I can submit PRs there as well. Just let me know the best way to proceed. Thanks!

**Comment by ibgreen** [comment]
@bclinkinbeard We have extracted our build chain to `ocular-dev-tools`: https://github.com/uber-web/ocular/tree/master/modules/dev-tools.

If you feel adventurous, you are welcome to do a PR there. After landing we would need to publish a new version and then bump ocular-dev-tools in the various repo.

**Comment by bclinkinbeard** [comment]
Hmm, does this mean it's still using Lerna though? https://github.com/uber-web/ocular/blob/master/modules/dev-tools/scripts/publish.sh

I sort of hope that is not the case because I would have expected the version of Lerna there, 2.9.1, to have the corrected behavior.

**Comment by donmccurdy** [comment]
I believe the relevant change to Lerna would only be in >3.x – https://github.com/lerna/lerna/tags?after=v3.0.5.

**Comment by bclinkinbeard** [comment]
Looks like you are right. I just opened https://github.com/uber-web/ocular/pull/197 on my phone, hope that's all that is needed.

**Comment by ibgreen** [comment]
> Hmm, does this mean it's still using Lerna though

Yes, it used lerna for monorepos (including deck, luma, loaders). ocular-dev-tools auto detects if the repo has a `modules` directory and in that case uses lerna in the scripts.

**Comment by bclinkinbeard** [comment]
https://github.com/uber-web/ocular/pull/197 has now been merged (thanks @Pessimistress!!). How would you prefer to go about publishing new releases? Should I create separate issues in the loaders.gl and luma.gl repos?

Thank you!

**Comment by Pessimistress** [comment]
7.0.10

**Comment by Pessimistress** [comment]
I believe all dependencies now contain LICENSE files.

**Comment by bclinkinbeard** [comment]
Thanks so much for the quick turnaround by everyone involved, I really
appreciate it. 🚀
