### ISSUE TITLE
Drawing layers on a map using deck gl

### ISSUE THREAD

**Issue by CorentinAmbroise** [uber/deck.gl#3153]
Hello there, 

I'm not sure if that is the correct place to ask this question but I couldn't find the answer, so please excuse me in advance if it is not, I am quite new to full stack development.

I am building a webapp to allow a user to visualize mobility data in a pretty and easy way, but I also want him to be able to draw simple features (polygons, points, ...) on the map if he wants to.
I've been trying for the past few hours to implement this on a map using deck.gl. In order to do this, I want to use the api mapbox-gl-draw, which was used before to do the same job when the webapp was only using mapbox and its features, but I am open to suggestions. Now that I managed to link my static mapbox map and my deck gl canvas through the WebGL as explained in the documentation, I would like to be able to draw. In order to do this, I need to use mapboxDraw instance's cursor over the one from deck gl, and I don't know how to do it properly. I guess it must be in the GL's settings but I'm not sure where to look. 

I'm not sure if that framework is designed to implement this kind of thing, as I have understood I think it is more only about data vis, but if it is, wouldn't it be nice to have the mapbox-gl-draw equivalent within the framework?

Anyway, thanks in advance for your answers,

Corentin

**Comment by bclinkinbeard** [comment]
Take a look at https://nebula.gl/
