### ISSUE TITLE
Showcase request: ProPublica gambling map

### ISSUE THREAD

**Issue by eads** [uber/deck.gl#3160]
We used Deck.gl to visualize the growth of video gambling terminals in Illinois over time for this story: https://features.propublica.org/the-bad-bet/how-illinois-bet-on-video-gambling-and-lost/#map

Figured it might be a fun showcase of using Deck.gl for very nuts-and-bolts real world explanatory data viz. The dataset isn't huge or anything, but it does tell a compelling and important story.

**Comment by 1chandu** [comment]
Thanks for sharing !!!

**Comment by ibgreen** [comment]
@tgorkin - a potential showcase for the deck.gl website
