### ISSUE TITLE
MapboxLayer Properties not updating

### ISSUE THREAD

**Issue by CP-Ram** [uber/deck.gl#3165]
Hi,
I am using Deck.gl to visualize 3d layer with mapbox gl map and it's very interesting library.

I have created MapboxLayer type as HexagonLayer and added into mapbox gl map instance.
but to update properties for the layer,first i am getting layer from mapbox instance and then trying to update properties of the layer like visible true to false,it is not working.

Here is the stackoverflow question:
[(https://stackoverflow.com/questions/56364705/how-to-update-visible-props-for-deckgl-mapbox-mapboxlayer)](url)

**Construct and Add to Mapbox:**
```
.....
this.map = new MapboxGl.Map(mapOptions);
...
...
const hexagonLayer = new MapboxLayer({
            type: HexagonLayer,
            id: 'myhexaLayer',
            data,
            colorRange: COLOR_RANGE,
            elevationRange: [0, 10000],
            elevationScale: 1,
            extruded: true,
            getPosition: d => d.COORDINATES,
            getElevationValue: e => Math.sqrt(e[0].properties.height) * 10,
            getColorValue: this.getColorValue,
            lightSettings: LIGHT_SETTINGS,
            pickable: true,
            onHover: setTooltip,
            opacity: 1,
            visible: true,
            ...options
        });

this.map.addLayer(hexalayer);
```
**GetLayer from mapbox and update properties:**

```
 var hexaLayer: any = this.map.getLayer('myhexaLayer');
          //*****first way
		  hexaLayer.implementation.props.visible = false;
		  
		  //******Second way
          hexaLayer.setProps({ visible: false });
          
		  this.map.addLayer(hexaLayer);
```

#### Repro Steps
1.create Mapbox layer and add into mapbox gl map instance.
2.get existing added layer from map object.
3.update properties of the layer. 

I am not sure it's bug or where i'm doing wrong.can you give suggest me to correct way.

**Comment by Pessimistress** [comment]
@CP-Ram `map.getLayer` does not return the original `MapboxLayer` instance. Mapbox converts the layer to something else internally, and this is not something we can control. To update the layer you need to save the original `hexgonLayer` that you created, and call `hexgonLayer.setProps`.

Here is an example: https://codepen.io/Pessimistress/pen/dEweKz

**Comment by CP-Ram** [comment]
@Pessimistress Thanks for explaination reply !!!
