### ISSUE TITLE
LineLayer with binary data

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3169]
I'm attempting to use LineLayer with binary data similar to what I've done with ScatterplotLayer but I'm getting an error I don't quite understand. My abbreviated code is below.

```
const pathLayer = new LineLayer({
  widthUnits: 'pixels',
  widthScale: 1,
  widthMaxPixels: 100,
  widthMinPixels: 3,
  getWidth: 5,
  getColor: [57, 73, 171],
  data: this.data, // {length: n}
  instanceSourcePositions: this.sourcePositions, // Float32Array(n*3)
  instanceTargetPositions: this.targetPositions, // Float32Array(n*3)
  instanceTargetPositions64xyLow: this.instanceSourceTargetPositions64xyLow, // Float32Array(n*4)
});
```

And the error I am getting is `Cannot read property 'sourcePosition' of undefined` from [this line](https://github.com/uber/deck.gl/blob/master/modules/layers/src/line-layer/line-layer.js#L34). Could you point me in the right direction?

**Comment by Pessimistress** [comment]
Looks like you're missing `instanceSourcePositions64xyLow`?

**Comment by bclinkinbeard** [comment]
Hmm, it actually looks like the prop name is just `instanceSourceTargetPositions64xyLow`. When I use that my lines render, but they're only correct at certain zoom levels. At other zoom levels lines are missing and one connects to a point off screen.

Setting `instanceSourcePositions64xyLow` and `instanceTargetPositions64xyLow` separately results in nothing rendering.

**Comment by Pessimistress** [comment]
How are you generating the low positions? They are not really lower part of a 64bit float; they are 32bit floats calculated as `x - Math.fround(x)`.

**Comment by bclinkinbeard** [comment]
Ha, it looks like generating them was the problem. If I just do `    this.instanceSourceTargetPositions64xyLow = new Float32Array(numSrcs * 4);` and leave it empty it works. Thanks!
