### ISSUE TITLE
Text layer with background

### ISSUE THREAD

**Issue by maps82** [uber/deck.gl#3178]
Hi! Can you give me a short and rough recipe on how I can achieve to render texts with text layer, but with white rounded background boxes, that have the same width as the text? I think I have to create a custom layer.

Is there a best practices for this without copying too much internals and messing around with a custom FontAtlasManager?

Thank you very much!

**Comment by maps82** [comment]
I solved this by writing a custom background layer, based on the original text layer source, together with a custom fontAtlasManager to calculate the background width based on the text, and modified the canvas texture created by the fontAtlasManager.

I think this is currently the only way to achieve such a background box. I leave this open in case someone has better ideas. If not feel free to close this issue.

**Comment by Pessimistress** [comment]
@xintongxia I think we could easily expose a TextLayer prop to set the background color of the texture canvas?

**Comment by maps82** [comment]
Would be great. But additionally I need (and have now) some rounded corners on the left and right of the background.

**Comment by maps82** [comment]
<img width="329" alt="Bildschirmfoto 2019-06-04 um 23 35 29" src="https://user-images.githubusercontent.com/12223156/58915516-7b12a200-8721-11e9-90ce-7063f9610759.png">

Thats what it looks currently in my case, but there is more to come...

**Comment by vnugent** [comment]
@maps82  would you please share the code snippet?

**Comment by danmarshall** [comment]
@Pessimistress : Would a background color enhance picking? I am hoping to get less accurate picking of text - for example, I would like the inside of the `o` and space between characters to be pickable.

![Text Picking](https://user-images.githubusercontent.com/11507384/63617252-d3797300-c59d-11e9-8a32-63e06f833fc6.gif)

**Comment by Pessimistress** [comment]
@xintongxia The picking issue should be fixable even without supporting a secondary color , if we make the cuttoff configurable: https://github.com/uber/deck.gl/blob/master/modules/layers/src/icon-layer/icon-layer-fragment.glsl.js#L47

**Comment by miguel-viola** [comment]
@maps82 
> I solved this by writing a custom background layer, based on the original text layer source, together with a custom fontAtlasManager to calculate the background width based on the text, and modified the canvas texture created by the fontAtlasManager.
> 
> I think this is currently the only way to achieve such a background box. I leave this open in case someone has better ideas. If not feel free to close this issue.

How does the fontAtlasManager work? I'm trying to do the same thing as you but with no success..

**Comment by xintongxia** [comment]
I'll enable `text-layer` to support customized background color this week.

**Comment by maps82** [comment]
> How does the fontAtlasManager work? I'm trying to do the same thing as you but with no success...

It's quite hacky and tailored to my use case, so I would need some time to prepare a clean generic sample, without showing too much of my customers code here, which I can't do.

I hope the upcoming text layer background feature will serve you. The trick for the background is basically to copy the text layer/fontmanager and modify the canvas it creates to your needs. And then overlay it with the regular text layer.

**Comment by miguel-viola** [comment]
Is there any documentation for the fontAtlasManager?

**Comment by mdsviola** [comment]
@xintongxia Did you manage to add custom background support?

**Comment by timeisgolden** [comment]
> <img alt="Bildschirmfoto 2019-06-04 um 23 35 29" width="329" src="https://user-images.githubusercontent.com/12223156/58915516-7b12a200-8721-11e9-90ce-7063f9610759.png">
> 
> Thats what it looks like currently in my case, but there is more to come...
@maps82 Hello, I want to implement the textLayer with rounded background.
can you share an example that you have done?

Thanks

**Comment by maps82** [comment]
I'm sorry, I can't provide any sample code here as I'm no longer working on the project where I used this and don't have source access anymore 😔

**Comment by timeisgolden** [comment]
> I'm sorry, I can't provide any sample code here as I'm no longer working on the project where I used this and don't have source access anymore 😔

Thanks for your replay, 
I really wanted to implement the IconLayer with rounded background in my project.
and have no way to implement it.
anyway, thanks.
