### ISSUE TITLE
Trips disappeared when the currentTime is zero

### ISSUE THREAD

**Issue by chengang0621** [uber/deck.gl#3184]
when i use tripslayer without react like follow issue [tripslayer](https://github.com/uber/deck.gl/issues/2425)
the animation code is 
`    

            function _animate() {

                var loopLength = 30, 

                    animationSpeed = 20;

                const timestamp = Date.now() / 1000;

                const loopTime = loopLength / animationSpeed;

                var currtime = ((timestamp % loopTime) / loopTime) * loopLength;

                const tripsLayer = new TripsLayer({

                    id: 'trips-layer',
                    data: data,
                    getPath: d => d.segments,
                    getColor: d => (d.vendor === 0 ? [253, 128, 93] : [23, 184, 190]),
                    opacity: 0.8,
                    widthMinPixels: 2,
                    rounded: true,
                    trailLength: 180,
                    currentTime: currtime
                })

                deckmap.setProps({ layers: [tripsLayer] });

                this._animationFrame = window.requestAnimationFrame(_animate);
            }
`
when the currtime is zero or very small，the tripsLayer disappeare; who can help me

**Comment by jianhuang01** [comment]
that's by design for trips layer, the currentTime is used for the trip animation(grow, fade).
