### ISSUE TITLE
Example of attributes transition

### ISSUE THREAD

**Issue by harisbal** [uber/deck.gl#3185]
Hello,
I'm attempting to apply a color transition of the paths in a TripsLayer.
At some point during the simulation I want paths to gradually turn from let's say red to green. I have managed to achieve the color change but not the transition. My question is more about the returning values of the `enter` function, since I cannot understand what the indexes of `value` represent in the docs example

**Documentation example**
```
new Layer({
  transitions: {
    getPositions: 600,
    getColors: {
      duration: 300,
      easing: d3.easeCubicInOut,
      enter: value => [value[0], value[1], value[2], 0] // fade in
    }
  }
});
```

**My (non-working) example**
```
new TripsLayer({
        id: 'trips',
        data: this.state.trips,
        getPath: d => d.Segments,
        getColor: d => d.Completed ? [255, 0, 0] : [0, 255, 0]),
        currentTime: this.state.time,
        transitions: {
          getColors: {
            duration: 2000,
            easing: d3.easeCubicInOut,
            enter: value => [value[0], value[1]]
          }
        }
      }),
```

The `Completed` attribute of trips changes dynamically during the simulation so I suppose that an `updateTriggers` should be also required but I can't make it work. 

As a final remark, in the `transitions` block why we use `getColors` instead of `getColor` ?

Thank you very much and apologies for all these questions

**Comment by jianhuang01** [comment]
@harisbal This is an interesting feature, thanks for asking questions. I did some experiments based on our trip example. Here is the code snippet.
```js
function switchColor() {
  setTimeout(() => { changeColor = !changeColor; switchColor() }, 5000);
}
// set timer to modify changeColor flag every 5 secs
switchColor();

new TripsLayer({
        id: 'trips',
        data: trips,
        getPath: d => d.segments,
        // switch color based on the changeColor flag
        getColor: changeColor ? [23, 184, 190] : [253, 128, 93],
        opacity: 0.3,
        widthMinPixels: 2,
        rounded: true,
        trailLength,
        currentTime: this.state.time,
        // add transition
        transitions: {
        // Need be getColor which matches the accessor name
          getColor: {
            duration: 2000,
            // the color here need be the old color of getColor accessor
            enter: () => changeColor ? [253, 128, 93] : [23, 184, 190]
          }
        },
        updateTriggers: {
          // color will be updated when changeColor flag changes
          getColor: {changeColor}
        }
      })
```

![image](https://user-images.githubusercontent.com/15093546/59299649-03bda080-8c42-11e9-8e7a-151a08a2c925.png)

**Comment by harisbal** [comment]
@jianhuang01 thank you very much for your reply.
I'll checkout your answer but I need a clarification.

In my example, the change of color relies on a change of the data and not of a (global) variable.
During the simulation, an appropriate function changes the `Completed` attribute in my data from `false` to `true `. Therefore, I cannot use `enter: () => changeColor ? [253, 128, 93] : [23, 184, 190]` because `changeColor` depends on each separate path. 

If I read the [documentation](https://github.com/uber/deck.gl/blob/master/docs/api-reference/layer.md#transitions-object-optional) properly I could use something along the lines of this
 `enter: (newColor, path) => path.Completed ? oldColor` but I haven't managed to get it to work.

Am I missing something?

Cheers

**Comment by Pessimistress** [comment]
@harisbal The keys in `transitions` should always match the accessor that is being transitioned. So `getColor` for TripsLayer.

In your use case, `enter` should not be necessary. `enter` is only called if your to-value is larger than from-value, i.e. something new has "entered", in which case we need to know where it enters from. If you are transitioning the color of an existing path, it will always be transitioned from the color that it was last rendered with.
