### ISSUE TITLE
TouchAction with DeckGL MapController

### ISSUE THREAD

**Issue by Ventronik** [uber/deck.gl#3189]
I am using React Map GL, and it has the ability to control touch interactions: touchAction="pan-y" 

I am adding a deck gl wrapper around the map and I have to use the controller in DeckGL now to control the map. Does the DeckGL Controller allow for touchAction="pan-y"  or is that not supported?

**Comment by Pessimistress** [comment]
Deck does not support this prop right now, we can add one.

**Comment by Ventronik** [comment]
@Pessimistress Yes, please add.

**Comment by Pessimistress** [comment]
7.1.4: https://github.com/uber/deck.gl/blob/7.1-release/docs/api-reference/deck.md#touchaction-string-optional
