### ISSUE TITLE
Can you give pointers on how to animate dashed lines or icons along a path?

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3198]
I need to create line segments that show a flow direction. I had hoped for an easy win by mimicking the SVG technique of updating the dash offset over time with PathLayer, but it doesn't have an explicit offset attribute and I didn't have much luck. The shader code also didn't seem structured in a way that I could easily inject tweaks. Is copying and tweaking the PathLayer shader the best approach for animating dashes?

A more flexible and robust solution would be animating icons or other graphics (a chevron, triangle, etc) along the path, but I'm not exactly sure where to start with that one. Is it just a matter of combining PathLayer and IconLayer and calculating the icon's angle correctly? And then setting up some kind of loop mechanism?

Any links or advice would be great. Thanks!

**Comment by ibgreen** [comment]
@bclinkinbeard 
> The shader code also didn't seem structured in a way that I could easily inject tweaks. Is copying and tweaking the PathLayer shader the best approach for animating dashes?

I would typically do something like this in the fragment shader. Basically, if the fragment shader has information on where along the path the fragment is (the path layer should already provide this to support the dashes), you can manipulate colors based on a uniform, using smoothstep, modular arithmetic etc, and by incrementing the uniform (you could just use one of the existing `animationProps`, you can move the effect forward along the path each frame.

You may need to active the `Deck.animation` prop to force deck.gl to rerender each frame except when some layer changes.

> The shader code also didn't seem structured in a way that I could easily inject tweaks. Is copying and tweaking the PathLayer shader the best approach for animating dashes?

We have a shader injection system to help us avoid forking the original shader code (particularly painful in case of the PathLayer...). It may require adding an injection point to the path layer shaders. @tsherif can provide more information on that.

FWIW, he fragment shader should be much easier to work with than the vertex shader.

>  more flexible and robust solution would be animating icons or other graphics (a chevron, triangle, etc)

That is an option but the most performant animation would be done in the fragment shader of the path layer because it would execute exclusively on the GPU.

**Comment by Pessimistress** [comment]
FYI the position along the path can be accessed in the fragment shader with this: https://github.com/uber/deck.gl/blob/7.1-release/modules/layers/src/path-layer/path-layer-fragment.glsl.js#L35

I believe both of your use cases can be achieved by tweaking the PathLayer fragment shader.

**Comment by bclinkinbeard** [comment]
I've made some progress, thanks! @ibgreen do I just pass `animate:true` when instantiating deck? How do I verify it’s turned on? I wasn’t able to find much in the docs.

**Comment by ibgreen** [comment]
@bclinkinbeard https://deck.gl/#/documentation/deckgl-api-reference/deck?section=_animate-experimental-

**Comment by bclinkinbeard** [comment]
Hmm, I don't think it's working but I'm not sure how to verify. I'm setting `_animate: true` in the props I pass to `new Deck()` and incrementing a counter in my fragment shader's `main()`, but the counter doesn't seem to increment.

**Comment by ibgreen** [comment]
there is no global state between shader invocations, you would need to supply a uniform from JS.

**Comment by bclinkinbeard** [comment]
Thanks for all the help! I was able to add a `dashPattern` uniform that supports up to 24 integers representing a dash/gap pattern, and properties that allow the animation to be enabled/disabled, modulated, and reversed.

**Comment by bclinkinbeard** [comment]
In some scenarios I'm seeing a major FPS drop just from setting `_animate: true`. Even if I have no accessor functions running, and just a single layer, FPS goes from 75 to ~20 when turning it on. This happens in 2 of 3 scenarios I currently have, but I don't understand what's different about any of them that would cause this. Any ideas on how to diagnose? Thanks!

**Comment by ibgreen** [comment]
How do you measure FPS? 

Keep in mind that when `_animate` is false, deck.gl's `requestAnimationFrame` returns without rendering if nothing visible to deck has changed (layers, viewport, etc).

When you set it to `true`, deck draws every frame ignoring the "dirty check".

This means FPS could be "artificially" inflated when it is false, if you just measure requestAnimationFrame count.

That said, 20 FPS sounds slightly low for a single layer unless your data set is quite big.

**Comment by bclinkinbeard** [comment]
I'm just using the threejs FPS monitor bookmarklet. My dataset is pretty
big so maybe that's the issue. I'm only enabling _animate so I can pass
updated timestamp uniforms to my shaders. Is there a better/lighter way to
do that while still avoiding the CPU?

**Comment by ibgreen** [comment]
OK. The point is, if _animate is not enabled, nothing is rendered unless deck props change, so you are getting a "virtual" FPS, normally capped at 60 FPS (you seem to have some higher sync letting you get to 75 FPS). So you are not actually seeing a "drop" in FPS, you are just seeing the real FPS since you are now rendering each frame.

With that understood, as to increasing the FPS, you may first want to rule out that deck.gl is doing anything on the CPU each frame. If you are not changing any deck.gl props (e.g trying to change a time uniform from JS) but just using the `animationProps` from the animation loop you should be good.

In that case, you are down to the GPU rendering speed. 20 FPS means that the GPU needs 50ms to render your frame. 

Since I understand that you have modified the shader, you can start experimenting with tweaking the shaders. Compare FPS with and without the changes you made and see if that affects FPS. If not, you are welcome to play around and tweak our code and see if there is something on our side that could be optimized.

Some of our features are dependent on uniforms, that are checked with if statements in the shader. Disabling those uniforms (or cutting the GLSL code) could make the shaders faster.

**Comment by bclinkinbeard** [comment]
That all makes sense, thank you.

> If you are not changing any deck.gl props (e.g trying to change a time uniform from JS) but just using the `animationProps` from the animation loop you should be good.

I'm not familiar with `animationProps`, I set `_animate: true` and wrote accessor functions to avoid the CPU. I've not come across `animationProps` in the docs, can you point me to more info. Thanks a bunch.

**Comment by ibgreen** [comment]
I am not sure it is documented in deck.gl but deck.gl uses a luma.gl `AnimationLoop` (a documented class in luma.gl) which provides new animation props every frame. 

I believe that these are exposed on `layer.context.animationProps`, so in `Layer.draw` you can just reference e.g. `layer.context.animationProps.tick`.

This way you don't need to activate the deck.gl update cycle every frame just to bump a time based prop/uniform to drive animation of your dashed lines etc.

**Comment by bclinkinbeard** [comment]
I see the object, but I'm not sure how to use it. I also need more than just a ticker, I have a time scrubber in my app so I'm trying to pass an updated `minTime` and `maxTime` uniform to the shader in response to user actions. Is `updateTriggers` the way to do that? I had thought the `_animate` approach was right because it called my accessor functions without requiring a new layer descriptor/assignment.

**Comment by ibgreen** [comment]
> I also need more than just a ticker, I have a time scrubber in my app so I'm trying to pass an updated minTime and maxTime uniform to the shader in response to user actions.

You will typically need to provide (and occasionally update) some new uniforms. What I am pointing out is that if you can avoid supplying new props/layers to deck.gl every frame and just use the luma.gl animation props in your shader for driving the animation, then performance should be better.

> I had thought the _animate approach was right because it called my accessor functions without requiring a new layer descriptor/assignment.

Hmm, that does not seem right. The `_animate` flag should just force deck.gl to redraw every frame, even if no layers/props have changed. 

https://github.com/uber/deck.gl/blob/478a7bbe6c2f61e2905cccd5044381637c3fbffd/modules/core/src/lib/deck.js#L290 (it returns a "redrawReason" string explaining why it is redrawing that frame.)

It should not be calling any accessor functions, unless you supply new layers and props to deck.gl (or if you have called some special function to "dirty" the layer state).

If you are not using `animationProps` and you are driving animation yourself by constantly updating deck with new layers and props, you should probably not set `_animate` is it could lead multiple redraws of the same frame (if your update code is not fast enough), which from your app's perspective would likely be hurting performance.

>  Is updateTriggers the way to do that?

updateTriggers is a way to force update of selected attributes. Again, attribute updates happen on CPU and is expensive. The best animation performance comes from not updating attributes and doing all the animation in shaders. But if your animation does require attribute to be updated every frame, then use updateTriggers to ensure only the minimal amount of attributes are recalculated.

**Comment by bclinkinbeard** [comment]
Thanks, I think I'm up to speed now.

> You will typically need to provide (and occasionally update) some new uniforms.

This is exactly what I'm trying to do in the most performant way. I can access my updated time values  without updating layers and props, but I'm not sure how to get them into the shader. I can assign them to `animationProps`, but I don't know how to then access them from the shader.

```
this.deckLayer.context.animationProps.minTime = this.minTime;
this.deckLayer.context.animationProps.maxTime = this.maxTime;
```

Can you help me connect these last two dots? Thanks so much!

**Comment by bclinkinbeard** [comment]
I think I figured it out. I thought I needed [property animation](https://github.com/uber/deck.gl/blob/203970dcfc/docs/developer-guide/animations-and-transitions.md#property-animation) but I guess I just need to call `draw()` on the layer? Is this the right way to trigger an update when my time uniforms change?

```
this.deckLayer.draw({
  uniforms: {
    minTime,
    maxTime,
  }
});
```

**Comment by ibgreen** [comment]
Almost... I think `layer.draw` should be called already, you should not need to call it directly.

For your custom layer you can set uniforms on the layer's `Model` instance by overriding `layer.draw` or `layer.updateState`. 

Call `this.model.setUniforms({minTime, maxTime});`

**Comment by bclinkinbeard** [comment]
Cool, that's what I'm doing. `this.deckLayer` above was meant to refer to my custom layer, so that `draw()` call is invoking the overridden `draw()`, which is included below.

```
draw(args: {uniforms}) {
  super.draw({
    uniforms: {
      minTime: this.props.minTime,
      maxTime: this.props.maxTime,
      ...args.uniforms,
    }
  });
}
```

Performance is good with this method and deck is idle when my uniforms aren't changing. Thanks for all the help!!

**Comment by ibgreen** [comment]
@bclinkinbeard Happy to hear that it worked out. 

PS - Not sure if you can share any of the results, but if you can, I'd love to see e.g. a GIF of your animated layer in action. Always interested in seeing what people build on top of deck.gl.

**Comment by bclinkinbeard** [comment]
Hey @ibgreen I will try to share a GIF soon. It's broken atm due to a refactor. :)

**Comment by Fl0rianFischer** [comment]
@bclinkinbeard do you have any code you could share? Currently trying to solve the same problem but having real difficulty implementing the shader code.

**Comment by NameFILIP** [comment]
@bclinkinbeard if by any chance you could extract it into a [codesandbox](https://codesandbox.io/) example for all future readers, that would be very helpful!
