### ISSUE TITLE
(dev branch) Layer#getNumInstances fails on empty arrays, Sets

### ISSUE THREAD

**Issue by nrabinowitz** [uber/deck.gl#32]
`Layer#getNumInstances` requires `data.size` or `data.set` to be truthy, when `0` is a valid value. An empty `Immutable.List` succeeds, but an empty array or Set will throw an error.

**Comment by ibgreen** [comment]
@tomoueda @nrabinowitz Fixed in deck.gl 3.0.0-beta4
