### ISSUE TITLE
Vertical movements in TripsLayer drawn as static black lines

### ISSUE THREAD

**Issue by harisbal** [uber/deck.gl#3215]
Probably related to #2302 

Attempting to draw vertical movements (changing only the z coordinate between 2 segments) results in black segments drawn at the beginning of the animation `currentTime=0` and remaining there forever.

In the image below the yellow path is supposed to reach the bottom of the black line and then move vertically upwards. As you can see the vertical segment is black and drawn at a wrong time.
![image](https://user-images.githubusercontent.com/6556306/59112151-57767400-893a-11e9-9dd4-9f9b5df53465.png)

using the sample data below can reproduce the issue
```
[{"Segments":[
    [-2.358666776,51.35911178,1000],
    [-2.3580923191,51.37119802,1000],
    [-2.35958041,51.38328429,1000],
    [-2.35958041,51.38328429,4000]],
    "Timestamps":[
        31669.0,
        31904.45,
        32139.9,
        57948.0]}]
```

**Comment by Pessimistress** [comment]
By default PathLayer/TripsLayer extrudes on the xy plane. If you wish to draw arbitrary 3d shape check out the new `billboard` prop in v7.1.

**Comment by harisbal** [comment]
@Pessimistress, thanks a lot, it works like a charm now. Maybe mention it in the docs so you can avoid similar stupid questions.
