### ISSUE TITLE
Drawing GeoJSON layer with new data causes a buggy render

### ISSUE THREAD

**Issue by sam-coxon** [uber/deck.gl#3221]
#### Description
When rendering different geoJSONs sequentially, the data from the previously drawn polygon seems to persist in a buggy way: The _border_ of the new polygon is drawn correctly, but the _fill_ of the new polygon seems to be rendering based on the data of the last drawn polygon.
(Pictures below)

initial geometry:
<img width="462" alt="Screen Shot 2019-06-10 at 2 06 09 PM" src="https://user-images.githubusercontent.com/47752881/59216132-fd1f2280-8b88-11e9-8fbf-1d2a8708372d.png">
second geometry (a smaller polygon, notice that the boundary is rendered correctly but the fill is buggy because it's drawing fill points from the initial geometry (above))
<img width="448" alt="Screen Shot 2019-06-10 at 2 06 29 PM" src="https://user-images.githubusercontent.com/47752881/59216133-fd1f2280-8b88-11e9-9092-561d75f3b9fc.png">

#### Repro Steps
To reproduce, pass a new geoJSON to the data prop of geojson layer (in my case I do this with a slider). Additionally this problem seems to only be a problem when the new geojson data is a _smaller_ geometry than the previous geojson. i.e. a larger geometry must have been rendered at some point previously, for the buggy fill-points to exist.

#### Environment (please complete the following information):
 - Framework Version: Deck 7.1.0
 - Browser Version: Chrome 74.0.3729
 - OS: macOS 10.14.5

Thank you for the help

**Comment by Pessimistress** [comment]
@sam-coxon Thanks for reporting. We patched a bug in 7.1.1, can you try and see if the problem persists in the latest version?

**Comment by sam-coxon** [comment]
@Pessimistress That fixed it! Thanks for the quick response and the patch.
