### ISSUE TITLE
building layer && polygon layer

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3222]
I have a question .
Now, I have many buildings data. more than 400,000 .  some of buildings corrdinate combination are complex . so  building's  json file is large.  
After   I load json file , program running is not smooth.
In mapbox ,I can publish a buildilng layer by geoserver.  the building layer  load by addLayer() and addSource() function , and can show or hide by zoom level.  
In deck.gl ,can I use similar way to ease the burden of  program running.

**Comment by Pessimistress** [comment]
You need to use the `TileLayer` for a mapbox-like behavior (which only loads/renders data that is visible in the current viewport).

**Comment by HeiYanjing** [comment]
> You need to use the `TileLayer` for a mapbox-like behavior (which only loads/renders data that is visible in the current viewport).

ok, thank you . I have a try.
