### ISSUE TITLE
Mapping Arrow Keys Panning to Button onClick

### ISSUE THREAD

**Issue by michaelsklepowich** [uber/deck.gl#3237]
Hello, I am using deck.gl within a react component inside a redux app that toggles between Orbit and Orthographic views. 

Regardless of the specific view, I want to create a set of "map control" buttons that the user can use to rotate or pan as an alternative to the keyboard or mouse. I want the pan from these control buttons to modify the viewState the same as if the user had pressed the arrow keys. 

I was able to recreate rotating with buttons that change the rotationX and rotationOrbit in my viewState. However, with panning, it seems that the viewState.target is incremented by values derived from the current viewState. 

From the docs, it looked as though I would need to create a custom controller, but I decided to make an issue to ask for any input. 

Love the work you guys are doing, thanks.

**Comment by jianhuang01** [comment]
One potential solution is that you can fake the mouse and keyboard events, pass them to controller's [handleEvent](https://github.com/uber/deck.gl/blob/c9ad4f491370113006b7611e2161354bfa7bf3b3/modules/core/src/controllers/controller.js#L75) function.

**Comment by michaelsklepowich** [comment]
Thanks for the insight, I'll start with that approach.

Are there any examples I could follow for passing events from other components to a controller?

**Comment by Pessimistress** [comment]
@michaelsklepowich We do not currently expose the panning logic. Depending on how much control you need, you can do one of the following (both of which are very hacky):

- As @jianhuang01 suggested, pass a simulated keyboard event to the controller: https://codepen.io/Pessimistress/pen/gNaXGb
- Find out the new view state:

```js
import {_OrbitController as OrbitController} from '@deck.gl/core';
const OrbitState = new OrbitController().ControllerState;

new OrbitState(currentViewState)
  .moveRight()
  .getViewportProps();	// This will give you the new view state
```

**Comment by michaelsklepowich** [comment]
Thank you both, @jianhuang01 and @Pessimistress. 

I was able to get panning working based on the "Find out the new view state" example by bringing the `_getUpdatedState` & `_calculateNewTarget` methods into my component. 

A very hacky approach, indeed.
