### ISSUE TITLE
ScenegraphLayer example not working

### ISSUE THREAD

**Issue by ForeverArt** [uber/deck.gl#3239]
#### Description
[ScenegraphLayer example](https://github.com/uber/deck.gl/blob/master/examples/website/scenegraph-layer) not working.

Could not see the rendered 3d model although the file `Duck.glb` is already fetched.

#### Repro Steps
- Clone repo according to [README.md](https://github.com/uber/deck.gl/blob/master/examples/website/scenegraph-layer/README.md).
- Use my own `MAPBOX_TOKEN` in `app.js`.
- `yarn`
- `npm start`

#### Environment (please complete the following information):
 - Framework Version: [deck.gl 7.1.0, ...](https://github.com/uber/deck.gl/blob/master/examples/website/scenegraph-layer/package.json)
 - Browser Version: Chrome 74.0.3729.157 (Official Build) (64-bit)
 - OS: Ubuntu 16.04.1
 - Node: node v12.2.0

#### Render Result
![Screenshot from 2019-06-14 14-01-33](https://user-images.githubusercontent.com/23061097/59486993-cd845900-8ead-11e9-8630-456821898b30.png)

**Comment by SymbolixAU** [comment]
Do you receive any errors in the javascript console? (In chrome press Ctrl + Shift + C, then go to the 'console' tab)

**Comment by ForeverArt** [comment]
Following warnings should not matter because the map is visible.

![bug](https://user-images.githubusercontent.com/23061097/59739102-15ccbe00-9296-11e9-88ff-3216debd86ae.png)

I removed the `transitions` attribute of  the `scenegraph-layer` at line 120 which this should not matter either, nothing else changed in `app.js` any more.

**Comment by ForeverArt** [comment]
If i don't remove the`transitions` attribute, errors will occur, as shown in the following picture.

![bug_transition](https://user-images.githubusercontent.com/23061097/59739489-a48e0a80-9297-11e9-88aa-88d1c3e24d9b.png)

**Comment by Pessimistress** [comment]
@georgios-uber

**Comment by georgios-uber** [comment]
looking...

**Comment by georgios-uber** [comment]
Cannot reproduce issue.

**Comment by georgios-uber** [comment]
I am able to verify that both the display and animation work on the latest version of deck master.

@ForeverArt can you delete your node_modules and yarn.lock and install again?
Are you using `yarn start-local` to start the example?

**Comment by ForeverArt** [comment]
Thanks @georgios-uber , ducks are visible now!
However, still got same error when enable animation work as mentioned before, should i open a new issue?
 
What's the difference between `start` and `start-local`?

At last, i will appreciate it if you update `README.md` by replacing `npm start` with `yarn start-local`.

**Comment by Pessimistress** [comment]
@ForeverArt `start-local` runs the example against the source code on the current branch (aka dev mode). `start` uses the published version of deck.gl installed in node_modules.

@georgios-uber Examples are supposed to work with both. If the current prod release does not work please patch it.

**Comment by georgios-uber** [comment]
#3370

**Comment by georgios-uber** [comment]
Fixed.
