### ISSUE TITLE
geojson icons misaligned when pitch > 0

### ISSUE THREAD

**Issue by vnugent** [uber/deck.gl#3247]
#### Description
I recently upgraded from v6.3 to v7.1.4 and noticed all of my geojson points are slightly off. The further they are from the center of the screen the worse they will get.  The problem exists only when pitch > 0.

Ok in the center of the screen
<img width="357" alt="Screen Shot 2019-06-18 at 12 30 42 PM" src="https://user-images.githubusercontent.com/3805254/59675691-13029800-91c6-11e9-9f60-8ef001835193.png">

Now it's not
<img width="470" alt="Screen Shot 2019-06-18 at 12 30 18 PM" src="https://user-images.githubusercontent.com/3805254/59675741-31689380-91c6-11e9-80e2-75f0ac2f64c4.png">

#### Repro Steps

https://codesandbox.io/s/cold-leftpad-0v9l5

note: need to provide a mapbox token

**Comment by Pessimistress** [comment]
Comment out the `altitude` from your view state and it will work. For deck canvas to synchronize with mapbox the camera altitude cannot be customized.
