### ISSUE TITLE
Standalone Bundled Version

### ISSUE THREAD

**Issue by mertemin** [uber/deck.gl#3248]
What is the suggested way of generating a standalone bundled version of the library (both minified and non-minified)? [This page](https://deck.gl/#/documentation/getting-started/using-standalone) provides links to standalone library hosted on unkpg.com, but I'd like to know if I can generate it myself.

**Comment by Pessimistress** [comment]
You can clone the repo and run 

```bash
yarn bootstrap
cd modules/main
yarn prepublishOnly
```

This will generate dist.min.js and dist.dev.js in the directory.

**Comment by mertemin** [comment]
I cloned the repo via `$ git clone -b v7.1.4 --single-branch https://github.com/uber/deck.gl.git`. Then `cd` into `deck.gl` folder and ran `yarn bootstrap`. I got the following error message: `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'bootstrap'`. Any ideas?

**Comment by bclinkinbeard** [comment]
I think you want `yarn run bootstrap|prepublishOnly`

**Comment by mertemin** [comment]
@bclinkinbeard Tried running `yarn run bootstrap`. Got a similar error: `00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run`.

**Comment by bclinkinbeard** [comment]
Weird. Running the latest version of yarn?

**Comment by mertemin** [comment]
> Weird. Running the latest version of yarn?

Apparently I wasn't on the latest version. I reinstalled yarn, followed @Pessimistress's instructions and everything worked as expected. Two files are generated `dist.min.js` and `dist/dist.dev.js`.

> You can clone the repo and run
> 
> ```shell
> yarn bootstrap
> cd modules/main
> yarn prepublishOnly
> ```
> 
> This will generate dist.min.js and dist.dev.js in the directory.
