### ISSUE TITLE
SceneGraphLayer: Constant transforms work, callbacks do not

### ISSUE THREAD

**Issue by donmccurdy** [uber/deck.gl#3249]
#### Description

When supplying a constant `getOrientation` like `[0, 0, 90]`, I see the correct result. Changing this to `() => [0, 0, 90]`, nothing appears on the map. Similar effect with `getScale`.

```js
const layer = new ScenegraphLayer({
  id: 'my-scene',
  data: this._features,
  getPosition: (d) => d.geometry.coordinates,
  getOrientation: () => [0, 0, 90],
  getScale: [1, 1, 1],
  scenegraph: 'assets/models/willow.glb'
});
```

#### Environment (please complete the following information):
 - Framework Version:
   - @loaders.gl/core@1.1.2
   - @deck.gl/mesh-layers@7.1.4
   - @luma.gl/addons@7.1.1
 - Browser Version: Chrome 75.0.3770.90
 - OS: macOS 10.14.5

[willow.glb.zip](https://github.com/uber/deck.gl/files/3303519/willow.glb.zip)

**Comment by georgios-uber** [comment]
Investigating...

**Comment by georgios-uber** [comment]
@donmccurdy I tried reproducing using the latest deck master. I cannot reproduce the issue. I tried: 
```
    getOrientation: () => { console.log('getOrientation'); return [0, 0, 90]; },
    getScale: () => { console.log('getScale'); return [1, 1, 1]; },
```
and I am able to see the logs for both methods for each object correctly.

Can you share more about what version of deck core you are using?
Are you providing the initial value and change it later? If so you might need to use [updateTriggers](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer)

**Comment by donmccurdy** [comment]
Oops sorry, user error. I installed `@deck.gl/mesh-layer` but didn't update my other `@deck.gl/*` dependencies from 7.0.2. The issue goes away if I update them all.

**Comment by donmccurdy** [comment]
In related news, the NYC Tree Census has never looked better. 😄

![C1A563CC-27CC-4CAB-AF5F-FE8CF475D845-90180-0000FC36B7B2E845](https://user-images.githubusercontent.com/1848368/59808564-a9f84e80-92b1-11e9-8e49-0a0aa78e934b.gif)

**Comment by ibgreen** [comment]
@donmccurdy very nice, thanks for sharing a gif. Perf looks pretty good!
