### ISSUE TITLE
Function passed as child of DeckGL react component never called

### ISSUE THREAD

**Issue by keller-mark** [uber/deck.gl#3259]
#### Description
In upgrading from 6.4.10 to 7.1.4, the ability to pass functions as children of the react DeckGL component broke (maybe somewhere around [this](https://github.com/uber/deck.gl/commit/3f47a957e4634cfcec992746dffdc64f2dba670b#diff-a60110b98ff9d7770dc5c0eb84db3682) commit). The function(s) are never called. 

In the debugger it seems that some `if` conditions do not pass and so the code never goes down the path that would cause it to call the functions that were passed as children.

#### Repro Steps
https://codesandbox.io/s/optimistic-boyd-xr46e
- Check in the CodeSandbox console that the `params` object was logged when the version is 6.4.10.
- Change the deck.gl version from `6.4.10` to `7.1.4` (using the deck.gl dependency dropdown menu in the left column).
- Check in the CodeSandbox console, the `params` object is no longer logged since the `go` function is never called.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.1.4
 - Browser Version: Chrome 74.0
 - OS: Mac OS X 10.11

#### Logs
No errors in the console

**Comment by Pessimistress** [comment]
@keller-mark Thanks for reporting. This is indeed a bug.

While we address this, you can work around it by giving your view an id:

`new OrthographicView({id: 'ortho'})`

**Comment by keller-mark** [comment]
Great, thank you!
