### ISSUE TITLE
Where to set devicePixelRatio?

### ISSUE THREAD

**Issue by dev-chr** [uber/deck.gl#3266]
I am trying to resolve the issue of the ScatterPlot Layer appearing pixelated on lower resolution screens. Using React, how do I increase the devicePixelRatio of rendered layer?

I've searched the source code and the docs, it doesn't seem clear where to actually set this.

Running version: 7.0.10

**Comment by 1chandu** [comment]
Check `useDevicePixels` prop on `Deck` class : https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md

By setting this flag to true (which is the default value) deck.gl will use full resolution of the your device. Check if this flag is explicitly set to false. If not, they you are already using devices full resolution.

**Comment by dev-chr** [comment]
I should have mentioned in my original post that I tried that. In a different issue, someone mentioned that you can increase the value of devicePixelRatio. Doing that in a in the config of a layer itself crashes the app for modifying a read only value. 

I’ll dig up the comment and post it here. They did say it is one way to fix the pixelation of the ScatterplotLayer.

**Comment by dev-chr** [comment]
[Here](https://github.com/uber/deck.gl/issues/557#issuecomment-292277367) is the mention of increasing "devicePixelRatio" @1chandu

**Comment by 1chandu** [comment]
Can you share your system details and native resolution where you see this problem, and some images to see how bad it is?

**Comment by dev-chr** [comment]
![Screen Shot 2019-06-26 at 3 57 48 PM](https://user-images.githubusercontent.com/10053700/60210622-4929c280-982b-11e9-913e-d18c937ef391.png)

I am on an iMac (Retina 5K, 27-inch, 2017)
GPU: Radeon Pro 575 4 GB

The screenshot is from the second monitor attached via USB-C to DVI converter. The second monitor is a Dell U2412M, 1920×1200, 16:10 aspect ratio, PPI of 94.34.

Browser is Chrome 75.0.3770.100

Hope this helps, @1chandu. Much appreciated!

**Comment by ibgreen** [comment]
As possible related bit of information: there has been a known limitation in MacOS where antialiasing is not applied on external monitors. And I can confirm that I have usually seen pixelated rendering on external monitors.

I did a quick search for recent information on this topic to see if anything has changed, but mainly found it mentioned in this rather old article: https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists

I am not sure how to work around this, @tsherif might know more.

**Comment by 1chandu** [comment]
One option we were discussing was to allow custom `devicePixelRatio` and down sampling might help. Long term solution would be add a new `effect` to perform anti-aliasing.

**Comment by dev-chr** [comment]
Thank you to all of you who stepped in and participated in this conversation! And thanks for putting the upcoming "plumbing" on the "to-do" list!

**Comment by dev-chr** [comment]
@1chandu Where can I find docs on how to implement setting a devicePixelRatio regardless of screen resolution?

**Comment by 1chandu** [comment]
@dev-chr , doc: https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#usedevicepixels-booleannumber-optional

These changes are going to be part of 7.3.0 release, if you want you can try it out using `v7.3.0-beta.1` or later version.
