### ISSUE TITLE
Deck.gl Showcase: Election Simulation

### ISSUE THREAD

**Issue by flowsipher** [uber/deck.gl#3277]
Hey all,

Really appreciate your work on this library and the help I've gotten this far with some of the roadblocks I ran into. Finally finished the project I was working on using deck.gl, and was wondering if there'd be any interest in showcasing it. Don't think anyone's visualized an election using simulated voter drives to their polling location and deck.gl's trip layer before.

http://mcvs.thesunstirade.com

**Comment by Pessimistress** [comment]
@flowsipher Thanks for sharing this cool project! Can you give us a blob of attribution/description to feature on https://deck.gl/#/showcases/overview?

**Comment by flowsipher** [comment]
@Pessimistress So sorry about the delay! Can't tell you how much I appreciate you all being willing to showcase. 

Based on the current blob framework it'd be:

By: Andrew Pulcipher, with the link being to my Twitter: https://twitter.com/andrewpulcipher

Description: An interactive visualization of the 2016 election that uses polling place operations research to simulate election day lines and voter walkoffs in real time.
