### ISSUE TITLE
Shared GL context between mapbox and deck.gl broken for @deck.gl/react 7.1.6

### ISSUE THREAD

**Issue by mayteio** [uber/deck.gl#3280]
#### Description
The docs say that you can share a GL context between deck.gl and react-map-gl. Whilst the API is there, it appears to be broken for the React component. I get a white flickering any time you try to move the map.

#### Repro Steps
[Minimal codepen reproducing this](https://codesandbox.io/s/peaceful-swirles-jwbsj?fontsize=14)

note: I have created the same setup with a class based component and the problem persists.

#### Environment (please complete the following information):
 - Framework Version: deck.gl latest (7.1.6)
 - Browser Version: Chrome latest 74
 - OS: MacOS latest (10.14.5)

**Comment by Pessimistress** [comment]
@mayteio This feature is specifically designed to insert deck layers into mapbox. For context sharing to work, you have to add a `MapboxLayer` to the mapbox layer stack, even if it's a dummy layer:

```js
  const deckRef = useRef();

  return (
    <DeckGL
      ref={deckRef}
      ...
    >
      {gl && (
        <StaticMap
          ...
          onLoad={e => {
            e.target.addLayer(
              new MapboxLayer({ id: "non-exist-layer", deck: deckRef.current.deck })
            );
          }}
        >
          {children}
        </StaticMap>
      )}
    </DeckGL>
  );
```

This seems counter-intuitive but it's unfortunately how the current API works -- Deck would not know that the context is being shared unless mapbox tells it so. The flashing you are seeing is because Deck thinks it's the only one drawing into the context, therefore clearing the canvas every time the viewport changes.

**Comment by mayteio** [comment]
I see! Thanks for the inside info. It might be worth adding that gotcha to the documentation, as I've seen a couple of other issues mentioned the flashing. Thanks @Pessimistress! 🙏

**Comment by JulesBlm** [comment]
Hi, when I try to add a new layer to the Mapbox layer stack but below other labels this way. Unfortunately it still renders on top of all the others layers. See the (minimal) code below, a full version can be found [in this repo](https://github.com/JulesBlm/GeologieVanZuidLimburg). I really don't know why this doens't work. Any help is appreciated.

`
React, { useState, useCallback, useRef } from 'react';
import ReactMapGL, {NavigationControl} from 'react-map-gl';
import DeckGL from '@deck.gl/react';
import { GeoJsonLayer } from  '@deck.gl/layers';
import { MapboxLayer } from "@deck.gl/mapbox";
import { MapController } from '@deck.gl/core';

import geologicalmap from './JSONs/geologielimburg.geojson';

export default function App() {
  const deckRef = useRef(null);
 ...
  const onWebGLInitialized = (gl) => {
    setGlState({gl});
  }

  const renderLayers = () => {
    return [
        new GeoJsonLayer({
          id: 'geologicalmap',
          data: geologicalmap,
          opacity: 0.4,
          filled: true,
          getFillColor: 'hotpink',
          getLineColor: [255, 255, 255, 59],
        })
      ];
  }  

  return (
    <DeckGL
      width={"70%"}
      ref={deckRef}
      layers={renderLayers()}
      viewState={myViewState}
      onViewStateChange={onViewStateChange}
      controller={{type: MapController, dragRotate: false}}
      onWebGLInitialized={onWebGLInitialized}
    >
      {glState && (
      <ReactMapGL
        ...
       **onLoad={e => {
          const { target: map } = e;
          map.addLayer(
            new MapboxLayer({ id: "geologicalmap", deck: deckRef.current.deck }), 'waterway-label'
          );
        }}**
    />
    )}
    </DeckGL>
  )
}
`

**Comment by JulesBlm** [comment]
Nevermind, everything's working now. I just forgot to include the 'gl' prop in the <ReactMapGl> component like this 'gl={glState}' 😅.
