### ISSUE TITLE
ScenegraphLayer: Accept` GLTFLoader` output

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#3282]
Related luma.gl discussion https://github.com/uber/luma.gl/issues/1150. 

#### Target Use case

- Ensures that an app can load data (using loaders.gl) before passing it to the scenegraph layer.
- The `GLTFLoader` can be called directly by the application, however the currently used `GLTFScenegraphLoader` can not (since the app normally does not have access to the gl context).

#### Proposed feature

- `ScenegraphLayer` will know internally how to instantiate a `scenegraph` from the data structure returned by the `GLTFLoader` from `@loaders.gl/gltf`. 
- It will use what is essentially the same undocumented luma.gl add-on APIs that are called by the `GLTFScenegraphLoader`.
- The undocumented support for accepting `GLTFScenegraphLoader` output could be deprecated (or just removed as it is likely not used).

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@tsherif @georgios-uber

**Comment by tsherif** [comment]
Should this be considered a replacement for luma.gl's `GLTFScenegraphLoader`? It could make sense to have the underlying APIs you mention live in luma (and be exposed), but the "build a scene graph" logic could live in deck.

**Comment by ibgreen** [comment]
> Should this be considered a replacement for luma.gl's `GLTFScenegraphLoader`?

Yes, at least from the deck.gl. The `GLTFScenegraphLoader` called the `GLTFLoader` internally and did some extra processing, this proposal moves that extra processing out of the loader and into the layer. 

Most importantly, this allows glTF files to be loaded at any time in application code, without access to deck.gl internals like the WebGL context.

> It could make sense to have the underlying APIs you mention live in luma (and be exposed), but the "build a scene graph" logic could live in deck.

Yes let's see where our separate discussion on luma.gl glTF API lands.

The scenegraph creating code in this PR could certainly be moved back to luma.gl, and since that code is internal to the layer, that can be done in separate PRs without breaking anything.

For now the attached PR would unblock the 3D tiles effort.
