### ISSUE TITLE
Minor layer docs spell errors

### ISSUE THREAD

**Issue by manishmz** [uber/deck.gl#3285]
#### Description
Fix spell error in layer documents

Files:
- layer.md
- column_layer.md
- cpu_grid_layer.md
- grid_cell_layer.md
- solid_polygon_layer.md
- trips_layer.md

**Comment by 1chandu** [comment]
Is this same as #3283 ? Also can you provide details, which files and line numbers or push a PR.

**Comment by manishmz** [comment]
Yes, I mistakenly added this
