### ISSUE TITLE
Loader until map fully rendered

### ISSUE THREAD

**Issue by Lowhearth** [uber/deck.gl#3293]
Hello,

While loading multiple IconLayers with huge amounts of data and big textures, at initialization, I can clearly see how the layers are being rendering in order, sometimes taking around 3 to 4 seconds to initialize and render all the layers.

Is there any way to capture an hypothetical event "On layers rendered" so I can hide the canvas through a loader and only display the map when fully initialized? 
I know about on deckGL loaded but this will fire as 

Thanks

**Comment by ibgreen** [comment]
@lowhearth - How are you loading the data for these layers? Are you just setting `data` to a URL?

**Comment by Lowhearth** [comment]
Data, iconsAtlas and iconMappings are prefetched before mounting DeckGL.

**Comment by ibgreen** [comment]
If all the data is pre-fetched, then I can't see what could be causing the issue you see.

True, the deck.gl layers will need to prepare GPU attributes for big data arrays, but nothing will render until that is done for all the layers you supply initially.

The gradual rendering you describe, should only happen if you start rendering deck.gl when your first data fetch completes. That would be under the control of your application. 

Apologies if I make assumptions, but are you already using some mechanism like `Promise.all` to make sure all your data is pre-fetched before mounting deck.gl?

**Comment by Lowhearth** [comment]
Didn't know that the deck component won't render any layers until all the attributes for the initially provided layers are calculated. That removes the necessity of such an hypothetical event for handling gradual rendering.

I'm using customs shaders with multiple texture bindings so I'll assume that's what's causing the problem.

Thanks for your fast response

**Comment by ibgreen** [comment]
> I'm using custom shaders with multiple texture bindings so I'll assume that's what's causing the problem.

if you are creating your textures using URLs (e.g. new `luma.Texture2D(gl, data: 'url')` instead of pre-loading the images before creating the textures, each layer (actually the underlying luma.gl model) will not render until all the texture uniforms have loaded.

This could potentially explain why your layers render at different times.

**Comment by Lowhearth** [comment]
You nailed it, I'm loading the textures with webpack's url-loader.
Preloading the images solved the problem

Thanks for your time
