### ISSUE TITLE
Minimap controller event propagation

### ISSUE THREAD

**Issue by serdaroquai** [uber/deck.gl#3294]
Hi, thank you for this great project,

In my use case I  have two views, a 'main' one that spans entire window and a 'mini' one on top of the main one. Both manage their own view states.

```
const views = [
        new MapView({ 
            id: "main",
            viewState,
            controller: true,
        }),
        new MapView({
            id: "mini",
            x: "68%", y: "2%", width: "30%",height: "30%",
            clear: true, 
            viewState: miniViewState,
            controller: true
        })
    ];
```
Since both views overlap, problem is controller of main view picks up interaction events from controller of mini. Therefore I can not move around mini view without modifying main view

I tried two approaches so far, first one is by supplying a custom onViewStateChange function to Deck and using the passed in interactionState parameter. It works mostly, however I can not catch mouse wheel zooms (interactionState.isZooming is always undefined) with this approach.

Second approach is I provide a custom controller that extends MapController for the mini view in order to stop propagation of mouse events. Problem is by the time mini view receives the mouse event, main views controller has already processed it.

Any pointers, tips, helps etc is much appreciated, thank you,
(using deck 7.0.5 with react 16.8.6)

**Comment by Pessimistress** [comment]
Try 7.1.10

**Comment by serdaroquai** [comment]
Unfortunately 7.1.10 did not solve the issue. I have two views one overlapping the other and would like to control two view states independently. So when I am hovering above the topmost view  I expect the controller to modify the viewstate belonging to that view. 

After the upgrade, regardless of which view I try to pan,  function onViewStateChange() only logs viewstate updates with the id "main", and is not called for view "minimap" even though minimap is on top. 

Only time onViewStateChange() receives an info with viewId equals "minimap" is at the end of panning when  `interactionState: {isDragging: false}` 

Here is the code I use:

```
    const views = [
        new MapView({ 
            id: "main",
            viewState: viewState,
            controller: true,
        }),
        new MapView({
            id: "minimap",
            x: "68%", y: "2%", width: "30%",height: "30%",
            clear: true, 
            viewState: miniViewState,
            controller: true
        })
    ];

    function onViewStateChange(info) {
        console.log(info);
        const {viewId, interactionState, viewState, oldViewState} = info;
        if ("main" === viewId) {
            setViewState({...viewState, id:"main"});
        } else if ("minimap" === viewId) {
            setMinimapViewState({...viewState, id:"minimap"}); 
        }
    }
```
```
            <DeckGL
                onViewStateChange={onViewStateChange}
                views={views}
                layers={layers}
            >
                <View id="main">
                    <StaticMap
                        reuseMaps
                        mapStyle="mapbox://styles/mapbox/dark-v9"
                        preventStyleDiffing={true}
                        mapboxApiAccessToken={token}
                    />
                </View>
                <View id="minimap">
                    <div style={{ backgroundColor: "black", width: "100%", height: "100%", opacity: 0.5 }} />
                </View>
            </DeckGL>`
```

**Comment by Pessimistress** [comment]
A quick test using 7.1.10: https://codepen.io/Pessimistress/pen/gNNvLd

**Comment by serdaroquai** [comment]
Thank you very much for your time and effort,

I just figured the reason my code does not work is because I use a variable to dynamically add the minimap view based on isVisible variable as such:

```javascript
    const views = [
        new MapView({ 
            id: "main",
            viewState: viewState,
            controller: true,
        }),
        isVisible && new MapView({
            id: "minimap",
            x: "68%", y: "2%", width: "30%",height: "30%",
            clear: true, 
            viewState: miniViewState,
            controller: true
        })
    ];
```

Last but not least, for reference here is a quick React example, for managing two different viewstates: [https://repl.it/repls/AmusingHandmadeWebsites](https://repl.it/repls/AmusingHandmadeWebsites)
