### ISSUE TITLE
Tooltips when using deck.gl in a Routes framework

### ISSUE THREAD

**Issue by simonrp84** [uber/deck.gl#3297]
Hello,
I'm using deck.gl react together with the `routes` library (similar to what's done [here](https://serverless-stack.com/chapters/handle-routes-with-react-router.html)).
I have a line like this in my `Routes.js` file:
```<AppliedRoute path="/my_map_src/" exact component={MyMap} props={childProps} />```

And in my MyMap.js file I have this (irrelevant sections removed for brevity):
```
import DeckGL, {GeoJsonLayer} from 'deck.gl';
...
export default class MyMapApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      hoveredObject: null
    };
    this._onHover = this._onHover.bind(this);
    this._renderTooltip = this._renderTooltip.bind(this);
  }

  _onHover({x, y, object}) {
    this.setState({x, y, object: object});
  }
...
  _renderLayers() {
     return [
        new GeoJsonLayer({
            id: 'getjson_data',
            data: my_data,
            pointRadiusMinPixels: 3,
            pointRadiusMaxPixels: 15,
            getFillColor: [255, 0, 255],
            opacity: 0.95,
            getRadius: 30,
            pickable: true,
            polygonOffset: 5000,
            onHover: this._onHover
        })]
     }
 _renderTooltip()
  {
    const {x, y, object} = this.state;
    console.log("Tooltip:",object);
    if (object)
    {
            return (
            object && (
            <div className="tooltip" style={{top: y, left: x}}>
            <div><b>Interesting thing</b></div>
                <div>
                    <div>Seen at: {object.properties.seen_at}Z</div>
                    <div>Type: {object.properties.type}</div>
                </div>
            </div>
            )
            );
        }
    }    

  render() {
    const {mapStyle = my_style} = this.props;

    return (
      <div className="MyMap" style={{ position: 'absolute', left: 0, top: "7%", width:"100%", height:"93%" }}>
        <DeckGL layers={this._renderLayers()} controller={true}>
            <StaticMap
                reuseMaps
                mapStyle={mapStyle}
                preventStyleDiffing={true}
                mapboxApiAccessToken={config.mapbox.TOKEN}
            />

            {this._renderTooltip}
        </DeckGL>
        </div>
    );
  }
}
```

I previously had my Deck.gl map displaying as a single page app, and that worked fine. But now the tooltips don't show up. The _rendertooltip() function is being called (I can see the console log output is correct) but the tooltip just isn't displayed.
What have I done wrong here? Does the Deck.GL tooltip need to be called or set up differently when using Routes? If so, what's the best way to do this?

Thanks!

**Comment by Pessimistress** [comment]
I don't see any problem in your code. Maybe it's a CSS issue? Can you find the dom element rendered by `_renderTooltip` using react dev tools?

**Comment by simonrp84** [comment]
In the end I came up with a custom solution using a separately-defined `<div>` element and playing with the `.style.display = "block"` and  `.style.display = "none"` props.
Not sure why my code above didn't work.
