### ISSUE TITLE
Is it possible for TextLayer to support text wrapping?

### ISSUE THREAD

**Issue by ForeverArt** [uber/deck.gl#3299]
Hello,
I am using deck.gl to show buildings’ name on a GeoJsonLayer.
However, those names are too long to have a good visual effects or contain description that should be displayed on the second line.

So, i am wondering whether TextLayer supports text wrapping？

The following screenshot is made by mapbox studio.
I want to known if there is a way to achieve the same effect by using `TextLayer` in deck.gl.

Thanks!

<img width="857" alt="WX20190628-141306@2x" src="https://user-images.githubusercontent.com/23061097/60321270-e5c89d80-99ae-11e9-929c-6a23d4c97dbf.png">

**Comment by Pessimistress** [comment]
TextLayer does not support wrapping at the moment. Per discussion with @xintongxia, we can split this feature into two parts:

- [ ] Support line breaks in text strings - we should be able to do this in a patch
- [ ] Support auto-wrapping - this will require an API audit. We can add this to the next milestone.
