### ISSUE TITLE
GeoJSON linestrings throw malformed error if coordinates empty.

### ISSUE THREAD

**Issue by bfreed** [uber/deck.gl#3301]
#### Description
An empty geometry GeoJSON feature throws an error and prevents anything from showing in deck.gl, rather than being silently excluded as in mapbox.gl, QGIS, etc.

This is a weird thing to report as a bug, I know. Why have a linestring with no coordinates? In this case, offsetting lines on the inside of a corner. In PostGIS, if offsetting to the inside of a corner by a distance larger than the distance from both endpoints to the corner, results in an empty geometry.

The “bug” (in my opinion) is really a difference in how deck.gl handles empty geometry compared to how it’s handled elsewhere.
Starting with PostGIS: ST_IsValid() returns true - it considers the empty linestring to be valid geometry, so we can’t just add “WHERE ST_IsValid(geom) IS TRUE” to the server queries.
Next, in a desktop environment, QGIS happily loads the offending view, just silently ignores the empty geometries.
Finally, in mapbox.gl: after wrapping with ST_AsGeoJson() and returning from PostGIS, loading into mapbox.gl causes no problem at all - again, it seems to silently ignore the empty geometry.

So my first experience with deck.gl was rough - calling the same API function as with Mapbox, getting the same GeoJSON, but the map is blank, with a dev console error about “malformed linestring coordinates.”
I tried iterating over the 230 features in the feature collection, wrapping each in a try/catch before updating the deck layers, but wherever the error is thrown, it seemed to go by the try/catch there.
Eventually, by loading slices of the array a bit at a time, narrowed it down to 4 LineStrings with empty geometry.

Personally, I don’t love things silently missing from my maps - we’ve had these edge cases for a few years without realizing it. Maybe throwing an error is better.
OTOH, the workaround is painful - for every layer I grab from the database, I have to explicitly check for empty geometry. And since it’s an edge case, not all projects have these inside corner offsets - so forgetting the explicit check could appear fine until some project has one and suddenly the whole map fails to work.

The big issue IMO is the “gotcha” factor when migrating in to deck.gl.

Either of these would be an improvement:
1. Silently ignore empty geometries, like Mapbox
OR 2. Add a warning to the Deck.GL documentation about empty geometries preventing anything else from loading.

#### Environment
I’m using deck.gl in a pure JS / non-React environment.
Just did NPM install today, so whatever the latest version is.
I wouldn’t expect it to be a version-specific thing, but I’ll check the specific version when I get back to desktop, if anyone thinks it’s relevant.

**Comment by bfreed** [comment]
Sorry about the open/close/reopen, the mobile keyboard submitted when I thought it would send me to the details, and posted an empty issue.

**Comment by Pessimistress** [comment]
@bfreed Thanks for reporting. This error is a result of https://github.com/uber/deck.gl/blob/master/modules/layers/src/geojson-layer/geojson.js#L203, which was put in place after too many users provide invalid GeoJSON Polygons (as a single loop instead of array of loops). I agree that empty coordinates should not result in a hard failure.

**Comment by Pessimistress** [comment]
This is patched in 7.1.8 - we're now logging a console warning instead of throwing an error.
