### ISSUE TITLE
LIGHT_SETTINGS  documentation

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3304]
I find some example.I want to set light parameter
`const LIGHT_SETTINGS = {`
  `lightsPosition: [-0.144528, 49.739968, 8000, -3.807751, 54.104682, 8000],`
  `ambientRatio: 0.4,`
  `diffuseRatio: 0.6,`
  `specularRatio: 0.2,`
  `lightsStrength: [0.8, 0.0, 0.8, 0.0],`
 ` numberOfLights: 2`
`};`

`const colorRange = [`
  `[1, 152, 189],`
  `[73, 227, 206],`
  `[216, 254, 181],`
  `[254, 237, 177],`
  `[254, 173, 84],`
 ` [209, 55, 78]`
`];

`const elevationScale = {min: 1, max: 50};`

A question. I want to know where is the documentation for light setting ,elevationScale.
and the explain for parameters.but in [deck.gl documentation](https://deck.gl/#/documentation/overview/introduction) . I can't find it .

**Comment by mayteio** [comment]
Are you after these? 

- [Lighting Effects](https://deck.gl/#/documentation/deckgl-api-reference/effects/lighting-effect)
- [Elevation Scale](https://deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer?section=linewidthminpixels-number-optional-)

**Comment by HeiYanjing** [comment]
> Are you after these?
> 
> * [Lighting Effects](https://deck.gl/#/documentation/deckgl-api-reference/effects/lighting-effect)
> * [Elevation Scale](https://deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer?section=linewidthminpixels-number-optional-)

Thank you for your reply.
I want to know what the parameter ambientRatio,diffuseRatio,specularRatio... means. I want to set light.
the documentation of your link don't have it.

**Comment by Pessimistress** [comment]
@HeiYanjing The `lightSettings` prop was an experimental feature on older versions of deck.gl. It has been removed in v7.0.

You can find the latest API in [guide to using lighting effect](https://deck.gl/#/documentation/developer-guide/using-lighting)

**Comment by HeiYanjing** [comment]
> @HeiYanjing The `lightSettings` prop was an experimental feature on older versions of deck.gl. It has been removed in v7.0.
> 
> You can find the latest API in [guide to using lighting effect](https://deck.gl/#/documentation/developer-guide/using-lighting)

thank you for your reply . 
cause the version problem.  my version is  6.3.2
