### ISSUE TITLE
Render layers into external framebuffer (or texture)

### ISSUE THREAD

**Issue by Chumhoo** [uber/deck.gl#3313]
Hello, 

I'm trying to draw everything rendered by deck.gl layers into a **framebuffer (or a texture)** externally generated by WebGL, and then use the texture in other WebGL applications. 
I noticed the "external framebuffer" is a proposed function mentioned in [RFC - View Classes for deck.gl](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.2/view-class-rfc.md), which says:

> Ideas:
> - color - Background color
> - onClear({gl, view, viewport, ...}) - Customize what is cleared (color, depth, stencil etc)
> - framebuffer - makes this view render into a framebuffer
> - parameters: {blendMode, ...}
>
> We could address use cases beyond simply rendering multiple views:
> - Multiple render passes over the same viewport - avoid clearing background
> - Rendering to offscreen framebuffers

Has this function been implemented yet? If so, could you please provide an example which performs similar rendering process? 

Thanks a lot!

**Comment by Pessimistress** [comment]
You're getting into experimental and undocumented territory, but it's possible to avoid clearing the canvas by supplying your own `_customRender` prop to `Deck`:

```js
const deck = new Deck({
  ...
  _customRender: redrawReason => deck._drawLayers(redrawReason, {clearCanvas: false});
});
```

It's not currently supported, but we could add an option alongside `clearCanvas` for you to specify the target framebuffer.

cc @jianhuang01

**Comment by Chumhoo** [comment]
Thank you for replying! Actually I'm only focusing on rendering to a framebuffer, instead of avoiding clearing the canvas.
But I did find a hacky way to do this! 

If a `framebuffer` is already created with a texture binded to it, and deckgl layers are all constructed, then it's simply

```javascript
var canvas = document.getElementById("deckgl-overlay");
var gl = canvas.getContext("webgl");
...
// render to texture by binding the framebuffer
gl.bindFramebuffer(gl.FRAMEBUFFER, framebuffer);

gl.clearColor(0, 0, 0, 1);  
gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);

if (deckgl.layerManager) // Make sure the context is loaded
{
  deckgl._drawLayers();
  deckgl.redraw();
}
      
// Draw other stuff...
```

Note that `gl` must share the same webgl context with deckgl to make this work.

**Comment by Pessimistress** [comment]
You shouldn't have to call `deckgl._drawLayers();` in this case; it's called inside `redraw()`.

**Comment by Chumhoo** [comment]
Totally agree. But it turns out that there will be some display issues without calling `deckgl._drawLayers();` I'll just keep both for now.
Thanks!

**Comment by Pessimistress** [comment]
A robust way to implement this could be using the `onBeforeRender` prop:

```js
new Deck({
  ...
  onBeforeRender: ({gl}) => {
    // bind your frame buffer here
  }
})
```

**Comment by Chumhoo** [comment]
Yes! This works pretty well. Thank you!

**Comment by damix911** [comment]
It does not seem to work for me. I see a couple of calls to `getDefaultFramebuffer` in `deck-renderer.js`. Aren't they going to override whatever I set in `onBeforeRender`?

On a side note, have a look [at DeckGL's layer pass](https://github.com/uber/deck.gl/blob/master/modules/core/src/passes/layers-pass.js#L9) and [LumaGL's state tracker](https://github.com/uber/luma.gl/blob/master/modules/webgl-state-tracker/src/state-tracking/with-parameters.js#L19). Note the difference in casing (`framebuffer` vs `frameBuffer`). Also note the comment right above that line (`// frameBuffer not supported: use framebuffer API // TODO - is this still true?`).

**Comment by Pessimistress** [comment]
@damix911 can you open a new issue? We do not monitor closed issues.
