### ISSUE TITLE
transition interpolator initial transitions zooms out

### ISSUE THREAD

**Issue by antonydellavecchia** [uber/deck.gl#3314]
When I initialize the map and do a first flyTo or linear transitions the map zooms all the way out
instead of zooming to the bounds, but works every time after, or if i do a zoom with my mouse first

      const bounds = [10.747981, 51.818442, 14.758593, 54.684764]
      const viewport = new WebMercatorViewport(viewState);
      const newViewport = viewport.fitBounds(bounds);
      const newViewState = {
        ...newViewport,
        transitionDuration: 100,
        transitionInterpolator: new FlyToInterpolator()
      }      
      
      setViewState(newViewState)

 - Framework Version: deck.gl 7.0.9
- doesn't work on firefox or chrome

**Comment by 1chandu** [comment]
What is the initial `zoom` value? Can you log the `zoom` values in `viewState` and `newViewState`?

**Comment by antonydellavecchia** [comment]
error because i initialised the initial view state as new WebMeractor()
