### ISSUE TITLE
H3HexagonLayer cannot load H3

### ISSUE THREAD

**Issue by rodmaz** [uber/deck.gl#3315]
## Description
When loading H3HexagonLayer, library `h3-js` is not found and an error `Cannot read property 'h3GetResolution' of undefined` is logged.
Using `@deck.gl/geo-layers/dist/dist.dev.js` for debugging, I can see that it cannot import the `h3-js` library. All other libraries, such as `math.gl` are imported successfully. 
`h3-js` is correctly installed as a dependency.

<img width="1280" alt="Screen Shot 2019-07-06 at 20 09 08" src="https://user-images.githubusercontent.com/55300/60762017-3d5cae00-a02c-11e9-8739-2d9957082450.png">

#### Environment:
 - Framework Version: deck.gl 7.1.7
 - Browser Version: Chrome 75.0.3770.100
 - OS: MacOS 10.14.5

#### Logs
```
deck: error while initializing H3HexagonLayer({id: 'h3-layer'})
 TypeError: Cannot read property 'h3GetResolution' of undefined
    at H3HexagonLayer.updateState (http://localhost:8080/@deck.gl/geo-layers/dist/dist.dev.js:11991:80)
    at H3HexagonLayer.value (http://localhost:8080/@deck.gl/core/dist.min.js:1:337224)
```

**Comment by Pessimistress** [comment]
@rodmaz Are you using the pre-bundled version? The bundle does not include h3-js because of its size. You need to include the h3-js bundle separately. See https://github.com/uber/deck.gl/blob/7.1-release/docs/layers/h3-hexagon-layer.md#installation

**Comment by rodmaz** [comment]
@Pessimistress I have installed the following packages using NPM:

```
    "@deck.gl/core": "^7.0.0",
    "@deck.gl/geo-layers": "^7.0.0",
    "@deck.gl/layers": "^7.0.0",
    "@deck.gl/mapbox": "^7.0.0",
```

I downgraded to `7.0.0` but the problem persists.

Yes, `h3-js@3.4.3` is installed as a dependency by NPM, just like `math.gl` was also installed.
`math.gl` is found correctly.

**Comment by Pessimistress** [comment]
Based on the installation instructions - you also need the following tag

`<script src="https://unpkg.com/h3-js"></script>`

Or your local copy:

`<script src="/h3-js/dist/h3-js.umd.js"></script>`

**Comment by rodmaz** [comment]
@Pessimistress Thanks for you prompt reply! I retested using my local copy and remote copy as your example. It simply cannot find h3 library.

```
    <script src="/@deck.gl/core/dist.min.js"></script>
    <script src="/@deck.gl/layers/dist.min.js"></script>
    <script src="/@deck.gl/geo-layers/dist.min.js"></script>
    <script src="/@deck.gl/mapbox/dist.min.js"></script>

    <script src="https://unpkg.com/h3-js"></script>
```

Debugger view:

<img width="1896" alt="Screen Shot 2019-07-08 at 20 14 59" src="https://user-images.githubusercontent.com/55300/60848591-96a81700-a1bd-11e9-8b06-b15965b5252a.png">


<img width="1041" alt="Screen Shot 2019-07-08 at 20 05 05" src="https://user-images.githubusercontent.com/55300/60848163-de2da380-a1bb-11e9-8b04-7063e581c7ce.png">

**Comment by Pessimistress** [comment]
h3 must be loaded before deck.gl.

**Comment by rodmaz** [comment]
@Pessimistress Thanks, that was it. Sorry for the stupidity here.
