### ISSUE TITLE
Some question about TileLayer

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3316]
Firstly. I publish a building Layer  by geoserver. And I test it successful by mapbox .
![image](https://user-images.githubusercontent.com/42837853/60808392-c30e6400-a1ba-11e9-828d-ab5bd9fd46ae.png)
 I set different color for buildings ,some code:

			map.on('load', function() {
		          map.addSource('building',{
		              'type':'vector',
		              'scheme':'tms',
		              'tiles':['http://192.168.1.125:8090/geoserver/gwc/service/tms/1.0.0/mysapce%3Achognqing@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf']
		          });
		          map.addLayer({ 
		            'id': '3d-buildings',
		            'source': 'building',
		            'source-layer':'chognqing',
		            'type': 'fill-extrusion',
		            'paint': { 
		                'fill-extrusion-color': [
		                      'interpolate', 
		                     ['linear'],
		                      ['get', 'height'],
		                    0, 'rgb(255,255,191)',
		                      10, 'rgb(253,174,97)',
		                      20, "#aaa",
		                ], 
		                'fill-extrusion-height': ['get', 'height'], 
		                'fill-extrusion-opacity': 0.6
		            } 
		        });
			 });

the most important  tiles url :
`'http://192.168.1.125:8090/geoserver/gwc/service/tms/1.0.0/mysapce%3Achognqing@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf'`

I try it in my project  like [TileLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-layer)
some code:
`import DeckGL, {PolygonLayer, ScatterplotLayer, PointCloudLayer, HexagonLayer,GridLayer,ArcLayer,IconLayer,TextLayer, FlyToInterpolator, PathLayer} from 'deck.gl';`
`import {VectorTile} from '@mapbox/vector-tile';`
`import Protobuf from 'pbf';`
`import {TripsLayer} from '@deck.gl/experimental-layers';`
`import {TileLayer}  from '@deck.gl/geo-layers';`

          new TileLayer({
              opacity: 0.7,
              lineWidthMinPixels: 1,
              getTileData: ({x, y, z}) => {
                const mapSource = `http://192.168.1.125:8090/geoserver/gwc/service/tms/1.0.0/mysapce%3Achognqing@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf`;
                return fetch(mapSource)
                  .then(response => response.arrayBuffer())
                  .then(buffer => {
                    const tile = new VectorTile(new Protobuf(buffer));
                    const features = [];
                    for (const layerName in tile.layers) {
                      const vectorTileLayer = tile.layers[layerName];
                      console.log('---------',vectorTileLayer);
                      for (let i = 0; i < vectorTileLayer.length; i++) {
                        const vectorTileFeature = vectorTileLayer.feature(i);
                        const feature = vectorTileFeature.toGeoJSON(x, y, z);
                        features.push(feature);
                      }
                    }
                    return features;
                  });
              }
          }),

for mapSource, I use the same url . It occur some problem:
![image](https://user-images.githubusercontent.com/42837853/60809392-24373700-a1bd-11e9-9916-3d0ae27850fb.png)
![image](https://user-images.githubusercontent.com/42837853/60809429-3618da00-a1bd-11e9-8545-3c03b6c92736.png)
And some other type problem in console:
`Unimplemented type:4`
`deck.gl :assertion failed`
Are the caused by my url?
![image](https://user-images.githubusercontent.com/42837853/60809605-a58ec980-a1bd-11e9-86f8-7c0be8fd5322.png)

**Comment by Pessimistress** [comment]
`.../{z}/{x}/{y}.pbf`

needs to be

`.../${z}/${x}/${y}.pbf`
