### ISSUE TITLE
 deck.gl - multiple versions detected

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3320]
![image](https://user-images.githubusercontent.com/42837853/60886943-c4f12980-a285-11e9-86ae-f98a71fce960.png)
this problem  ...  it's crazy .
for the new version deck.gl add TileLayer.    I want use  TileLayer(@deck.gl/geo-layers) to add  a published layer.
in my package.json, all the versions about deck.gl:
   ` "@deck.gl/experimental-layers": "^6.3.0",`
    `"deck.gl": "^6.3.2",`
I tried match the right versions,but failed.
after npm install @deck.gl/geo-layers
 `"@deck.gl/geo-layers": "^7.1.7",`
![image](https://user-images.githubusercontent.com/42837853/60887364-c7a04e80-a286-11e9-960a-607c1312ee17.png)
For js code:
`import DeckGL, {PolygonLayer, ScatterplotLayer, PointCloudLayer, HexagonLayer,GridLayer,ArcLayer,`
  `  IconLayer,TextLayer, FlyToInterpolator, PathLayer,COORDINATE_SYSTEM} from 'deck.gl';`
`import {TripsLayer} from '@deck.gl/experimental-layers';`

if I add the code: ` import {TileLayer}  from '@deck.gl/geo-layers';`
there are some warnings :
![image](https://user-images.githubusercontent.com/42837853/60887609-62009200-a287-11e9-97d1-dec1cf64eeff.png)
![image](https://user-images.githubusercontent.com/42837853/60887617-64fb8280-a287-11e9-82d2-e2274ae0652c.png)

So....
How can I resolve it?

**Comment by mayteio** [comment]
I'd delete your `node_modules` folder, clear your `package.json` of anything deck.gl then run `$ yarn add @deck.gl/react @deck.gl/layers @deck/geo-layers`. 

This will upgrade you to the latest version of deck.gl. TripsLayer is no-longer experimental and comes from `@deck.gl/geo-layers`.

I ran into a similar issue upgrading from 6.* to 7.* - the best option was just to clear out my dependencies and `package.json` and start again.

**Comment by HeiYanjing** [comment]
@mayteio 
thank you for your reply . I succeeded in your way.

**Comment by davidcalhoun** [comment]
Unfortunately just ran into this same issue with Yarn 3 (berry), and the working fix was similar:

1. `rm yarn.lock`
2. `yarn cache clean --all` (may not be needed)
3. `yarn`
