### ISSUE TITLE
Access all data in the current viewport

### ISSUE THREAD

**Issue by sam-coxon** [uber/deck.gl#3330]
I am trying to limit the number of displayed data points in the current _viewport_. Is there some way of accessing the data that is currently visible based on that viewport? Not all the data total just the data that you can currently see.

Thanks!

**Comment by 1chandu** [comment]
Short answer is No.  In the graphics pipeline, invisible data is clipped to viewport bounds after all vertex shader processed all vertices. There are some advanced techniques to avoid processing non visible data, like bounding boxes, occlusion query etc, but they are not currently implemented by deck.gl.

A temporary solution can be to use [pickObjects](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=pickobjects), with entire size , then returned object contains the indices of visible data elements.

**Comment by sam-coxon** [comment]
Thanks for the quick response, that function will do just fine!
