### ISSUE TITLE
LayerExtension is not exported from '@deck.gl/core'

### ISSUE THREAD

**Issue by sam-coxon** [uber/deck.gl#3337]
#### Description

 I would like to use the new [DataFilter extension](https://github.com/uber/deck.gl/blob/37b5841ccefc3541b57ac33ae4b21ec0c4700fda/docs/extensions/data-filter-extension.md) (@deck.gl/extensions/data-filter) but the current @deck.gl/core seems to not have been updated to support that and I get the error "LayerExtension is not exported from '@deck.gl/core'"

#### Environment (please complete the following information):
 - Framework Version: @deck.gl 7.1.9

**Comment by Pessimistress** [comment]
@sam-coxon The feature will be included in the upcoming 7.2 release. If you want to try it you can install `deck.gl@^7.2.0-alpha`.

**Comment by sam-coxon** [comment]
Got it, thanks for the quick response, and for adding this extension!
