### ISSUE TITLE
Retrieving bounds and zoom of map

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#3344]
From the [`onViewStateChange`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#onviewstatechange-function) documentation we know that a 

> callback is fired when the user has interacted with the deck.gl canvas, e.g. using mouse, touch or keyboard.

So we can observe / listen for interaction and use the `viewState` data by putting a function inside `onViewStateChange`, for example

```js
const deckgl = new deck.DeckGL({
  mapboxApiAccessToken: x,
  container: mycontainer,
  onViewStateChange: ({viewState}) => {
    console.log( viewState );
  }
});
```

Which gives us something like

```js
{
    "width": 1388.0,
    "height": 400.0,
    "latitude": -2.719598,
    "longitude": -2.164757,
    "zoom": 0.2425895,
    "bearing": 0.0,
    "pitch": 0.0,
    "altitude": 1.5,
    "maxZoom": 20.0,
    "minZoom": 0.0,
    "maxPitch": 60.0,
    "minPitch": 0.0,
    "position": [
        0.0,
        0.0,
        0.0
    ],
    "transitionDuration": 0.0
}
```

### Questions

1. Is this the correct approach for returning and interacting with the map zoom/bearing/pitch? 
2. Is there a way or formula we can use to get the lon/lat bounds of the map, given we know the zoom, centre, pitch, bearing and the width/height of the canvas?

**Comment by Pessimistress** [comment]
Yes, this is the correct callback to use to listen to map state changes.

To intercept and manipulate camera changes, you can do something like:

```js
onViewStateChange: ({viewState}) => {
  return {
    ...viewState,
    zoom: Math.max(viewState.zoom, 3)
  };
}
```

To get the bounds of the map:

```js
import {WebMercatorViewport} from '@deck.gl/core';

onViewStateChange: ({viewState}) => {
  const viewport = new WebMercatorViewport(viewState);

  const nw = viewport.unproject([0, 0]);
  const se = viewport.unproject([viewport.width, viewport.height]);

  // do what you need to do
}
```

**Comment by SymbolixAU** [comment]
Thanks, I'll give it a go!

**Comment by SymbolixAU** [comment]
@Pessimistress The documentation for [`unproject`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/viewport.md#unproject) says 

> Unproject pixel coordinates on screen onto [lng, lat, altitude] on map

However, using `unproject` as per your suggestion, the longitude values are not restricted to (-180, 180)

Reproducible steps, log the state change

```js
onViewStateChange: ({viewState}) => {
  const viewport = new WebMercatorViewport(viewState);
  const nw = viewport.unproject([0, 0]);
  const se = viewport.unproject([viewport.width, viewport.height]);
  console.log("north: ", nw[1], ", south: ", se[1]);
  console.log("east: ", se[0], "west: ", nw[0] );
});
```
and scroll the map east/west

![Screen Shot 2019-09-20 at 11 37 31 am](https://user-images.githubusercontent.com/18344164/65292504-0e6dc700-db9b-11e9-80ac-d300b4ab1b8b.png)


I think another adjustment is required in `unproject` to get the longitude correctly into (-180, 180).

**Comment by SymbolixAU** [comment]
@tgorkin do you think it's worth reopening this?

**Comment by Jamal8548** [comment]
You will want to manage view state in your react app with deck's viewState and onViewStateChange prop. People usually hook this up to a useState hook.
