### ISSUE TITLE
Debounce viewport-change re-renders

### ISSUE THREAD

**Issue by sam-coxon** [uber/deck.gl#3346]
I am trying to implement a layer where the rendered points change based on the current viewport, in essence thresholding the amount of displayed data (based on the viewport).

Because updateState is called on change to the viewport I have the problem of the layer trying to render hundreds of times every time i zoom or pan, and I want it to only re-render once when zoom/pan stops.

I can't add a this.debounce function to the layer class because it throws an "object is not extensible" error, is there somewhere else to add a debounce function, or some other way to select when to re-render when the viewport changes?

**Comment by 1chandu** [comment]
[shouldUpdateState](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=shouldupdatestate) controls when to update the Layer (i.e. call `updateState`). But there is only one flag that is set whenever any parameter of viewport is changed `changeFlags.viewportChanged`, it doesn't distinguish what part of viewport is changed.

Also if you are not re-drawing during the zoom, layer content will be out os sync with the base map.

**Comment by sam-coxon** [comment]
At the moment I'm redrawing on any viewport change. In the case of redrawing during zoom i have the option of checking if the zoom is some non-integer value (i.e. don't redraw when zoom is halfway between to steps), but i don't know of a similar solution for pan.

If the changeFlags aren't helpful in this context is there some way to attach a debounce function to the class?

**Comment by Pessimistress** [comment]
@sam-coxon You can attach a custom function to the layer state:

```js
initializeState() {
  super.initializeState();

  this.setState({
    debouncedUpdate: debounce(() => {
      ...
    })
  });
}

updateState(params) {
  super.initializeState(params);

  this.state.debouncedUpdate();
}
```

**Comment by sam-coxon** [comment]
Unfortunately I also need to update a state object in that debounce function. So attaching the debounce to state will cause the whole function to remount every time i setState (from the debounce function)

**Comment by Pessimistress** [comment]
Calling `setState` from inside the debounced function should be fine. Can you share your code sample if you are seeing otherwise?

**Comment by tgorkin** [comment]
Closing assuming this is resolved, please reopen and comment if not.
