### ISSUE TITLE
Scatterplot layer click event 

### ISSUE THREAD

**Issue by martahj** [uber/deck.gl#3349]
Looks similar to https://github.com/uber/deck.gl/issues/2974, but I couldn't solve it with a similar workaround (see below)

I'm trying to display a scatterplot layer of elements using React DeckGL over ReactMapGL. Clicking on a point should open up a new div over the map with some additional info about the point, which the user is supposed to be able to dismiss by clicking on any part of the map that isn't covered by a point.

After the user clicks on a point, the scatterplot click is correctly fired, and the div opens. Unfortunately, however, the click event is also propagated up to the map, so the map click handler immediately closes the div. 

I tried the following approaches to fixing this:
1. Prevent event propagation. As there doesn't seem to be a way of suppressing event propagation if a layer's click handler is triggered, however, this didn't get off the ground.
2. Allow the map click handler to fire, but do not hide the div if the click target is the scatterplot layer. Unfortunately, however, the event target is just the DeckGL canvas regardless of where on the map I've clicked. I may be missing something but I didn't see a reliable way of identifying  whether a scatterplot layer was called.
3. Add an 'onHover' listener to when the mouse was over a scatterplot item, and inside the map click handler, do not hide the div if the user is hovering. This solved the problem at the cost of a lot of re-renders, except in the case where the div opens to cover the clicked scatterplot item, since the div covers the item, which sets hovering to false.

I've thought about delaying the time until hovering gets set to false, but if possible I'd like to find a solution that doesn't potentially introduce a race condition into this interaction.

I put together a minimal example to illustrate the issue. Unfortunately I couldn't put it in a codepen without publishing my mapbox credentials, but the code is here:

```js
import React, { useState } from 'react';
import ReactMapGL, { Marker } from 'react-map-gl';
import DeckGL, { ScatterplotLayer } from 'deck.gl';

const generateLayer = (onClick, onHover ) => new ScatterplotLayer({
  data: [{ position: [96, 32]}],
  id: 'pins',
  onClick,
  onHover,
  pickable: true,
  opacity: 1,
  stroked: true,
  filled: true,
  radiusScale: 1,
  radiusMinPixels: 30,
  radiusMaxPixels: 30,
  lineWidthMinPixels: 5,
  lineWidthMaxPixels: 5,
  getRadius: 30,
});

export const MyComponent = () => {
  const [showDiv, setShowDiv] = useState(false);
  const [hovering, setHovering] = useState(false);

  const onClick = (e) => {
    if (!hovering) setShowDiv(false);
  }

  const markerClick = (e) => {
    setShowDiv(true);
    return true;
  }

  const markerHover = ({ picked }) => {
    setHovering(picked);
  }

  return (
    <>
      <ReactMapGL
        height={450}
        width={450}
        latitude={32}
        longitude={96}
        zoom={8}
        mapStyle={process.env.MAP_STYLES}
        mapboxApiAccessToken={process.env.MAPBOX_TOKEN}
        onClick={onClick}
      >
      <DeckGL
        height={450}
        width={450}
        latitude={32}
        longitude={96}
        zoom={8}
        layers={[generateLayer(markerClick, markerHover)]}
      />
      <Marker latitude={32} longitude={96}>
      </Marker>
      </ReactMapGL>
      <div style={{ display: showDiv ? 'unset' : 'none', height: '400px', width: '400px', backgroundColor: 'red', position: 'absolute', top: '70px', cursor: 'pointer' }} />
    </>
  )
}
```

I'm running:
deck.gl v6.4
react-map-gl v5.0.3
react v16.8.6

Any thoughts on what the best way to solve this would be?

**Comment by Pessimistress** [comment]
react-map-gl and deck.gl are two separate libraries so unfortunately there is no easy way to stop propagation from one to another.

Instead, you want to listen to `onClick` on the `DeckGL` component. If a layer's `onClick` callback returns a truthy value, the click event will not bubble up to the `onClick` callback of the DeckGL canvas.

https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=onclick-function-optional-

**Comment by martahj** [comment]
Ok, thank you @Pessimistress . One more question - what's the recommended way to listing to the Deckgl `onClick` in a React environment? I can't find any mention of it in [the docs](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=getcursor-function-) and I don't want to do something hacky/discouraged

**Comment by Pessimistress** [comment]
Just search for `onClick` in that doc you linked?

**Comment by martahj** [comment]
Oh I see, the suggestion is that I add `onClick` to layer; I thought it was to listen to `onClick` from the DeckGL canvas component. My mistake.

In my example code, though, I already have an `onClick` attached to the layer, and regardless of whether I return `true` or not (I did in my example because I saw that in the docs), the effect is bubbled up to `ReactMapGL`, and I don't see a way of intercepting it a the DeckGL level to change how it handles clicks from that layer.

Is there something I can do in how I set up that layer or the DeckGL component that would make returning `true` from its onClick handler prevent the click from bubbling up to ReactMapGL?

**Comment by Pessimistress** [comment]
@martahj Instead of assigning your callback to `ReactMapGL`'s `onClick` prop, you need to use `DeckGL`'s `onClick` prop:

```
  <DeckGL
    ...
    onClick={onClickMap}
    layers={[new ScatterplotLayer({..., onClick: onClickLayer})]}
  />
```

**Comment by martahj** [comment]
Hmm I tried that but then the function never gets called if I click the map, even after getting rid of the return statement that prevents the layer click from bubbling up:

```js
export const MyComponent = () => {
  const [showDiv, setShowDiv] = useState(false);
  const [hovering, setHovering] = useState(false);

  const onClick = (a, b) => {
    console.log('map click') // does not log if I click on the map
    if (!hovering) setShowDiv(false);
  }

  const markerClick = (a, b) => {
    setShowDiv(true);
  }

  const markerHover = ({ picked }) => {
    setHovering(picked);
  }

  return (
    <>
      <ReactMapGL
        height={450}
        width={450}
        latitude={32}
        longitude={96}
        zoom={8}
        mapStyle={process.env.MAP_STYLES}
        mapboxApiAccessToken={process.env.MAPBOX_TOKEN}
        // onClick={onClick}
      >
      <DeckGL
        height={450}
        width={450}
        latitude={32}
        longitude={96}
        zoom={8}
        layers={[generateLayer(markerClick, markerHover)]}
        onClick={onClick}
      />
      <Marker latitude={32} longitude={96}>
      </Marker>
      </ReactMapGL>
      <div style={{ display: showDiv ? 'unset' : 'none', height: '400px', width: '400px', backgroundColor: 'red', position: 'absolute', top: '70px', cursor: 'pointer' }} />
    </>
  )
}
```

Sorry to be so annoying about this, but any idea what I'm doing wrong?

**Comment by Pessimistress** [comment]
Ah you are using deck.gl@6.4 The prop was called [onLayerClick](https://github.com/uber/deck.gl/blob/6.4-release/docs/api-reference/deck.md#onlayerclick-function-optional) back then.

**Comment by martahj** [comment]
That did the trick! Thank you so much @Pessimistress
