### ISSUE TITLE
Dynamically show/hide views

### ISSUE THREAD

**Issue by serdaroquai** [uber/deck.gl#3352]
I would like to dynamically show/hide a minimap (with its own viewstate), but the controller events are not picked up by the minimap when it is dynamically created.  Below are two examples to observe the difference:

always on minimap view, it's viewstate is interactable:  [https://repl.it/repls/AmusingHandmadeWebsites](https://repl.it/repls/AmusingHandmadeWebsites)

same example but minimap is toggled via onClick handler, in this case minimap  viewstate is not interactable: [https://repl.it/repls/SympatheticCostlyBots](https://repl.it/repls/SympatheticCostlyBots)

Any pointers about how to do this right are welcome, thank you!

**Comment by Pessimistress** [comment]
I agree this implicit catch is not awesome. A work around I can think of is to add two new views instead of one when the minimap is on, i.e. you have either

```js
const views = [
  new MapView({id: 'main', controller: true})
];
```

Or

```js
const views = [
  new MapView({id: 'main-with-minimap', controller: true}),
  new MapView({id: 'minimap', controller: true})
];
```
