### ISSUE TITLE
Possible to pre-render/cache hexagons for HexagonLayer

### ISSUE THREAD

**Issue by vnugent** [uber/deck.gl#3363]
The data set has about 150K points. Would it be possible to "pre-render" the hexagons somehow?

**Comment by Pessimistress** [comment]
What is the goal? Are you trying to save data download size or client-side processing time?

**Comment by vnugent** [comment]
I'm trying to save data download size

**Comment by Pessimistress** [comment]
You can aggregate the points into hex bins yourself then use the [ColumnLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/column-layer) to render them (which is what the HexagonLayer does). Then you will only need to send the center and count of each hex to the client.
