### ISSUE TITLE
Deck gl layers disappear when 2 Deck instances is present

### ISSUE THREAD

**Issue by heshan0131** [uber/deck.gl#3373]
#### Description
kepler.gl renders 2 Deck.gl instance when export map as an image. when the export map dialog is triggered, kepler render another off-screen map using plot-container.js, which means we are render 2 DeckGl instance at the same time. one is the actual map you see in the background, one is the offscreen plot container

After upgrading to deck.gl 7, I noticed that the background deck layers will disappear when the preview map image shows up

#### Repro Steps
- Load a sample map (e.g. the earthquake map)
- Click share button on top of the side panel
- select export image
- when the preview shows up in the modal (which means the Deck instance in the plot container finishes render), the background map layer disappears.

![bug-image-export](https://user-images.githubusercontent.com/3605556/61820954-f7b12b00-ae0a-11e9-8079-16d2a6d0a0a3.gif)

**Comment by 1chandu** [comment]
Adding some more context:
Started showing up, when Export Deck component is created with `preserveDrawingBuffer: true` [PR](https://github.com/keplergl/kepler.gl/pull/624)
