### ISSUE TITLE
Trips Layer rendered wrongly in OrthographicView

### ISSUE THREAD

**Issue by Chumhoo** [uber/deck.gl#3392]
#### Description

The trips layer renders incorrectly in OrthographicView with identity coordinate system. 
It renders disordered intersecting lines and runs extremely slow when I interact with it.

- Bug screenshot rendered by OrthographicView and identity coordinate system:

![Screenshot from 2019-07-30 18-19-40](https://user-images.githubusercontent.com/15712179/62176497-a0bdc100-b2f6-11e9-9384-75eae57ff8a2.png)

- Expected: rendered by MapView

![Screenshot from 2019-07-30 17-55-59](https://user-images.githubusercontent.com/15712179/62175658-4f600280-b2f3-11e9-8b48-1bcb7a4f2fa6.png)

#### Repro Steps

The bug could be reproduced quickly by the code below. 
For comparison, the expected layer can be correctly rendered by uncomment MapView, and comment OrthographicView and IDENTITY (all marked in the code). 

```javascript
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>deck.gl trips layer demo</title>
  <style>
    body {
      width: 100vw;
      height: 100vh;
      margin: 0;
    }
    #deckgl-overlay {
      background: #000;
    }
</style>
</head>
<body>
  <script src='https://d3js.org/d3.v5.min.js'></script>
  <script src='https://unpkg.com/deck.gl@~7.0.0/dist.min.js'></script>
  <script>
    const deckgl = new deck.DeckGL({
      mapbox: false,
      viewState: {
        zoom: 10,
        target: [-73.9712, 40.7831, 0],
        longitude: -73.9712,
        latitude: 40.7831
      },
      views: [
        // [1] Uncomment this line
        // new deck.MapView({id: 'map'}),
        // [2] Comment this line
        new deck.OrthographicView({id: 'ortho'})
      ],
    });  
    d3.json('https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/trips.json').then(data => {
        deckgl.setProps({
          layers: [
            new deck.TripsLayer({
              id: 'trips',
              // [3] Comment this line
              coordinateSystem: deck.COORDINATE_SYSTEM.IDENTITY,
              data,
              getPath: d => d.segments,
              getColor: d => (d.vendor === 0 ? [253, 128, 93] : [23, 184, 190]),
              opacity: 1.0,
              widthMinPixels: 2,
              rounded: true,
              trailLength: 100,
              currentTime: 1800
            })
        ]
      }); 
    });
  </script>  
</body>
</html>
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.1.10
 - Browser Version: Chrome 75.0
 - OS: Linux Debian

#### Logs

No logs.

**Comment by Pessimistress** [comment]
@Chumhoo By default `getWidth` is `1`. In `COORDINATE_SYSTEM.LNGLAT` mode, `1` is 1 meter. When you use lnglat data with `COORDINATE_SYSTEM.IDENTITY`, `1` is 1 degree which is ~110km. Add something like `widthScale: 0.0001` to your layer and it will render.

**Comment by Pessimistress** [comment]
`OrthographicView` does not handle geographic data like `MapView` does, this includes Mercator distortion, y-flipping, etc. If you just want to remove the perspective, you can construct `MapView` with `orthographic: true`.

**Comment by Chumhoo** [comment]
Thank you for your helpful answer! @Pessimistress 
It seems that I did forget to specify the width for that layer... And it was solved after I added that prop.
Yes I'm aware of the `orthographic` prop, but I still need those two views for different purposes.
