### ISSUE TITLE
Rendering pathLayer at high zoom

### ISSUE THREAD

**Issue by thomasgwatson** [uber/deck.gl#3399]
#### Description

Uneven rendering of path layer at higher zoom levels.

![rendering](https://user-images.githubusercontent.com/5193218/62500957-760fb480-b79d-11e9-8cb1-e61bcf9dbc1e.gif)

#### Repro Steps

I have attempted to get a different rendering result using [layer properties](https://deck.gl/#/documentation/deckgl-api-reference/layers/path-layer?section=widthscale-number-optional-) such as widthScale, widthUnits, fp64 and tweaking widthMinPixels/widthMaxPixels.

Any tips, or is this just an architectural decision that I won't be able to get around?

Layer code
`/**
 * Data format:
 * [
 *   { color: [82, 163, 219], coordinates: [[-122.4, 37.7], [-122.5, 37.8], [-122.6, 37.85]] },
 *   ...
 * ]
 */
export default function createTraceLayer(data, selected) {
  return new PathLayer({
    id: 'trace-layer',
    data,
    rounded: true,
    widthMinPixels: 6,
    widthMaxPixels: 16,
    getPath: ({ coordinates }) => coordinates,
    getColor: ({ color }) => color,
    getWidth: 8,
    opacity: selected ? 0.4 : 0.9,
    fp64: true
  })
}`

#### Environment (please complete the following information):
 - Framework Version: 7.1.10
 - Browser Version: Chrome 75
 - OS: Mojave

**Comment by Pessimistress** [comment]
From your GIF it looks like it's the other way around (path disappear at low zoom levels). It will help if you share your path data; I suspect that it is too fine-grained. The PathLayer discards a segment if the length/width ratio is less than `0.001` (this is arguably an arbitrary number but we cannot reduce it to 0). You can try [turf.simplify](http://turfjs.org/docs/#simplify) to reduce the number of points when zooming way out.

**Comment by thomasgwatson** [comment]
Thanks for the insight. I suspect you are right: it is gps trace data and so many many points along the path. And sorry, getting my zoom orientation back to front!
