### ISSUE TITLE
Make more layer properties functions

### ISSUE THREAD

**Issue by twgonzalez** [uber/deck.gl#3401]
#### Target Use case
Being able to have more granular control of how a layer renders a datum would allow for more expressive visualizations.

#### Proposed feature
Make more of the layer properties dynamic functoids that are data bound.  For instance, being able to have the radius of a column within a ColumnLayer use a dynamic getter to set its value like what is being done for strokes and fills.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Can you explicitly list the props hat you are interested in?

**Comment by twgonzalez** [comment]
First, thank you and the team for a GREAT framework.  I am really impressed with the performance and abstractions you have used to create this.  The code is super clean and easy to follow.

In general, being able to adjust any datum specific property dynamically would be super helpful.  For instance here is simple use case:

A user wants to place a mouse over a rendered item and have it visible properties change on mouse-over or click.   

Currently we have the auto highlight feature, but it would be helpful to be able to adjust other visible features.  Unless I am missing something the only way I see how to do this for props that are not currently adjustable is to have a separate 'highlight' layer with these non adjustable properties pre-set and then to render that one datum in this temporary layer.  I am not sure if there are performance implications for my proposal below, or another best practice you would recommend to achieve the same.

Here is an example of the per datum props I would want to change on a the Column Layer (but it applies equally well to other layers.)

fill opacity per datum
stroke opacity per datum
radius per datum
disc resolution per datum
angle per datum
stroked per datum
extruded per datum
wireframe per datum
material per datum

**Comment by Pessimistress** [comment]
@twgonzalez For these specific examples:

- you can already control fill and stroke opacity by returning [R, G, B, A] with `getFillColor` and `getLineColor`.
- you can "turn off" stroked/extruded/wireframe for a particular datum by either returning `[0, 0, 0, 0]` with `getLineColor`, or returning `0` with `getLineWidth`, and returning `0` with `getElevation`.
- it's fair to support per-object radius.
- disk resolution cannot be changed per-object. This layer accelerates rendering by instancing the same model at each position. Creating different geometries for each object is extremely expensive, and in the case of `ColumnLayer`, you probably won't even see the visual difference.
- material per object: should be doable but what's the use case?

It's worth noting that WebGL has an upper limit of 16 attributes. `ColumnLayer`  already uses 9, `PathLayer` uses 12. Extensions such as [DataFilterExtension](https://deck.gl/#/documentation/submodule-api-reference/deckgl-extensions/data-filter-extension) relies on adding custom attributes to a layer. The more attributes we add to a layer, the less extensible it will become.

With that said, I think it might be possible for us to make an extension that "convert" a uniform to an attribute? Then users can pick and choose the one they want to define per-object. @tsherif

**Comment by twgonzalez** [comment]
Great points!   I totally forgot about the alpha channel in the RGBA color properties.. I was stuck in the typical CSS/D3 paradigm.   So use case solved there and with "turning off" strokes.

Good on radius - it would be helpful

Understood on disk resolution - no use case compelling enough to warrant the performance hit (and additional code complexity)

In regards to the material per object, I can't think of a super compelling use case other than importing glTF files - but I suspect you already handle that in the SceneGraphLayer (which I haven't looked at yet.)

The idea of being able to abstract extension that "converts" a uniform to an attribute might leave a nice hook in place for developers doing edge-case type work and work within the WebGL upper limit of 16 attributes (which I wasn't aware of.)

If there is any way I can offer more feedback or help out just let me know.

**Comment by tgorkin** [comment]
Closing assuming this is resolved adequately. Please reopen and comment or create new issue(s) with additional specific feature requests.

**Comment by twgonzalez** [comment]
I think the only relevant feature to come out of this was to add the ability to support a per-object radius.   But I could always write a custom layer to do this if you guys don't see that as relevant use case.
