### ISSUE TITLE
IconLayer   icon disappear

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3406]
before some days I update deck.gl version to v7
` "@deck.gl/core": "^7.1.7",`
` "@deck.gl/geo-layers": "^7.1.7",`
`"@deck.gl/layers": "^7.1.7",`

when I load IconLayer, it succeeded。
![image](https://user-images.githubusercontent.com/42837853/62620441-ebb98300-b94b-11e9-9b74-4ea5ca06ede5.png)
after I dragged the map,Icon disppear
![image](https://user-images.githubusercontent.com/42837853/62620474-012ead00-b94c-11e9-8cd0-770c3b79bcd7.png)
no matter change the zoom level or move the map position
Icons sometimes appear and sometimes disappear

**Comment by xintongxia** [comment]
Have you checked the [icon](https://github.com/uber/deck.gl/tree/master/examples/website/icon) example? 

If you still have troubles with seeing the icon while dragging, you can share your code snippet here.

**Comment by HeiYanjing** [comment]
@xintongxia  thank you for your reply.
I checked the [documention iconlayer example](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer).
this is my code

         const exhibitoncityIncons = require('../../../../public/resources/images/cityIcon.png');
         const exhibitionMappings = require('../../../../public/resources/data/exhibition_icon_mapping.json');


          new IconLayer({
              id:'city-layer',
              data:this.props.map.cityIcons,
              pickable: true,
              iconAtlas:exhibitoncityIncons,
              iconMapping:exhibitionMappings,
              sizeScale: 150,
              getPosition: d => d.coordinates,
              getIcon: d => d.icon,
              onClick: info => this.iconClick(info),
          }),

**Comment by xintongxia** [comment]
I did a simple IconLayer example, you can play around with your own icon parametres. 

https://codesandbox.io/embed/peaceful-joliot-xvufo

I'll update the doc.

**Comment by HeiYanjing** [comment]
@xintongxia  ok, thank you fory your share.
I have another question. Whether  there  is a attribute to set Icon hiding or display.
for example , when zoom level  >8  and zoom level <14 ,Icon display .ohterwise ,hiding Icon layer?
thank you

**Comment by xintongxia** [comment]
there is a [`onViewStateChange`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#onviewstatechange-function) callback you can listen to

Also I updated the coodesandbox

**Comment by HeiYanjing** [comment]
@xintongxia  thank you.
you are the kindest person in the world.
