### ISSUE TITLE
TileLayer example not working in Firefox

### ISSUE THREAD

**Issue by MiKom** [uber/deck.gl#3436]
#### Description
TileLayer example doesn't show the map in latest firefox

#### Repro Steps
Go to https://deck.gl/#/examples/core-layers/tile-layer in latest Firefox

Map doesn't show up

#### Environment (please complete the following information):
 - Framework Version: whatever is in the example
 - Browser Version: Firefox 69.0b12 (64-bit)
 - OS: Windows 10 1903

#### Logs
[ff_deckgl_logs.txt](https://github.com/uber/deck.gl/files/3496085/ff_deckgl_logs.txt)

**Comment by Pessimistress** [comment]
Looks like FF does not support the options parameter in `createImageBitmap`: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap#Browser_compatibility

This needs to be fixed in both deck and loaders.gl.

**Comment by Pessimistress** [comment]
Fixed in 7.2.1
