### ISSUE TITLE
Question about ColumnLayer

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3437]
![image](https://user-images.githubusercontent.com/42837853/62932305-7689fa00-bdf2-11e9-813c-4cb596fb2b7b.png)
![image](https://user-images.githubusercontent.com/42837853/62932350-84d81600-bdf2-11e9-99d5-528dfe89b0c4.png)
In columnLayer example ,Is there any  way to set the value of the data on the top of column.
like the picture 2( 23340 on the top of column)

**Comment by ibgreen** [comment]
You should be able to position TextLayer labels using the same data you use for the ColumnLayer.

**Comment by HeiYanjing** [comment]
@ibgreen  I tried it. but  the height value in the coordinates doesn't  work. and I also tried to  set  different z axis value . 
![image](https://user-images.githubusercontent.com/42837853/63673679-6709a880-c817-11e9-9ae3-29930e8b6055.png)

**Comment by HeiYanjing** [comment]
@ibgreen  thank you for your reply. I tried it .  and there is another question
![image](https://user-images.githubusercontent.com/42837853/63932533-f1f1d980-ca89-11e9-8641-d7c9e3289966.png)



          new  ColumnLayer({
            id:'column-layer',
            data,
            diskResolution: 12,
            radius: 25,
            extruded: true,
            pickable: true,
            coverage:3,
            elevationScale: 0.1,
            getPosition: d => d.coor,
            getFillColor: d => [254, 17, d.value * 1, 255],
            getLineColor: [0, 0, 0],
            getElevation: d => d.value,
          }),

this column have two different color ,the back of column's color looks like  black. I haven't set light

**Comment by tgorkin** [comment]
Closing this issue. Please open a new issue if you are still having issues with column layer lighting.
