### ISSUE TITLE
TileLayer - LineString doesn't render due to GPSL compilation errors 

### ISSUE THREAD

**Issue by martin-kieliszek** [uber/deck.gl#3441]
**Context**
I have succesfully used the example `TileLayer` documentation to retrieve `pbf` vector tiles and render `Point` features on deck.gl

https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md

**Problem**
Unfortunately, if any of my source tiles have layers with `LineString` features, the example falls apart. 

Nothing renders and I receive errors like below:

```
Uncaught Error: GLSL compilation errors in vertex shader path-layer-vertex-shader-1
```
```
luma: GLSL compilation errors in vertex shader path-layer-vertex-shader-1
513:     dot(offsetFromStartOfPath, dir)
514:   );
515:   geometry.uv = vPathPosition;
^^^ ERROR: 'assign' : cannot convert from 'varying highp 2-component vector of float' to 'const highp float'

517:   float isValid = step(instanceTypes, 3.5);
518:   vec3 offset = vec3(vCornerOffset * widthPixels * isValid, 0.0);
519:   DECKGL_FILTER_SIZE(offset, geometry);
^^^ ERROR: 'DECKGL_FILTER_SIZE' : no matching overloaded function found

545: 
546: void main() {
547:   geometry.worldPosition = instanceStartPositions;
^^^ ERROR: 'assign' : cannot convert from 'attribute highp 3-component vector of float' to 'const highp float'

548:   geometry.worldPositionAlt = instanceEndPositions;
^^^ ERROR: 'assign' : cannot convert from 'attribute highp 3-component vector of float' to 'const highp float'

564:   if (billboard) {
565:     vec4 prevPositionScreen = project_position_to_clipspace(prevPosition, prevPosition64xyLow, ZERO_OFFSET);
566:     vec4 currPositionScreen = project_position_to_clipspace(currPosition, currPosition64xyLow, ZERO_OFFSET, geometry.position);
^^^ ERROR: '=' : cannot convert from 'const mediump float' to 'highp 4-component vector of float'

586:       lineJoin(prevPosition, currPosition, nextPosition),
587:       1.0);
588:     geometry.position = pos;
^^^ ERROR: 'assign' : cannot convert from 'highp 4-component vector of float' to 'const highp float'

589:     gl_Position = project_common_position_to_clipspace(pos);
590:   }
591:   DECKGL_FILTER_GL_POSITION(gl_Position, geometry);
^^^ ERROR: 'DECKGL_FILTER_GL_POSITION' : no matching overloaded function found

592:   DECKGL_FILTER_COLOR(vColor, geometry);
^^^ ERROR: 'DECKGL_FILTER_COLOR' : no matching overloaded function found
```

Has anyone been successful in rendering `TileLayer` with `LineString` features? 

Not even `1` `LineString` is working for me using southern hemisphere lat, lngs - exceptions continue to occur. The moment I remove any `LineString` layer from the vector data, the other `Point` layers render as expected without a crash

During chrome debugging, I can see all the features are succesfully fetched and converted to geojson prior to being added into the features array (see example link above if not following). 

When the fetch finally returns the feature array in the getTileData function, exceptions occur aftwards.

Versions of dependencies I have for linked example
```
"@mapbox/vector-tile": "1.3.1",
 "pbf": "3.2.0"
"@deck.gl/geo-layers": "7.1.10"
"@deck.gl/react": "7.1.10"
```

**Seeking Help**

Can anyone that has a `LineString` layer on a `pbf` tileserver (such as `tileserver-gl`) confirm that they are able to render a LineString on deck.gl using the example? I can't determine a fix based off the above errors I am receiving and am concerned it is within the above libaries.

**Stack Trace**
```
Uncaught Error: GLSL compilation errors in vertex shader path-layer-vertex-shader-1
    at VertexShader._compile (shader.js:105)
    at VertexShader.initialize (shader.js:60)
    at VertexShader.Shader (shader.js:45)
    at new VertexShader (shader.js:137)
    at ShaderCache.getVertexShader (shader-cache.js:36)
    at ShaderCache._createNewProgram (shader-cache.js:98)
    at ShaderCache.getProgram (shader-cache.js:74)
    at Model._createProgram (base-model.js:305)
    at Model.initialize (base-model.js:36)
    at Model.initialize (model.js:34)
    at Model.BaseModel (base-model.js:26)
    at new Model (model.js:24)
    at PathLayer._getModel (path-layer.js:236)
    at PathLayer.updateState (path-layer.js:201)
    at PathLayer._updateState (layer.js:684)
    at PathLayer._initialize (layer.js:660)
    at LayerManager._initializeLayer (layer-manager.js:452)
    at LayerManager._updateSublayersRecursively (layer-manager.js:383)
    at LayerManager._updateSublayersRecursively (layer-manager.js:404)
    at LayerManager._updateSublayersRecursively (layer-manager.js:404)
    at LayerManager._updateLayers (layer-manager.js:338)
    at LayerManager.setLayers (layer-manager.js:193)
    at LayerManager.updateLayers (layer-manager.js:221)
    at Deck._onRenderFrame (deck.js:692)
    at AnimationLoop.onRender (animation-loop.js:278)
    at AnimationLoop._renderFrame (animation-loop.js:352)
    at AnimationLoop.redraw (animation-loop.js:170)
    at renderFrame (animation-loop.js:310)
```

Appreciate anyone that may assist, comment or direct me elsewhere if necessary

Kind Regards

**Comment by Pessimistress** [comment]
The shaders are from @deck.gl/layers@7.2.0 but your @deck.gl/core is 7.1.x. you need to make sure that all dependency versions match.

**Comment by martin-kieliszek** [comment]
Thanks @Pessimistress you made my long troubleshooting session worth it :)

Your suggestion fixed my problem
```
npm remove @deck.gl/layers
```

And then 
```
npm install --save @deck.gl/layers@7.1.0
```

**Post Mortum**
I had been playing around with `IconLayer` and `LineLayer` prior to using `TileLayer`. I definitely installed the latest version of `@deck.gl/layers`. This version was higher than the core version as you described.

**One more question**
Now that I can succesfully use `TileLayer`, can you please confirm if it is possible to use it to render `Icon`'s on `Point` features?

I can see lines and points can have their colours and size changed. However, my search into the base layer of `TileLayer` has lead me to believe there are no options for Icons. 

I may need to do all symbol styling on tileserver backend, is this your recommendation?

If you have an approach for rendering Icons on TileLayer `Point` features, please let me know :D 

Great work, thanks again and take care

**Comment by xintongxia** [comment]
You can use [`IconLayer`](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer) to render your points and pass to [`renderSubLayers`](https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md#rendersublayers-function-optional)

```
renderSubLayers({data, tile}) => {
  
  const iconLayer = new IconLayer({
    id: 'icon-layer',
    data, // points data from your tiles
    pickable: true,

    sizeScale: 15,
    getPosition: d => d.coordinates, // position of the icon

    // OPTION 1: pre-packed icon atlas       
    iconAtlas: 'images/icon-atlas.png',
    iconMapping: ICON_MAPPING,
    getIcon: d => 'marker',

    // OPTION 2: dynamic icon url
    getIcon: d => ({
      url: d.icon_url,
      width: 128,
      height: 128,
      anchorY: 128
    })
  })

  return [..., iconLayer];
}
```
