### ISSUE TITLE
How to Find all PointCloudLayer Nodes Within an Area 

### ISSUE THREAD

**Issue by michaelsklepowich** [uber/deck.gl#3445]
Hello, I'm trying to implement a bounding-box 'selector' for a PointCloudLayer using an Orthographic View in React/Redux. 

I'm logging the coordinates of the box with `onClick={({x, y}) => this.handlePclClick(x, y)}` on the DeckGL component (first click logs the top-left XY, second click logs the bottom-right XY). 
![boundingbox](https://user-images.githubusercontent.com/35241990/63042860-cb278680-be7f-11e9-95fa-74bbe4ad01f2.png)
However, the XY values I get back from this onClick are based on the width/height of the canvas element 

I want to return all nodes contained within the coordinates of the box but I don't know where to find the XY coordinates associated with each PCL node in the DeckGL component and trying to find the PCL nodes from the DeckGL XY seems like a hacky approach.

Love the work you guys are doing, thanks.

**Comment by xintongxia** [comment]
from the `onClick` callback, you can access `lngLat` under your cursor. `onClick={({x, y, lngLat}) => this.handlePclClick(...)}`. From there you can execute data filtering based on your polygon.

**Comment by michaelsklepowich** [comment]
Thank you, this is exactly what I was looking for. 

I forgot to mention that I was using a non-mercator coordinate system. 
Interestingly, though, the `lngLat` works with `COORDINATE_SYSTEM.IDENTITY`

Is there a list of all arguments I can access from the onClick callback in the documentation?

**Comment by xintongxia** [comment]
@michaelsklepowich 

you can print out and what's in there by `onClick={(obj) => console.log(obj)}

Also you can use this [`pickobjects`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#pickobjects)

**Comment by michaelsklepowich** [comment]
@xintongxia Awesome, thank you very much for the help.

**Comment by zt123123** [comment]
@xintongxia  I am doing this too, I have a question with the `pickobjects` API, 
```js
    const handleClick = info => {
      const { x, y } = info;
      pointCloudLayer.setProps({
        id: 'point-cloud-layer',
        pointSize: 0.2,
      });
      const pickInfo = info.layer.context.deck.pickObjects({
        x, y, width: 1000, height: 1000, layerIds: ['point-cloud-layer'],
      });
      console.log(pickInfo);
    };
```
Firstly, I want to get all points which is selected by a bounding-box.
I use  `pickobjects` API, I pass pixel of `x`,`y`, whatever I change the `width` and `height`, it always return array of length one, not all selected points. so, I wanna to know what is the meaning of `width` `height` ?
Secondly, I want to highlight them, I dont know how to start coding and which API could help me...

**Comment by zt123123** [comment]
@michaelsklepowich could you please show me your code, great  thanks !
