### ISSUE TITLE
Perf: `Uint8Arrays` passed through props are (unnecessarily) copied to `Uint8ClampedArrays`

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#3447]
#### Description

There is helpful logic in the deck.gl attribute manager that will copy a binary data array passed in through props to the correct target type.

However, when passing in `Uint8Array` for colors, which would work perfectly, this gets copied to `Uint8ClampedArray`, an unnecessary operation that hurts performance and increases memory pressure.

More broadly, since 7.3 now supports attribute descriptors where we can also specify type and normalization, this auto-conversion feature can potentially defeat attempts at using more compact arrays as input data.

#### Repro Steps

Found during 3d-tiles debugging. Run 3d-tiles example in loaders.gl with a pointcloud example, click on the warnings in console and put a break point in the source.

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.2.0]
 - Browser Version: [e.g. Chrome 76.0]
 - OS: [e.g. Mac OS X 10.14]

#### Logs

<img width="535" alt="Screen Shot 2019-08-14 at 11 41 32 AM" src="https://user-images.githubusercontent.com/7025232/63047354-2611ab80-be89-11e9-9b1f-4fa9897efefe.png">

**Comment by tsherif** [comment]
Is there a reason we use clamped arrays?

**Comment by ibgreen** [comment]
No strong reason. They could be considered slightly less likely to surprise the user in case of user errors, since over/underflows are handled a bit more "gracefully".

But we would have the opposite problem if we switched to `Uint8Array`. The app could still choose to use `Uint8ClampedArray`s and we would still get an unnecessary copy.

The point is that when reading data from these arrays, from the GPUs point-of-view, they are equivalent (same memory layout), no copy needed.

**Comment by tsherif** [comment]
I don't often see clamped arrays used explicitly, just as a return from things like `canvas.getImageData`. Not related to this bug, but I think it would be more consistent with general practice to default to using Uint8Arrays.

**Comment by ibgreen** [comment]
No strong opinion, using `Uint8ClampedArray` to represent color attributes is just a choice we make in the layers when we specify attributes. I suspect that with the exception of this warning, it is essentially invisible to users. 

Using clamped arrays for colors give us a couple of "free" if-statements that ensure overflowing colors are properly clamped (rather than just truncated to first byte).

```
clampedArray[i] = color.red; 
<=> 
array[i] = color.red > 255 ? 255 : (color.red < 0 ? : color.red);
```

**Comment by Pessimistress** [comment]
I think we can just remove the array type check altogether; if the user is providing their own buffer, then they are responsible of its validity.

If we want to stay on the safe side (e.g. colors are normalized so providing Float32Array is potentially breaking and hard to debug), we can try:

- check if bytes per element is the same
- if optional configs e.g. `normalized` `offset` `stride` are defined by the original attribute but not the user, issue a console warning
