### ISSUE TITLE
Mapbox Layer console error - id already exists

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#3450]
#### Description
I'm using the Mapbox Layer to add a scatterplot. The layer loads, but there are javascript console log errors saying the id already exists. It's like it's trying to load the layer more than once.  

![Screen Shot 2019-08-15 at 10 03 26 am](https://user-images.githubusercontent.com/18344164/63064334-f1165f00-bf43-11e9-995d-21341191037a.png)

#### Repro Steps

I've copied the example at [Use a Layer from an existing Deck's layer stack](https://github.com/uber/deck.gl/blob/master/docs/api-reference/mapbox/mapbox-layer.md#use-a-layer-from-an-existing-decks-layer-stack).

I've added the 
```
map.on('styledata', function() { 
  map.addLayer(new MapboxLayer({id: 'my-scatterplot', deck}));
});
```
to overcome Mapbox's `Style Not Loaded` error.

Working example is at this [jsfiddle](https://jsfiddle.net/symbolixau/ewm4pkuo/60/), and the code is copied here

```html
<html>
  <head>
    <script src="https://unpkg.com/deck.gl@7.2.1/dist.min.js"></script>
    <!-- only if base map is needed -->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.css' rel='stylesheet' />

<style>
body { margin:0; padding:0; }
#map { position:absolute; top:0; bottom:0; width:100%; }
</style>

  </head>
  <body>
    <div id="map"></div>
  </body>
  <script type="text/javascript">
  
  // token from: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
  mapboxgl.accessToken = 'TOKEN';
  var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
    center: [-74.50, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
  });

const deck = new Deck({
    gl: map.painter.context.gl,
    layers: [
        new ScatterplotLayer({
            id: 'my-scatterplot',
            data: [
                {position: [-74.5, 40], size: 1000}
            ],
            getPosition: d => d.position,
            getRadius: d => d.size,
            getFillColor: [255, 0, 0]
        })
    ]
});

map.on('styledata', function() { 
  map.addLayer(new MapboxLayer({id: 'my-scatterplot', deck}));
  });
  </script>
</html>
```

#### Environment
 - Framework Version: [e.g. deck.gl 7.2.1]
 - Browser Version: [e.g. Chrome 76.0.3809.100]
 - OS: [e.g. Mac OS X 10.14.5]

**Comment by Pessimistress** [comment]
`styledata` can be fired more than once: https://docs.mapbox.com/mapbox-gl-js/api/#map.event:styledata

You should use the `load` event. I will update the documentation.

**Comment by dcooley** [comment]
perfect, thanks; I don't know how I didn't see that - fixed: https://jsfiddle.net/symbolixau/ewm4pkuo/62/

**Comment by sumarlidason** [comment]
for others, i experienced this when using `interleaved: true` in conjunction with a `TileLayer<ImageBitmap>` basemap, resolved by disabling `interleaved`.
