### ISSUE TITLE
Question about  FlyToInterpolator

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3451]
During initialization, I set the INITIAL_VIEW_STATE
`const INITIAL_VIEW_STATE = {`
`    latitude: 34.91370433957939,`
 `   longitude: 106.36210675335315,`
`    zoom: 4,`
`    maxZoom: zoomSet.max,`
`    minZoom: zoomSet.min,`
`    pitch: pitchSet.init,`
`    bearing: bearingSet.init`
`  };`
then ,I move the map center ,change the latitue,longitude,zoom level...
According to the example of _goToNYC() in the [document](https://deck.gl/#/documentation/deckgl-api-reference/views/view-state-transitions?section=usage)
 when  I want change the the mapview to init. it doesn't work.

            this.setState({
                viewState: {
                    ...INITIAL_VIEW_STATE,
                    transitionDuration: 8000,
                    transitionInterpolator: new FlyToInterpolator(),
                    transitionInterruption:TRANSITION_EVENTS.IGNORE
                },

I have two questions:
1,transitionInterpolator: new FlyToInterpolator() works, What conditions must be met? . set different  element  of different value of  INITIAL_VIEW_STATE(latitude,longitude...)?
2,` "@deck.gl/core": "^7.1.7",`
    `"@deck.gl/geo-layers": "^7.1.7",`
   ` "@deck.gl/layers": "^7.1.7",`
` "react-map-gl": "^4.0.5",`
 this is my version . In document example ,
`import DeckGL, {FlyToInterpolator} from 'deck.gl';` 
where should I import `FlyToInterpolator`?
`import DeckGL ,{FlyToInterpolator} from '@deck.gl/react';`
or
`import  {FlyToInterpolator} from 'react-map-gl';`?

**Comment by HeiYanjing** [comment]
if a coordinate fly to another success.
Is there any restrictions.
What Conditions Can't move Succeed?

**Comment by 1chandu** [comment]
Are there any errors in your browser console?

> where should I import FlyToInterpolator?

you can import it form `deck.gl` or `@deck.gl/core`.

You can also check this example:  https://github.com/uber/deck.gl/tree/master/test/apps/viewport-transitions-flyTo

**Comment by HeiYanjing** [comment]
@1chandu ,yes ,no errors.
if console errors ,I will  resolve it .

        this.setState({
            viewState: {
            ...this.state.viewState,
            longitude: ...,
            latitude: ...,
            transitionDuration: 2000,
            bearing:0,
            pitch:50,
            },
        });

If I don't use  `FlyToInterpolator ` . this also can move fly .  It's amazing!

**Comment by 1chandu** [comment]
As [documented](https://deck.gl/#/documentation/deckgl-api-reference/views/view-state-transitions) it uses `LinearInterpolator ` if none specified.
