### ISSUE TITLE
How to Add getLineWidth to PointCloudLayer

### ISSUE THREAD

**Issue by michaelsklepowich** [uber/deck.gl#3460]
Hello, I want to add the same circumference/border from the [ScatterPlotLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer) to the nodes of my PointCloudLayer to make it easier to distinguish overlapping nodes (especially at lower opacities).

The PointCloudLayer does not support the getLineWidth data accessor and I want to be able to use all associated lineWidth props.

My initial thought was just to add the instanceLineWidth, instanceLineColors, etc to the initializeState method of the PointCloudLayer, but I wanted to make an issue to ask for any suggestions.

Love the work you guys are doing, thanks.

**Comment by Pessimistress** [comment]
You'll probably have an easier time modify the ScatterplotLayer to do this. The only difference is that the ScatterplotLayer draws the circle on the XY plane, and the PointCloudLayer draws the circle in the screen space.

**Comment by michaelsklepowich** [comment]
Thank you for insight.
