### ISSUE TITLE
Cant find module 'gl' from 'webgl-types.js' when testing

### ISSUE THREAD

**Issue by Kondifaxe** [uber/deck.gl#3464]
When I am testing my react project which includes deck.gl, i'm getting the following error: 
> Cannot find module 'gl' from 'webgl-types.js'.
The stack trace goes back to when deck.js tries to create a gl context.

**Comment by ibgreen** [comment]
There is a bit of information here https://luma.gl/#/documentation/developer-guide/getting-started

Basically you need to install `gl` to get WebGL support under Node.js.

Alternatively, you can get around this by checking if you are not in the browser and avoid instantiating deck.gl when running under Node.js
