### ISSUE TITLE
TransitionInterruption  event

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3465]
For the documents:

TRANSITION_EVENTS | Result
-- | --
BREAK | Current transition will stop at the current state and next ViewState update is processed.
SNAP_TO_END | Current transition will skip remaining transition steps and ViewState is updated to final value, transition is stopped and next ViewState update is processed.
IGNORE | Any ViewState update is ignored until current transition is complete, this also includes ViewState changes due to user interaction.

can I capture the interrupt event  to handle my business?
and can I use  code to  stop the transient process?
Forexample, set the time  ` transitionDuration :10000` , and in 5000ms,  trigger to stop the process?

**Comment by 1chandu** [comment]
> can I capture the interrupt event to handle my business?

You can provide a callback for `onTransitionInterrupt` that gets fired when interruption is occurred.

> and can I use code to stop the transient process?

When you start the transition, set `interruption` to `BREAK`.
