### ISSUE TITLE
why are cylinders  shown differently under same opacity?

### ISSUE THREAD

**Issue by chris2go** [uber/deck.gl#3469]
![image](https://user-images.githubusercontent.com/14014428/63315375-90b96000-c33d-11e9-952b-b332fdde63d7.png)
why are cylinders  shown differently under same opacity?looks like  it might hv sth 2 do with ambient light settings?

**Comment by 1chandu** [comment]
Its due to blending, the color of a cylinder is blended with the color of the objects behind it (could be a base map or another cylinder).

**Comment by chris2go** [comment]
> Its due to blending, the color of a cylinder is blended with the color of the objects behind it (could be a base map or another cylinder).

tks for the help.
emm, true but might not be the case here, see the img below? a cylinder's supposed 2 have two different lighting effects due 2 some kinda built'n ambient light setting. the question is why,in the img of my 1st post,it works out  differently and i'm pretty sure at least some of them are not blocked by others, as if those cylinders take in light from different angles which makes the visualization a bit confusing, it took me quite some time to figure out the data not aligned in rows.
![image](https://user-images.githubusercontent.com/14014428/63632283-d049ba00-c665-11e9-9fda-907d4faabcef.png)

**Comment by chris2go** [comment]
> Hi @chris2go. The issue is that deck.gl's default depth testing isn't ideal for transparency. You should see some improvement (not perfect) if you add the following property to your layer:
> 
> ```js
> parameters: {
> 	depthMask: false
> }
> ```
> 
> Let us know if that helps.

might not be exactly wot i'm looking for , but better ,tks man!

**Comment by tgorkin** [comment]
Closing assuming this is adequately answered. Please reopen and comment if that’s not the case.
