### ISSUE TITLE
Support for Async Loading in Layers

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#347]
For v4 we need a simple way for an async layer action (like a texture load) to update the layer's state when done and call `Layer.setNeedRedraw`.

The problem:
* When a layer fires of an async action and the callback executes, the `Layer` instance that originally made the call is typically no longer around. Even if the callback holds on to the old layer, the layer.state object has been moved to a “future” layer, and calling `Layer.setState` and `Layer.setNeedsRedraw` will not have the desired effects.

Background:
* Today we clear (i.e. set to `null`) the state objects from old layers when we match them with new ones. This was mainly done as a debugging aid, to help apps catch when they are unintentionally modifying an old layer.
* While this is probably still valuable, keeping the state pointer on old layers would not break any existing code. With that change, all layers that ever matched a state object would point to it. This would allow a callback to hold on to a layer and be able to access its state. 
* Consideration would have to be given to other "state" on the layer. E.g. the context object would no longer be valid, this could lead to hard-to-detect bugs depending on what methods the async callback uses.

Possible Solutions:
* We could define `Layer.setState` as the only acceptable function to call in a callback, and make sure that `Layer.setState` calls `Layer.setNeedsRedraw`? 
* We could just tell people to set `state.layerNeedsRedraw` to `true`. The fact that we store needsRedraw in the state is an implementation detail that could change.
* We could also add a set() method on the state object. It should be possible to capture state and the set method could update any state variables and set needsRedraw.
* Or we could create a function getAsyncSetter() that returned a function that could be safely called at a later stage.

**Comment by ibgreen** [comment]
@Pessimistress @shaojingli @gnavvy

**Comment by Pessimistress** [comment]
Another use case would be calculating attributes in a web worker.

**Comment by ibgreen** [comment]
> Another use case would be calculating attributes in a web worker.

Yep - that would be pretty awesome. I do think we slightly more control over that use case since we might be able handle the async updates inside the attribute manager rather than exposing it to the layer writer.

**Comment by ibgreen** [comment]
Went with the simple approach of no longer setting `state` to `null` for disposed layers.

The other approaches were not well-developed enough. Time will tell if this was the right choice.
