### ISSUE TITLE
EditableGeoJsonLayer's context does not have a gl prop

### ISSUE THREAD

**Issue by Kondifaxe** [uber/deck.gl#3470]
When running yarn test in my react project, im getting the error:

```
Cannot read property 'addEventListener' of undefined

      at EditableGeoJsonLayer.addEventListener [as _addPointerHandlers] (node_modules/@nebula.gl/layers/src/layers/editable-layer.js:97:28)
```
, which is due to the EditableGeoJsonLayer's context does not have a gl prop. I've added "gl" and "luma.gl", but i'm still getting this problem for some reason.

**Comment by Pessimistress** [comment]
@Kondifaxe Please move this issue to the nebula.gl repo.
