### ISSUE TITLE
HeatmapLayer throws GL_BLEND with floating-point color attachments requires the EXT_float_blend extension

### ISSUE THREAD

**Issue by christianbalderrama** [uber/deck.gl#3480]
#### Description

Implementing the `HeatmapLayer` doesn't reflect the heatmap and throws warning in the console see logs below.

#### Repro Steps
```
    const layers = [
      new HeatmapLayer({
        id: "heatmaplayer",
        data: [{COORDINATES: [-122.42177834, 37.78346622], WEIGHT: 10}],
        getPosition: d => d.COORDINATES,
        getWeight: d => d.WEIGHT,
      }),
    ];
    return (
      <MapGL ...>
        <DeckGL
            viewState={this.state.viewState}
            initialViewState={this.state.viewState}
            controller={{type: MapController}}
            layers={layers}
            onContextMenu={event => event.preventDefault()}
        />
      </MapGL>
    );
```

#### Environment:
 - Framework Versions:
```
    "@deck.gl/aggregation-layers": "^7.2.2",
    "@deck.gl/core": "^7.2.2",
    "@deck.gl/layers": "^7.2.2",
    "@deck.gl/mapbox": "^7.2.2",
    "@deck.gl/react": "^7.2.2",
```
 - Browser Version: Chrome 75.0.3770.142
 - OS: Xubuntu 18.04 LTS x64

#### Logs
```
2TWFwOjE=:1 [.WebGL-0xc881cd8b300]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: GL_BLEND with floating-point color attachments requires the EXT_float_blend extension
```

**Comment by christianbalderrama** [comment]
![Screenshot_2019-08-22_09-12-44](https://user-images.githubusercontent.com/18398769/63478592-0435ab80-c4bd-11e9-8de0-7f1d67f197bb.png)

This console warning shows in the official documentation and does not reflect the heatmaps as well.

**Comment by 1chandu** [comment]
`HeatmapLayer` is `WebGL2` only for now (support for WebGL1 in future releases), but it should print an error message when run under `WebGL2`.

One possibility is you are using `WebGL2`, but `EXT_float_blend` is not supported, if so we have to add explicit check for it.  Can you set `luma.log.priority=1` in your chrome browser console and refresh the heatmap documentation page, and copy paste logs here? It should log what kind of WebGL context it is using.

To verify if you have the support, can you go to https://webglreport.com/?v=1 and under `WebGL1` and `WebGL2` tab,  see if `EXT_float_blend` listed?

**Comment by 1chandu** [comment]
Filed a [bug](https://github.com/KhronosGroup/WebGL/issues/2920) to Khronos for clarifying this extension page for WebGL2 support :

**Comment by 1chandu** [comment]
@christianbalderrama , it turns out the `EXT_float_blend` is not always supported in WebGL2 and this layer requires it. I am making a change to log more meaningful message instead of a crash.
