### ISSUE TITLE
CPUGridLayer error in pre-bundled scripts 

### ISSUE THREAD

**Issue by heumsi** [uber/deck.gl#3484]
In [this doc](https://deck.gl/#/documentation/deckgl-api-reference/layers/cpugrid-layer), CPUGridLayer is introduced to use pre-bundled scripts.

but, when I use this class, this error appear,
```
# input
new deck.CPUGridLayer({....})
```
```
# output
Uncaught TypeError: deck.CPUGridLayer is not a constructor.
```

So, I tried to find CPUGridLayer in `https://unpkg.com/deck.gl@~7.0.0/dist.min.js`
but, I can't find this class...

How can I use CPUGridLayer in script js?

**Comment by Pessimistress** [comment]
Hmm this is an error in the docs; CPUGridLayer was introduced in 7.1. We need to replace all `~7.0.0` with either `~7.2.0` or `^7.0.0`.

@1chandu
