### ISSUE TITLE
IconLayer load a gif picture?

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3512]
Is there any way  to load gif picture when I use IconLayer?

**Comment by Pessimistress** [comment]
It's not possible to load a gif directly. However, you can pack each frame of the animation into the atlas and change the icon name on each frame, which is fairly cheap. This is a common technique used by game developers.

**Comment by HeiYanjing** [comment]
@Pessimistress  thank you for your advise

**Comment by Losiyu** [comment]
In react, show I use State to control the icon picture in each frame?
