### ISSUE TITLE
3D tile example can't show anything with PR #3496

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#3515]
#### Description

All the [3D tile example](https://github.com/uber-web/loaders.gl/tree/master/examples/3d-tiles) can't show any data after integrating with Deck.gl after PR #3496 

#### Repro Steps

Launch 3D tile example with native deck.gl dependency, nothing shows up.
Revert local deck.gl to commit before  #3496, everything works fine.

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

#### Logs

NO error messages.

**Comment by Pessimistress** [comment]
The experimental `layer.context.animationProps` was removed in this PR.
