### ISSUE TITLE
_Sunlight _shadow only throws across background on initial render (bonus lighting question!)

### ISSUE THREAD

**Issue by mayteio** [uber/deck.gl#3543]
#### Description

Firstly: I understand this is an unstable feature, hoping this can help get it towards stable!

I'm trying to create a visualisation that simulates sunlight at any given time or date.

When using the `_Sunlight` lighting effect's `_shadow` prop, the shadows only throws on the first render. When I recreate the sunlight instance, the shadows appear to only throw on polygons. 

Expected (achieved without creating new sunlight instance or interleaving with Mapbox layers):

<img width="1199" alt="Screen Shot 2019-09-07 at 11 17 09 am" src="https://user-images.githubusercontent.com/43975092/64467899-2ee05f00-d161-11e9-92d3-f1107ac27afe.png">

Actual (occurs when either generating new sunlight instance or interleaving with mapbox layers):

<img width="1198" alt="Screen Shot 2019-09-07 at 11 17 22 am" src="https://user-images.githubusercontent.com/43975092/64467912-4d465a80-d161-11e9-9315-e1b7ae27c32c.png">

#### Repro Steps

[Code sandbox demo](https://codesandbox.io/s/melbourne-shadows-9ipxb)

The relevant lines are in App.js:28, which;

1. calls generateLighting.js (get new LightingEffect instance with updated props)
2. puts the new lighting instance in state

That then gets passed to the map on line 51 in render.

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.2.2]
 - Browser Version: [e.g. Chrome 76.0]
 - OS: [e.g. Mac OS X 10.14.6]

#### Logs
No error logs are thrown.

#### Bonus question:

With lighting effects, I can't seem to figure out realistic lighting on the building polygons using a combination of ambient light and sunlight. Do I need to dynamically change the ambient light based on time as well? The buildings just seem to be black no matter what.

**Comment by Pessimistress** [comment]
It's not surprising that the shadow system does not work with Mapbox integration. The way the Mapbox layer system works, each layer is rendered in isolation, and they are not aware of each other (hence the building layer only casts shadow onto itself). Because we do not own the render pipeline when deck is used as Mapbox custom layers, it's arguably impossible to generate an accurate shadow map. For your use case, It can be worked around by rendering the buildings and the ground with the same layer.

For your bonus question - I think we do calculate sun rise and sunset times in the `SunLight` class, so it's possible to set light strength as well as direction based on time. It may require a little feature work to create two internal lights from the same `SunLight` instance.

**Comment by mayteio** [comment]
Thanks for your comment @Pessimistress, interesting to understand the inner workings of Mapbox and its limitations. 

If I remove the Mapbox Layers and just render as an overlay, I do get shadows on the first render - though when I regenerate the `SunLight` class by changing the time, [https://codesandbox.io/s/melbourne-shadows-9ipxb](the shadows are lost). Are you suggesting that the ground (large square polygon covering Melbourne) should be part of the buildings GeoJSON? And I set the color on some property, i.e. `fillColor: d => d.properties.isGround ? [0,0,0,0] : [255,255,255]` ?

Bonus question: Would the second light act as a point light to light up the rest of the scene?

**Comment by Pessimistress** [comment]
> Are you suggesting that the ground (large square polygon covering Melbourne) should be part of the buildings GeoJSON? 

Yes

> when I regenerate the SunLight class by changing the time, the shadows are lost.

Instead of making a new `LightingEffect` instance, I suggest you directly set `sunLight.timestamp` on the existing instance for now. There are some perf issues and known bugs when the LightingEffect is removed/added. @jianhuang01

**Comment by mayteio** [comment]
Thanks for the guidance @Pessimistress, I was able to achieve a great effect: https://codesandbox.io/s/melbourne-shadows-9ipxb

For some reason though, you must move the map before the shadow effect takes place. I've tried delaying the shadow until the data has loaded, but that has no effect. Any idea why this might be?

**Comment by mayteio** [comment]
[https://sunlight-to-parks.netlify.com/](Final result) - thanks for the help team.

**Comment by Pessimistress** [comment]
> you must move the map before the shadow effect takes place

There was a bug that we fixed recently - maybe try `7.3.0-beta`?
