### ISSUE TITLE
TextLayer not displaying correctly when used after a PolygonLayer

### ISSUE THREAD

**Issue by jochri3** [uber/deck.gl#3544]
I'm using **ubers deck.gl** for visuaization.Everything work fine but,when on the **map** i use `PolygonLayer` for displaying polygon for each `state/province`,it work fine,but the if i add a `TextLayer` for displaying **labels(names)**,the label or text is rendered on the given `state/province` , but only in a half part,not completely.But when i remove the `PolygonLayer` the text is rendered correctly.

#1 - Without the **PolygonLayer**

[![Map without PolygonLayer][1]][1]

#2 - With **PolygonLayer**
[![With PolygonLayer][2]][2]

So as you can see,my `TextLayer` is overidden by the `PolygonLayer`.
Also,in the order of definition of layers in my code,the `TextLayer` comes after the `PolygonLayer`.
Here are the both codes:

 

    ...
        new PolygonLayer({
              id: "province-contours",
              data: provinceContours,
              pickable: true,
              stroked: true,
              filled: true,
              wireframe: true,
              lineWidthMinPixels: 1,
              lineWidthScalelineWidthScale: 0,
              getPolygon: d => d.contour,
              getFillColor: hoverColor,
              getLineColor: [31, 74, 75],
              getLineWidth: 1,
              highlightColor: [0, 0, 128, 128],
              autoHighlight: true,
            }),
        new TextLayer({
              id: "text-layer",
              data: provinceLabel,
              pickable: true,
              getPosition: d => d.coordinates,
              getText: d => d.name,
              getSize: 32,
              opacity: 1,
              getAngle: 0,
              getColor: [0, 0, 0, 255],
              getTextAnchor: "middle",
              getAlignmentBaseline: "center"
            })
    ...

Here the documentation for both of them:
[PolygonLayer][3]
[TextLayer][4]

How can i fix this problem?

Thank you!

  [1]: https://i.stack.imgur.com/Pk0IB.png
  [2]: https://i.stack.imgur.com/Ti9jK.png
  [3]: https://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer
  [4]: https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer

**Comment by Pessimistress** [comment]
Your texts are anchored at z=0 and the bottom halves are buried "under ground" by the polygons. You can try set `getAlignmentBaseline: 'bottom'` in combination with  the `getPixelOffset` prop to shift them up. If you do wish to render them at the same location, you can also disable depth test by using

```
new TextLayer({
  // ...
  parameters: {depthTest: false}
});
```

**Comment by tgorkin** [comment]
Closing assuming the response above resolves the issue.  Please reopen and comment if this is not resolved.
