### ISSUE TITLE
mapboxLayer flicker

### ISSUE THREAD

**Issue by linghuam** [uber/deck.gl#3601]
#### Description
when I use mapboxLayer in mapbox-gl-js, the scatter layer flicker when pitch the map.

#### Repro Steps
- A Codepen [example](https://codepen.io/linghuam/pen/ExYpOYy) that reproduces the behavior

#### Environment :
 - Framework Version: [deck.gl 7.2.4]
 - Mapbox-gl Version: [1.3.1]
 - Browser Version: [Chrome 77.0]
 - OS: [Mac OS High Sierra 10.13.6]

**Comment by ibgreen** [comment]
You have two scatterplot layers on top of each other, see: https://deck.gl/#/documentation/developer-guide/tips-and-tricks?section=z-fighting-and-depth-testing
