### ISSUE TITLE
pickable: true causing ScatterplotLayer color changes?

### ISSUE THREAD

**Issue by bclinkinbeard** [uber/deck.gl#3629]
I have my custom ScatterplotLayer with time filtering in the shader, which I'm using again for the first time in a while. I discovered that when I would update my time uniforms, the color of my dots would change unpredictably. I couldn't find any code that was doing it, so I started commenting things out one by one. Very confusingly, I've discovered that turning off `pickable` fixes the issue. That's obviously not a long term solution and I'm just flat out perplexed at this point, so I'm hoping someone here might have an idea. My entire layer definition is below.

```
/**
 * deck.gl layer that adds time window awareness to deck.gl's ScatterplotLayer.
 */
export class MyScatterplotLayer extends deck.ScatterplotLayer {
  static layerName: string;
  static defaultProps: any;  // tslint:disable-line:no-any
  minTime!: number;
  maxTime!: number;

  // tslint:disable-next-line:no-any
  constructor(props: ScatterplotLayerProps) {
    super(props);
  }

  initializeState() {
    super.initializeState();
    this.state.attributeManager.addInstanced({
      instanceTimestamps: {size: 1, accessor: 'getTimestamps'},
    });
  }

  // tslint:disable-next-line:no-any
  draw(args: {uniforms: any}) {
    super.draw({
      uniforms: {
        maxTime: this.props.maxTime,
        minTime: this.props.minTime,
        ...args.uniforms,
      }
    });
  }

  getShaders() {
    const shaders = super.getShaders();
    shaders.inject = {
      'vs:#decl': `\
        attribute float instanceTimestamps;
        varying float vTimestamp;
        uniform float minTime;
        uniform float maxTime;
      `,
      'vs:#main-start': `\
        vTimestamp = instanceTimestamps;
      `,
      'fs:#decl': `\
        uniform float minTime;
        uniform float maxTime;
        varying float vTimestamp;
      `,
      'fs:#main-start': `\
        if (vTimestamp < minTime || vTimestamp > maxTime) {
          discard;
        }
      `,
    };
    return shaders;
  }
}

const DEFAULT_PIXEL_RADIUS = 3;

MyScatterplotLayer.layerName = 'MyScatterplotLayer';
MyScatterplotLayer.defaultProps = {
  id: 'my-scatterplot-layer',
  filled: true,
  getFillColor: [0, 0, 255],
  getRadius: DEFAULT_PIXEL_RADIUS,
  maxTime: Number.MAX_SAFE_INTEGER,
  minTime: -Number.MAX_SAFE_INTEGER,
  radiusMaxPixels: DEFAULT_PIXEL_RADIUS,
  radiusMinPixels: DEFAULT_PIXEL_RADIUS,
  useDevicePixels: true,
  opacity: 1,
};
```

**Comment by 1chandu** [comment]
When picking is enabled, there is an additional render pass happens to offscreen buffer with custom picking colors, but that shouldn't affect what you see on the screen. When the color of the dots change, are they random colors? can you share the image?

**Comment by bclinkinbeard** [comment]
They definitely follow a pattern, where they initially start in the black to red range and, if the dataset is large enough, eventually into orange and yellow and green. Blue never seems to appear.
![image](https://user-images.githubusercontent.com/140343/65179140-10a31a80-da0f-11e9-80b6-8331195aeff8.png)

**Comment by 1chandu** [comment]
Looking at the image, it is possible the picking color being used instead of actual color, is this a regression? What version of deck.gl are you using? Can you check older versions?

**Comment by 1chandu** [comment]
Also please provide your environment details: 

 - Framework Version: ? [e.g. deck.gl 6.3.0]
 - Browser Version: ? [e.g. Chrome 71.0]
 - OS: ? [e.g. Mac OS X 10.4]

**Comment by bclinkinbeard** [comment]
Confirmed this happens with deck.gl 7.1.5, 7.1.9, and 7.2.4
Chrome 77.0.3865.90 on macOS 10.14.6

**Comment by Pessimistress** [comment]
I am unable to reproduce this: https://codepen.io/Pessimistress/pen/yLBZejL

Can you share the props with which you are using the layer?

**Comment by bclinkinbeard** [comment]
The random coloring only happens when I update my `minTime` and `maxTime` uniforms. It will then disappear the next time a "normal" render is triggered by mouse interaction or moving the map. My long list of layer props are below, and `pickable: true` is the only one that seems to cause this behavior.

```
const layerProps: ScatterplotLayerProps = {
  id: this.layerId,
  data: this.data,
  visible: this.visible,
  instancePositions: this.positions,
  instanceTimestamps: this.instanceTimestamps,
  instancePositions64xyLow: this.instancePositions64xyLow,
  getFillColor: this.getFillColor,
  onHover: (event: any) => {  // tslint:disable-line:no-any
    if (event.index < 0) {
      this.onHover(event);
      return;
    }
    this.onHover(
        event,
        service.timeSortTable(this.table!).get(event.index),
    );
  },
  minTime: -Number.MAX_SAFE_INTEGER,
  maxTime: Number.MAX_SAFE_INTEGER,
  getLineColor: this.getLineColor,
  lineWidthMinPixels: this.lineWidth || 1,
  lineWidthMaxPixels: this.lineWidth || 8,
  stroked: this.stroked,
  autoHighlight: true,
  pickable: true,
  highlightColor: [0, 255, 0],
  getRadius: this.getRadius,
  radiusMinPixels: this.pixelRadius || 0,
  radiusMaxPixels: this.pixelRadius || 5e3,
  radiusScale: this.pixelRadius ? 1 : 2 ** (15 - this.fractionalZoom),
};
```

**Comment by bclinkinbeard** [comment]
It looks like I've tracked my problem down to calling `draw()` directly on a layer, instead of triggering a redraw via the proper lifecycle methods. Weird manifestation, but my bad. :)
