### ISSUE TITLE
Choropleth layer doesn't support fill colors

### ISSUE THREAD

**Issue by chrisirhc** [uber/deck.gl#37]
![image](https://cloud.githubusercontent.com/assets/132584/15982877/bd3de348-2f49-11e6-8bcf-2b231c5172fc.png)
(image from react-map-gl)

**Comment by vicapow** [comment]
@chrisirhc Rementioning this here since it might be useful for others but if you're looking for a more performant workaround, this effect can be achieved in MapboxGL via data driven styles. see: https://www.mapbox.com/blog/data-driven-fill-color/

**Comment by chrisirhc** [comment]
Gotcha. Yep, that's a good solution if we didn't need deck.gl's layering capabilities or interactivity.

**Comment by vicapow** [comment]
Not sure what your needs are exactly, but react-map-gl / MapboxGL supports interactivity. If there's some other feature of DeckGL you still need, you could just create a new map and put it on top.

**Comment by mcnuttandrew** [comment]
@chrisirhc this should be fixed after https://github.com/uber/deck.gl/commit/bb648172de1722fd61656984f77cd4f27968ae03 ?

**Comment by gnavvy** [comment]
@mcnuttandrew Yes, was thinking to add an example before closing this one.
