### ISSUE TITLE
Picking a 3D point

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#3719]
#### Target Use case

In some editing use cases (nebula.gl, avs.auto), users need to select a 3D position on a path or surface.

Currently, `pickingInfo.coordinate` is produced by unprojecting the 2D screen position onto the ground (Z=0). When working with extruded or floating geometries, the result will not be on the picked object.

#### Proposed feature

`pickingInfo.coordinate` should be a point that is actually on the picked geometry.

#### To Do List 
  - [x] Add label and assign to milestone
  - [ ] (mini) RFC
  - [x] Coding
  - [x] Doc update
  - [ ] What’s new update
  - [ ] Test

**Comment by jay-manday** [comment]
How can i utilize this awesome feature? I'm working on a app where I'm loading a 3D model of a steel structure and utilizing the point-cloud-layer to pick reference points for an industrial robotic assembly line and being able to derive the `z` coordinate is a critical component of the module that i'm working on.

For reference here's my layer definition:

```
  const pointLayer = s => new PointCloudLayer({
    id: 'point-cloud-layer',
    data: s.points,
    coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
    numInstances: s.pointsCount,
    instancePositions: s.points,
    getColor: [255, 255, 255],
    getNormal: [0, 1, 0],
    pointSize: 2.5,
    opacity: 0.5,
    onClick: (s) => console.log(s)
  })
  

```

**Comment by ibgreen** [comment]
@jay-manday I believe this feature is only available in alpha releases. If you need it today, you can try `7.4.0-alpha.2`, it should be relatively stable/similar to v7.3 as not that many features from our next release have landed yet.

**Comment by jay-manday** [comment]
Thanks @ibgreen ! definitely will try that alpha release out :)

**Comment by jay-manday** [comment]
Hi @ibgreen, I'm using the release you suggested above `7.4.0-alpha.2`, and things are stable, however when i use the `onClick` method it still returns the following:

```
{
color: Uint8Array(4) [119, 65, 1, 2]
coordinate: (2) [-1.8511185572271995, -138.25794343693855]
devicePixel: (2) [1265, 617]
index: 82294
layer: PointCloudLayer {props: {…}, id: "point-cloud-layer", count: 222, lifecycle: "Discarded. Awaiting garbage collection", parent: null, …}
lngLat: (2) [-1.8511185572271995, -138.25794343693855]
picked: true
pixel: (2) [632, 637]
pixelRatio: 2
x: 632
y: 637
}
```


My layer definition is:

```
 const pointLayer = s => new PointCloudLayer({
      id: "point-cloud-layer",
      data: s.points,
      coordinateSystem: COORDINATE_SYSTEM.IDENTITY,
      numInstances: s.pointsCount,
      instancePositions: s.points,
      getColor: [255, 255, 255],
      getNormal: [0, 1, 0],
      pointSize: 2.5,
      opacity: 0.5,
      pickable: true,
      onClick: s => console.log(s)
    });

```

Thank you again for the help!

**Comment by ibgreen** [comment]
@jay-manday Haven't used this feature myself yet, but I believe you may need to will need pass in an additional parameter to picking function:

See https://github.com/uber/deck.gl/blob/master/docs/api-reference/deck.md#pickobject

Until we make it possible for you to control this parameter, you may need to call picking function yourself:

```
onClick: this._onClick.bind(this),

_onClick() {
 const {deck} = this.context.deck;
 deck.pickObject({..., unproject3D: true});
}
```
