### ISSUE TITLE
LineLayer onHover called with wrong index or not called at all.

### ISSUE THREAD

**Issue by bbss** [uber/deck.gl#3722]
#### Description
We are tracking flights in our deck.gl app by using the LineLayer, and for some paths the hover handler seems to sometimes have the wrong index (and thus also a wrong object). 
In doing real-time flights we pass a new array every update, however sometimes the onHover gets called with a really high index. More rarely a hover handler will not get called at all.

#### Repro Steps
It's been hard to find out what is causing it, so making a repro case is hard. Of note is that I've found a way to hack around the issue by changing the id of the layer whenever the index is over 10.000. That will often fix the issue, and subsequent hovers will have the correct index.
e.g.

onHover index: 10030133 -> updating layer id
onHover index 78 -> correct index/object subsequently

However sometimes the index will be wrong even though its index is below 10.000 so it's not a good solution.

#### Environment:
 - Framework Version: deck.gl 7.2.2
 - Browser Version: Chrome 77.0
 - OS: Mac OS X Catalina

#### Logs
I have noticed one of the layers we're extending hasn't properly updated the shader yet so we do get a warning that might be related:
luma: `project_pixel_to_clipspace` has been removed. Use `project_pixel_size_to_clipspace` instead

~~I will fix that and will update this issue if that changes the situation.~~
However this is for our layer extending the PointCloudLayer, which is not having any issues.

**Comment by Pessimistress** [comment]
We fixed a bug in picking recently. Try 7.2.6.
