### ISSUE TITLE
Weird rendering of scatterplot, not align with map 

### ISSUE THREAD

**Issue by wkm97** [uber/deck.gl#3748]
Anyone have any idea why the points are not align with the map?

![image](https://user-images.githubusercontent.com/31875755/66222725-66144280-e704-11e9-85b8-802b270177ca.png)

This is the message from the console:
![image](https://user-images.githubusercontent.com/31875755/66222847-a70c5700-e704-11e9-9e45-d0f237aadd79.png)

**Comment by Pessimistress** [comment]
Which version are you using? Can you try 7.3.2 and 7.2.6?

**Comment by wkm97** [comment]
New version work like magic. Thank you!
