### ISSUE TITLE
Postprocessing effect affecting or hiding Static Map

### ISSUE THREAD

**Issue by maldo-ctrl** [uber/deck.gl#3753]
#### Description
Hello everybody,

I m tryng to implement add a [PostProcessEffect](https://deck.gl/#/documentation/deckgl-api-reference/effects/post-process-effect) to the Deck.gl layers of a mapBox Static Map and I am having an issue: the Postprecessing is hiding the Static Map behind the layers.

#### Repro Steps

This is my code:

`import { brightnessContrast, ink } from '@luma.gl/effects';
import { PostProcessEffect } from '@deck.gl/core';`

`const postProcessEffect = new PostProcessEffect(brightnessContrast, {
            brightness: 0.5,
            contrast: 0.5
        });`

 `<div style={{ height: windowSize[0], width: windowSize[1], position: 'absolute' }}>

                    <DeckGL
                        viewState={viewState}
                        controller={MapController}
                        layers={this._renderLayers()}
                        onViewStateChange={this._onViewStateChange}
                        ref={ref => {
                            this._deck = ref && ref.deck;
                        }}
                        effects={[postProcessEffect]}
                        onWebGLInitialized={this._onWebGLInitialized}
                    >
                        {gl && (
                            <StaticMap
                                ref={ref => {
                                    this._map = ref && ref.getMap();
                                }}
                                gl={gl}
                                mapStyle="mapbox://styles/mapbox/light-v9"
                                mapboxApiAccessToken={MAPBOX_ACCESS_TOKEN}
                                onLoad={this._onMapLoad}
                            />
                        )}
                    </DeckGL>
                </div>`

#### Environment (please complete the following information):
Some of my dependencies version:

 "@luma.gl/effects": "^7.3.1"
 "deck.gl": "^7.3.2"
 "react": "^16.9.0"

#### Logs

Here is a screenshot of the problem:

![problem](https://user-images.githubusercontent.com/53186719/66309402-d8a23f80-e909-11e9-847f-5ea3c368b508.png)

**Comment by 1chandu** [comment]
[effects](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=effects-array-) prop is an Array not an Object, can fix this and re-try, also, are there any errors/warnings in your browser console.

**Comment by maldo-ctrl** [comment]
Hi, 

Finally I removed the webgl shared context from the Static Map and it solved the problem:
`//gl={gl}`
