### ISSUE TITLE
TypeError: can't define property "default-view": Object is not extensible

### ISSUE THREAD

**Issue by daaain** [uber/deck.gl#3773]
#### Description

After updating several libraries in the project I'm working on, I started to get a runtime error from deck.gl as soon as trying to interact with the map:

```
TypeError: can't define property "default-view": Object is not extensible
```

The error points to this line: https://github.com/uber/deck.gl/blob/master/modules/core/src/lib/deck.js#L719

I'm guessing it might be new React behaviour which is not supported? I'm trying to make things work with the (currently) latest `16.10.2`.

Also using `react-map-gl` if that helps, though the stack trace seems to only touch components of deck.gl.

#### Repro Steps

Ours is a fairly complex app, but if you have a sample setup to build on in Codepen or something I can try to create a simple repro.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.1.11
 - Browser Version: breaks both with Firefox Developer and Chrome Canary
 - OS: MacOS 10.14.6

#### Logs

```
deck.js:711 Uncaught TypeError: Cannot add property default-view, object is not extensible
    at Deck._onViewStateChange (deck.js:711)
    at ViewManager._onViewStateChange (view-manager.js:241)
    at MapController.updateViewport (controller.js:223)
    at MapController._onWheel (controller.js:339)
    at MapController.handleEvent (controller.js:82)
    at EventRegistrar._emit (event-registrar.js:108)
    at EventRegistrar.handleEvent (event-registrar.js:82)
    at Manager.emit (hammer.js:2519)
    at EventManager._onOtherEvent (event-manager.js:295)
    at WheelInput._onWheel (wheel-input.js:87)
    at WheelInput.handleEvent (wheel-input.js:82)
```

**Comment by 1chandu** [comment]
> Ours is a fairly complex app, but if you have a sample setup to build on in Codepen or something I can try to create a simple repro.

You can clone one of the code.pen demos : [link](https://deck.gl/#/documentation/getting-started/learning-resources)

**Comment by daaain** [comment]
OK, I figured out what was the problem: passing a `WebMercatorViewport` class instance as `initialViewState`, which was then set as `this.viewState`: https://github.com/uber/deck.gl/blob/5af228714038f644ca936f966474483a6c64c162/modules/core/src/lib/deck.js#L147

Spreading the viewport object solved the issue, ie `initialViewState={{ ...viewport }}`

Not sure if it's something you might want to fix / work around in the library code so will leave you to close the issue or leave it open.

**Comment by Pessimistress** [comment]
`initialViewState`/`viewState` are expected to be plain objects, not viewport instances.
