### ISSUE TITLE
HeatmapLayer cann't be cancel

### ISSUE THREAD

**Issue by HeiYanjing** [uber/deck.gl#3778]
"@deck.gl/aggregation-layers":"^7.3.2",
    "@deck.gl/core": "^7.1.7",
    "@deck.gl/geo-layers": "^7.1.7",
    "@deck.gl/layers": "^7.1.7",
    "@deck.gl/mapbox": "^7.1.10",
    "@deck.gl/mesh-layers": "^7.3.2",
    "@deck.gl/react": "^7.1.7",

      new HeatmapLayer({
        id: 'heatmapLayer',
        data :heatmapData,
        getPosition: d => [d.COORDINATES[0],d.COORDINATES[1],d.COORDINATES[2]],
        getWeight: d => d.WEIGHT
      }),

 [HeatmapLayer example](https://deck.gl/#/documentation/deckgl-api-reference/layers/heatmap-layer), For this example.
first question, I add height value in coordinate array ,it doesn't work. 
second ,In my project ,I used many layers ,like Iconlayer,geosjsonLayer and so on .
but when I use HeatmapLayer ,after I set the value for   `heatmapData` ,I can see the heatmapLayer
![image](https://user-images.githubusercontent.com/42837853/66703109-a184c180-ed41-11e9-87e2-35a5b6cd5d6a.png)

but not matter what I  set  `heatmapData` to be  `null`.  the heatmap always show in map

**Comment by 1chandu** [comment]
@HeiYanjing  thanks for reporting it, I was able to reproduce the problem and working on the fix.
Will update here once a new patch is published with the fix. Meanwhile you can use `visible` prop (set it to false) as a workaround.

**Comment by HeiYanjing** [comment]
> @HeiYanjing thanks for reporting it, I was able to reproduce the problem and working on the fix.
> Will update here once a new patch is published with the fix. Meanwhile you can use `visible` prop (set it to false) as a workaround.

thank you for your reply.
I use `visible` prop  resolve it

**Comment by 1chandu** [comment]
Should get resolved in deck.gl 7.3.3, please reopen if you not.
