### ISSUE TITLE
all deck Layer did not show in Deck

### ISSUE THREAD

**Issue by ErichChen** [uber/deck.gl#3779]
#### Description

        2. if hide the map style code ,the layers can be show 
        3 ,so how can i both show the map and ScatterplotLayer
#### codes ,you can just run it 
<html>
  <head>
    <title>deck.gl HexagonLayer Example</title>

    <script src="https://unpkg.com/deck.gl@^7.0.0/dist.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>

    <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js"></script>

    <style type="text/css">
      body {
        font-family: Helvetica, Arial, sans-serif;
        width: 100vw;
        height: 100vh;
        margin: 0;
      }

      #map {
        position: absolute;
        top: 0;
        left: 0;
        height:800px;
		width:1500px
      }

      label {
        display: inline-block;
        width: 140px;
      }
    </style>
  </head>

  <body>

	<div id='map'></div>
  </body>

  <script type="text/javascript">
mapboxgl.accessToken ='pk.eyJ1IjoiY2hlbmZ1Z3VpIiwiYSI6ImNrMW5tN2VjOTBieXYzZHFrc3M0eTN0dWcifQ.XpqsPu6-scvo1L0qzq5X3A';
  const map = new mapboxgl.Map({
   
    container: 'map',
    //style: 'mapbox://styles/mapbox/streets-v11',
center: [75.4157, 39.2324],
    zoom: 6,

  });
//map.setStyle('mapbox://styles/mapbox/dark-v10' );
    function setTooltip(info){
    if(info.object){
      console.log("scat:",info.object.message)
    }
   

  }
const deck = new Deck({
   gl: map.painter.context.gl,
  initialViewState: {longitude: -122.45, latitude: 37.78, zoom: 12},
  controller: true,
  layers: [
    new ScatterplotLayer({
      data: [
        {position: [-122.415, 37.78], message: 'Hover over me1'},
 {position: [-122.425, 37.78], message: 'Hover over me2'},
 {position: [-122.435, 37.78], message: 'Hover over me3'},
 {position: [-122.445, 37.78], message: 'Hover over me4'}23:23 2019/10/12
      ],
      getPosition: d => d.position,
      getRadius: 300,
      getFillColor: [255, 255, 0],
      // Enable picking
      pickable: true,
      // Update tooltip
      onHover: info => setTooltip(info)
    })
  ]
});
    
	 map.on('load', () => {
	 
          
          
              
          
          
          
          
           
          
           
    
  
      
	   
      
  
	  
      
        
      
    
     

  }
  )
  </script>
</html>

**Comment by ErichChen** [comment]
i do not want use deckgl ,because that binding react

**Comment by ibgreen** [comment]
> i do not want use deckgl ,because that binding react

I am not sure I understand... Are you saying you don't want to use deck.gl because deck.gl requires React? 

That is not true: deck.gl is a pure JavaScript API with *optional* React bindings. 

If you import `https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js` instead of `https://unpkg.com/deck.gl@7.0.0/dist.min.js` you will get the JS version of the API. 

You will need to import a few additional scripts to get the layers etc. If you look at the [Submodule API Reference](https://deck.gl/#/documentation/submodule-api-reference/deckgl-extensions/overview) there is a script for each module.

**Comment by ErichChen** [comment]
thanks for you letter


&nbsp;at first ,i tried you suggestion,but&nbsp;









in the all,i want to add some layer and use the onHover event,i made pickable=true,while,it did not work ,even the layer did not show


like the demo&nbsp;&nbsp;&nbsp;https://deck.gl/#/documentation/deckgl-api-reference/layers/hexagon-layer



demos used the “new Deckgl()"&nbsp;&nbsp;


whlie,i did not learned react, so i choosed the demo like&nbsp;https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/mapbox-layer?section=use-a-layer-from-an-existing-deck-s-layer-stack
and i try to make it work ,like the Enclosure ”deck.html“&nbsp;





i really do not know what is wrong&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ib Green"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月13日(星期天) 凌晨1:30
收件人:&nbsp;"uber/deck.gl"<deck.gl@noreply.github.com&gt;;
抄送:&nbsp;"陈月月"<342930647@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [uber/deck.gl] all deck Layer did not show in Deck (#3779)



 
i do not want use deckgl ,because that binding react
  
I am not sure I understand... Are you saying you don't want to use deck.gl because deck.gl requires React?
 
That is not true: deck.gl is a pure JavaScript API with optional React bindings.
 
If you import https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js instead of https://unpkg.com/deck.gl@7.0.0/dist.min.js you will get the JS version of the API.
 
You will need to import a few additional scripts to get the layers etc. If you look at the Submodule API Reference there is a script for each module.

**Comment by ErichChen** [comment]
excumes me ,i have another quesion


the onHover event in this demo didnot work too ,that i missed?&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ib Green"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月13日(星期天) 凌晨1:30
收件人:&nbsp;"uber/deck.gl"<deck.gl@noreply.github.com&gt;;
抄送:&nbsp;"陈月月"<342930647@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [uber/deck.gl] all deck Layer did not show in Deck (#3779)



 
i do not want use deckgl ,because that binding react
  
I am not sure I understand... Are you saying you don't want to use deck.gl because deck.gl requires React?
 
That is not true: deck.gl is a pure JavaScript API with optional React bindings.
 
If you import https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js instead of https://unpkg.com/deck.gl@7.0.0/dist.min.js you will get the JS version of the API.
 
You will need to import a few additional scripts to get the layers etc. If you look at the Submodule API Reference there is a script for each module.

**Comment by ErichChen** [comment]
> > i do not want use deckgl ,because that binding react
> 
> I am not sure I understand... Are you saying you don't want to use deck.gl because deck.gl requires React?
> 
> That is not true: deck.gl is a pure JavaScript API with **optional** React bindings.
> 
> If you import `https://unpkg.com/@deck.gl/core@7.0.0/dist.min.js` instead of `https://unpkg.com/deck.gl@7.0.0/dist.min.js` you will get the JS version of the API.
> 
> You will need to import a few additional scripts to get the layers etc. If you look at the [Submodule API Reference](https://deck.gl/#/documentation/submodule-api-reference/deckgl-extensions/overview) there is a script for each module.

i mean the differences【new  Deck】 object between【new Deckgl】 object ，when i
make mapbox and deck together，onhover did not  work even  did not show
