### ISSUE TITLE
website examples data format?

### ISSUE THREAD

**Issue by serdaroquai** [uber/deck.gl#3780]
Hi, what is the binary format used for the [examples with 858.4K  scatterplot-data](https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/scatterplot-data.txt)?

To add some more context: I am trying to compare performance aspects between various options of using large binary data, and would love to learn about the format deck.gl website examples use, how this format is converted into layer data etc.

**Comment by serdaroquai** [comment]
no love? :(

**Comment by ibgreen** [comment]
@serdaroquai The compression system used for those examples was a hack done as part of the early deck.gl 3.0 release almost three years ago to ensure the website would load on mobile. It is part of the `website` code in deck and was never intended to be used by apps. 

We haven't touched this for a long time and it would require some research on our side to refresh ourselves on the details, not sure it is worth it.

In addition, while we haven't really discussed and agreed on this yet, my take is that with the next-gen binary support planned for v8.0, we should phase out this compression scheme completely in our next major release, further reducing our appetitive for digging into this now.

If you keep poking into the website folder and the worker code there and get a bit further have more specific questions feel free to ask again, perhaps we could answer them with less effort on our side.
