### ISSUE TITLE
when map renders ,why it makes my ScatterplotLayer under the map? is  affected by the z-index?

### ISSUE THREAD

**Issue by ErichChen** [uber/deck.gl#3781]
<html>
  <head>
    <title>deck.gl HexagonLayer Example</title>
<script src="https://unpkg.com/deck.gl@^7.0.0/dist.min.js"></script>

<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js"></script>

<style type="text/css">
  body {
    font-family: Helvetica, Arial, sans-serif;
    width: 100vw;
    height: 100vh;
    margin: 0;
  }

  #map {
    position: absolute;
    top: 0;
    left: 0;
    height:800px;
	width:1500px
  }

  label {
    display: inline-block;
    width: 140px;
  }
</style>
<div id='map'></div>
<script type="text/javascript"> 
mapboxgl.accessToken ='pk.eyJ1IjoiY2hlbmZ1Z3VpIiwiYSI6ImNrMW5tN2VjOTBieXYzZHFrc3M0eTN0dWcifQ.XpqsPu6-scvo1L0qzq5X3A'; const map = new mapboxgl.Map({ 
container: 'map',
 //style: 'mapbox://styles/mapbox/streets-v11',
 center: [75.4157, 39.2324], 
 zoom: 6, 
 });

 map.setStyle('mapbox://styles/mapbox/dark-v10' );
 function setTooltip(info){ 
 if(info.object){ 
 console.log("scat:",info.object.message) } 
 } 
 const deck = new Deck({
 gl: map.painter.context.gl,
 initialViewState: {longitude: -122.45, latitude: 37.78, zoom: 12}, 
 controller: true,
 layers: [ new ScatterplotLayer({ 
 data: [ {position: [-122.415, 37.78], message: 'Hover over me1'}, 
 {position: [-122.425, 37.78], message: 'Hover over me2'}, 
 {position: [-122.435, 37.78], message: 'Hover over me3'}, 
 {position: [-122.445, 37.78], message: 'Hover over me4'} ], 
 getPosition: d => d.position,
 getRadius: 300, 
 getFillColor: [255, 255, 0], 
   // Enable picking
 pickable: true,
      // Update tooltip
 onHover: info => setTooltip(info)
 }) ] 
 }); 
 map.on('load', () => { 
 
 
 } ) </script>
</html>

**Comment by ErichChen** [comment]
this is the problem code that you can click just run it
https://jsfiddle.net/y2du3ef4/

**Comment by 1chandu** [comment]
@ErichChen , you are giving mapboxe's gl context to deck.gl this may not work this way.

If you need to interleave your 3d content with mapbox layers you should use deck.gl's [MapboxLayer](https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview)

But if you only want to use mapbox as a base map, you can follow any of our standard examples, like this [one](https://github.com/uber/deck.gl/blob/d5b5d5c3515f80a25f72633e7813fb21cc7a8233/examples/website/scatterplot/app.js#L50).

**Comment by ErichChen** [comment]
> @ErichChen , you are giving mapboxe's gl context to deck.gl this may not work this way.
> 
> If you need to interleave your 3d content with mapbox layers you should use deck.gl's [MapboxLayer](https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview)
> 
> But if you only want to use mapbox as a base map, you can follow any of our standard examples, like this [one](https://github.com/uber/deck.gl/blob/d5b5d5c3515f80a25f72633e7813fb21cc7a8233/examples/website/scatterplot/app.js#L50).


thanks  for your replay
you are right,i want to use mapbox as a base map ,and i need   to interleave  3d content, but i do not use any react ,you can see the demo  below  ,i add onhover ,it did not work 
![1](https://user-images.githubusercontent.com/21305978/66793474-28978c80-ef30-11e9-9045-1211e2105822.png)

https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/mapbox-layer?section=use-a-layer-from-an-existing-deck-s-layer-stack
