### ISSUE TITLE
diference in delay between onClick and onHover 

### ISSUE THREAD

**Issue by YuriDem** [uber/deck.gl#3783]
I see that the onClick event has a delay, and onHover event is much faster.  
i see th same issues #2683 .. but people ask to show the code, when the problem is visible on the site in exames https://deck.gl/#/examples/core-layers/icon-layer

handle onHover and onClick have the same atributes, but onClick has delay ~200ms

maybe someone faced this problem ? 
I know the way to use onHover to manage variable to state and set onClick on the map ... but

**Comment by 1chandu** [comment]
All events are processed through `EventManager` from `mjolnir.js` module.

How is `~200ms` is measured?

Also it is possible that a `mouse click` event detection takes longer when compared to `moues move` ??

**Comment by Pessimistress** [comment]
`onClick` has a small delay so that the event doesn't fire when double clicking. What is your use case?

**Comment by YuriDem** [comment]
> `onClick` has a small delay so that the event doesn't fire when double clicking. What is your use case?

Thanks for the answer, for instance I want to show popup or create pin ... doesn't matter, is there a way to get rid of this delay ?

**Comment by Pessimistress** [comment]
You can disable double click by setting `controller: {doubleClickZoom: false}`

**Comment by jimvermillion** [comment]
Thanks @Pessimistress, that took care of it for me

**Comment by diehl** [comment]
@Pessimistress This thread just helped me resolve the click delay mystery I was seeing with a PyDeck visualization. I was able to figure out how to specify the controller in a PyDeck viz built with a JSON spec but I've not yet figured out how to make this assertion in a PyDeck viz specified in pure Python. Wondering if you can point me in the right direction...
