### ISSUE TITLE
Polygon layer, only one polygon is rendered.

### ISSUE THREAD

**Issue by wkm97** [uber/deck.gl#3805]
#### Description
I am trying to create an onclick event where it will add polygon on map, but only the first polygon is rendered.
![image](https://user-images.githubusercontent.com/31875755/67183113-458dfd00-f413-11e9-9e77-868cfe6bd61a.png)

The data for both pins are inside, not sure why it is not working:
![image](https://user-images.githubusercontent.com/31875755/67183399-f5636a80-f413-11e9-9b0a-33ac43d97073.png)

#### Environment (please complete the following information):
 - Framework Version:  deck.gl 7.3.3
 - Browser Version: Chrome Version 77.0.3865.120
 - OS: Win 10 Ver. 1809

#### Logs
No errors has occurred

**Comment by jianhuang01** [comment]
Can you create a deck.gl polygon example with the data fed in? If that doesn't work, just link your example here, so we can help. It is hard to know what is going on there with a screenshot.

**Comment by ibgreen** [comment]
@wkm97 Have you confirmed this is an issues with only one polygon being displayed, as opposed to one of the polygons being malformatted?

A possible test: If you delete the first polygon, does the second polygon start showing (or vice versa)? If not your data for the non-visible polygon is probably bad (or the coordinates are just outside of the screen).

One thing we would like to do is provide better validation for geojson and polygon data, so if you pin point where things went wrong, let us know and maybe we could emit a warning message...

**Comment by wkm97** [comment]
This is how it look like:
![chrome-capture-1](https://user-images.githubusercontent.com/31875755/67264403-94a06480-f4dd-11e9-8e4d-e17e905da858.gif)

But when I re-render the polygon layer every time the number of pins is even number, it works:
![chrome-capture-2](https://user-images.githubusercontent.com/31875755/67264556-f791fb80-f4dd-11e9-8b4f-a2e94b5635ba.gif)

For the test, after i remove the first polygon and insert a new one, it works too:
![chrome-capture](https://user-images.githubusercontent.com/31875755/67264624-3aec6a00-f4de-11e9-9173-0a6cf386127c.gif)

**Comment by wkm97** [comment]
Multipolygon able to done using GeoJsonLayer.
