### ISSUE TITLE
Deck.gl crashes when there are multiple heatmap layers

### ISSUE THREAD

**Issue by SterlingMcCall** [uber/deck.gl#3812]
#### Description
I would expect multiple heatmap layers to work together as any other layer would work with multiples. However, adding multiple heatmap layers results in deck.gl crashing with an error in the console.

#### Repro Steps
Here is a minimal example of the bug: https://codepen.io/sterlingmccall/pen/bGGrYWp

The map will initially seem to have loaded correctly, but when zooming in or out or panning the map, the error will eventually be thrown and the map will become unresponsive. This usually takes 10 to 20 seconds of playing with the map, but sometimes more quickly.

#### Environment (please complete the following information):
 - Framework Version: tested with deck.gl 7.3.2 and 7.3.3, as well as both Google maps and Mapbox
 - Browser Version: Chrome 78, Firefox 70
 - OS: ubuntu 18.04
 
#### Logs
```
deck: Multiple old layers with same id TriangleLayer({id: 'heatmap-triangle-layer'}) 

Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

deck: error while initializing TriangleLayer({id: 'heatmap-triangle-layer'})
 Error: "deck.gl: assertion failed.
    at r (dist.min.js:1)
    at e.value (dist.min.js:1)
    at e.value (dist.min.js:1)
    at t.value (dist.min.js:6)
    at t.value (dist.min.js:6)
    at t.value (dist.min.js:6)
    at t.value (dist.min.js:6)
    at t.value (dist.min.js:6)
    at t.value (dist.min.js:6)
    at o.value (dist.min.js:6)
```

**Comment by 1chandu** [comment]
Looking ...

**Comment by 1chandu** [comment]
@SterlingMcCall ,  fixed in deck.gl 7.3.4.
