### ISSUE TITLE
Controller: handleEvent does not trigger for additional subscribed events

### ISSUE THREAD

**Issue by arp82** [uber/deck.gl#3822]
#### Description
When trying to create a custom map controller and subscribing to additional events by modifying the controller's `events` property (such as 'click' or 'mouseover'), the `handleEvent` method does not seem to trigger for the aforementioned events

#### Repro Steps
You can find the issue reproduced in the codesandbox below (mapbox token is not provided in the sample)
https://codesandbox.io/s/reverent-fire-c4tdk

Basically, the above codesandbox takes the basic example from deck.gl documentation with a slight modification to add a custom map controller which should be subscribing to pretty much every event. Then, the `handleEvent` method is overridden to write the event type captured in the console. Default events such as 'wheel' or 'panout' are successfully logged in the console, but others such as 'click' or 'mouseover' are not.

#### Environment:
 - Framework Version:  deck.gl 7.3.3, react-map-gl 5.0.12
 - Browser Version: Chrome 76.0.3809.132
 - OS: Windows 10

Thanks in advance for your time and effort!

**Comment by Pessimistress** [comment]
Try 7.3.5

**Comment by arp82** [comment]
After testing it, I have not been able to reproduce the issue and the controller has been recognizing events as intended.

Thanks a lot for the effort! I'm closing the issue.
