### ISSUE TITLE
IconLayer with auto packing atlas showing wrong icon

### ISSUE THREAD

**Issue by ruizmarc** [uber/deck.gl#3834]
#### Description

We are using IconLayer to represent live data with auto packing atlas (we generate a few hundred different icons depending on the data we receive). Everytime we receive an event with updated data, we set props with an updated layer and we get the changes represented in the map. 

We are identifying every different icon with a uniqued ID. 

We have noticed that sometimes (we haven't found a reproducible pattern, but it happens frequently), although we are using the correct identifier for the icon, a different icon than the provided is being used. It seems like the atlas is not properly mapped or the wrong icon is being reused.

#### Repro Steps

Problem can be reproduced with any browser. The first drawing seems always fine, but icons start showing wrong pictures after updating data. It is not happing with all icons drawn, but just for a few of them. 

We haven't found a reproducible pattern, but it seems it happens more frecuently when a few dozens of unique icons have been created. 

We update the layer info, using set props like this:

`
this.overlay.setProps({ layers: [
      clustersLayer.clone({ data: clustersData })
]}); 
`

This is how we generated the IconLayer:

```
    const clusterSize = 124;
    return new IconLayer({
      id: 'icon-cluster',
      data,
      getPosition: (c: Cluster) => [c.centerLon, c.centerLat],
      opacity: 1,
      getIcon: (c: Cluster) => ({
        id: this.generateClusterIconId(c),
        url: `data:image/svg+xml;base64,${ btoa(this.generateClusterIconUrl(c, clusterSize)) }`,
        width: clusterSize,
        height: clusterSize
      }),
      sizeScale: .625,
      getSize: clusterSize,
      alphaCutoff: 0,
      pickable: true,
      onClick: ({ object: c }: { object: Cluster }) => {
        this.clusterClicked = c.geohash;
        if (this.getZoom() >= MAX_ZOOM) { // If cluster cannot longer be zoomed in
          this.changeToList.emit();
        } else {
          this.map.fitBounds({
            east: c.maxLon,
            north: c.maxLat,
            south: c.minLat,
            west: c.minLon
          });
        }
      },
    });

```

The amount of data entries may change depending on the bounds of the map in the screen and the events we receive, so we don't always have the same length of data (pointing this out, just in case it is relevant).

#### Environment (please complete the following information):
 - Framework Version: 7.3.3
 - Browser Version: Safari 13.0.3
 - OS: Mac OS Catalina 10.15.1

**Comment by Pessimistress** [comment]
Try 7.3.5

**Comment by ruizmarc** [comment]
It works great now! It always shows the proper icon :)

Thanks for your quick solution!
