### ISSUE TITLE
TripsLayer: Load tiled data

### ISSUE THREAD

**Issue by mrieser** [uber/deck.gl#3837]
#### Target Use case

Currently, TripsLayer typically loads a static data set containing the trips to visualize. For very large datasets, it's not feasible to load all data at once. A workaround in this case is to modify the URL in the data property to be dependent on the view-extent, such that always only the data for the current view is loaded. But this might still transfer the same data multiple times if the view is moved just a little. This is the reason why modern maps use tiles, so they only have to load a few additional tiles around the border when the view gets moved. And they use tiles adapted to the current zoom level.
Having a way to load trips also tile-by-tile could help to minimize the amount of data to be loaded when the view is moved, and it would allow for (server-side) filtering and pre-processing of the trips depending on the zoom-level of the map to further optimize the visualized data. 

#### Proposed feature

TripsLayer should offer a way to load trips-data according to current tile-numbering schemas (e.g. `some-url/${zoom}/${x}/${y}.json`), similar like other vector or raster tiles are loaded for base maps.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
@mrieser have you tried using the `TileLayer` with the `TripsLayer`?

**Comment by mrieser** [comment]
Thanks for the hint about `TileLayer`. I wasn't aware that it can be combined with `TripsLayer`. I'll definitely give it a try!
