### ISSUE TITLE
How can I know when a layer has finished loading? 

### ISSUE THREAD

**Issue by HHammerite** [uber/deck.gl#3843]
I was hoping to find a way to know when a layer has been loaded. I'm working with large data sources which take 5-10 seconds to appear on the map. Is there a way, maybe a callback, to know when a layer has been finally added to the map?

Thanks :)

**Comment by Pessimistress** [comment]
If you are using a url for the `data` prop, the layer calls its `onDataLoad` prop when the data is fully downloaded.

If you want to know when the layer is rendered to screen, you can listen to Deck’s `onAfterRender`.

**Comment by gireeshbhogireddy** [comment]
I am unable to trigger onDataLoad property of MVTLayer when the data is fully loaded, codebase is in below URL:
https://codepen.io/gireesh-bhogireddy/pen/LYqoMoV?editors=0011
Please let me know whats going wrong here.
 
 thanks
