### ISSUE TITLE
Insert a flat icon on map

### ISSUE THREAD

**Issue by JorundMartinsen** [uber/deck.gl#3858]
Hi. I'm using this library to display the location of vessels and their current heading.

My vessel icon is svg, and i've implemented it by using the SVGOverlay. However, the heading is not preseved when rotating the map, and position is changed when tilting the map.
I tested the IconLayer as well, but same result.

With the SimpleMeshLayer, bearing and position is preserved, however size changes on zoom.

Desired behavior:
'Flat' icon on the map, preserving the bearing, position and size, similar to the directions from google maps.

How to do this?

**Comment by Pessimistress** [comment]
You can try setting the `billboard: false` prop on your `IconLayer`.

**Comment by JorundMartinsen** [comment]
Yes, of course. Thank you
