### ISSUE TITLE
Custom pointcloud layer with overlapping attributes

### ISSUE THREAD

**Issue by MGraefe** [uber/deck.gl#3860]
Hi, I am currently creating a custom pointcloud layer which should support vastly different input vertex formats. Generally all of these formats are of the overlapping type, so I have only one input buffer with position, color informations etc. Currently I am not rendering instanced data.

I am currently using the attributer manage to dynamically specify my x, y, z etc. attributes and in the `draw` function of the layer I draw a luma.gl Model:

```javascript
  calculatePositions(attribute) {
    console.log('calculatePositions');
    const {data} = this.props;
    attribute.update({value: data});
  }

  initializeState() {
    this.getAttributeManager().add({
      x: {
        size: 1,
        type: GL.FLOAT,
        fp64: false,
        offset: 0,
        stride: 12,
        divisor: 0,
        noAlloc: true,
        update: this.calculatePositions,
      },
      // similar for y and z, just different offsets
    });
```

I need to specify the individual componets (x,y,z etc.) because they might not be sequential when I move to real data.

The Model is created (only when the input cloud changes) like this:

```javascript
 new Model(
      gl, {
        ...this.getShaders(),
        id: `${this.props.id}-model`,
        geometry: new Geometry({
          drawMode: GL.POINTS,
          vertexCount,
        }),
        isInstanced: false,
      },
    );
```

Now the catch: I think that the vertex data is uploaded multiple times to the GPU when the input data changes. I am not sure if also three different buffers are created for the three different vertex attributes but it could be the case. Also, calculatePositions is called three times per update, which might be part of this issue.

I hope you can help me with the following questions:
 
- How can I prevent that three vertex buffers are created
- How can I optimize the upload to the GPU so that it's only done once when necessary
- What would generally be the best way to implement this? I found some information regarding manual buffer management in layers but not enough that I would know how to do this.

Thanks in advance,
Marius

**Comment by Pessimistress** [comment]
Looks like you have 3 attributes (x, y, z) sharing the same updater (`calculatePositions`). When data changes, all attributes are updated, hence the updater being called 3 times.

**Comment by MGraefe** [comment]
Would the behaviour be any different if I use an accessor instead of the update function? I need to use one of the two, otherwise I get an error.

Currently my test data is just a singe Float32Array with x,y,z,x,y,z...
I know that I could just put that into a single position parameter but I need to specify the offsets and strides of individual components for flexibility reasons, when I use real data in the future there might be additional fields between x,y,z and the stride would be larger than 12 bytes.

**Comment by MGraefe** [comment]
Okay, I am now trying to manually handle the luma.gl buffers. I have removed everything related to the attribute manager (initializeState() is empty now) and I am manually creating my luma.gl Model like this:

```javascript
  getModel(gl) {
    const {data} = this.props;
    const vertexCount = data.length / 3;
    console.log('creating model');

    let {buffer} = this.state;
    if (!buffer) {
      buffer = new LumaBuffer(gl, data);
      this.setState({buffer});
    } else {
      buffer.subData(data);
    }

    return new Model(
      gl, {
        ...this.getShaders(),
        id: `${this.props.id}-model`,
        geometry: new Geometry({
          drawMode: GL.POINTS,
          vertexCount,
          attributes: {
            xIn: {
              buffer,
              offset: 0,
              stride: 12,
              type: GL.FLOAT,
              size: 1,
              value: data,
            },
            // similar for yIn, zIn just with different offsets
          },
        }),
        isInstanced: false,
      },
    );
  }
```

This works if I set the `value` parameter in every attribute to point to the data. The problem is that the buffer is now uploaded 4 times to the GPU (and I suspect each attribute uses a separate buffer instead of the same one).

If I don't specify `value` for the attributes (like why would I have to, I already specified a buffer) I get a number of luma.gl errors, all following a failed assert: ` Error: Geometry geometry-3 attribute xIn: must be typed array or object with value as typed array`.

This might be more of a luma.gl question now, but how do I specify a model with overlapping attributes and just one buffer? I get more and more clueless and my suspicion is, that this use case isn't really implemented correctly in luma.gl right now. Any advice?

**Comment by MGraefe** [comment]
Solved it by not using the Geometry class (which seems to be outdated) and creating the model like this:

````javascript
return new Model(
      gl, {
        ...this.getShaders(),
        id: `${this.props.id}-model`,
        drawMode: GL.POINTS,
        vertexCount,
        attributes: {
          xIn: {
            buffer,
            offset: 0,
            stride: 12,
            type: GL.FLOAT,
            size: 1,
          },
          // similar for yIn, zIn
        },
      },
    );
```

With this approach the vertex buffer is just uploaded once to the GPU, hence I can also be sure that all attributes use the same buffer.

I noticed however that a picking buffer is automatically updated each time I update the vertex buffer, this can be solved by removing the instancePickingColors attribute from the attribute manager (it gets added by default): `this.getAttributeManager().remove(['instancePickingColors']);`

All of this is rather unintuitive but I guess I am also doing pretty non-standard stuff. So this can be closed unless of course you want to add some comments.

**Comment by Pessimistress** [comment]
@MGraefe the best way to approach this is to add a single attribute `positions`, with `shaderAttributes`:

```js
  calculatePositions(attribute) {
    console.log('calculatePositions');
    // I don't recommend directly passing your typed array to `props.data`, as `data.length` is used to determine the number of points. You can wrap it into something like `{length: 100000, ...otherData}`.
    attribute.update({value: ...});
  }

  initializeState() {
    this.getAttributeManager().add({
      positions: {
        // I don't think you can get away without specifying `size`, though this value shouldn't matter if you are always packing the buffer externally
        size: 3,
        type: GL.FLOAT,
        stride: 12,
        // Alternatively, you can use `data: {length: 100000, attributes: {positions: <Float32Array>}}`
        update: this.calculatePositions,
        shaderAttributes: {
          x: {
            size: 1,
            offset: 0
          },
          y: {
            size: 1,
            offset: 4
          },
          z: {
            size: 1,
            offset: 8
          }
        }
      }
    });
  }
```

You can think of it as each attribute creates one buffer, and its "shader attributes" share the same buffer with different views.

Reference:
https://deck.gl/#/documentation/deckgl-api-reference/attribute-manager?section=add

**Comment by MGraefe** [comment]
Thanks for your help, using the shaderAttributes mechanism would've certainly helped but I somehow missed this when reading the documentation, my bad.
I am currently not using the attribute manager at all. I am fully managing the buffer myself which I feel a lot more comfortable with right now as I know exacty when it is updated. Deck.gl does a lot of things behind the curtains (which often is a good thing!) but I need every last drop of performance for handling our pointclouds so I need to be sure when what stuff is happening. I am not saying it cannot be done with Deck.gl itself but it's just easier for me right now to do it myself.
