### ISSUE TITLE
IconLayer with auto packing atlas stops drawing icons, generateMipmap crashes

### ISSUE THREAD

**Issue by ruizmarc** [uber/deck.gl#3875]
#### Description

We are using IconLayer to represent live data with auto packing atlas (we generate a few hundred different icons depending on the data we receive). Everytime we receive an event with updated data, we set props with an updated layer and we get the changes represented in the map.

We have noticed that sometimes icons stops rendering properly and instead of showing an icon, a black square is drawn (we haven't found a reproducible pattern, but it happens frequently). Although it can be reproduced on desktops, it specially happens on touch based devices such as an iPad.

![IMG_0009](https://user-images.githubusercontent.com/5717082/68653862-f11b0080-052c-11ea-8fc3-239f0c155ada.jpeg)

#### Repro Steps

It is reproducible in any browser and OS.

First time data is drawn properly, but after navigating through the map zooming in and out or changing bounds, it eventually crashes and stops drawing the icons, but black squares instead. 

Notice that when zoom is changed or bounds are changed, data is updated. 

We update the layer info, using set props like this:

`
this.overlay.setProps({ layers: [
      clustersLayer.clone({ data: clustersData })
]}); 
`

This is how we generated the IconLayer:

```
    const clusterSize = 124;
    return new IconLayer({
      id: 'icon-cluster',
      data,
      getPosition: (c: Cluster) => [c.centerLon, c.centerLat],
      opacity: 1,
      getIcon: (c: Cluster) => ({
        id: this.generateClusterIconId(c),
        url: `data:image/svg+xml;base64,${ btoa(this.generateClusterIconUrl(c, clusterSize)) }`,
        width: clusterSize,
        height: clusterSize
      }),
      sizeScale: .625,
      getSize: clusterSize,
      alphaCutoff: 0,
      pickable: true,
      onClick: ({ object: c }: { object: Cluster }) => {
        this.clusterClicked = c.geohash;
        if (this.getZoom() >= MAX_ZOOM) { // If cluster cannot longer be zoomed in
          this.changeToList.emit();
        } else {
          this.map.fitBounds({
            east: c.maxLon,
            north: c.maxLat,
            south: c.minLat,
            west: c.minLon
          });
        }
      },
    });

```

The amount of data entries may change depending on the bounds of the map in the screen and the events we receive, so we don't always have the same length of data (pointing this out, just in case it is relevant).

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.3.6
 - Browser Version: could reproduce it in Safari, Chrome and Firefox
 - OS: could reproduce it on MacOS and Windows

#### Logs

Every time it stops drawing icons I get these three errors:

```
[Error] WebGL: INVALID_VALUE: texImage2D: width or height out of range
    texImage2D
```

```
[Error] WebGL: INVALID_OPERATION: generateMipmap: level 0 not power of 2 or not all the same size
```

 ```
[Error] WebGL: INVALID_VALUE: copyTexSubImage2D: rectangle out of range
```

**Comment by Pessimistress** [comment]
@ruizmarc Based on your description I suspect you are hitting the texture size limit of the browser. Looks like you are dynamically generating icons based on cluster size. Do you generate a distinct icon for every number? How big are your icons (the `width` and `height` returned by `getIcon`)?

For better performance, I suggest you use the `TextLayer` for displaying the cluster size, on top of an `IconLayer` which only displays the background shape. This will limit the number of icons needed.

**Comment by tsherif** [comment]
A few additional notes:
- You can get the texture size limit on your machine by running the following code in the browser console: 
```js
gl = document.createElement("canvas").getContext("webgl");
gl.getParameter(gl.MAX_TEXTURE_SIZE);
```
- You can explore what the size limits look like on devices you want to support on [WebGL Stats](https://webglstats.com/webgl/parameter/MAX_TEXTURE_SIZE)

**Comment by ruizmarc** [comment]
It was exactly the problem you were describing! Thanks for the suggestions. I will look for a workaround. Thanks again, I’m closing the issue.

**Comment by p4cm4n** [comment]
Hi! 

We had the very same problem, svg et all, even after updating deck to 8.0.15, our code was basically the same as @ruizmarc's so we ended up making the svg files smaller from 512px to 32px in the SVG AND getIcon, the code is something like this:

`        return ({
          url: `data:image/svg+xml;base64,${base64Data}`,
          width: 32,
          height: 32,
          mask: false,
        });`

**Comment by Pessimistress** [comment]
@p4cm4n we don’t monitor closed issues. Please open a new bug with a codepen/code sandbox that reproduces your issue.
