### ISSUE TITLE
How can you load a scenegraph glb layer from local file upload? 

### ISSUE THREAD

**Issue by HHammerite** [uber/deck.gl#3881]
Is there a way to select a local file from an input and pass the file to a scenegraph layer? Specifically glb files.

**Comment by ibgreen** [comment]
@HHammerite I think that as long as you can load a binary GLB file as an `ArrayBuffer` you should be able to pass it to the ScenegraphLayer's scenegraph prop.

With the standard caveat that loading of local files into browsers can only be done through `File` objects returned as a result of user integration with drag-and-drop callbacks or file selection inputs, i.e. you can't hard code a path to a local file in your app. 

You could however use something like `arraybuffer-loader` to have webpack bundle the glb in your app.

**Comment by HHammerite** [comment]
@ibgreen I've implemented my loading like this, passing the result of a FileReader read as an array buffer to the layer. I get no errors, but I also don't see the model either. Any ideas what could be going on? I am loading the glb from a File object (selected using the file browser)

**Comment by HHammerite** [comment]
@ibgreen I just found that I'm getting a warning from luma.gl `luma: invalid scenegraph: undefined scenegraph-layer.js:173`. I was afraid that the model was the issue but after pointing the ScenegraphLayer scenegraph prop to the original [download ](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb)it seems to be fine.

**Comment by dianaow** [comment]
Hey @harrycollin, how did you solve this issue?

**Comment by harrycollin** [comment]
@dianaow I don't think I did to be honest. Sorry I can't be any help :/

**Comment by ibgreen** [comment]
I downloaded your file and drag-and-dropped it into https://loaders.gl/examples/gltf and it worked.

Drag-and-drop creates a `File` object and the GLB is loaded from that object.

**Comment by acebelowzero** [comment]
@dianaow Did you solve this issue?

**Comment by kibala145** [comment]
Just to clarify, if someone still facing the same problem, use load function with appropriate loader
https://loaders.gl/modules/core/docs/api-reference/load

```
import { load } from '@loaders.gl/core'
import { GLTFLoader } from '@loaders.gl/gltf'

const scenegraph = await load(file, GLTFLoader)
const scenegraphLayer = new ScenegraphLayer({
  scenegraph: previewScenegraph,
  ...
})
```
