### ISSUE TITLE
IconLayer antialias artifacts when using SVG

### ISSUE THREAD

**Issue by akre54** [uber/deck.gl#3891]
#### Description
When adding an SVG iconAtlas to IconLayer I get a black antialias artifact around the edge of the circle:

<img width="829" alt="Screenshot 2019-11-15 07 29 44" src="https://user-images.githubusercontent.com/931368/68954914-ca9dd500-0779-11ea-87c0-7523e9b16b63.png">
<img width="486" alt="Screenshot 2019-11-15 07 29 37" src="https://user-images.githubusercontent.com/931368/68954915-ca9dd500-0779-11ea-8c6b-7e46064aef43.png">

#### Repro Steps
I have an SVG IconAtlas that looks like this:

```svg
<svg width="256" height="512" viewBox="0 0 256 512" xmlns="http://www.w3.org/2000/svg">
  <circle cx="128" cy="128" fill="#fff" r="120" />
  <path d="m128 24-64 184 64-32 64 32z" fill="#456cb4" />
  <circle cx="128" cy="384" fill="#fff" r="120" />
</svg>
```

My iconMapping looks like this:

```
iconMapping: {
  arrow: {x: 0, y: 0, width: 256, height: 256},
  point: {x: 0, y: 256, width: 256, height: 256},
},
```

@tsherif suggests it might have something to do with the background alpha blending with the IconManager's canvas `ctx.clearRect` call, which clears the canvas to [transparent black](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clearRect).

#### Environment (please complete the following information):
 - Framework Version: deck 7.3.0
 - Browser Version: Chrome 78
 - OS: Mac OS 10.14

#### Logs
No warnings

**Comment by xintongxia** [comment]
Thanks for reporting, I'll look into it.

**Comment by Pessimistress** [comment]
While we investigate, if this particular icon is always white, you may set `[iconName]: {..., mask: true}` in `iconMapping` then use it with `getColor: [255, 255, 255]`.

**Comment by akre54** [comment]
So this one needs to show an arrow every 5 or 10 steps. My `getIcon` looks like this: `getIcon: (_, {index}) => index % 5 === 0 ? 'arrow' : 'point',`.

How are you suggesting I use the `getColor` in this case? The `point` icon is just a white circle, so could potentially use a ScatterPlot layer for that.

**Comment by Pessimistress** [comment]
If you are using 'mask: true` for both `arrow` and `point`, simply set

`getColor: (_, {index}) => index % 5 === 0 ? [0, 0, 255] : [255, 255, 255]`

For icons with `mask: false`, it doesn't matter what `getColor` returns.

**Comment by akre54** [comment]
But that turns the entire icon either white or blue, correct? Unfortunately that means it also doesn't show my icon.

Suggestions?

<img width="531" alt="Screenshot 2019-11-19 23 55 22" src="https://user-images.githubusercontent.com/931368/69210280-0d133900-0b0f-11ea-9c2a-844f791c0928.png">

**Comment by xintongxia** [comment]
@tsherif 

When application pass in `iconAtlas` image,

`IconManager` will load that image to a `Texture`, so do you know how to make the texture respect the source image's alpha?  
https://github.com/uber/deck.gl/blob/master/modules/layers/src/icon-layer/icon-manager.js#L253

**Comment by tsherif** [comment]
I believe the issue is that the texture itself is blending from transparent black outside the icon to white inside it, so there's a region of semi-transparent gray around the edges. I don't know SVG at all, but if there's a way to make the back ground transparent white (i.e. rgba(255,255,255, 0)), I think that would fix this issue.

**Comment by xintongxia** [comment]
@akre54 

As suggested by Tarek, you can add almost transparent background, i.e.. I am not sure why `fill-opacity="0.0"` is not working, but with a mimimum opacity, the border pixel is gone.
```
<svg width="256" height="512" viewBox="0 0 256 512" xmlns="http://www.w3.org/2000/svg">
  <rect width="256" height="512" fill="#fff" fill-opacity="0.01"/>
  <circle cx="128" cy="128" fill="#fff" r="120"/>
  <path d="m128 24-64 184 64-32 64 32z" fill="#456cb4"/>
  <circle cx="128" cy="384" fill="#fff" r="120"/>
</svg>
```
