### ISSUE TITLE
pydeck IconLayer doesn't appear

### ISSUE THREAD

**Issue by heumsi** [uber/deck.gl#3900]
Hi, I treid to draw Icon Layer. but doesn't appear

here is what i did

![image](https://user-images.githubusercontent.com/31306282/69115943-cf41f080-0acd-11ea-8a0c-07c2941e0328.png)

and the result was

![image](https://user-images.githubusercontent.com/31306282/69115954-d8cb5880-0acd-11ea-84b6-efd6a8e80306.png)

anything didn't appear...

is there something wrong in my code..?!
I already checked that my icon png file was in valid directory.
and there were not any script errors...

**Comment by ajduberstein** [comment]
Thanks for the bug report! I'm investigating this. Currently I think that the IconLayer is indeed broken in pydeck. I'll see if I can either make a recommendation for your code here or put out a patch.

**Comment by ajduberstein** [comment]
I'll have to put out a patch for this. I'll update this issue when it's done.

**Comment by ajduberstein** [comment]
Modifying an example from [Streamlit](https://github.com/streamlit/streamlit/pull/565):

```python
import pydeck as pdk
import pandas as pd

icon_data = {
    "url": "https://img.icons8.com/plasticine/100/000000/marker.png",
    "width": 128,
    "height":128,
    "anchorY": 128
}
data = pd.read_json("https://raw.githubusercontent.com/uber-common/deck.gl-data/master/website/bart-stations.json")
data['icon_data']= None
for i in data.index:
     data['icon_data'][i] = icon_data

view_state = pdk.ViewState(
    longitude=-122.22,
    latitude=37.76,
    zoom=9,
    pitch=50
)

icon_layer = pdk.Layer(
    type='IconLayer',
    data=data,
    get_icon='icon_data',
    get_size=4,
    pickable=True,
    size_scale=15,
    get_position='coordinates'
)
tooltip = {
   "html": "<b>Address:</b> {address} <br/> <b>Station:</b> {name}",
   "style": {
        "backgroundColor": "steelblue",
        "color": "white"
   }
}
r = pdk.Deck(layers=[icon_layer], initial_view_state=view_state, tooltip=tooltip)
r.show()
```

Works in pydeck 0.2.0, which was released two days ago.

![image](https://user-images.githubusercontent.com/2204757/71839671-91465f00-3070-11ea-8d24-3e5cb30b6b3a.png)

**Comment by tamir-jether** [comment]
im having some issue as well. when i use a URL, it works fine, but when i try to use a local png file, nothing is shown.

is pydeck not working with the pre-packed iconAtlas option in the iconLayer?

**Comment by ajduberstein** [comment]
@tamir-jether Thanks for reaching out! Can you file a new issue and include source code? It will be easier for me to replicate the error and fix it.

**Comment by pipesalas** [comment]
I'm having the same problem. At first it worked, but when I tried to display another image (using URL as well), the icon doesn't show.

**Comment by ajduberstein** [comment]
@pipesalas @tamir-jether You can subscribe to #4625, I'll be working on this. Give me a few weeks.
