### ISSUE TITLE
TripsLayer draws incorrectly for a A-B-A path

### ISSUE THREAD

**Issue by kevinresol** [uber/deck.gl#3907]
#### Description
Given 3 distinct points on map, namely A, B & C. When drawing a A-B-A path, the line will be incorrectly extended beyond point B.

The following image illustrates the problem:
- the green line is a A-B-C path, which is drawn correctly
- the orange line is a A-B-A path, which is drawn incorrectly

![Screenshot 2019-11-21 at 11 17 46 AM](https://user-images.githubusercontent.com/1103788/69301254-93836400-0c50-11ea-804e-7e9f9a6a64d9.png)

#### Repro Steps

https://codepen.io/kevinresol/pen/vYYPWWJ

#### Environment 
 - Framework Version: deck.gl 7.3.6
 - Browser Version: Chrome 78.0.3904.108
 - OS: Mac OS X 10.14.6

**Comment by romische** [comment]
Thanks! I have encountered this problem many times. Note that the unwanted part of the line disappear when we zoom

**Comment by kevinresol** [comment]
Unfortunately in my example, the defect remains there at any zoom level

**Comment by romische** [comment]
you're right in fact ! my points where not **exactly** A-B-A, but rather A-B-(A+0.000001)

**Comment by romische** [comment]
Same effects applies to PathLayer and GeoJson Layer

**Comment by Pessimistress** [comment]
Can you give 8.1.0-alpha.2 a try?

**Comment by romische** [comment]
> Can you give 8.1.0-alpha.2 a try?

Sadly, 8.1.0-alpha.2 doesn't fix it. 
Thank you :)


<img width="764" alt="Screen Shot 2020-02-12 at 18 30 56" src="https://user-images.githubusercontent.com/22628155/74361011-67e2c680-4dc6-11ea-98e7-454ab4dfe61f.png">

**Comment by Pessimistress** [comment]
@romische Have you tried setting the `miterLimit` or `rounded` prop?

**Comment by romische** [comment]
@Pessimistress 8.1.0-alpha.2 with `rounded:true` did fix the bug ! 


Well there's still this very tiny glitch (looks like deckgl is giving me the finger) - appearing in blinks at high zoom values only. I would say it's not relevant but maybe you need the info..
<img width="143" alt="Screen Shot 2020-02-13 at 01 04 19" src="https://user-images.githubusercontent.com/22628155/74388952-0db12800-4dfd-11ea-8d61-7f908c0ec85f.png">

**Comment by Pessimistress** [comment]
`8.1.0-alpha.4` should work with `rounded` on or off.

**Comment by kevinresol** [comment]
It looks much better,  but still not entirely correct. I am not very sure if this should be considered closed.

https://codepen.io/kevinresol/pen/vYYPWWJ
![image](https://user-images.githubusercontent.com/1103788/75307574-066f2d00-5887-11ea-9e99-75650dcac388.png)

**Comment by Pessimistress** [comment]
It is behaving as expected. The default `miterLimit` prop is `4` which makes the joint at B extends out. If you change it to `0` then it will be cut of.

**Comment by kevinresol** [comment]
sounds good then. thanks!
