### ISSUE TITLE
TextLayer scale or hide on resize

### ISSUE THREAD

**Issue by jasonsturges** [uber/deck.gl#3923]
Is it possible for text to resize on zoom? Or, does `sizeMinPixels` of `0` indicate it will ultimately be hidden at a certain zoom threshold?

[TextLayer example](https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer) from the documentation:

![text-layer](https://user-images.githubusercontent.com/1213591/69466759-f6592600-0d4a-11ea-9987-3824148cf7cd.gif)

Is the source code for those documentation examples easily available?

**Comment by maldo-ctrl** [comment]
Do something like this:

```
const _getTextSize = () => {
    const { viewState } = this.state;
    const { zoom } = viewState;
    return 30/zoom;      // Example of resizing rule, size will increase when zoom out
}

...

const layer = new TextLayer({
    id: 'text-layer',
    data,
    pickable: true,
    getPosition: d => d.coordinates,
    getText: d => d.name,
    getSize: _getTextSize ,
    getAngle: 0,
    getTextAnchor: 'middle',
    getAlignmentBaseline: 'center',
    onHover: ({object, x, y}) => {
      const tooltip = `${object.name}\n${object.address}`;
      /* Update tooltip
         http://deck.gl/#/documentation/developer-guide/adding-interactivity?section=example-display-a-tooltip-for-hovered-object
      */
    }
  });

...

  return <DeckGL {...viewport} layers={[layer]} />;
```

**Comment by Pessimistress** [comment]
You can set `sizeUnits: 'meters'` if you want the text to zoom with the map.

**Comment by jasonsturges** [comment]
@maldo-ctrl @Pessimistress Thanks to you both!
