### ISSUE TITLE
PathLayer visual artifacts

### ISSUE THREAD

**Issue by shayke** [uber/deck.gl#3931]
#### Description
PathLayer creates visual artifacts in some cases.

#### Repro Steps
Use the fiddle here: https://jsfiddle.net/8fa2q1sh/1/
You can see the line width is wrong:
![image](https://user-images.githubusercontent.com/1285887/69555130-5d751580-0fab-11ea-89d0-8458683e2ffa.png)

When you zoom in a bit it's getting fine:
![image](https://user-images.githubusercontent.com/1285887/69555171-6e258b80-0fab-11ea-9502-ccdbcb552e8b.png)

Trying to debug in `path-layer-fragment.glsl.js` looks like those pixels
are fallen into the `vMiterLength > 0.0 && length(vCornerOffset) > 1.0` case
not sure how this should be handled since when `rounded=true` there shouldn't be any miterLimit?

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.3.6]
 - Browser Version: [e.g. Chrome 78.0.3904.97]
 - OS: [e.g. Mac OS X 10.4.4]

**Comment by shayke** [comment]
@Pessimistress any pointers maybe?
If i could get some help understanding the offset length perhaps
it will be easy to perform antialiasing here same as:
https://github.com/uber/deck.gl/commit/82dbe806712b2a10da11d86a5c48e2dadce1eb68?

Thanks!

**Comment by Pessimistress** [comment]
This might be solved by #4111

**Comment by Pessimistress** [comment]
Can you give 8.1.0-alpha.2 a try?

**Comment by shayke** [comment]
Is master the same? I'm still getting weird artifacts:
![image](https://user-images.githubusercontent.com/1285887/74101652-d284cf80-4b44-11ea-9919-58e3f388b7fd.png)
![image](https://user-images.githubusercontent.com/1285887/74101655-e0d2eb80-4b44-11ea-9e2d-9319c957c463.png)
![image](https://user-images.githubusercontent.com/1285887/74101659-eaf4ea00-4b44-11ea-86cb-1f9d0402a794.png)

**Comment by Pessimistress** [comment]
Can you share your dataset?

With your JSFiddle, 7.3:

![image](https://user-images.githubusercontent.com/2059298/74180707-d7a15780-4bf4-11ea-946d-db7c09a9c3a0.png)

8.1.0-alpha:

![image](https://user-images.githubusercontent.com/2059298/74180723-dd973880-4bf4-11ea-9a8d-0bf8a319e169.png)

**Comment by Pessimistress** [comment]
Reopen if this is still an issue in 8.1.0.
