### ISSUE TITLE
Is it possible to use Deck.GL as Webpack external for a React project?

### ISSUE THREAD

**Issue by OriolInvernonLlaneza** [uber/deck.gl#3944]
I'm currently developing two different React applications which use Deck.GL to render two maps, each with a different type of layer. 
When using them as standalone they both work perfectly, however, when the two get mounted in the same parent application, the second map I visit crashes (due to loading the library two times, or so it seems).
Given that, I added Deck.GL to Webpack externals of both applications and added an unpkg link to the parent application. However, this gives an "Unable to resolve 'h3'" error, so I also put h3-js in externals but it keeps searching for it on Deck.GL javascript.
My next step was to import from the @deck.gl/core, @deck.gl/react, @deck.gl/layers, etc instead and only load what is needed, but I got a similar error as it was searching for 'luma' in @deck.gl/layers.

So, how do I correctly define Deck.GL as a Webpack external?

**Comment by Pessimistress** [comment]
h3-js is not bundled with deck.gl because of its size (1.5M). If you need to use it, you can include the h3-js bundle from unpkg BEFORE the deck script. Otherwise you can create a dummy global object `window.h3 = {}`

**Comment by OriolInvernonLlaneza** [comment]
Thanks for answering @Pessimistress .
I was not able to make it work with neither of your suggestions. If I try to include only deck.gl with or without loading h3 before I get: 

> Unable to resolve bare specifier "h3" from https://unpkg.com/deck.gl@7.3.6/dist.min.js

However, If I load both apps with their respective deck.gl dependencies, I get the folllowing errors:
![image](https://user-images.githubusercontent.com/15238295/70040354-b5b7a300-15bb-11ea-9609-f4896a80ba9e.png)

**Comment by Pessimistress** [comment]
Can you share a minimal app that reproduces this error?
Check out our [Codepen examples](https://codepen.io/vis-gl), most of which use the standalone bundle without h3-js.

**Comment by OriolInvernonLlaneza** [comment]
I will try to have a project ready for tomorrow, thanks for your attention! :)

**Comment by OriolInvernonLlaneza** [comment]
Happy new year!

I have finally been able to check this again and it seems the problem is caused by Angular Routing. When I navigate between the React applications using Angular routerLinks I receive that error, however, if I use simple <a> tags both maps work.

The greatest difference in behaviour between the two ways of navigating is that <a> tags are refreshing the page and loading everything again while Angular Routing doesn't. 

So, what I confirm from this is that we are unable to load Deck.gl multiple times, a problem that could be avoided by only importing It once and sharing It through Webpack external but I'm still unable to do it.

**Comment by Pessimistress** [comment]
> but I'm still unable to do it.

Without seeing *how* you are including the pre-built scripts in your page header or set up your webpack config I don't have much else to offer.

**Comment by OriolInvernonLlaneza** [comment]
Hello again, It looks like using deck.gl by parts and without externals allows me to have it loaded more than once on the page without the "unknown shader module" error popping.
However, I'm still interested on moving it out of the bundle with webpack externals, so I'll give you collaborator access on a private (I'm not alllowed to make the code public yet) example repo if you want to take a look at it. Thanks for your help :)

**Comment by Pessimistress** [comment]
Sure. You can also take a look at how the deck.gl website uses it as external:

https://github.com/uber/deck.gl/blob/94bad4bb209a5da0686fb03f107e86b18199c108/website/webpack.config.js#L128-L141

https://github.com/uber/deck.gl/blob/94bad4bb209a5da0686fb03f107e86b18199c108/website/src/static/index-prod.html#L17-L19

**Comment by OriolInvernonLlaneza** [comment]
Thank you so much! It worked with that configuration :smile:
