### ISSUE TITLE
Attribute: add support for `getData()`

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#3956]
#### Target Use case

Aggregation layers, when doing aggregation on GPU, need to read attribute value (like position) for each individual object to perform aggregation. 

#### Proposed feature

Add an API like `getData(objectIndex)` to `Attribute` class.  Based on attribute properties (like, size, type, etc), `getData` should return the value.

#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
I prefer not adding more accessibility methods to the `Attribute` class. `Attribute`'s primary goal is getting data to the GPU, not working with them on the CPU. In the CPU aggregation use case, you may checkout `getAccessorFromBuffer` in `iterable-utils`.
