### ISSUE TITLE
Struggles upgrading from 6.1 => 7.3

### ISSUE THREAD

**Issue by thomasgwatson** [uber/deck.gl#3961]
Trying to upgrade deck.gl from 6.1 to 7.3. I have looked at the upgrade guide and the pathLayer and iconLayer I am using are not explicitly mentioned there as having breaking changes.

Features before upgrade:
<img width="179" alt="Screen Shot 2019-12-04 at 13 47 51" src="https://user-images.githubusercontent.com/5193218/70184676-2c789d00-169d-11ea-88e3-dd13cf56c457.png">

The icons are styled and positioned correctly

Features after upgrade
<img width="168" alt="Screen Shot 2019-12-04 at 13 48 12" src="https://user-images.githubusercontent.com/5193218/70184566-ed4a4c00-169c-11ea-829f-091d98c5ed1e.png">

Now the icons are all stacked in the center of the viewport, and they are uniformly grey.

As I said, I couldn't find anything obvious in the upgrade guide to sort me out.

Checking some issues here I then:
- changed all my imports from `'deck.gl'` to `@deck.gl/layers` or `@deck.gl/react`
- changed my package.json to include     
    "@deck.gl/core": "^7.3.6",
    "@deck.gl/react": "^7.3.6",
    "@deck.gl/layers": "^7.3.6"
- threw out my node_modules
- ran npm install

Still no joy. Checking the docs for the individual layer types, there don't *seem* to be any API changes. I'm running on `"react-map-gl": "^5.0.7",`

Any hints about what to do next? I have the "Inexplicable upgrade breakage sadz"

**Comment by thomasgwatson** [comment]
Also getting this warning: "deck: setting null viewState"

Could there a change in how react-map-gl and deck.gl deal with the viewport?

**Comment by thomasgwatson** [comment]
Ok, I changed the props from `{...viewport}` to `viewState={viewport}` and everything works.

Did this change in the API happen in an earlier version? I checked and it is mentioned in the transition between 5.3 => 6.0 for "react only". Since I was still using the `deck.gl` import for 6.1, not the `@deck.gl/react`, perhaps I was shielded from this API break?

**Comment by luiztiago** [comment]
I got the same issue and it's working when I changed the props from `{...viewport}` to `viewState={viewport}`.
Thanks 👍
