### ISSUE TITLE
Hardware Acceleration Logic

### ISSUE THREAD

**Issue by sumarlidason** [uber/deck.gl#4006]
#### Target Use case
With google's [swiftshader](https://github.com/google/swiftshader) attempting to fill the gaps for those without GPU hardware acceleration I fear the logic in use as of `7.3.7` to determine whether to attempt GPU usage ~ is no longer sufficient with negative consequences. In my (basic) tests using `GridLayer` resulted in a 22 second render time, while `CPUGridLayer` was **11x** faster @ 2 seconds.

- `GridLayer` [vimeo](https://vimeo.com/379017096)
- explicit `CPUGridLayer` [vimeo](https://vimeo.com/379016973)

#### Proposed feature
Enhance GPU introspection to detect pseudo-GPUs:
https://github.com/uber/deck.gl/blob/80b23c254e7dcfeaed81e42fea42948298b0cc7d/modules/aggregation-layers/src/utils/gpu-grid-aggregation/gpu-grid-aggregator.js#L109-L111

![image](https://user-images.githubusercontent.com/1991770/70713011-23965580-1cb3-11ea-8795-6c057b4d811f.png)

Maybe using something like [detect-gpu ](https://github.com/TimvanScherpenzeel/detect-gpu) could help. On the swiftshader "gpu":
![image](https://user-images.githubusercontent.com/1991770/70714493-45450c00-1cb6-11ea-8165-567b20c66288.png)

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by tsherif** [comment]
Detecting software rendering is straightforward using [failIfMajorPerformanceCaveat](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1)

**Comment by sumarlidason** [comment]
thanks @tsherif !

I tried creating the component like so,
```jsx
<DeckGL
  glOptions={{failIfMajorPerformanceCaveat: true}}
  viewState={{
    ...
```
That results in an unhandled promise rejection, outside of the render path, so react error boundaries did not help ~

I ended up just instantiating a gl context to check this (which was happening anyways inside of `detect-gpu`):
```javascript
import { createGLContext } from '@luma.gl/webgl';

let canvas = document.createElement('canvas');
let gl = createGLContext({failIfMajorPerformanceCaveat: true, canvas, height: 2, width: 2});
let hasGPU = false;
if(gl) {
  hasGPU = true;
  gl.getExtension('WEBGL_lose_context').loseContext();
  gl = null;
  canvas = null;
}
```

it behaves as expected, thank you!
