### ISSUE TITLE
RotationX and rotationZ in the layer-browser example doesn't work for LAT_LON mode

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#401]

**Comment by ibgreen** [comment]
A main problem with layer rotations is defining the center point that the `modelMatrix` rotates around. 

* For layers using `METER_OFFSET` projection mode the layer specifies the center. Rotations should work for layers using this mode. Among the examples, I believe `METER_OFFSET` is currently only used by the `PointCloudLayer` example, the center point is the "anchor point" just below the floating sphere. 

* However, for `LNG_LAT` mode, the center point is 0, 0 in the partially projected mercator world coordinates, which is at one of the far corners of the world map, which makes no sense to the user. So even a tiny rotation angle with respect to such a distant center would move the layer out of view. So the example does not apply rotation to these layers.

* A possible solution is to support a `LNG_LAT_OFFSET` mode where we can still specify coordinates in [lng, lat] but also a center point, and do a delta operation in the shader. Apart from helping the rotation case, there are interesting precision/performance implications of such a mode.

Naturally it is also possible to handle these things by increasing the number of operations in the shader. The current constraint has been that we want to do only a single matrix multiplication in the shader, and do all matrix premultiplications in the CPU. If we sent multiple matrices to the shader we could be more flexible, at the cost of some rendering performance.

**Comment by ibgreen** [comment]
From the library perspective it could be argued that this is an `enhancement` rather than a `bug`. 

Still, I agree that the for the user of our main example it is quite confusing that these sliders don't do anything for most layers. So we might e.g. want to hide the sliders, or add a tool tip that explains what is going on.

**Comment by shaojingli** [comment]
Then, let's remove the sliders in the layer-browser example.

**Comment by ibgreen** [comment]
@shaojingli I believe you just commented out this code.
