### ISSUE TITLE
Incorrect rendering of s2 cells when zoomed out

### ISSUE THREAD

**Issue by supersonicclay** [uber/deck.gl#4019]
#### Description
Larger s2 cells are rendered as overlapping ninja stars.

#### Repro Steps

https://codesandbox.io/s/s2-ninja-star-bug-22tu7

![image](https://user-images.githubusercontent.com/469582/70839460-1a4bdc80-1dca-11ea-912e-4a04c3998b50.png)

The two smaller ones to the north correctly don't overlap. But the two larger ones to the south incorrectly overlap

#### Environment (please complete the following information):
 - Framework Version: deck.gl@7.3.8
 - Browser Version: Chrome
 - OS: OSX

**Comment by Pessimistress** [comment]
Fixed in 7.3.9
