### ISSUE TITLE
Passing layers as component props, throws exception on rendering the component

### ISSUE THREAD

**Issue by Rumpelstinsk** [uber/deck.gl#4034]
#### Description
When you try to render a layer for the second time, it throw an exception. Changing the id has no effect

#### Repro Steps
1. Download de project sample here: https://github.com/Rumpelstinsk/DeckSample
2. Run `npm install`
3. On file `src|components\MapLayer\MapLayer.js` replace `#YOUR_MAP_BOX_TOKEN#` to your real mapbox token
4. Run `npm start`
5. Click `layer-2` and wait 4 seconds to render
6. Click `layer-1` and wait 4 seconds. Error will be shown on console. React project crash completely

#### Environment (please complete the following information):
You can see directly on the sample

#### Logs

> layer-manager.js:367 deck: error while initializing ColumnLayer({id: 'piezometric-layer_1576594391242'})
>  Error: deck.gl: assertion failed.
>     at assert (assert.js:6)
>     at ColumnLayer._initState (layer.js:875)
>     at ColumnLayer._initialize (layer.js:555)
>     at LayerManager._initializeLayer (layer-manager.js:364)
>     at LayerManager._updateSublayersRecursively (layer-manager.js:311)
>     at LayerManager._updateLayers (layer-manager.js:270)
>     at LayerManager.setLayers (layer-manager.js:167)
>     at LayerManager.setProps (layer-manager.js:162)
>     at Deck.setProps (deck.js:273)
>     at Deck._setGLContext (deck.js:657)
>     at Deck._onRendererInitialized (deck.js:694)
>     at AnimationLoop.onInitialize (animation-loop.js:242)
>     at animation-loop.js:152
> _initializeLayer @ layer-manager.js:367
> _updateSublayersRecursively @ layer-manager.js:311
> _updateLayers @ layer-manager.js:270
> setLayers @ layer-manager.js:167
> setProps @ layer-manager.js:162
> setProps @ deck.js:273
> _setGLContext @ deck.js:657
> _onRendererInitialized @ deck.js:694
> onInitialize @ animation-loop.js:242
> (anonymous) @ animation-loop.js:152
> Promise.then (async)
> start @ animation-loop.js:128
> Deck @ deck.js:194
> componentDidMount @ deckgl.js:59
> commitLifeCycles @ react-dom.development.js:22101
> commitLayoutEffects @ react-dom.development.js:25344
> callCallback @ react-dom.development.js:336
> invokeGuardedCallbackDev @ react-dom.development.js:385
> invokeGuardedCallback @ react-dom.development.js:440
> commitRootImpl @ react-dom.development.js:25082
> unstable_runWithPriority @ scheduler.development.js:697
> runWithPriority$2 @ react-dom.development.js:12149
> commitRoot @ react-dom.development.js:24922
> finishSyncRender @ react-dom.development.js:24329
> performSyncWorkOnRoot @ react-dom.development.js:24307
> (anonymous) @ react-dom.development.js:12199
> unstable_runWithPriority @ scheduler.development.js:697
> runWithPriority$2 @ react-dom.development.js:12149
> flushSyncCallbackQueueImpl @ react-dom.development.js:12194
> flushSyncCallbackQueue @ react-dom.development.js:12182
> flushPendingDiscreteUpdates @ react-dom.development.js:24377
> flushDiscreteUpdates @ react-dom.development.js:24356
> finishEventHandler @ react-dom.development.js:1384
> batchedEventUpdates @ react-dom.development.js:1418
> dispatchEventForPluginEventSystem @ react-dom.development.js:5894
> attemptToDispatchEvent @ react-dom.development.js:6010
> dispatchEvent @ react-dom.development.js:5914
> unstable_runWithPriority @ scheduler.development.js:697
> runWithPriority$2 @ react-dom.development.js:12149
> discreteUpdates$1 @ react-dom.development.js:24417
> discreteUpdates @ react-dom.development.js:1438
> dispatchDiscreteEvent @ react-dom.development.js:5881
> assert.js:6 Uncaught (in promise) Error: deck.gl: assertion failed.
>     at assert (assert.js:6)
>     at ColumnLayer._initState (layer.js:875)
>     at ColumnLayer._initialize (layer.js:555)
>     at LayerManager._initializeLayer (layer-manager.js:364)
>     at LayerManager._updateSublayersRecursively (layer-manager.js:311)
>     at LayerManager._updateLayers (layer-manager.js:270)
>     at LayerManager.setLayers (layer-manager.js:167)
>     at LayerManager.setProps (layer-manager.js:162)
>     at Deck.setProps (deck.js:273)
>     at Deck._setGLContext (deck.js:657)
>     at Deck._onRendererInitialized (deck.js:694)
>     at AnimationLoop.onInitialize (animation-loop.js:242)
>     at animation-loop.js:152

**Comment by ergum** [comment]
I had a similar problem like described above. Any suggestion?

**Comment by Pessimistress** [comment]
@Rumpelstinsk Your component is mixing `this._deck` and `this.deck`. when you call `new MapboxLayer({id, deck})` sometimes `deck` is undefined.

**Comment by Rumpelstinsk** [comment]
@Pessimistress thanks for taking time to review the sample. It was a copy-paste error from the real project. I have just updated the sample to rename the variables correctly.

**Comment by Pessimistress** [comment]
Just FYI we will not run random projects on our work box for security reasons. If you can put your project on code Sandbox we may help you debug.

Judging from the error message you are reusing a layer instance that has been added then removed. When you update the list of layers you should always create new instances. Creating a new layer has virtually no cost.

**Comment by Rumpelstinsk** [comment]
I have uploaded the code to Sandbox: https://codesandbox.io/s/vigilant-paper-4bsp2?fontsize=14&hidenavigation=1&theme=dark

However something gets broken on migration. It throws a console error saying the format of the json sample is incorrect. however it works with no problem on VS.

Despite the error, you can see the complete code there. On the other hand, I'm not reusing a layer. If you take a look to `LayerManager.js`, every layer has a different Id.

**Comment by Pessimistress** [comment]
You `LayerManager` is storing layer instances in `this.state`. Once a layer is finalized (removed from DeckGL) it cannot be reused again. `showPiezometricLayer`, `showWaterQualityLayer` must always create new layer instances.

**Comment by Rumpelstinsk** [comment]
Ok I see the problem now. Creating a new layer every time, seems to avoid the problem.
Thanks fot the help.
