### ISSUE TITLE
TileLayer: trigger rerender without refetching data

### ISSUE THREAD

**Issue by ibesora** [uber/deck.gl#4036]
Is there a way to force a rerender of a tile layer without refetching the data?

My use case is the following one:
- I have a TileLayer that fetches and decodes MVT tiles. This layer contains a number of points with a property that's used to filter them.
- On the UI I have a toggle for each value of that property and when the user clicks it the points with that value should change their status to visible/not-visible

In order to do that I've tried different things:

- Filtering the points inside the `getTileData` function and changing the `id` of the layer each time one toggle is changed to trigger a refresh. This is slow because even though the browser might have the MVT data cached so no request is done, the processing of that data is done every time.
- Defining a `getRadius` function that returns 0 if the toggle is disabled. This does nothing if the `id` of the layer is not changed because deck.gl doesn't know there have been any changes and changing the `id`gets us back to the first point, having to decode the MVT even though the data hasn't changed is really slow.

Crazy ideas I've thought about:
- Create 50 different layers, one per each property value, and change the `visible` property of the layer depending on the status of each toggle
- Store the decoded MVT features in a cache and return the content stored there instead of having to process the MVT each time a toggle is changed

But those seem like overkill.

I haven't looked at the internals of deck.gl (yet!) so I don't know if that's easy/possible to do. 
Any idea?

**Comment by Pessimistress** [comment]
> Defining a getRadius function that returns 0 if the toggle is disabled.

You want to use [updateTriggers](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer?section=updatetriggers-object-optional-) to tell the layer that `getRadius` needs to be re-evaluated, something like:

```
updateTriggers: {
  getRadius: {
    // describe your filter here. This value is compared one-level deep between layer updates
    type: 'Point',
    rank: '>=4',
    ...
  }
}
```

**Comment by ibesora** [comment]
That works great.
Thanks for pointing that out!
