### ISSUE TITLE
can deck.gl read the 3Dtiles city model of caesium?

### ISSUE THREAD

**Issue by marc111** [uber/deck.gl#4052]
I want to load the caesium's b3dm file into deck.gl. 
I know that there is a tile 3D layer API in deck.gl. 
but I don't know how to use it. 
The official case is only the 3Dtiles of the point cloud, not the city model

**Comment by xintongxia** [comment]
@marc111 

[Tile3DLayer](https://deck.gl/#/documentation/deckgl-api-reference/layers/tile-3d-layer) supports `.b3dm` tiles. `Tile3DLayer` is still experimental, it may has some issues.

We are scheduled to release a new version of deck.gl (v8) soon, should have a better version of `Tile3DLayer`
