### ISSUE TITLE
OnHover is bubbling even when returning true

### ISSUE THREAD

**Issue by lukemcgregor** [uber/deck.gl#4055]
#### Description
If you implement onHover on a layer and also on the root deck, and then you return truthy in the layer it still calls onHover on the deck. https://github.com/uber/deck.gl/blob/master/docs/developer-guide/interactivity.md#behavior-of-built-in-event-handling says that this should not bubble when returning true.

#### Repro Steps
 - Create a deck with a layer  which consumes some space
 - implement hover on the layer and the deck with the layer returning true
 - Expected: only one of the onHovers should be called at once
 - Actual: when hovering on the layer component both onHover handlers are called

https://codepen.io/lukemcgregor/pen/GRgWrEY

#### Environment (please complete the following information):
 - Framework Version: 7.3.6
 - Browser Version: Chrome 79.0.3945.79
 - OS: Mac OSX 10.15.2

**Comment by Pessimistress** [comment]
Thanks for reporting. This is indeed a bug. Looks like instead of skipping the root `onHover`, it is called with an empty `pickingInfo`.

**Comment by Pessimistress** [comment]
Fixed in 7.3.11
