### ISSUE TITLE
DataFilterExtension Update FilterValue Via Click

### ISSUE THREAD

**Issue by btbritz** [uber/deck.gl#4058]
I have some data being filtered via a timestamp initially. And on a button click I'm hoping to update what is being filtered and rendered to the screen.

```
layerData () {
  return new ScatterplotLayer({
  ...
    getFilterValue: d => {
      if (type === 'time') {
        return d.timestamp / MS_PER_DAY 
      } else {
        return d.score
      }
    },
  ...
  })
}

// From button click
toggleRange () {
    this.deck.setProps({layers: this.layerData()})
},
```
Am I missing something? Does getFilterValue() not get update when you setProps after init?

**Comment by Pessimistress** [comment]
No. `getFilterValue` is an accessor and you need to use `updateTriggers` to triggger an update. Otherwise we would be calling this function on every render frame.

I also recommend using `DataFilter({size: 2})` to handle multiple filter values.
