### ISSUE TITLE
Calculate absolute bounds for map

### ISSUE THREAD

**Issue by lukemcgregor** [uber/deck.gl#4060]
I am having some trouble calculating the bounding box containing the viewport. I need to render copies of data across map views at minimal zoom which are wider than 1 earth, eg below there are two Africas, so features there will need double rendering.

![image](https://user-images.githubusercontent.com/1284608/71215937-f33b6080-231d-11ea-9490-11e765b38d00.png)

I currently calculate the bounding box containing the view like this:

```
      const [x1, y1] = viewport.unproject([0, 0]);
      const [x2, y2] = viewport.unproject([viewport.width, 0]);
      const [x3, y3] = viewport.unproject([viewport.width, viewport.height]);
      const [x4, y4] = viewport.unproject([0, viewport.height]);
      const north = Math.max(y1, y2, y3, y4);
      const south = Math.min(y1, y2, y3, y4);
      const east = Math.max(x1, x2, x3, x4);
      const west = Math.min(x1, x2, x3, x4);
```

This deals with cases where the map is rotated. However in cases where the viewport is wider than 1 world the unproject call seems to clamp the coordinates to -180, 180. While this makes sense on one level I cant find an easy way to tell what virtual coordinates I need to render duplicates at so they show at all duplicate locations. 

**Is there a way to either render features at all duplicate locations, or to detect the absolute max/min longitude of the map so I can work out what duplicates I need to render?**

**Comment by Pessimistress** [comment]
How are you getting your `viewport`? `WebMercatorViewport.unproject` should not clamp the longitude.

**Comment by lukemcgregor** [comment]
I am using WebMercatorViewport, below is the full code including that call. If you want I can try and repro in a codepen.
```
"deck.gl": "^7.3.6",
"viewport-mercator-project": "^6.2.2"
```
```
      <ReactMapGl
        /* eslint-disable-next-line react/jsx-props-no-spreading */// as per ReactMapGl docs
        {...viewport}
        onViewportChange={vp => {
          patchViewport(config.id, {
            latitude: vp.latitude,
            longitude: vp.longitude,
            zoom: vp.zoom,
            bearing: vp.bearing,
            pitch: vp.pitch,
            width: vp.width,
            height: vp.height,
            transitionDuration: vp.transitionDuration
          });
        }}
       ...
```


```
      const viewport = new WebMercatorViewport(action.payload.viewport);
      const [x1, y1] = viewport.unproject([0, 0]);
      const [x2, y2] = viewport.unproject([viewport.width, 0]);
      const [x3, y3] = viewport.unproject([viewport.width, viewport.height]);
      const [x4, y4] = viewport.unproject([0, viewport.height]);
      const north = Math.max(y1, y2, y3, y4);
      const south = Math.min(y1, y2, y3, y4);
      let east = Math.max(x1, x2, x3, x4);
      let west = Math.min(x1, x2, x3, x4);
```

**Comment by lukemcgregor** [comment]
@Pessimistress I made it in a codepen using the bundled deckgl lib that includes that viewport. It didnt reproduce the issue (though making the viewport in the console with my version does). In my code I'm importing both separately which makes me think my version might be bad, should I be using a different import for the projection?

**Comment by lukemcgregor** [comment]
Ok it looks like my problem was that `viewport-mercator-project` is old, I switched to `@math.gl/web-mercator@3.1.1` and it worked as expected. Thanks
