### ISSUE TITLE
HTML element with ID "deck" causes “multiple VERSIONs detected” error

### ISSUE THREAD

**Issue by sw1227** [uber/deck.gl#4069]
#### Description
I tried to use deck.gl in  Observable notebook. My notebook title was **deck**, and importing deck.gl triggered “multiple versions detected” error.
I first thought it's a bug with Observable notebook. However, according to Mike Bostock's investigation, 
it seems to be a bug with deck.gl: any page with an element with the id “deck” will (erroneously) trigger this “multiple versions detected” error.

> Deck.gl checks the existence of the deck global to determine if you’ve already loaded the Deck.gl library. This means that any page with an element with the id “deck” will (erroneously) trigger this “multiple versions detected” error.
> 
> Deck.gl could also fix their library to have a more precise test for already being loaded, rather than checking the existence of a deck global.
> 
> https://talk.observablehq.com/t/bug-notebook-title-causes-multiple-versions-detected-error/2669/3?u=sw1227

#### Repro Steps
1. Create HTML element with the id `deck`.
2. import deck.gl

https://talk.observablehq.com/t/bug-notebook-title-causes-multiple-versions-detected-error/2669/3?u=sw1227

#### Environment (please complete the following information):
 - Framework Version: deck.gl 6.4.10
 - Browser Version: Chrome 78.0.3904.108
 - OS: macOS 10.15.1

**Comment by Pessimistress** [comment]
Thanks for reporting. We will release patches for 8.0 and 7.3.

deck.gl v6 is no longer actively maintained. You can check out [this notebook](https://observablehq.com/@pessimistress/deck-gl-playground) which works for the latest v7 and v8 releases.

**Comment by sw1227** [comment]
Thanks for your quick response! I will check the notebook, too. ☺️

**Comment by Pessimistress** [comment]
8.0.1/7.3.11
