### ISSUE TITLE
v8.0 - peer dependency/runtime versioning issues

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#4072]
#### Description

Looks like there are some minor dependency/versioning issues in the initial 8.0 release. The runtime version is reported as `8.0.0-beta.2`, and it seems that a couple of peer dependencies in luma.gl are not fully updated to 8.0.

#### Repro Steps

<img width="613" alt="Screen Shot 2019-12-23 at 9 31 12 AM" src="https://user-images.githubusercontent.com/7025232/71371928-bc588b00-2567-11ea-93c2-6236de96f51b.png">

```
npm ls | grep deck.gl
├─┬ @deck.gl/core@8.0.0
├─┬ @deck.gl/geo-layers@8.0.0
├─┬ @deck.gl/layers@8.0.0
├─┬ @deck.gl/mesh-layers@8.0.0
├─┬ @deck.gl/react@8.0.0
npm ERR! peer dep missing: @luma.gl/engine@^7.1.0, required by @luma.gl/experimental@8.0.0
npm ERR! peer dep missing: @luma.gl/gltools@^7.1.0, required by @luma.gl/experimental@8.0.0
npm ERR! peer dep missing: @luma.gl/shadertools@^7.1.0, required by @luma.gl/experimental@8.0.0
npm ERR! peer dep missing: @luma.gl/webgl@^7.1.0, required by @luma.gl/experimental@8.0.0
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.0
 - Browser Version: Chrome 78
 - OS: Mac OS X 10.14.5

**Comment by Pessimistress** [comment]
The inlined version is a known issue. `lerna` stopped running the `version` script at root sometime this year.

luma.gl's `peerDependencies` need to be fixed.

**Comment by Pessimistress** [comment]
8.0.1
