### ISSUE TITLE
Font Icon (i.e., Webfont) TextLayer/IconLayer?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4073]
Not sure if the is the appropriate place to ask...

Would there be a way to use a webfont as an icon (Specifically, https://materialdesignicons.com/). I was looking at the IconLayer and TextLayer however I can't seem to figure out a way to leverage these for this purpose. I did try using the unicode value for the icon(s) I wanted to use along with specifying the fontFamily as 'Material Design Icons'. Neither seemed to work...  

Any help would be great! BTW, big fan of deck. Using it with Vue.

**Comment by Pessimistress** [comment]
I assume you are including the webfont using stylesheets. Adding a `@font-face` doesn't guarantee the font to be loaded.

Check out [this CodePen](https://codepen.io/Pessimistress/pen/yLybGqX) where we render a `<div>` using the `Material Icons` font *before* the `TextLayer` is initialized. It forces the page to load the font. If you remove the `<div>`, the font can no longer be found by the canvas.

You may not want to use this hack in production, in case of being affected by future browser optimizations:
- The font loading may become asynchronous, i.e. after the page is rendered
- The font may not be loaded when the div is hidden

If that is a concern, you can also use [this technique](https://stackoverflow.com/questions/59013793/how-to-render-icon-fonts-on-html-canvas-and-material-design-icon-fonts-in-partic):

```js
const material_font = new FontFace( 'Material Icons',
  // pass the url to the file in CSS url() notation
  'url(https://fonts.gstatic.com/s/materialicons/v48/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2)' );
document.fonts.add(material_font); // add it to the document's FontFaceSet

material_font.load().then(() => {
  deckgl.setProps({
    layers: [...]	// add TextLayer here
  })
})
```

**Comment by jfuehner** [comment]
@Pessimistress Thanks! I’ll give that a go.

Would you happen to know if the IconLayer also supports using 3D models as icons? glTF perhaps?

**Comment by Pessimistress** [comment]
You need to use `ScenegraphLayer` for that.

**Comment by jfuehner** [comment]
@Pessimistress another question for you. Is it possible to assign a css style to icons in the icon layer?

**Comment by Pessimistress** [comment]
If you know the style that applies to each icon, then you can use data URL to render SVG icons:

```js
getIcon: d => ({
  id: 'icon-1',
  url: 'data:image/svg+xml;utf8,<svg>...</svg>',
  width: 64,
  height: 64
})
```

But once an icon with a specific id is loaded (read: rasterized) it cannot be changed.

See [auto packing iconAtlas](https://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer?section=example-auto-packing-iconatlas).

**Comment by jfuehner** [comment]
@Pessimistress is it possible to use a dataUri as the url or can we pass a base64 string to the 'data:image/svg+xml;utf8,<svg>...</svg>' string?

**Comment by jfuehner** [comment]
@Pessimistress, disregard... Oversight on my part that the dataUri was actually what was being passed to the url property of the icon

**Comment by jfuehner** [comment]
@Pessimistress so I tried both the _hack_ and the FontFace recommendations. These both work in simple scenarios.

However, I have an app where I am loading deck from as a web component which gets rendered to the browser inside a shadow-dom. For some reason, neither the _hack_ nor the FontFace solutions work in this situation. Its as if the canvas context is not picking up the custom font with it being inside the shadow-dom...

Any thoughts?
