### ISSUE TITLE
deck.gl v4 not working for safari

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#408]
Unfortunately, Safari doesn't support Object.values() method. 

<img width="612" alt="screen shot 2017-03-09 at 10 19 39 am" src="https://cloud.githubusercontent.com/assets/21322704/23765021/8af56014-04b4-11e7-8d64-e596f6300f89.png">

https://bugs.webkit.org/show_bug.cgi?id=150131

**Comment by ibgreen** [comment]
Good catch. looks like [Object.values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) comes in ES2017. 

Deck.gl's code base is intended to be completely ES6 (ES2015) conformant - allowing it to run without transpilation and polyfills on modern browsers.

**Comment by shaojingli** [comment]
#409
