### ISSUE TITLE
Update SunLight effect as time changes?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4082]
I have a use-case where I need to display a SunLight lighting effect over as map along with updating the SunLight in real-time as time changes.

Looking for an example of how I might update the timestamp for the SunLight (https://deck.gl/#/documentation/deckgl-api-reference/lights/sun-light) lighting effect as time changes?

**Comment by xintongxia** [comment]
I'll work on an example shortly.

**Comment by xintongxia** [comment]
@jfuehner here is an example, showing sunlight changing in a day in Vancouver. Hope it can help your use case.

https://codesandbox.io/s/sunlight-timestamp-demo-emspi?fontsize=14&hidenavigation=1&theme=dark

**Comment by Pessimistress** [comment]
@xintongxia Something to consider is that by creating a new `LightingEffect` every frame you lose the WebGL resources associated with it. This will be a big perf problem if you turn on shadow. You can simply update the `timestamp` field of the existing `SunLight` instance and trigger an update with `deck.redraw()`.

**Comment by xintongxia** [comment]
@jfuehner close it for now. But feel free to reopen it if you have further questions.
