### ISSUE TITLE
[Mini RFC] Detect if a layer has loaded all of its assets

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#4091]
### Background

deck.gl introduced async props support in v6. Currently, all layers have the ability to load some of its assets asynchronously, including `data`, `image` (BitmapLayer), `iconMapping` and `iconAtlas` (IconLayer), `texture` (SimpleMeshLayer), etc.

In most applications, we just want deck to rerender as soon as new assets become available. However, it may be also desirable to know when a layer has fully loaded its assets and performed a complete draw. In render tests, we should only compare screenshots when all layers are done loading. In kepler.gl, video frames should only be saved when the content is fully rendered.

### Proposal

Add a public method to the base `Layer` class `Layer.isLoaded()`.
The method should return true when:

- All async props are resolved - this is the default implementation of the base `Layer`'s method
- All async requests that affect render (downloads, data processing, etc.) are resolved - this should be implemented by each layer if needed
- All sublayers are loaded - this is the default implementation of the base `CompositeLayer`'s method

Note that `isLoaded()` would still return true even if some assets fail to load. It merely indicates that all async operations are done -- not necessarily successfully -- and the layer has come to an "idle" state util future prop updates.

In practice, an application can use the feature as follows:

```js
Deck({
  ...
  layers,
  onAfterRender: () => {
    if (layers.every(layer => layer.isLoaded())) {
      // capture screenshot
    }
  }
})
```

**Alternative names**

- `isIdle`
- `isAwaitingAsset`

### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [ ] What’s new update 
  - [x] Test

**Comment by Pessimistress** [comment]
@ibgreen @chrisgervang @heshan0131

**Comment by ibgreen** [comment]
This is great start and much needed for a use case we are working on.

- I was thinking it would be nice to have a callback, not just a query, e.g. for test cases etc.
- it would be neat if this "rolls up" to a method and callback on `Deck`
 - `Deck.isLoaded()`,
- `Deck.onLoaded(true/false)`

- Especially in TileLayer and Tile3DLayer, we have layers that can be loaded and then no longer loaded when view props change, so being able to track loading status before each frame is important for e.g. video rendering, leading to a flow like:

```js
deck.setProps({layers: new Tile3DLayer(...)});

// `deck.onLoaded` called with `false`
// ... loading tiles
// `deck.onLoaded` called with `true`

deck.setProps({ViewState})

// `deck.onLoaded` called with `false`
// ... loading missing tiles
// `deck.onLoaded` called with `true`
```

**Comment by Pessimistress** [comment]
Why wouldn't your Tile3DLayer use case be covered by my code sample in the proposal? You already know that a reload is required when you initiate `setProps`. Even if you get a callback `onLoaded(true), you still need to listen to `onAfterRender` to be able to capture a video frame.

**Comment by ibgreen** [comment]
That is true, it could all be done with the simpler mechanism you propose so this is more an API design suggestion.

My comments and example are based on a sense that:

- Loading status is a core concept that deserves its own top-level API, bringing to the user's attention that we support this important and non-trivial feature. 

- There are other things than video frames that could be updated when load status changes, such as UI elements etc indicating that things are still loading. 

- Allowing apps listen for such changes directly in a callback with a self-documenting name rather than adding a layer loop in `onAfterRender` would be clearer in my opinion.

**Comment by Pessimistress** [comment]
Unlike `onDataLoad`, which exposes the loaded data array to the user, the “assets loaded” event does not have any tangible results. When the assets are loaded, the layer is simply marked “needs redraw.” Any texture/state that has been updated is internal to the layer and subject to change without documentation. So what exactly would be accomplished by listening to this event? Is your app manually tracking the loaded states of all the layers?

**Comment by ibgreen** [comment]
>  When the assets are loaded, the layer is simply marked “needs redraw.” 

Good point, a bit more detail around how the loading tracking should be done would probably be good thing to add to the RFC. 

I.e. how would it look for Layer authors? Can we do it with no impact?

I get the sense that you have an idea around a minimal system, and I am probably imagining something a bit more extensive that is aware of when things load.

**Comment by ibgreen** [comment]
For the use cases section in your RFC, these are the 3 use cases currently in my mind around "rendering individual frames":
- testing
- video animation
- using deck as an image/texture rendering engine for use e.g. with other rendering engines (will share some code soon around this)

**Comment by ibgreen** [comment]
> So what exactly would be accomplished by listening to this event?

1. A loading spinner
```
deck.setProps({
  onLoaded: isLoaded => dispatch(showSpinner(!isLoaded))
});
```

2. rendering individual frames

While this can certainly be done by animation loop callbacks, I feel using callbacks on top of the animation loop does not feel natural when rendering individual frames, and would prefer to see a simpler, more "linear" API for these cases:

```
  deck.setProps({layers, viewState, renderLoop: false});
  await deck.loaded(); // TBD pseudo-code, we could ideate on how to get a promise here.
  await deck.render();
```

Also in the animation loop case (unless extra logic was added), deck would potentially render lots of wasted frames while deck was loading, whereas here we would explicitly only render when we actually want the frame.

**Comment by Pessimistress** [comment]
Looks to me that your last two example use cases can be solved if `setProps` returns a promise.

I think this is what we can agree:

- Regardless of what API we add to the Deck class, the `loaded` check needs to be supported on the layer level.
- For a layer, this is a passive check, i.e. no callbacks will be exposed.

I prefer to keep this proposal small and actionable. Discussion regarding the Deck API can be a separate thread.

**Comment by ibgreen** [comment]
> Looks to me that your last two example use cases can be solved if setProps returns a promise.

Yes they could, but is it intuitively/unambigously clear what a `setProps` promise should represent? Loaded? Rendered? Transitions complete?

> Regardless of what API we add to the Deck class, the loaded check needs to be supported on the layer level.

Agreed. (An architectural change that might be desirable in the future is being able to define separate "`deck.props.dataSources`", so that e.g. multiple layers can share the same data. Of course, the layers `loaded()` methods could still refer to the dataSources, so that would still work with this API).

> For a layer, this is a passive check, i.e. no callbacks will be exposed.

Understood. This requires busy-polling but that is in line with how dirty checks in general work at the moment.

> I prefer to keep this proposal small and actionable. Discussion regarding the Deck API can be a separate thread.

That works for me. I am totally fine with the proposal, mainly wanted to engage/show interest/encouragement. 

And in fairness, the current RFC mainly talked about the top-level API rather than the implementation, so I suppose that is what I ended up trying to provide my perspective on.

**Comment by xintongxia** [comment]
Maybe also need consider how to surface to users when some assets failed to load.
https://github.com/uber/deck.gl/issues/4149
