### ISSUE TITLE
Interleaving pros/cons?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4099]
Hi! I found this showcase example interleaving/passing deck layer contexts to mapbox layers...

https://deck.gl/showcases/gallery/mapbox-layer

Can you share the pros/cons of doing this? Would I be losing performance and all the deck.gl goodness doing this? 

Thanks!

**Comment by ibgreen** [comment]
@jfuehner https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview?section=advantages-and-limitations
