### ISSUE TITLE
Does pydeck support FlyToInterpolator viewport animation or any other transition between lat/longs? Thanks

### ISSUE THREAD

**Issue by davidhayter-karhoo** [uber/deck.gl#4101]

**Comment by ajduberstein** [comment]
Thanks for the question! It's not explicitly documented for pydeck but there are transitions.

Pass the `transition_duration` argument in the `ViewState` you pass to `Deck` and  call `update` on that `Deck` object. The `transition_duration` argument is specified in milliseconds. Taking the example notebook [linked here](https://github.com/uber/deck.gl/blob/master/bindings/pydeck/examples/01%20-%20Introduction.ipynb) and modifying it slightly:

![transition-compress](https://user-images.githubusercontent.com/2204757/71847665-52b9a000-3082-11ea-99b1-880a9e7e7cec.gif)

**Comment by davidhayter-karhoo** [comment]
Thanks for the comprehensive response, that worked for me

**Comment by swha03** [comment]
i want to use transition_duration, but i can't!
Changing the zoom still works but The screen won't move. and The FlyToInterpolator does not apply.

**Comment by ajduberstein** [comment]
Latest fix is discussed in #4217

**Comment by cornhundred** [comment]
@ajduberstein can transition_duration be used to animate an update to scatterplot positions (by updating the position column in a scatterplot's data attribute)?
