### ISSUE TITLE
Polygon outline flicker in the GeoJSONLayer 

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#411]
The filled part and stroked outline of polygons in GeoJSONLayer flickers really bad due to z-fighting. It's a small issue technically, but visually very unpleasing.

![mar-09-2017 11-19-01](https://cloud.githubusercontent.com/assets/21322704/23766610/738d4e40-04ba-11e7-80aa-1e50fa003221.gif)

**Comment by ibgreen** [comment]
Thinking about a generic solution: In v4 we have added a `layerIndex` uniform. Perhaps we could use this in the `project` function to add a tiny z offset in clip space (i.e. `layerIndex * EPSILON`) after rendering?

**Comment by shaojingli** [comment]
Let's discuss this to see which is better - do the offset in the world space or in the clip space

**Comment by ibgreen** [comment]
We now have the `polygonOffset` prop to combat this. We should make sure we use it in the examples.

**Comment by 1chandu** [comment]
@shaojingli @ibgreen 
We are applying polygon offset for this example  (all layers get applied by an offset of -(layerIndex*100) by default). I tried to increase the offset to -(layerIndex*5000), the flickering is gone to some extent, but at higher zoom levels it is still present. If I enable fp64 prop, with existing polygon offset there is not flickering, so should I just enable fp64 on this example by default?

**Comment by ibgreen** [comment]
> should I just enable fp64 on this example by default?

I think that is fine for now.
