### ISSUE TITLE
getTileData accessor cannot access state variables from outside the TileLayer

### ISSUE THREAD

**Issue by sam-coxon** [uber/deck.gl#4119]
I'm using the Tile Layer to fetch geojson tiles and then color them according to another api call. 
My `getTileData` function fetches the tiles, and then loops through the polygons of each tile to get a list of polygon-id's that it will use to fetch data about those shapes (i.e. what color to draw them), which it then puts into a state variable (dictionary of id's -> colors).

The issue is: I want to minimize the number of requests to this api that gives me the colors of the polygons, I know that tiles from different zoom levels will often contain the same shapes, so i don't want to _re-fetch_ all the id's that i have gotten from another zoom level. 

Iif I add all the ids of the shown shapes on one zoom level and put them into a dictionary that i access with `getFillColor`, and then i zoom **_out_** one level, my `getTileData` function does not see that the updated dictionary variable of id's that i created from the first level. How do i make `getTileData` see the most recent  `dictionary` ?

I don't want to use update triggers like:
`updateTriggers={{
    getTileData: dictionary
}}`
because i update `dictionary` in `getTileData` which creates this weird loop.

Is there any way to make `getTileData` aware of the updated `dictionary` variable?

**Comment by Pessimistress** [comment]
Have you tried using `updateTriggers={{getFillColor}}` instead? Technically speaking your tile data has not changed, so re-fetching them is excessive. You only need the sublayers to reevaluate the fill colors.

**Comment by sam-coxon** [comment]
Sorry I'm not sure i explained this well enough.

The coloring is working fine, I have `updateTriggers={{getFillColor}}` already. What i want to avoid is simply refetching the data as you said. To do that i have to see if the id that i would fetch is already in a dictionary from a previously loaded tile. The problem is that the `getTileData` accessor has no awareness of the updated dictionary. 

ex)
`const` [idDictionary, setIdDictionary] = useState({})
....
<TileLayer
   ....
   getTileData={(x,y,z) =>
      for each geoJSON in tile {
         if (id not in dictionary) {
            dictionary[id] = fetch(colorForId(id))
         }   
      }  
   }
`

but within the `getTileData` accessor, dictionary is _**always**_ empty, even though i can see it's being populated outside of the layer

Thank you for the help!

**Comment by Pessimistress** [comment]
I see. The issue is that `setDictionary` does not mutate the `idDictionary` object, but creates a new object. On the other hand, `TileLayer` ignores any subsequent updates to `getTileData`, and the first `getTileData` value only references the initial state (empty object).

Conceptually, you should not use `useState` for caching because updating `idDictionary` is not supposed to trigger a new render. To make the cache persist, you simply do:

```js
const idDictionary = {};

<TileLayer
   ....
   getTileData={(x,y,z) =>
      for (...) {
         if (!(id in idDictionary)) {
            idDictionary[id] = true;
            fetch(id);
         }   
      }  
   }
/>
```

**Comment by sam-coxon** [comment]
Ahhh, I understand completely. Thank you for the quick response and for the explanation. I truly appreciate it!
