### ISSUE TITLE
The polygon layer example in layer-browser needs some tweaking

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#412]
The polygon layer in the example has the "extruded" and "wireframe" check box that doesn't work due to data provided. We should have some ways to disable or remove these two checkbox or at least explicitly tell our users not they are not effective. 

<img width="781" alt="screen shot 2017-03-09 at 1 38 30 pm" src="https://cloud.githubusercontent.com/assets/21322704/23771977/190c54e8-04ce-11e7-9a6e-29fbbd2e2a11.png">

Also, when clicking on the "extruded" box:

<img width="763" alt="screen shot 2017-03-09 at 1 38 51 pm" src="https://cloud.githubusercontent.com/assets/21322704/23771987/25ca91ae-04ce-11e7-9bce-f0afffa41583.png">

**Comment by ibgreen** [comment]
> "extruded" and "wireframe" check box that doesn't work due to data provided. We should have some ways to disable or remove these two checkbox or at least explicitly tell our users not they are not effective

An option could be to fix the data, so that we can show the user the full capability of the layer.

**Comment by shaojingli** [comment]
Fixed in #424
