### ISSUE TITLE
GoogleMapsOverlay: updateTrigger not working.

### ISSUE THREAD

**Issue by lovanva** [uber/deck.gl#4120]
Hello,

We have recently switched to google maps and I am adding a GoogleMapsOverlay with a GeoJsonLayer layer on the the map. This loads fine with the fillColor for each polygon. However, when trying to trigger an update to change the fillColor nothing happens. Could someone please point me in the right direction? Code snippet below:

const overlay = new GoogleMapsOverlay({
        layers: [
          new GeoJsonLayer({
            id: 'harvest',
            data: featureCollection,
            // Styles
            visible: true,
            filled: true,
            pointRadiusMinPixels: 2,
            opacity: 1,
            getFillColor: f => this.styleHarvestFeature(f),
            stroked: false,
            // Interactive props
            pickable: true,
            autoHighlight: false,
            onHover: this.updateTooltip,
            onClick: this.updateTooltip,
			//yieldMin and yieldMax values are updated onChange of input control.
            updateTriggers: {
              getFillColor: [this.yieldMax, this.yieldMin]
            },
            parameters: {
              depthTest: false,
            }
          })
        ]
      });

**Comment by Pessimistress** [comment]
Where are you updating the updateTriggers?

**Comment by lovanva** [comment]
Thank you for your response. I have figured out the issue by creating another function to update the layer using overlay.setProps({layers: [new GeoJsonLayer({......})]})

**Comment by Pessimistress** [comment]
Try add prop `style: {zIndex: <number>}`

**Comment by lovanva** [comment]
Setting zIndex did not work for me, however I found the issue to be different layers are added to different google mapManes which causes some layers to always be on top. When I create layers of the same type, for example an OverlayLayer, it will place the last rendered layer on top.
