### ISSUE TITLE
How intelligent is decks rendering?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4130]
Hi! Had some questions regarding the intelligence of decks rendering engine...

- Does deck only render objects (i.e., polygons, points, etc) that are within the users current viewing extent/rectangle?
- Does deck perform deduplication of object's that overlay another object (i.e., duplicate points, polygons, etc)?
- Would there be any documentation that goes into detail of the intelligence of the rendering engine?

Thanks!

**Comment by Pessimistress** [comment]
> Does deck only render objects (i.e., polygons, points, etc) that are within the users current viewing extent/rectangle?

No. Currently only `TileLayer` and `Tile3DLayer` fetch/render data on demand.

> Does deck perform deduplication of object's that overlay another object (i.e., duplicate points, polygons, etc)?

No. The use cases that deck targets require us to minimize CPU time and get data on screen as fast as possible. Pre-processing data like this is expensive. It can be done using other libraries prior to feeding data to deck.gl, should the application choose so.
