### ISSUE TITLE
Regresion while generating icon atlas with inline data url using deck.gl 8

### ISSUE THREAD

**Issue by Nekronik** [uber/deck.gl#4132]
#### Description
When providing the `getIcon` function in an `IconLayer` with `url:"data:image/svg+xml;base64,PHN...mc+"` an error is thrown.
This works in version 7 including latest release.
If the `url` is an asset instead of inline data it works fine in version 8.

#### Repro Steps
```
getIcon: () => ({
  id: 'generatedId',
  url: 'DATA',
  width: 96,
  height: 96
}
```
`data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjQiIGhlaWdodD0iMTI0IiB2aWV3Qm94PSIwIDAgNTAgNTAiPgogICAgPGRlZnM+CiAgICA8ZmlsdGVyIGlkPSJkcm9wLXNoYWRvdyIgeD0iLTUwJSIgeT0iLTUwJSIgd2lkdGg9IjMwMCUiIGhlaWdodD0iMzAwJSI+CiAgICAgIDxmZUdhdXNzaWFuQmx1ciBpbj0iU291cmNlQWxwaGEiIHN0ZERldmlhdGlvbj0iNSIvPgogICAgICA8ZmVPZmZzZXQgZHg9IjAiIGR5PSIwIiByZXN1bHQ9Im9mZnNldGJsdXIiLz4KICAgICAgPGZlRmxvb2QgZmxvb2QtY29sb3I9IiMwMDAwMDAiLz4KICAgICAgPGZlQ29tcG9zaXRlIGluMj0ib2Zmc2V0Ymx1ciIgb3BlcmF0b3I9ImluIi8+CiAgICAgIDxmZU1lcmdlPgogICAgICAgIDxmZU1lcmdlTm9kZS8+CiAgICAgICAgPGZlTWVyZ2VOb2RlIGluPSJTb3VyY2VHcmFwaGljIi8+CiAgICAgIDwvZmVNZXJnZT4KICAgIDwvZmlsdGVyPgogICAgPC9kZWZzPgogICAgPGNpcmNsZSBjeD0iNTAlIiBjeT0iNTAlIiByPSIxNSIgZmlsbD0iYmxhY2siIGZpbHRlcj0idXJsKCNkcm9wLXNoYWRvdykiLz4KICAgIDxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDcsIDcpIj4KICAgICAgPHBhdGggZmlsbD0iIzRiNTA3MCIgc3Ryb2tlLXdpZHRoPSIzIiBkPSJNMTggMi4wODQ1IGEgMTUuOTE1NSAxNS45MTU1IDAgMCAxIDAgMzEuODMxIGEgMTUuOTE1NSAxNS45MTU1IDAgMCAxIDAgLTMxLjgzMSIgc3Ryb2tlPSIjZmZmIi8+CiAgICAgIDxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZS13aWR0aD0iMyIgZD0iTTE4IDIuMDg0NSBhIDE1LjkxNTUgMTUuOTE1NSAwIDAgMSAwIDMxLjgzMSBhIDE1LjkxNTUgMTUuOTE1NSAwIDAgMSAwIC0zMS44MzEiIHN0cm9rZT0iIzNiZWRiOSIgc3Ryb2tlLWRhc2hhcnJheT0iMTQsIDEwMCIvPgogICAgPC9nPgogICAgPC9zdmc+`

#### Environment (please complete the following information):
 - Framework Version: all versions of deck.gl 8
 - Browser Version: Chrome 79.0
 - OS: KDE Neon

#### Logs
```
icon-manager.js:348 Error: Could not load image blob:https://localhost/04e57b3d-c127-48ae-8eff-bed4b2d8a115: [object Event]
    at Image.image.onerror [as __zone_symbol__ON_PROPERTYerror] (parse-to-image.js:76)
    at Image.wrapFn (zone-evergreen.js:1191)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:465)
    at invokeTask (zone-evergreen.js:1603)
    at Image.globalZoneAwareCallback (zone-evergreen.js:1629)
```

Which comes from [here](https://github.com/uber-web/loaders.gl/blob/94b076fd8ea9617c3d4519e9f3684bf657331dc6/modules/images/src/lib/parsers/parse-to-image.js#L41)

**Comment by Pessimistress** [comment]
Fixed in 8.0.6
