### ISSUE TITLE
Google Maps overlay shows nothing when zoomed out too far

### ISSUE THREAD

**Issue by pwambach** [uber/deck.gl#4144]
#### Description
We have a Google Map and use the Deck.Gl GoogleMapOverlay to sync the deck.gl layers. The problem is when zooming out so far that more than 360 degree of longitude is visible all deck.gl layers disappear.
The expected behavior would be that the points stay visible on the map.
Theoretically they should be duplicated if the same location on earth appears twice on screen but I guess this is another issue.

The console logs this warning `deck: Pixel project matrix not invertible`.

#### Repro Steps
I made a simple example on codepen: https://codepen.io/pwambach/pen/WNbKNzm
Depending on the screen resolution the two red dots around LatLng 0/0 disappear when zooming out 2 or 3 levels.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.5
 - Browser Version: Chrome 79
 - OS: Mac OS X 10.15

**Comment by Pessimistress** [comment]
This will be fixed in 8.1.0. You can test the feature with deck.gl@^8.1.0-alpha.
