### ISSUE TITLE
Since v8 layers disappear when zooming in/out [NVIDIA GeForce GT 750M]

### ISSUE THREAD

**Issue by ilyabo** [uber/deck.gl#4145]
#### Description
Since version 8.0.0 all layers only appear after zooming in and disappear when zooming out.

The issue can be reproduced with deck.gl 8.0.0 and 8.0.6, but **_not with_** 7.3.13. 

My colleague doesn't experience the same issue, so it's likely something hardware-specific. My graphic card is NVIDIA GeForce GT 750M 2 GB.

#### Repro Steps
Open the [deck.gl documentation for any layer](https://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer). The layer won't be visible:

![image](https://user-images.githubusercontent.com/351828/72346038-6fcf1e00-36d5-11ea-8341-6418af749f4c.png)

After zooming in the layer becomes visible and disappears again when zooming out:

![deckgl8-bug2](https://user-images.githubusercontent.com/351828/72345892-16ff8580-36d5-11ea-9e6f-fa179335cfb0.gif)

The issue appears to concern all the layers:

![deckgl8-bug](https://user-images.githubusercontent.com/351828/72345722-b07a6780-36d4-11ea-9afb-11c824a98fb1.gif)

#### Environment (please complete the following information):
 - Framework Version: 8.0.0, 8.0.6
 - Browser Version: reproducible in Chrome 79, Firefox 71 and Safari 13.0.4
 - OS: Mac OS X 10.15.2

<img src=https://user-images.githubusercontent.com/351828/72346377-23381280-36d6-11ea-9ba8-d01621550773.png width=300>

#### Logs
Nothing suspicious in the logs.

**Comment by Pessimistress** [comment]
@tsherif @1chandu Looks like it happens when zoom<12. Could it be an issue in `tan_fp32`?

**Comment by tsherif** [comment]
@ilyabo Are you using Chrome? If so can, you navigate to chrome://gpu and dump the results here? In particular, I'm interested in the values for GL_VENDOR, GL_RENDERER, and GL_VERSION.

@Pessimistress It's possible as I suspect Chrome uses the Intel GPU by default, so it would be using the workaround. That said, I don't believe anything change there in 8.0?

**Comment by ilyabo** [comment]
I can reproduce the issue with Chrome, Firefox and Safari. Something has definitely changed in deck.gl   as the issue is not reproducible with 7.x. I tried with a simple test app and the issue goes away once I downgrade to 7. I will check the settings in Chrome later today.

**Comment by ilyabo** [comment]
Here's the info from chrome://gpu on my MacBook:
![image](https://user-images.githubusercontent.com/351828/72416234-7e214680-3776-11ea-9ac6-9ae05f07bd6b.png)

**Comment by tsherif** [comment]
Interesting. Are you able to use the Intel GPU on your machine? I believe if you go into the Energy Saver settings and enable "Automatic graphics switching", Chrome should start using the Intel GPU (you can verify via chrome://gpu again). If that works, let us know if the problem persists.

@Pessimistress I wonder if there are some discrete GPUs that require the workaround.

**Comment by Pessimistress** [comment]
The Intel bug is a precision issue, it shouldn't make the scene disappear.

**Comment by ilyabo** [comment]
I tried disabling "Automatic graphics switching", but in chrome://gpu still says "NVIDIA". But it makes sense, NVIDIA is the high-performance one:
![image](https://user-images.githubusercontent.com/351828/72469011-c2483180-37de-11ea-9712-843789fc9830.png)
I googled, but haven't found a simple way of doing it in Catalina.

**Comment by ilyabo** [comment]
I asked around and one of my colleagues could reproduce the issue on his machine (others could not). He has the same graphics card as me:  
<img src=https://user-images.githubusercontent.com/351828/72514147-6e753100-384e-11ea-9975-89453cab9191.png width=350>

**Comment by ilyabo** [comment]
Here's the test app I used: https://5e1eea178225f3153d6f3ce2--deck-gl-8-test.netlify.com/
The yellow outline doesn't show up for us.

**Comment by Pessimistress** [comment]
@ilyabo We are still trying to get hold of a machine that reproduces the issue. Can you go to https://codepen.io/Pessimistress/pen/jOEzbvV and try change the deck dependency to the following versions:

- 8.0.0-beta.2
- 8.0.0-beta.1
- 8.0.0-alpha.2
- 8.0.0-alpha.1

**Comment by ilyabo** [comment]
Big thanks for looking at this, guys!

@Pessimistress I tried playing with the Codepen, none of the 8.x.x versions worked. Only see the white background with no layers. In the Console I see this:

```"luma.gl: `Buffer.type` is deprecated and will be removed in a later version. Use `Buffer.accessor.type` instead"```

7.3.13 does work:
![image](https://user-images.githubusercontent.com/351828/72568190-d6ac2d00-38b7-11ea-8f64-0727fb495657.png)

**Comment by Pessimistress** [comment]
Can you try these links:
https://cdn.statically.io/gh/Pessimistress/Pessimistress.github.io/master/test/app-830b0ff.html
https://cdn.statically.io/gh/Pessimistress/Pessimistress.github.io/master/test/app-b73b81a.html

**Comment by ilyabo** [comment]
@Pessimistress 
![image](https://user-images.githubusercontent.com/351828/72595937-41d31f00-390b-11ea-98d9-eca2521d84da.png)

**Comment by Pessimistress** [comment]
Thank you! That helps pinpoint the commit that broke it. Can you see if this version works:

https://cdn.statically.io/gh/Pessimistress/Pessimistress.github.io/master/test/app-707d4a1.html

**Comment by ilyabo** [comment]
@Pessimistress No, I only see the dots after zooming in.

**Comment by Pessimistress** [comment]
Published 8.0.9.
