### ISSUE TITLE
Getting the "Global" WebGL Context

### ISSUE THREAD

**Issue by ilan-gold** [uber/deck.gl#4154]
Hello again, please forgive me if this is answered somewhere or if the answer is clear if you are very accustomed to WebGL.  I wish to get context that all layers share (of which there is only one from what I can tell) so I can use it to render a `Texture2D` via a `BitmapLayer` sublayer of a `Tile` from `TileLayer`.  [`BitmapLayer`](https://github.com/uber/deck.gl/blob/master/docs/layers/bitmap-layer.md) can accept a `Texture2D` but this needs a WebGL rendering context.  Currently I have a hacky way of doing it but it is definitely not correct.  How should this be passed in?  For reference, here is the function I have overriden in [`Tile`](https://github.com/uber/deck.gl/blob/853d9724343be7a85187c27ea20167cbefc0e6c3/modules/layers/src/base-tile-layer/utils/tile.js) to get it to (kind of) work but this is clearly wrong as the `this.layer` sometimes has not been created by the time the `Promise` resolves:

```
_loadData() {
    const {
      x, y, z, bbox,
    } = this;
    if (!this.getTileData) {
      return null;
    }

    return this.getTileData({ x, y, z })
      .then((buffers) => {
        const texture = new Texture2D(this.layer.context.gl, {
          width: 512,
          height: 512,
          format: GL.RGB,
          data: buffers.data,
          pixelStore: {
            [GL.UNPACK_FLIP_Y_WEBGL]: true
          },
          mipmaps: true
        });
        this._data = texture;
        this._isLoaded = true;
        this.onTileLoad(this);
        return texture;
      })
      .catch((err) => {
        this._isLoaded = true;
        this.onTileError(err);
      });
  }
```
I feel like you could possibly somehow do it with `onWebGLInitialized` of the `DeckGL` component but I am not clear on this.

I would be happy to update the BitmapLayer documentation to make this clear.  Additionally let me know if I am being not clear about this so I can clarify.

**Comment by Pessimistress** [comment]
`onWebGLInitialized` is the way to go. 

```js
_onWebGLInitialized(gl) {
  this.setState({gl});
}

render() {
  const {gl} = this.state;

  const layers = gl ? [new TileLayer(...)] : [];

  return <DeckGL ... layers={layers} onWebGLInitialized={this._onWebGLInitialized} />
}
```

**Comment by ilan-gold** [comment]
Thank you, that worked perfectly well - the ternary operator did the trick :)
