### ISSUE TITLE
Add getPixelOffset to IconLayer

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4156]
#### Target Use case
Adding the getPixelOffset (Function|Array|, optional) to the IconLayer similar to the existing TextLayer's getPixelOffset would allow me to place multiple icons at the same position (i.e., lat/lon/alt) and offset them so they do not overlap. This would be useful in providing informational icons around a main icon.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by jfuehner** [comment]
@Pessimistress, I cobbled together a bit of a hack for the time being in my IconLayer's getPosition function... It works somewhat but is not ideal...

`
                    getPosition: d => {
                        let [pixelOffsetX, pixelOffsetY] = [0, -0.2];

                        let deck = val;
                        let viewPort = deck.getViewports()[0];
                        let coords = d.coordinates;
                        let projCoords = viewPort.project(coords);
                        let projCoordsX = projCoords[0];
                        let projCoordsY = projCoords[1];
                    
                        let newProjCoordsX = (projCoordsX+pixelOffsetX);
                        let newProjCoordsY = (projCoordsY+pixelOffsetY);

                        const unprojCoords = viewPort.unproject([newProjCoordsX, newProjCoordsY]);

                        return unprojCoords;
                    }
`

**Comment by Pessimistress** [comment]
I think this is a reasonable feature to add.

While we work on this, you can try:
- assign different angles to the icons at the same location
- use the TextLayer with a webfont.

**Comment by Pessimistress** [comment]
#4205
