### ISSUE TITLE
IconLayer not working properly on MacOS with deck.gl 8.0.7

### ISSUE THREAD

**Issue by ruizmarc** [uber/deck.gl#4159]
#### Description

IconLayer is not working properly on MacOS. Icons are not being showed. We noticed that it is working fine on Windows and Linux, but not on MacOS. We first noticied it on our own project, as icons were not being showed in the map only on MacOS (doesn't matter the browser). And then we saw that it is not working find neither in the example (in the example the icons appear, but not in the proper position). 

#### Repro Steps

This is how it looks like when we enter to the example page with MacOS.

**MacOS**

![image](https://user-images.githubusercontent.com/5717082/72546373-f8db8600-388a-11ea-9a63-0d23ad784964.png)

![image](https://user-images.githubusercontent.com/5717082/72546262-c3369d00-388a-11ea-83bc-09fa59e6c034.png)

And this is how it looks like in Windows or Linux

**Windows** 

![image](https://user-images.githubusercontent.com/5717082/72546513-2b857e80-388b-11ea-979d-bea3597574fa.png)

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]: 8.0.7
 - Browser Version: [e.g. Chrome 71.0]: Any browser
 - OS: [e.g. Mac OS X 10.4]: MacOS 10.15.2

#### Logs

No logs were shown

**Comment by Pessimistress** [comment]
@ruizmarc I cannot reproduce it on my mac. Can you elaborate more on "the icons appear, but not in the proper position"? Is it possible to record a video?

What is your GPU?

@tsherif Could be related to #4145 ?

**Comment by Pessimistress** [comment]
@ruizmarc Just to check if this is the same issue as #4145 - are icons displayed correctly when zoom>12 ?

**Comment by ruizmarc** [comment]
> @ruizmarc I cannot reproduce it on my mac. Can you elaborate more on "the icons appear, but not in the proper position"? Is it possible to record a video?

This is what I tried to show with the two screenshots on MacOS. In the first one you can see there are no icons, in the second one (south pole) all the icons appear. However, on Windows and Linux, all the icons appear around the world. So this is why I was saying they appear, but not in the proper position. However, in our project they even don't appear. 

> What is your GPU?

<img width="246" alt="image" src="https://user-images.githubusercontent.com/5717082/72605243-ae0a4e80-391c-11ea-95f3-e8eacb335953.png">

> @ruizmarc Just to check if this is the same issue as #4145 - are icons displayed correctly when zoom>12 ?

It is not working for me at any zoom level neither in my project nor the example.

**Comment by Pessimistress** [comment]
@ruizmarc Can you visit https://codepen.io/Pessimistress/pen/jOEzbvV and report if it renders on your box; then change the deck.gl dependency to 8.1.0-alpha.1 and see if it fixes your issue?

**Comment by ruizmarc** [comment]
@Pessimistress I have just checked it. When entering to your codepen it was not rendering. However, when I changed it to 8.1.0-alpha.1 I could see a map with a point in France, the same I could see in other computers! It seems it is solved with this new version.

**Comment by Pessimistress** [comment]
Published 8.0.9.
