### ISSUE TITLE
pydeck: Document how to pass String arguments

### ISSUE THREAD

**Issue by dakoop** [uber/deck.gl#4164]
Thanks for this work. In the [Expression Parsers subsection](https://github.com/uber/deck.gl/blob/master/bindings/pydeck/docs/layer.rst#expression-parsers-in-pydeck-layer-arguments), I suggest adding a note that to have a string not be interpreted as an function, you need to nest quotes. For example, to set HexagonLayer.colorAggregation, one has to specify "Mean" as `color_aggregation="'MEAN'"` in pydeck. It may also be useful to link to the recently updated [conversion reference](https://github.com/uber/deck.gl/blob/master/docs/api-reference/json/conversion-reference.md) which was useful when figuring out how the "@@=" strings were interpreted.

**Comment by ajduberstein** [comment]
Yes, I think this is a valid point. We'll be releasing new documentation in mid-February and I'll cover the expression parser in more depth.

**Comment by ajduberstein** [comment]
Addressed in #4270
