### ISSUE TITLE
error while initializing GeoJsonLayer

### ISSUE THREAD

**Issue by titivermeesch** [uber/deck.gl#4176]
Hi,

I created a map with DeckGL on it, and everything works fine, until it don't.
I have a component that is rendering an EditableGeoJsonLayer from nebula.gl and it works, but when I switch from a page in my app and go back to the map it gives me this : 
`Error: deck.gl: assertion failed.` 3 times, for PathLayer, GeojsonLayer and EditableGeojsonLayer.
This don't happen if you reload the page, only if you switch pages inside the app.
This is the useEffect that handles this editable layer : 

`  useEffect(() => {
    const editablePolygonLayer = new EditableGeoJsonLayer({
      id: layerName,
      mode: mapMode,
      selectedFeatureIndexes: selectedFeatureIndexes,
      data: mapEditFeatures,
      pointRadiusScale: 0,
      pointRadiusMaxPixels: 0,
      ...editableLayerColorset,
      onEdit: ({ updatedData, editContext }) => {
        handleGeoJsonEdit(updatedData, editContext)
      },
    })
    if (mapLayers.filter(l => l.id === layerName).length === 0) {
      addLayer(editablePolygonLayer)
    } else {
      const newLayers = mapLayers.map(layer => {
        if (layer.id === layerName) {
          return editablePolygonLayer
        }
        return { ...layer }
      })
      setLayers(newLayers)
    }
  }, [mapMode, mapEditFeatures, selectedFeatureIndexes])`

Am I doing something wrong?

**Comment by vladpalkanov** [comment]
The same for me just now. 

```jsx
const Editor = props => {
  const [data, setData] = useState(() => props.data)

  const layer = useMemo(() => {
    return new EditableGeoJsonLayer({
      id: 'geojson-layer',
      data,
      mode: DrawPolygonMode,
      selectedFeatureIndexes: [],
      onEdit: ({ updatedData }) => {
        setData(updatedData)
      },
    })
  }, [props.data])

  return (
    <Deck  initialViewState={INITIAL_VIEW_STATE}  layers={[editor.layer]}>
      <StaticMap
          reuseMaps
          mapStyle="mapbox://styles/mapbox/satellite-v9"
          preventStyleDiffing={true}
          mapboxApiAccessToken={MAPBOX_TOKEN}
        />
    </Deck>
  )
}
```

```
assert.js:6 Uncaught Error: deck.gl: assertion failed.
    at assert (assert.js:6)
    at DeckPicker._drawAndSample (deck-picker.js:308)
    at DeckPicker._pickClosestObject (deck-picker.js:158)
    at DeckPicker.pickObject (deck-picker.js:67)
    at Deck._pick (deck.js:391)
    at Deck._pickAndCallback (deck.js:550)
    at Deck._onRenderFrame (deck.js:704)
    at AnimationLoop.onRender (animation-loop.js:252)
    at AnimationLoop._renderFrame (animation-loop.js:340)
    at AnimationLoop.redraw (animation-loop.js:178)
    at renderFrame (animation-loop.js:279)
assert @ assert.js:6
_drawAndSample @ deck-picker.js:308
_pickClosestObject @ deck-picker.js:158
pickObject @ deck-picker.js:67
_pick @ deck.js:391
_pickAndCallback @ deck.js:550
_onRenderFrame @ deck.js:704
onRender @ animation-loop.js:252
_renderFrame @ animation-loop.js:340
redraw @ animation-loop.js:178
renderFrame @ animation-loop.js:279
requestAnimationFrame (async)
requestAnimationFrame @ request-animation-frame.js:5
_requestAnimationFrame @ animation-loop.js:327
renderFrame @ animation-loop.js:280
requestAnimationFrame (async)
requestAnimationFrame @ request-animation-frame.js:5
_requestAnimationFrame @ animation-loop.js:327
renderFrame @ animation-loop.js:280
requestAnimationFrame (async)
requestAnimationFrame @ request-animation-frame.js:5
_requestAnimationFrame @ animation-loop.js:327
renderFrame @ animation-loop.js:280
...
```

**Comment by Pessimistress** [comment]
You cannot reuse a layer instance after it’s removed. Just create a new one.

**Comment by titivermeesch** [comment]
So I suppose this remove happens when the map unmounts? Because I'm not removing any layers by myself.

**Comment by Pessimistress** [comment]
Either you removed the layer or unmounted DeckGL, the layer must be finalized to release the resources it created. Otherwise we will create a memory leak. Finalized layer cannot be reused.

**Comment by titivermeesch** [comment]
Thanks for that, I'll let you know if I'm still having an error

**Comment by titivermeesch** [comment]
So in the DeckGL component I have a prop like this: `layers={mapLayers}`
Do you mean that mapLayers should just be emptied? With null or an empty Object or something?

**Comment by Pessimistress** [comment]
I can't tell what `mapLayers` contains from your code (you need to wrap a code block with three back ticks ` instead of one). The array must be regenerated (by calling `new SomethingLayer(...)`) when you remount DeckGL.

**Comment by ebbishop** [comment]
@titivermeesch How did you end up solving this? I'm running into a very similar problem.

**Comment by titivermeesch** [comment]
> @titivermeesch How did you end up solving this? I'm running into a very similar problem.

I has been a long time, so I can't directly remember. Do you mind sharing your implementation? Maybe I can figure something out based on the experience I had with DeckGL from the past year

**Comment by suryakumara** [comment]
Hi, I have similiar problem when I use EditableGeoJsonLayer.

**Comment by titivermeesch** [comment]
> Hi, I have similiar problem when I use EditableGeoJsonLayer.

What if you pass in an empty array to that layer as data? If that works, please check that your data structure is correct. There is probably something wrong with the data you feed

**Comment by danilo-css** [comment]
The way I ended up solving this problem was using the parameter "visible" inside the layer configs instead of using a conditional "if" statement to add the layer to a list.

The layer will always be pushed to the list and rendered no matter what, just it's visibility will be able to be turned on or off.

**Comment by charlieforward9** [comment]
I got this error when trying to load a `GeoJsonLayer` into a `MapboxOverlay` control with `interleave: true`. When I removed the interleave, it solved my problem.
