### ISSUE TITLE
when i load the latest deck.gl, i get an error loading 2 versions of luma.gl

### ISSUE THREAD

**Issue by adnan-wahab** [uber/deck.gl#4187]
#### Repro Steps
npm I

#### Environment (please complete the following information):
linux

#### Logs
{
  "name": "react-mapbox-webpack-2",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "start-local": "webpack-dev-server --env.local --progress --hot --open",
    "start": "webpack-dev-server --progress --hot --open",
    "build": "webpack -p"
  },
  "dependencies": {
    "css-loader": "^3.2.0",
    "csv": "^5.3.0",
    "d3": "^5.12.0",
    "d3-request": "^1.0.6",
    "deck.gl": "^8.0.9",
    "grommet": "^2.10.0",
    "js-md4": "^0.3.2",
    "lodash": "^4.17.15",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-map-gl": "^5.0.0",
    "style-ext-html-webpack-plugin": "^4.1.2",
    "styled-components": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.0",
    "html-webpack-plugin": "^3.0.7",
    "style-loader": "^1.0.0",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.1"
  }
}

**Comment by Pessimistress** [comment]
Remove your lock file and do a clean install.
