### ISSUE TITLE
Follow/track object as it moves across map?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4188]
I have a use-case where I need to provide our end-users with the ability to follow/track an object as it moves. Was curious if there is a recommended approach for such a case?

I tried simply just updating the deck **viewState** object as the object moves but that the map does not move. I also tried calling **jumpTo** on the map object but that too doesn't seem to yield the expected results... 

Appreciate any insights on this...

**Comment by Pessimistress** [comment]
Please share your code of whatever you have tried. It is impossible to tell what went wrong from your description.

**Comment by jfuehner** [comment]
@Pessimistress 

Here is an example of trying to modify viewState [https://codesandbox.io/s/laughing-allen-jocvf](https://codesandbox.io/s/happy-bogdan-gh8o2)

Here is an example of using mapbox's jumpTo [https://codesandbox.io/s/laughing-allen-jocvf](https://codesandbox.io/s/laughing-allen-jocvf)

You can set the mapbox access token (mapAccessToken) and the tracked aircraft callsign (trackedAircraftCallsign) inside data.js as appropriate...

**Comment by Pessimistress** [comment]
I don't see you calling `deck.setProps({viewState})` anywhere.

**Comment by jfuehner** [comment]
@Pessimistress, sorry about that... Not sure what happened. Please take a look at these two new urls...

Using viewState...
[https://codesandbox.io/s/hungry-spence-itcky](https://codesandbox.io/s/hungry-spence-itcky)

Using jumpTo...
[https://codesandbox.io/s/lucid-breeze-8xojd](https://codesandbox.io/s/lucid-breeze-8xojd)

**Comment by Pessimistress** [comment]
`onViewStateChange` is not fired when you call `setProps({viewState})` yourself, so you need to call `map.jumpTo` at the same time.

**Comment by jfuehner** [comment]
@Pessimistress, I’ll give that a go. Although that does seem a bit counterintuitive. I would think anytime viewstate changes then onViewStateChange would fire?

**Comment by jfuehner** [comment]
@Pessimistress, so I tried calling jumpTo in addition to setting viewState as seen in this code example... [https://codesandbox.io/s/ecstatic-payne-s5cr5](https://codesandbox.io/s/ecstatic-payne-s5cr5)

However, it still does not appear to be working as desired. I'm unable to zoom in/out...

**Comment by Pessimistress** [comment]
You cannot use both the `initialViewState` and `viewState` props. Your view state is either controlled or not controlled. Once you supply `viewState`, it is always used over the internally tracked view state, see [documentation](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=initialviewstate-object-).

Therefore, on `onViewStateChange`, you have to manually update deck's view state by calling `deck.setProps({viewState})`. We do not trigger `onViewStateChange` again because that would cause an infinite loop.

**Comment by jfuehner** [comment]
I see, thank you for the clarification. Not setting initialViewState and handling viewState myself appears to work like a charm.
