### ISSUE TITLE
Layers unable to handle multiple click when using Popup

### ISSUE THREAD

**Issue by cptoon** [uber/deck.gl#4192]
#### Description
Layers were not interactive properly when using React-map-gl's Popup by MapContext. It unable to handle multiple click on deck's layer.

#### Repro Steps
With out MapContext I able to gather number of click though layer interactive's ev > tabCount object, but it does not work when I apply MapContext into deck component.

```
export default class MapWithContext extends Component {
  render() {
    const layer = [
      new GridCellLayer({
        id: 'grid-layer',
        data,
        pickable: true,
        extruded: false,
        cellSize: 250,
        coverage: 0.95,
        opacity: 0.1,
        getPosition: d => d.coordinates,
        onClick: (info, ev) => console.log(ev),
      })
    ]

    return (
      <DeckGL
        ContextProvider={MapContext.Provider}
        initialViewState={initialViewState}
        controller={{doubleClickZoom: false}}
        layers={layer}
      >
        <StaticMap
          key="baseMap"
          mapboxApiAccessToken={MAPBOX_TOKEN}
        />
        <Popup
          key="popup"
          longitude={-122.3985}
          latitude={37.702}
        >
          popup
        </Popup>
      </DeckGL>
    );
  }
}

```

#### Environment (please complete the following information):
 - Framework Version: deck@8.0.9
 - Browser Version: Chrome 79.0
 - OS: OSX

**Comment by Pessimistress** [comment]
Can you explain "cannot handle" and "does not work"? What is the expected behavior and what is the actual behavior?

**Comment by cptoon** [comment]
@Pessimistress 
I expected the layer would call onClick function whenever that layer was clicked.
And when I double or triple clicks on layer, the onClick function should called and the value of tapCount should return 2 and 3 respectively.
But currently, onClick function only work with single click and it do nothing when double clicks on the layer.

**Comment by Pessimistress** [comment]
This should be fixed in the latest react-map-gl. You need to remove your yarn.lock and reinstall dependencies.

**Comment by cptoon** [comment]
@Pessimistress It is working now, thank you for your help.
