### ISSUE TITLE
Luma debug logging isn't working

### ISSUE THREAD

**Issue by goszczynskip** [uber/deck.gl#4195]
#### Description
Can't see luma debug info anymore in newest deck.gl version.

#### Repro Steps
build dev react app with map and any GeoJsonLayer.  (NODE_ENV === "development")
 
run in your console:
```
luma.log.enable()
luma.log.level = 2
```

uniforms and attributes aren't displayed in console.

Browser: Firefox 72.0.1 (Windows)

**Comment by Pessimistress** [comment]
@tsherif

**Comment by Pessimistress** [comment]
This should be fixed in luma.gl 8.0.5.
