### ISSUE TITLE
React DeckGL tooltip param

### ISSUE THREAD

**Issue by arraydude** [uber/deck.gl#4197]
#### Description
Can the React component also have a tooltip param, just like the non-React constructor? We want to do this: 

https://github.com/uber/deck.gl/blob/c4820536277ecefbdf062145a02651e2c7847670/bindings/pydeck/pydeck/io/templates/index.j2#L53

I could not find a simples way like this using the React component

**Comment by Pessimistress** [comment]
The [getTooltip](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=gettooltip-function-optional-) prop is available for both the `Deck` class and the `DeckGL` React component.

**Comment by arraydude** [comment]
Thanks @Pessimistress for answering this.

I tried hardcoding the getTooltip prop in this way but it is not being shown:

```jsx
        <DeckGL
          initialViewState={deck.initialViewState}
          height={deck.initialViewState.height}
          width={deck.initialViewState.width}
          layers={this.state.initialized ? deck.layers : []}
          getTooltip={() => ({
            text: 'Testing tooltip text'
          })}
          controller
        >
```

**Comment by Pessimistress** [comment]
Did you enable the `pickable` prop on your layers?

**Comment by arraydude** [comment]
Yes, I'm creating the object using this code:

```python
import pydeck as pdk

UK_ACCIDENTS_DATA = (
    "https://raw.githubusercontent.com/uber-common/"
    "deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv"
)

layer = pdk.Layer(
    "HexagonLayer",
    UK_ACCIDENTS_DATA,
    get_position="[lng, lat]",
    auto_highlight=True,
    elevation_scale=50,
    pickable=True,
    elevation_range=[0, 3000],
    extruded=True,
    coverage=1,
)

# Set the viewport location
view_state = pdk.ViewState(
    longitude=-1.415, latitude=52.2323, zoom=6, min_zoom=5, max_zoom=15, pitch=40.5, bearing=-27.36
)

# Combined all of it and render a viewport
r = pdk.Deck(
    map_style="mapbox://styles/mapbox/light-v9",
    layers=[layer],
    initial_view_state=view_state,
    tooltip={"html": "<b>Elevation Value:</b> {elevationValue}", "style": {"color": "white"}},
)

print(r.to_json())
```

**Comment by Pessimistress** [comment]
Please check your deck.gl version. The tooltip feature was added in 7.3.

**Comment by arraydude** [comment]
Yes!, that was the problem thanks @Pessimistress
