### ISSUE TITLE
Please distribute PyDeck as a conda package

### ISSUE THREAD

**Issue by MarcSkovMadsen** [uber/deck.gl#4201]
#### Target Use case

1. In general a lot of data scientists and analysts working in Python are using the Anaconda distribution. It would be helpfull for them if PyDeck was available as a conda package

2. For me personally I'm trying to add support for PyDeck to [Panel](https://panel.holoviz.org/index.html) to enable users of Python to use Deck.Gl in their awesome interactive apps. Since the main developer is from Anaconda and the users of Panel are primarely using the Ananaconda Distribution it would also help here if PyDeck was distributed as a conda package. See [Panel PyDeck Pull Request](https://github.com/holoviz/panel/pull/960).

#### Proposed feature

Distribute PyDeck as a conda package so that it can be installed via `conda install pydeck`.

#### Additional context

I cannot currently install PyDeck via `conda`

```bash
(panel_dev) C:\repos\private\panel>conda install pydeck
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pydeck

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

but `pip install pydeck` works fine.

**Comment by ajduberstein** [comment]
Thanks for filing, @MarcSkovMadsen – pydeck is now available via conda-forge. You can run `conda install -c conda-forge pydeck` install it.

**Comment by MarcSkovMadsen** [comment]
Thanks.

Panel is now available i Panel. A framework for creating awesome Analytics apps in Python. See https://panel.holoviz.org/reference/panes/DeckGL.html#panes-gallery-deckgl
