### ISSUE TITLE
PathLayer getColor setting all paths to color of first element

### ISSUE THREAD

**Issue by aaronsamkennedy** [uber/deck.gl#4208]
In a playground, I had a large number of paths with varying colors working perfectly. Once I nested them into my actual application, the assigned colors broke. 

```
const findColor = (difficulty) => {
  switch(difficulty) {
    case 'expert':
      return [0, 0, 0];
    case 'difficult':
      return [0, 0, 0];
    case 'intermediate':
      return [17,0,255];
    case 'easy':
      return [51,153,51];
    default:
      return [0,0,0];
  }
};

const polyLine = (props) => {
  
  const data = props.data

  console.log(props.data)
  const layer = new PathLayer({
    id: 'path-layer',
    data,
    pickable: true,
    widthScale: 2,
    widthMinPixels: 1,
    getPath: d => d.path,
    getColor: d => findColor(d.difficulty),
    getWidth: d => 5
  });

  return (<DeckGL viewState={props.viewport} layers={[layer]} />);
};

export default polyLine;
```

They all had the color of the first element in the data array. I have a search bar that filters the data array, and on certain searches, a 3 of the colors will reappear for the remaining paths but once it's cleared they will all reset to the color of the first element. 

      <ReactMapGL
        {...this.state.viewport}
        mapboxApiAccessToken={this.state.MapBoxAPIAccessToken}
        mapStyle={this.state.mapStyle}
        onViewportChange={(viewport) => this.setState({viewport})}
      >
        <PolyLine
          viewport={this.state.viewport}
          data={this.props.data}/>
      </ReactMapGL>

Any advice on what I can do to fix this issue I'm having?

**Comment by aaronsamkennedy** [comment]
To clarify I additionally added a hover and it appears that all properties are stuck on the first element (name and color) to all elements when rendering their paths.

**Comment by aaronsamkennedy** [comment]
Figured it out for the most part. This seems kind of weird to me but I reverted the deck.gl version from 8.0.11 back to 7.3.15 and it works again. Is there something in the new version to replace this feature?

**Comment by Pessimistress** [comment]
Can you make a code sandbox example that reproduces this issue?

**Comment by aaronsamkennedy** [comment]
Of course, I had it replicated in two different local instances but I updated the two versions locally this morning and it seems to have been resolved even though I don't see anything in the changelog. I suppose we can close this.

**Comment by aaronsamkennedy** [comment]
Unfortunately, this issue came back today when 8.0.12 got updated. I tried clearing the node modules and going back to 8.0.11, but that didn't seem to work. Yet is did when I went back to 7.3.15. For some reason, I can't seem to get it to work in code sandbox though, I can get each version to work, respectively, if I build two separate instances, but I get a duplicate version error if I try to change the version in the sandbox. https://codesandbox.io/s/vigilant-elbakyan-sehxl

**Comment by Pessimistress** [comment]
I see each path in different colors. Are you seeing something different? Can you report your os, browser, and gpu?

**Comment by aaronsamkennedy** [comment]
Of course, I'm on macOS Catalina 10.15.2, Chrome  79.0.3945.130, and my GPU is Intel Iris Plus Graphics 655 1536 MB. 

The only change between these two photos was the deck.gl version on the local instance at least. 

<img width="734" alt="Screen Shot 2020-01-30 at 4 18 21 PM" src="https://user-images.githubusercontent.com/36516690/73558706-f5123c80-4410-11ea-9840-1e25580c3da3.png">

<img width="776" alt="Screen Shot 2020-01-30 at 4 00 47 PM" src="https://user-images.githubusercontent.com/36516690/73558707-f5123c80-4410-11ea-926e-c3e018605725.png">

**Comment by jkbktl** [comment]
I am having an issue with same colors as well on my project (it was working yesterday). I am using v8.0.11. (MacOS Catalina 10.5.2, both Chrome [79.0.3945.130] and Safari [13.0.4], Intel Iris Plus Graphics 650)

**Comment by Pessimistress** [comment]
Can you post a screenshot of the code sandbox link above as rendered on your machine? I cannot reproduce this issue.

**Comment by jkbktl** [comment]
<img width="409" alt="Screenshot 2020-02-05 01 01 05" src="https://user-images.githubusercontent.com/520927/73798480-2f822d80-47b3-11ea-899c-a329ea0a8ea5.png">

It looks fine. But I don't think it's machine related as I have my project deployed and it's same on every machine (I can't share it tho). I also had an issue with dash extension, it didn't work for part of the path (it had worked), like it couldn't accept different attributes for multiple objects.

I have found a workaround. I split that array into multiple PathLayers, so it works for me, but it has some visual glitches now:
<img width="842" alt="Screenshot 2020-02-05 01 04 30" src="https://user-images.githubusercontent.com/520927/73798657-cfd85200-47b3-11ea-8f40-689de8056970.png">

**Comment by Pessimistress** [comment]
> It looks fine

I am confused. What is the purpose of the example if it does not reproduce the issue? @aaronsamkennedy Can you either:

- Update the code sandbox so that it renders paths in wrong colors
- Provide steps that I can follow (click a button, etc.) to make the paths appear in wrong colors

**Comment by aaronsamkennedy** [comment]
I'll see if I can get it to replicate in a sandbox, again having trouble with changing the versions of the deck in codesandbox. That said I have it replicated locally so I should be able to get it up.

**Comment by aaronsamkennedy** [comment]
Okay, I think that I got it to replicate in code sandbox! https://codesandbox.io/s/deckgl-c5lg7. I mean I hope its something simple but the only solution I've been able to find is rolling back to previous versions of deck.gl

**Comment by Pessimistress** [comment]
@aaronsamkennedy Your paths are malformed - each path is supposed to be an array of points, but you are occationally providing an array of array of points.

Add this to your `getRuns` it will work:

```js
  let path = data.features[i].geometry.coordinates;
  if (path.length === 1) {
    path = path[0];
  }

  ...
```

If you are unsure about how to interpret the source data, it's easier to use the `GeoJsonLayer` than the `PathLayer` directly.

**Comment by aaronsamkennedy** [comment]
That did it, thanks so much! Sorry for that wild goose chase
