### ISSUE TITLE
pydeck ViewState Update

### ISSUE THREAD

**Issue by swha03** [uber/deck.gl#4217]
![image](https://user-images.githubusercontent.com/23448719/73545172-29701200-447e-11ea-8972-d87b4d306648.png)

I did the same as the picture above.
However, the FlyToInterpolator does not work properly and Map control does not work either.
Am I not using it properly?

```python
import pandas as pd

UK_ACCIDENTS_DATA = 'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv'

pd.read_csv(UK_ACCIDENTS_DATA).head()
layer = pdk.Layer(
    'HexagonLayer',
    UK_ACCIDENTS_DATA,
    get_position='[lng,lat]',
    auto_highlight=True,
    elevation_scale=50,
    pickable=True,
    elevation_range=[0, 3000],
    extruded=True,                 
    coverage=1)

view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=6,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36)

r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.show()

view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=10,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36)
r.view_state = view_state
r.update()
```

**Comment by ajduberstein** [comment]
You're correct–deck.gl 8.1 broke support for setting the view state this way. You can update `initial_view_state` instead:

```python
view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=4,
    min_zoom=1,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36,
    transition_duration=4000)
r.initial_view_state = view_state
r.update()
```

**Comment by swha03** [comment]
I did as you told me, but I'm not responding at all this time.
my env is 
async-generator==1.10
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
click-plugins==1.1.1
cligj==0.5.0
colorama==0.4.3
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
Fiona==1.8.13
GDAL==3.0.3
geopandas==0.6.2
idna==2.8
importlib-metadata==1.4.0
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.2
Jinja2==2.10.3
json5==0.9.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyter-dashboards==0.7.0
jupyter-server==0.1.1
jupyterlab==1.2.6
jupyterlab-pygments==0.1.0
jupyterlab-server==1.0.6
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==3.1.2
memory-profiler==0.57.0
mistune==0.8.4
more-itertools==8.1.0
munch==2.5.0
nbconvert==5.6.1
nbformat==5.0.4
nodejs==0.1.1
notebook==6.0.3
numpy==1.18.1
optional-django==0.1.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.2
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.2
psutil==5.6.7
pydeck==0.2.0
Pygments==2.5.2
pyparsing==2.4.6
pyproj==2.4.2.post1
pyrsistent==0.15.7
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
pywinpty==0.5.7
pyzmq==18.1.1
qtconsole==4.6.0
requests==2.22.0
Send2Trash==1.5.0
Shapely==1.6.4.post2
six==1.14.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.7
voila==0.1.20
wcwidth==0.1.8
webencodings==0.5.1
widgetsnbextension==3.5.1
zipp==2.0.1

and i installed pydeck as pip but i could not confirm the version of deck.gl.

**Comment by swha03** [comment]
Sorry, i reinstall the pydeck, so it works normally. Thank you!
