### ISSUE TITLE
Straightforward way to prevent dragging/panning and zooming?

### ISSUE THREAD

**Issue by merges** [uber/deck.gl#4219]
I'm using Deck.gl in React. (It's amazing, thank you!) I'm using the `OrthographicView`. Is there a canonical and straightforward way to prevent dragging/panning and zooming?

**Comment by Pessimistress** [comment]
You can disable the `controller` prop:

```js
controller={false}
```

Or pass an object:

```js
controller={{dragPan: false, scrollZoom: false}}
```

See https://deck.gl/#/documentation/deckgl-api-reference/controllers/controller
