### ISSUE TITLE
PointCloudLayer: use of getPosition with the transitions prop leads to unexpected behavior

### ISSUE THREAD

**Issue by sfairgrieve** [uber/deck.gl#4223]
#### Description
In deck.gl 8, attempts to use `getPosition` within the `transitions` prop as part of `PointCloudLayer` initialization leads to points to being positioned incorrectly with incorrect picking info.  This worked fine in deck.gl 7.x.  Example below:

```
            new PointCloudLayer({
                id: 'elevation',
                data: this.state.spotElevations,
                pickable: true,
                autoHighlight: true,
                getPosition: f => [f.coordinates[0], f.coordinates[1], f.coordinates[2] * (viewState.zoom < 14 ? 14 - viewState.zoom : 0)],
                pointSize: 1,
                getColor: f => {
                    const colorVal = this.state.elevationColor(f.coordinates[2]);
                    const colorObj = color(colorVal);
                    return [colorObj.r, colorObj.g, colorObj.b, 255];
                },
                transitions: {
                   getPosition: {
                      duration: 300
                   }
                },
                updateTriggers: {
                    getPosition: [viewState.zoom]
                },
                onHover: ({object, x, y}) => {
                  this.setState({
                     hoveredObject: object,
                     pointerX: x,
                     pointerY: y
                  })
                }
            })
```

##### Correct/Expected Behavior (deck.gl 7.x with `getPosition` in the `transitions` prop or deck.gl 8.x without it)

![image](https://user-images.githubusercontent.com/3417702/73654291-4dd41600-4659-11ea-88bd-43ae99ec1023.png)

##### Issue (deck.gl 8.x with `getPosition` in the `transitions` prop)

![image](https://user-images.githubusercontent.com/3417702/73654194-0f3e5b80-4659-11ea-85c0-820d8271b501.png)

#### Repro Steps
Add `getPosition` to the `transitions` prop of a `PointCloudLayer`.  This appears to occur regardless of whether or not `updateTriggers` with `getPosition` are specified.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.12
 - Browser Version: Chrome 79.0.3945.130
 - OS: Mac OS X 10.14.6

#### Logs
N/A - no notable log entries

**Comment by Pessimistress** [comment]
Can you try 8.0.13?

**Comment by sfairgrieve** [comment]
Works great!  Thanks for the fix!
