### ISSUE TITLE
Deck not working with Mapbox maxBounds?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4234]
Deck appears to become disconnected from the mapbox events when the maxBounds property is set. In this [example](https://codesandbox.io/s/ecstatic-payne-s5cr5) in mounted.js I set the mapbox `maxBounds` property to `[[-180, -90], [180, 90]]`. If you zoom all the way out and then attempt to drag the map around you will see the deck and mapbox layer are no longer in sync...

Currently using the following:
 - deck.gl 8.0.13
 - Chrome 77
- OSX 10.14/Windows 10

**Comment by Pessimistress** [comment]
In your app deck.gl is handling the interaction, not the map. You update the map on deck's `onViewStateChange`. Nobody listens to any mapbox event.

If you want to limit the longitude and latitude of your view you need to do that inside `onViewStateChange`.

**Comment by jfuehner** [comment]
@Pessimistress sorry not sure I follow. Would you have an example you could share that keeps viewState within maxBounds?

**Comment by Pessimistress** [comment]
See [documentation](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=onviewstatechange-function-).

To restrict longitude range:

```js
onViewStateChange: ({viewState}) => {
  if (viewState.longitude > 90) {
    viewState.longitude = 90;
  }
  if (viewState.longitude < 0) {
    viewState.longitude = 0;
  }

  // update mapbox
  return viewState;
}
```

To prevent wrapping:

```js
onViewStateChange: ({viewState, oldViewState}) => {
  if (Math.abs(viewState.longitude - oldViewState.longitude) > 180) {
    viewState.longitude = Math.sign(oldViewState.longitude) * 180;
  }

  // update mapbox
  return viewState;
}
```

**Comment by Boimb** [comment]
@Pessimistress from what I see here, or what I could experiment on my side, those boundaries apply to the center of the view (longitude and latitude props of the viewState), not the map boundaries, meaning that depending on viewPort and zoom, you won't restrict view to the same visible area. 
Any idea on how "restrict view to a portion of the map" could be achieved ? Or maybe I'm missing sthg else :/

**Comment by abouroubi** [comment]
@Pessimistress @Boimb 
Looking for the exact same feature.
Mapbox SDK maxBounds was so handy 😕

**Comment by vsg24** [comment]
This is definitely a problem :(
