### ISSUE TITLE
Springiness/Resistance in Zoom/Pan

### ISSUE THREAD

**Issue by ilan-gold** [uber/deck.gl#4238]
I'm having trouble figuring out how to do this and haven't found anything in the docs.  It also might not exist yet, although I don't really believe that.  Does DeckGL support a spring/stiffness to zooming/panning in a viewport (like [OpenSeaDragon](https://openseadragon.github.io/examples/ui-zoom-and-pan/))?  I'd be happy to help clarify this however it can be, or implement something if you want it.

**Comment by Pessimistress** [comment]
You will have to implement your own [MapController](https://deck.gl/#/documentation/deckgl-api-reference/controllers/controller).

**Comment by ilan-gold** [comment]
Thank you.
