### ISSUE TITLE
Interleaved Buffer With IconLayer and TextLayer?

### ISSUE THREAD

**Issue by jfuehner** [uber/deck.gl#4244]
I was looking at the interleaved-buffer [example](https://github.com/uber/deck.gl/tree/master/examples/experimental/interleaved-buffer) as a way to increase rendering performance...

The example provides mockups of using the `PathLayer`, `SolidPolygonLayer` and `ScatterPlotLayer`. Was curious if perhaps you have a mockup of this approach using an IconLayer and TextLayer?

For the `IconLayer` specifically, I am trying to determine how I could best pass back the `getIcon` attributes _(i.e., width, height, url)_ as apart of the buffer.

For the `TextLayer` specifically, I am trying to determine how I could best pass back the `getText` _(i.e., string)_ as apart of the buffer.

Any help as always is really appreciated!

**Comment by Pessimistress** [comment]
IconLayer: You cannot use auto-packing with external buffers. You must provide a prepacked icon atlas where all icon ids are integers. Then `getIcon` can be an attribute array.

TextLayer will support binary data in 8.1. You can follow [this example](https://github.com/uber/deck.gl/blob/master/docs/layers/text-layer.md#use-binary-attributes) using 8.1.0-alpha.2.

**Comment by jfuehner** [comment]
@Pessimistress thank you! That’s super helpful! 

Any idea when 8.1 might be released?

**Comment by Pessimistress** [comment]
We are targeting end of February/beginning of March.

**Comment by jfuehner** [comment]
Got it, thanks! 

With the binary examples is it possible to pass an array of attributes (i.e., object id, etc) that could be accessed as apart of an event function (i.e., onClick, etc)? If so, how might you do that?

**Comment by Pessimistress** [comment]
The callback will receive the index of the object. You can look up the information with the index.

**Comment by jfuehner** [comment]
@Pessimistress I see... I’m not sure however the index would be unique enough for my use-cases.

In my app I could have multiple layers coming from multiple sources. So the index wouldn’t be unique enough to find the item across the different layers/data sources.

Any other alternative?

**Comment by Pessimistress** [comment]
I don't understand your question. The object index is for the layer that is picked. When you use a JavaScript array as `data` that index is what deck uses to retrieve the picked object.

**Comment by jfuehner** [comment]
@Pessimistress sorry, let me better explain what I believe my perceived problem is with only having access to the object index when using the binary layer configuration. 

In my app I receive an array of objects that loos similar to...

```
        const dataSources = [
            {
                index: 0,
                id: 1,
                layers: [
                    {
                        index: 0,
                        id: 11,
                        polygonLayer: true,
                        data: [
                            { index: 0, id: 111, position: [...] },
                            { index: 1, id: 112, position: [...] }
                        ]
                    },
                    {
                        index: 1,
                        id: 12,
                        polygonLayer: true,
                        data: [
                            { indes: 0, id: 121, position: [...] },
                            { index: 1, id: 122, position: [...] }
                        ]
                    },
                    {
                        index: 2,
                        id: 13,
                        textLayer: true,
                        data: [
                            { index: 0, id: 131, position: [...] },
                            { index: 1, id: 132, position: [...] }
                        ]
                    }
                ]
            },
            {
                index: 1,
                id: 2,
                layers: [
                    {
                        index: 0,
                        id: 21,
                        polygonLayer: true,
                        data: [
                            { index: 0, id: 211, position: [...] },
                            { index: 1, id: 212, position: [...] }
                        ]
                    }
                ]
            }
        ]
    }
```

The above structure is then translated into respective deck layers...

With the non-binary layer configuration when an object is picked I have fully access to the entire object. With the entire object I would have the object id which I could use to find within the array object structure above...

`    onClick: (info) => info.object.id;`

With the binary layer configuration it sounds as though I would have access only to the object index.

`onClick: (info) => info.index; `

With the object index I wouldn't have a way to locate within the array object structure above the corresponding object that was picked as the index would not be unique.

Hope that helps...

**Comment by jfuehner** [comment]
@Pessimistress I thought about my use-case a bit more. With the `layer` details being passed back  in the event handlers I can simply use the layer id and `object` index to locate the full object within my `dataSources` array...
