### ISSUE TITLE
Error initializing PolygonLayer using pre-bundled scripts

### ISSUE THREAD

**Issue by anthonynorth** [uber/deck.gl#4254]
#### Description
Error initializing `PolygonLayer` using pre-bundled scripts (`@deck.gl/core` & `@deck.gl/layers`). No issues using complete deck.gl bundle however.

#### Repro Steps
- [Codepen example](https://codepen.io/anthonynorth/pen/qBdEmzy)

#### Environment (please complete the following information):
 - deck.gl 8.0.13
 - Browser Version: Chrome 79.0
 - OS: Windows 10 1909

#### Logs
[console.log](https://github.com/uber/deck.gl/files/4173881/console.log)

**Comment by Pessimistress** [comment]
Thank you for reporting!

Fixed in 8.0.14.
