### ISSUE TITLE
Lat/long range visible in the viewport

### ISSUE THREAD

**Issue by ricardoekm** [uber/deck.gl#4263]
I'd like to load dynamic data in Deck.gl when the user pan and zoom. 

I've managed to get the zoom level, height/width of the viewport and the center point (in lat/long). However, how can I translate this into the lat/long range visible in the viewport so I can load the data that fits the screen?

Thanks.

**Comment by Pessimistress** [comment]
```js
import {WebMercatorViewport} from '@deck.gl/core';

const viewport = new WebMercatorViewport({width, height, longitude, latitude, zoom});
viewport.unproject([0, 0]); // top left corner
viewport.unproject([width, height]); // bottom right corner
```

See https://deck.gl/#/documentation/deckgl-api-reference/viewports/web-mercator-viewport

**Comment by ricardoekm** [comment]
Awesome! Thank you very much.
