### ISSUE TITLE
Pydeck Language

### ISSUE THREAD

**Issue by swha03** [uber/deck.gl#4264]
I want to change the language of mapbox in Pydeck.
Can I change it using setLayoutProperty on deck.gl, but can it be done with Pydeck?

**Comment by ajduberstein** [comment]
Hi @swha03 can you provide some example code of what you're trying to do?

**Comment by swha03** [comment]
You mean deck.gl example code?
map.setLayoutProperty('country-label-lg', 'text-field', '{name_fr}')

**Comment by Pessimistress** [comment]
@swha03 you can create a map style with the desired labels and pass it’s url to pydeck.

**Comment by ajduberstein** [comment]
@swha03 you can set the language on a tile set in Mapbox Studio:

![image](https://user-images.githubusercontent.com/2204757/74391984-8e026980-4dba-11ea-9efd-e33551c47612.png)

You can then use the URL published from Mapbox Studio in pydeck.

**Comment by swha03** [comment]
Thank you very much for your kind reply every time I ask!
