### ISSUE TITLE
Binary Data format on aggregation (grid) layers

### ISSUE THREAD

**Issue by dcooley** [uber/deck.gl#4265]
Is it possible to use Binary Data format on aggregation layers?

Example [jsfiddle here](https://jsfiddle.net/symbolixau/jgpe1wts/100/), using `https://unpkg.com/deck.gl@8.1.0-alpha.3/dist.min.js`

In this example I'm creating two `CPUGridLayer` objects (to make use of `onSetColorDomain`):
 
`gridLayer1` - uses [binary data format](https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md#supply-attributes-directly)
`gridLayer2` - uses a standard JSON object.

```js
  const binaryLocation = new Float32Array([-0.198456, 51.50554,-0.205590, 51.51491]);
  const binaryColourWeight = new Float32Array([1,1000]);
  const binaryElevationWeight = new Float32Array([1,100000]);

  const gridLayer1 = new deck.CPUGridLayer({
    map_id: 'map',
    id: 'grid',
    data: {
      length: 2,
      attributes: {
        getPosition: {value: binaryLocation, size: 2},
        getColorValue: {value: binaryColourWeight, size: 1},
        getElevationWeight: {value: binaryElevationWeight, size: 1}
      }
    },
    //colorAggregation: 'SUM',
    extruded: true,
    gpuAggregation: false,
    onSetColorDomain: d => alert( d )
   });

  const data = [
    {
      coordinates: [-0.198456, 51.50554],
      colour: 1,
      elevation: 1
    },
    {
      coordinates: [-0.205590, 51.51491],
      colour: 1000,
      elevation: 100000
    }
  ];
  
  const gridLayer2 = new deck.CPUGridLayer({
    map_id: 'map',
    id: 'grid',
    data: data,
    getPosition: d => d.coordinates,
    getColorWeight: d => d.colour,
    getElevationWeight: d => d.elevation,
    //colorAggregation: 'SUM',
    extruded: true,
    gpuAggregation: false,
    onSetColorDomain: d => alert( d )
   });
```

In the jsfiddle example you can see if you switch between 

```js
deckgl.setProps({layers: [gridLayer1] });
// and
deckgl.setProps({layers: [gridLayer2] });
```
Then the `gridLayer1` (binary data format) doesn't seem to use the `getColorValue: {value: binaryColourWeight, size: 1}` accessor.

Is it possible to use binary data on aggregation layers, and if so, what mistake have I made?

**Comment by 1chandu** [comment]
Binary data is not supported on CPU Aggregation, as actual attributes are set after aggregating them on CPU. Can you try using `GPUGridLayer`, but you have use `getColorWeight` and `getElevationWeight` accessors. You can either use `GridLayer` with above props and set `gpuAggregation=true` or directly use `GPUGridLayer` [doc](https://deck.gl/#/documentation/deckgl-api-reference/layers/grid-layer?section=gpu-aggregation)

**Comment by SymbolixAU** [comment]
I've tried using binary data on the `GPUGridLayer`, but only the first point is rendered. [updated fiddle](https://jsfiddle.net/symbolixau/jgpe1wts/121/)

**Comment by 1chandu** [comment]
For GPUGridLayer, I verified, the attributes are set properly, except there is an issue with bounding box calculation when position attribute size is 2, as workaround set `position` attribute size to 3 and provide `0` for z, it should work.

I made following changes to above fiddle:
```
const binaryLocation = new Float32Array([-0.198456, 51.50554, 0, -0.205590, 51.51491, 0]);
...
getPosition: {value: binaryLocation, size: 3},
```

<img width="1393" alt="Screen Shot 2020-02-25 at 3 04 40 PM" src="https://user-images.githubusercontent.com/9502731/75295715-2ef01c00-57e0-11ea-86b8-37b5a1611eca.png">

**Comment by 1chandu** [comment]
Please close if the above WA is working, remaining issues are tracked here  #4310

**Comment by dcooley** [comment]
Unfortunately I'm not seeing the same as you

![Screen Shot 2020-02-26 at 10 22 12 am](https://user-images.githubusercontent.com/8093396/75296659-eab55800-5881-11ea-9a84-589a16c19339.png)

[updated fiddle](https://jsfiddle.net/symbolixau/jgpe1wts/132/)

Tried on Firefox 73.0.1 and Chrome 79.0.3945.130

**Comment by 1chandu** [comment]
@dcooley , you need to either use `GPUGridLayer` or set prop `gpuAggregation: true` with `GridLayer`.

As described in #4310 , binary data support is not supported by generic 'GridLayer' (without setting gpuAggregation prop to true)  yet.

**Comment by SymbolixAU** [comment]
I have `gpuAggregation: true` set

(Now at work so I switched github accounts)

![Screen Shot 2020-02-26 at 10 32 09 am](https://user-images.githubusercontent.com/18344164/75297198-56e48b80-5883-11ea-866b-45efb6a5a02b.png)

**Comment by 1chandu** [comment]
[your fiddle ](https://jsfiddle.net/symbolixau/jgpe1wts/132/) works fine for me on Chrome (78.0.3904.108) and Firefox (73.0.1 )

<img width="1463" alt="Screen Shot 2020-02-26 at 11 34 35 AM" src="https://user-images.githubusercontent.com/9502731/75380564-1c332100-588c-11ea-95e1-c2901ee1807f.png">

**Comment by SymbolixAU** [comment]
Nothing that looks like it's related to Deck.gl

![Screen Shot 2020-02-27 at 8 00 04 am](https://user-images.githubusercontent.com/18344164/75387272-2fe79180-5937-11ea-800d-cde0343c554e.png)

**Comment by SymbolixAU** [comment]
Same with `v8.1.0-alpha.6`

I've also conducted a very quick, unscientific survey - https://twitter.com/_davecooley/status/1234192436806574082 - and it suggests only seeing 1 square is very much an outlier, as it's only me that has this issue.

**Comment by SymbolixAU** [comment]
Same with `v8.1.0-beta.1`. I still appear to be the only one with this issue...

**Comment by SymbolixAU** [comment]
Same with `v8.1.0`. Given you don't see an issue, and no-one else I've asked can replicate it, I'm going to assume the issue is with something in my setup. So happy for this to close, and let #4310  carry on
