### ISSUE TITLE
Pass encoded string to show as bitmap layer

### ISSUE THREAD

**Issue by Robert-OP** [uber/deck.gl#4268]
Hello, hope you are well. Thank you for this extraordinary library. 👍 

**Q1: Is it possible to pass a string directly in order to show as a bitmap layer?**

I am trying to use the Bitmap Layer by passing the bitmap directly as a string, but it complains (image below) that _No valid loader found for data starting with "" for 
"Qk02EAAAAAAAADYEAAAoAAAAQAAAADAAAAABAAgAAAAAAAAMAADEDgAAxA4AAAABA ..."_

**Q2: Should I do my own decoding and then pass the image?**

![image](https://user-images.githubusercontent.com/16807022/74452534-81951400-4e81-11ea-8475-74de5300d54f.png)

This is how I am using the bitmap layer, where `bitmap.image` is the encoded string above:

![image](https://user-images.githubusercontent.com/16807022/74453044-29124680-4e82-11ea-8afe-d63b1a6350d1.png)

**Comment by Pessimistress** [comment]
You need to pass a valid [data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), e.g. `data:image/jpeg,...`

**Comment by Robert-OP** [comment]
> You need to pass a valid [data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), e.g. `data:image/jpeg,...`

Hi @Pessimistress 10x 

I will try it tomorrow, but in my case it would be passing something like this to the `image` prop?

```
image: "data:image/png;base64,myEncodedString"
```

**Comment by Pessimistress** [comment]
Yes. To validate your data url, you can copy and paste it into your browser's location bar. It should display your image if it can be decoded.

**Comment by Robert-OP** [comment]
@Pessimistress thanks a lot, works well, I only need to set the right bounds :D

![image](https://user-images.githubusercontent.com/16807022/74515727-71c41100-4f0f-11ea-8801-393dbbf5e57b.png)
