### ISSUE TITLE
Can you confirm correct functioning of WebMercatorViewport unprojectFlat

### ISSUE THREAD

**Issue by mikeldn** [uber/deck.gl#4280]
Hi,

I've been trying to get the lat lng, of the bounds of the viewport using WebMercatorViewport **unprojectFlat** [As per docs](https://github.com/uber/deck.gl/blob/master/docs/api-reference/web-mercator-viewport.md)

unproject seems to work well, but I want the bounds as if bearing and pitch had not been applied, which is what unprojectFlat seems to do?!?

However, I only seem to get back coords like [-180,-85.05112877980659] rather than the expected (in London) approx [-0.11088879653871807, 51.51526849909505]. 

This seems to have been discussed before on [this request](https://github.com/uber/deck.gl/issues/4184), but the user seemed happy with unproject(). 
They have setup a demo [here](http://jsfiddle.net/symbolixau/fon8yzL5/38/).

Would be great to see a working example of unProjectFlat, with the syntax for the zoom?scale? parameter, and a conformation of the version of DeckGL this works on.

Thanks!

**Comment by mikeldn** [comment]
Update: I still can't seem to get unprojectFlat to work for me (maybe I'm doing something wrong), however I did find a work around.

Whatever the actual current viewport of the deckgl, you can always create a fake "flat" viewport, by setting **pitch & bearing to 0,** and use regular unproject() from that viewport.

FYI: I'm using Vue.js, and storing the current viewState in "this.deckViewState": 

var flatViewport = new deck.WebMercatorViewport({
width: this.deckViewState.width,
height: this.deckViewState.height,
longitude: this.deckViewState.longitude,
latitude: this.deckViewState.latitude,
zoom: this.deckViewState.zoom,
**pitch: 0,
bearing: 0**
});
var nw = flatViewport.**unproject**([0, 0]);
var se = flatViewport.**unproject**([flatViewport.width, flatViewport.height]);

Anyway, maybe it'll help someone...

**Comment by Pessimistress** [comment]
The documentation is outdated. `unprojectFlat` doesn't do what you need at all. The solution in your second comment is the way to go.

**Comment by mikeldn** [comment]
Thank you! Understood!
