### ISSUE TITLE
deck and mapbox layer order

### ISSUE THREAD

**Issue by chenkai0520** [uber/deck.gl#4286]
I wang to change the basemap layer in mapbox，but the deck layer is covered。

Is there a way to control the deck layer index in mapbox？

thank you

**Comment by wlfei0502** [comment]
`MapboxLayer` can do it. [https://github.com/uber/deck.gl/tree/master/docs/api-reference/mapbox](url)

**Comment by chenkai0520** [comment]
> `MapboxLayer` can do it. [https://github.com/uber/deck.gl/tree/master/docs/api-reference/mapbox](url)

谢谢
