### ISSUE TITLE
LayerExtension: VS injection and geometry interaction

### ISSUE THREAD

**Issue by Bowlx** [uber/deck.gl#4289]
#### Description
I'm trying to make layer extension, which allows to color polygon layers related on their position at screen, I'm using injection hook  "vs:DECKGL_FILTER_COLOR" to get accsess to vertex color and change it depend on geometry.position.x and geometry.position.y, it works untill I zoom out to ~12, with zoom >=12 it stops working.

#### Repro Steps

- inject into vertex shader via vs:DECKGL_FILTER_COLOR
- change vertex color depend on geometry position
- zoom out to >=12

codepen example: https://codepen.io/bowlx/pen/RwPGaGb 

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.14
 - Browser Version: Chrome 79 
 - OS: Windows 10

**Comment by Pessimistress** [comment]
This is expected. deck.gl switches to an "offset" mode in z >= 12 to compensate for the precision loss in GLSL and float32 attributes. `geometry.position` is a relative coordinate whose origin moves around with the camera. `geometry.worldPosition` is much more reliable for your use case.

**Comment by Bowlx** [comment]
Thank you for the answer, i made calculation based on worldPosition and now it works properly.
Here is code if someone looking for extension which makes polygon's color gradient'ish and camera related:
   
    class ColorFilter extends LayerExtension {
    getShaders() {
    return {
      inject: {
      "vs:#decl":
     "uniform float latMin; uniform float latMax; uniform float lonMin; uniform float lonMax;",
    "vs:DECKGL_FILTER_COLOR":  `
    float x = (geometry.worldPosition.x - lonMin)/(lonMax-lonMin);
    float y = (geometry.worldPosition.y - latMin)/(latMax-latMin);
    color = vec4(1.0-y,x,1.0-x,0.65);
    `,
      },
    };
    }
    updateState(params) {
    const { bbox } = params.props; //bbox - array of map bounds [latMin,lonMin,latMax,lonMax]
    for (const model of this.getModels()) {
      model.setUniforms({
        latMin: bbox[0],
        lonMin: bbox[1],
        latMax: bbox[2],
        lonMax: bbox[3],
      });
    }
    }
    }
