### ISSUE TITLE
Promise data refetch when layer props updated

### ISSUE THREAD

**Issue by mozartilize** [uber/deck.gl#4304]
#### Description
Hi, I have layers which data prop return to promise fetching data from a worker. When I update layer props by create new instance, for example I update layer visible prop and I notice that the data got refetched. I tried to reuse the data from layers filtered in layerManager but its life cycle is discarded and waiting for gabage collection and some not available anymore.

So are data got refetched normal behavior?

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.0.12
 - Browser Version: latest chrome, firefox...
 - OS: manjaro

**Comment by Pessimistress** [comment]
If your old layer instance’s lifecycle is “finalized”, it means that your new layer does not have the same id. Fetched data etc. can only be transferred to the new instance if they are considered the same layer, i.e. have the same id.

**Comment by mozartilize** [comment]
Of course it has the same id!

**Comment by mozartilize** [comment]
I've just double check, reuse downloaded data from layerManager works but not with promise data prop.

**Comment by Pessimistress** [comment]
Please share your layer code if you need help troubleshoot. I can only speculate based on the information you provided.

**Comment by mozartilize** [comment]
sorry for the delay, here's my example code:

```javascript
  const layerVisibility = {circles: true, labels: true}

  function toggleLayer(key) {
    layerVisibility[key] = !layerVisibility[key];
    render();
  }

  function fetchData(url) {
    // return a Promise
  }

  function render() {
    const layers = [
      // when visibility is off, this layer's internal states will be retained in memory,
      // making turning it back on instant
      new ScatterplotLayer({
        data: fetchData(url1),
        visible: layerVisibility.circles,
        ...
      }),
      new TextLayer({
        data: fetchData(url2),
        visible: layerVisibility.labels,
        ...
      })
    ];

    deck.setProps({layers});
  }
```
and when `render` called, data get refetched...

**Comment by ibgreen** [comment]
This is expected because you are calling fetch on each render.

Either leave the fetching to deck.gl, by just passing the url
```
new ScatterplotLayer({
        data: url1,
        visible: layerVisibility.circles,

        ...
      }),
```

Or if you need to use a custom fetch, fetch in advance and keep passing the same promise, deck will understand and do the right thing.

```
const dataPromise = fetchData;

render() { 
  new ScatterplotLayer({
        data: fetchPromise,
        visible: layerVisibility.circles,

        ...
      }),
```
