### ISSUE TITLE
Mouse position via mapbox.gl

### ISSUE THREAD

**Issue by stevesoaeris** [uber/deck.gl#4315]
Is there a way to get the mouse position (lng, lat) easily from deck similar to how mapbox.gl does it?
I tried using mapbox's 
`map.on('mousemove', ... ` as in
https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/
but it doesn't work when deck is there.

**Comment by jfuehner** [comment]
@stevesoaeris tap into the various [deck events](https://deck.gl/#/documentation/deckgl-api-reference/deck). Specifically, the `onHover` and `onDrag` functions both of which provide an `info` object which contains a `coordinate` property.

**Comment by stevesoaeris** [comment]
ok, that helps a lot.  I was on the wrong track and implementing custom `controller`s.
