### ISSUE TITLE
can anyone tell me what's the format of trips-data.txt

### ISSUE THREAD

**Issue by zohaib055** [uber/deck.gl#434]
I want to use custom trips-data.txt file with my own lat and long . but the current file is encoded can you guys tell  how can i encode and decode that file .

**Comment by zohaib055** [comment]
I will appreciate your help

**Comment by shaojingli** [comment]
@gnavvy @Pessimistress any ideas?

**Comment by Pessimistress** [comment]
@zohaib055 the file is compressed for faster loading. If you want to use the trips layer with your own data, checkout the readme file: https://github.com/uber/deck.gl/blob/master/examples/sample-layers/trips-layer/README.md

**Comment by zohaib055** [comment]
@Pessimistress  i have been using this example https://uber.github.io/deck.gl/#/examples/trip-routes .. want to put own lat long and timestamp  . can you give on short example showing one line on the map with custom lat long and timestamp

**Comment by zohaib055** [comment]
@Pessimistress  Looks like d.path  is path to the data object that provides lat long and timestamp but but how would i give path to the custom file or object

**Comment by zohaib055** [comment]
@Pessimistress  i can see the lat long segments in side the object this.props in trips-layer.js file

my questions how i pass my custom object having the same this or should i overide these segments ?

**Comment by zohaib055** [comment]
@Pessimistress  ^^

**Comment by ibgreen** [comment]
> my questions how i pass my custom object having the same this or should i overide these segments ?

@zohaib055 
* All layers take a `data` prop. It should be an array of objects. The layer will query each object for some data and build a WebGL geometry to render it. 
* You may also need to provide accessors. In the case of trips-layer you need to define `getPath` and `getColor`. These should be functions that return the path and the color. Each path is an array of coordinates.  The defaults return `object.path` and `object.color`, so if you structure your objects that way you don't need to specify accessors..
```
<DeckGL ... layers={[
  new TripsLayer({
     data: [
        {path: [[lng, lat, z], [lng, lat, z], ...], color: [255, 0, 0, 255]},
        {path: [[lng, lat, z], [lng, lat, z], ...], color: [255, 0, 0, 255]},
        ...
     ]
  })
]}/>
```

**Comment by ibgreen** [comment]
@zohaib055  Correction. As specified in the README, it should be `timestamp` instead of `z` as third coordinate above.

**Comment by zohaib055** [comment]
Thanks @ibgreen
