### ISSUE TITLE
How to deck.gl tileLayer changed URL updateTriggers function setting?

### ISSUE THREAD

**Issue by bbbbbra** [uber/deck.gl#4341]
Using deck.gl version 7.3.12

I want to reload after changing the URL of the tile layer. How can I make a tile image change smoothly?

I want to get the getTileData () function called again just by changing the URL.

Currently on the same screen,

I want to recall different tile data according to the URL change.

- The conclusion is how to TileLayer reload(different URL request)

**Comment by bbbbbra** [comment]
how to TileLayer reload(different URL request)

**Comment by Pessimistress** [comment]
All cached tiles will be invalidated if the `getTileData` updateTrigger is changed.

```js
updateTriggers: {
  getTileData: {url}
}
```

**Comment by bbbbbra** [comment]
thank you so much

**Comment by yangup** [comment]
Can you tell me more in detail, I don’t quite understand

**Comment by padawannn** [comment]
https://deck.gl/docs/developer-guide/performance#use-updatetriggers

**Comment by sheeceg** [comment]
updateTriggers dose not work! even when I change the url property. Can you please give some hints what might be the issue?
```
 var url=".../{x}/{y}/{z}"
 deckgl = new Deck({
    controller: true,
    canvas: "deckmap",
    initialViewState: INITIAL_VIEW_STATE,
    maxCacheSize:100,
    layers: [
      new TileLayer({
        id: "decklayer",
        data: [
          url
        ],
        updateTriggers: {
          getTileData: {url}
        },
        maxRequests: 100,
        pickable: true,
        highlightColor: [60, 60, 60, 40],
        minZoom: 0,
        maxZoom: 30,
        tileSize: 512 / devicePixelRatio,

        renderSubLayers: (props) => {
          const {
            bbox: { west, south, east, north },
          } = props.tile;

          return [
            new BitmapLayer(props, {
              data: null,
              image: props.data,
              bounds: [west, south, east, north],
            }),
          ];
        },
      }),
    ],
  });
```
