### ISSUE TITLE
BitmapLayer: Props documentation

### ISSUE THREAD

**Issue by anthonynorth** [uber/deck.gl#4346]
#### Description
Prop `bitmap` should be `image`
<https://github.com/uber/deck.gl/blob/master/docs/layers/bitmap-layer.md#data>

#### Repro Steps
NA

#### Environment (please complete the following information):
NA

#### Logs
NA

**Comment by ibgreen** [comment]
We should add `ImageBitmap` to the list of supported inputs.

**Comment by anthonynorth** [comment]
Thanks @Pessimistress
