### ISSUE TITLE
Complex polygon with holes doesn't render correctly

### ISSUE THREAD

**Issue by marioaks** [uber/deck.gl#4349]
#### Description
Using the PolygonLayer or the GeoJsonLayer, polygons with holes in them do not render correctly. Even the example in the docs for the PolygonLayer doesn't work. 

#### Repro Steps
This polygon (the example used in https://deck.gl/#/documentation/deckgl-api-reference/layers/polygon-layer)

```
// Complex polygon with holes (array of rings)
[
   [[-122.4, 37.7], [-122.4, 37.8], [-122.5, 37.8], [-122.5, 37.7], [-122.4, 37.7]],
   [[-122.45, 37.73], [-122.47, 37.76], [-122.47, 37.71], [-122.45, 37.73]]
]
```
Renders like this: 
![Screen Shot 2020-03-04 at 2 42 26 PM](https://user-images.githubusercontent.com/13203039/75916841-0b078880-5e27-11ea-9273-31a3cb3ddab6.png)

#### Environment (please complete the following information):
- Framework Version: [e.g. deck.gl 8.1.0-alpha.6]
- Browser Version: [e.g. Chrome 80.0]
- OS: [e.g. Mac OS X 10.14]

**Comment by Darune** [comment]
Not sure what went wrong but it looks fine to me : 
https://codesandbox.io/s/brave-darwin-n0ue9

**Comment by marioaks** [comment]
Well, I think the main difference is that your sandbox is using version 8.0.17 and I’m trying to use version 8.1.0-alpha.6

**Comment by Pessimistress** [comment]
It works fine with 8.1.0-alpha. Remember you can't pass the above data sample directly to `data`. `data` prop needs to be an array of polygons.

**Comment by marioaks** [comment]
Ohh haha I I feel dumb now! Forgot that a multipolygon with holes can also be read as two distinct polygons. Thanks for the help!
