### ISSUE TITLE
regression after removing brfs

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#435]
In the current master, npm run build fails for: ERROR in bundle.js from UglifyJs.
This may due to https://github.com/mapbox/mapbox-gl-js/issues/4359 but the suggested workaround does not help.

Another possible reason is we are using some internal APIs from mapbox-gl in react-map-gl, which the prebuilt mapbox-gl.js we specified as webpack alias does not include.

Will give it another try, if it does not work, we might have to resume the brfs for the demos at least.

**Comment by ibgreen** [comment]
@Pessimistress @gnavvy 

I have only seen this occasionally, not consistently. Ideas:
* Can we check the exact versions of react-map-gl when this fails. I've noticed that yarn does not always install the latest version if there is an older version that is compatible with the package.json wildcard for that module.
* Can we check that clearing out node_modules and reinstalling does not fix this (the clean install needs to be done both in root and examples for most of our webpack configs).

**Comment by ibgreen** [comment]
I believe @Pessimistress fixed this before the release.
