### ISSUE TITLE
FontAtlasManager not available via unpkg

### ISSUE THREAD

**Issue by shabbyrobe** [uber/deck.gl#4355]
#### Description

The FontAtlasManager type is not available when using the unpkg-hosted version of deck.gl, even though it is exported in the code.

#### Repro Steps
```
<html>
  <head>
    <script src="https://unpkg.com/deck.gl@^8.0.0/dist.min.js"></script>
  </head>
  <body>
    <script>
      document.write(!!deck.TextLayer); // 🚿
      document.write(!!deck.FontAtlasManager);
    </script>
  </body>
</html>
```
The nasty little snippet above prints `truefalse`, when I would expect it to print `truetrue`.

#### Environment (please complete the following information):
 - Framework Version: 8.0.17
 - Browser Version: FF 73.0.1
 - OS: Windows 10

**Comment by Pessimistress** [comment]
`FontAtlasManager` is not public API. Everything exported by the layers module can be found here:

https://github.com/uber/deck.gl/blob/master/modules/layers/src/index.js

**Comment by shabbyrobe** [comment]
Hm, ok, I missed that detail. Apologies for the distraction.
