### ISSUE TITLE
Docs: Getting Started should mention the examples in pure-js/scripting

### ISSUE THREAD

**Issue by andybak** [uber/deck.gl#4356]
Call me old school but surely a .js src tag and a light sprinking of json is simpler than npm/webpack etc?

Seeing a "Get started" like that would have been very encouraging initially.

**Comment by Pessimistress** [comment]
Are you  referring to [this page](https://deck.gl/#/documentation/getting-started/using-standalone)?

**Comment by andybak** [comment]
No. I meant "Getting Started" in the main menu: https://deck.gl/#/documentation/getting-started/installation

It seems strange to not mention the absolute most simple way to get started on the page called "Getting Started". A CDN simple file install also makes life a lot easier when using non-js frameworks (Django in my case)

**Comment by andybak** [comment]
Ah. I see what's going on. That page isn't actually "Getting Started" - that's the section title.

However - it *is* the page that's displayed when you click on "Getting Started". I'm not sure why I didn't think to look at the page called "Using Without React". I was focusing on "start at the beginning of the docs and work your way through". I still stand by my point that it would be good to mention the simpler option earlier on.

**Comment by Pessimistress** [comment]
This is addressed in #4395
