### ISSUE TITLE
Possible to change order of TileLayer's sublayers?

### ISSUE THREAD

**Issue by kylebarron** [uber/deck.gl#4369]
I'm trying to build a "hybrid" extruded terrain layer, where vector features are rendered on the terrain's surface. I have a working prototype, where the terrain is a `SimpleMeshLayer` and 2D 
point and line vector tile features are snapped to the terrain mesh on the fly and rendered with a `GeoJsonLayer`.

An issue I'm facing is that some vector features are visible _through_ the terrain, for example, features through Mt. St. Helens:
![image](https://user-images.githubusercontent.com/15164633/76285018-5de8a200-6264-11ea-8bf7-cdc91818d036.png)
![image](https://user-images.githubusercontent.com/15164633/76285831-4b6f6800-6266-11ea-9e1d-6f5912d759ac.png)

I believe the core of this issue is that, since the `SimpleMeshLayer` and `GeoJsonLayer` are sublayers of a `TileLayer`, the order of the layers is:
```
vector1
terrain1
vector2
terrain2
...
```

So even if vector and terrain features are rendered in the correct order _within_ a tile, they might be in the wrong order _across_ tiles.

What I'm looking for is some way to sort all the vector layers before all the mesh layers.

One theoretical alternative is to have two separate `TileLayers`. One for the vector data; another for the terrain. This is problematic, however, because then you're creating the mesh twice for each tile.

Here's the gist of my `TileLayer`:

```js
function getTileData({x, y, z, bbox}) {
  const terrainUrl = getTerrainUrl({x, y, z});
  const textureUrl = getTextureUrl({x, y, z});
  const mvtUrl = getOpenMapTilesUrl({x, y, z});

  // minx, miny, maxx, maxy
  // This is used to flip the image so that the origin is at the top left
  const bounds = [0, 1, 1, 0];

  // Load vector tile
  const mvttile = load(mvtUrl, MVTLoader);
  // Load terrain tile
  const terrain = loadTerrain({
    terrainImage: terrainUrl,
    bounds,
    elevationDecoder: ELEVATION_DECODER,
    meshMaxError: MESH_MAX_ERROR
  });
  // Load satellite image
  const texture = textureUrl
    ? // If surface image fails to load, the tile should still be displayed
      load(textureUrl).catch(_ => null)
    : Promise.resolve(null);

  return Promise.all([terrain, texture, mvttile]);
}

function renderSubLayers(props) {
  const {data, tile} = props;

  return [
    new GeoJsonLayer(props, {
      // NOTE: currently you need to set each sublayer id so they don't conflict
      id: `geojson-layer-${tile.x}-${tile.y}-${tile.z}`,
      data: data.then(result => {
        const mesh = result[0];
        const features = result[2];
        return snapFeatures({terrain: mesh, features});
      }),
      lineWidthMinPixels: 5,
      coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
      modelMatrix: getModelMatrix(tile)
    }),
    new SimpleMeshLayer(props, {
      id: `terrain-simple-mesh-layer-${tile.x}-${tile.y}-${tile.z}`,
      data: DUMMY_DATA,
      mesh,
      texture,
      getPolygonOffset: null,
      coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
      modelMatrix: getModelMatrix(tile),
      getPosition: d => [0, 0, 0],
      // Color to use if surfaceImage is unavailable
      getColor: [255, 255, 255]
    }),
  ];
}
```

Any ideas?

**Comment by Pessimistress** [comment]
Can you try setting `getPolygonOffset: null` on the TileLayer?

**Comment by kylebarron** [comment]
Huh, that does appear to work!

I'll have to experiment with `getPolygonOffset` more in the future to reduce z-fighting, but raising the vector layers a little, like `getPolygonOffset: () => [0, -50],` is helpful.

**Comment by Pessimistress** [comment]
The default `getPolygonOffset` increments the offset based on the layer index. In the tiled case, the layer index is currently calculated as such:

| tile | layer | layerIndex |
| --- | --- | --- |
| tile0 | subLayer0 | 0 |
| | subLayer1 | 1 |
| | subLayer2 | 2 |
| tile1 | subLayer0 | 3 |
| | subLayer1 | 4 |
| | subLayer2 | 5 |
| tile2 | subLayer0 | 6 |
| | subLayer1 | 7 |
| | subLayer2 | 8 |

In reality, we should probably use

| tile | layer | layerIndex |
| --- | --- | --- |
| tile0 | subLayer0 | 0 |
| | subLayer1 | 1 |
| | subLayer2 | 2 |
| tile1 | subLayer0 | 0 |
| | subLayer1 | 1 |
| | subLayer2 | 2 |
| tile2 | subLayer0 | 0 |
| | subLayer1 | 1 |
| | subLayer2 | 2 |
