### ISSUE TITLE
Albers equal area projection

### ISSUE THREAD

**Issue by kbatchu** [uber/deck.gl#4370]
Hello,
I understand that the default projection used in deck.gl is 'Web mercator'. However, is it possible to load a geojson that is in Albers Equal Area projection (or any other projection other than Web Mercator)  into deck.gl ? If yes, how ?

Thanks
Kiran

**Comment by Pessimistress** [comment]
You can project them on the CPU and render using `OrthographicView` and `COORDINATE_SYSTEM.CARTESIAN`. See [example](https://codepen.io/vis-gl/pen/xMGzxB).

**Comment by kbatchu** [comment]
Thanks for your help. I got a little bit further along...and I ran into this issue. So I am loading the US States geojson and projecting it to 'geoAlbers' using D3 and then loading into deck.gl using the 'PolygonLayer'. It seems to be projecting it correctly, however, it does not render the states that are on the 'border' of the United States. The states that are surrounded by other states are rendered properly. I am attaching the snapshot of what I see and the US states geojson. The geojson file is fine since I can view it on mapshaper.org. Here is my code: 

`import $ from "jquery";
import * as d3 from "d3";
import * as d3topo from "d3topo";
import { Deck, COORDINATE_SYSTEM, OrthographicView } from "@deck.gl/core";
import {
  ScatterplotLayer,
  GeoJsonLayer,
  ColumnLayer,
  PolygonLayer,
  SolidPolygonLayer
} from "@deck.gl/layers";

function AlbersProj() {
  
  var deckgl;
  var usStatesLayer;
  var wWidth;
  var wHeight;
  var proj;

  wWidth = $(window).width();
  wHeight = $(window).height();

  const INITIAL_VIEW_STATE = {
    latitude: 39.82,
    longitude: -98.58,
    zoom: 4
  };

  function initDeckGLPureJS() {
    var currentViewState;

    deckgl = new Deck({
      initialViewState: INITIAL_VIEW_STATE,
      controller: true,
      views: new OrthographicView({ controller: true }),
      onViewStateChange: ({ viewState }) => {        
        currentViewState = viewState;
        deckgl.setProps({ viewState: currentViewState });
      }
    });
  }

  function setTooltip(object, x, y) {
    const el = document.getElementById("tooltip");
    if (object) {
      el.innerHTML = object.message;
      el.style.display = "block";
      el.style.left = x + "px";
      el.style.top = y + "px";
    } else {
      el.style.display = "none";
    }
  }

  function loadUSGeom() {
    d3.json("usStatesGeoJSON_20m.json", function(error, data) {     

      proj = d3.geoAlbers().fitExtent(
        [
          [0, 0],
          [wWidth, wHeight]
        ],
        data
      );

      usStatesLayer = new PolygonLayer({
        id: "USStates",        
        data: data.features,
        coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
        stroked: true,
        filled: true,
        pickable: false,
        opacity: 1,
        lineWidthMinPixels: 1,
        lineWidthMaxPixels: 2,
        getPolygon: function(d) {
          var projCoordArr = [];
          var projCoord;
          var coordArr = d.geometry.coordinates[0];
          coordArr.forEach(elem => {
            projCoord = proj(elem);
            projCoordArr.push(projCoord);
          });
          return projCoordArr;
        },
        getLineWidth: 1,
        getLineColor: [193, 193, 193, 130],
        getFillColor: [173, 173, 173],        
      });

      deckgl.setProps({
        layers: [usStatesLayer]
      });
    });
  }
 
    initDeckGLPureJS();
    loadUSGeom(); 
}
export default AlbersProj;
![deck_albers](https://user-images.githubusercontent.com/34347771/76451265-9217ac00-63a5-11ea-83ed-8d272755be56.PNG)
[usStatesGeoJSON_20m.zip](https://github.com/uber/deck.gl/files/4320105/usStatesGeoJSON_20m.zip)



`

**Comment by kbatchu** [comment]
I think I know what the problem is....the above code processes only 'Polygon' type features in the geojson and does not process 'MultiPolygon' type features. The states that are not being displayed are 'MultiPolygon' types. Anyone know how to modify the above code to process 'MultiPolygon' features as well ?
Thanks

**Comment by kbatchu** [comment]
It is working now. I just had to loop through the nested arrays of the 'MultiPolygon'.
thanks
