### ISSUE TITLE
Pan/zoom not working

### ISSUE THREAD

**Issue by ricardoekm** [uber/deck.gl#4392]
Sorry, I should be clearly doing something wrong but I'm can't figure what it's.

I'm building a simple map with a line layer from the [getting started docs](https://deck.gl/#/documentation/getting-started/using-with-react), however different from the online examples pan and zoom are not working.

I've added controller={true} to DeckGL component and also tried to customize the controller params:
```javascript
<DeckGL viewState={initialViewState}
        controller={{type: MapController, scrollZoom: true, doubleClickZoom: true}}
        layers={layers}>
        <StaticMap mapboxApiAccessToken="token"/>
</DeckGL>
```

I thought it could something related to [StaticMap](https://uber.github.io/react-map-gl/docs/api-reference/static-map) vs [InteractiveMap](https://uber.github.io/react-map-gl/docs/api-reference/interactive-map) from react-map-gl. However all examples use StaticMap.

I also tried to add maxZoom and minZoom props. No error or warning shows up in the console.

Any help would be appreciated. Thanks!

Code available here: https://gist.github.com/ricardoekm/bfe098f3b94951b20c828bfbb8120f93

**Comment by kylebarron** [comment]
I think [you want](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=initialviewstate-object-) `initialViewState={initialViewState}`.

**Comment by ricardoekm** [comment]
Exactly! Thank you very much!!
