### ISSUE TITLE
Terrain Layer picking

### ISSUE THREAD

**Issue by kylebarron** [uber/deck.gl#4398]
#### Target Use case

1. Simple point elevation retrieval by picking mesh `position`.
2. Use picked point with `controller` to rotate around picked point instead of `z=0`.

#### Proposed feature

I was looking through `simple-mesh-layer.js` and noticed that it supports returning `position` through picking:
https://github.com/uber/deck.gl/blob/4e1c12cfd1e0b6f9bb8e2091dddd95e2313d05aa/modules/mesh-layers/src/simple-mesh-layer/simple-mesh-layer.js#L130-L147

I experimented setting `pickable: true` on the [mesh website example](https://github.com/uber/deck.gl/blob/master/examples/website/mesh/app.js), and it appears to expose an `object` like:
```
{
    "object": {
        "position": [60, 180],
        "color": [141.66666666666669, 128, 170],
        "orientation": [3.3333333333333357, 0, -90]
    }
}
```

Here, `position` is returned as a 2D coordinate. Is that specific to that mesh example? I.e. if `position` could be returned as a 3D coordinate corresponding to a point on the face of the terrain mesh, that would be a simple way to get point elevation data.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
You'll need to call `deck.pickObject` yourself with `unproject3D: true`.

**Comment by kylebarron** [comment]
Works well, thanks!
