### ISSUE TITLE
DeckGL & React-Map-GL

### ISSUE THREAD

**Issue by seeyijie** [uber/deck.gl#4399]
Hello, I have read the documentation for using MapboxLayer with deck.gl, however, I keep getting a blank map. I have referenced the following documentation below.
https://deck.gl/#/documentation/submodule-api-reference/deckgl-mapbox/overview?section=using-with-react

I noticed that:
1) If I removed gl from gl && StaticMap, I will be able to see the mapstyles light-v9. However, I suspect gl is not initialised to the latest value. 

> Cannot read property 'addLayer' of null

2) Is there a way to initialised gl without using this keyword? Am I not supposed to use hooks when implementing this?

Thank you so much.

``` 
  const [mapInstance, setMapInstance] = useState(null);
  const [gl, setGl] = useState(null);
  const [deckInstance, setDeckInstance] = useState(null);
  function _onMapLoad(mapInstance, deckInstance) {
    mapInstance.addLayer(new MapboxLayer({
      id: 'id123',
      source: {
        type: 'vector',
        url: 'mapbox://styles/xxxx/yyyy'
      },
      deckInstance
    }));
  }
...
...
  return (
    <div>
...
      <DeckGL
        ref={ref => setDeckInstance(ref && ref.deck)}
        initialViewState={viewState}
        layers={renderLayers({
          data: disasterData(),
          onHover: hoverHandler,
          settings,
        })}
        controller
        onWebGLInitialized={() => setGl(gl)}
      >
        {gl && (
          <StaticMap
            gl={gl}
            ref={ref => setMapInstance(ref && ref.getMap())}
            mapStyle="mapbox://styles/mapbox/light-v9"
            mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_KEY}
            onLoad={() => _onMapLoad()}
          />
        )}
      </DeckGL>

```

**Comment by Pessimistress** [comment]
`onWebGLInitialized={(gl) => setGl(gl)}`

**Comment by seeyijie** [comment]
I can't believe I miss that! Thank you @Pessimistress ! 
This time, I encountered this. It seems like it did not write the value to its state before it crashes.

> TypeError: Cannot read property 'addLayer' of null

**Comment by Pessimistress** [comment]
You're calling `_onMapLoad` without any parameters.

You should also be using [useRef](https://reactjs.org/docs/hooks-reference.html#useref) instead of ref callbacks if you are using hooks.

**Comment by seeyijie** [comment]
Thanks! Resolved :)
