### ISSUE TITLE
Tile3DLayer no longer working with data served from Cesium

### ISSUE THREAD

**Issue by mkasznia** [uber/deck.gl#4411]
Hi,
I'm trying to update to new version of Tile3DLayer however I cannot get it working.
```
export const createPointCloudLayer = (id) => {
    return new Tile3DLayer({
        id: 'tile-3d-layer'+id,
        data: `https://assets.cesium.com/${id}/tileset.json`,
        loader: CesiumIonLoader,
        loadOptions: {
            'cesium-ion': {accessToken: 'mytoken'}
        },
        _subLayerProps: {
            scenegraph: {_lighting: 'flat'}
        }
    });
}
```
Is giving me 401 from Cesium due to invalid token. What am I doing wrong?
Previous version of Tile3DLayer worked like a charm.

Versions:
```
"deck.gl": "latest",
"loaders.gl": "^0.3.5",
"@loaders.gl/draco": "^2.1.1",
"@loaders.gl/3d-tiles": "^2.1.1",
```

**Comment by xintongxia** [comment]
@ mkasznia

Could you try removing `loaders.gl` from the dependency?

We use lerna to manage our loader sub modules, however it stopped bump version at some point, I'll work on a fix soon.

At the mean time, you can use your ion assetId and  accessToken with the [sandbox](https://codesandbox.io/s/loadersgldeckgl3d-tiles-qdkgd), which is the same as our [website example](https://deck.gl/#/examples/core-layers/tile-3d-layer).

**Comment by mkasznia** [comment]
Thank you for reply,
I've tried to remove ```loaders.gl``` however still got 401 from Cesium side.
I also tried sandbox you provided and everything works fine there. I'm a little bit confused.
Now my code looks like this:
```
import {CesiumIonLoader} from '@loaders.gl/3d-tiles';
import {Tile3DLayer} from '@deck.gl/geo-layers';
import { DracoWorkerLoader } from "@loaders.gl/draco";
import { registerLoaders } from "@loaders.gl/core";

registerLoaders([DracoWorkerLoader]);

export const createPointCloudLayer = (id) => {
    return new Tile3DLayer({
        id: 'tile-3d-layer'+id,
        data: `https://assets.cesium.com/${id}/tileset.json`,
        loader: CesiumIonLoader,
        loadOptions: { "cesium-ion": { accessToken: 'mytoken' } },
    });
}
```

I noticed one important thing - in the sandbox, before sending request for tiles, deckgl sends auth req to `https://api.cesium.com/v1/assets/<assetid>/endpoint.` endpoint. However it does not happen within my own project. Do you have any clues?

**Comment by xintongxia** [comment]
@mkasznia 

Could you make sure the dependencies version (deck.gl, loaders.gl) matched [sanbox example](https://codesandbox.io/s/loadersgldeckgl3d-tiles-qdkgd)

**Comment by mkasznia** [comment]
@xintongxia thank you so much for help. The problem was usage of newest deck.gl, after changing to `"deck.gl": "8.1.0",` everything works again. You'r awesome!

**Comment by Danchev1** [comment]
You need to specify the token, which is in your cesium account.
