### ISSUE TITLE
Flipped order of parameters of `_dataDiff` in documentation

### ISSUE THREAD

**Issue by MehdiSaffar** [uber/deck.gl#4414]
The [documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/layer) for `_dataDiff` has an example code with this order of parameters `(oldData, newData)` while it seems that the correct order is `(newData, oldData)`

```
let data = [...];

function updateData(index, item) {
  // make a shallow copy
  data = data.slice();
  data.splice(index, 1, item);
  const layer = new ScatterplotLayer({
    data,
    // Only update the attributes at `index``
    _dataDiff: (oldData, newData) => [{startRow: index, endRow: index + 1}],
    ...
  });
  deck.setProps({layers: [layer]});
}
```

**Comment by Pessimistress** [comment]
Looks like the doc shows the order of the arguments correctly, it's the sample code that's flipped.
