### ISSUE TITLE
Setting tooltip using binary data format

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#4418]
### Question:

How do you set the 'tooltip' attribute when using the binary data format?

### Worked example

Adding a tooltip to a 'standard' layer is trivial following [your examples](https://deck.gl/#/documentation/developer-guide/adding-interactivity?section=the-picking-info-object).

```js

  const normalScatter = new deck.ScatterplotLayer({
    data: [
        {position: [2, 2], message: 'Hover over me'}
      ],
    id: "normal",
    getPosition: d => d.position,
    getFillColor: [0,0,255],
    getRadius: 100000,
    pickable: true,
    onHover: info => setTooltip(info.object, info.x, info.y)
  });

  function setTooltip(object, x, y) {
    const el = document.getElementById('tooltip');
    if (object) {
      el.innerHTML = object.message;
      el.style.display = 'block';
      el.style.left = x + 'px';
      el.style.top = y + 'px';
    } else {
      el.style.display = 'none';
    }
  };
```

However, when using the binary data format, the `info` object doesn't exist. So how do you tell `onHover` where to get the data?

```js
  const binaryLocation = new Float32Array([0,0]);
  const binaryRadius = new Float32Array([100000]);
  const binaryColour = new Float32Array([255,0,0]);

  const binaryScatter = new deck.ScatterplotLayer({
    id: "binary",
    data: {
      length: 1,
      attributes: {
        getPosition: {value: binaryLocation, size: 2},
        getRadius: {value: binaryRadius, size: 1},
        getFillColor: {value: binaryColour, size: 3}
      }
    },
    pickable: true,
    onHover: info => setTooltip(info.object, info.x, info.y)
  });
```

[here](https://jsfiddle.net/symbolixau/r0hbsxvt/64/) is a working jsfiddle with a full example.

**Comment by Pessimistress** [comment]
`info` is always available, however `info.object` will be empty if you use binary attributes. You can check `info.layer.id` and then use `info.index` to look up the information from other data sources.

**Comment by SymbolixAU** [comment]
Excellent. Yes I can use the `layer.id` and `info.index` to reference the data object.

[updated working fiddle](https://jsfiddle.net/symbolixau/r0hbsxvt/81/)

Thanks, as always @Pessimistress
