### ISSUE TITLE
Extending a Layer - adding a new accessor function

### ISSUE THREAD

**Issue by SymbolixAU** [uber/deck.gl#4433]
**How do I define a new accessor in an extended layer using the scripting API?**

---

I'm using the scripting API and trying to learn how to extend a layer. The specific issue I'm facing is, how do I 'insert' a new accessor function? Here is a [jsfiddle example](https://jsfiddle.net/symbolixau/pxLs8n2y/74) showing where I'm up to, and I've replicated the specific deckgl code here:

```js
const data = [
    {
      path: [[0.1,0],[0.3,0.2]],
      colour: [[255,0,0,255],[0,255,0,0,255]]
    }
   ]
 
  class AnotherPathLayer extends deck.PathLayer {
  
    initializeState() {
      super.initializeState();
      this.state.attributeManager.addInstanced({
        instanceAnotherColour: {
        size: this.props.colorFormat.length,
        //type: GL.UNSIGNED_BYTE,
        normalized: true,
        accessor: 'getAnotherColour',
        transition: deck.ATTRIBUTE_TRANSITION,
        defaultValue: deck.DEFAULT_COLOUR,
        }
      });
    }
  
    getShaders() {
      return {
        ...super.getShaders(),
        inject: {
          'vs:#decl': 'attribute vec4 instanceAnotherColour;',
        }
      }
    }
  }
  
  const defaultProps = {
    getAnotherColour: {
      type: 'accessor', 
      value: deck.DEFAULT_COLOUR
    }
  }

//  AnotherPathLayer.layerName = 'AnotherPathLayer';
//  AnotherPathLayer.defaultProps = defaultProps;
 
  const pathLayer = new AnotherPathLayer({
    map_id: 'map',
    id: 'normal',
    data: data,
    getPath: d => d.path,
    getColor: d => d.colour,
    getWidth: 1000
  });
 
   deckgl.setProps({layers: [pathLayer] });
```
Where should the 

```js
getAnotherColour: {
      type: 'accessor', 
      value: deck.DEFAULT_COLOUR
    }
``` 
be placed so that the `getAnotherColour` accessor is accessible to the `AnotherPathLayer`?

**Comment by Pessimistress** [comment]
```js
AnotherPathLayer.defaultProps =  {
    getAnotherColour: {
      type: 'accessor', 
      value: deck.DEFAULT_COLOUR
    }
  }
```

**Comment by SymbolixAU** [comment]
That gives 

> Error: accessor "getAnotherColour" is not a function

<img width="1425" alt="Screenshot 2020-03-31 at 11 01 29 am" src="https://user-images.githubusercontent.com/18344164/77973170-38205b80-733f-11ea-9405-af5bee0326a2.png">

**Comment by Pessimistress** [comment]
`deck.DEFAULT_COLOUR` in your prop definition is undefined.

**Comment by SymbolixAU** [comment]
oh yes, the `U` !

And that points out the other bug I had too; I hadn't defined those constants!

all working now - https://jsfiddle.net/symbolixau/pxLs8n2y/88/
