### ISSUE TITLE
Increase line width on hover 

### ISSUE THREAD

**Issue by UttamRahane** [uber/deck.gl#4435]
How can I increase width of line on hover? I want to click on line and it's hard to pick line because it's width in 1. I can't set more because there are lot of lines so I want to increase width of particular line on hover.

**Comment by 1chandu** [comment]
Buy writing a custom layer you can achieve this, basically your custom layer vertex shader would check if current vertex belongs to picked instance and scale it if so.

If all you need is able to pick when you get closer to the line, easier thing would be to use [pickingRadius](https://deck.gl/#/documentation/deckgl-api-reference/deck?section=pickingradius-number-optional-) prop, set it to a value like 5 or 10.

**Comment by UttamRahane** [comment]
Thanks, it helps to solve my issue.

**Comment by neelduttahere** [comment]
Hey @1chandu ,

Is there a way to achieve this without writing a custom layer, but altering `_subLayerProps`?
