### ISSUE TITLE
Way of saving canvas to image in deck.gl

### ISSUE THREAD

**Issue by liokm** [uber/deck.gl#4436]
Hi, I want to save the webgl canvas to image by using `toDataURL` or `gl.readPixels` and have some questions:

- In order to read from canvas, seems I need to use `deck.redraw()` to trigger the render and read from framebuffer. ~~Since I am using `<DeckGL>` in React and, according to [the code](https://github.com/uber/deck.gl/blob/master/modules/react/src/deckgl.js#L64) the `this.deck` is not exposed from `<DeckGL>`, how could I achieve this without passing customized deck instance?~~ Use `ref.current.deck.redraw(true)`
- What is your recommendation of the way saving canvas to image, in deck.gl?
Thanks!

**Comment by kylebarron** [comment]
You probably want to use a `ref`, e.g.:
```jsx
        <DeckGL
          ref={ref => {
            this.deck = ref;
          }}
```
Then you can access deck.gl in the class through `this.deck`

**Comment by liokm** [comment]
@kylebarron Thank you, that makes sense. ref works here.

**Comment by baiqiushi** [comment]
Hi, I'm glad I saw this issue. I'm facing the same issue here, wanna save deck.gl scatterLayer result to an image. But I am using plain JS, can you elaborate more on how to do this? Thank you!

My code looks like this:
```html
<div id="deck-gl-canvas"></div>
```

```javascript
$scope.scatterLayer = new deck.DeckGL({
              container: 'deck-gl-canvas',
              initialViewState: {
                  latitude: $scope.map.getCenter().lat,
                  longitude: $scope.map.getCenter().lng,
                  zoom: $scope.map.getZoom() - 1,
                  bearing: 0,
                  pitch: 0
              },
              controller: true,
              layers: []
       });

const deckGLScatterplot = new deck.ScatterplotLayer({
              id: 'deck-gl-scatter',
              data: $scope.points,
              radiusMinPixels: Math.round($scope.pointRadius),
              getPosition: d => [d[1], d[0]],     // returns longitude, latitude, [altitude]
              getRadius: d => $scope.pointRadius,  // returns radius in meters
              getFillColor: d => [0, 0, 255]           // returns R, G, B, [A] in 0-255 range
    });

$scope.scatterLayer.setProps(
          {
                layers: [deckGLScatterplot],
                viewState:
                  {
                    latitude: $scope.map.getCenter().lat,
                    longitude: $scope.map.getCenter().lng,
                    zoom: $scope.map.getZoom() - 1,
                    bearing: 0,
                    pitch: 0
                  }
          });
```

**Comment by tsherif** [comment]
If you use the `onAfterRender` callback, you shouldn't need `preserveDrawingBuffer` (which has some performance implications), since it will be in the same `requestAnimationFrame` loop.

**Comment by baiqiushi** [comment]
Hi @Pessimistress and @tsherif , thank you for your suggestions! Actually I figured out myself with using the `html2canvas` tool, and it's quite simple, just call the `DeckGL.redraw(true)` before capturing the canvas content. The code snippet is pasted here in case anyone in the future may also need this:

#### Please NOTE: my method only works for static plots of deck.gl, not for animations

```javascript
function screenshot() {
        // force redraw of deckgl
        $scope.scatterLayer.redraw(true);
        // get the container div of deck.gl
        let div = document.getElementById("deck-gl-canvas");
        // use html2canvas tool to capture the content of the canvas inside the div and download it as an png file
        html2canvas(div).then(canvas => {
              document.body.appendChild(canvas);
              let a = document.createElement('a');
              // toDataURL defaults to png, so we need to request a jpeg, then convert for file download.
              a.href = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
              a.download = 'screenshot.png';
              a.click();
        });
}
```

Best,
Qiushi

**Comment by tsherif** [comment]
Great! It doesn't look like you need that `html2canvas` tool though. The element you get with `document.getElementById("deck-gl-canvas")` is already a canvas. I believe the rest of your code will work the same way, i.e.
```js
let canvas = document.getElementById("deck-gl-canvas");
document.body.appendChild(canvas);
let a = document.createElement('a');
// toDataURL defaults to png, so we need to request a jpeg, then convert for file download.
a.href = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
a.download = 'screenshot.png';
a.click();
```

**Comment by btbritz** [comment]
Anyone else getting a blank image when using the above ^ ? Thoughts on how to fix?

**Comment by btbritz** [comment]
NM, forgot to redraw() before saving.

**Comment by yingcongleong** [comment]
Hi, i tried the all the answer on above but it still doesn't work for me, whenever i try to export the image instead of getting current canvas as the image, i end up create a new canvas and save that canvas as image. How can i fix this problem? Thanks!

**Comment by SushantKumar29** [comment]
> Anyone else getting a blank image when using the above ^? Thoughts on how to fix it?

I am having the same issue, Any way to fix it ??

**Comment by arthurgailes** [comment]
@SushantKumar29 

Had to hack this together, as onAfterRender can run dozens of times for complicated maps, and needs to run again after the redraw. 

My total process looks something like this:

```
<DeckGL
      ref={deckRef}
      {...}
      onAfterRender={() => {
        if (deckRef?.current?.deck.takeScreenshot) {
          mapScreenshot({ deck: deckRef.current.deck });
        }
      }}
    />
```

```
// clicking for screenshot
onClick=() => {
        deckRef.current.deck.redraw(true);
        Object.assign(deckRef.current.deck, { takeScreenshot: true });
      }
```


```
let functionHasRun = false;

export function mapScreenshot({ deck }: { deck: any }) {
// limit to after all layers are reloaded
  const areAllLayersLoaded = deck.props.layers.every(
    (layer: { isLoaded: boolean }) => layer.isLoaded,
  );
  if (!areAllLayersLoaded) return;
  // force a second redraw of deckgl 
  if (!functionHasRun) {
    deck.redraw(true);
    functionHasRun = true;
    return;
  }
  // get the container div of deck.gl
  let div = document.getElementById('deckgl-wrapper');
  // need to use html2canvas in order to capture non-deck elements like mapbox basemap
  html2canvas(div).then((canvas) => {
    document.body.appendChild(canvas);
    let a = document.createElement('a');
    // toDataURL defaults to png, so we need to request a jpeg, then convert for file download.
    a.href = canvas.toDataURL('image/png').replace('image/png', 'image/octet-stream');

    a.download = 'screenshot.png';
    a.click();
  });
  functionHasRun = false;
   // a hack added to the deckgl object
  deck.takeScreenshot = false;
}
```

**Comment by davidcalhoun** [comment]
Full example in React, if you only want the deck.gl overlay in a transparent PNG without the base map background, here's a quick and dirty simple example:

```tsx
import React, { useRef } from 'react';
...

export default function App() {
    const deckRef = useRef(null);

    return (
            <DeckGL
                ...
                ref={deckRef}
                onAfterRender={() => {
                    // Fires multiple times.

                    // Converts the deck.gl canvas to a base64-encoded image.  Other image MIME types can be used here as well.
                    // See https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
                    const base64Image = deckRef?.current?.deck?.canvas?.toDataURL('image/png');

                    // Creates a temporary link and clicks on it to download.
                    // No need to append this element to the DOM.
                    const a = document.createElement('a');
                    a.href = base64Image;
                    a.download = 'screenshot.png';
                    a.click();
                }}
            >
                ...
            </DeckGL>
    );
}

```

This will download multiple screenshots that will download automatically to your computer.  The first few will be blank.

**Comment by chrisgervang** [comment]
[`getCanvas()`](https://deck.gl/docs/api-reference/core/deck#getcanvas) is now recommended over directly accessing the protected canvas property. It'll return the correct canvas when integrating with other basemaps, like maplibre.

```ts
import React, { useRef } from 'react';
...

export default function App() {
    const deckRef = useRef(null);

    return (
            <DeckGL
                ...
                ref={deckRef}
                onAfterRender={() => {
                    // Fires multiple times.

                    // Converts the deck.gl canvas to a base64-encoded image.  Other image MIME types can be used here as well.
                    // See https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
                    const base64Image = deckRef?.current?.deck?.getCanvas()?.toDataURL('image/png');

                    // Creates a temporary link and clicks on it to download.
                    // No need to append this element to the DOM.
                    const a = document.createElement('a');
                    a.href = base64Image;
                    a.download = 'screenshot.png';
                    a.click();
                }}
            >
                ...
            </DeckGL>
    );
}
```

**Comment by danilo-css** [comment]
> [`getCanvas()`](https://deck.gl/docs/api-reference/core/deck#getcanvas) is now recommended over directly accessing the protected canvas property. It'll return the correct canvas when integrating with other basemaps, like maplibre.
> 
> ```ts
> import React, { useRef } from 'react';
> ...
> 
> export default function App() {
>     const deckRef = useRef(null);
> 
>     return (
>             <DeckGL
>                 ...
>                 ref={deckRef}
>                 onAfterRender={() => {
>                     // Fires multiple times.
> 
>                     // Converts the deck.gl canvas to a base64-encoded image.  Other image MIME types can be used here as well.
>                     // See https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
>                     const base64Image = deckRef?.current?.deck?.getCanvas()?.toDataURL('image/png');
> 
>                     // Creates a temporary link and clicks on it to download.
>                     // No need to append this element to the DOM.
>                     const a = document.createElement('a');
>                     a.href = base64Image;
>                     a.download = 'screenshot.png';
>                     a.click();
>                 }}
>             >
>                 ...
>             </DeckGL>
>     );
> }
> ```

This works but it downloads a lot of screenshots and doesn't keep the basemap. 

Does anyone know how I could trigger it with a button to download a single image, keep the basemap and get the image to be higher resolution?
