### ISSUE TITLE
map gets flipped on x-axis running on Alpine with Chromium 80 using Xvfb

### ISSUE THREAD

**Issue by FibreFoX** [uber/deck.gl#4443]
#### Description
For a project of mine I use some automated headless test-setup, where a build-server does end-to-end testing. After an upgrade to the [latest chromium-version provided by Alpine-Linux edge](https://pkgs.alpinelinux.org/packages?name=chromium&branch=edge) a lot of tests broke, because the integrated deck.gl based map now is mirrored/flipped on x-axis.

#### Repro Steps
- you need to have a working Docker-setup locally/remote
- use the following as `Dockerfile_311` content
```
FROM alpine:3.11
RUN apk add --no-cache \
    bash \
    nss \
    ttf-freefont \
    udev \
    mesa-gles \
    mesa-dev \
    mesa-osmesa \
    mesa-dri-swrast \
    xvfb \
    chromium \
    chromium-chromedriver

RUN mkdir -p /usr/lib/chromium/swiftshader/
RUN ln -s /usr/lib/libEGL.so /usr/lib/chromium/swiftshader/libEGL.so
RUN ln -s /usr/lib/libGLESv2.so.2 /usr/lib/chromium/swiftshader/libGLESv2.so
RUN ln -s /usr/lib/libOSMesa.so.8 /usr/lib/chromium/libosmesa.so

VOLUME /opt/export

WORKDIR /opt/export
```
- create a docker-image `docker build -f ./Dockerfile_311 -t deckglbug:alpine311`
- use the following as `Dockerfile_edge` content
```
FROM alpine:edge
RUN apk add --no-cache \
    bash \
    nss \
    ttf-freefont \
    udev \
    mesa-gles \
    mesa-dev \
    mesa-osmesa \
    mesa-dri-swrast \
    xvfb \
    chromium \
    chromium-chromedriver

RUN mkdir -p /usr/lib/chromium/swiftshader/
RUN ln -s /usr/lib/libEGL.so /usr/lib/chromium/swiftshader/libEGL.so
RUN ln -s /usr/lib/libGLESv2.so.2 /usr/lib/chromium/swiftshader/libGLESv2.so
RUN ln -s /usr/lib/libOSMesa.so.8 /usr/lib/chromium/libosmesa.so

VOLUME /opt/export

WORKDIR /opt/export
```
- create a docker-image `docker build -f ./Dockerfile_edge -t deckglbug:alpineedge`
- after all images were build, please create some `export`-folder to mount into the docker-containers later
- to verify it is working, create a temporary docker-container: `docker run --rm -ti -v $(pwd)/export:/opt/export deckglbug:alpine311 /bin/bash`
- (inside the container) please start a virtual framebuffer with WebGL-extension: `Xvfb :1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &`
- (inside the container)just to make sure, export the display `export DISPLAY=":1"`
- (inside the container) to (finally) create the first screenshot, please execute this command (the parameters are part of our test-setup): `chromium-browser --no-sandbox --use-gl=swiftshader --ignore-gpu-blacklist --disable-extensions --ignore-certificate-errors --disable-dev-shm-usage --force-device-scale-factor=1 --headless --window-size=1920,1080 --disable-gpu --screenshot https://deck.gl/`
- (inside the container) to access the screenshot, you need to give permissions (danger: unsecure permissions here): `chmod 0666 screenshot.png`
- (inside the container) now quit/stop the docker-container (should cleanup itself): `exit`
- check the created screenshot, it should look okay (please ignore the CSS-stuff, look at the map, it should be "normal")
- to now see the bug appearing, create a different temporary docker-container: `docker run --rm -ti -v $(pwd)/export:/opt/export deckglbug:alpineedge /bin/bash`
- (inside the alpineedge container) please start a virtual framebuffer with WebGL-extension: `Xvfb :1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &`
- (inside the alpineedge container)just to make sure, export the display `export DISPLAY=":1"`
- (inside the alpineedge container) to (finally) create the second screenshot, please execute this command (the parameters are part of our test-setup): `chromium-browser --no-sandbox --use-gl=swiftshader --ignore-gpu-blacklist --disable-extensions --ignore-certificate-errors --disable-dev-shm-usage --force-device-scale-factor=1 --headless --window-size=1920,1080 --disable-gpu --screenshot https://deck.gl/`
- (inside the alpineedge container) to access the screenshot, you need to give permissions (danger: unsecure permissions here): `chmod 0666 screenshot.png`
- (inside the alpineedge container) now quit/stop the docker-container (should cleanup itself): `exit`
- check the created screenshot, it should look broken, the city is "upside down"

#### Environment:
- Framework: deck.gl 8.1.1 (the deck.gl website currently resolves to that)
- Browser Version (not working): Chromium 80.0.3987.132-r2
- Browser Version (working): Chromium 79.0.3945.130-r0
- OS (working): Alpine Linux 3.11
- OS (not working): Alpine Linux Edge

#### Logs
no relevant logs could be gathered

**Comment by 1chandu** [comment]
Can you verify if actual rendering of deck.gl is fine (without your automated test setup), if so this could be an issue with how the test result is captured and compared?

**Comment by FibreFoX** [comment]
@1chandu As I posted instructions that are using a "minimal" setup to reproduce this issue without my test-harness, you are able to see for yourself. This has nothing to do with my test-setup.

The first Dockerfile runs with Alpine 3.11 + Chromium 79, the later one runs with Alpine Edge. and when you are using my instructions above, you will see deck.gl rendering okay, nothing that gets corrupted due to any test-framework I am using.

**Comment by FibreFoX** [comment]
To make it more visual, here are the screenshots that are generated by chrome/chromium as described above.

With Alpine Edge + Chromium 80:
![screenshot](https://user-images.githubusercontent.com/1042579/78218540-3e891180-74be-11ea-804f-2a87a3242220.png)
With Alpine 3.11 + Chromium 79:
![screenshot_79](https://user-images.githubusercontent.com/1042579/78218546-41840200-74be-11ea-8d23-2aa930d6531a.png)

**Comment by ibgreen** [comment]
Naively, it looks like the graphics driver in this config is flipping the Y axis.

Given your rather special setup, unless there is evidence to the contrary (e.g. you are able to confirm that older deck.gl versions work), I would not expect this issue to be deck.gl specific. 

It sounds like something that could affect other 3D apps as well. Have you tested other WebGL applications and 3D frameworks, e.g. THREE.js demos etc?  

Also relevant since you are running deck in Docker image, without a GPU: https://github.com/uber/deck.gl/blob/master/dev-docs/platform-support.md#virtual-machines

**Comment by FibreFoX** [comment]
@ibgreen thanks for the update, I will check if I can spot something interesting regarding the drivers
As I have to check other "demo"-pages via chrome-screenshot CLI-command, this might take a while.

What is curious: it works in "older" versions, but breaks with current Edge + Chromium 80, I will check if I am able to have some Debian-based setup for this, maybe this is Alpine-specific/some Alpine-bug.

**Comment by FibreFoX** [comment]
After playing around with Docker, this is the Debian-based setup I created:
```
FROM debian:buster

RUN apt-get update && apt-get install -y chromium xvfb libegl1 libgles2 libosmesa6 

RUN mkdir -p /usr/lib/chromium/swiftshader/
RUN ln -s /usr/lib/x86_64-linux-gnu/libEGL.so.1 /usr/lib/chromium/swiftshader/libEGL.so
RUN ln -s /usr/lib/x86_64-linux-gnu/libGLESv2.so.2 /usr/lib/chromium/swiftshader/libGLESv2.so
RUN ln -s /usr/lib/x86_64-linux-gnu/libOSMesa.so.8 /usr/lib/chromium/libosmesa.so

VOLUME /opt/export

WORKDIR /opt/export
```

Calling `chromium --no-sandbox --use-gl=egl --ignore-gpu-blacklist --disable-extensions --ignore-certificate-errors --disable-dev-shm-usage --force-device-scale-factor=1 --headless --window-size=1920,1080 --screenshot https://deck.gl/` seems to create a proper screenshot.

Will investigate a bit more, not yet sure if this is a compatibility-bug of deck.gl/underlying libs or the package from Alpine.

**Comment by FibreFoX** [comment]
Hahaha, got this working, seems that chrome not works a bit different now.

Command for Alpine 3.11 / Chromium 79:
```
chromium-browser --no-sandbox --use-gl=swiftshader --ignore-gpu-blacklist --disable-extensions --ignore-certificate-errors --disable-dev-shm-usage --force-device-scale-factor=1 --headless --window-size=1920,1080 --disable-gpu --screenshot https://deck.gl/
```

Command for Alpine Edge / Chromium 80:
```
chromium-browser --no-sandbox --use-gl=egl--ignore-gpu-blacklist --disable-extensions --ignore-certificate-errors --disable-dev-shm-usage --force-device-scale-factor=1 --headless --window-size=1920,1080 --screenshot https://deck.gl/
```

Not quite sure if this is really chromium, or my personal setup with Xvfb. Without ` --disable-gpu` and switching to `egl` instead of `swiftshader` now seems to work out for me.

Sorry folks to worry you about this, but maybe it helps others with some older headless setup.

**Comment by FibreFoX** [comment]
Might have spoken too soon. I still have problems with the new command.

Will report back when having found more details.

**Comment by FibreFoX** [comment]
Short Update from my side: this seems to be "fixed" with Chromium 81 on Alpine ... no idea why this happened, but are happy that this is working with swiftshader again.
