### ISSUE TITLE
Is it possible to update TileLayer sublayers when something changes?

### ISSUE THREAD

**Issue by MehdiSaffar** [uber/deck.gl#4445]
I am building an editor for OSM nodes. It looks something like this:

![image](https://user-images.githubusercontent.com/13124263/78276151-50e56880-751b-11ea-899d-163f1b919da5.png)

I am using `TileLayer` to retrieve the nodes.

Each node has an associated value, from which I derive the color based on a color scheme. The color scheme can be selected by the user at anytime. 

I would like to refresh the tile layer's color scheme when the user changes it. I tried

```
updateTriggers: {
    renderSubLayers: [colorScheme]
}
```

but it doesn't work. The only solution I found is to add a trigger to `getTileData`:
```
updateTriggers: {
    getTileData: [colorScheme]
}
```
unfortunately this means querying the server for the same exact information, while I could simply update the fill color of the nodes.

When the user selects a color scheme while the tiles are loaded, some might have the first color scheme while others have the second color scheme (see screenshot) which I think is not good user experience.

My code: 

```
const tileLayer = new TileLayer({
    updateTriggers: {
	getTileData: [this.colorScheme] // here
    },
    minZoom: 12,
    maxZoom: 12,
    getTileData: async ({bbox}) => {
	const nodes = [] // get nodes based on bbox
	return { bounds, nodes }
    },
    renderSubLayers: (layer) => {
	const { id, data } = layer

	if (data.then) return null

	const { nodes } = data

	const getValue = node => node.value
	const domain = getDomain(getValue, nodes)
	const { colorScheme } = this
	const radiusScale = d3.scaleSqrt()
	    .domain(domain)
	    .range(radiusRange)
	    .clamp(true)
	    .unknown(radiusRange[0])


	const colorRange = colorScheme.discrete
	const colorScale = d3.scaleSequential(colorScheme.continuous).domain(domain)

	const getPosition = node => node.location.coordinates
	const getFillColor = node => toRgbArray(colorScale(getValue(node)))
	const getRadius = node => radiusScale(getValue(node))

	return new ScatterplotLayer({
	    id,
	    data: data.nodes,
	    getPosition,
	    getFillColor,
	    getRadius,
	    opacity: 0.2,
	    pickable: false,
	})
    }
})
```

Any way to achieve what I want without refetching the tiles? Thanks!

**Comment by Pessimistress** [comment]
Change any prop on your `TileLayer` will invalidate the cached results of `renderSubLayers`. e.g.

```js
const tileLayer = new TileLayer({
    getTileData,
    renderSubLayers,
    minZoom: 12,
    maxZoom: 12,
    colorScheme
})
```

**Comment by MehdiSaffar** [comment]
That worked, thanks a lot! I didn't know we could pass any props to TileLayer directly.

**Comment by sheeceg** [comment]
Hi, whats the syntax to pass a props to TileLayer directly?

**Comment by N-D-P** [comment]
I have exact problem, filtering the data point is working but it is very slow, as It will call the DB and get new tiles, I was thinking of using DataFilterExtension, if you have solved this problem can you provide more details how you achieved it
