### ISSUE TITLE
TextLayer backgroundColor not showing up.

### ISSUE THREAD

**Issue by btbritz** [uber/deck.gl#4459]
Given a new TextLayer layer:
```
layers.push(new TextLayer({
  id: `label-layer[${i}]`,
  data: placeholderArr, // mock data
  pickable: true,
  getPosition: d => d.coordinates,
  getText: d => d.label,
  getSize: 16,
  getColor: d => d.color,
  opacity: 1,
  getTextAnchor: 'middle',
  getAlignmentBaseline: 'center',
  backgroundColor: [0, 0, 250] // Doesn't seem to work?
}))
```
Not sure why backgroundColor wouldn't work?

**Comment by Pessimistress** [comment]
Please report the version of deck.gl and browser used.

Does the `backgroundColor` in the [documentation](https://deck.gl/#/documentation/deckgl-api-reference/layers/text-layer) work for you?

**Comment by btbritz** [comment]
@Pessimistress Thank you for the response.

Version: ^7.3.6 
Browser: Chrome 80.0.3987.149 (Official Build) (64-bit)

In the documentation, it only works only **after** I change the the color manually in the running example.

Thanks again.

**Comment by Pessimistress** [comment]
`backgroundColor` support was added in 8.0.

**Comment by ibgreen** [comment]
Maybe we should adopt a convention of adding a `"from:v8.0" badge or similar to classes and props in the docs when we add new features? I was about to start doing that in loaders.gl...

**Comment by btbritz** [comment]
That was it. Thank you.

@ibgreen Love that idea :)
