### ISSUE TITLE
pydeck Binder gives a "404: Not Found" error

### ISSUE THREAD

**Issue by JackKelly** [uber/deck.gl#4462]
#### Description
Clicking on the [binder link](https://mybinder.org/v2/gh/uber/deck.gl/binder?filepath=examples) in the [pydeck docs](https://deckgl.readthedocs.io/en/latest/) takes the user to binder.  Binder spends about a minute loading the environment, and then reports "404: Not Found".

(deck.gl is great, BTW!  Thanks so much for all your hard work!)

#### Environment (please complete the following information):
 - Browser Version: Firefox 75.0
 - OS: Ubuntu 19.10

**Comment by ajduberstein** [comment]
Thanks for reporting–I'll get this fixed.

As a workaround, you can cut the `/examples` off the url and see the notebooks in the Jupyter file finder.

**Comment by ajduberstein** [comment]
Fixed in our new documentation at https://pydeck.gl/
