### ISSUE TITLE
Deck.GL StaticMap viewState & ViewPort Problem

### ISSUE THREAD

**Issue by drunkenmyno** [uber/deck.gl#4489]
Hello, i'm using Superset with Deck.GL Components but currently im facing a problem with a StaticMap and more then one layer on it 

the viewState gets updated with correct coordinates but the viewport will not update

![deck gl problem](https://user-images.githubusercontent.com/19605766/79216786-0da9c480-7e4e-11ea-9841-5ac2457b357e.png)

the above red marked is the viewState and below the viewport.

I'm using Deck.Gl version 7.1.11

this is the React Code i used as a return

 return React.createElement(React.Fragment, null, React.createElement("div", {
      style: {
        position: 'relative',
        width,
        height: adjustedHeight
      }
    }, React.createElement(DeckGL, {
      initWebGLParameters: true,
      controller: true,
      width: width,
      height: adjustedHeight,
      layers: layers,
      viewState: viewState,
      onViewStateChange: this.onViewStateChange
    }, React.createElement(StaticMap, {
      mapStyle: this.props.mapStyle,
      viewState: viewState,
      mapboxApiAccessToken: this.props.mapboxApiAccessToken
    })), children), React.createElement(Tooltip, {
      tooltip: tooltip
    }));

Thanks for any suggesstion

**Comment by Pessimistress** [comment]
We are no longer maintaining v7.1. Is it possible for you to upgrade to v8 or at least 7.3?

**Comment by drunkenmyno** [comment]
I updated now to 8.1.1 still the same :) the viewport did not get rendered correctly
