### ISSUE TITLE
Coordinate precesion is low in projected views

### ISSUE THREAD

**Issue by kachkaev** [uber/deck.gl#45]
Looks like deck.gl layers can only be used on the small zoom levels at the moment due to the way the coordinates are being projected. Here is the difference between how the polygons from the example  are rendered by the library and QGIS:

![sf_webgl](https://cloud.githubusercontent.com/assets/608862/17400179/62b9090a-5a3e-11e6-9f0b-46875862774c.PNG)
![sf_qgis](https://cloud.githubusercontent.com/assets/608862/17399980/404ba27a-5a3d-11e6-9f1d-7d1510dbd434.png)

The outlines wobble quite noticeably when you change the viewport, which suggests that not enough precision is being applied in trigonometric functions inside glsls. Attempts to use different numeric types in various places did not help in my case due to lack of WebGL / deck.gl knowledge.

It would be nice if the layers could be upgraded to (optionally) support higher precision during rendering. Until then, let this issue be a warning to those who want to render something on top of MapboxGL at a building scale :–)

Please share your code if you've managed to patch any of the built-in deck.gl layers!

__UPD__ Demo of wobbling (underlying MapboxGL layer works OK):
![wobbling](https://cloud.githubusercontent.com/assets/608862/17400617/c8e6290e-5a40-11e6-81fb-9de62167b2d7.gif)

**Comment by contra** [comment]
@kachkaev Did you ever find a workaround for this? Basically makes the built-in layers unusable atm :(

**Comment by gnavvy** [comment]
This is different from the primitive distortion issue, but might be alleviated by that fix depending what coordinate system you are using.

As you mentioned, there's a tradeoff between precision (CPU 64bit floating point) and speed (GPU 32bit floating point in glsl 1.00), and we chose the latter. There are walkarounds, e.g. using multiple coordinate systems. The ideal solution is to simulate high-precision floating point operations, we have done some work on that but need more tests (1+ week(s)) before we are comfortable to release it.

**Comment by kachkaev** [comment]
@contra still no workaround unfortunately. Had to limit the zoom level to 14, but this is not possible in any app. Really looking forward for a solution by @gnavvy. Would be good if the official example was properly synced with the library upon release (see #43)!

**Comment by gnavvy** [comment]
@kachkaev could you share a slice of your data please? We didn't observe salient distortion until zoom > 18 (if we are both referring to the mapbox zoom level). wondering how your data is formatted.

**Comment by kachkaev** [comment]
@gnavvy the images and the animation above are obtained from your data, which you refer to from the example.

**Comment by contra** [comment]
@gnavvy Wobbling is visible in the demo (Chrome @ 52.0.2743.116 (64-bit), OSX)

**Comment by contra** [comment]
Any implementation tips? I could take a whack at this if I knew where to start!

**Comment by ibgreen** [comment]
@contra - We are finalizing a general solution for high zoom levels and higher coordinate precision. Stay tuned.

**Comment by ibgreen** [comment]
In the deck.gl v3 beta releases we now have both 64 bit layers, and meter offset mode for 32 bit layers, which both solve this. Already consumable from beta releases and will be merged to master
