### ISSUE TITLE
Demo site bugs

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#457]
### Layer docs in the demo site bugs
- [x] The color of the polygon layer is wrong when extrusion is enabled
- [x] The projectionMode slider needs to be removed from all layers
- [x] The GridLayer demo: uniforms.js:102 GridLayer-grid-cell  Bad uniform lonOffset NaN
- [x] Need a screenshot of the GridCellLayer
- [ ] After using the website for some time, this error message comes up: "map.js:1209 WARNING: Too many active WebGL contexts. Oldest context will be lost."

**Comment by ibgreen** [comment]
@shaojingli Consolidate with #441 ?
