### ISSUE TITLE
Make sublayer instance accessible in `CompositeLayer.getPickingInfo()`

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#466]
### Problem
Because the source sublayer is no longer exposed, user cannot define different hover behaviors for each sublayer by checking `info.layer`. They will instead have to infer this information using `info.object`, which requires them to know the implementation details of the composite layer.

### Proposed feature
When calling `getPickingInfo()` on a composite layer, pass an additional `sourceLayer` argument so that the composite layer can populate `info` with appropriate properties. This change will not affect the existing core layers, but give custom composite layers more context to decide what to expose to the user.

@ibgreen @shaojingli

**Comment by shaojingli** [comment]
#468
