### ISSUE TITLE
Move big demo data files out of core deck.gl repo

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#479]
About the big data files in the demo directory, we should move them out of this repository.

We mustn't let deck.gl become one of those 1GB monster repos that takes an hour to clone (if GitHub even supports such large repos).

A first suggestion is that we set up a new repo with just the demo data files, and we update our demo load its data from there. When then use `git filter-branch` to purge them completely from this repo.

**Comment by shaojingli** [comment]
Just as a reference, as of deck.gl v4.0.0-rc.5, the data transferred for a clean clone from github is 68.16 MiB.

**Comment by ibgreen** [comment]
We have removed the dependencies on master, now we need to remove them from the repo by rewriting history.
