### ISSUE TITLE
glslify appears to be a production dep

### ISSUE THREAD

**Issue by mike-marcacci** [uber/deck.gl#48]
I've been trying to use deck.gl in a webpack project, and have encountered a few snags. At first I thought `glslify` simply needed to be listed in `dependencies` rather than `devDependencies`, but I think there may be more subtlety here, so I figured I'd create an issue.

Either way, glslify does appear to be a production dependency, even in the dist.

**Comment by ibgreen** [comment]
@mike-marcacci 

deck.gl is pre transpiled with the babel-glslify plugin - all references to glslify in the dist folder (which is what the app should consume) should have been removed. Sounds like your webpack setup was still accessing src folder for some reason.

deck.gl is extensively tested with browserify but not with webpack. A webpack example PR would be welcome.

**Comment by mike-marcacci** [comment]
Hi @ibgreen - thanks for the response; taking your comment into consideration, I have reattempted to integrate deck.gl, but I definitely see references to `glslify` inside the dist, including `deckgl.js` and several of the layers:

![image](https://cloud.githubusercontent.com/assets/690517/18319702/b6327064-74db-11e6-8e40-d830f939b151.png)

**Comment by ibgreen** [comment]
>  I definitely see references to glslify inside the dist

@mike-marcacci - Yes it looks like your are correct. For now, we will move glslify to `dependencies` on dev branch and republish.
