### ISSUE TITLE
Demo site interaction bugs with react-map-gl@3.0.0

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#488]
1. Zoom is always centered at the canvas center instead of pointer position. This is a major usability issue.
2. Overlays cannot intercept mouse event any more (see icon example - click marker - mouse wheel over tooltip) by calling `event.stopPropagation`.

@ibgreen @shaojingli

**Comment by ibgreen** [comment]
#493 attempts to address 1 and includes the source code of the map controls component so that we can start debugging 2.

**Comment by shaojingli** [comment]
The current plan is to revert back to react-map-gl v2.x and fix the build issue there. So I'm going to remove the v4.0 label and retarget this issue to v4.1
