### ISSUE TITLE
deck.gl documentation issues

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#496]
Index (Left sidebar):
- [ ] Not being able to collapse topics will cause problems on mobile devices?

Getting Started
- [x] Title of first topic (Getting Started), align title with index (Installation)?
- [x] Title of "Using with Mapbox" doc - fix capitalization, remove hyphen in title.
- [x] Rename "Interactivity" => "Enabling Interactivity"? (to make it fit better with the other titles in the section)

Advanced Topics
- [x] Order looks random, can we think of a better order here? Either let's think it through, or at minimum just make them alphabetical...

Layer Catalog
- [x] Source code links inline with text - move up to tags or down to bottom?
- [x] Let's remove the deprecated layers.
- [x] HexagonCell and GridCell - they don't follow the documentation scheme (they have gifs instead of interactive docs), pulls down impression when clicking through the layers - all the other layers have exactly the same layout and design. Fix, or remove them from docs?
- [x] Have we made the final call on whether to include images or not?
- [x] PointCloudLayer still broken due to Viewport fix.
- [x] Have we tested the split screen layout on mobile devices?

API Reference
- [x] No source code links
- [x] The remark about methods not being intended for applications should also be added to "members" section.
- [x] We are documenting "internal" methods on AttributeManager (everything except `add*` and `invalidate*`) and Viewport (`getMatrices`).
- [x] Could be confusing, maybe clearly separate/mark as two sections of methods or use tags?
- [x] Should we include these methods at all? Could cause extra work when we change these?

**Completed**
- [x] Explain how to switch to non-cartographic projection mode
["To use this mode..."](https://github.com/uber/deck.gl/blob/master/docs/coordinate-systems.md#non-cartographic-projection-mode) <-- finish this sentence.
- [x] README under root folder has merge error at "## Developing" section.

**The following are moved from #441.**
- [x] Remove mention of Immutable support etc, until we have full support/test suite for this
- [x] Rigorous review of the Upgrade docs
- [x] Update API guidelines with latest decisions on composite layers, line vs stroke etc.
- [x] Improve "Getting Started" page
- [x] Consider bumping "Getting Started" to be the first thing in the docs. People often learn by jumping in and modifying, rather than by R'ingTFM.

**Comment by shaojingli** [comment]
Thanks @ericsoco ! This is very valuable! Let use this issue to track all docs related change we need to make.

**Comment by ericsoco** [comment]
@ibgreen cleared up many doc issues in #507. Not sure if we still need this issue or not.

**Comment by shaojingli** [comment]
@ericsoco let's keep it up for a little longer. New doc issues might come out and we could just an entry this issue.

**Comment by ibgreen** [comment]
Added list of comments from a recent revie
