### ISSUE TITLE
Add support for rendering multiple primitives in a single WebGL layer

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#5]
In the current implementation, each layer has only one primitive that uses one shader program.
Adding multiple primitives support will allow rendering more complex layers without duplicating the data.
e.g. allow render choropleth contour (gl.LINES) and filled region (gl.TRIANGLES) within one choropleth layer.

**Comment by ibgreen** [comment]
Supported in deck.gl v3 using new lifecycle methods `draw` and `pick`.
