### ISSUE TITLE
rendering overlays = multiple canvas with the same id

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#50]
not sure if this is configurable, couldn't track it down but seems like a bug

**Comment by gnavvy** [comment]
the recommended practice would be to create one canvas with multiple layers sharing the same gl context for the rendering.

**Comment by contra** [comment]
@gnavvy Does there need to be an ID at all? React's refs should allow you to reference the DOM element, and it seems like it isn't being used anyways. I removed the ID on my fork and everything works great.

**Comment by gnavvy** [comment]
by ID were you referring to the layer ID? it is used for:
1. matching layers so as to check if there's a change in data/viewport, if not, skip the calculation;
2. distinguish programs and geometries for multiple layers of the same type.

**Comment by contra** [comment]
@gnavvy RE: canvas element ID

**Comment by gnavvy** [comment]
you can specify canvas ID and style for each DeckGLOverlay for customized styling now, from v2.4.4.
<img width="788" alt="screen shot 2016-08-17 at 12 58 11 pm" src="https://cloud.githubusercontent.com/assets/144743/17751069/47f8ccf4-647a-11e6-83a4-32e6507fd49d.png">
