### ISSUE TITLE
Improve new user flow

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#505]
- [x] `npm start` fails if on a version of Node that doesn't run ES6. We should use `nvm` or similar to require 6.4 (based on [destructuring support](http://node.green/), without which webpack fails)  or greater (have we decided formally on a target?)
- [x] Be more explicit in README about `MAPBOX_ACCESS_TOKEN` requirement and in error if not set up. I see this is in [./demo](https://github.com/uber/deck.gl/blob/master/demo/README.md), but ./example/layer-browser requires it too, which means `npm start` fails out-of-the-box.
- [x] Install `layer-browser` deps the right way. `postinstall` hook is not correct. Will be fixed by https://github.com/uber/deck.gl/pull/504/.

**Comment by ericsoco** [comment]
@ibgreen any thoughts on Node version managing? Any precedent in other libs?

**Comment by ibgreen** [comment]
> We should use nvm or similar to require 6.4

Hmm, while I am always open to ideas, I don't think we should be installing/running nvm. It is really the user's responsibility to organize his development environment and manage different node versions.

> (based on destructuring support, without which webpack fails)

This doesn't sound right. Webpack should not require Node 6? Maybe just something in our webpack config files? They don't have to use every ES6 feature...

(have we decided formally on a target?)

Node version 6 brings ES6 support which is something we leveraged in deck.gl v4  to make tests run without transpilation. This was a pretty big effort and I would not like to go backwards. 

I don't personally see a value in supporting use of old node versions for development of deck.gl.

We should certainly update the requirement listed in the README
https://github.com/uber/deck.gl/blob/master/README.md#node-version-requirement. Open a PR?

> @ibgreen any thoughts on Node version managing? Any precedent in other libs?

I am not aware of any ways to provide warnings during development, other than adding additional scripts like you suggested.  The `engines` field in `package.json` is used during installation of the published package so not useful here. 

> Be more explicit in README about MAPBOX_ACCESS_TOKEN requirement and in error if not set up. I see this is in ./demo, but ./example/layer-browser requires it too, which means npm start fails out-of-the-box.

Just to confirm, failing to set the token should only mean that the map doesn't render. The app should still build and run. If that's not the case we have a problem. 

FWIW, I just opened a doc-fix PR that adds more info about tokens, but of course this remains a "gotcha" for the casual user who jumps directly into the example without reading the docs, installs and runs, and fails to get a map.

> Install layer-browser deps the right way. postinstall hook is not correct. Will be fixed by #504/.

Merged, thanks!

**Comment by ericsoco** [comment]
> This doesn't sound right. Webpack should not require Node 6? Maybe just something in our webpack config files? They don't have to use every ES6 feature...

Correct, the layer-browser example's webpack config uses destructuring. I guess alternatively we can not use ES6 in there, but that seems antithetical to the motion toward not even transpiling.

> Just to confirm, failing to set the token should only mean that the map doesn't render. The app should still build and run. If that's not the case we have a problem.

Correct, but without the map, (and with no layers on by default) the example _feels_ broken.

**Comment by ibgreen** [comment]
> Correct, the layer-browser example's webpack config uses destructuring. I guess alternatively we can not use ES6 in there.

Node 4 supports a lot of ES6 features - just not everything. I think just replacing the restructuring construct would likely make the rest of the config work on Node 4. PR welcome :)

And thinking more about this, you are absolutely right here: Ideally we would support two levels of Node.js (>6 for development of the core library, but >4 should suffice for running the examples).

Since we all work on Node 6 it can be hard to notice when we break Node 4 support, but that doesn't mean we shouldn't try.

>  Without the map, (and with no layers on by default) the example feels broken

Good point. I guess we could check that `token != null` in the examples and show some error in the browser (worst case, we could just use an ugly `window.alert` if we think this is better than just mysteriously showing no map?)

**Comment by ericsoco** [comment]
With #504, #507, #508, and #509, we can close this.
