### ISSUE TITLE
The blog branch should really be in a separate repo

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#510]
Every time I tried to pull the blog branch, it pulls down hundreds of megabytes of data from the entire deck.gl repo... we really need to move the blog branch to a different repo. 

Let's discuss after v4 release

**Comment by ibgreen** [comment]
> Let's discuss after v4 release

Sounds good. If we get the big data files out of the repo, maybe it could be OK to keep the blog with the code?

**Comment by ibgreen** [comment]
This is happening, no need to track it here.
