### ISSUE TITLE
scatterplot points completely distorted/invisible at higher zoom levels

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#52]
<img width="352" alt="screen shot 2016-08-14 at 11 09 15 pm" src="https://cloud.githubusercontent.com/assets/425716/17654722/318e352e-6274-11e6-8b2f-e97f909ebbe7.png">

To reproduce, just zoom in on a scatter plot view.

Possibly related to #45

**Comment by gnavvy** [comment]
We have already fixed this and will push the patch in two days.

**Comment by contra** [comment]
@gnavvy Any pointers? I can apply it on my own fork and test today.

**Comment by gnavvy** [comment]
just published 2.4.1 to fix the distortion for the scatterplot and the hexagon layer.
want to give it a try? @contra 
(the jittering on the centroids remains, unfortunately, will have to implement the high-precision simulation)

**Comment by jleyden** [comment]
Any idea on when the jittering will be resolved? Thanks!

**Comment by contra** [comment]
@jleyden @ericsoco This landed a looong time ago. Use the fp64 flag.
