### ISSUE TITLE
PointCloudLayer draw line issue.

### ISSUE THREAD

**Issue by objcdeveloper** [uber/deck.gl#533]
Isn't it possible to draw a line rather than points?

I need to draw a line from Location A to Location B above the map.

I tried to do this using PointCloudLayer since this supports 3d positioning.

Is it possible to support z index in other layers?

Or hope this PointCloudLayer supports draw line functionality.

Thank you.

**Comment by ibgreen** [comment]
> Isn't it possible to draw a line rather than points? I tried to do this using PointCloudLayer since this supports 3d positioning.

@objcdeveloper  Have you tried the LineLayer? It draws lines and it does support z positioning.

**Comment by objcdeveloper** [comment]
Line Layer?

Can you send the example?

**Comment by shaojingli** [comment]
https://github.com/uber/deck.gl/tree/master/examples/line

**Comment by objcdeveloper** [comment]
I tried this line already, but didn't find a way to make it draw above the map. Like 10 centimeters high above the map.

**Comment by objcdeveloper** [comment]
Sorry, my mistake, it works.

**Comment by shaojingli** [comment]
Good to know! Closing this.
