### ISSUE TITLE
(feature) scatterplot - set radius per item

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#54]
would be great to have the ability to set the radius per item, like you can do with color

**Comment by gnavvy** [comment]
this is actually one of the tasks in the tutorial branch.

**Comment by contra** [comment]
@gnavvy Any interest in bringing it into the layer?

**Comment by gnavvy** [comment]
added per item radius support in 2.4.1.
you can now specify the radius along with the position and color, for each point.

<img width="1106" alt="screen shot 2016-08-16 at 12 14 08 pm" src="https://cloud.githubusercontent.com/assets/144743/17721371/9144a686-63de-11e6-883a-2a842976cb95.png">

**Comment by contra** [comment]
@gnavvy Thanks! Much appreciated.
