### ISSUE TITLE
scatterplot - outline

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#55]
would be great to be able to specify an outline color + width on scatterplot points

temporary workaround is to render another layer with the same data, but different colors and a radius 1 unit higher at a z of 0, with your actual data points at a z of 1.

**Comment by gnavvy** [comment]
had the same issue for the choropleth layer. in deck.gl we tend to render one primitive for one layer, so the two-layer workaround is preferred for the moment.

**Comment by mcnuttandrew** [comment]
The above ^ PR doesn't quite address the letter of this issue, but provides an enhancement for the two layer approach

**Comment by mcnuttandrew** [comment]
Hey @contra, with the merge of #130 I think this issue is resolved, so i'm going to close it.

**Comment by contra** [comment]
@mcnuttandrew The scatterplot outline mode does only the outline, right? This ticket was about doing a dot with an outline (or shadow) for visibility reasons.
