### ISSUE TITLE
Lighting not working....on my machine only.

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#559]
Demos e.g. hero demo on index.html, geojson demo, have no lighting. Repro'd on:
- Chrome 57.0.2987.133
- Safari 10.0.3
- Firefox 52.0.2

OSX 10.12.3
MacBook Pro Retina 15"
Intel Iris Pro 1536 MB

<img width="1779" alt="screen shot 2017-04-06 at 10 47 26 am" src="https://cloud.githubusercontent.com/assets/1127259/24768173/76c7c8d0-1ab6-11e7-93bf-93fa3ef6c583.png">

**Comment by ericsoco** [comment]
Others here tested, no problems. Just me! 🎉

**Comment by shaojingli** [comment]
@ericsoco 
Is this a regression? or it's never worked?
Is there any error info in console?
Also, can you put luma.log.priority = 2 to the console and paste output there?

**Comment by ericsoco** [comment]
I believe it's a regression, but not certain.
We just determined the high-level cause is 64-bit mode; disabling it on the TripsLayer example (used on the demo homepage) restores lighting.

**Comment by shaojingli** [comment]
This stems from a bug from Intel Iris Pro GPU's compiler. Refer to #563
