### ISSUE TITLE
(feature) scatterplot - scale radius with zoom?

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#56]
I think this would be a nice feature to have by default, or the ability to turn this on easily.

You can do it yourself right now by writing your own wrapper to the layer and changing the radius based on zoom state, but this isn't ideal.

**Comment by gnavvy** [comment]
We can add support to allow radius defined based on real-world distances (e.g. 10km radius).
Though I have to deprioritize this for now, at least after the full geoJson geometry type support.

but PR is always welcomed : )

**Comment by contra** [comment]
@gnavvy ScatterPlotOverlay should redraw if the radius option changes, right? Can't seem to get that to work.

**Comment by gnavvy** [comment]
depends. the default radius will scale with the zoom (derived from a ∆latitude) but for now if you pass in your own radius, it will override the default one.
https://github.com/uber/deck.gl/blob/master/src/layers/scatterplot-layer/scatterplot-layer.js#L133

**Comment by contra** [comment]
@gnavvy Default radius doesn't seem to be scaling right.

<img width="718" alt="screen shot 2016-08-15 at 5 13 30 pm" src="https://cloud.githubusercontent.com/assets/425716/17679906/a46a5694-630b-11e6-957c-2e39b987f8d6.png">
<img width="571" alt="screen shot 2016-08-15 at 5 13 39 pm" src="https://cloud.githubusercontent.com/assets/425716/17679910/a7b4a2a0-630b-11e6-8090-d920c7b96e03.png">

**Comment by gnavvy** [comment]
could you elaborate on what is the problem with the scaling? the radius was defined to be approximately the same with the street size (bottom image) but became larger (top image) than expected when zoom in?

**Comment by contra** [comment]
@gnavvy Looks fine on lower zoom levels, but on higher zoom levels the dots become extremely large and eventually obscure the entire viewport.

This is with a ScatterplotLayer that has no radius parameter given, so being calculated here: https://github.com/uber/deck.gl/blob/master/src/layers/scatterplot-layer/scatterplot-layer.js#L138-L144

Here's what I'm trying to achieve:

<img width="682" alt="screen shot 2016-08-16 at 3 01 46 pm" src="https://cloud.githubusercontent.com/assets/425716/17712070/6b1fcb78-63c2-11e6-8281-879d8fab1206.png">
<img width="608" alt="screen shot 2016-08-16 at 3 01 16 pm" src="https://cloud.githubusercontent.com/assets/425716/17712077/7335b55c-63c2-11e6-971a-ec8c4ff31957.png">

**Comment by gnavvy** [comment]
I see, so basically a maximum radius to prevent the points from getting too large.
will add the support together with #54

**Comment by gnavvy** [comment]
we might have to add more thorough solutions to allow radius:
1. with constant screen size;
2. with constant geo-distance;
3. scales with zoom;
4. scales with zoom + with max screen size;

for now, specifying both global radius at layer level and radius at per item level will lead to radius with constant screen size.

**Comment by Vednus** [comment]
Specifying both global radius at layer leve and radius at per item level used to give a radius with a constant screen size, but after I updated to the newest version, this doesn't seem to be working.

**Comment by Vednus** [comment]
I ended up using the cod outlined here to normalize the radius if anyone else is needing this: [http://stackoverflow.com/questions/30703212/how-to-convert-radius-in-metres-to-pixels-in-mapbox-leaflet](url)

**Comment by ibgreen** [comment]
@vednus This should not be needed. 

I think there is a difference between Scatterplot and Scatterplot64. The 32 bit version should behave correctly (i.e the radius should be in item `radius * layerRadius` meters, the latter hasn't been updated completely.

Can you confirm which layer you are using?

We've gotten some feedback that the docs need improving in this regard as well (scatterplot radius handling and interaction between props and accessor etc).

@manassra @shaojingli

**Comment by Vednus** [comment]
I'm using the 32 bit version via `import { ScatterplotLayer } from 'deck.gl'` so I guess it's not behaving correctly...

**Comment by ibgreen** [comment]
Tracked in #264
