### ISSUE TITLE
Trips example - Stroke Width

### ISSUE THREAD

**Issue by stevescc** [uber/deck.gl#566]
I'm working off the Trips example, and in it there is a stroke width however it doesn't appear to make a difference. How might I increase the width of the "trips"?
Thanks (great work by the way)

**Comment by gnavvy** [comment]
It seems the strokeWidth is a legacy prop that is not used inside and should be removed when instantiating the TripsLayer. @Pessimistress Could you confirm please?

To adjust the lineWidth, we might have to change the implementation of the TripsLayer from using gl.LINES to gl.TRIANGLE_STRIP (https://github.com/uber/deck.gl/pull/352) as gl.lineWidth is no longer supported (https://github.com/uber/deck.gl/issues/334).

**Comment by Pessimistress** [comment]
Yes, sadly `gl.lineWidth` has been deprecated by both  [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=60124) and [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=634506).

**Comment by stevescc** [comment]
Ok thanks @gnavvy and @Pessimistress . If there is readme on using gl.TRIANGLE_STRIP instead of gl.LINES I'd be glad to read it.

**Comment by thuanmb** [comment]
@stevescc I got the same issue with you and I'm investigated and implemented a solution to use TRIANGLE_TRIP for trips layer already (PR below). The only issue for now is the animation is not that good than before. But I think it will be a good start for you.
https://github.com/uber/deck.gl/pull/1606
