### ISSUE TITLE
Picking breaks when moving between screens with different devicePixelRatio

### ISSUE THREAD

**Issue by ilyabo** [uber/deck.gl#567]
After moving the browser window with a deck.gl visualization between a retina and a non-retina displays the following happens:

- picking doesn't work properly
- the rendering on retina is very pixelated (non-retina->retina)

Probably this is caused by certain calculations involving devicePixelRatio not being updated. It would be nice if deck.gl could handle this more gracefully. A change in devicePixelRatio could [be detected](http://stackoverflow.com/questions/28905420/window-devicepixelratio-change-listener/29653772#29653772) and the necessary calculations could be updated accordingly.

**Comment by gnavvy** [comment]
@ilyabo Thanks for the pointer to the matchMedia API. will test and fix.

**Comment by ibgreen** [comment]
deck.gl v4.1 should read devicePixelRatio every render, it should be able to adapt without even needing the matchMedia API. @1chandu maybe we can do some tests.

**Comment by ilyabo** [comment]
Indeed, this appears to be fixed in v4.1
