### ISSUE TITLE
Anti-Aliasing Not Working when using multiple monitors on Mac

### ISSUE THREAD

**Issue by mcnuttandrew** [uber/deck.gl#573]
It would be great if we could access fp64 in identity mode. The difference is not that noticable for lines, but scatterplots get pretty rasterized:

![screen shot 2017-04-13 at 10 05 33 am](https://cloud.githubusercontent.com/assets/6854312/25015462/c09a4f62-2030-11e7-9c76-c2ea34524ca8.png)

**Comment by gnavvy** [comment]
seems like an aliasing issue, are you getting this on a non-retina display? 
also could be the number of triangles used to approximate a circle is not large enough.
fp64 mode should not make a difference in this case as we are not zooming w/ a large multiplier.

**Comment by mcnuttandrew** [comment]
i'm see this on both a retina and non-retina display. Is there a recommended way to address this from the pre-packaged layers, or would the solution be to build a custom layer?

**Comment by gnavvy** [comment]
multi-pass rendering (first => texture + anti-aliasing, then => screen) seems like a favorable approach to me, which is also aligned with the roadmap for transform feedback support. 
ref: https://github.com/uber/deck.gl/issues/557

it will change the rendering pipeline though, so might take some efforts if we were to support all the layers. a customized layer as a temporary workaround if you only need it for the scatterplot layer, or just use the icon layer with a set of predefined [markers](http://matplotlib.org/_images/marker_reference_01.png) maybe?

**Comment by Pessimistress** [comment]
There's a known [issue](https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists) where Chrome disables anti-aliasing when multiple monitors are connected.

**Comment by Pessimistress** [comment]
Seems that @mcnuttandrew's issue is indeed caused by the combination of OS X, Chrome and multiple monitors. If this is an important use case to address, you can customize the ScatterplotLayer by manually softening the border in the fragment shader:
```glsl
// original
if (distToCenter <= 1.0) {
  gl_FragColor = vColor;
} else {
  discard;
}

// new
const float SOFT_BORDER = 0.04;
if (distToCenter <= 1.0) {
  float soften = smoothstep(0.0, SOFT_BORDER, 1.0 - distToCenter);
  gl_FragColor = vec4(vColor.rgb, vColor.a * soften);
} else {
  discard;
}
```
