### ISSUE TITLE
How can I react to the user panning the map?

### ISSUE THREAD

**Issue by simonw** [uber/deck.gl#574]
I'd like to detect when the user pans or zooms the hexagon map and load additional data from the server corresponding to the new viewport. Is this possible? Any chance of documentation or an example?

**Comment by ericsoco** [comment]
deck.gl overlays layers onto a [`react-map-gl`](https://github.com/uber/react-map-gl#example) instance (just a wrapper for Mapbox-GL). You can handle events on that instance [as shown in the Layer Browser example](https://github.com/uber/deck.gl/blob/master/examples/layer-browser/src/app.js#L185) that is run via `npm start` from the root, e.g. with an `onChangeViewport` prop.
