### ISSUE TITLE
Changing colors of LineLayer

### ISSUE THREAD

**Issue by anthonyemberley** [uber/deck.gl#575]
Hi, I am trying to change the color of specific segments in a LineLayer component after pressing a button and updating state.  Is it possible to change the color of a LineLayer after the initial render?

Most of my code is from the LineLayer example in the repo, but I have tried the following strategies with no luck:
- Manipulating the FlightPaths data by adding a color field then changing this color field in the state (and therefore the props of DeckGLOverlay)
- Passing in a custom getColor function to the DeckGLOverlay props
- Attempting to pass an extra state variable to the getColor function in deckgl-overlay.js

I've learned that the getColor function isn't called when the DeckGLOverlay component is re-rendered.

Any help would be much appreciated, thank you!

**Comment by anthonyemberley** [comment]
I solved this issue by putting a key in the div which will reset the component when its value is changed. In my case like this:
`
          <div key={selectedRoute}>
            <DeckGLOverlay viewport={viewport}
              strokeWidth={strokeWidth}
              routes={routes}
              hazards={hazards}
              getColor={this.getColor.bind(this)} 
              />
          </div>
`
this way when selectedRoute changes, the component will reset and call getColor again.

**Comment by ericsoco** [comment]
Passing an accessor prop like `getColor` is the right pattern 👍

**Comment by anthonyemberley** [comment]
@ericsoco a little confused by your comment. How would I do that? I tried passing a function in getColor but it wouldn't rerender.

**Comment by ericsoco** [comment]
Sorry, I read too fast.

You'll need to set an `updateTriggers` map on your `LineLayer` that checks a flag that's flipped on button click. E.g.:

```
new LineLayer({
  id: 'flight-paths',
  // ...
  updateTriggers: {
    getColor: () => buttonClicked
  }
})
```

And then reference that `buttonClicked` value in your `getColor` accessor. You'll probably want to pass `buttonClicked` as a prop into the layer containing the `LineLayer` (e.g. in `deckgl-overlay.js`), following the Reactive programming paradigm.

**Comment by ericsoco** [comment]
My esteemed colleague @Pessimistress tells me I got it wrong >.<

I edited the answer above, and added new context -- the main change is that passing a function to `updateTriggers` like I did before is not the expected pattern. Instead, you should pass a single value or map of values.

**Comment by anthonyemberley** [comment]
Thank you for the update, this is very helpful!
