### ISSUE TITLE
Create example using deck.gl with angular2

### ISSUE THREAD

**Issue by dyh333** [uber/deck.gl#576]
the examples seems all using in react. is there any examples using in angular2 or vue? thanks.
like deck.gl very much.

**Comment by ibgreen** [comment]
> is there any examples using in angular2?

@dyh333 There is no such example available but it would be great to have one in the `examples/` folder. 

Would love to see a PR. It should not be hard to put together, and there is actually a little bit of information in the docs: 
* [Using Standalone](http://uber.github.io/deck.gl/#/documentation/advanced-topics/using-standalone)
* [Layer Manager](http://uber.github.io/deck.gl/#/documentation/api-reference/layer-manager)

As an assumption you'd essentially only need to create a DeckGL angular component and provide `setLayers` and a `setViewport` methods or props (not quite sure what the best API in Angular 2 would look like). Basically you would just port the code in [this React integration file](https://github.com/uber/deck.gl/blob/master/src/react/deckgl.js) to Angular 2.

Also found a [Polymer port](https://github.com/PolymerVis/deck-gl), it is based on deck.gl v3 instead of v4 but might still provide some inspiration.

**Comment by dyh333** [comment]
@ibgreen thanks your reply. i wiil try it.

**Comment by donmccurdy** [comment]
Hi! Love the work you all are doing with deck.gl, and really appreciate your intentions of not depending on React or Mapbox GL.

When trying to use DeckGL v4, though, there does seem to be a dependency somewhere. Here's my example config:

```json
{
  "name": "example-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "budo index.js:bundle.js -- -t babelify",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Don McCurdy <email@example.com>",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "^6.23.0",
    "deck.gl": "^4.0.4",
    "luma.gl": "^3.0.1"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babelify": "^7.3.0",
    "browserify": "^14.3.0",
    "budo": "^9.4.7"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}

```

```
// index.js
import DeckGL, {LineLayer} from 'deck.gl';

assert(DeckGL);
```

Result of `npm run dev`: 

> Cannot find module 'react'
google-deckgl-layer/node_modules/deck.gl/dist/react

**Comment by ibgreen** [comment]
@donmccurdy `DeckGL` is the react wrapper for deck.gl. It is a React component that wraps the `LayerManager`. If you want to use deck.gl without react, you'll want to use the `LayerManager` directly.

The react bindings are in [`src/react`](https://github.com/uber/deck.gl/tree/master/src/react)

Also, the `deck.gl` npm module lists `react` as a peer dependency. To get past npm's dependency checking you'd likely need to install it even though you won't be importing it/bundling it.

In the future, we'd like to separate the independent parts of deck.gl from the react bindings. Maybe we'll turn deck.gl into a monorepo and publish `deck.gl` and `deck.gl-react` modules. We could then add a `deck.gl-angular` module etc as well.

**Comment by donmccurdy** [comment]
@ibgreen thanks for clarifying. With this change, the error is the same:

```js
import {LayerManager} from 'deck.gl';
import assert from 'assert';

assert(LayerManager);
```

I'm a bit new to the ES6 module syntax, should that be `from 'deck.gl/LayerManager'` or something, to isolate LayerManager from other parts of the module?

Unfortunately installing react in any manner is not an option for me. Perhaps `react` could be moved to `optionalDependencies`?

**Comment by mpeula-choice** [comment]
Im trying to make an example with angular 2 and google maps ([code](https://github.com/mpeula-choice/riDeck)) and I finally achieve the integration in some point, but I am facing an issue with the hexagon generation (image). do you know why is this happening? I would appreciate some help :).

<img width="403" alt="capture" src="https://user-images.githubusercontent.com/22220156/27786605-1c33ba98-5fe2-11e7-8e7f-adc3354aa1be.PNG">

**Comment by avijitpsingh** [comment]
@mpeula-choice 

Hi,

We recently tried to do similar stuff. Were you able to resolve the above issue?
I don't see you are binding markers on google maps with values. Probably, that's causing this issue?

Thanks,
Avijit

**Comment by ibgreen** [comment]
Sorry for the slow reply, at first blush looks like you haven't enabled depth testing.

**Comment by avijitpsingh** [comment]
Hi @ibgreen,

Are there plans to have standalone examples for deck.gl or angular wrapper over deck.gl?

**Comment by ibgreen** [comment]
> Are there plans to have standalone examples for deck.gl or angular wrapper over deck.gl?

@avijitpsingh We definitely want to make it easier to use deck.gl in non-React contexts. 
* As a first big step, we have already broken out event handling from the react integration into its own `EventManager`, which is a plain JavaScript/ES6 class.
* As a next step (soon), we are planning to replace the internal `WebGLRenderer` React component with the luma.gl `AnimationLoop`, which is a plain JavaScript/ES6 class. 
* When this is done, the `DeckGL` React component will be a really thin and trivial wrapper that delegates all the interesting work to reusable, framework independent JavaScript classes. Those components could then easily be integrated with other frameworks.  

While I don't see the deck.gl core team actually doing an Angular example (we'd probably opt for a framework neutral, pure JS example) we'd be interested in strongly supporting someone who wanted to contribute an Angular example as a PR.

**Comment by rpk** [comment]
Hi @ibgreen , I tried to simplify the example provided by @mpeula-choice to try and help diagnose the issue ([fork here](https://github.com/rpk/riDeck)).

I changed the hexagon layer to a scatterplot layer, configured the same as the scatterplot example provided by deck.gl.

I then added center.json (a single point at 0,0), and added a gmaps marker at 0,0. I set the default viewport to 0,0. Below is an image that shows the offset between the two webgl layers, as you pan and zoom in and zoom out the position of the webgl scatterplot layer seems to change. When the page first loads, the google maps marker appears to be in the center of the screen at 0,0 while the deck.gl scatterplot layer is off screen.
Image showing the results:
![center_test](https://user-images.githubusercontent.com/1000314/30126724-c35babcc-92f1-11e7-99b7-8ce377e4fa5f.png)

Here is the same thing with the manhattan dataset:
![manhattan_test](https://user-images.githubusercontent.com/1000314/30127005-9c9488f0-92f2-11e7-88f5-1add427df13e.png)

I'm happy to try any suggestions you have and report back with results.

**Comment by ibgreen** [comment]
>> Are there plans to have standalone examples for deck.gl or angular wrapper over deck.gl?

> As a next step (soon), we are planning to replace the internal WebGLRenderer React component with the luma.gl AnimationLoop, which is a plain JavaScript/ES6 class.

@avijitpsingh FYI - Just opened the (AnimationLoop PR](https://github.com/uber/deck.gl/pull/915) I promised, this collects the entire React integration into one file, should make it easier to port.

**Comment by ibgreen** [comment]
@rpk This is exciting! I will take a look at the fork as soon as time permits. 

In the mean-time, the visual impression is that there is a scale issue
* the manhattan overlay looks 2x the size of the map of manhattan, but otherwise correctly aligned. * A crazy idea would be to subtract 1 from the deck.gl zoom value (`scale` is 2**`zoom`) just in case google maps and deck.gl are interpreting differently.
* could be related to retina displays? On master we have added a `useDevicePixelRatio` prop to deck.gl to control the use of the retina multiplier.

Also deck.gl `Viewport`s interpret lng/lat as center of screen (not sure what google maps conventions are) and needs correct width height.

**Comment by ibgreen** [comment]
We now have an example that renders deck.gl layers [without React and Mapbox](https://github.com/uber/deck.gl/blob/master/examples/pure-js/without-map/README.md)

**Comment by dazhi1011** [comment]
@ibgreen great job!

**Comment by shaojingli** [comment]
Assignee added retroactively just for reference

**Comment by cracKer92** [comment]
[Pure js example working link](https://github.com/uber/deck.gl/tree/master/examples/get-started/pure-js)

**Comment by beginor** [comment]
I have build a trips-layer demo with angular , source repo is [https://github.com/beginor/ng-deck-gl](https://github.com/beginor/ng-deck-gl), and view it online [https://beginor.github.io/ng-deck-gl](https://beginor.github.io/ng-deck-gl)
