### ISSUE TITLE
arc layer flickers on zoom change

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#58]
when the zoom changes the arc flickers pretty consistently. every other viewport prop doesn't cause this. it seems to be the last segment of the arc that disappears then reappears rapidly.

![](http://g.recordit.co/jyOgYif6k3.gif)

**Comment by contra** [comment]
![](http://g.recordit.co/6QDjTtohJf.gif)

easier to spot with a higher stroke width

**Comment by contra** [comment]
Any implementation tips? I could take a whack at this if I knew where to start!

**Comment by shaojingli** [comment]
Please verify if #140 solved this or not?

**Comment by contra** [comment]
@shaojingli Thanks, I'll test it when the latest hits npm
