### ISSUE TITLE
Picking - mobile tap

### ISSUE THREAD

**Issue by primozs** [uber/deck.gl#580]
Is there any easy way - setting to make picking more successful on tap?
Cheers

**Comment by Pessimistress** [comment]
@primozs Are you referring to being unable to select a precise pixel in touch ux? We don't currently have a setting for this, but there is an open discussion regarding the support of something like `pickingRadius`. @ibgreen

Meanwhile, a work around could be rendering an extra invisible layer with "fat" geometries for picking (e.g. use `[0,0,0,0]` as color and twice the line width).

**Comment by primozs** [comment]
Hi, @Pessimistress 
Yes, its very hard to tap select or touch drag start. I was thinking to make my one picking with geo point (x,y) similar like mapbox tile feature query. In my case viewport feature query.
Thank you for info and direction!

**Comment by shaojingli** [comment]
@primozs does this https://github.com/uber/deck.gl/pull/641 solve your issue

**Comment by primozs** [comment]
@shaojingli Hi, I was checking this yesterday. I saw that there is also feature query option now, but I did not try it in my code. I only tried picking radius in layer browser.  It looks good I guess this can be closed. Thank you for this nice project.
