### ISSUE TITLE
how to change the stroke width of the flow layer?

### ISSUE THREAD

**Issue by lyons66** [uber/deck.gl#593]
Hi, we are working on a project using your tool recently. I tried to increase the stroke width but fails.... : ( Any suggestion?

**Comment by shaojingli** [comment]
@lyons66 by flow layer, are you referring to the TripsLayer? Unfortunately, stroke width is not available for this example layer as it uses GL.LINES to draw the trip trails. Chrome and Firefox both stopped supporting line width for GL.LINES earlier this year. 

The solution is to reimplement the TripLayer using LineLayer or PathLayer.
