### ISSUE TITLE
Icon layer in the layer browser broken on master

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#615]
Uncaught (in promise) Error: Deduced size does not match supplied data element size
    at Texture2D._deduceImageSize (http://localhost:8080/bundle.js:15732:17)
    at Texture2D._deduceParameters (http://localhost:8080/bundle.js:15702:36)
    at Texture2D.initialize (http://localhost:8080/bundle.js:15376:37)
    at new Texture2D (http://localhost:8080/bundle.js:27711:11)
    at http://localhost:8080/bundle.js:208750:14
    at Array.map (native)
    at http://localhost:8080/bundle.js:208747:19
    at <anonymous>

**Comment by shaojingli** [comment]
This is a fallout of https://github.com/uber/luma.gl/pull/136 @ibgreen

**Comment by ibgreen** [comment]
> This is a fallout of uber/luma.gl#136 @ibgreen

Could we temporarily revert to luma.gl v3?

**Comment by shaojingli** [comment]
Should have been solved by uber/luma.gl#160

**Comment by shaojingli** [comment]
So this issue appear again with deck.gl v4.1.0-alpha.7 and luma.gl v4.0.0-alpha.5. The root cause is identified as the default minification filter settings require mipmapping for textures and mipmapping is turned off by default in https://github.com/uber/luma.gl/pull/177/

**Comment by ibgreen** [comment]
I am of the opinion that mipmapping should be on by default in luma. Would be nice go through the situations where it needs to be off (I assume some framebuffer attachment situations?) and see if there are good ways to handle those.

**Comment by shaojingli** [comment]
@ibgreen Let's do that

**Comment by Pessimistress** [comment]
@ibgreen @shaojingli mipmapping was throwing errors for me with luma.gl alpha.3 when I use non-power-of-2 textures.

**Comment by shaojingli** [comment]
@Pessimistress yeah... this is a limit of WebGL 1, non-power-of-2 textures can't have mipmaps

https://www.khronos.org/webgl/wiki/WebGL_and_OpenGL_Differences
