### ISSUE TITLE
traillength issue in trips example

### ISSUE THREAD

**Issue by wzt1001** [uber/deck.gl#616]
I was trying to increase the traillength value in trips example. It was all normal when the value is kept below, say, 2500. Once it exceeds this value some trails are stopped moving forward at some particular moment and reappearing after a few seconds. I am wondering if you have set a maximum for this traillength property which could be causing this problem.
Thanks!

**Comment by shaojingli** [comment]
@Pessimistress .. thoughts?

**Comment by Pessimistress** [comment]
@wzt1001 If you are using the trips app in examples - it loops `time` between `0` and `1800` so that's probably interfering with your `trailLength` of `2500`.
