### ISSUE TITLE
reducing dist size

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#621]
not sure if you're worried about this, but the dist for deck.gl is approaching 2mb

some info:

<img width="810" alt="screen shot 2017-05-01 at 7 09 56 pm" src="https://cloud.githubusercontent.com/assets/425716/25598246/df2d3d0c-2ea1-11e7-9a3e-c308176b1fc4.png">

**Comment by ericsoco** [comment]
Another thing to consider as we grow the layer catalog (and another argument for considering "primitive" layers as a distinction separate from geo/non-geo. The fewer layers we include in the core distribution, the more we can keep the core distro lightweight.

Thanks for the note, @contra.

**Comment by ibgreen** [comment]
@contra  Good feedback - how much of an issue is this for you and other users?

As background, the distro has three complete copies of the tree, the original `src` (which is pure ES6 and can run untranspiled in modern browser and node 7, the `dist-es6` folder for tree-shaking and the vanilla transpiled `dist` folder)

Short term:
* We should probably strip comments from the dist/dist-es6 folders. This looks like a quick fix: https://www.npmjs.com/package/babel-plugin-remove-comments

Longer term:
* We are doing what we can to support tree shaking. When it works the app will only bundle what it needs and the size of the distro is mainly a development concern. Because of this we aren't planning to go to extremes splitting things up in tiny separate npm modules.
* That said, as @shaojing said, we will likely start publishing additional layer packages as separate npm modules in the next release (probably using a monorepo/lerna approach)

PS That looks like a nice analysis tool. Could you provide a link? Maybe we should add a dev script that runs it?

**Comment by contra** [comment]
@ibgreen Debugging our bundle size on a webpack app and found a few offenders - deck.gl + mapbox-gl are ~3MB even after tree shaking in webpack 2.

The tree shaking is actually pretty awful in webpack 2 in my experience with it so far - it doesn't work very well on anything since most people put their compiled code on NPM (which uses module.exports, not usable w/ tree shaking).

Tool is https://github.com/th0r/webpack-bundle-analyzer

I'll try to mess around with aliasing `deck.gl` to `node_modules/deck.gl/dist-es6` and see if that improves the tree shaking - I think the package.json points to `dist/index.js` which uses the non-shakeable common.js exports.

**Comment by ibgreen** [comment]
> deck.gl + mapbox-gl are ~3MB even after tree shaking in webpack 2
Is that for minified code? 

>  tree shaking - it doesn't work very well on anything since most people put their compiled code on NPM (which uses module.exports, not usable w/ tree shaking).

Other modules will hopefully see the light. It is a really good concept. And the alternatives (micro npm modules, importing  js files from subdirectories etc), while often necessary, are miserable.

FWIW the tree shaking bundlers are supposed to check for the package.json `module` entry in preference of `main`.
```
  "main": "dist/index.js",
  "module": "dist-es6/index.js",
```
In fact looking again at your screen shot, it makes it pretty clear that `dist-es6` was indeed picked so at least that is good news. 

We should add the babel comment remover plugin in asap to get the dev dist down, and then do some profiling on minified code.

**Comment by ibgreen** [comment]
Experimenting with remove-comments . At the moment i suspect that a big part of it are the source maps.
Before and after removing comments:
<img width="399" alt="screen shot 2017-05-01 at 7 07 15 pm" src="https://cloud.githubusercontent.com/assets/7025232/25601629/5083c958-2ea2-11e7-86ab-7179bf07beef.png">
<img width="339" alt="screen shot 2017-05-01 at 7 13 30 pm" src="https://cloud.githubusercontent.com/assets/7025232/25601624/4a608200-2ea2-11e7-99f7-0a7da30b2938.png">

**Comment by ibgreen** [comment]
@contra - if you have any insights into the best way of handling source maps during transpile/publishing, feel free to share. 

Right now we are placing an inline source map into each transpiled file. Minification should strip them for production, but it is still a lot of space.

**Comment by contra** [comment]
@ibgreen I usually go with isolated map files and a comment linking them (`source-map` devtool option or `cheap-source-map`

**Comment by ibgreen** [comment]
We currently have different setup, we use babel to generate inline source map for each file as it transpiles it into the dist folder. There is no combined source map for the generated dist tree. Will need to do some research on what the options are.

**Comment by contra** [comment]
@ibgreen AFAIK the `source-map` or `cheap-source-map` values will generate one map per file, side by side (adding `.map` to the end) and include a comment at the bottom of the source file that points the sourcemap to the external file.

This works well since the sourcemaps are only loaded when the user opens devtools, and adds minimal overhead to the dist size (a few characters for the file name per file)

**Comment by contra** [comment]
Including these since you have to include all of them for using deck.gl:

<img width="769" alt="screen shot 2017-05-02 at 11 43 45 am" src="https://cloud.githubusercontent.com/assets/425716/25626183/ad8b88b8-2f2c-11e7-90f2-ba55c7286d8d.png">

<img width="1152" alt="screen shot 2017-05-02 at 11 44 02 am" src="https://cloud.githubusercontent.com/assets/425716/25626173/aade42fe-2f2c-11e7-9337-8295e9d9cf9b.png">

A basic deck.gl map (deck.gl + luma.gl + mapbox-gl + react-map-gl + all of the deps of these projects) is going to be more than 4.1MB of JS

**Comment by shaojingli** [comment]
@ibgreen is this a useful tool for this task? https://medium.com/@Pinterest_Engineering/introducing-bonsai-an-open-source-webpack-analyzer-6bdfe22f8984

**Comment by ibgreen** [comment]
Link to [Reduce Distribution Size RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/v5.0/reduce-distribution-size-rfc.md)
