### ISSUE TITLE
How to run examples with deck.gl locally linked

### ISSUE THREAD

**Issue by nkint** [uber/deck.gl#627]
Hi.
I'd like to run examples with deck.gl library loaded not from `node_modules` but from my local clone. How to do that?
Thanks

**Comment by shaojingli** [comment]
Hi @nkint 

You can go to individual example folders and run `npm run start-local` from there.

**Comment by nkint** [comment]
Ok thanks. But doing that the `3d-heatmap` example does not work: no blue 3d lines inside England.

Here are two screenshot, nothing changed a part from `npm run start` or `npm run start-local`

http://i65.tinypic.com/2qa4faw.png --> npm run start-local

http://i66.tinypic.com/6t22wy.jpg --> nom run start

**Comment by shaojingli** [comment]
@nkint I can repro the issue on my computer. 

Could you try a clean copy of deck.gl and see if it works?

If you, please call up your debug console by pressing option+command+I and paste any output from console here. I can take a look.
