### ISSUE TITLE
scatterplot example currently fails on Linux

### ISSUE THREAD

**Issue by kvey** [uber/deck.gl#63]
![selection_087](https://cloud.githubusercontent.com/assets/515757/18231390/b1b79926-726d-11e6-818e-57079a2b4377.png)

Scatterplot points are appearing like this instead of at their lat/lng locations.
v2.2.1 does not have this issue
v2.2.4 also does not have this issue

Issue is due to
```
gl_FragColor = vColor;
```
v
```
gl_FragColor = vec4(1., 0., 0., 1.);
```

Which I don't understand how that affects position.

**Comment by ibgreen** [comment]
@kvey - Just tried the default example (`npm start`) on latest master (v2.4.6) and scatterplot renders as it should. Need more info to reproduce.

**Comment by kvey** [comment]
Operating System: X11 Linux x86_64
Screen Resolution: 1920 x 1080
Web Browser: Chrome 52.0.2743.116
Browser Size: 1918 x 920
IP Address: 50.232.207.195
Color Depth: 24 bit

![selection_099](https://cloud.githubusercontent.com/assets/515757/18296482/d7a35056-745e-11e6-8e55-9f3a4f275ef6.png)

commit: ea22779

**Comment by ibgreen** [comment]
@kvey - Hmm, that does not look good. Maybe this is a Linux issue? 

We are going to set up a linux environment for testing, but it could take a little time. 

Can you try to zoom out and in a little? The scatterplot has a minimum size I believe, maybe related to that?

**Comment by kvey** [comment]
I was able to get it working with that fragment shader change, though I don't understand why that had any effect.

![selection_101](https://cloud.githubusercontent.com/assets/515757/18296990/654a82c8-7462-11e6-8d34-888a1b6acaad.png)
![selection_100](https://cloud.githubusercontent.com/assets/515757/18296991/654c6340-7462-11e6-8188-4dd9d2a4e1e9.png)

Had a similar issue attempting to texture the points and I think it might have something to do with naming of the varyings? Though I can't confirm that.

Unrelated to this issue but incase you might think it's kind of cool, I was using this messing with rendering pokemon from pokemon-go haha: [gfycat of visualization working](https://gfycat.com/HarmoniousOfficialBaldeagle) though I ended up just building off of v2.2.4 due to this issue.

**Comment by gnavvy** [comment]
Hi @kvey, I just pushed a patch (2.4.7) with a (potential) fix, could you take a look and see if it fix your first issue?

**Comment by kvey** [comment]
@gnavvy patch doesn't seem to correct the issue, previously I attempted fixing this by just skipping that condition - so always projecting - which failed to correct it.

**Comment by ibgreen** [comment]
@vkey if you are still playing with the shader, I think the last line in the vertex shader is of interest

```
  vColor = mix(color, pickingColor, renderPickingBuffer);
```

Your screenshot seems to indicate that vColor for arcs (and perhaps scatterplot) is set to `pickingColor` instead of `color`.

As an example, try to change renderPickingBuffer to 0.0 in both arc and scatterplot and see if that helps. If so we have narrowed down the issue.

**Comment by ibgreen** [comment]
Fixed by luma.gl v2.5.3, which was just published. 

@kvey A fresh npm install should fix the problem for you, it should pull in luma.gl v2.5.3
