### ISSUE TITLE
support for data textures?

### ISSUE THREAD

**Issue by adnan-wahab** [uber/deck.gl#632]
Does deck.gl currently support using textures as a data source for layers? 

For example using the scatter plot layer, instead of loading a json or csv with 5 million rows, you could load an image with 5 million pixels.

It looks like the wind demo is using this with a custom particle layer + transform feedback..

**Comment by ibgreen** [comment]
@adnan-wahab 
> Does deck.gl currently support using textures as a data source for layers?

None of the built in layers support this now, but this is the type of GPGPU programming techniques we are currently exploring for the next iteration of deck.gl and luma.gl.

> For example using the scatter plot layer, instead of loading a json or csv with 5 million rows, you could load an image with 5 million pixels.

Reading data from a texture in WebGL is actually the straightforward part. 

What is not as obvious is how to encode the necessary data in the type of image formats supported by browsers. In the case of a scatterplot layer (and many of the current deck.gl layers) you'd need to encode fairly high precision lng/lat pairs in the image data. (For layers in METER_OFFSET mode, I suppose 16 bit PNG could work, or we could implement our own binary image format loaders).

If you have any good ideas about image encoding of geospatial data, either for the current layers or for new layers with different data inputs, we would love to hear about it.

> It looks like the wind demo is using this with a custom particle layer + transform feedback..

Almost. It does load binary data, and it stores it in floating point textures, but I do not recall it actually loading any data directly from images.

**Comment by shaojingli** [comment]
@adnan-wahab While it might have better performance, using textures as an input for a layer is requires WebGL knowledge in handling various texture format and additional preprocessing in apps that uses deck.gl. As @ibgreen mentioned, if there are widely acceptable standards for encoding geodata in texture / image, we would very much like to add support for it.

**Comment by chrisgervang** [comment]
The wind example has an elevation layer that [loads in a 2D greyscale image](https://github.com/uber/deck.gl/blob/master/examples/wind/src/layers/elevation-layer/elevation-layer.js#L31). It maps greyscale to height, and requires lat/lng for the images corners. I modified the vertex shader a bit to make the interpolation less coarse, and the fragment shader to use color maps.

**Comment by ibgreen** [comment]
@chrisgervang We mainly need to define a "general enough approach" to make this a standard feature in our layers. We are actively working on improved GPGPU support and data textures is one of the topics. Worth syncing up with @1chandu who is currently doing work in this area (more focused on GPU aggregation but it does involves data textures).

**Comment by chrisgervang** [comment]
> "general enough approach"

Makes sense, and I agree.. I wouldn't say the method I proposed is elegant or very general 😝. Each data source and deck.gl layer would need a very custom serializer/deserializer to know how to stitch images together. Another limitation with the bounding box method is I reserve a color value (like `rgb(0,0,0)`) to mean "not used" so that I can define meaningful edges within the bbox, again adding to the complexity of the serializer/deserializer (and lowering resolution 😢).
