### ISSUE TITLE
How to animate ArcLayer arcs individually?

### ISSUE THREAD

**Issue by JunShern** [uber/deck.gl#633]
Hi, I'm working on a project to visualize flight trips on a map, and I would like to animate this such that I can see flight paths appearing and disappearing (similarly to the Trips example, but using ArcsLayer instead of TripsLayer). 

Following the Trips example, I managed to use `_animate()` to get a `time` property into my `render()` function. The `render()` function then creates an ArcLayer of flight trips, selectively displaying the relevant flight trips of a given time by manipulating the source and target color (opacity) based on time. 

This is what I tried: 

```
new ArcLayer({
  id: 'arc-layer',
  data: arcs,
  strokeWidth,
  opacity,
  getSourcePosition: d => d.sourcePosition,
  getTargetPosition: d => d.targetPosition,
  getSourceColor: d => this.timeIsInInterval(time, d.tripStartTime, d.tripEndTime) ? sourceColor : [0,0,0,0],
  getTargetColor: d => this.timeIsInInterval(time, d.tripStartTime d.tripEndTime) ? targetColor : [0,0,0,0]
}),
```

This renders but it doesn't move past what I am guessing is the first frame of the animation - the render doesn't seem to update even though when I print the time variable in the console I can see it updating. 

I have successfully used `time` in other properties of the ArcLayer (for example, setting `strokeWidth: time % 5` does get me a rapidly updating stroke width animation), so I am guessing that this is related to the fact that getSourceColor and getTargetColor take function arguments instead of values, but I do not know how to solve this.

Alternatively, it would be good to just 'turn off' the arc instead of rendering a zero-opacity arc but I have not been able to figure out how to do this either. 

Please help!

**Comment by ibgreen** [comment]
@JunShern 
Since WebGL vertex attributes are expensive to update, they are not updated every frame. Instead, deck.gl uses an [`updateTriggers` mechanism](https://github.com/uber/deck.gl/blob/master/docs/api-reference/base-layer.md#updatetriggers-object-optional) to control when to actually update attributes. 

You'll want to specify that the attributes affected by those accessors need to be updated when `time` changes, something like:
```
updateTriggers: {
   getSourceColor: time,
   getTargetColor: time
}
```
Clearly, this important feature is not nearly as well documented as it should be.

**Comment by junshernchan** [comment]
Hi @ibgreen, thanks that answered my question!

`updateTriggers` worked perfectly, however upon rendering I found that the 0-opacity lines are erasing part of the lines that I do want displayed, resulting in the following partially 'broken' lines:

![image](https://cloud.githubusercontent.com/assets/27656340/25778365/483dc75e-332e-11e7-8100-f5727cfb5103.png)

Is there a property or method for the ArcLayer to completely turn lines off or on, for example setting `visible: false` or `strokeWidth: 0` for individual data points?

**Comment by ibgreen** [comment]
@JunShern 
Even though the arcs are transparent they are still being rendered which affects the Z buffer and hides arcs behind.

You can `discard` the fragment in GLSL fragment shader whenever alpha is zero, something like this should work:

```
const TRANSPARENT_FRAGMENT_SHADER = `\
#define SHADER_NAME arc-layer-fragment-shader
#ifdef GL_ES
precision highp float;
#endif
varying vec4 vColor;
void main(void) {
  gl_FragColor = vColor;
}
`;

class TransparentArcLayer extends ArcLayer {
  getShaders() {
    return Object.assign({}, super.getShaders(), {
       fs: TRANSPARENT_FRAGMENT_SHADER
    });
 }
}
```

**Comment by ibgreen** [comment]
@JunShern
Updated the code to actually include the discard.

**Comment by cc-ch** [comment]
> Hello
> I saw that you solved the problem of the  ArcLayer before, I want to know how you use the updateTriggers to  visualize flight trips on a map
> Please help!

**Comment by hijiangtao** [comment]
@cc-ch Currently, you can visualize it by Brushing arcs and shaders. More details at https://github.com/uber/deck.gl/issues/2531#issuecomment-450475596
