### ISSUE TITLE
Picking always runs

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#634]
deckgl.js [always adds input event handlers](https://github.com/uber/deck.gl/blob/master/src/react/deckgl.js#L129) to its `canvas`, even when no layers have specified mouse event callbacks. This means that picking runs on every mouse event (move and click and drag) right now.

We should only be adding those handlers when the application indicates it wants to respond to input events.

Planning to fix as part of the event handling refactor.
/cc @Pessimistress

**Comment by shaojingli** [comment]
Is this still an issue? @ericsoco @Pessimistress

**Comment by Pessimistress** [comment]
Yes. We do not do any checking before calling `pickLayers`. In a common scenario, if no layers are pickable, when mouse moves, we unnecessarily switch context to the picking frame buffer, renders nothing, then return an empty pixel. Worst case scenario, if all layers are pickable but no `onHover` callback is assigned, we still run the full picking render cycle.

**Comment by ericsoco** [comment]
Yes, the [TODO is now in layer-manager](https://github.com/uber/deck.gl/blob/master/src/lib/layer-manager.js#L159-L162)

**Comment by 1chandu** [comment]
We fixed picking flow, now when no layers are pickable, we don't enter into picking flow.
