### ISSUE TITLE
Scatterplot Layer - circle opacity on overlap?

### ISSUE THREAD

**Issue by skokenes** [uber/deck.gl#635]
I am using a scatterplot layer with black circles that overlap. I've set opacity on them and the layer as a whole does get opaque; however, the circles are not transparent to each other. Ie, the circles blend together in the same shade, rather than showing the overlaps in a darker shade:
![screen shot 2017-05-08 at 3 48 01 pm](https://cloud.githubusercontent.com/assets/5554373/25822176/c4acfbca-3405-11e7-8340-29b794e10236.png)

I defined my individual points in the format:
```
{
  position: [LAT,LONG],
  radius: 3,
  color: [0,0,0,55],
}
```

And the layer in the format
```
var myLayer = new ScatterplotLayer({
  id: "my-layer",
  data: myData,
  radiusScale: 50,
  outline: false,
  opacity: 0.5
});
```

Is there something I am doing wrong here? How do I get the circles to show their overlap?

**Comment by ibgreen** [comment]
> How do I get the circles to show their overlap?

Great question. We should probably add some docs about this. Can provide more information later, but as a first quick answer to hopefully get you going again, WebGL has blend modes that allow you to control this. Poke around the code base to learn more, see how the other deck.gl examples are doing it. If you need more information, let us know!

**Comment by skokenes** [comment]
Ok thanks I will do that. If you can point me to a specific example that does it, that will help me poke around :) Haven't found one yet but I will look harder

**Comment by skokenes** [comment]
Ok, I got it with 
```
gl.enable(gl.BLEND);
gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);
```

But no clue if that's a good blend function to use or not :). If you can provide any resources or suggestions for a scatterplot overlay, that would be great. Thanks for the quick response

**Comment by shaojingli** [comment]
The default blend mode of deck.gl is 
`gl.blendFunc(GL.SRC_ALPHA, GL.ONE_MINUS_SRC_ALPHA)`

This is set during _onRendererInitilialized(). In case you are wondering about WebGL's blend mode and it's effect, please check a wonderful webpage here:

http://delphic.me.uk/webglalpha.html
