### ISSUE TITLE
importing deck.gl?

### ISSUE THREAD

**Issue by skokenes** [uber/deck.gl#637]
Sorry if this is the wrong place to post this - I cannot figure this out for the life of me and am not sure where else to turn.

I am building an Angular 2 app using [angular-seed](https://github.com/mgechev/angular-seed)

I am trying to import LayerManager like so:
`import { LayerManager } from "deck.gl";`
This produces this error: `GET http://localhost:5555/node_modules/deck.gl.js 404 (Not Found)`

So, then I try importing like this:
`import { LayerManager } from "../../../../../../node_modules/deck.gl/dist/index"; `
This gives me a whole bundle off errors like:
```
GET http://localhost:5555/node_modules/deck.gl/dist/shader-utils.js 404 (Not Found)
GET http://localhost:5555/node_modules/deck.gl/dist/lib.js 404 (Not Found)
```

Any thoughts? Point me in the right direction to figure how to get this loaded in? I've had similar issues trying to bundle deck.gl before on my own; only time I've really gotten it to work is just downloading the standalone examples

Thanks for any feedback

**Comment by ibgreen** [comment]
> I am building an Angular 2 app using angular-seed

@skokenes - I suspect an issue with the bundling setup. Your bundler (`rollup` according to angular-seed home page) does not appear to find the deck.gl package.json file - it should be looking for `node_modules/deck.gl/dist-es6/index.js`.

I assume you have installed deck.gl? 
```
yarn add deck.gl
```

Hard to say more unless you can share your code. We have tested deck.gl with browserify and webpack but not with rollup, so perhaps there is some issue we should fix to enable rollup. But your error looks more basic than that.

**Comment by skokenes** [comment]
SystemJS I believe, not rollup. Yes I think its the bundler -> it appears to be resolving directory paths like `require(./shader-utils)` to `shader-utils.js` instead of `shader-utils/index.js`

You guys don't host a deck.gl build anywhere, do you?

**Comment by ibgreen** [comment]
> You guys don't host a deck.gl build anywhere, do you?

Unfortunately not at the moment, we haven't had any requests for this. That said it should not be hard to run a bundler on index.js (perhaps adding a wrapper that copies the deck.gl symbols onto a global object) and generate your own build. There is already a webpack config in the deck.gl root that could serve as a starting point.

> SystemJS I believe, not rollup.

According to the [angular-seed docs](https://github.com/mgechev/angular-seed#tree-shaking-with-rollup) there seems to be some type of rollup integration for production builds, could be worth testing that to see if you get further.

**Comment by skokenes** [comment]
Yup ok thats what I did and got it working, thanks so much

The justification IMO for offering a pre-bundled build for the browser is just to allow people to get up and running quickly for playing around / prototyping. Kind of my use-case here - incorporating deck.gl into a solution for a hackathon and don't have time to figure out how to properly incorporate it with the rest of my team's code

**Comment by ericsoco** [comment]
This is a great use case, thanks @skokenes. Hope deck.gl is working out for you.
@ibgreen let's consider hosting a build on e.g. https://cdnjs.com/.
