### ISSUE TITLE
how to make deck.gl work in responsive canvas?

### ISSUE THREAD

**Issue by skokenes** [uber/deck.gl#638]
I am using deck.gl in Angular 2 so I am not using the DeckGL React component. I've been able to create a statically sized canvas that I can put render a ScatterplotLayer to without any issue. However, I am running into headaches when I try to make the canvas responsively sized. 

Whenever the canvas changes size, the ScatterplotLayer seems to get pretty screwed up. It renders too small and in the seemingly wrong location and its skewed so the circles become ellipses.

I'm assuming that I am not reacting to the resize event properly. I've tried tracing through the DeckGL component but am getting a bit lost. Can anyone lay out the steps that I need to take when a resize event happens? Ie, do I need to update the canvas, then update the viewport, etc?

**Comment by ibgreen** [comment]
> I'm assuming that I am not reacting to the resize event properly.  It renders too small and in the seemingly wrong location and its skewed

You need to call [`gl.viewport`](https://github.com/uber/deck.gl/blob/master/src/react/webgl-renderer.js#L149) when the size of the window changes. I'd look there first.

**Comment by shaojingli** [comment]
@skokenes if check the `webgl-renderer.js`, you'll see that on every frame, deck.gl checks if the viewport size is changed and calls `gl.viewport(x, y, w, h);` to adjust viewport sizes. You need to do the same in your code.

**Comment by skokenes** [comment]
Got it!

Thank you guys for being responsive and patient, even with these questions that are not issues with your code. It's really helped and I'm looking forward to sharing my positive experience with deck.gl with others

**Comment by shaojingli** [comment]
@skokenes  Thank you! 🙌🎆🙋😃🙂🎶👍

**Comment by ibgreen** [comment]
@skokenes That sounds great. 

For what it's worth, we have an open issue on [angular integration](https://github.com/uber/deck.gl/issues/576). If you have a working angular example that you'd like to share, you are welcome to open a PR towards the deck.gl examples folder.

**Comment by skokenes** [comment]
Yes, definitely can put together a simple example of hooking deck.gl into
an Angular 2 component when the dust has settled on my project

**Comment by dyh333** [comment]
@skokenes . hi,  would you share your demo using deck.gl in ng2 ? I am trying the same thing but failed.
thanks

**Comment by ibgreen** [comment]
@dy333 - Not sure if it helps, but just opened a [PR](https://github.com/uber/deck.gl/pull/915) that collects the entire deck.gl / React integration into a single file.
