### ISSUE TITLE
Debugging picking?

### ISSUE THREAD

**Issue by skokenes** [uber/deck.gl#640]
Hi, I am having trouble getting picking to work with a scatterplot layer. I have an animation that updates the data I am rendering frequently. When the data is updated, I am running the following code to update my visualization:

```
// Update layer
    var myLayer = new deckgl.ScatterplotLayer({
      id: "my-layer",
      data: data,
      radiusScale: 6000,
      outline: false,
      opacity: 1,
      updateTriggers: {
        getRadius: t,
        getColor: t
      },
      pickable: true,
      onHover: function(info) { console.log("Hovered:", info); },
      onClick: function(info) { console.log("Clicked:", info); }
    });

    this.layerManager
      .updateLayers({
        newLayers: [myLayer]
      });

    this.layerManager
      .drawLayers({
        pass: Math.random()
      });
```

However, I can't get the onHover nor the onClick functions to fire. Is there something I am doing wrong? If not, how would you suggest I go about debugging this?

**Comment by ibgreen** [comment]
> However, I can't get the onHover nor the onClick functions to fire

[LayerManager.pickLayers](https://github.com/uber/deck.gl/blob/master/src/react/deckgl.js#L149) needs to be called on mouse events. 

Note that you'll need to install your own event handlers (using DOM or Angular) since that is done by the react bindings.

**Comment by skokenes** [comment]
Thanks again
