### ISSUE TITLE
deck.gl可以用openLayers代替mapbox吗？ 

### ISSUE THREAD

**Issue by zhangzn3** [uber/deck.gl#650]
deck.gl可以用openLayers代替mapbox吗？

**Comment by ibgreen** [comment]
> deck.gl可以用openLayers代替mapbox吗？

@zhangzn3  deck.gl does not depend on mapbox so it should be possible. You'll want a react wrapper for openlayers, perhaps you could try something like [react-openlayers](https://www.npmjs.com/package/react-openlayers). 
Then just send the same `lng`,`lat`,`zoom` props to react-openlayers and the deck.gl component.

**Comment by zhangzn3** [comment]
我deck.gl,openLayers设置成一样的lng,lat,zoom ,坐标竟然有偏差。。。

**Comment by zhangzn3** [comment]
貌似只是纬度有偏差。。什么原因？

**Comment by zhangzn3** [comment]
还有个问题,我看render后的DOM结构，mapBox地图在底层，deck.gl层覆盖在mapbox层上面，为什么onChangeViewport事件写在mapbox里而不是deck.gl层里？ 怎么触发changeViewport的呢

**Comment by decula** [comment]
Is there any example code to use react-openlayers in deck.lg?
