### ISSUE TITLE
SyntaxError: missing = in const declaration

### ISSUE THREAD

**Issue by lightnight11** [uber/deck.gl#651]
Hi,

after I have npm install and npm start, the arc example doesn't show up on my firefox 47.0 browser. I check the console and found this error - SyntaxError: missing = in const declaration.

The error points to the line " for (const k in obj) {" in the code below.
/*
 * Polyfill for Object.values. Not fully spec compliant, but we don't
 * need it to be.
 *
 * @private
 */
exports.values = function (obj        )                {
    const result = [];
    for (const k in obj) {
        result.push(obj[k]);
    }
    return result;
};

anyone can advise how I can resolve this issue? Thanks in advance.

**Comment by ibgreen** [comment]
> the arc example doesn't show up on my firefox 47.0 browser

@lightnight11  While we investigate this, I am pretty sure that upgrading to latest Firefox (53) will solve this issue (since it supports ES6 source code out of the box).

**Comment by lightnight11** [comment]
yes. It solves my problem. Thank you so much.
