### ISSUE TITLE
Picking is broken

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#653]
The picking buffer always stays empty after the layers draw into it.

This may be a luma error -- `width` and `height` were at first not getting set correctly. Then, I `yarn upgrade`d to bump luma and I see now that `width` and `height` are set as expected, but the buffer still remains empty.

**Comment by shaojingli** [comment]
It's broken by https://github.com/uber/luma.gl/pull/172 @ibgreen

**Comment by ericsoco** [comment]
@shaojingli this appears to be fixed? I'm on `luma.gl@4.0.0-alpha.4`.

**Comment by ericsoco** [comment]
@shaojingli bump

**Comment by shaojingli** [comment]
This has been fixed by https://github.com/uber/luma.gl/pull/183
