### ISSUE TITLE
How to position points in scatterplot?

### ISSUE THREAD

**Issue by skokenes** [uber/deck.gl#655]
Sorry for another how to question...

I'm trying to create a basic, non-geo example of a scatterplot using deck.gl, similar to examples like these that I've seen for regl lately [http://bl.ocks.org/rflow/39692bd181fb1eb0b077a4caf886b077](http://bl.ocks.org/rflow/39692bd181fb1eb0b077a4caf886b077)

I am struggling to plot some basic points onto a scatterplot layer. I have a canvas that is about 1900 x 700 px. I set the viewport like:

```
viewport = new Viewport({
    width: 1900,
    height: 700
})
```
For test purposes, I created a single point that has a property `position: [0,0]`. When I try to render this point, it does not appear on the canvas. When I check `viewport.project([0,0])`, it returns [950, 350], which indicates to me that the point should render in the middle of the canvas. However, it doesn't. I can get the point to show if I make the radius huge such that it covers the entire canvas; its clear from doing that that it is positioned somewhere off screen.

What am I doing wrong? How do you handle translating position onto the viewport?

**Comment by contra** [comment]
@skokenes Did you give it a radius or a color or anything else other than just the location?

**Comment by skokenes** [comment]
Of course. As stated, if I jack the radius up to extreme sized I can see
the point swallow up the canvas. It is clearly not centered anywhere within
the canvas.

I can try to copy/paste my entire code snippet when I am back at a computer

**Comment by ibgreen** [comment]
@skokenes - Non-geospatial viewports is a somewhat new feature in deck.gl v4, we don't have a lot of good minimal standalone examples.

The [plot example](https://github.com/uber/deck.gl/blob/master/examples/plot/app.js#L17)  is probably the best current starting point. It also has the `OrbitControls` that would allow you to pan around and interact with your points.

If the plot example is too much to digest at once we can try to answer more specific questions, let us know.

**Comment by skokenes** [comment]
Ok thanks I will take a look at that example. Here is what I have currently:
```
// Generate some random data
var totalPts = 1;

var data = Array.apply(null, Array(totalPts)).map(function(v,i) {
    return {
        radius: 25,
        color: [255,0,0,255],
        position: [0,0], //[0,0] //[-90,80] //[0,0]
    }
 });

// Initialize canvas and get pixel ratio (for retina screens)
var canvas = document.querySelector("#deck-canvas");
var pixelRatio =  (typeof window !== 'undefined' && window.devicePixelRatio) || 1;

// Set canvas size according
var gl = canvas.getContext("webgl");

// Enable blending for opacity
gl.enable(gl.BLEND);
gl.blendFuncSeparate(gl.SRC_ALPHA, gl.ONE, gl.ONE_MINUS_DST_ALPHA, gl.ONE);
gl.blendEquation(gl.FUNC_ADD);

var layerManager = new deckgl.LayerManager({gl});

updateViewport();
updateLayer();

// Update the viewport
function updateViewport() {
    var container = document.querySelector("#container");
    var dimensions = container.getBoundingClientRect();

    var width = dimensions.width;
    var height = dimensions.height;

    canvas.setAttribute("width", width * pixelRatio);
    canvas.setAttribute("height", height * pixelRatio);

    canvas.style.width = width + "px";
    canvas.style.height = height + "px";

    gl.viewport(0, 0, width * pixelRatio, height * pixelRatio);

    window.viewport = new deckgl.Viewport({
        width: width,
        height: height
    });
    
    /* new deckgl.OrthographicViewport({
        width: width,
        height: height,
        left: 0,
        top: 0
    });
    */

    layerManager.setViewport(viewport);
}

// Update the layer
function updateLayer() {
    var myLayer = new deckgl.ScatterplotLayer({
        id: "my-layer",
        data: data,
        radiusScale: 1,
        //radiusMinPixels: 20,
        //radiusMaxPixels: 50,
        outline: false,
        opacity: 1
    });

    layerManager.updateLayers({
        newLayers: [myLayer]
    });

    layerManager.drawLayers({
        pass: Math.random()
    });
}```

I seemed to get _closer_ by using an OrthographicViewport like so:

```
viewport = new deckgl.OrthographicViewport({
        width: width,
        height: height,
        left: 0,
        top: 0
    });
 ```
With this viewport, `viewport.project([0,0])` gives me [0,0], which is what I would expect, but the circle actually draws to the right of the left border and halfway down the canvas:
<img width="1425" alt="screen shot 2017-05-22 at 6 20 50 pm" src="https://cloud.githubusercontent.com/assets/5554373/26330788/9f0ec774-3f1b-11e7-9eb1-01c066cbff4b.png">
