### ISSUE TITLE
Demo website broken on Safari

### ISSUE THREAD

**Issue by antiquechrono** [uber/deck.gl#691]
Whenever I try to look through the demo gallery at http://uber.github.io/deck.gl/#/examples/overview the map will load but none of the visualizations ever load. I am running OSX.

I get the following errors for example on the IconLayer example.

meteorites-decoder.js:2 SyntaxError: Unexpected identifier 'coordinates'

<img width="790" alt="screen shot 2017-06-06 at 4 56 10 pm" src="https://user-images.githubusercontent.com/572187/26853815-26e73e24-4ad9-11e7-81f6-e621dfe7896f.png">

**Comment by ibgreen** [comment]
@antiquechrono Just tested on Safari 10.1.1 and things seem to work. What version are you using?

**Comment by antiquechrono** [comment]
Version 9.1.2 (11601.7.7)

**Comment by antiquechrono** [comment]
It looks like the let syntax isn't supported in this browser version. According to https://caniuse.com/#search=let the first supported version was 10

**Comment by ibgreen** [comment]
We do transpile our code in order to support old browsers, but it looks like something is slipping through, we also got a similar report on an old Firefox version. 

It would be good to find out where it is / what is causing it. Don't really have old browser versions handy for test though. 

Just in case you have been poking around in the stack trace etc and if you saw anything more, e.g. what module it might be that is causing this etc, please share any additional info you have.

**Comment by antiquechrono** [comment]
That's the weird thing, there's nothing in the log other than that. Basically when you are browsing the gallery I will click on one of the examples and it loads but the *-decoder.js file errors out with the first let statement in that file. So for example here's what the errors look like when I try to load different gallery examples.

[Log] luma.gl 3.0.2 - Assign luma.log.priority in console to control logging: 0: none, 1: minimal, 2: verbose, 3: attribute/uniforms, 4: gl logs (bundle.js, line 32)
luma.log.break[], set to gl funcs, luma.log.profile[] set to model names
[Log] deck.gl 4.0.6 - set deck.log.priority=2 to trace attribute updates (bundle.js, line 32)
[Error] SyntaxError: Unexpected identifier 'sequence' (scatterplot-data-decoder.js, line 4)
[Error] SyntaxError: Unexpected identifier 'result' (flight-path-data-decoder.js, line 3)
[Error] SyntaxError: Unexpected identifier 'total' (heatmap-data-decoder.js, line 2)
[Error] SyntaxError: Unexpected identifier 'coordinates' (meteorites-decoder.js, line 2)

**Comment by shaojingli** [comment]
@ibgreen @Pessimistress AFAIK, the worker files are not transpiled, right?

**Comment by Pessimistress** [comment]
We do not transpile the workers. I believe most of our workers are written in es5. I can fix this.

**Comment by Pessimistress** [comment]
Just checked and all workers were rewritten in es6 as of [319](https://github.com/uber/deck.gl/pull/319). I remember @ibgreen making a point of only supporting evergreen browsers. We may want to transpile them since it still seems to be a problem?

**Comment by ibgreen** [comment]
> I remember @ibgreen making a point of only supporting evergreen browsers.

In general yes, though there have been requests to cover IE11 as well (for a while at least), if the cost is not high.

And of course, as long as we are transpiling the rest of the code, it makes sense to transpile the workers too.
