### ISSUE TITLE
how to use it without react?

### ISSUE THREAD

**Issue by liujiusheng** [uber/deck.gl#694]
I saw your demo all build up react,but how can i use it without react?

**Comment by miketheredherring** [comment]
There is a brief overview here: https://uber.github.io/deck.gl/#/documentation/advanced-topics/using-standalone. However, there is a lot of event handling which you must do manually, so you have to pave your own path!

**Comment by ibgreen** [comment]
@liujiusheng The entire react integration is located in the [src/react](https://github.com/uber/deck.gl/tree/master/src/react) folder. 

You'd need to replicate that code, without react.  As @miketheredherring says you need to create a gl context, an event loop and bind some events, and call the `LayerManager` as needed. `LayerManager` really does all the work, you just need to wire it up.

There are a couple of closed issues related to getting deck.gl to work in Angular, e.g #638, it could be worth poking around a little there to see what was said.

**Comment by shaojingli** [comment]
@liujiusheng as @ibgreen mentioned, using deck.gl without react requires you to connect correct wires to `LayerManager` and handles events properly. If you could build up a simple example without React, you are very welcome to write up a PR.

**Comment by ericsoco** [comment]
Note also that we plan to move some of the event handling over to LayerManager to support exactly this use case. That should land in the weeks-future (not days, not months)....

**Comment by liujiusheng** [comment]
@ @shaojingli thanks.it will render only after i have used map.drawLayers()?And what is the params means.
