### ISSUE TITLE
Unable to run example, npm install failed. 

### ISSUE THREAD

**Issue by liuhy0302** [uber/deck.gl#699]
Hi, this is my first time using deck.gl, and I failed to run "npm install" in the examples/arc directory. I'm also attaching the debug.log file.
Any help would be highly appreciated!

[2017-06-09T02_14_09_331Z-debug.log.txt](https://github.com/uber/deck.gl/files/1062957/2017-06-09T02_14_09_331Z-debug.log.txt)

➜ arc git:(master) ✗ npm install
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install instead
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install instead
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install instead
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR! fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/hongyi/.npm/_logs/2017-06-09T02_14_09_331Z-debug.log

**Comment by ibgreen** [comment]
@liuhy0302 Just did an npm install in arc folder and it worked. Check that you are using recent versions of node and npm (`nvm` is your friend). We have all moved to yarn, also worth a try.

**Comment by moneytrey29** [comment]
I can access uber

**Comment by liuhy0302** [comment]
Thank you @ibgreen for the help! I fixed this error by updating to the latest version, and using "yarn" instead of "npm install" on my Mac.
