### ISSUE TITLE
Pan and set view in trips example

### ISSUE THREAD

**Issue by iskandari** [uber/deck.gl#718]
In `examples/trips/trips-layer/deckgl-overlay.js ` the map's starting position is set with a static method:

```
  static get defaultViewport() {
    return {
      longitude: -74,
      latitude: 40.72,
      zoom: 13,
      maxZoom: 16,
      pitch: 45,
    };
  }
```
I would like to slowly fly to a specific location using the trips example with `map.flyTo()` - which is demonstrated [here](https://www.mapbox.com/mapbox-gl-js/example/flyto-options/).  How could I integrate a flyTo function in the defaultViewport?

**Comment by shaojingli** [comment]
@iskandari DeckGL works like _a react component that doesn't contain internal state_. So it doesn't handle interpolation of viewports and animation automatically. Therefore, the application needs to do it themselves. 

DeckGL's demo site actually uses tween.js to interpolate viewports between examples. You can refer to `demo/src/utils/map-utils.js`
