### ISSUE TITLE
`npm start` can fail when deps change in examples/layer-browser

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#737]
The [script to install deps for `layer-browser` on `npm start`](https://github.com/uber/deck.gl/blob/master/package.json#L24) works fine when first running it, but when `examples/layer-browser/package.json` changes, the script will see that `examples/layer-browser/node_modules` already exists and will not update packages. This can cause `npm start` to fail when deps are added / bumped.

We might consider running `yarn upgrade` instead of `npm i`, if we're open to promoting `yarn` to a devDep of deck.gl. I hesitate to add an `npm i` to every `npm start` call, regardless of the existence of `examples/layer-browser/node_modules`, because it will slow down the example build significantly.

**Comment by jianhuang01** [comment]
This issue is hanging here for a long time, usually we manually do "yarn" or "npm install" when pulled new code or changed package.json.
