### ISSUE TITLE
我把mapbox替换成百度地图，为什么经纬度对不上？

### ISSUE THREAD

**Issue by zhangzn3** [uber/deck.gl#745]
RT，同样的经纬度，显示位置有偏差，为什么？

**Comment by gnavvy** [comment]
请问显示位置的偏差是只出现在经度方向？纬度方向？还是完全偏离？可否提供一下截图？
另外，mapbox的地图（俯视状态下）需要提供地图中心点的经纬度和zoom level，不确定百度地图和mapbox指定地图显示区域的API是否类似。

**Comment by esrever001** [comment]
Long story short, it is because different latlng system.
Almost all latlng outside of China is using WGS84 coords system, but in China due to regulations, they are all applied with non-linear transformation into GCJ02 system, and on top of that, baidu has its own BD09 system.

related: http://www.jianshu.com/p/0fe30fcd4ae7

**Comment by gnavvy** [comment]
@esrever001 Thanks for the insight. I just check the Baidu map API, http://developer.baidu.com/map/reference/, and it uses a similar API (centerAndZoom) to Mapbox. So I guess it is due to the coords system, will add BD09 & GCJ02 support into roadmap discussion.

**Comment by zhangzn3** [comment]
@gnavvy  百度地图的缩放级别和deckgl的缩放级别不能对应，我只是手动调试成相近大小。。

**Comment by zhangzn3** [comment]
@esrever001 我也看到类似的文章说不仅仅坐标体系不一样，哪怕同样是墨卡托投影，投影参数不一样，位置也会有区别，那这样的话，国内哪个地图跟mapbox是一样的，可以代替mapbox的？

**Comment by fuzhenn** [comment]
@zhangzn3 高德地图, 腾讯地图, 天地图墨卡托版都是用的墨卡托投影 (EPSG:3857), 应该都能用在deck.gl上

**Comment by zhangzn3** [comment]
@fuzhenn  多谢，我试试高德看看

**Comment by zhangzn3** [comment]
@gnavvy  deckgl的zoom怎么设置成跟其他的地图zoom一样？ 怎么换算的？

**Comment by fuzhenn** [comment]
我之前测试时, mapbox-gl(deckgl)的zoom比一般的3857 zoom要小1级
比如15级时, mapbox-gl是14级

**Comment by zhangzn3** [comment]
@fuzhenn 多谢  [高德地图个mapbox对比截图](http://files.cnblogs.com/files/leyi/gaode-mapbox.gif)
同样的经纬度，我把高德的zoom缩小一级，显示还是稍微有点差距，可以接受，可能zoom还需要调吧

**Comment by fuzhenn** [comment]
这是因为高德地图的坐标系和mapbox不同, 高德用的是gcj02(火星坐标), mapbox是真实经纬度.
总结一下:
* mapbox和高德地图的投影坐标系一样, 都是用的EPSG:3857, 单mapbox级别比高德高一级
* mapbox和高德的坐标系不一样, mapbox用的是wgs84(真实经纬度), 高德用的是gcj02(国测局02即火星坐标)

可以试试把有偏差的坐标做一下转化(从真实经纬度转成火星坐标),应该就能准确叠加了. 转化算法可以搜github.

顺便提一下, 天地图用的是cgcs2000坐标, 和真实经纬度基本没有偏差, 和mapbox应该能准确叠加 (天朝的地图服务搞的真复杂.. 😿 )

**Comment by shaojingli** [comment]
多谢 @esrever001 @fuzhenn  
@zhangzn3 WGS84转GCJ02参考前面那个简书的链接

**Comment by ibgreen** [comment]
About support for non-Web Mercator projections:
* Currently deck.gl does web mercator projection directly in the shader.
* Most non-spherical Mercator projections are too complicated to do in the shader, at least on every frame.
* deck.gl could easily offer a new projection mode (`projectionMode: COORDINATE_SYSTEM.MERCATOR_WORLD`) where layers would accept pre-projected web-mercator world coordinates (tile 0 coordinates) as positions.
* With that mode, you could use a javascript projection module to convert coordinates (there are many on npm, [this one](https://www.npmjs.com/package/sphericalmercator]) looks like it might do it, but there are others.

**Comment by shaojingli** [comment]
@zhangzn3 当deckgl和basemap一起使用的时候，我们通过react-map-gl的MapGL component控制地图的viewport和触发onChangeViewport
