### ISSUE TITLE
Picking broken on devicePixelRatio change

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#747]
Repro steps:
- In the layer-browser example, use cmd + to increase `window.devicePixelRatio`
- Move mouse. `pickLayers` throws error for negative typed array length.

Cause:
We handle `devicePixelRatio` differently in rendering and picking.
- `WebGLRenderer` uses fixed pixel ratio that is determined when the app loads.
- The picking frame buffer is set to the same size as the WebGL canvas.
- `pickLayers` retrieves pixel ratio every time an event fires to adjust the mouse position, then clips the picking rectangle with the frame buffer size. The current clipping implementation results in negative size when the adjusted mouse position is outside the canvas.

Proposed fixes:
- There should be a single source of truth for pixel ratio, probably managed by `DeckGL` and passed down to both `WebGLRenderer` and `LayerManager`
- `pickLayers` should abort if picking rectangle size is invalid

@ibgreen @shaojingli

**Comment by ibgreen** [comment]
> In the layer-browser example, use cmd + to increase window.devicePixelRatio

Interesting, i didn't realize that zooming in the browser is visible to the app, I thought that was just a pixel magnification that the browser did without the app's knowledge.

For sure we should align `devicePixelRatio`. We may even want to do it on the luma.gl level, there is a corresponding picking module and canvas and framebuffer resize support there. 

Another question is whether to resize the framebuffers to match `devicePixelRatio` (this applies both to the default drawing buffer maintained by the canvas and for the picking buffer that we  create programmatically). luma.gl does resize these, but at the top of my head I am not sure about deck.gl.

**Comment by Pessimistress** [comment]
deck.gl just use whatever the canvas size is:
```
    this.context.pickingFBO.resize({
      width: gl.canvas.width,
      height: gl.canvas.height
    });
```
Which is set by `WebGLRenderer`:
```
    createElement('canvas', {
      width: width * pixelRatio,
      height: height * pixelRatio,
      ...
    });
```
