### ISSUE TITLE
point cloud examples are not able to renders files with larger size(>100MB)

### ISSUE THREAD

**Issue by jtewari08** [uber/deck.gl#748]
Hi, 

I am trying to render the las/ply files in point cloud examples , and the app is crashing when the file size is more that 100MB approx, is this a known issue? Also what are the possible solutions to outcome this. The files I need to render are up to 1GB.

Thanks

**Comment by ibgreen** [comment]
> and the app is crashing when the file size is more that 100MB approx,

We'll need to figure out what is causing the browser to crash. Chrome has a 1GB limit for arrays which puts a hard limit on the number of elements in a layer (somewhere between 10 and 100 million items). 

If that is the case it is possible that splitting into multiple point cloud layers would help. But I am not convinced you are hitting this limit at just 100MB input data, so the issue might depend on the las loader. 

Is your file accessible for us to test so we can see where it fails?

**Comment by gnavvy** [comment]
Also, depending on the format of your point cloud file, if it is text / ASCII formatted, 100MB should not be a problem regarding memory usage; if it is binary, the uncompressed result could exceed the 1GB limit.

**Comment by jtewari08** [comment]
Thanks for the quick reply. I cannot share the file as it is a corporate data , but type is binary , file size 900 MB and 25,000,000 points approx.So are you saying that this a restriction for deck.GL for all layers?

**Comment by Pessimistress** [comment]
@jtewari08 The memory restriction is imposed by Chrome. There are two things you can try:

- Sample/filter your data when loading, since you likely don't have to render all 25M points at the same time.
- Instead of constructing a JavaScript array, create typed arrays and pass them directly as attributes:
```
const instancePositions = new Float32Array(count * 3);
const instanceNormals = new Float32Array(count * 3);
const instanceColors = new Uint8ClampedArray(count * 4);

// Fill the arrays with your data

new PointCloudLayer({
      projectionMode: COORDINATE_SYSTEM.IDENTITY,
      radiusPixels: 2,
      instancePositions,
      instanceNormals,
      instanceColors
})
```
Typed arrays do not count towards the memory limit of each webpage.
@gnavvy It might be nice to show this technique in one of your point cloud examples?

**Comment by shaojingli** [comment]
@jtewari08 Is @Pessimistress's suggestion working for the issue you are facing?
