### ISSUE TITLE
Incomplete geojson layer with large source data

### ISSUE THREAD

**Issue by stevelacy** [uber/deck.gl#749]
We have a dataset of 1000+ polygons rendered through a `GeoJsonLayer` which only seems to render part of the total number of features.

Code:
```js
    new GeoJsonLayer({
        id: 'plots',
        pickable: true,
        drawCountour: false,
        data: polygons,
        onHover: onHoverBound,
        onClick: onClickBound,
        stroked: false,
        fp64: true
      })
```

This is the rendered output:
![selection_2017062917 22 4701](https://user-images.githubusercontent.com/5648999/27716032-41df93c4-5cf0-11e7-9a19-670864aa9324.png)

And the length of features:
![selection_2017062917 26 1101](https://user-images.githubusercontent.com/5648999/27716038-46968486-5cf0-11e7-8b58-c2b921f68137.png)

I've confirmed the data does render correctly when passed into an ArcGIS layer map:
![selection_2017062917 28 4501](https://user-images.githubusercontent.com/5648999/27716066-79443054-5cf0-11e7-9e12-f79fc2b048a8.png)

Any ideas? I looked through all the settings and didn't see any for max or limit.
Cheers

**Comment by ibgreen** [comment]
> Any ideas? I looked through all the settings and didn't see any for max or limit.

There should not be any limits, 1000 items is a very low number for deck.gl

As a first suggestion, the rendering is dependent on the layer's accessors picking up the right data from the GeoJson feature `properties`. 
E.g. 
```
getFillColor (Function, optional)
Default: f => f.properties.fillColor || [0, 0, 0, 255]
```
You can supply your own accessors to match the format your GeoJson should it not have a `properties.fillColor` on each feature (although you seem to be getting a blue color for some of your data).

Also - While I don't think it is the problem, I noticed that you are using the `drawContour` prop - that was used by the now deprecated `ChoroplethLayer`s, the `GeoJsonLayer` has different [props](https://uber.github.io/deck.gl/#/documentation/layer-catalog/geojson-layer?section=render-options).

**Comment by stevelacy** [comment]
I duplicated the [demo](https://uber.github.io/deck.gl/#/documentation/layer-catalog/geojson-layer) and used the example data with the same layer setup
```js
  const layer = new GeoJsonLayer({
    id: 'geojson-layer',
    data,
    filled: true,
    stroked: false,
    extruded: true
  })
```
This time it does not render anything.
![selection_2017063013 12 0201](https://user-images.githubusercontent.com/5648999/27752465-f90eb444-5d95-11e7-8f09-4649f05d68f4.png)

deck.gl 4.0.5, luma.gl 3.0.0

**Comment by Pessimistress** [comment]
@stevelacy judging from the screenshot, you need to specify the `getRadius` accessor because the default is 1 meter, which is not visible from this zoom level.

**Comment by stevelacy** [comment]
Which version of deck.gl has that option? I tried it on 4.0.5 without success

**Comment by Pessimistress** [comment]
@stevelacy Can you share your code? This [documentation](https://uber.github.io/deck.gl/#/documentation/layer-catalog/geojson-layer?section=render-options) page shows all the props available.

**Comment by contra** [comment]
@Pessimistress What would `getRadius` do for display of filled polygons?

**Comment by Pessimistress** [comment]
@contra `getRadius` doesn't apply to polygons. I was commenting on the latest screenshot which shows point features.

**Comment by contra** [comment]
@Pessimistress ah my bad - any idea about the polygons?

**Comment by Pessimistress** [comment]
@contra The initial code snippet shared in this thread was using deck.gl v3 api and would not work with v4. Without knowing what else has been tried it's hard for me to tell what went wrong. Also have you confirmed that the data is standard GeoJSON?

**Comment by stevelacy** [comment]
Yeah, the data is standard geojson, all features have the same format, the ones shown and the ones that are not rendered.
I'll confirm all code is using v4

**Comment by shaojingli** [comment]
@stevelacy Hi Steve, it's really hard for us to help you without plugging in your data and poke around it. Is it possible that you provide some of your data that is not rendering properly, so that we could try ourselves?

**Comment by contra** [comment]
@shaojingli 

As JSON: https://municipal.systems/v1/municipalities/jers-nj/zones

As GeoJSON: https://municipal.systems/v1/municipalities/jers-nj/zones/export?format=geojson

**Comment by Pessimistress** [comment]
@contra the polygons you are hoping to render are stored in `properties.area`, while GeoJSON standard stores geometries in `geometry`. The GeoJsonLayer only reads `geometry`, which returns a point for each feature.
To see the points: add `getRadius: () => 100` to your GeoJsonLayer props.
To see the polygons, you have two options:
- Format your source data and replace `geometry` with `properties.area` for each feature.
- Use `PolygonLayer` and use `getPolygon: f => f.properties.area.coordinates[0]` as a prop.

**Comment by contra** [comment]
@Pessimistress Sorry, not the right data URL - https://staging.municipal.systems/v1/municipalities/jers-nj/schemata/parcel/export?format=geojson&download=true

**Comment by Pessimistress** [comment]
@contra In the GeoJsonLayer example, use these props:
```
    const layer = new GeoJsonLayer({
      id: 'geojson',
      data,
      opacity: 0.8,
      stroked: true,
      filled: true,
      extruded: false,
      wireframe: false,
      fp64: true,
      getFillColor: f => [200, 0, 128],
      getLineColor: f => [255, 255, 255]
    });
```
![image](https://user-images.githubusercontent.com/2059298/28146463-e992c9ae-672e-11e7-80ec-0e454fc36bd1.png)

**Comment by Pessimistress** [comment]
It might have been confusing for you because the lots share borders, they all blend together and look like one.

**Comment by contra** [comment]
Given the original case the entire city should be completely filled in. If there are any holes then you are reproducing the bug. You should see 28,000 polygons.

**Comment by Pessimistress** [comment]
@contra The sample data you shared with me contains 3,253 MultiPolygons with a mean of 5.3 vertices. I assume it's just a subset.

**Comment by stevelacy** [comment]
I updated our code to match yours as well as updating to 4.0.6, I will verify but it seems that it is working.

Thanks for the help!
