### ISSUE TITLE
Passing MapboxGL access_token via queryParam

### ISSUE THREAD

**Issue by urosi2453** [uber/deck.gl#75]
It would be nice if we can pass Mapbox access_token via queryParam while running deck.gl examples.

react-map-gl has options to pass access_token via queryParam.

**Comment by ibgreen** [comment]
@Pessimistress Can we use same token for demo and example and remove the need to pass in token?

**Comment by ibgreen** [comment]
The react-map-gl dev branch has built in support for URL token parsing. This will eventually be available in deck.gl
