### ISSUE TITLE
Add `useDevicePixelRatio` as prop to `DeckGL` component.

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#760]
In current implementation, we always use `window.devicePixelRation` when setting up canvas.width/height and also in all modules that handle events (mouse position etc).
We should be able to pass `useDevicePixelRatio` to `DeckGL` component and use it as single point of truth to whether use window.devicePixelRation or not. (Pass this boolean to all modules that use window.devicePixelRatio, like `draw-and-pickup`, `viewport-uniforms` etc).

**Comment by shaojingli** [comment]
Is this resolved? @1chandu

**Comment by 1chandu** [comment]
Closing as the remaining issue of having prop to control is tracked by #843.
