### ISSUE TITLE
Zoom out moves all icons from their positions in iconlayers. But It seems a general zoom problem.

### ISSUE THREAD

**Issue by cuevash** [uber/deck.gl#771]
Trying with the example :  deck.gl/examples/icon.

When doing a full zoom out the map starts moving.. first upwards and then rightwards. That causes the iconlayers to move accordingly first downwards and then leftwards.

Seems to start from zoom 0.9xx and downwards till 0.

**Comment by Pessimistress** [comment]
@shaojingli @ibgreen This is a known problem at low zoom level. In non-perspective mode, Mapbox shifts the viewport to avoid white gaps at the edge. We should update `WebMercatorViewport` to match this behavior.

**Comment by shaojingli** [comment]
Yes. I also know this issue before. But thanks @cuevash for pointing it out.

**Comment by Pessimistress** [comment]
@cuevash If you upgrade to react-map-gl@3.0.0-beta.3 this issue should be fixed.
