### ISSUE TITLE
Cannot update isPickable after layer being initialized

### ISSUE THREAD

**Issue by gnavvy** [uber/deck.gl#79]
The isPickable prop is only being set to the model once when initializing the layer.
https://github.com/uber/deck.gl/blob/master/src/layers/base-layer.js#L466
Users cannot control whether a layer should respond to hover/click events afterward.

One workaround is to set isPickable = true when initializing the layers and to handle the picking logic (e.g. ignore) in the callback functions.

**Comment by ibgreen** [comment]
This should be completely fixed by #123
