### ISSUE TITLE
grid-aggregator fails on large number of coordinate points. 

### ISSUE THREAD

**Issue by shawel** [uber/deck.gl#793]
grid-aggregator.js fails on large number of points when trying to find max & min lat longs because of 
 the following two lines
```
const latMin = Math.min.apply(null, allLat);
const latMax = Math.max.apply(null, allLat);
```
Number of arguments on apply is not consistently implemented across browsers and it fails on some arbitrary limit. It is best to switch to something like  `max =Math.max(max, latlng) `  & it would help with performance to calculate both at once.

**Comment by gnavvy** [comment]
Hi @shawel,

> Number of arguments on apply is not consistently implemented across browsers and it fails on some arbitrary limit. 
Thanks for reporting the issue.
Could you provide your dev env info so we can test after we made the fix?

**Comment by ibgreen** [comment]
@heshan0131 fyi

**Comment by ibgreen** [comment]
Fixed on master. Will be published in patch release soon.
