### ISSUE TITLE
Invalid prop `viewport` of type `OrbitViewport` supplied to `DeckGL`

### ISSUE THREAD

**Issue by dazhi1011** [uber/deck.gl#795]
when I run the 'deck.gl-4.1.0-beta.6\examples\plot' example,there is an error like this:
**## "Failed prop type: Invalid prop `viewport` of type `OrbitViewport` supplied to `DeckGL`, expected instance of `Viewport`."**
but the `OrbitViewport` is extended from `Viewport`... any suggestions here?

**Comment by shaojingli** [comment]
For some reason, the `OrbitViewport` is not recognized as a subclass of `Viewport` when running from the transpiled deck.gl. This shows up only when using `npm run start`, NOT when using `npm run start-local`. Any ideas, @Pessimistress ?

**Comment by shaojingli** [comment]
This is due to we import `OrbitViewport` directly from `deck.gl/dist` and can be resolved by importing it from `deck.gl/dist-es6` instead. This is a quick fix and will break this example on older browsers. Eventually, we should export the `OrbitViewport`.

**Comment by dazhi1011** [comment]
thx,fix it by changing the import path. @shaojingli
