### ISSUE TITLE
s2layer sample not working

### ISSUE THREAD

**Issue by minhdanh** [uber/deck.gl#800]
I start the examples on my machine. All the layers display on the map when I click on that layer in the layer browser, except for s2Layer. It doesn't show anything. Is this a bug or something?
Here is the screen shot:

![screenshot 2017-07-21 11 59 22](https://user-images.githubusercontent.com/4865412/28449712-47809a08-6e0c-11e7-8040-19e6cbea167f.png)

**Comment by 1chandu** [comment]
Fixed by #869

**Comment by minhdanh** [comment]
Thank you
