### ISSUE TITLE
Dev guide: enable64bitSupport when subclassing a layer

### ISSUE THREAD

**Issue by rivulet-zhang** [uber/deck.gl#803]
Hi, I am trying to subclass a layer in deck.gl and have a question about the 64bit layer support. Basically, I have two vertex shader files (one regular and one 64bit) that I would use to override the existing ones.  The user can flag `fp64` attribute to toggle on or off the 64 bit feature. In the implementation of core layers, the function `enable64bitSupport` is used to check the flag. However, this function does not seem to be exported in deck.gl so I am not able to use it when developing a standalone program. I could grab the function and add it to my repo, but not sure if it is the best way to do it. Any thought or suggestion on this?

**Comment by shaojingli** [comment]
@rivulet-zhang you can just copy and paste the `enable64bitSupport` function for now...

**Comment by rivulet-zhang** [comment]
@shaojingli I see. Thanks!
