### ISSUE TITLE
export 'setParameters' was not found in 'luma.gl' in point-cloud-ply example

### ISSUE THREAD

**Issue by siddharth1024** [uber/deck.gl#808]
I'm trying to run point-cloud-ply example and getting a blank page, console shows two errors,

```
Uncaught TypeError: __webpack_require__.i(...) is not a function
"export 'setParameters' was not found in 'luma.gl',
```
I've tried installing other versions of luma.gl (4.0.0 alpha), however it says DeckGL v4 requires peer version of Luma 3.0.0.

I'm on Windows 10 64-bit, Node v6.10.0, npm v3.10.10.

**Comment by siddharth1024** [comment]
I fixed the problem by changing Peer Dependency of DeckGL (Luma) from 3.0.0 to 4.0.0-beta.6.

```
"peerDependencies": {
    "luma.gl": "**4.0.0-beta.6**",
  ...
},
```

Seems like a hack, any proper solution?

**Comment by shaojingli** [comment]
@siddharth1024 . Not it's not a hack :) so luma.gl v4 has some different APIs with luma.gl v3.

I'll make sure all our examples has correct dependencies.
