### ISSUE TITLE
How to create/show info box on hover/click

### ISSUE THREAD

**Issue by SikFar** [uber/deck.gl#819]
Hi,

On [https://uber.github.io/deck.gl/#/examples/core-layers/icon-layer] you guys showing a info box when hovered or clicked, the code for that functionality is not in the repo..

Ty!

**Comment by ralphstodomingo** [comment]
It's in https://github.com/uber/deck.gl/blob/master/website/src/components/demos/icon-demo.js. The examples provide minimal standalone functionality.
