### ISSUE TITLE
Trips is always displaying Newyork map irrespective of data 

### ISSUE THREAD

**Issue by khajaasmath786** [uber/deck.gl#820]
I am trying to display the trips of our data using deck.gl. With the examples mentioned for Trips, I have modified app.js with example data of my GitHub as shown below. 

// Source data CSV
const DATA_URL = {
TRIPS: 'https://github.com/khajaasmath786/deck.gl-data/tree/master/examples/trips/occ.json'
};

if you see occ.json, co-ordinates represent the data from Denver but the data is not displayed instead map of newyork.  is there anything wrong with my data or changes made in app.js?

**Comment by gnavvy** [comment]
Hi @khajaasmath786 

Could you check if you have changed the initial map position? the default LngLat is pointing to New York.
https://github.com/uber/deck.gl/blob/master/examples/trips/deckgl-overlay.js#L19-L20

**Comment by khajaasmath786** [comment]
Thanks for responding. I havent done any changes. for me too work with data
that I have, can I comment it out or should I include any more changes?

It should automatically pick up the location but not the default one always.

**Comment by ibgreen** [comment]
This is by design. The map state needs to be initialized to the correct location.

Auto inferring position from data is a nice idea, but not quite clear how to do it given the separation between the underlying map component and the visualization.
