### ISSUE TITLE
Hexagon Layer, how to make hexagon height value based

### ISSUE THREAD

**Issue by SikFar** [uber/deck.gl#829]
Is it possible to make the height of the hexagon in hexagon layer be value based and not as the doc says:

> The color and height of the hexagon is scaled by number of points it contains

Ty!

**Comment by Pessimistress** [comment]
@SikFar The HexagonLayer generates a [HexagonCellLayer](https://github.com/uber/deck.gl/blob/4.1-release/docs/layers/hexagon-cell-layer.md) under the hood. HexagonCellLayer has a `getElevation` accessor with which you can use your own value. You can check the source of HexagonLayer or examples/layer-browser for usage examples.

**Comment by SikFar** [comment]
Cool thanks, would it be to much to ask for specification? 😄 Do I override the `getSubLayerClass ` method?

**Comment by heshan0131** [comment]
Hi @SikFar 
You can subClassing `HexagonLayer` and override the `_onGetSublayerElevation` method with your own. This method takes each cell `{centroid: [], points: []. index}` as input , and returns the elevation. Note the `points: []` is the array of data points that contained by each cell. You can use these array of points to calculate your own elevation.
