### ISSUE TITLE
"View Code" links on the deck.gl site are broken

### ISSUE THREAD

**Issue by williamge** [uber/deck.gl#832]
Take https://uber.github.io/deck.gl/#/examples/custom-layers/trip-routes for example, click the View Code button and it'll take you to :

https://github.com/uber/deck.gl/tree/4.0-release/examples/trips 

which doesn't work, the '4.0-release' branch doesn't exist anymore

Both of these links do work instead: 

https://github.com/uber/deck.gl/tree/4.1-release/examples/trips
https://github.com/uber/deck.gl/tree/master/examples/trips

**Comment by shaojingli** [comment]
The link to source code in our examples should point to source of 4.1-release branch.

However, anyone has an idea why 4.0-release branch is deleted?

@ibgreen @Pessimistress @1chandu

**Comment by shaojingli** [comment]
restored the 4.0-release branch. will update the link.

**Comment by ibgreen** [comment]
@Pessimistress @shaojingli the docs still point to 4.0 example code.

**Comment by ibgreen** [comment]
Being addressed, final step tracked in #855.
