### ISSUE TITLE
HexagonCellLayer documentation refers to a seemingly non-existent getRadius(d) method

### ISSUE THREAD

**Issue by kforeman** [uber/deck.gl#840]
The [coverage section](https://github.com/uber/deck.gl/blob/f132d93e01c497ccab79a7981de73a6a628ee509/docs/layers/hexagon-cell-layer.md#coverage-number-optional) of the `HexagonCellLayer` documentation states that
```
The radius of hexagon is calculated by `coverage * getRadius(d)`
```
but as best I can tell it's simply `coverage * radius`.

It'd be very nice to have a hexagon-specific radius so that you could have e.g. radius represent counts and color represent rates (for instance to not give too much visual weight to sparsely populated areas) like `ScatterplotLayer` provides. 

Is the documentation incorrect, is there work in that direction off on another branch, or am I just wrong and misreading things? Thanks!

**Comment by heshan0131** [comment]
You are right. It is a typo, `radius` is calculated by `coverage * radius`
We currently don't have plans to support getRadius. Have you thought about subclassing the hexagon layer and add another attributes?

**Comment by ibgreen** [comment]
@shaojingli we have a doc bug, would be good to get a PR up asap.
