### ISSUE TITLE
Mouse pointer movement not registered when moving too fast

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#847]
Steps to repro :
- Apply changes from #839
- In layer-browser, select Scatterplot layer , enable autoHighlight prop, zoom or pan, so one circle instance is partially clipped by border, move the mouse pointer slowly from with in this circle to outside of the canvas, you can see highlighting is disabled when mouse pointer moves away, repeat the same, but this time move the mouse fast, you can see highlighting is still on even after mouse pointer is outside of the canvas.

**Comment by ibgreen** [comment]
@1chandu can you describe which browser events we are currently handling? How do we track mouse leaving the canvas?

**Comment by Pessimistress** [comment]
This is because we do not handle the `mouseleave` event on the canvas. If the `mousemove` event doesn't fire while the mouse is over the void (due to frame rate), no more onHover is triggered.
I am adding a `mouseleave`/`pointerleave` event to the EventManager.
