### ISSUE TITLE
Merge documentation cleanup, example fixes to 4.1-release and republish docs

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#855]
Cherry-pick following PRs to 4.1-release
#854 - e48b903 (already ported to 4.1)
#850 - f77cd2e (already ported to 4.1)
#869 - d82b8a8
#868 - 799c9c8
#870 - bf9b294
#874 - 3d1dd14 (Layer.parameters: Update docs and forward in GeojsonLayer)
#875 - 75c36aa
#879  - 0cff977
#876 - e7b9368
#884 - a92f7ab

**Comment by shaojingli** [comment]
I guess we only need to republish the website. I'll do it

**Comment by ibgreen** [comment]
There are documentation changes on master that relate to new features that are not in 4.1.

E.g. @1chandu just landed doc changes relating to the new auto highlighting props.
