### ISSUE TITLE
adding getColorValue function prevents columns from rendering

### ISSUE THREAD

**Issue by ralexrdz** [uber/deck.gl#856]
Hello!

I'm using a the 3d heat map example with hexagon layers, using version 4.0.6
besides positions, my data has a value called "price".

When everything default, data shows normally asigning elevation and color depending on points.length

I would like to select the color of the columns depending on the **average** of "prices" of the points on each hexagon. so I added a getColorValue to calculate this average

```
getColorValue(points){
    let count = points.length;
    let sum=0;
    points.forEach(function(point){
      sum+=point.price;
    })
    let avg = res / count
    console.log ('average', avg)
    return avg.
};
```

When adding this, **none** of the columns appear

when printing averages, I realize they never go more than 1000

so I added this property: colorDomain: [0,1000]

Still nothing appears. I don't know how to debug this. Any recomendations?

**Comment by shaojingli** [comment]
@heshan0131

**Comment by heshan0131** [comment]
the `getColorValue` in hexagon layer should work. I just tested it. What's your output of  `console.log ('average', avg)`?

Are you using your own `hexagonAggregator` function or the default.

in the `hexagon-layer.js` `getValueDomain` method you can also call `console.log(this.state.valueDomain)`
at the end of the function to see if the auto calculated `colorDomain` looks correct.

**Comment by ralexrdz** [comment]
We realize there was no getValueDomain in v.4.0.6 upgrade to v.4.1 and now it works. I think it was just a version problem
