### ISSUE TITLE
react-native port

### ISSUE THREAD

**Issue by minessis** [uber/deck.gl#880]
Any plan to provide this library for react-native?

**Comment by shaojingli** [comment]
@minessis this is a very interesting. Yes, we are thinking about how mobile platforms could be better supported. Right now, the best way is to run it in a web view and use WebGL on mobile Safari / Chrome. 

ReactNative itself won't automatically handle WebGL and some significant work might be necessary to wire native OpenGL to other parts of deck.gl.

**Comment by rullymartanto** [comment]
any news on this?

**Comment by ruymon** [comment]
Any updates?
