### ISSUE TITLE
How to properly implement tooltips?

### ISSUE THREAD

**Issue by TPreece101** [uber/deck.gl#883]
Hi,
I must sat that I love the deck.gl library and the layers are so beautiful but I am having a little bit of a problem at the moment and I was hoping that you could help me out? I am struggling to implement tooltips on a hexagon layer map, I am attempting to use the `<Popup>` component from `react-map-gl` , I have got it to appear and show the relevant data on the popup and have got it to move around by updating the position and the text in the `onHover` function but I am struggling to get it to disappear properly. Is there some kind of 'mouseout' event somewhere that I can use? The other idea I've had is putting in an invisible layer of some sort so that I can use the `onHover` function from that to hide the tooltip. There must be a better way to do this and I see that you have tooltips working properly on your examples in the gallery just not in the examples that we can see the code for. I was wondering if you could possibly point me in the right direction?
Best wishes
Tom

**Comment by heshan0131** [comment]
Hi @TPreece101 glad you are liking our library and layers.
Here is the [heatmap code ](https://github.com/uber/deck.gl/blob/master/website/src/components/demos/heatmap-demo.js#L78-L96) that we show in the gallery. in your `onHover(info)` function You can either check `info.object` or `info.picked`, if nothing is picked, you hide the tooltip.

**Comment by TPreece101** [comment]
Thank you so much for pointing me towards the heatmap code, I had not realized that code was available! After seeing that I had it up and running in a matter of minutes. Thank you for such a quick response.

**Comment by alldoami** [comment]
Is there a way to enable onHover(info) and show info.object within Superset? @heshan0131
