### ISSUE TITLE
picking/highlighting remaining work

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#890]
- [x] Move picking module back to luma, verify any compatibility issues. (run instancing app for highlighting.)
- [x] Mark old picking uniforms as deprecated.
- [x] Update any deck.gl examples to use picking module instead of custom picking.

**Comment by 1chandu** [comment]
Bumping to P1, this has been delayed for long time already, we should finish it and let deck.gl depend on luma's picking module, it gets complicated as we plan to refactor shader module and lot or refactoring happening in picking flow.

**Comment by shaojingli** [comment]
Yes @1chandu please do. Thanks for keeping track of it

**Comment by 1chandu** [comment]
Reaming work is completed in https://github.com/uber/deck.gl/pull/1045
