### ISSUE TITLE
mapbox tile as a datasource

### ISSUE THREAD

**Issue by williaster** [uber/deck.gl#905]
Is it possible to use data from mapbox tiles directly as a datasource for a component layer?

This would be really nice for things like buildings or enterprise boundaries that are already part of the tiles. e.g., for buildings, from the [mapbox docs](https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/) you can simply reference the `building` source layer:

```javascript
map.addLayer({
  'id': '3d-buildings',
  'source': 'composite',
  'source-layer': 'building',
  'filter': ['==', 'extrude', 'true'],
  'type': 'fill-extrusion',
  'minzoom': 15,
  'paint': {
    'fill-extrusion-color': '#aaa',
    'fill-extrusion-height': {
        'type': 'identity',
        'property': 'height'
    },
    'fill-extrusion-base': {
        'type': 'identity',
        'property': 'min_height'
    },
    'fill-extrusion-opacity': .6
  }
});
```

**Comment by ibgreen** [comment]
@williaster Creating a layer that reads map tiles is an interesting idea, but there hasn't been any work on it. 

You can of course set such extruded map styles on the underlying map (e.g. layering deck.gl on top of react-map-gl), but mapbox and deck.gl will use different Z-buffers so it doesn't work well for extruded map layers.

**Comment by Harrisandwich** [comment]
@cyrilchapon , @williaster 

Not sure if either of you are still thinking about this, but for anyone else who ends up here looking for an answer to this question:

It looks like there's an experiment TileLayer available
https://github.com/uber/deck.gl/blob/master/modules/experimental-layers/src/tile-layer/tile-layer.md

I haven't tried it yet, but it looks like it fits pretty much perfectly with what I need. Hope it helps

**Comment by HeiYanjing** [comment]
@williaster Hi, deck.gl support add mapbox layer now.
#3316 ,I tried . but have some error. 
could you help  me take a look ?

**Comment by HeiYanjing** [comment]
@williaster   #3329  ,not #3316
