### ISSUE TITLE
Previous layer as pixel shader input (render to texture)

### ISSUE THREAD

**Issue by bjornreppen** [uber/deck.gl#908]
I'm experimenting with creating real-time visualizations of user defined queries in the area of biodiversity on maps.

A couple of trivial use case examples:
 - Display shark observations at maximum 1km from coast 
 - Display observations of chaparral @ <400m ASL

Would it be possible to have the first layer render to a texture (ie. the < 1km to coast or <400m ASL) and then from the second layer sample the previous layer texture in the pixel shader in order to for example colorize the pixels differently if they satisfied the query (were shaded or discarded) by the previous layer? 

Enjoyed your talk at Siggraph.  Thank you so much for sharing!

**Comment by ibgreen** [comment]
> Would it be possible to have the first layer render to a texture

@bjoprnreppen Yes this is a great idea with a lot of interesting applications. We have been playing with this idea from time to time, but have not started on any implementation yet. 

One piece of good news is that "improved visuals/visual effects" is one of our focus areas for deck.gl 5.0 is so this feature would fit well with that theme. 

I will add a call for an RFC on this topic to the [5.0 plans](https://github.com/uber/deck.gl/tree/master/dev-docs/RFCs).

**Comment by ibgreen** [comment]
<img width="1062" alt="screen shot 2017-09-06 at 11 54 13 am" src="https://user-images.githubusercontent.com/7025232/30129217-2174efe0-92fa-11e7-80fa-4601928f8978.png">

Added
