### ISSUE TITLE
Test deck.gl with React 16

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#917]
We need to do some testing with React 16. 
* We already know we need to replace string refs with functions.
* We should make our React dependencies in package.json more generous to permit React 16
* I also wanted to merge the example that [supports JSX syntax for layers](https://github.com/uber/deck.gl/tree/master/examples/jsx-layers) into the main react component, but first wanted to make sure that it still works for React 16.

**Comment by 1chandu** [comment]
As part of API AUDIT we decided to skip this for 5.0 release, moving to 6.0.

**Comment by ibgreen** [comment]
This was addressed in 5.0
