### ISSUE TITLE
Autohighlighting does not work on multimodel layers

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#918]
Update: The statements causing crash are now wrapped in `if (layer.state.model)` conditions, meaning that this code no longer crashes but silently fails for multi-model layers. Autohighlighting for such layers is a narrow use case so lowering priority of this.

<img width="409" alt="screen shot 2017-09-06 at 3 01 24 pm" src="https://user-images.githubusercontent.com/7025232/30136565-63c5664e-9314-11e7-8911-24aec1d100e8.png">

Autohighlighting assumes that a layer has a single model. This crashes for layers that have multiple models. We may need a new `Layer` callback.

**Comment by 1chandu** [comment]
Do we have any layer that has multiple models that I can work with?
`state.model` is used in several places of `Layer` and `LayerManager` classes, we should make sure those are all covered for layers with multiple models.

**Comment by ibgreen** [comment]
I believe that the [axis layer in the plot example](https://github.com/uber/deck.gl/blob/master/examples/plot/plot-layer/axes-layer.js#L109) has multiple models. 

It is not exactly a layer that needs auto highlighting, but should work for debugging purposes.

**Comment by Pessimistress** [comment]
In the past we just leave multi-model layers on their own (e.g. the default `draw` method)

**Comment by ibgreen** [comment]
Update: The statements causing crash are now wrapped in if (layer.state.model) conditions, meaning that this code no longer crashes but silently fails for multi-model layers. Autohighlighting for such layers is a narrow use case so lowering priority of this.
