### ISSUE TITLE
Can't get 3d-heatmap example to compile

### ISSUE THREAD

**Issue by benheb** [uber/deck.gl#919]
I followed this readme here: https://github.com/uber/deck.gl/tree/4.1-release/examples/3d-heatmap

When I run `npm start` or `npm run start-local` the browser opens but is blank, and I get an insane list of errors of unfound modules: 

<img width="1181" alt="1__open" src="https://user-images.githubusercontent.com/910495/30143521-71b30e9e-9343-11e7-8e8d-192099b78ff1.png">

<img width="1174" alt="1__open" src="https://user-images.githubusercontent.com/910495/30143482-45fd21b8-9343-11e7-94dd-800db2415932.png">

I've run `npm install`, and `react-map-gl` exists in my node_modules directory, so I'm not sure where the missing link is. Any thoughts? I've tried with node version 6.9.1 and 8.3.0.

**Comment by ibgreen** [comment]
@benheb 

A few pieces of info that might help you: 
* `npm start` is the simpler option. It builds against the official release of deck.gl that you install in the example directory.
* `npm run start-local` builds against the local tree on master. It requires installing not only the example but also in the root deck.gl folder. Not installing in the root is likely the cause of the error cascade we see in your screenshots.  In addition it picks up code from master that is in development, so slightly more likely to have issues.

FWIW, I just pulled latest master, installed using yarn, under Node 7.9 and ran the 3d-heatmap example successfully both using start and start-local.

**Comment by benheb** [comment]
@ibgreen k, I just started fresh and everything seems to work. Looking forward to playing around in here, thanks!
