### ISSUE TITLE
extrusions

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#92]
Not so much an issue, more of a discussion.

Mapbox GL JS just landed support for rendering extrusions, which means 3d buildings are a thing.

https://github.com/mapbox/mapbox-gl-style-spec/issues/456
https://github.com/mapbox/mapbox-gl-style-spec/pull/495

![image](https://cloud.githubusercontent.com/assets/425716/19210210/b5204982-8ce9-11e6-9bf8-000966f231f3.png)
![image](https://cloud.githubusercontent.com/assets/425716/19210213/c1af3b36-8ce9-11e6-9dc6-185590616b96.png)

I guess my question is, how is deck.gl going to work with this if its just a layer rendered over the map?

**Comment by vicapow** [comment]
wow... those look beautiful! and good question. It's possible Deck.GL could eventually become a MapboxGL plugin / custom layer using some of the new APIs that are in progress. see: https://github.com/mapbox/mapbox-gl-js/issues/281

**Comment by contra** [comment]
FYI - this feature landed and is now in the newest release of mapbox-gl-js

**Comment by ibgreen** [comment]
Unless mapbox publishes a plugin that shares their WebGL context we won't be able to integrate with their perspective graphics. Mapbox' current plugin focus is on their new canvas styles, however while these do support interleaving of flat graphics, they do not allow coordination of the z buffer.

**Comment by contra** [comment]
@ibgreen Have you opened an issue on their repo about it? It takes them a really long time to get the ball rolling so it might be worth opening that now and hope it's done in a year.

**Comment by ibgreen** [comment]
@contra Yep. We've also had face-to-face meetings with their engineers.

**Comment by pr1ntr** [comment]
has anything happened with this? Would be nice to be able to render deck.gl layers under the buildings.

**Comment by ibgreen** [comment]
> has anything happened with this? Would be nice to be able to render deck.gl layers under the buildings.

Yes, mapbox has a custom API on a dev branch, we have started to experiment with it. Tracked in #2132
