### ISSUE TITLE
queryObject: ids of composite layers cannot be used for layerIds parameter

### ISSUE THREAD

**Issue by ralphstodomingo** [uber/deck.gl#920]
I happened to be using `queryObject` for this particular event handler:
```
const pickInfo = this.deckGLInstance.queryObject({
   x: event.clientX,
   y: event.clientY,
   // to make sure this handler only applies to overlays...
   layerIds: this.state.overlays.map((o) => `geojson-layer-${o.properties.overlay_id}`),
 });
```
and `pickInfo` always returned a null value. I had a hunch that this was because I was using a `GeoJsonLayer`, which had sublayers with the same name as the parent layer except '-polygon-fill' etc. appended in the end.
I tried to put that as `layerIds: ['geojson-layer-1-polygon-fill']`, to confirm, and sure enough, the polygons in the layer were picked.

**Comment by ibgreen** [comment]
@ralphstodomingo - Yes. Looks like you have found a bug, or at least a weakness in our API. It seems reasonable to expect `queryObject` to include composite layer hierarchies when selecting pickable layers by id.

We should fix this and clarify in the docs.

Until then, as a workaround you'll need to manually list the names of the generated layers, as you have found out they are just formed by appending suffixes.

@Pessimistress @1chandu
