### ISSUE TITLE
HexagonLayer hexagons' z-indexes are wrong / reversed after swapping out React for Inferno

### ISSUE THREAD

**Issue by TedDriggs** [uber/deck.gl#928]
I wouldn't normally expect a library to 'just work' after replacing something as fundamental as React, but the bug I hit actually seems orthogonal to the virtual DOM tool chosen.

# Repro Steps
1. Install all required packages for deck.gl with react-mapbox-gl
1. Add `inferno` and its respective dependencies, and alias them to use `inferno-compat` via webpack
1. Render!

# Observed
![screen shot 2017-09-12 at 4 13 52 pm](https://user-images.githubusercontent.com/4805575/30352591-99a86a16-97d5-11e7-9fbc-edbbbafaf7b6.png)

# Expected
![screen shot 2017-09-12 at 4 16 39 pm](https://user-images.githubusercontent.com/4805575/30352628-d063e440-97d5-11e7-92d3-ce6e69aa4cb2.png)

Here's the code that creates the layer:

```typescript
new HexagonLayer({
                id: 'data-layer',
                data,
                radius: 200,
                extruded: true,
                elevationRange: [0, 1000],
                opacity: 0.8,
                elevationScale: 4,
                coverage: 1,
            })
```

I did notice something odd, which was that `extruded` had to be explicitly set despite the docs claiming it defaults to `true` for this layer type. I wonder if there's a difference in how default props are assessed?

**Comment by ibgreen** [comment]
@TedDriggs - another thing that has failed is enabling of depth testing (z buffer). Either you might not have copied that code from the original example, or Inferno fails to call [onWebGLInitialized](https://github.com/uber/deck.gl/blob/master/src/react/deckgl.js#L147).

Hard to say for sure, but does indeed appear like React property values fail to be set. Most of deck.gl's React integration is in the linked source file so putting some breakpoints in there should help narrow it down.

If you are willing to open a PR with your example (maybe in `examples/integrations/inferno` we might be able to take a quick look as well.

**Comment by TedDriggs** [comment]
@ibgreen Throwing a breakpoint in there, I'm seeing that `props.onWebGLInitialized` exists and has its default value of `noop`. Looking at the example, I can't find anywhere that's passing any function to that, but it's definitely possible I'm missing something.

**Comment by ibgreen** [comment]
@TedDriggs Most of our examples will have some code like this:
```
  _initialize(gl) {
    gl.enable(gl.DEPTH_TEST);
    gl.depthFunc(gl.LEQUAL);
  }

  render() {
    return <DeckGL {...viewport} layers={layers} onWebGLInitialized={this._initialize} />;
  }
```

**Comment by colinsheppard** [comment]
I'm experiencing a similar problem, almost like the rendering uses elevation to decide which hexes to draw on top instead of distance from viewer:

![image](https://user-images.githubusercontent.com/333206/31033768-3284ebb8-a516-11e7-8077-f53d37823ac0.png)

**Comment by ibgreen** [comment]
@TedDriggs @colinsheppard Please check the following two lines

https://github.com/uber/deck.gl/blob/4.1-release/examples/3d-heatmap/deckgl-overlay.js#L100

https://github.com/uber/deck.gl/blob/4.1-release/examples/3d-heatmap/deckgl-overlay.js#L131

**Comment by colinsheppard** [comment]
That's it, thanks @ibgreen!

![image](https://user-images.githubusercontent.com/333206/31035767-1408d840-a51e-11e7-91d9-ac7444a9e329.png)
