### ISSUE TITLE
Viewport: View Matrix Decomposition support

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#940]
Ref: https://github.com/uber/deck.gl/pull/939/files

-Extract traditional camera parameters from any Viewport? We have the `viewMatrix`, which can be decomposed using standard 4x4 matrix techniques.

-Possible methods:
 -* `WebMercatorViewport.getCameraPosition`		
 -* `WebMercatorViewport.getCameraLookAt`		
 -* `WebMercatorViewport.getCameraUp`		
 -* `WebMercatorViewport.getFov`		
 -* `WebMercatorViewport.getClippingPlanes` -> [near, far]

**Comment by ibgreen** [comment]
This should be moved to math.gl
