### ISSUE TITLE
Streaming csv/json

### ISSUE THREAD

**Issue by ek-nath** [uber/deck.gl#941]
Referring to the 3d-heatmap example, would it possible to provide a streaming json/csv source in this location: 
<pre><code>requestCsv(DATA_URL, (error, response) => {
        if (!error) {
          const data = response.map(d => ([Number(d.lng), Number(d.lat)]));
          this.setState({data});
        }
      });
</code></pre>

**Comment by ibgreen** [comment]
> Referring to the 3d-heatmap example, would it possible to provide a streaming json/csv source in this location:

deck.gl has no streaming facilities but can integrate with most API's, simply rerender the layer with new data as it comes in.

Hard to advice you more without context about the "streaming" source? 
* Do you have a streaming API in mind, or are you asking a more basic question about what browser APIs to use for streaming, etc? 
* Do you have a big data that you want to load gradually and display partially as it data comes in? Or do you want to update with completely new heatmaps?

**Comment by ek-nath** [comment]
@ibgreen sorry for not updating this earlier. I had my notifications turned off :(
I have an elasticsearch server that gets constantly updated and I am trying to live visualize the incoming stream of lat-long data there.

**Comment by florinvirdol** [comment]
@ek-nath did you manage to visualize the ElasticSearch incoming stream of lat & long data in deck.gl?
