### ISSUE TITLE
feasibility check

### ISSUE THREAD

**Issue by dleitner100** [uber/deck.gl#945]
Hey!
I'm a student and I would like to use deck.gl for a project at university. I wanted to ask you first if you think that it's possible to visualize public transport data of a city (real time json) using deck.gl?
Thanks for you answers!

**Comment by ibgreen** [comment]
>  I wanted to ask you first if you think that it's possible to visualize public transport data of a city (real time json) using deck.gl?

@dleitner100 While it is always risky to say yes without understanding all requirements, as you can probably imagine, we build such applications on top of deck.gl.

The amount of effort would depend on your expectations (e.g. while you can get very far with the standard layers, pixel perfect real time animation/interpolation of say tens of thousands of vehicles, while possible, would almost certainly require customized layers and some shader programming).

Also deck.gl doesn't help you with the data streaming parts, just the visualization.
