### ISSUE TITLE
MapboxAccessToken

### ISSUE THREAD

**Issue by dleitner100** [uber/deck.gl#949]
I am trying to get the heatmap example running on my windows machine but I got stuck when I'm trying to export the Mapboxtoken.
It seems that the export command is not working in windows command line.

Is there a workaround to export the token on Windows?

**Comment by ibgreen** [comment]
> Is there a workaround to export the token on Windows?

@dleitner100 You'd have to consult the webpack documentation to see if `webpack.EnvironmentPlugin` supports Windows. 

You can always copy your token into the [code](https://github.com/uber/deck.gl/blob/master/examples/3d-heatmap/app.js#L10).
