### ISSUE TITLE
3.x npm publishes not runnable

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#95]
Not sure if you were aware, but all of the 3.x releases on npm were published without a `dist` folder so they don't run (error finding dist/index.js).

**Comment by ibgreen** [comment]
@contra - this is very strange - we are using these in multiple internal apps without issue, the `dist` folder seems to be there just as it should. Also `dist` is still mentioned in the files section in [package.json](https://github.com/uber/deck.gl/blob/dev/package.json#L18).

Wonder if it is possible to check the contents of a published module on npmjs.com?

Could it be an `npm cache clean` issue?

**Comment by contra** [comment]
Yeah, seems like it was a cache issue from having beta 16 installed which didn't have a dist folder. Weird behavior on npms part. Sorry about the ticket, my bad.
