### ISSUE TITLE
`updateTriggers` broken when using default accessors

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#950]
The following layer:
```
new ScatterplotLayer({
      data,
      updateTriggers: {
          getColor: color
      }
})
```
Is not updated when `color` changes. This is caused by the default `shouldUpdateState` implementation:
```
    return changeFlags.propsOrDataChanged;
```
which does not reflect `updateTriggers` change. The current examples work because they are using inline accessors, which counts towards a prop change.

@ibgreen

**Comment by ibgreen** [comment]
> which does not reflect updateTriggers change.

Do we know why? Is [`_diffUpdateTriggers`](https://github.com/uber/deck.gl/blob/master/src/lib/layer.js#L503) not being called?

**Comment by Pessimistress** [comment]
> Do we know why? Is [`_diffUpdateTriggers`](https://github.com/uber/deck.gl/blob/master/src/lib/layer.js#L503) not being called?`_diffUpdateTrigger` is called, but because `shouldUpdateState`, `attributeManager.update()` is not called to recalculate the invalidated attribute.

**Comment by ibgreen** [comment]
> because shouldUpdateState returns false, attributeManager.update() is not called to recalculate the invalidated attribute.

* Perhaps we should just bypass `shouldUpdateState` for `updateTriggers`? The user has already been explicit about what should be updated.
* My first assumption was that `changeFlags.propsOrDataChanged` should be true if `updateTriggers` fired. But maybe that would cause more updates than we want?

Whatever we decide it might be good to update the docs, including the new article on "Updates".

**Comment by ibgreen** [comment]
@1chandu - strongly suspect this is also broken in the release version
