### ISSUE TITLE
GridLayer clipping issue

### ISSUE THREAD

**Issue by martennilsson** [uber/deck.gl#967]
Do you have any idea why I get this issue with GridLayer?
![sep -29-2017 17-04-35](https://user-images.githubusercontent.com/21829/31022316-ae1c0d66-a538-11e7-8569-9e195c2f6c45.gif)

**Comment by ibgreen** [comment]
@martennilsson Looks like depth testing is not enabled. If you check the examples they usually set `depthTest: true` in an initialization callback.

We plan to make `depthTest: true` default in the next major release, but for now this step is still needed for extruded layers.

**Comment by martennilsson** [comment]
Thanks! Didn't see that.
