### ISSUE TITLE
Realtime Update for PathLayer

### ISSUE THREAD

**Issue by freddie-ai** [uber/deck.gl#974]
How should a path on the `PathLayer` data attribute be updated and force the layer to update?

Any help would be really appreciated!

**Comment by freddie-ai** [comment]
I think I may have worked it out. Will post solution once I've confirmed.

**Comment by Pessimistress** [comment]
@freddie-ai Checkout the documentation for [`updateTriggers`](https://uber.github.io/deck.gl/#/documentation/api-reference/layer?section=data-properties)

**Comment by freddie-ai** [comment]
I've been using `dataComparator` where I pass in a function that tells the layer to update if the path data length has changed.

I feel as if I should be using the `getPath` data accessor with `updateTriggers`, but I'm not sure how...

Sorry to be a pain -- not done much graphics stuff before!

**Comment by ibgreen** [comment]
@freddie-ai deck.gl currently doesn't have support for only updating a single element in a data array.

The updateTriggers allow you specify when a certain accessor, such as `getColor` needs to be called again on *all* objects. That is usually significantly cheaper than regenerating all geometry and vertex attributes.

But getPath essentially modifies the geometry (number of vertices) which requires a full geometry rebuild so you might as well use a dataComparator.

For perf the key is that you make sure that `dataComparator` never triggers an update when your object hasn't changed.

**Comment by freddie-ai** [comment]
I see, thanks for explaining.

**Comment by jonenst** [comment]
@ibgreen 
> deck.gl currently doesn't have support for only updating a single element in a data array.

Is this still the case (Dec 2019) ? That is, if you have 1 million elements in a PathLayer, is there a way to have ultrafast performance when changing the position of a single element ?
Thanks in advance.
ps: if not, I guess you have to get the element out of the global Pathlayer into it's own PathLayer and update it there ?
