### ISSUE TITLE
Show message explaining that wind map example doesn't work on safari

### ISSUE THREAD

**Issue by jckr** [uber/deck.gl#975]
(http://philogb.github.io/page/wind/)

https://twitter.com/OBuchel/status/915017337211899905

I get:  
[Error] Unhandled Promise Rejection: Error: createGLContext called on canvas 'texture-canvas' before page was loaded
	(anonymous function) (context.js:53)
	promiseReactionJob

**Comment by ibgreen** [comment]
@jckr - This is unfortunately expected as the wind map is a WebGL2 example, currently only supported by Chrome and Firefox. But the error message needs to be much better.

@1chandu, @shaojingli - We need to make this clear and have a nice message on non-supporting browsers.
