### ISSUE TITLE
Move TextLayer into core layers in deck.gl

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#976]
#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update (check if code and text-layer.md are in sync @gnavvy by 03/09)
  - [x] Whats new update 
  - [x] Testing (move from exp to core folder and then test on rendering-test)

**Comment by ibgreen** [comment]
Just as a clarification: This was moved to experimental-layers as a staging ground for audit and further improvements. It is not yet part of core-layers.

**Comment by rivulet-zhang** [comment]
Thanks @ibgreen It is better to reopen it to track the status and we can safely close it once the text layer is moved to the core layers from the experimental layers. (The text layer has been moved from the example folder to the experimental layers in this PR #1062)

**Comment by rivulet-zhang** [comment]
Just to clarify, the text layer implementation in the `example` folder (`text-layer`, `tagmap`) is still the old version. The new version is only located in the `experimental-layers` for review. Once the new version is reviewed and moved to the core layers, we can just safely delete the old version in the `example` folder.

**Comment by 1chandu** [comment]
@gnavvy 
Teams feedback: This needs to go through teams review and then depending on time we should make into 4.2 or 5.0 release.

**Comment by ibgreen** [comment]
We have started using the `TextLayer` in apps and worked through the initial set of minor bugs, it looks promising. At the point it is mainly an API Audit that is required.

**Comment by gnavvy** [comment]
Will do in the following steps:
- [ ] 1. Move Text-Layer code and doc from experimental-layers to core-layers
- [ ] 2. Publish patch release of deck.gl to have Text-layer exported from deck.gl instead of deck.gl-layers
- [ ] 3. Move Text-layer related examples from experimental to core, update paths accordingly
- [ ] 4. API Audit
- [ ] 5. Publish document on the v5.2 website
