### ISSUE TITLE
v3 - arc layer blowing up

### ISSUE THREAD

**Issue by contra** [uber/deck.gl#98]
Not happening on the dev branch demo, but I'm getting this in a project when rendering an arc layer:

<img width="1111" alt="screen shot 2016-10-11 at 3 28 00 pm" src="https://cloud.githubusercontent.com/assets/425716/19285285/6d9dd206-8fc7-11e6-8550-0984eb051130.png">
<img width="429" alt="screen shot 2016-10-11 at 3 30 50 pm" src="https://cloud.githubusercontent.com/assets/425716/19285380/b9bf46d8-8fc7-11e6-853d-58deb664b784.png">

Happens when the overlay has two layers rendered, then a third layer (the arc layer) is added to the layers prop.

**Comment by ibgreen** [comment]
@contra - As a first step, make sure you take note of the breaking API change in v3. In contrast to v2, deck.gl v3 expects arrays for all positions, colors etc (instead of objects {x,y,z}, {r,g,b} etc.. It also introduces accessors that can help if your data is not organized the right way.

**Comment by contra** [comment]
@ibgreen Ah, wasn't aware of that. Checked the changelog and docs and didn't see any mention of that. I'll give it a try.

**Comment by contra** [comment]
@ibgreen Just to clarify: The API for arcs should be like this?

```js
position: [
  [ x, y, z ],
  [ x, y, z ]
]
```

**Comment by ibgreen** [comment]
@contra 

> Checked the changelog and docs and didn't see any mention of that

Yes I guess you would need to check the CHANGELOG on the dev branch, there is a small note: https://github.com/uber/deck.gl/blob/dev/CHANGELOG.md#300-beta13--

> The API for arcs should be like this?

Per default accessors they should be called sourcePosition and targetPosition.
But by supplying custom accessors you could store them anyway you want.

https://github.com/uber/deck.gl/blob/dev/src/layers/core/arc-layer/arc-layer.js#L118
https://github.com/uber/deck.gl/blob/dev/src/layers/core/arc-layer/arc-layer.js#L27
