### ISSUE TITLE
Multi-model layers are broken on master

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#991]
`draw-layer` and `pick-layer` should never directly access `layer.state.model` (or `layer.state` in general). This makes it impossible for multi-model layers to overwrite the default logic.
https://github.com/uber/deck.gl/blob/master/src/core/lib/pick-layers.js#L127
https://github.com/uber/deck.gl/blob/master/src/core/lib/draw-layers.js#L184
https://github.com/uber/deck.gl/blob/master/src/core/lib/draw-layers.js#L245

We may add a method `Layer.updateModuleSettings` to handle this.

@ibgreen @1chandu

**Comment by ibgreen** [comment]
> draw-layer and pick-layer should never directly access layer.state.model

Agreed. If we are serious about multi model layer support we should probably open a task to create a test case and add a sample multi model layer to the layer browser, if not they will likely break again.

> We may add a method Layer.updateModuleSettings to handle this.

Yes, maybe that is a good way. The `updateModuleSettings` system is definitely ripe for a refactor. It was necessary to get the shader module system off the ground, and I think the basic idea behind it is still good, but it is not exactly easy to explain to a new user how and when it should be called.

**Comment by Pessimistress** [comment]
The PlotLayer example is multi-model. It's not in the layer browser because it's non-geospatial.

**Comment by ibgreen** [comment]
> The PlotLayer example is multi-model. It's not in the layer browser because it's non-geospatial.

Yes good point. Maybe we could add a section in the layer browser for non-geospatial layers, and kill two birds with one stone (i.e. make it easier to test both non-geospatial and multi-model layers).

**Comment by 1chandu** [comment]
@ibgreen @Pessimistress , anything pending on this otherwise please close.
