### ISSUE TITLE
Should user be able to pick things he can't see?

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#994]
In current picking implementation:
- If I have a pickable layer with points, and on top of that I draw a black square that fills the screen that is non-pickable
-  Then I can still pick the points, because the black square is not drawn into the picking buffer (only pickable layers are rendered).
- To fix this visible but non-pickable layers would have to be drawn with all nullPickingColor, so it would require a minor enhancement to the picking module to support that.

**Comment by jianhuang01** [comment]
Good to know that we only render items in pickable layer to picking buffer for now.

**Comment by 1chandu** [comment]
> To fix this visible but non-pickable layers would have to be drawn with all nullPickingColor, so it would require a minor enhancement to the picking module to support that.

Instead of changing the module code, alternatively, we can render all layers to picking buffer (instead of just pickableLayers) and during decode, if the pickedLayer is non pickable (`pickedLyaer.isPickable() is false`), send NULL picking color to consumers. This should be much simpler change not touching the shader module code.

**Comment by ibgreen** [comment]
> alternatively, we can render all layers to picking buffer (instead of just pickableLayers) and during decode, if the pickedLayer is non pickable 

Yes good point, that would work too, I'd be fine with that.

Some observations:
* It would be a little easier to hit the 255 pickable layer limit
* There would be a little more work to filter objects especially when doing `queryVisibleObjects`.
* The picking module is in luma.gl, so solving the problem in JavaScript in deck.gl doesn't solve the identical problem for (hypothetical) luma.gl picking module users.

The above issues are small and not really concerns. That said, the shader change would be small as well, presumably a new boolean uniform that returns the `nullPickingColor` when set.

**Comment by 1chandu** [comment]
@ibgreen   We added 'layerFilter' prop, can this be closed now?

**Comment by ibgreen** [comment]
It is a different issue: We don't draw layers that are not pickable into the picking buffer, but we do draw them into the default renderbuffer. So visually, non-pickable layers can occlude pickable layers, but since non-pickable layers are not drawn during picking, so it is possible to pick things that you can't see.
