### ISSUE TITLE
Add a general non-geospatial layer-browser

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#998]
We need an example similar to layer-browser for non-geospatial layers so that they won't be accidentally broken.

**Comment by ibgreen** [comment]
PR #1210 adds the capability to show the plot layer. Remaining work:

- event handling still doesn't work. Two ways of fixing this could either be support for multiple controllers or an alternate "dual tab" approach.

Also we should add more layers in `COORDINATE_SYSTEM.IDENTITY` mode. At least a PointCloudLayer showing in the `OrbitViewport`.
